### ISSUE TITLE
Error on GetExchangeInfoAsync

### ISSUE THREAD

**Issue by ruudw86** [JKorf/Binance.Net#1001]
When calling the usdtFuturesApi.ExchangeData.GetExchangeInfoAsync() a JsonSerializationException occurs:
Working on latest stable version 8.0.0  Newtonsoft.Json 13.0.1

[2] Deserialize JsonSerializationException: Error setting value to 'ContractType' on 'Binance.Net.Objects.Models.Futures.BinanceFuturesUsdtSymbol'

**Comment by ruudw86** [comment]
Full error:
[full error exchangeinfo.txt](https://github.com/JKorf/Binance.Net/files/8108843/full.error.exchangeinfo.txt)

**Comment by JKorf** [comment]
Thanks for the report. Seems like when a new contract is being listed it doesn't always have a ContractType set yet. I've changed the property to being nullable to fix the deserialization error when this happens.

**Comment by ruudw86** [comment]
Great, thanks a lot
