### ISSUE TITLE
TradeRulesBehaviour.AutoComply not working

### ISSUE THREAD

**Issue by hyperms** [JKorf/Binance.Net#1004]
Hi,
After updating to version 8.0.0 TradeRulesBehaviour.AutoComply does not work and the following error occurs in PlaceOrderAsync:
Precision is over the maximum defined for this asset.

**Comment by JKorf** [comment]
Thanks for the report, I'll fix this in next update.

**Comment by JKorf** [comment]
Hi, you're right. There was an issue with the option not being set correctly. It should be fixed in the latest version.

**Comment by hyperms** [comment]
Thanks
