### ISSUE TITLE
Сrash on BinanceSocketClient.UnsubscribeFromStream(BinanceStreamSubscription)

### ISSUE THREAD

**Issue by Sergey-A-Dvortsov** [JKorf/Binance.Net#101]
When the method is called, the program goes into an infinite wait ... I temporarily solved the problem by changing the code of method to:
  lock (sockets)
            {
                var strm = sockets.FirstOrDefault(s => s.StreamResult.StreamId == streamSubscription.StreamId);
                if(strm != null)
                {
                    strm.Socket.Close().ConfigureAwait(false).GetAwaiter().GetResult();
                    strm.TryReconnect = false;
                }

            }

**Comment by JKorf** [comment]
Hi, thanks for the report. I've just pushed a new version (might take a few minutes to show up) fixing this issue.
