### ISSUE TITLE
Binance Socket Client Not connecting

### ISSUE THREAD

**Issue by devonnell52** [JKorf/Binance.Net#1010]
I am currently trying to link the Binance API to PowerBI through the websocket but for some reason my code keeps giving me errors saying "BinanceSocketClient" could not be found. I want to know if the using directive has maybe changed from a pervious version or if i am simply coding incorrectly for what i want to achieve. I am wanting to link my own Binance account to powerBI in order to pull real time data of my own personal trades as well as store historical data for analysis in the future. My Code is as follows:

using System;
using Binance.Net;
using Binance.Net.Objects;
using CryptoExchange.Net.Authentication;
using CryptoExchange.Net.Logging;
using Newtonsoft.Json;

namespace CryptoTradesPowerBI
{
    class TradeStream
    {

        static HttpClient httpClient = new HttpClient();

        public static void InitiateStream(string binanceAPIKey, string binanceAPISecret, string symbol, string powerBIAPIURL)
        {
            int tradeCount = 0;
            decimal cumulativeQuantity = 0;

            BinanceSocktClient.SetDefaultOptions(new BinanceClientOptions()
            {
                ApiCredentials = new ApiCredentials(binanceAPIKey, binanceAPISecret),
                LogVerbosity = LogVerbosity.None,
                LogWriters = new List { Console.Out },
            }) ;

            var socketClient = new BinanceSocketClient();
            Console.WriteLine("Connecting to Binance Websocket @ " + socketClient.BaseAddress + "\n");

            var successingSingleTicker = socketClient.Spot.SubscribeToTradeUpdates(symbol, data =>
            {
                tradeCount++;
                cumulativeQuantity += data.Quantity;

                var trade = new Trade(symbol, data.TradeTime, tradeCount, cumulativeQuantity, data.Price, data.Quantity);

                var jsonString = JsonConvert.SerializeObject(trade);

                Console.WriteLine(jsonString + "\n");
               
                try
                {
                    var postToPowerBI = PowerBIPostAsync(powerBIAPIURL, "[" + jsonString + "]");
                }
                catch (Exception e)
                {
                    Console.WriteLine(e);
                }
            });

            Console.ReadLine();
        }

        static async Task<HttpResponseMessage> PowerBIPostAsync(string pbiurl, string tradeEvent)
        {
            HttpContent content = new StringContent(tradeEvent);
            HttpResponseMessage response = await httpClient.PostAsync(pbiurl, content);
            response.EnsureSuccessStatusCode();
            return response;
        }
    }
}

**Comment by devonnell52** [comment]
The BinanceSocketClient.SetDefaultOptions keeps on readings errors into my code and i don't know whats wrong

**Comment by devonnell52** [comment]
Also the Binance.Net.Objects.Spot directory doesn't seem to be there anymore.

**Comment by JKorf** [comment]
The latest version has some breaking changes, see here:
https://jkorf.github.io/Binance.Net/MigrationGuide.html
