### ISSUE TITLE
GetBalancesAsync() not working

### ISSUE THREAD

**Issue by redquantum** [JKorf/Binance.Net#1011]
Hello Dear Friend,

This method not working.

 var commonClient= await  user.SpotApi.CommonSpotClient.GetBalancesAsync();

There is no return and no exception.

I use latest version.

Thank you.

**Comment by HypsyNZ** [comment]
https://github.com/JKorf/Binance.Net/issues/1008

**Comment by redquantum** [comment]
Hello
I updated the version " 8.0.6 " but this method still doesn't work. 
Please Help, What is the problem? Thank you.

**Comment by HypsyNZ** [comment]
Can you attempt the request again in debugging mode with logging enabled please

**Comment by redquantum** [comment]
Hi, Thank you for answer.

I'm seeing this Error Message:

 [2] Error received: {"code":-1022,"msg":"Signature for this request is not valid."}

**Comment by redquantum** [comment]
And I'm sure my Key, Secret Key true, because another function working correctly, I'm getting Kline and connecting Socket.

**Comment by HypsyNZ** [comment]
Well the error message isn't wrong so maybe that client isn't inheriting your default options for whatever reason, hard to say.

It seems like the problem is in your implementation somewhere though.

**Comment by JKorf** [comment]
Being able to retrieve klines and connecting the socket client doesn't give any guarentee the credentials are correct. They are publicly available so there is no authorization done on those requests. Try double checking your api key/secret and make sure you set it correctly on the client.

**Comment by redquantum** [comment]
Hello, 

My connection

![baglanti](https://user-images.githubusercontent.com/10393082/156772135-308a0d19-fce9-47d8-b68a-e0c60ebc69ac.jpg)

and my Api confin on Binance

![image](https://user-images.githubusercontent.com/10393082/156772189-9f04b2c8-9df0-4db2-af23-b5e171bd37eb.png)

I think, everything normal..

what do you think?

**Comment by JKorf** [comment]
I don't see anything odd in there. I've tried it locally and it works for me as expected. 
Can you try to call an other authenticated endpoint? For example `await client.SpotApi.Account.GetUserAssetsAsync();`.

**Comment by redquantum** [comment]
I tested this method
var us= await binanceClient.SpotApi.Account.GetUserAssetsAsync();

I'm seeing same error message.

**Comment by redquantum** [comment]
Hello, 
I updated Crypto Exchange again Tonight, thinking you solved the problem, but I ran into a new problem. Now I'm getting this error.

This Method:

var info = await binanceClient.SpotApi.ExchangeData.GetExchangeInfoAsync();

--- Error --- output
Exception thrown: 'System.MissingMethodException' in CryptoExchange.Net.dll

Catch :
Method not found: 'System.Uri CryptoExchange.Net.ExtensionMethods.SetParameters(System.Uri, System.Collections.Generic.SortedDictionary`2<System.String,System.Object>)'.'

Thank you.

**Comment by redquantum** [comment]
Actually GetKline etc. It throws errors in places.

**Comment by JKorf** [comment]
Generally speaking you should just use the CryptoExchange.Net version that's being referenced in the client library. I've yet to update the Binance.Net package for v5.1.4 of CryptoExchange.Net, but will do so shortly. The errors you're now seeing are caused by that.

I'm not sure why you're having issues with authenticated calls. Are you sure you're not mixing up testnet/live credentials? I doubt there is an issue with time or culture, I've seen no reports of that anywhere and all time are in UTC.

**Comment by redquantum** [comment]
Thank you for everything.

I Resolved this problem. 

1.Today Updated Again Binance.net and CryptoExchange.net
2.Createded new API key on Binance

Then everything working.

Thank you for help.
