### ISSUE TITLE
GetMarkPriceKlinesAsync max limit not in sync with Binance API

### ISSUE THREAD

**Issue by Cage-e** [JKorf/Binance.Net#1013]
**Describe the bug**
GetMarkPriceKlinesAsync has a limit of 500 results but the Binance API accepts up to 1500. 

**To Reproduce**
What endpoints and subscriptions are called.

**Expected behavior**
Change the max limit from 500 to 1500 and keep the default value on 500 as expected in the Binance API.

**Debug logging**
Add debug logging related to the issue. Enable Debug logging in the client options by settings LogLevel to Debug.

**Comment by JKorf** [comment]
This has been updated in the latest version

**Comment by JKorf** [comment]
Ah my bad, I fixed it in the Coin futures API, but there was 1 call in the USD futures API which wasn't correct, which of course was the one you're trying to use.
I've fixed it in 8.0.5.

**Comment by Cage-e** [comment]
No worries. Big thanks in the first place for the amazing job.
