### ISSUE TITLE
Updating to version 8

### ISSUE THREAD

**Issue by orionflame** [JKorf/Binance.Net#1015]
Hi,

I updated to v8 of the API but I am getting so many errors with the previous version. I am editing the code to guess the correct functions to use but these ones so far I don't know what I am supposed to use instead:

BinanceClient.Spot.Order.GetOrdersAsync
BinanceClient.Margin.Order.GetMarginAccountOrdersAsync 
BinanceClient.General.GetAccountInfoAsync
BinanceClient.Lending.GetLendingAccountAsync
BinanceClient.Spot.Market.GetKlinesAsync

Thanks a lot in advance.

**Comment by andresdrb** [comment]
The namespaces and classes have been refactored significantly. E.g. BinanceClient.Spot.Order.GetOrdersAsync is now BinanceClient.SpotApi.Trading.GetOrdersAsync. I had to update many things

**Comment by orionflame** [comment]
Thanks a lot that worked for that function, I am trying to find the rest. For Margin there is no MarginApi.

**Comment by andresdrb** [comment]
![image](https://user-images.githubusercontent.com/9131538/155881082-e11687bf-1bbe-4f37-9640-9dd6505c14dd.png)

**Comment by orionflame** [comment]
Oh I see, I will update these. I am surprised they are also under Spot now because I thought Margin was supposed to be separate.

Are these changes from Binance or a tidying effort from this API?

**Comment by orionflame** [comment]
Same for these:
BinanceClient.Spot.UserStream.StartUserStreamAsync ( );
BinanceClient.Margin.UserStream.StartUserStreamAsync ( );

**Comment by andresdrb** [comment]
I think they just tidied few things alongside some changes from Binance

Enviado desde mi iPhone

**Comment by orionflame** [comment]
Same these ones also I can't find any KeepAlive functions:
BinanceClient.Spot.UserStream.KeepAliveUserStreamAsync ( spotListenKey.Result.Data );
BinanceClient.Margin.UserStream.KeepAliveUserStreamAsync ( marginListenKey.Result.Data );

**Comment by orionflame** [comment]
Also KlineInterval.OneMonth is changed to TimeSpan, but I was reading about it, it says 1 month can't be represented easily? Like is it 30 says or 31, 28 etc?

**Comment by GLipitch** [comment]
This works in 8~

```     
        new BinanceClient().SpotApi.ExchangeData.GetKlinesAsync("BTCUSDT", KlineInterval.OneHour);
```

**Comment by orionflame** [comment]
Thanks that works I thought I had to use CommonSpotApi instead of ExchangeData.

**Comment by orionflame** [comment]
OK I managed to update everything.
