### ISSUE TITLE
Cannot get order by clientId

### ISSUE THREAD

**Issue by valerionatangelo** [JKorf/Binance.Net#1016]
I'm quite new to binance.net, so maybe I'm missing something; but I think that not being able to retrieve an order by clientId is a huge problem, since if one cannot get the response of placeOrder (for example because the application crashes or because a network issue), then he will never be able to perform any reconciliation action on that order. To make things worse, GetOpenOrders() and GetClosedOrders() also don't return clientIds in their responses.

**Comment by JKorf** [comment]
Hi, orders returned by the order endpoints should have `ClientOrderId` property which contains the client specified ID. Also the `GetOrderAsync` has a `origClientOrderId` which you can use to retrieve an order by client id

**Comment by valerionatangelo** [comment]
Hi, I'm using version 8.03 and I cannot find a suitable parameter (clientId) in the GetOrder() call; I can only see string id and cancellationtoken. In the situation described (you couldn't get the placeOrder response with the orderId) I would expect to be able to search the order by clientId. Is it possible? What is the recommended way to do that? 
Also I couldn't find any origClientOrderId property in the CryptoExchange.Net.CommonObjects.Order type. Is that to be extracted someway from SourceObject?

Thank you.

**Comment by JKorf** [comment]
Have a look at the methods in `client.SpotApi.Trading.xxx`, i think thats what you're looking for

**Comment by valerionatangelo** [comment]
Thank you very much. Sorry to bother you with this.

**Comment by JKorf** [comment]
No problem
