### ISSUE TITLE
Connect to Binance Accounts in same program

### ISSUE THREAD

**Issue by habeebmatrix** [JKorf/Binance.Net#102]
In the sample code:

> BinanceClient.SetDefaultOptions(new BinanceClientOptions().....

What is the scope of this Connection settings?
Is it limited to the class or the whole application?
Will I be able to initiate new instance of the classe passing different API keys to simultaneously listen to different accounts within the same application?

**Comment by JKorf** [comment]
SetDefaultOptions is a static method, which means it will set the default options for every new client that you create to those specific options IF you don't pass any options when creating a new client. You can set the default options to some apikey/secret and still create a new client with different credentials by passing in other options in the constructor:
````C#
BinanceClient.SetDefaultOptions(new BinanceClientOptions().....
var client1 = new BinanceClient(); // Will have the credentials specified in the above line
var client2 = new BinanceClient(new BinanceClientOptions() .. ) // Will have the credentials specified in the constructor parameter
````

**Comment by habeebmatrix** [comment]
o thats cool. thanks for the info.
