### ISSUE TITLE
There is replacment IBinanceClientMarket in the new version

### ISSUE THREAD

**Issue by NektoDron** [JKorf/Binance.Net#1020]
The API 7.x had universal interface IBinanceClientMarket  for every market (FuturesUsdt.Market for example). But now every interface is unique. This solution is not clear, what is the point of the interface? So that you can write universal code that uses it. Now this is not possible. And so it is with other parts, not only with market data.

**Comment by HypsyNZ** [comment]
pretty sure they were all rename to something like `FuturesUsdt.Common`

**Comment by JKorf** [comment]
Supporting the different (partly) overlapping interfaces was too much overhead in figuring out what parts are shared and which aren't, which would need to be verified every time something changes in those shared interface methods or a new method was added which might be available for multiple API's.
