### ISSUE TITLE
Warnings about "Cannot map enum value" and "unknown user data event" when swapping coins

### ISSUE THREAD

**Issue by mange-ess** [JKorf/Binance.Net#1023]
**Describe the bug**
In the Binance Futures trading web app, I swapped some USDT for BUSD.
An application I had running, listening to my account's events, outputs warnings relating to this event.

**To Reproduce**
Subscribe to user data updates. Swap coins.
`var sub = await _socketClient.UsdFuturesStreams.SubscribeToUserDataUpdatesAsync(listenKey.Data, ...)`

**Expected behavior**
It would be nice if this would not generate warnings, but this is not a serious issue.

**Debug logging**
`2022/03/04 07.12.43.673 | Warning | Cannot map enum value. EnumType: Binance.Net.Enums.AccountUpdateReason, Value: COIN_SWAP_WITHDRAW, Known values: DEPOSIT, WITHDRAW, ORDER, FUNDING_FEE, WITHDRAW_REJECT, ADJUSTMENT, INSURANCE_CLEAR, ADMIN_DEPOSIT, ADMIN_WITHDRAW, MARGIN_TRANSFER, MARGIN_TYPE_CHANGE, ASSET_TRANSFER, OPTIONS_PREMIUM_FEE, OPTIONS_SETTLE_PROFIT. If you think COIN_SWAP_WITHDRAW should added please open an issue on the Github repo`
`2022/03/04 07.12.43.685 | Warning | Cannot map enum value. EnumType: Binance.Net.Enums.AccountUpdateReason, Value: COIN_SWAP_DEPOSIT, Known values: DEPOSIT, WITHDRAW, ORDER, FUNDING_FEE, WITHDRAW_REJECT, ADJUSTMENT, INSURANCE_CLEAR, ADMIN_DEPOSIT, ADMIN_WITHDRAW, MARGIN_TRANSFER, MARGIN_TYPE_CHANGE, ASSET_TRANSFER, OPTIONS_PREMIUM_FEE, OPTIONS_SETTLE_PROFIT. If you think COIN_SWAP_DEPOSIT should added please open an issue on the Github repo`
`2022/03/04 07.12.43.689 | Warning | Binance    | Received unknown user data event COIN_SWAP_ORDER: CryptoExchange.Net.Sockets.DataEvent'1[System.String]'`

**Comment by JKorf** [comment]
Hi, I've added the COIN_SWAP_WITHDRAW/COIN_SWAP_DEPOSIT  enum values so that should take care of the first 2 warnings in the next version. As for the last warning, I'm not sure what the COIN_SWAP_ORDER user update is, it is not documented.

**Comment by mange-ess** [comment]
Brilliant, thank you! :) 

And thanks for a great library 👍
