### ISSUE TITLE
Count of opened sockets

### ISSUE THREAD

**Issue by Kirill2Kirill** [JKorf/Binance.Net#1034]
Am i understand well, that all subscribe with BinanceSocketClient (for example: user data stream, tickers updates) are really using only one socket?
So they can not send me informations simultaneously? 
It always be a query of rather messages on my port?
So i can safely use one thread to listen and changes my models with it info?

And i can make only one susbcription to ConnectionClosed, ConndectionRestored event? And in will work for all subs?

**Comment by JKorf** [comment]
The amount of subscription on a single connection can be controller with the `SocketSubscriptionsCombineTarget` client option. It is default set to 10, which means 10 subscriptions will use a single socket, then the next 10 will use another etc. Per socket there is one message handling thread, so updates per socket are always sequential. However, updates from multiple different socket connections can come in at the same time. Connection events are also per socket connection. If you have 10 subscription on a socket all 10 will receive the same connection events.

If you would want to check what socket connection a subscription is on you can compare the `updateSubscription.SocketId` property.
