### ISSUE TITLE
binanceSocketClient.SpotStreams.SubscribeToAllTickerUpdatesAsync

### ISSUE THREAD

**Issue by Dimasio7777** [JKorf/Binance.Net#1040]
Hello everybody. Next Problem. I'm new to programming. Therefore, do not judge strictly.
 var binanceSocketClient = new BinanceSocketClient();
              var subscribeResult = await binanceSocketClient.SpotStreams.SubscribeToAllTickerUpdatesAsync( data =>
            {
     //JS = data.Topic.ToString();// This working!
// JS = data.Data.ToString();// Result: System.Collections.Generic.List`1[Binance.Net.Objects.Models.Spot.Socket.BinanceStreamTick]
 JS = data.OriginalData.ToString(); //Exception: NullReferenceException - Object reference does not point to an instance of an object.
                      Console.WriteLine(JS);
                           });
Before I used kline stream and its working good. Now I want recieve data, such as price. What i do wrong. Thx.
After use data.OriginalData.ToString() i see data in my Console in VS. 
Data: {
  "stream": "!ticker@arr",
  "data": [
    {
      "e": "24hrTicker",
      "E": 1648213840872,
      "s": "ETHBTC",
      "p": "0.00049200",
      "P": "0.698",
      "w": "0.07089964",
      "x": "0.07045000",
      "c": "0.07094200",
      "Q": "0.13660000",
      "b": "0.07094000",
      "B": "0.15200000",
      "a": "0.07094100",
      "A": "4.45520000",
      "o": "0.07045000",
      "h": "0.07142500",
      "l": "0.07031300",
      "v": "92385.87130000",
      "q": "6550.12547648",
      "O": 1648127440188,
      "C": 1648213840188,
      "F": 331633516,
      "L": 331805392,
      "n": 171877
    },
How can i get  "c": "0.0025",      // Last price. Thx.

**Comment by HypsyNZ** [comment]
```
public static async Task SubscribeToAllTickerUpdatesAsync()
        {
            _ = await SubscribeToAllTickerUpdatesAsync(data =>
            {
                try
                {
                    var exchangeInfo = Static.ManageExchangeInfo.GetStoredExchangeInfo();
                    var pricesFilter = Static.AllPrices.ToList();
                    foreach (var ud in data.Data)
                    {
                        var symbol = pricesFilter.SingleOrDefault(p => p.SymbolView.Symbol == ud.Symbol);
                        if (symbol != null)
                        {
                            symbol.SymbolView = new Binance24HPrice
                            {
                                Symbol = ud.Symbol,
                                LastPrice = ConvertBySats.ConvertDecimal(ud.LastPrice, ud.Symbol, exchangeInfo),

                                OpenTime = ud.OpenTime,
                                OpenPrice = ud.OpenPrice,
                                LastQuantity = ud.LastQuantity,
                                LastTradeId = ud.LastTradeId,
                                HighPrice = ud.HighPrice,
                                LowPrice = ud.LowPrice,
                                PrevDayClosePrice = ud.PrevDayClosePrice,
                                PriceChange = ud.PriceChange,
                                PriceChangePercent = ud.PriceChangePercent,
                                BaseVolume = ud.BaseVolume,
                                QuoteVolume = ud.QuoteVolume,
                                CloseTime = ud.CloseTime,
                                TotalTrades = ud.TotalTrades,
                                WeightedAveragePrice = ud.WeightedAveragePrice,
                            };
                        }
                    }
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                }
            });
```

https://github.com/HypsyNZ/BinanceTrader.NET/blob/main/BinanceTrader.NET/BVVM/Static/Socket.cs#L187

**Comment by Dimasio7777** [comment]
Thx. I Understood!
This Solved my problem.
try
                {
                                       foreach (var ud in data.Data)
                    {
                                               Console.WriteLine(ud.Symbol+"="+ud.LastPrice);
                    }
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                }

**Comment by Dimasio7777** [comment]
Solved!
