### ISSUE TITLE
How to redirect ConsoleLogger to Texbox?

### ISSUE THREAD

**Issue by hcanak** [JKorf/Binance.Net#1042]
Can any one show how to set the log records write to the textbox? Thanks.

**Comment by HypsyNZ** [comment]
you really need to provide more information than that

something like [this in WPF ](https://github.com/HypsyNZ/BinanceTrader.NET/blob/main/BinanceTrader.NET/BVVM/Logging/MiniLog.cs)

**Comment by hcanak** [comment]
May you consider to add support for redirecting the log to textbox/richtextbox in future updates?
I realy cannot maintain a fork:

**Comment by JKorf** [comment]
The library works with the ILogger interface to handle logging. Any actually loggers can be configured as you wish, but that's not part of this library.
