### ISSUE TITLE
GetKlinesAsync interval option missing

### ISSUE THREAD

**Issue by OrhanCinar** [JKorf/Binance.Net#1044]
What happened to the interval option at GetKlinesAsync method. How i am suppose to get the data for specific interval. At the latest update a lot of things are broken.

**Comment by QwykSilver** [comment]
I am also having an issue with this.  I note that the KlineInterval parameter was replaced by a TimeSpan.  I have tried several different TimeSpans, and all get the same result:

"Unsupported timespan for Binance Klines, check supported intervals using Binance.Net.Enums.KlineInterval"

Analyzing the Candles is integral to my processes.  Is there an ETA on this being fixed?

**Comment by OrhanCinar** [comment]
I have found the problem;

There are different methods. 

One is :

Client.SpotApi.CommonSpotClient.GetKlinesAsync()

and the other

Client.SpotApi.ExchangeData.GetKlinesAsync() << this one is for binance
