### ISSUE TITLE
Cant;t find endpoint

### ISSUE THREAD

**Issue by Zondor33** [JKorf/Binance.Net#1045]
Hello. Why doesn't this point ([Recent Trades List](https://binance-docs.github.io/apidocs/futures/en/#recent-trades-list)) for futures in the product? I need to get non-aggregated real-time transactions. How can i do this?

**Comment by HypsyNZ** [comment]
> Hello. Why doesn't this endpoint ([Recent Trades List](https://binance-docs.github.io/apidocs/futures/en/#recent-trades-list)) for futures exist in the library? I need to get non-aggregated real-time transactions. How can i do this?

https://github.com/JKorf/Binance.Net/blob/c3d888e43bcf39de0084a7ea19af29cab178fa68/Binance.Net/Interfaces/Clients/SpotApi/IBinanceClientSpotApiExchangeData.cs#L95

**Comment by HypsyNZ** [comment]
https://github.com/JKorf/Binance.Net/blob/c3d888e43bcf39de0084a7ea19af29cab178fa68/Binance.Net/Interfaces/Clients/CoinFuturesApi/IBinanceClientCoinFuturesApiExchangeData.cs#L50
