### ISSUE TITLE
SubscribeToAllTickerUpdatesAsync not call after REST calls

### ISSUE THREAD

**Issue by diegoaraujolima** [JKorf/Binance.Net#1046]
After making a candlestick REST call, Socket data is no longer received consistently. Even making the call to UnsubscribeAllAsync, it is intermittent, sometimes it receives and sometimes it doesn't.

**Comment by HypsyNZ** [comment]
Maybe something is blocking in your implementation somewhere, this doesn't even sound possible.

**Comment by diegoaraujolima** [comment]
How i keep socket alive? What a method? Not found KeepAlive().

**Comment by mange-ess** [comment]
@diegoaraujolima there is a function KeepAliveUserStreamAsync which you call, for example in the BinanceClient.UsdFuturesApi.Account interface.

**Comment by diegoaraujolima** [comment]
OK. But what is this listenKey parameter?

**Comment by HypsyNZ** [comment]
> OK. But what is this listenKey parameter?

It notifies Binance to keep sending information to the socket

the `listenkey` is in the return of the `subscription`

**Comment by diegoaraujolima** [comment]
Are you sure? Wouldn't the listenKey be the return key of the StartUserStreamAsync method?

**Comment by HypsyNZ** [comment]
> Are you sure? Wouldn't the listenKey be the return key of the StartUserStreamAsync method?

Yeah that is what I said.

This issue isn't constructive. You need to take a entry level programming course.

**Comment by diegoaraujolima** [comment]
Is this serious? I think you confused when you said which method returns the listenKey. I just corrected what you said, because Subscribe doesn't return the listenKey, but an integer id, which is for another purpose.

**Comment by HypsyNZ** [comment]
The listen key from `StartUserStreamAsync` (the subscription) needs to be used with `KeepAliveUserStreamAsync` at least once an hour, personally I do this every 15 minutes.

**Comment by diegoaraujolima** [comment]
Yes, that I know, I already use it that way. The problem is not that. I have a socket to get the price using the SubscribeToAllTickerUpdatesAsync() method and every close of 1 minute, 1 hour, 4 hours and 1 day candles and then iterate on all symbols to get the candles and calculate the RSI of all candle closes. In some cases the candle calls stop responding and in some cases it is the socket that stops receiving messages.

**Comment by HypsyNZ** [comment]
Are you getting error messages saying the socket is going slow?

Do you get any errors/information when this happens with logging level set to "Information" ?

when you say "stops responding" do you have to start the subscription again or does it 'just start working' again?

**Comment by HypsyNZ** [comment]
The other thing that comes to mind is maybe all of this is happening in the same thread and causing it to block, 

did you create these subscriptions inside their own `Task` or inside your UI thread?

**Comment by diegoaraujolima** [comment]
In fact, from what I'm checking it could be an excessive amount of calls on Binance. While I have these threads picking up the candles, after that I generate some orders on Binance for several currencies and it seems that when there is a delay in the response in the order API, some threads are blocked waiting for the completion of others. It seems to me more of a problem of managing concurrent threads than in fact a problem of the library. I'll double check and if I find a problem with the library I'll bring it here again. Thanks for listening.

**Comment by HypsyNZ** [comment]
Let us know when you figure it out, I am invested in the outcome now haha

**Comment by diegoaraujolima** [comment]
Is it possible to set a timeout for REST API requests?

**Comment by JKorf** [comment]
I'm sorry, this issue got kinda burried. You can use the `RequestTimeout` in the client options to set the request timeout
