### ISSUE TITLE
ListenKey, TradeRules, SendPeriodic

### ISSUE THREAD

**Issue by Kirill2Kirill** [JKorf/Binance.Net#1047]
1) Should I really used to `ListenKey `in my app? I tried to make few socket connections, and DO NOT send `ListenKey `to binance every 60 min. So my connections has been lost, but then i received an event of its restored. So all connections to different sockets was keeps alive even without using `ListenKey` from my side.

2) The same questions about `TradeRules`. Should i even request it by myself or not?

3) The last question: what is `SocketClient.SendPeriodic` can be used for? I do not find nothing about sending info on socket in finance-api-documentation.

**Comment by HypsyNZ** [comment]
This is not an issue.

**Comment by HypsyNZ** [comment]
1. The listen key from `StartUserStreamAsync` (the subscription) needs to be used with `KeepAliveUserStreamAsync` at least once an hour, personally I do this every 15 minutes. This is not optional, If you don't keep the key alive the server may choose not to send information to you if it is busy or has other messages for you.

2. This is disabled by default unless you enable it in client options, if you enable it then it will periodically update itself and actually uses a lot of resources, You should just handle this yourself if you plan on trading a lot.

3. This is used by other exchanges you can delete it if you care.

**Comment by HypsyNZ** [comment]
1. The listen key from `StartUserStreamAsync` (the subscription) needs to be used with `KeepAliveUserStreamAsync` at least once an hour, personally I do this every 15 minutes. This is not optional, If you don't keep the key alive the server may choose not to send information to you if it is busy or has other messages for you.

2. This is disabled by default unless you enable it in client options, if you enable it then it will periodically update itself and actually uses a lot of resources, You should just handle this yourself if you plan on trading a lot.

3. This isn't used you can delete it if you care.
