### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by nikkozp** [JKorf/Binance.Net#105]
Hey
I want to make an error process, but in data.Error.Message outputs me Json
and in data.Error.Code -  number that is not associated with the number of errors on Binance
```
var cancelOrder = client.CancelOrder(order["Symbol"].ToString(), Convert.ToInt64(order["OrderId"]));
if (cancelOrder.Success)
{
//data
}
else
{
       BinanceLog?.Invoke(cancelOrder.Error.Message);
 }
```

I want to make an error process, but in data.Error.Message to me outputs Json
and in data.Error.Code - number that is not associated with the number of errors on Binance

Example:

cancelOrder.Error.Message
> Server error: {"code":-2011,"msg":"UNKNOWN_ORDER"}

cancelOrder.Error.Code
> 3

this is a bug or how it should be?

It would be easier and clearer if
cancelOrder.Error.Message

> UNKNOWN_ORDER

cancelOrder.Error.Code
> -2011

**Comment by JKorf** [comment]
Hi, error parsing was something I meant to do but forgot to actually implement.. Anyway, I just pushed a version (v3.1.14) which correctly maps the error message/code to the result object.

**Comment by nikkozp** [comment]
thx

**Comment by nikkozp** [comment]
not working, have same Error handling

**Comment by JKorf** [comment]
Can you verify you're using version >= 3.1.14 ? It works for me locally.

If you're having issues with the latest version please let me know what call you're having issues with and what the result is, including debug logging.
