### ISSUE TITLE
Missing endpoints for isolated and cross margin fee data?

### ISSUE THREAD

**Issue by aleslipensky** [JKorf/Binance.Net#1052]
Hello,

I need to query information about isolated and cross margin rates, but can't find the way how to do that.
Cross margin rates can be maybe found by GetMarginInterestRateHistoryAsync, but I don't have an idea, how to get the isolated margin rates.
There are two endpoints : 
              https://binance-docs.github.io/apidocs/spot/en/#query-isolated-margin-fee-data-user_data
              https://binance-docs.github.io/apidocs/spot/en/#query-cross-margin-fee-data-user_data
which should be exactly for that. They are not implemented, I guess...? Any chance they might be? Or is there any other way how to get the rates, especially for isolated margin rates?

Many thanks!
Ales

**Comment by HypsyNZ** [comment]
https://github.com/JKorf/Binance.Net/pull/998

**Comment by aleslipensky** [comment]
ty

**Comment by HypsyNZ** [comment]
Don't thank me just yet it wasn't merged because I deleted the branch, Just showing you how to add an endpoint really.

**Comment by aleslipensky** [comment]
I just did it and it works. Lovely. Thank you, you saved my day

**Comment by HypsyNZ** [comment]
https://github.com/JKorf/Binance.Net/pull/1077
