### ISSUE TITLE
Get Spot price 24/24

### ISSUE THREAD

**Issue by eragondr** [JKorf/Binance.Net#1054]
Iam doing a signalr project. And i have function to get  the price of  the token in the list loops  forever. Similarto this. 
![image](https://user-images.githubusercontent.com/28474355/163432589-46b97d32-cd73-4b6f-9c66-c6f91dfe7b06.png)

And if i use the  client.SpotApi.ExchangeData.GetPriceAsync for too long, I will run out the number of call and  get null pointer exception in the :
 decimal price = getPrice.Data.Price;

How can i get the price of each token in the list one by one and looping forever

**Comment by HypsyNZ** [comment]
Use `GetPricesAsync()` instead without providing a symbol

**Comment by YunusOzdemirr** [comment]
Using while is true in here??

**Comment by eragondr** [comment]
i  want  an endless loop so iam using while true . what is the proplem ?

**Comment by YunusOzdemirr** [comment]
That can be a bad way for ram
Maybe you can use ChannelWriter and ChannelReader for Stream data
