### ISSUE TITLE
LogLevel dynamic change

### ISSUE THREAD

**Issue by Kirill2Kirill** [JKorf/Binance.Net#1055]
I want to change LogLEvel dynamicaly. And try to use this construction:
```
if (SocketClient != null) 
     SocketClient.ClientOptions.LogLevel = value;
if (Client != null) 
     Client.ClientOptions.LogLevel = value;
```
But it didnt work.
For example it cannot be changed form Info to Trace.
Any idea?
Only by creating new clients with new options? 
This is not good because of the large number of references to the current instances

Now im using the trace loglevel in clients options, and catch loglevel values which i need by logger options. 
But clients is still use extra resources for it.

**Comment by HypsyNZ** [comment]
https://github.com/JKorf/Binance.Net/blob/f08c8e75a0bd6c015b10e8ada59b4dd35884c2f1/Binance.Net/Objects/BinanceClientOptions.cs#L72-L93

**Comment by Kirill2Kirill** [comment]
> https://github.com/JKorf/Binance.Net/blob/f08c8e75a0bd6c015b10e8ada59b4dd35884c2f1/Binance.Net/Objects/BinanceClientOptions.cs#L72-L93

Its great, but how i can change it dynamicaly?
I can set BinanceClientOptions only when create new clients.

**Comment by HypsyNZ** [comment]
You don't need to do that

```cs
        /// <summary>
        /// Write a log entry
        /// </summary>
        /// <param name="logLevel">The verbosity of the message</param>
        /// <param name="message">The message to log</param>
        public void Write(LogLevel logLevel, string message)
        {
            if (Level != null && (int)logLevel < (int)Level)
                return;


            var logMessage = $"{ClientName,-10} | {message}";
            foreach (var writer in writers.ToList())
            {
                try
                {
                    writer.Log(logLevel, logMessage);
                }
                catch (Exception e)
                {
                    // Can't write to the logging so where else to output..
                    Trace.WriteLine($"{DateTime.Now:yyyy/MM/dd HH:mm:ss:fff} | Warning | Failed to write log to writer {writer.GetType()}: " + e.ToLogString());
                }
            }
        }
```



https://github.com/JKorf/CryptoExchange.Net/blob/1739769f87fc6900edd31d19253dd248799028fa/CryptoExchange.Net/Logging/Log.cs#L48-L71

**Comment by JKorf** [comment]
Its currently not possible to change the LogLevel after a client has been created. Although I can see some value in allowing this it's not something I can very easily change. So it's not something that'll probably be implemented short term.

**Comment by JKorf** [comment]
This should be working with the latest versions
