### ISSUE TITLE
Socket ping rate

### ISSUE THREAD

**Issue by Kirill2Kirill** [JKorf/Binance.Net#1056]
Currently, I am tracking the ping to the exchange by using `_client.SpotApi.ExchangeData.PingAsync()` method every second.
And my logic works fine, but it clogs up the LOGS with trash info messages about this requests. 
Maybe there is some way to track the ping to the server via sockets?

**Comment by HypsyNZ** [comment]
> Maybe there is some way to track the ping to the server via sockets?

This would probably slow the socket down and [this issue is in the wrong repo](https://github.com/JKorf/CryptoExchange.Net)

**Comment by JKorf** [comment]
Cleaning up old issues, if you feel this issue is still relevant feel free to comment.
There is no easy way to control or see ping message from a websocket connection.
