### ISSUE TITLE
Can't parse symbol filter of type: TRAILING_DELTA

### ISSUE THREAD

**Issue by altaym** [JKorf/Binance.Net#1059]
Since Binance has added a new FilterType 'TRAILING_DELTA' that is not part of the FilterType enum in the existing API, the API to get ExchangeInfo will generate a "2022.04.17 00:45:37:412 | Warning | Can't parse symbol filter of type: TRAILING_DELTA" throws an exception.

What is the way to fix this? thanks

**Comment by HypsyNZ** [comment]
This was `Merged` and can be closed

**Comment by HypsyNZ** [comment]
https://github.com/JKorf/Binance.Net/pull/1067
