### ISSUE TITLE
SubscribeToUserStream - Not receiving Trade Notifications

### ISSUE THREAD

**Issue by habeebmatrix** [JKorf/Binance.Net#106]
```
var successAccount = socketClient.SubscribeToUserStream(listenKey, data =>
{
	// Custom Code
},
data =>
{
	// Custom Code
});
```
In the above code, delegate in Custom code is not called in some 50% of the time when a new trade happens. Any idea on this issue?
Once I unsubscribe and close the app and restart it works.
Will it be a good idea to periodically 
1) Check if the Subscription still exists?
2) If not, periodically unsubscribe and resubscribe to UserStream.

Anyone faced this scenarios before?

**Comment by JKorf** [comment]
Hi, are you aware that after 1 hour the stream is disconnected unless you send a KeepAlive? 
See:
https://github.com/binance-exchange/binance-official-api-docs/blob/master/user-data-stream.md#pingkeep-alive-a-listenkey

**Comment by habeebmatrix** [comment]
Thanks @JKorf for the insight.
I could find a KeepAliveUserStream() method for BinanceClient, but not for BinanceSocketClient.
Could you please suggest an approach to ping and keep the connection alive for a BinanceSocketClient.

**Comment by JKorf** [comment]
That's the one you need. You use the Rest client `BinanceClient` to open the stream and get a listenkey. That listenkey is then used to open the user stream in the `BinanceSocketClient`. You then have to use the rest client again to send a `KeepAliveUserStream` every 30 minutes as suggested by Binance. Let me know if you have any issues.

**Comment by habeebmatrix** [comment]
Thanks a lot @JKorf .
I will update the code to do this. I will update this thread with my results.

**Comment by habeebmatrix** [comment]
@JKorf , what I did was store the listenkey and call

>  client.KeepAliveUserStream(listenKey)

 every 30 min. But it returned 

> Server error: {"code":-1125,"msg":"This listenKey does not exist."}

Any idea about this?

**Comment by JKorf** [comment]
Hm that shouldn't happen. Can you give small code samples of the code you're using?

**Comment by JKorf** [comment]
Don't see anything wrong, can you verify with debug logging the same listenkey is send in the keep alive as you receive in the start user stream?

I just tried with the following code, can you check if this works for you?
````C#
static void Main(string[] args)
        {
            var client = new BinanceClient(new BinanceClientOptions()
            {
                LogVerbosity = LogVerbosity.Debug,
                ApiCredentials = new ApiCredentials("KEY", "SEC")
            });


            var socketClient = new BinanceSocketClient(new BinanceSocketClientOptions()
            {
                LogVerbosity = LogVerbosity.Debug,
                ApiCredentials = new ApiCredentials("KEY", "SEC")
            });

            var us = client.StartUserStream();
            socketClient.SubscribeToUserStream(us.Data.ListenKey, data =>
            {

            },
            data =>
            {

            });

            Console.ReadLine();
            client.KeepAliveUserStream(us.Data.ListenKey);
            Console.ReadLine();
            client.StopUserStream(us.Data.ListenKey);
            Console.ReadLine();
        }
````

**Comment by habeebmatrix** [comment]
Hi @JKorf ,
As of now it is working fine. In between, I again got the same issue.
So I also doubt, if this can happen if I make a new connection to the same Binance account and Subscribe to UserStream. Not confirmed though. Right now, I tried to make another connection to the same account and in both programs I got the same listen key.
I am not sure if Binance updates the listen key anytime.

**Comment by habeebmatrix** [comment]
listenkey issue happened again. It was trying with the original listen key and it says listenkey doesn't exist.

**Comment by JKorf** [comment]
You have debug logging if when you started the user stream + when you tried the keep alive?

**Comment by habeebmatrix** [comment]
I tried to KeepAlive every 30 min.
After the first ListenKey, it was around 1.5 hours, it started giving the error.
I do not think this time is fixed.

**Comment by JKorf** [comment]
I've had it running for 3 hours now, no problems. When I called StartUserStream again after this time it just returned the same listenKey I already had. Again, can you put LogVerbosity to LogVerbosity.Debug and provide logging of the calls?

**Comment by habeebmatrix** [comment]
The issue is still happening. But kinda randomly. Last time, it ran for around 6 hours properly and then shows this error. During this time, no trade notification is received as well. Please find the logs below. It shows the portion of logs where it was successfully and when it started showing u the errors. These logs are in sequence. Could you please take a look.

> 7/26/2018 1:41:51 AM: KeepAliveTimerCallback, ListenKey: pFNhOXJnBpgtvDtZsVOySEag4QsLouXMoye7gYv2EZpP1LZKl0M9PA89khk6
> 2018/07/26 01:41:51:121 | Debug | Creating request for https://api.binance.com/api/v1/userDataStream
> 2018/07/26 01:41:51:124 | Debug | Sending  request to https://api.binance.com/api/v1/userDataStream?listenKey=pFNhOXJnBpgtvDtZsVOySEag4QsLouXMoye7gYv2EZpP1LZKl0M9PA89khk6 with parameters listenKey=pFNhOXJnBpgtvDtZsVOySEag4QsLouXMoye7gYv2EZpP1LZKl0M9PA89khk6,
> 2018/07/26 01:41:51:524 | Debug | Data returned: {}
> Success:True, Error: , {}
> 7/26/2018 1:51:51 AM: KeepAliveTimerCallback, ListenKey: pFNhOXJnBpgtvDtZsVOySEag4QsLouXMoye7gYv2EZpP1LZKl0M9PA89khk6
> 2018/07/26 01:51:51:122 | Debug | Creating request for https://api.binance.com/api/v1/userDataStream
> 2018/07/26 01:51:51:127 | Debug | Sending  request to https://api.binance.com/api/v1/userDataStream?listenKey=pFNhOXJnBpgtvDtZsVOySEag4QsLouXMoye7gYv2EZpP1LZKl0M9PA89khk6 with parameters listenKey=pFNhOXJnBpgtvDtZsVOySEag4QsLouXMoye7gYv2EZpP1LZKl0M9PA89khk6,
> 2018/07/26 01:51:51:526 | Warning | Server returned an error: {"code":-1125,"msg":"This listenKey does not exist."}
> Success:False, Error: Server error: {"code":-1125,"msg":"This listenKey does not exist."},
> 7/26/2018 2:01:51 AM: KeepAliveTimerCallback, ListenKey: pFNhOXJnBpgtvDtZsVOySEag4QsLouXMoye7gYv2EZpP1LZKl0M9PA89khk6
> 2018/07/26 02:01:51:193 | Debug | Creating request for https://api.binance.com/api/v1/userDataStream
> 2018/07/26 02:01:51:197 | Debug | Sending  request to https://api.binance.com/api/v1/userDataStream?listenKey=pFNhOXJnBpgtvDtZsVOySEag4QsLouXMoye7gYv2EZpP1LZKl0M9PA89khk6 with parameters listenKey=pFNhOXJnBpgtvDtZsVOySEag4QsLouXMoye7gYv2EZpP1LZKl0M9PA89khk6,
> 2018/07/26 02:01:51:658 | Warning | Server returned an error: {"code":-1125,"msg":"This listenKey does not exist."}
> Success:False, Error: Server error: {"code":-1125,"msg":"This listenKey does not exist."},

**Comment by JKorf** [comment]
Can't see anything weird in that logging.. I'm not sure why it is suddenly deciding the key is invalid. I'll try to reproduce again today. Can you confirm the same APIKey/Secret isn't used in another (part of your) program to start a user stream?

**Comment by habeebmatrix** [comment]
Within the same Program, I do not use the key any more. The basic structure of my program is the one I had sent earlier (Main()). There are some sub routines, but it does not manipulate the connection.
Another instance of the same program with the same keys also has not been opened.

Anyway, at the time of KeepAlive call, if i get en error, I think I should try to reconnect. Because I am not getting updates on trade. Could you please suggest the best way to do it like:
```
socketClient.UnsubscribeAllStreams();
client.StopUserStream(listenKey);
```
Then again,
```
var successAccount = socketClient.SubscribeToUserStream(listenKey, data =>
{
	// Custom Code
},
data =>
{
	// Custom Code
});
```
This seems fine?

**Comment by JKorf** [comment]
You'll have to call StartUserStream again to get a new listenkey again before re-subscribing. Other than that that should work.

**Comment by JKorf** [comment]
I´ve run the today again for about 8 hours, no problems. I´m not sure what else to try, I might try to get some info from Binance to see what can cause this.

**Comment by habeebmatrix** [comment]
Its perfectly working now. Thanks @JKorf for the support and patience.

**Comment by JKorf** [comment]
I actually tried disconnecting my internet to see if that would invalidate the listenkey, but it still worked after reconnecting. That dc was only like 30 seconds though, maybe longer dc's might void the key, I don't know. Glad you found a working solution!

**Comment by kingchenc** [comment]
@habeebmatrix how u fixxed the bug "This listenKey does not exist."? small example? thx

**Comment by c9s** [comment]
> I tried to KeepAlive every 30 min. After the first ListenKey, it was around 1.5 hours, it started giving the error. I do not think this time is fixed.

same here, but I am using golang to connect to the server

**Comment by c9s** [comment]
the listen key was successfully created and the user data stream can also be created, however, after 2 more minutes, I sent a keep alive listen key to the binance api server, the api responds that the listen key does not exist.

**Comment by iZakaroN** [comment]
For me the problem was second instance of the application is reusing and disposing the user stream key on application exit. Commenting the following code looks that have fixed the problem:
				//Do not stop UserStreamKey as multiple applications to same api dispose other application events 
				//if (_userStreamListenKey != null)
				//	await HttpClient.Spot.UserStream.StopUserStreamAsync(_userStreamListenKey).UnWrap();
