### ISSUE TITLE
connections forced closed

### ISSUE THREAD

**Issue by xkqg** [JKorf/Binance.Net#1061]
I use sometimes many connections to Binance, therefor I got several times connection forced closed and some of the Async methodes took more then a minute to complete

I solved the issue by adding the nextline at the start of the program
ServicePointManager.DefaultConnectionLimit = 200

Hopefully this can be helpfull

**Comment by HypsyNZ** [comment]
### ServicePointManager.DefaultConnectionLimit Property

>The maximum number of concurrent connections allowed by a [ServicePoint](https://docs.microsoft.com/en->us/dotnet/api/system.net.servicepoint?view=net-6.0) object. The default connection limit is 10 for ASP.NET hosted >applications and 2 for all others. When an app is running as an ASP.NET host, it is not possible to alter the value of this >property through the config file if the autoConfig property is set to true. However, you can change the value >programmatically when the autoConfig property is true. Set your preferred value once, when the AppDomain loads.

https://docs.microsoft.com/en-us/dotnet/api/system.net.servicepointmanager.defaultconnectionlimit?view=net-6.0

**Comment by HypsyNZ** [comment]
This branch can be cherry picked

**Comment by HypsyNZ** [comment]
This branch can still be cherry picked but won't be merged.
