### ISSUE TITLE
Adding trailing to spot APIs

### ISSUE THREAD

**Issue by CrayCrayBoy** [JKorf/Binance.Net#1065]
Hi JKorf,

Really admire all your work! Binance has recently added trailing to spot orders. Just wondering if it's on your radar. Thanks!

https://binance-docs.github.io/apidocs/spot/en/#change-log
Support of trailing with spot API on April 13.

**Comment by HypsyNZ** [comment]
https://github.com/JKorf/Binance.Net/pull/1060

**Comment by HypsyNZ** [comment]
https://github.com/JKorf/Binance.Net/pull/1067
