### ISSUE TITLE
New error on GetExchangeInfo

### ISSUE THREAD

**Issue by nikkozp** [JKorf/Binance.Net#107]
Hi, 
I think Binance again something updated, since the function call GetExchangeInfo gives an error. I think this is due to the MAX_NUM_ALGO_ORDERS

> 08:57:02.827 Error deserializing data: Deserialize Unknown Exception:  Received data: {"timezone":"UTC","serverTime

**Comment by FairDeveloper** [comment]
I'm getting that, the error is in SymbolFilterConverter.cs: 
System.InvalidOperationException: 'Sequence contains no matching element' 
at the line:
SymbolFilterType type = new SymbolFilterTypeConverter(false).ReadString(obj["filterType"].ToString());

**Comment by jukoson** [comment]
same here

**Comment by jooxee** [comment]
4: Error deserializing data

**Comment by ivarsdzalbs** [comment]
Same issue

**Comment by JKorf** [comment]
Hi everyone, I've just pushed a fix (works on my machine :D) for this, should be available on Nuget in a few minutes ( v3.1.15)

**Comment by ivarsdzalbs** [comment]
Can confirm, fixed. Thank you!

**Comment by TheFitzZZ** [comment]
@JKorf thanks for the super fast reaction dude. Will update our binaries and post if somethings bad still. 

Thanks again!

**Comment by basdroid** [comment]
Nice, everything is working again, many thanks.
