### ISSUE TITLE
WS OrderBookUpdatesAsync gives back bid prices in the wrong (opposite) order. 

### ISSUE THREAD

**Issue by MachineTrader** [JKorf/Binance.Net#1070]
Websocket function SubscribeToOrderBookUpdatesAsync() gives back bid prices in opposite order. 

The Lowest and least interesting Bid price first. 

This forces programmer to reverse the list which takes time(Ms), and can easily lead to unnecessary problem solving
 and bug hunting when working with multiple exchanges. 
 
This is not the case from the same endpoint on FTX.

Does this purely have to do with how Binance sends prices out, or is there a mistake in the library? 

Could we solve this by reversing prices in the fastest possible way in the library?

**Comment by HypsyNZ** [comment]
It doesn't sound like you are building an order book correctly.

**Comment by JKorf** [comment]
The data isn't adjusted in the library, it's just how the server sends it. It might be different from exchange to exchange, but I don't really see how that's an issue for updates (it would be for a snapshot)
