### ISSUE TITLE
Placed order with socket

### ISSUE THREAD

**Issue by ejinguyen** [JKorf/Binance.Net#1072]
I have a problem when placed order 
{"Code":-1003,"Message":"Way too much request weight used; IP banned until 1651381254370. Please use the websocket for live updates to avoid bans.","Data":null}

So I try to use socket, but I don't know to placed order with Socket, please help me!

**Comment by JKorf** [comment]
You can't place orders via the socket client, just use the rest client for this. You shouldn't get rate limited from just that. You should use the socket client for getting live data updates, like live prices and order updates

**Comment by HypsyNZ** [comment]
@ejinguyen 

What are your default options?

You should use `TradeRulesBehaviour = None`

**Comment by ejinguyen** [comment]
> TradeRulesBehaviour

**Comment by ejinguyen** [comment]
> You can't place orders via the socket client, just use the rest client for this. You shouldn't get rate limited from just that. You should use the socket client for getting live data updates, like live prices and order updates

Thank you admin!

**Comment by ejinguyen** [comment]
> @ejinguyen
> 
> What are your default options?
> 
> You should use `TradeRulesBehaviour = None`

I tried it, but the issue is still unresolved

**Comment by ejinguyen** [comment]
I resolved my problem by reduce calling api. Thank all!
