### ISSUE TITLE
Isolated Margin Account Activate Error...

### ISSUE THREAD

**Issue by hcanak** [JKorf/Binance.Net#1073]
Hello,

In order to activate Isolated Margin Account first time, you need to transfer asset to that account. When transfering asset to that account i frequently get the following error:
**Error Code: -1000
Error Message: An unknown error occurred while processing the request.**

Any one facing this error? Any suggestion about how to recover this?

**Comment by HypsyNZ** [comment]
> In order to activate Isolated Margin Account first time, you need to transfer asset to that account. 

Where did you read that.

You need to activate the account first; https://binance-docs.github.io/apidocs/spot/en/#enable-isolated-margin-account-trade

**Comment by hcanak** [comment]
I found it by examining. When you try to send **SpotApi.Account.EnableIsolatedMarginAccountAsync** first time, it gives the following error:

{-11001: Isolated margin account does not exist. }

**Comment by eduardobellotto** [comment]
Hi hcanak.

I was receiving this error when I was trying to create the isolated margin account during a high volatility period for the symbol.

When I create the account during a low volatility period I don't receive this message.

So, I create and disable the accounts in advance, to be able to use them when I need it.

Maybe it can be the case for you.

**Comment by hcanak** [comment]
> Hi hcanak.
> 
> I was receiving this error when I was trying to create the isolated margin account during a high volatility period for the symbol.
> 
> When I create the account during a low volatility period I don't receive this message.
> 
> So, I create and disable the accounts in advance, to be able to use them when I need it.
> 
> Maybe it can be the case for you.

Hi [eduardobellotto](https://github.com/eduardobellotto), You are right, that is what i did:
