### ISSUE TITLE
CryptoExchange.Net5.1.8 and Binance.Net 8.0.12

### ISSUE THREAD

**Issue by Dimasio7777** [JKorf/Binance.Net#1074]
var cts = new CancellationTokenSource();
var subscribeResult = await client.SpotStreams.SubscribeToKlineUpdatesAsync();

Also i used CancellationTokenSource to close subscription. In last ver(5.1.8 amd 8.0.12) i had Error:
"Instance 'System.Net.WebSockets.InternalClientWebSocket' cannot be used for communication because it has entered the 'Aborted' state."
Previous ver working good. CryptoExchange.Net5.1.7 and Binance.Net 8.0.11;

**Comment by HypsyNZ** [comment]
What are you asking.

**Comment by Dimasio7777** [comment]
When I activate CancellationToken using  cts.Cancel() in subscription var subscribeResult = await client.SpotStreams.SubscribeToKlineUpdatesAsync();
I ve got error.
"Instance 'System.Net.WebSockets.InternalClientWebSocket' cannot be used for communication because it has entered the 'Aborted' state."
Previous ver working good. CryptoExchange.Net5.1.7 and Binance.Net 8.0.11;

**Comment by HypsyNZ** [comment]
Found relevant logs

>Exception: The 'System.Net.WebSockets.InternalClientWebSocket' instance cannot be used for communication because it has been transitioned into the 'Aborted' state.

> Trace:   at System.Net.WebSockets.WebSocketBase.ThrowIfAborted(Boolean aborted, Exception innerException)

> Inner: System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.

You can just ignore this.
