### ISSUE TITLE
AutoComply does not seem to be working for quoteQuantity when placing a market order in spot market.

### ISSUE THREAD

**Issue by TheUserNameIsStrongInThisOne** [JKorf/Binance.Net#1078]
When placing a market order in spot market (_client.SpotApi.Trading.PlaceOrderAsync), the quoteQuantity does not trigger clamping to trade rules.
The binance server response is error code: -1100, message: "Illegal characters found in parameter 'quoteOrderQty'; legal range is '^([0-9]{1,20})(\.[0-9]{1,20})?$'."

The quantity parameter seems to be working fine. You can see the clamping to trade rules in the debug log for the quantity parameter, but when using the quoteQuantity these log lines are absent.

If the quoteQuantity is manually rounded to lot size and precision, the error does not occur.

**Comment by JKorf** [comment]
I've added checking of quoteQuantity vs the minimal notional value
