### ISSUE TITLE
Limit order on pair SNTETH fails with “{-1121: Invalid symbol. }”

### ISSUE THREAD

**Issue by gsscoder** [JKorf/Binance.Net#1081]
**Describe the bug**
When I try to place a buy limit order of type fill or kill I get `{-1121: Invalid symbol. } ` error.

**To Reproduce**
```csharp
var result = await _singedClient.SpotApi.Trading.PlaceOrderAsync(
		pair, OrderSide.Buy, SpotOrderType.Limit, timeInForce: TimeInForce.FillOrKill,
		quantity: 2312.90968m, price: 0.0001734m);
```

**Expected behavior**

An order with some status.

**Debug logging**
I can't for the moment I'm working on the code and is intermediate state, sorry.

Best regards and thanks for the excellent work

**Comment by HypsyNZ** [comment]
Does this issue occur for other symbols?

**Comment by gsscoder** [comment]
No, just for the pair presented here SNTETH

**Comment by JKorf** [comment]
I'm not sure, would be a Binance issue. So you'd have more luck trying to contact them I think
