### ISSUE TITLE
PlaceOrderAsync quantity error since v8.1

### ISSUE THREAD

**Issue by phunkboy** [JKorf/Binance.Net#1085]
**Describe the bug**
Since updating to v8.1.x, I'm getting the following error whenever I submit a Quote Order Quantity market order using PlaceOrderAsync in SpotApi:

`Param 'quantity' or 'quoteOrderQty' must be sent, but both were empty/null!`

**To Reproduce**
Place a market buy order with `quoteQuantity` set to a decimal amount and leave `quantity` null.

**Expected behavior**
The buy order should be successful for the amount specified.  If I rollback to v8.0.13, everything works fine.

**Comment by JKorf** [comment]
Have you used 8.1.1?  There was in issue in 8.1.0 which might've caused this

**Comment by phunkboy** [comment]
Yes, I get the same error in v.8.1.1 and v.8.1.0. Switching back to v8.0.13 fixes the issue.

**Comment by phunkboy** [comment]
The error is fixed in v8.1.2. Many thanks!
