### ISSUE TITLE
Query Cross Margin Account Details NOT working properly

### ISSUE THREAD

**Issue by hcanak** [JKorf/Binance.Net#1087]
Hello,

i think following endpoint has some bug. Firstly, it should have a filed named "free" but in this library, it does not. In this library, there is "available" field which i think it represents "free". But the main problem is;

- **available** filed is always equal to **netAsset** field and
- **locked** field is always equal to **zero**.

Can you check does it need a fixing? Thanks for all your afford.

ENDPOINT

Query Cross Margin Account Details (USER_DATA)
GET /sapi/v1/margin/account (HMAC SHA256)

Response:

{
      "borrowEnabled": true,
      "marginLevel": "11.64405625",
      "totalAssetOfBtc": "6.82728457",
      "totalLiabilityOfBtc": "0.58633215",
      "totalNetAssetOfBtc": "6.24095242",
      "tradeEnabled": true,
      "transferEnabled": true,
      "userAssets": [
          {
              "asset": "BTC",
              "borrowed": "0.00000000",
              "free": "0.00499500",
              "interest": "0.00000000",
              "locked": "0.00000000",
              "netAsset": "0.00499500"
          },
          {
              "asset": "BNB",
              "borrowed": "201.66666672",
              "free": "2346.50000000",
              "interest": "0.00000000",
              "locked": "0.00000000",
              "netAsset": "2144.83333328"
          },
          {
              "asset": "ETH",
              "borrowed": "0.00000000",
              "free": "0.00000000",
              "interest": "0.00000000",
              "locked": "0.00000000",
              "netAsset": "0.00000000"
          },
          {
              "asset": "USDT",
              "borrowed": "0.00000000",
              "free": "0.00000000",
              "interest": "0.00000000",
              "locked": "0.00000000",
              "netAsset": "0.00000000"
          }
      ]
}

**Comment by HypsyNZ** [comment]
> You said `it should have a filed named "free" but in this library`

Yes this is correct, free was renamed to available.

-----

 > You said `free field is always equal to netAsset field` but in your own example that isn't true

```cs 
{
"asset": "BNB",
"borrowed": "201.66666672",
"free": "2346.50000000",
"interest": "0.00000000",
"locked": "0.00000000",
"netAsset": "2144.83333328"
},
```

So it is not clear what you are asking.

-----

You said `locked field is always equal to zero.`

Do you have any open orders or some other reason to expect it to be something other than zero, It works for me.

**Comment by HypsyNZ** [comment]
- [x] Checked `Objects\Models\Spot\Margin\BinanceMarginAccount.cs` and found no errors.
- [ ] `BinanceMarginAccount` is not a partial class and should be move to its own file
- [ ] `BinanceMarginBalance`  is not a partial class and should be move to its own file

**Comment by hcanak** [comment]
Excuse me sir @HypsyNZ Everything works perfect 👍 
Thanks for your quick response.
