### ISSUE TITLE
Universal transfer not working between Main and Isolated Margin Accounts

### ISSUE THREAD

**Issue by eduardobellotto** [JKorf/Binance.Net#1088]
Congratulations for the Project!

I noticed that the `MainToMargin` method transfers to the Cross Margin Account, even filling the `toSymbol` field correctly.

In the same way, the `MarginToMain` method transfers from the Cross Margin account, even filling the `fromSymbol` field correctly.

Could you take a look at this?

Thanks!

**Comment by HypsyNZ** [comment]
> You said `between Main and Isolated Margin Accounts`

![Untitled](https://user-images.githubusercontent.com/54571583/170474418-2973e86d-3e1f-4c53-9bb0-684f112a172d.png)

`CrossMarginTransferAsync` not for `Isolated Margin`

**Comment by HypsyNZ** [comment]
- [x] Clarified usage of `CrossMarginTransferAsync`

**Comment by HypsyNZ** [comment]
> Could you take a look at this?

You should be using `IsolatedMarginAccountTransferAsync`

![IsolatedTransfer](https://user-images.githubusercontent.com/54571583/170476023-e842caf2-b9f5-4b44-a703-ebbd49af9b4b.png)

**Comment by eduardobellotto** [comment]
Thanks for the answer HypsyNZ.

I'm talking about Universal Transfer:

`var result = client.SpotApi.Account.TransferAsync(UniversalTransferType.MainToMargin, "USDT", 0.01M, null, "VITEUSDT").Result;`

The Universal Transfer should work between Main and Isolated Margin Accounts too.

P.S.: in the example above, the VITEUSDT account was activated at the test time.

**Comment by HypsyNZ** [comment]
![Untitled](https://user-images.githubusercontent.com/54571583/170686617-6398b527-d036-4c88-ac78-da74c570bd84.png)

You need to specify `to` and `from`

![Untitled](https://user-images.githubusercontent.com/54571583/170686790-7b7aa588-9a49-4539-9acc-7e7b605e26d1.png)

You found the defaults basically.

**Comment by HypsyNZ** [comment]
![Untitled](https://user-images.githubusercontent.com/54571583/170687576-d2db592b-a67c-4959-92ea-00b9ecf32bcd.png)

**Comment by eduardobellotto** [comment]
Hi HypsyNZ.

The `client.SpotApi.Account.TransferAsync` method has no account types parameters.

Are you using another method?

The link of the related API documentation is that one:

https://binance-docs.github.io/apidocs/spot/en/#user-universal-transfer-user_data

Please, try to transfer something between Main and Isolated Margin Accounts using **this method** and tell me if it worked for you.

Best regards.

**Comment by eduardobellotto** [comment]
Hi HypsyNZ.

In the `client.SpotApi.Account.TransferAsync` method, there is no option for selecting account types.

The link of the related API documentation is that one:

https://binance-docs.github.io/apidocs/spot/en/#user-universal-transfer-user_data

As you suggested, I put the symbol in `toSymbol` and `fromSymbol` fields, but the transfer has occurred between Main and Cross Margin accounts again:

var result = client.SpotApi.Account.TransferAsync(UniversalTransferType.MainToMargin, "USDT", 0.01M, "VITEUSDT", "VITEUSDT").Result;

Please, try to transfer something between Main and Isolated Margin Accounts using this method and tell me if it worked for you.

Best regards.

**Comment by HypsyNZ** [comment]
![Untitled](https://user-images.githubusercontent.com/54571583/170842780-2170eae9-349f-4fd0-8575-8fc5ad592899.png)


It actually doesn't look like you can transfer directly from Isolated -> Spot your options are:

> Isolated -> Cross -> Spot

> Spot -> Cross -> Isolated

**Comment by HypsyNZ** [comment]
If you use the other endpoint above I think you can accomplish what you want to do.

**Comment by HypsyNZ** [comment]
You should use [Universal Transfer (For Master Account)](https://binance-docs.github.io/apidocs/spot/en/#universal-transfer-for-master-account) which doesn't use `UniversalTransferType`


`fromAccountType: "SPOT"`

`toAccountType: "ISOLATED_MARGIN"`

![Untitled](https://user-images.githubusercontent.com/54571583/170843089-e3807ac1-af82-4131-8bb7-50c0240c9ae7.png)

**Comment by HypsyNZ** [comment]
I just realized the endpoint you need is missing

**Comment by HypsyNZ** [comment]
### TransferSubAccountAsync

![Untitled](https://user-images.githubusercontent.com/54571583/170843240-20e1c4c9-18fb-4046-8516-716bc398eabf.png)

**Comment by HypsyNZ** [comment]
Sorry for the confusion, I hope this solves your issue.

**Comment by HypsyNZ** [comment]
You will need to wait until the PR is merged before you can use this with the `Master Account` (Main)

But it should solve your issue.

**Comment by eduardobellotto** [comment]
Thank you very much HypsyNZ!
