### ISSUE TITLE
Margin Transfer for Sub-account 

### ISSUE THREAD

**Issue by Gabasco** [JKorf/Binance.Net#1089]
When using GeneralApi.SubAccount.TransferSubAccountMarginAsync(), I am receiving the following message:
_{-1022: Signature for this request is not valid. }_

Shouldn't the timestamp and signature (respectively) be the last parameters instead of the parameter type?

**Comment by HypsyNZ** [comment]
`{-1022: Signature for this request is not valid. }`

- [ ] Check the permissions on your API Key and make sure transfers are enabled
- [ ] Check your Secret Key and ensure it is correct

**Comment by Gabasco** [comment]
- [ ]  **Check the permissions on your API Key and make sure transfers are enabled**

Enabled (Master and Sub-Account)

![image](https://user-images.githubusercontent.com/63671519/170515943-88b76911-360d-47ce-93e6-4c00b428254b.png)

- [ ]  **Check your Secret Key and ensure it is correct**

It is correct.

Just to be sure, I deleted the API and recreated another one. 
Same error message keeps showing. 
Other functions I use are working fine.

Any other suggestion?

**Comment by Gabasco** [comment]
Workaround: 
Using `Client.SpotApi.Account.TransferAsync()` 
Instead of `GeneralApi.SubAccount.TransferSubAccountMarginAsync()`

- [ ] You need to enable _Permits Universal Transfer_ option for the API Key which requests this endpoint.

**Comment by HypsyNZ** [comment]
Yeah, those endpoints do different things even though they kind of look the "same"

So you solved your problem?

**Comment by JKorf** [comment]
Thanks for the heads up, these should be working with the latest version
