### ISSUE TITLE
Unable to retrieve trading rules, validation failed

### ISSUE THREAD

**Issue by ndphuong** [JKorf/Binance.Net#109]
Hi
I already upgrade to latest version but still have this problem
`Unable to retrieve trading rules, validation failed`

Have any solution for this?

**Comment by JKorf** [comment]
Hi, can you double check you're on the latest version? It works for me. Latest is version 3.1.15

**Comment by JKorf** [comment]
Yes there was a bug fix in 3.1.15 in the GetExchangeInfo call which is used to update the trade rules

**Comment by ndphuong** [comment]
indeed, it work well after upgrade to 3.1.5

Thank you @JKorf
