### ISSUE TITLE
Trailing stop order type

### ISSUE THREAD

**Issue by Benajax** [JKorf/Binance.Net#1091]
Hi JKorf,

The trailing stop order type was previously a binance futures only feature but can see ( via binance mobile app) that the trailing stop order type has been introduced for Spot as well. It is a good feature to include in the library. 

Thanks

**Comment by HypsyNZ** [comment]
It has already been added you can add `trailingDelta` to your spot orders

**Comment by Benajax** [comment]
That is great @HypsyNZ. Will upgrade to pick up those changes. Thanks.

**Comment by HypsyNZ** [comment]
There is also a new symbol filter for the `trailingDelta` in the `Exchange Information` for each `Symbol` that uses the feature.

example: 
```cs
    {
          "filterType": "TRAILING_DELTA",
          "minTrailingAboveDelta": 10,
          "maxTrailingAboveDelta": 2000,
          "minTrailingBelowDelta": 10,
          "maxTrailingBelowDelta": 2000
   }
```

**Comment by Benajax** [comment]
Not an issue
