### ISSUE TITLE
Missing Json DateTime converter for BinanceRebate.UpdateTime

### ISSUE THREAD

**Issue by sergiodebst** [JKorf/Binance.Net#1093]
**Describe the bug**
JsonReaderException (Unexpected character encountered while parsing value: 1. Path 'data.data[0].updateTime') on getting data from `SpotApi.Account.GetRebateHistoryAsync`

**To Reproduce**
Get data from the binance endpoint `/sapi/v1/rebate/taxQuery` calling `BinanceClient.SpotApi.Account.GetRebateHistoryAsync`.
If there is at least 1 record, then it will fail.

**Expected behavior**
Correct deserialize and return `WebCallResult.Success = true`

----
Also I have noticed there is missing the JsonResponse test file for the request.
You can find the binance example here: https://binance-docs.github.io/apidocs/spot/en/#get-spot-rebate-history-records-user_data
```
{
   "status": "OK",
   "type": "GENERAL",
   "code": "000000000",
   "data": {
        "page": 1,  // current page
        "totalRecords": 2,  // total records
        "totalPageNum": 1,  // total pages
        "data": [
            {
                "asset": "USDT",  // rebate asset
                "type": 1,        // rebate type：1 is commission rebate，2 is referral kickback
                "amount": "0.0001126", 
                "updateTime": 1637651320000
            },
            {
                "asset": "ETH",
                "type": 1,
                "amount": "0.00000056",
                "updateTime": 1637928379000
            }
        ]
    }

}
```

**Comment by JKorf** [comment]
Thanks for the report, fixed in the latest version
