### ISSUE TITLE
SpotAPI GetKlines Limit Parameter

### ISSUE THREAD

**Issue by wurucu** [JKorf/Binance.Net#1096]
Shouldn't the limit be 1500?

https://github.com/JKorf/Binance.Net/blob/a7ae6e04ae5b180f1aac39b965c369080867aef5/Binance.Net/Clients/SpotApi/BinanceClientSpotApiExchangeData.cs#L260

Referance : https://binance-docs.github.io/apidocs/futures/en/#kline-candlestick-data

**Comment by HypsyNZ** [comment]
Yes, Good catch.

https://github.com/JKorf/Binance.Net/pull/1099

**Comment by lap888** [comment]
This interface returns not a standard OHLCV
<img width="455" alt="image" src="https://user-images.githubusercontent.com/30146744/171412277-6ba56c86-e7cf-40c9-98c5-e3e55da356c1.png">
why add a price for close high low open?
why no like this
<img width="478" alt="image" src="https://user-images.githubusercontent.com/30146744/171412486-9fdb275a-5753-4245-ba74-ff5bbbbee4c7.png">

**Comment by HypsyNZ** [comment]
> This interface returns not a standard OHLCV

Looks pretty standard to me, can you elaborate?

 > why no like this

What do you mean? Do you want the raw JSON?

**Comment by lap888** [comment]
> 

now had sloved,i ues automapper to map model

**Comment by JKorf** [comment]
Fixed in the latest version
