### ISSUE TITLE
GET /sapi/v1/pay/transactions (HMAC SHA256)

### ISSUE THREAD

**Issue by ivanfiao** [JKorf/Binance.Net#1097]
Hello... Binance has changed the docs:

The endpoint GET /sapi/v1/pay/transactions (HMAC SHA256) used the start time as "startTimestamp" and end time as "endTimestamp"... The docs were updated and now parameters were changed to "startTime" and "endTime".

![image](https://user-images.githubusercontent.com/61050503/171188188-8e6d0b70-256f-43fe-bc14-c717cedb226c.png)

**Comment by HypsyNZ** [comment]
Thank you.

https://github.com/JKorf/Binance.Net/pull/1098

**Comment by JKorf** [comment]
Fixed in latest version
