### ISSUE TITLE
Not sure what I am doing wrong

### ISSUE THREAD

**Issue by Transigent** [JKorf/Binance.Net#11]
I am sorry to be posting here but I dont know what else to do. I am experimenting with this project and I cannot get the simplest thing to work.

I have downloaded the source from Github and created a second project in the solution with a reference to the Binance.net project. In my blank Windows Forms VB project I have only the following:

```vb.net
    Public Sub New()
        ' This call is required by the designer.
        InitializeComponent()

        ' Add any initialization after the InitializeComponent() call.
        Using client As New BinanceClient()
            Dim ping = client.Ping
        End Using
    End Sub
```

Regardless of what method I call, eg. client.Ping, client.GetAllPrices, etc., it hangs at the first call. If I press pause in the debugger after calling Ping, the code is waiting at line 128 in BinanceClient.cs

```C#
public BinanceApiResult<bool> Ping() => PingAsync().Result;
```

I have tried the following:
- Turning off firewall
- Using C# instead of VB code
- Changing frameworks, currently on 4.7.1, although the framework in Binance.net properties is greyed and cannot be changed
- Using Nuget to install Binance.net instead of the project
- Tried VS2017 then VS2015

I am so confused... Any tips on how to get started would be greatly appreciated!

**Comment by JKorf** [comment]
Hi, sorry to hear that. Can you try to do the call in a separate task to see if that works?

**Comment by Transigent** [comment]
Fantastic, that solved the problem! 
Thank you very much for your quick reply, much appreciated!

**Comment by Sheikz13** [comment]
Hey Transigent,

I am also writing code in VB. I get the exact same problem. What did you do to fix it and what other packages did you install? What does "separate task" mean?

Thanks for your time in advance.

**Comment by JKorf** [comment]
Great to hear. Can I ask with what version of Bittrex.Net you were having that problem?

**Comment by Transigent** [comment]
Hi it was the latest one from Nuget, it says 2.2.1.0

**Comment by JKorf** [comment]
If you update to version 2.2.3 it should now work without the extra Task needed when calling from the UI thread :)

**Comment by Transigent** [comment]
I forgot to say thank you for the support JKorf, we all appreciate it immensely. I tried the new version and it works great.

Thanks again.

**Comment by JKorf** [comment]
Thanks for the kind words, appreciated :)
