### ISSUE TITLE
startup problem

### ISSUE THREAD

**Issue by xaxoto** [JKorf/Binance.Net#1100]
Hello, how to configure the program so that it can be started. I can't find in which file the API KEY is put and when I start it says "Binance.Net-master\Binance.Net\Objects\BinanceClientOptions.cs>144> BinanceApiAddresses.Default.BlvtSocketClientAddress" that it is empty and can't make the EXE file.

**Comment by HypsyNZ** [comment]
This is not a valid issue.

**Comment by xaxoto** [comment]
And why isn't it a valid question? This is a problem for me and that is why I am asking about it.
If he had answered me instead of writing that this was not a question.

**Comment by HypsyNZ** [comment]
You haven't provided enough information to help you.

**Comment by xaxoto** [comment]
That's all I get when I try to start building.
![errors](https://user-images.githubusercontent.com/44766471/172540045-9d5528cd-433c-467f-8e22-34185289cbee.jpg)

**Comment by ngothanhluan** [comment]
Please learn .net programing before starting on this.

**Comment by xaxoto** [comment]
I guess I'm a little familiar with .net, I've been working with visual studio, VB, C #, SQL and PHP for 20 years

**Comment by JKorf** [comment]
The project isn't an executable, it's a library which you can use from your own code. Have a look at the documentation
