### ISSUE TITLE
format for GetIncomeHistory, 

### ISSUE THREAD

**Issue by thomasd3** [JKorf/Binance.Net#1101]
I am doing this (F#):

    let types = "REALIZED_PNL;COMMISSION"   // no space
    let! result = rest.UsdFuturesApi.Account.GetIncomeHistoryAsync(incomeType = types, limit = 1000) |> Async.AwaitTask

and get from Binance:

    -1130:Data sent for parameter 'incomeType' is not valid.

Is it even possible to send several income types in a single request?

**Comment by JKorf** [comment]
I don't think you can send multiple entries. It should be 1 value or omitted to receive all types

**Comment by thomasd3** [comment]
Confirmed on the Binance side.
