### ISSUE TITLE
Lot size filter is not work.

### ISSUE THREAD

**Issue by farukborann** [JKorf/Binance.Net#1102]
Client =>
`client = new BinanceClient(new BinanceClientOptions() { ApiCredentials = new ApiCredentials(apiKey, apiSecret), UsdFuturesApiOptions = new BinanceApiClientOptions() { TradeRulesBehaviour = TradeRulesBehaviour.AutoComply } });`

I'm try to place order async : 
`client.UsdFuturesApi.Trading.PlaceOrderAsync(symbol, orderSideClose, FuturesOrderType.TakeProfitMarket, balance / stopPrice * leverage *20/100, stopPrice: stopPrice, positionSide: positionSide, workingType: WorkingType.Mark);`

But its return => 
`Precision is over the maximum defined for this asset.`

I tried to use =>
`var exchangeInfo = await client.UsdFuturesApi.ExchangeData.GetExchangeInfoAsync();`
 `var symbolData = exchangeInfo.Data.Symbols.SingleOrDefault(x => string.Equals(x.Name.ToLower(), symbol.ToLower(), StringComparison.CurrentCultureIgnoreCase));`
`var minQty = symbolData!.LotSizeFilter?.MinQuantity;`
`var maxQty = symbolData!.LotSizeFilter?.MaxQuantity;`
`var stepSize = symbolData!.LotSizeFilter?.StepSize;`
`stopPrice = BinanceHelpers.ClampQuantity(minQty!.Value, maxQty!.Value, stepSize, (decimal)stopPrice);`
And it's not work for me.

I tried this too =>
`var stepSize = (decimal)Math.Pow(10, -BitConverter.GetBytes(decimal.GetBits(symbolData!.PriceFilter!.MinPrice)[3])[2]);`
 `stopPrice = BinanceHelpers.ClampQuantity(minQty!.Value, maxQty!.Value, stepSize, (decimal)stopPrice);`
It's look like work for me. But it's not the best way for fix this and i this this will not be work maybe.
How can i fix it ?
Note : I find manually lot size in here => https://www.binance.com/api/v1/exchangeInfo
It's not look like right cause in there lot size = 0.1 but i will be order like this => 1.542 or 5.135 (lot size 3)
Lot size filter working normally for price. But not for stopPrice.

And i have a another question.
Binance.net have any auto max long/short qty calculator function ?
I found this about it : [https://bnb-prod-mbx-forum-uploads.s3.dualstack.ap-northeast-1.amazonaws.com/original/2X/5/53de512ecf88e5b68b6aa53c45bc2aed15fb4fe9.png](https://bnb-prod-mbx-forum-uploads.s3.dualstack.ap-northeast-1.amazonaws.com/original/2X/5/53de512ecf88e5b68b6aa53c45bc2aed15fb4fe9.png)

**Comment by JKorf** [comment]
Has been fixed. There are no such calculations in the library atm.
