### ISSUE TITLE
SpotStreams not working?

### ISSUE THREAD

**Issue by andresdrb** [JKorf/Binance.Net#1103]
Is anyone aware of the spot streams not working? I stopped receiving updates sometime earlier today...

**Comment by HypsyNZ** [comment]
Are you still having issues with this?

**Comment by andresdrb** [comment]
Seems to be working now. Any idea what happened with it?

Obtener Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: HypsyNZ ***@***.***>
Enviado: Tuesday, June 14, 2022 4:10:48 PM
Para: JKorf/Binance.Net ***@***.***>
Cc: andresdrb ***@***.***>; Author ***@***.***>
Asunto: Re: [JKorf/Binance.Net] SpotStreams not working? (Issue #1103)


Are you still having issues with this?

**Comment by HypsyNZ** [comment]
It is likely you didn't keep the connection alive

**Comment by andresdrb** [comment]
I’ve had it working for months and in my code I have all that is required for the KeepAlive

Obtener Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: HypsyNZ ***@***.***>
Enviado: Wednesday, June 15, 2022 6:10:47 AM
Para: JKorf/Binance.Net ***@***.***>
Cc: andresdrb ***@***.***>; Author ***@***.***>
Asunto: Re: [JKorf/Binance.Net] SpotStreams not working? (Issue #1103)


It is likely you didn't keep the connection alive
