### ISSUE TITLE
Error when Get Position ADL Quantile Estimation

### ISSUE THREAD

**Issue by prandini** [JKorf/Binance.Net#1107]
**Describe the bug**
Error when call 
binanceClient.UsdFuturesApi.Account.GetPositionAdlQuantileEstimationAsync(Symbol);

**To Reproduce**
Open a position on futures, and call method above.

**Expected behavior**
return List<AdlQuantileResponseModel> without error

**Debug logging**
2022/06/28 00:25:52:114 | Error | Binance    | [2] Deserialize JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.IEnumerable`1[Binance.Net.Objects.Models.Futures.BinanceFuturesQuantileEstimation]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'symbol', line 1, position 10., data: [Data only available in Trace LogLevel]

******************
binanceClient.UsdFuturesApi.Account.GetPositionAdlQuantileEstimationAsync(Symbol);

Error.Message:
Deserialize JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.IEnumerable`1[Binance.Net.Objects.Models.Futures.BinanceFuturesQuantileEstimation]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'symbol', line 1, position 10.

**Comment by prandini** [comment]
Hi, anyone having this problem?

the call isn`t working.


Can i fix it and send a pull request?

**Comment by JKorf** [comment]
What about if you don't specify a symbol?

**Comment by JKorf** [comment]
Should be fixed
