### ISSUE TITLE
Sorry for the duplicate, but is there a US testnet?

### ISSUE THREAD

**Issue by kevindarby** [JKorf/Binance.Net#1109]
"https://testnet.binance.vision"

^---- is that for US?  

"wss://testnet.binance.vision",
^--- is this the wss address?

Thanks

**Comment by prozerran** [comment]
Hi, i'm also in the same situation. Does this library have an option to connect to a testnet? Such as....

https://testnet.binance.vision/api
wss://testnet.binance.vision/ws
wss://testnet.binance.vision/stream

Or how would i switch it to using a testnet?!?!?!?

**Comment by JKorf** [comment]
I don't think there is a separate testnet for US, but you should be able to use the normal testnet for testing. 
See https://jkorf.github.io/CryptoExchange.Net/FAQ.html#can-i-use-the-testnetusother-api-with-this-library
