### ISSUE TITLE
API-key format invalid.

### ISSUE THREAD

**Issue by ilyushinandy** [JKorf/Binance.Net#1110]
After updating the library from 8.0.4 to 8.1.3, when sending the api key and the secret key, the following is the next response from binance - / Info / Binance / [8] Creating a request for https://api.binance.com/api/v3/account - {"code":-2014,"msg":"Invalid API key format".}
The keys were copied from the wallet, tell me what has changed and how to fix it?

**Comment by JKorf** [comment]
There shouldn't have been any change. Make sure the key/secret is correct. You can also try generating a new key/secret and see if that helps.

**Comment by ilyushinandy** [comment]
The problem is solved by generating new key/secret.
