### ISSUE TITLE
WebSockets ListenKey

### ISSUE THREAD

**Issue by SlavaTT** [JKorf/Binance.Net#1112]
WebSockets ListenKey does not exist in objects, it is helpfull to have it, I parsed it from OriginalData JSON.
Now I'd like to added it, to BinanceStreamEvent ?
Will make a PR today

**Comment by JKorf** [comment]
Not sure what you mean with this

**Comment by SlavaTT** [comment]
I mean that there is listen key in raw json data, and it does not exist in parsed response. It is usefull to look up/macth related subscription in an array if you have multiple ones. But it looks like object needs to be changed to include it.

**Comment by JKorf** [comment]
What call/object are we talking about?

**Comment by SlavaTT** [comment]
Hello JKorf, 
{"stream":"eHYTcqVgrEZReQuC61RfKU8E94OioLxxCukoI7IsP3kb4gXpyy0rBLtYCb5RpN3I","data":{"e":"ACCOUNT_UPDATE","T":1659398400138,"E":1659398400209,"i":"FzoCuXSgsRTiAuXq","a":{"B":[{"a":"DOGE","wb":"253.35703735","cw":"253.35703735","bc":"0.04379962"}],"P":[],"m":"FUNDING_FEE"}}}
This is JSON from account update, I meant this stream identifier is not deserialized. I deserialized it separatelly, taking from OriginalData.

**Comment by JKorf** [comment]
I see, it's been added to version 8.1.8
