### ISSUE TITLE
Bug in GetMarginMaxTransferAmountAsync

### ISSUE THREAD

**Issue by hcanak** [JKorf/Binance.Net#1114]
Hi,

GetMarginMaxTransferAmountAsync() method does not return the "amount" ? Can you check?

![image](https://user-images.githubusercontent.com/79494507/178444678-41e85a99-8758-4073-aa50-6a1523a7a21e.png)

**Comment by JKorf** [comment]
The result is a decimal, which is the amount property

**Comment by hcanak** [comment]
Oh, thank you @JKorf :)
