### ISSUE TITLE
Missing Enum-Type "TRD_GRP_004" in Binance.Net.Enums.AccountType

### ISSUE THREAD

**Issue by mga70** [JKorf/Binance.Net#1115]
Error-Message:
Cannot map enum value. EnumType: Binance.Net.Enums.AccountType, Value: TRD_GRP_004, Known values: SPOT, MARGIN, FUTURES, LEVERAGED, TRD_GRP_002, TRD_GRP_003. If you think TRD_GRP_004 should added please open an issue on the Github repo

Could solve it with a local repo copy:
AccountTypeConverter.Mapping -> Add: **new KeyValuePair<AccountType, string>(AccountType.TradeGroup004, "TRD_GRP_004")**
Binance.Net.Enums.AccountType -> Add: **TradeGroup004**

**Comment by JanKorf** [comment]
Has been fixed in 8.1.5

**Comment by JKorf** [comment]
Has been fixed in 8.1.5
