### ISSUE TITLE
'Signature for this request is not valid' for one specific Universal Transfer (Margin to Isolated Margin)

### ISSUE THREAD

**Issue by eduardobellotto** [JKorf/Binance.Net#1118]
Hi.

I've receiving the error ```-1022 - Signature for this request is not valid``` in Universal transfer "Margin to Isolated Margin".

I'm using version 8.1.5, my API Key permissions, and the Secret Key are correct.

Example code that returns  the error:

```var callResult = client.SpotApi.Account.TransferAsync(UniversalTransferType.MarginToIsolatedMargin, "BUSD", 14M, null, "ADABUSD").Result;```

I already tryied to change 'fromSymbol' and 'toSymbol' data, without success.

Interestingly, the opposite direction (Isolated Margin to Margin) is working fine:

```var callResult = traderClient.SpotApi.Account.TransferAsync(UniversalTransferType.IsolatedMarginToMargin, "BUSD", 14M, "ADABUSD", null).Result;```

This is the link for the documentation:
https://binance-docs.github.io/apidocs/spot/en/#user-universal-transfer-user_data

Could you check it, please?

Thanks in advance!

**Comment by eduardobellotto** [comment]
I noticed that the wrong signature has a plus sign (+) at the end, in the request body.

Wrong signature:

```amount=14&asset=BUSD&recvWindow=5000&signature=XXXXXXXXXXXXXXXX&timestamp=1657676754362&toSymbol=ADABUSD&type=MARGIN_ISOLATEDMARGIN+```

Correct signature:

```amount=14&asset=BUSD&fromSymbol=ADABUSD&recvWindow=5000&signature=XXXXXXXXXXXXXXXX&timestamp=1657676723651&type=ISOLATEDMARGIN_MARGIN```

Maybe this is the reason.

**Comment by JKorf** [comment]
This should be fixed in the latest versions, there was a sneaky space hiding in some string..

**Comment by eduardobellotto** [comment]
Thank you very much!
