### ISSUE TITLE
Binance.Net 3.1.15 isn't compatible with CryptoExchange.Net 0.0.33

### ISSUE THREAD

**Issue by NektoDron** [JKorf/Binance.Net#112]
Severity	Code	Description	Project	File	Line	Suppression State
Error		Unable to resolve dependencies. 'CryptoExchange.Net 0.0.33' is not compatible with 'Binance.Net 3.1.15 constraint: CryptoExchange.Net (= 0.0.31)', 'Bitfinex.Net 1.1.4 constraint: CryptoExchange.Net (= 0.0.31)', 'Bittrex.Net 2.1.10 constraint: CryptoExchange.Net (= 0.0.31)'.			0

**Comment by JKorf** [comment]
That is done deliberately, new versions of CryptoExchange.Net are not necessarily compatible with all implementation versions. The newest version of the different libraries will have the same restrictions, ie Bittrex, Bitfinex and Binance all use 0.0.31 at the moment. CryptoExchange.Net isn't meant to be updated  on its own. 

CryptoExchange.Net 0.0.33 doesn't add any value for the existing libraries, some changes have been made for the implementation of a new exchange.
