### ISSUE TITLE
SubscribeToUserDataUpdatesAsync() not working properly

### ISSUE THREAD

**Issue by Digitalmatiq** [JKorf/Binance.Net#1120]
I've been trying to use the `SubscribeToUserDataUpdatesAsync()` function. However I'm pretty sure my implementation is correct, the `onOrderUpdate ` action is not triggering at all. My Implementation is as follows:

```
binanceClient.UsdFuturesApi.Account.StartUserStreamAsync()
				.GetAwaiter().GetResult().GetResultOrError(out var listenKey, out var error);

binanceSocketClient.UsdFuturesStreams.SubscribeToUserDataUpdatesAsync(listenKey,
				onListenKeyExpired: null,
				onLeverageUpdate: null,
				onMarginUpdate: null,
				onAccountUpdate: null,
				onOrderUpdate: this.OnOrderUpdate)
					.GetAwaiter().GetResult().GetResultOrError(out this._orderSubscription, out var streamError);
```

So practically my `this.OnOrderUpdate` function never gets called. The way I'm trying to make this work is after sending an order (also via the `binanceClient`) that which I confirm it works. Also my tick feed subscription seem to work as well.

After having enabled `LogLevel.Trace` on the `binanceSocketClient` I also receive the following:

> 2022/07/16 23:29:22:832 | Trace | Binance    | Client configuration: LogLevel: Trace, Writers: 1, OutputOriginalData: False, Proxy: -, Base.ApiCredentials: set, AutoReconnect: True, ReconnectInterval: 00:00:00, MaxConcurrentResubscriptionsPerSocket: 5, SocketResponseTimeout: 00:00:10, SocketNoDataTimeout: 00:00:00, SocketSubscriptionsCombineTarget: 10, MaxSocketConnections: , CryptoExchange.Net: v5.2.1.0, Binance.Net: v8.1.6.0
> 2022/07/16 23:29:22:837 | Trace | Binance    |   BinanceSocketClientSpotStreams configuration: Credentials: -, BaseAddress: wss://stream.binance.com:9443/
> 2022/07/16 23:29:22:839 | Trace | Binance    |   BinanceSocketClientUsdFuturesStreams configuration: Credentials: -, BaseAddress: wss://stream.binancefuture.com/ws
> 2022/07/16 23:29:22:841 | Trace | Binance    |   BinanceSocketClientCoinFuturesStreams configuration: Credentials: -, BaseAddress: wss://dstream.binance.com/
> 2022/07/16 23:29:22:856 | Information | Binance    | [1] Creating request for https://testnet.binancefuture.com/fapi/v1/positionSide/dual
> 2022/07/16 23:29:23:254 | Information | Binance    | [2] Creating request for https://testnet.binancefuture.com/fapi/v1/listenKey
> 2022/07/16 23:29:24:002 | Debug | Binance    | Socket 1 new socket created for wss://stream.binancefuture.com/ws/stream
> 2022/07/16 23:29:24:016 | Debug | Binance    | Socket 1 adding new subscription with id 4, total subscriptions on connection: 1
> 2022/07/16 23:29:24:021 | Debug | Binance    | Socket 1 connecting
> 2022/07/16 23:29:25:179 | Debug | Binance    | Socket 1 connected to wss://stream.binancefuture.com/ws/stream
> 2022/07/16 23:29:25:181 | Debug | Binance    | Socket 1 status changed from None to Connected
> 2022/07/16 23:29:25:183 | Debug | Binance    | Socket 1 starting processing tasks
> 2022/07/16 23:29:25:206 | Trace | Binance    | Socket 1 sending data: {"method":"SUBSCRIBE","params":["fu1cwJ9mSIKHEq1f7hMXOO7mE0uNs7Ov22AJfWLhhfoF08dAxSUSR5qwJAVNAWN1"],"id":3}
> 2022/07/16 23:29:25:208 | Trace | Binance    | Socket 1 Adding 107 to sent buffer
> 2022/07/16 23:29:25:221 | Trace | Binance    | Socket 1 sent 107 bytes
> 2022/07/16 23:29:25:491 | Trace | Binance    | Socket 1 received 22 bytes in single message
> 2022/07/16 23:29:25:494 | Trace | Binance    | Socket 1 received data: {"id":3,"result":null}
> 2022/07/16 23:29:25:498 | Trace | Binance    | Socket 1 Subscription completed
> 2022/07/16 23:29:25:500 | Information | Binance    | Socket 1 subscription 4 completed successfully
> 2022/07/16 23:29:25:504 | Information | Binance    | [5] Creating request for https://testnet.binancefuture.com/fapi/v2/account
> 2022/07/16 23:29:27:012 | Information | Binance    | [6] Creating request for https://testnet.binancefuture.com/fapi/v1/order
> 2022/07/16 23:29:27:764 | Trace | Binance    | Socket 1 received 408 bytes in single message
> 2022/07/16 23:29:27:766 | Trace | Binance    | Socket 1 received data: {"e":"ORDER_TRADE_UPDATE","T":1658003368255,"E":1658003368258,"o":{"s":"BTCUSDT","c":"69ac1178-a4fa-43f9-b27e-69ec1c5b0e19","S":"BUY","o":"MARKET","f":"GTC","q":"0.010","p":"0","ap":"0","sp":"0","x":"NEW","X":"NEW","i":3072453155,"l":"0","z":"0","L":"0","T":1658003368255,"t":0,"b":"0","a":"0","m":false,"R":false,"wt":"CONTRACT_PRICE","ot":"MARKET","ps":"LONG","cp":false,"rp":"0","pP":false,"si":0,"ss":0}}
> 2022/07/16 23:29:27:771 | Warning | Binance    | Socket 1 Message not handled: {
>   "e": "ORDER_TRADE_UPDATE",
>   "T": 1658003368255,
>   "E": 1658003368258,
>   "o": {
>     "s": "BTCUSDT",
>     "c": "69ac1178-a4fa-43f9-b27e-69ec1c5b0e19",
>     "S": "BUY",
>     "o": "MARKET",
>     "f": "GTC",
>     "q": "0.010",
>     "p": "0",
>     "ap": "0",
>     "sp": "0",
>     "x": "NEW",
>     "X": "NEW",
>     "i": 3072453155,
>     "l": "0",
>     "z": "0",
>     "L": "0",
>     "T": 1658003368255,
>     "t": 0,
>     "b": "0",
>     "a": "0",
>     "m": false,
>     "R": false,
>     "wt": "CONTRACT_PRICE",
>     "ot": "MARKET",
>     "ps": "LONG",
>     "cp": false,
>     "rp": "0",
>     "pP": false,
>     "si": 0,
>     "ss": 0
>   }
> }
> 2022/07/16 23:29:27:773 | Trace | Binance    | Socket 1 subscription 4 message processed in 6ms, (0ms user code)
> 2022/07/16 23:29:27:774 | Trace | Binance    | Socket 1 received 512 bytes in single message
> 2022/07/16 23:29:27:776 | Trace | Binance    | Socket 1 received data: {"e":"ACCOUNT_UPDATE","T":1658003368255,"E":1658003368258,"a":{"B":[{"a":"USDT","wb":"2949.19157427","cw":"2949.19157427","bc":"0"}],"P":[{"s":"BTCUSDT","pa":"0","ep":"0.00000","cr":"-4.01760000","up":"0","mt":"cross","iw":"0","ps":"BOTH","ma":"USDT"},{"s":"BTCUSDT","pa":"0.080","ep":"20985.38000","cr":"2.51520002","up":"-1.95809900","mt":"cross","iw":"0","ps":"LONG","ma":"USDT"},{"s":"BTCUSDT","pa":"0","ep":"0.00000","cr":"-1.14000000","up":"0","mt":"cross","iw":"0","ps":"SHORT","ma":"USDT"}],"m":"ORDER"}}
> 2022/07/16 23:29:27:777 | Warning | Binance    | Socket 1 Message not handled: {
>   "e": "ACCOUNT_UPDATE",
>   "T": 1658003368255,
>   "E": 1658003368258,
>   "a": {
>     "B": [
>       {
>         "a": "USDT",
>         "wb": "2949.19157427",
>         "cw": "2949.19157427",
>         "bc": "0"
>       }
>     ],
>     "P": [
>       {
>         "s": "BTCUSDT",
>         "pa": "0",
>         "ep": "0.00000",
>         "cr": "-4.01760000",
>         "up": "0",
>         "mt": "cross",
>         "iw": "0",
>         "ps": "BOTH",
>         "ma": "USDT"
>       },
>       {
>         "s": "BTCUSDT",
>         "pa": "0.080",
>         "ep": "20985.38000",
>         "cr": "2.51520002",
>         "up": "-1.95809900",
>         "mt": "cross",
>         "iw": "0",
>         "ps": "LONG",
>         "ma": "USDT"
>       },
>       {
>         "s": "BTCUSDT",
>         "pa": "0",
>         "ep": "0.00000",
>         "cr": "-1.14000000",
>         "up": "0",
>         "mt": "cross",
>         "iw": "0",
>         "ps": "SHORT",
>         "ma": "USDT"
>       }
>     ],
>     "m": "ORDER"
>   }
> }
> 2022/07/16 23:29:27:779 | Trace | Binance    | Socket 1 subscription 4 message processed in 2ms, (0ms user code)
> 2022/07/16 23:29:27:780 | Trace | Binance    | Socket 1 received 474 bytes in single message
> 2022/07/16 23:29:27:782 | Trace | Binance    | Socket 1 received data: {"e":"ORDER_TRADE_UPDATE","T":1658003368255,"E":1658003368258,"o":{"s":"BTCUSDT","c":"69ac1178-a4fa-43f9-b27e-69ec1c5b0e19","S":"BUY","o":"MARKET","f":"GTC","q":"0.010","p":"0","ap":"20962.60000","sp":"0","x":"TRADE","X":"FILLED","i":3072453155,"l":"0.010","z":"0.010","L":"20962.60","n":"0.08385040","N":"USDT","T":1658003368255,"t":236038005,"b":"0","a":"0","m":false,"R":false,"wt":"CONTRACT_PRICE","ot":"MARKET","ps":"LONG","cp":false,"rp":"0","pP":false,"si":0,"ss":0}}
> 2022/07/16 23:29:27:783 | Warning | Binance    | Socket 1 Message not handled: {
>   "e": "ORDER_TRADE_UPDATE",
>   "T": 1658003368255,
>   "E": 1658003368258,
>   "o": {
>     "s": "BTCUSDT",
>     "c": "69ac1178-a4fa-43f9-b27e-69ec1c5b0e19",
>     "S": "BUY",
>     "o": "MARKET",
>     "f": "GTC",
>     "q": "0.010",
>     "p": "0",
>     "ap": "20962.60000",
>     "sp": "0",
>     "x": "TRADE",
>     "X": "FILLED",
>     "i": 3072453155,
>     "l": "0.010",
>     "z": "0.010",
>     "L": "20962.60",
>     "n": "0.08385040",
>     "N": "USDT",
>     "T": 1658003368255,
>     "t": 236038005,
>     "b": "0",
>     "a": "0",
>     "m": false,
>     "R": false,
>     "wt": "CONTRACT_PRICE",
>     "ot": "MARKET",
>     "ps": "LONG",
>     "cp": false,
>     "rp": "0",
>     "pP": false,
>     "si": 0,
>     "ss": 0
>   }
> }
> 2022/07/16 23:29:27:785 | Trace | Binance    | Socket 1 subscription 4 message processed in 2ms, (0ms user code)

It does receive something on the websocket so I guess it's something that I'm missing
Am I doing something wrong or is this a bug ?

**Comment by HypsyNZ** [comment]
> I've been trying to use the `SubscribeToUserDataUpdatesAsync()` function. However I'm pretty sure my implementation is correct, the `onOrderUpdate ` action is not triggering at all. My Implementation is as follows:
> 
> ```
> binanceClient.UsdFuturesApi.Account.StartUserStreamAsync()
> 				.GetAwaiter().GetResult().GetResultOrError(out var listenKey, out var error);
> 
> binanceSocketClient.UsdFuturesStreams.SubscribeToUserDataUpdatesAsync(listenKey,
> 				onListenKeyExpired: null,
> 				onLeverageUpdate: null,
> 				onMarginUpdate: null,
> 				onAccountUpdate: null,
> 				onOrderUpdate: this.OnOrderUpdate)
> 					.GetAwaiter().GetResult().GetResultOrError(out this._orderSubscription, out var streamError);
> ```
> 
> So practically my `this.OnOrderUpdate` function never gets called. The way I'm trying to make this work is after sending an order (also via the `binanceClient`) that which I confirm it works. Also my tick feed subscription seem to work as well.
> 
> After having enabled `LogLevel.Trace` on the `binanceSocketClient` I also receive the following:
> 
> > 2022/07/16 23:29:22:832 | Trace | Binance    | Client configuration: LogLevel: Trace, Writers: 1, OutputOriginalData: False, Proxy: -, Base.ApiCredentials: set, AutoReconnect: True, ReconnectInterval: 00:00:00, MaxConcurrentResubscriptionsPerSocket: 5, SocketResponseTimeout: 00:00:10, SocketNoDataTimeout: 00:00:00, SocketSubscriptionsCombineTarget: 10, MaxSocketConnections: , CryptoExchange.Net: v5.2.1.0, Binance.Net: v8.1.6.0
> > 2022/07/16 23:29:22:837 | Trace | Binance    |   BinanceSocketClientSpotStreams configuration: Credentials: -, BaseAddress: wss://stream.binance.com:9443/
> > 2022/07/16 23:29:22:839 | Trace | Binance    |   BinanceSocketClientUsdFuturesStreams configuration: Credentials: -, BaseAddress: wss://stream.binancefuture.com/ws
> > 2022/07/16 23:29:22:841 | Trace | Binance    |   BinanceSocketClientCoinFuturesStreams configuration: Credentials: -, BaseAddress: wss://dstream.binance.com/
> > 2022/07/16 23:29:22:856 | Information | Binance    | [1] Creating request for https://testnet.binancefuture.com/fapi/v1/positionSide/dual
> > 2022/07/16 23:29:23:254 | Information | Binance    | [2] Creating request for https://testnet.binancefuture.com/fapi/v1/listenKey
> > 2022/07/16 23:29:24:002 | Debug | Binance    | Socket 1 new socket created for wss://stream.binancefuture.com/ws/stream
> > 2022/07/16 23:29:24:016 | Debug | Binance    | Socket 1 adding new subscription with id 4, total subscriptions on connection: 1
> > 2022/07/16 23:29:24:021 | Debug | Binance    | Socket 1 connecting
> > 2022/07/16 23:29:25:179 | Debug | Binance    | Socket 1 connected to wss://stream.binancefuture.com/ws/stream
> > 2022/07/16 23:29:25:181 | Debug | Binance    | Socket 1 status changed from None to Connected
> > 2022/07/16 23:29:25:183 | Debug | Binance    | Socket 1 starting processing tasks
> > 2022/07/16 23:29:25:206 | Trace | Binance    | Socket 1 sending data: {"method":"SUBSCRIBE","params":["fu1cwJ9mSIKHEq1f7hMXOO7mE0uNs7Ov22AJfWLhhfoF08dAxSUSR5qwJAVNAWN1"],"id":3}
> > 2022/07/16 23:29:25:208 | Trace | Binance    | Socket 1 Adding 107 to sent buffer
> > 2022/07/16 23:29:25:221 | Trace | Binance    | Socket 1 sent 107 bytes
> > 2022/07/16 23:29:25:491 | Trace | Binance    | Socket 1 received 22 bytes in single message
> > 2022/07/16 23:29:25:494 | Trace | Binance    | Socket 1 received data: {"id":3,"result":null}
> > 2022/07/16 23:29:25:498 | Trace | Binance    | Socket 1 Subscription completed
> > 2022/07/16 23:29:25:500 | Information | Binance    | Socket 1 subscription 4 completed successfully
> > 2022/07/16 23:29:25:504 | Information | Binance    | [5] Creating request for https://testnet.binancefuture.com/fapi/v2/account
> > 2022/07/16 23:29:27:012 | Information | Binance    | [6] Creating request for https://testnet.binancefuture.com/fapi/v1/order
> > 2022/07/16 23:29:27:764 | Trace | Binance    | Socket 1 received 408 bytes in single message
> > 2022/07/16 23:29:27:766 | Trace | Binance    | Socket 1 received data: {"e":"ORDER_TRADE_UPDATE","T":1658003368255,"E":1658003368258,"o":{"s":"BTCUSDT","c":"69ac1178-a4fa-43f9-b27e-69ec1c5b0e19","S":"BUY","o":"MARKET","f":"GTC","q":"0.010","p":"0","ap":"0","sp":"0","x":"NEW","X":"NEW","i":3072453155,"l":"0","z":"0","L":"0","T":1658003368255,"t":0,"b":"0","a":"0","m":false,"R":false,"wt":"CONTRACT_PRICE","ot":"MARKET","ps":"LONG","cp":false,"rp":"0","pP":false,"si":0,"ss":0}}
> > 2022/07/16 23:29:27:771 | Warning | Binance    | Socket 1 Message not handled: {
> > "e": "ORDER_TRADE_UPDATE",
> > "T": 1658003368255,
> > "E": 1658003368258,
> > "o": {
> > "s": "BTCUSDT",
> > "c": "69ac1178-a4fa-43f9-b27e-69ec1c5b0e19",
> > "S": "BUY",
> > "o": "MARKET",
> > "f": "GTC",
> > "q": "0.010",
> > "p": "0",
> > "ap": "0",
> > "sp": "0",
> > "x": "NEW",
> > "X": "NEW",
> > "i": 3072453155,
> > "l": "0",
> > "z": "0",
> > "L": "0",
> > "T": 1658003368255,
> > "t": 0,
> > "b": "0",
> > "a": "0",
> > "m": false,
> > "R": false,
> > "wt": "CONTRACT_PRICE",
> > "ot": "MARKET",
> > "ps": "LONG",
> > "cp": false,
> > "rp": "0",
> > "pP": false,
> > "si": 0,
> > "ss": 0
> > }
> > }
> > 2022/07/16 23:29:27:773 | Trace | Binance    | Socket 1 subscription 4 message processed in 6ms, (0ms user code)
> > 2022/07/16 23:29:27:774 | Trace | Binance    | Socket 1 received 512 bytes in single message
> > 2022/07/16 23:29:27:776 | Trace | Binance    | Socket 1 received data: {"e":"ACCOUNT_UPDATE","T":1658003368255,"E":1658003368258,"a":{"B":[{"a":"USDT","wb":"2949.19157427","cw":"2949.19157427","bc":"0"}],"P":[{"s":"BTCUSDT","pa":"0","ep":"0.00000","cr":"-4.01760000","up":"0","mt":"cross","iw":"0","ps":"BOTH","ma":"USDT"},{"s":"BTCUSDT","pa":"0.080","ep":"20985.38000","cr":"2.51520002","up":"-1.95809900","mt":"cross","iw":"0","ps":"LONG","ma":"USDT"},{"s":"BTCUSDT","pa":"0","ep":"0.00000","cr":"-1.14000000","up":"0","mt":"cross","iw":"0","ps":"SHORT","ma":"USDT"}],"m":"ORDER"}}
> > 2022/07/16 23:29:27:777 | Warning | Binance    | Socket 1 Message not handled: {
> > "e": "ACCOUNT_UPDATE",
> > "T": 1658003368255,
> > "E": 1658003368258,
> > "a": {
> > "B": [
> > {
> > "a": "USDT",
> > "wb": "2949.19157427",
> > "cw": "2949.19157427",
> > "bc": "0"
> > }
> > ],
> > "P": [
> > {
> > "s": "BTCUSDT",
> > "pa": "0",
> > "ep": "0.00000",
> > "cr": "-4.01760000",
> > "up": "0",
> > "mt": "cross",
> > "iw": "0",
> > "ps": "BOTH",
> > "ma": "USDT"
> > },
> > {
> > "s": "BTCUSDT",
> > "pa": "0.080",
> > "ep": "20985.38000",
> > "cr": "2.51520002",
> > "up": "-1.95809900",
> > "mt": "cross",
> > "iw": "0",
> > "ps": "LONG",
> > "ma": "USDT"
> > },
> > {
> > "s": "BTCUSDT",
> > "pa": "0",
> > "ep": "0.00000",
> > "cr": "-1.14000000",
> > "up": "0",
> > "mt": "cross",
> > "iw": "0",
> > "ps": "SHORT",
> > "ma": "USDT"
> > }
> > ],
> > "m": "ORDER"
> > }
> > }
> > 2022/07/16 23:29:27:779 | Trace | Binance    | Socket 1 subscription 4 message processed in 2ms, (0ms user code)
> > 2022/07/16 23:29:27:780 | Trace | Binance    | Socket 1 received 474 bytes in single message
> > 2022/07/16 23:29:27:782 | Trace | Binance    | Socket 1 received data: {"e":"ORDER_TRADE_UPDATE","T":1658003368255,"E":1658003368258,"o":{"s":"BTCUSDT","c":"69ac1178-a4fa-43f9-b27e-69ec1c5b0e19","S":"BUY","o":"MARKET","f":"GTC","q":"0.010","p":"0","ap":"20962.60000","sp":"0","x":"TRADE","X":"FILLED","i":3072453155,"l":"0.010","z":"0.010","L":"20962.60","n":"0.08385040","N":"USDT","T":1658003368255,"t":236038005,"b":"0","a":"0","m":false,"R":false,"wt":"CONTRACT_PRICE","ot":"MARKET","ps":"LONG","cp":false,"rp":"0","pP":false,"si":0,"ss":0}}
> > 2022/07/16 23:29:27:783 | Warning | Binance    | Socket 1 Message not handled: {
> > "e": "ORDER_TRADE_UPDATE",
> > "T": 1658003368255,
> > "E": 1658003368258,
> > "o": {
> > "s": "BTCUSDT",
> > "c": "69ac1178-a4fa-43f9-b27e-69ec1c5b0e19",
> > "S": "BUY",
> > "o": "MARKET",
> > "f": "GTC",
> > "q": "0.010",
> > "p": "0",
> > "ap": "20962.60000",
> > "sp": "0",
> > "x": "TRADE",
> > "X": "FILLED",
> > "i": 3072453155,
> > "l": "0.010",
> > "z": "0.010",
> > "L": "20962.60",
> > "n": "0.08385040",
> > "N": "USDT",
> > "T": 1658003368255,
> > "t": 236038005,
> > "b": "0",
> > "a": "0",
> > "m": false,
> > "R": false,
> > "wt": "CONTRACT_PRICE",
> > "ot": "MARKET",
> > "ps": "LONG",
> > "cp": false,
> > "rp": "0",
> > "pP": false,
> > "si": 0,
> > "ss": 0
> > }
> > }
> > 2022/07/16 23:29:27:785 | Trace | Binance    | Socket 1 subscription 4 message processed in 2ms, (0ms user code)
> 
> Am I doing something wrong or is this a bug ?

If you haven't edited the library this is a bug.

**Comment by Digitalmatiq** [comment]
> > > 2022/07/16 23:29:27:777 | Warning | Binance    | Socket 1 Message not handled: {
> 
> > Am I doing something wrong or is this a bug ?
> 
> If you haven't edited the library this is a bug.

I'm using the last version of the library.  Does that trace mean something is wrong then ?

**Comment by Digitalmatiq** [comment]
I figured out what the problem was. My socket connection address was wrong. I didn't know there was a static class with all those values. One should use those:

`BinanceApiAddresses.TestNet.UsdFuturesSocketClientAddress`
`BinanceApiAddresses.TestNet.UsdFuturesRestClientAddress`

Changed addresses to those above and then it worked. Closing this
