### ISSUE TITLE
Automapper exception with CryptoExchange.Net V5.*

### ISSUE THREAD

**Issue by saeedEzaziranjkeli** [JKorf/Binance.Net#1121]
**Describe the bug**
I use in my project AutoMapper and it works with CryptoExchange.Net v4.*, after migrate CryptoExchange.Net to v5.* I could not start my project and get this exception : 
'Unable to load one or more of the requested types.
Could not load type _**'CryptoExchange.Net.ExchangeInterfaces.ICommonOrderId'**_

**To Reproduce**
Add Automapper.extensions.Microsoft.DependencyInjection version 8.1.1 to project and in Startup:
services.AddAutoMapper(typeof(Startup).Assembly);
**or**  services.AddAutoMapper(AppDomain.CurrentDomain.GetAssemblies());

**Expected behavior**
You could not start your project

**Debug logging**
Unable to load one or more of the requested types.
Could not load type 'CryptoExchange.Net.ExchangeInterfaces.ICommonOrderId' from assembly 'CryptoExchange.Net, Version=5.2.2.0, Culture=neutral, PublicKeyToken=null'.

**Comment by JKorf** [comment]
Hi, ICommonOrderId is no longer a thing in 5.x, see https://jkorf.github.io/CryptoExchange.Net/Migration%20Guide.html
I think you might have a reference to an older version still somewhere in your project, or there is some caching happening. Either way, ICommonOrderId shouldnt be sought in version 5.
