### ISSUE TITLE
Effective Multiple

### ISSUE THREAD

**Issue by UzverUA** [JKorf/Binance.Net#1124]
Hi, is this endpoint missing? https://binance-docs.github.io/apidocs/spot/en/#query-isolated-margin-tier-data-user_data
I want to get Effective Multiple of a symbol. Searched documentation and "Issues" here and didn't find anything. Can someone, please, help me to figure it out?)

**Comment by HypsyNZ** [comment]
> Binance.Net.Interfaces.Clients.SpotApi.IBinanceClientSpotApiAccount.GetIsolatedMarginTierDataAsync

**Comment by HypsyNZ** [comment]
You can just search the xml file for future reference

![xml](https://user-images.githubusercontent.com/54571583/193134614-5a34a422-a07b-4daf-afe3-4ef696fad9b4.png)

**Comment by UzverUA** [comment]
Got it. Thanks man)
