### ISSUE TITLE
While listening future stream, can I add an additional symbol?

### ISSUE THREAD

**Issue by ertan2002** [JKorf/Binance.Net#1129]
Hi all

I have been developing a Rest API with .net core and have a question.

I can subscribe a coin list by using SubscribeToKlineUpdatesAsync method without problem. But my users will be able to add extra symbols while the webservice is working.
 
Is it possible to do that without stop/pause and update my list or insert the new symbol?

Or if I call my method again with only the new symbol (I mean if I call several times SubscribeToKlineUpdatesAsync with my new symbol as a parameter)? 

What is the best approach?

**Comment by ertan2002** [comment]
For update:

I think SubscribeToKlineUpdatesAsync  method works. When I have a new symbol, I just call SubscribeToKlineUpdatesAsync  method again and it addes the list.. but I am not sure if it is the best apporach.. Could you please give a quick explanation?

**Comment by JKorf** [comment]
The library manages the socket connections internally. By default it combines 10 subscriptions on 1 socket connection and creates a new socket connection for the next 10 subscriptions. When you just call `SubscribeToKlineUpdatesAsync ` for an additional symbol it will add a new subscription on the current connection (or open a new connection if it already has 10 subscriptions on the current connection). 

If that is okay behavior is up to you to decide. You can control how many subscription are combined on a connection with the `SocketSubscriptionsCombineTarget` client option.

**Comment by ertan2002** [comment]
It sounds great. Thank you for your explanation.
