### ISSUE TITLE
Socket error No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by tttpco** [JKorf/Binance.Net#113]
Hi JKorf.

This is my socket subscription code:

```
            var socketClient = new BinanceSocketClient(new BinanceSocketClientOptions()
            {
                LogVerbosity = LogVerbosity.Debug
            });
            
            var successKline = socketClient
                .SubscribeToKlineStream(exchangeInstrument.Instrument.Code.ToLower(), 
                    KlineInterval.FiveMinutes, (data) =>
            {
                var priceData = data.Data;
                // handle data                               
            });
```

I set a breakpoint inside the block but it never fires, and in the console I see the following repeatedly:

```
Info | Connection lost, going to try to reconnect
Debug | Websocket connection failed, state: Closed
Debug | Connecting websocket
Error | Socket error No connection could be made because the target machine actively refused it
```

Thanks for your help and the very good work.

**Comment by JKorf** [comment]
Hi, judging from the logging no connection could be made to the Binance server. Can you verify your internet is working fine and it's not blocked (i.e. company networks might block these connections)

**Comment by tttpco** [comment]
I can request raw REST APIs from the postman successfully. So, I don't think that the problem be from the internet connection.

**Comment by JKorf** [comment]
The websocket uses a different protocol than the REST API. Is it possible for you to try from a different network?

**Comment by tttpco** [comment]
Yes I'll try it and come back here, soon.

**Comment by tttpco** [comment]
I connected to a VPN server and my code got the following error:

Error | Socket error A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

**Comment by tttpco** [comment]
My problem was from the network infrastructure of the country. I settled a VPN connection which supports web sockets, and the problem gone.

Thank you.

**Comment by JKorf** [comment]
Great, glad you managed to fix it
