### ISSUE TITLE
Leveraged Tokens Redeem not supported?

### ISSUE THREAD

**Issue by andresdrb** [JKorf/Binance.Net#1133]
**Describe the bug**
When trying to use the RedeemLeveragedTokenAsync on SpotApi  method I get "redeem asset not supported" as error message. Is this a problem of the Binance API? (they seem to support it) or the client?

![image](https://user-images.githubusercontent.com/9131538/183133444-a48e1885-1e4e-40fd-9b64-531fc053a59d.png)

**Comment by JKorf** [comment]
That would be something on the Binance API. Make sure you're sending the right parameters and have the right permissions, and contact Binance if you think there is an issue
