### ISSUE TITLE
orderbook fluctuations

### ISSUE THREAD

**Issue by dungtrandk** [JKorf/Binance.Net#1136]
Sometimes I detect high fluctuations in the orderbook.
In my case I am subscribed to SOL/USDT. What happens is that sometimes asks/bids gets returned from the API with values that are "not in line" with the other values. 

Here is an example of the binance sol/usdt ask prices:

**Timestamp     Ask**
10:12:36:710 - 57,84000000
10:12:36:907 - 57,61000000
10:12:37:108 - 47,81000000
10:12:37:209 - 57,38000000
10:12:37:409 - 57,15000000
10:12:37:607 - 47,37000000
10:12:37:708 - 56,91000000
10:12:37:907 - 56,68000000
10:12:38:273 - 47,37000000
10:12:38:365 - 47,37000000
10:12:38:481 - 47,37000000
10:12:38:714 - 56,00000000
10:12:38:810 - 47,37000000
10:12:38:911 - 47,49000000
10:12:39:109 - 47,38000000
10:12:39:209 - 55,55000000
10:12:39:412 - 55,32000000
10:12:39:708 - 55,10000000

As you can see, there is a huge fluctuation between 47'isch and 55'isch. 
The correct price range is 47'isch.

I am using your API for FTX as well and here I see the same problem.

How come this is?

**Comment by JKorf** [comment]
How are you using it? I assume you're subscribing to a stream?

**Comment by dungtrandk** [comment]
Yes i use the method **BinanceSocketClient.SpotStreams.SubscribeToOrderBookUpdatesAsync**.
And 100 as the update interval on the pair SOLUSDT.

What I want to achieve is to have an orderbook that shows bid/asks like the exchanges does it. fx:

![image](https://user-images.githubusercontent.com/39093451/186837766-13e96596-df40-43d7-92fe-80b5ce16eca6.png)

**Comment by dungtrandk** [comment]
One other thing. Just so that I understand it correctly.

When data comes in via the socket stream, and there are fx 4 asks and 3 bids.
Is it correctly understood that those asks and bids are the latest created limit orders on the order book?

Which means that data from the orderbook subscription on the socket stream, are incoming orders on the orderbook.

Then, if you want to know the outgoing orders (the actual trades) you need to subscribe to the trade updates on the socket.
So whenever there is a trade it means that either the bids or asks, previously mentioned, are reduced in quantity?
And that you wil  have to do this yourself?

Thanks by the way, for an awesome API :-)

**Comment by JKorf** [comment]
The stream you're subscribing to only gives updates to changes in the order book, so there is some synchronization logic needed there. You can use the `SubscribeToPartialOrderBookUpdatesAsync` method to subscribe to full updates for a part of the order book. Or you can have a look at the BinanceSpotSymbolOrderBook class, which has the synchronization logic implemented already. 

To answer your questions; the updates you receive from `SubscribeToOrderBookUpdatesAsync` are changes to the order book. These are either adds (new order at a new price), update (changed amount of total order value at a  price) or removes (order executed or canceled at a price point). There isn't a link between the change and the actual action which caused the change.
