### ISSUE TITLE
Quanity parameter should be invariant culture in all requests

### ISSUE THREAD

**Issue by GraniLuk** [JKorf/Binance.Net#1137]
**Describe the bug**
PurchaseStakingProductAsync and RedeemStakingProductAsync returns Bad Signature error, because quanity parameter is passed with wrong culture, it should always be passed formatted with InvariantCulture as other decimal parameters. 

**To Reproduce**
PurchaseStakingProductAsync and RedeemStakingProductAsync with any parameters.

**Expected behavior**
It should returns Success response.

**Debug logging**
Add debug logging related to the issue. Enable Debug logging in the client options by settings LogLevel to Debug.

It just needs to be changed to: 
{ "amount", quantity.ToString(CultureInfo.InvariantCulture) },

**Comment by HypsyNZ** [comment]
This issue made me check what year it is.

**Comment by JKorf** [comment]
Has been fixed
