### ISSUE TITLE
HOW TO: Close Position, get Trades, all trades with ClOrdId

### ISSUE THREAD

**Issue by prozerran** [JKorf/Binance.Net#1138]
Not really a bug, or missing feature, but how to....
I have several questions.....

1) Whats the API to call to close a futures position, either on USDM or COINM (Futures or Inverse Futures) [for both Limit and Market Close position]
2) How get to all trades (trade history) but the API seem to ONLY allow get all trades by Symbol, I just want to get all trades regardless of symbol. 
3) If and only when get all trades do return, I do not see the corresponding ClientOrderId return as well. I need to get ClOrdId.

These issues are for Futures and InvserseFutures (USDM and COINM)
Theres seem to work ok for Spot, but the above 3 issues exist for the 2 futures, how can i resolve it.

**Comment by JKorf** [comment]
1. Closing a position is making a new sell order for the amount you want to close, the same way you also placed the buy order.
2. Sadly this is not available (limitation of the Binance API)
3. Trades do not include a clientOrderId in their model, only an orderId. Again, this is a limitation of the API unfortunately.

**Comment by thebitbrine** [comment]
@JKorf 
Binance itself has an internal endpoint for getting trade history:
```https://www.binance.com/bapi/futures/v1/private/future/user-data/trade-history```

Implementing internal API endpoints can often be simple since it often uses the same auth method as the public ones.
I might personally get on this.
