### ISSUE TITLE
Cannot get TickSize from GetExchangeInfoAsync

### ISSUE THREAD

**Issue by trapdoor26** [JKorf/Binance.Net#1139]
Hello,

I think there is a problem at GetExchangeInfoAsync task.
As below screenshot, you may see that i try to get TickSize info under Filters.

But under Filters, only FilterType seems to appear.
But when investigating parent, you can see TickSize is there.

Can this problem be solved different way ?

![image](https://user-images.githubusercontent.com/79747343/186129469-9b55366c-c76b-49cb-afaf-ca36bf876992.png)

![image](https://user-images.githubusercontent.com/79747343/186129942-6bedc792-1b48-4d66-ac24-b00086117b35.png)

**Comment by JKorf** [comment]
You can use the specific filter accessor on the symbol,  for example `symbol.PriceFilter.TickSize`
