### ISSUE TITLE
Socket error

### ISSUE THREAD

**Issue by nikkozp** [JKorf/Binance.Net#114]
In the last update there was an error with sockets

2018.08.13 21: 50: 14: 009 / http / 1.1 404 socket error / error not found
2018.08.13 21: 50: 14: 012 / Info / connection Lost, attempt to reconnect

**Comment by JKorf** [comment]
Hi, it seems to work fine for me. What are you trying to do/what happens?

**Comment by nikkozp** [comment]
today I installed the latest version 
I didn't change anything in my code

and when there is a connection to sockets, there is an error in this moment

```
var successAccount = ws.Subscribe to User Stream(listenKey, 
data=>
{
//data
}, 
data=>{
//data
})


 successAccount.Data.Closed + = () =>
            {
            }; / / error here

```
error here, successAccount == null

**Comment by nikkozp** [comment]
and before you release a new version, please see 

CallResponse<long> ping = client.Ping()  

all the time he wants to return bool. Cannot convert bool to long

**Comment by nikkozp** [comment]
Thank you very much, you're the best :)

Cant update to 3.1.18

Could not find package "Binance.Net 3.1.18" in the following primary sources: "https://api.nuget.org/v3/index.json" Make sure that all Internet sources of packages are available (OR) that the package ID and version are correct.

**Comment by JKorf** [comment]
It takes a few minuten to be available on nuget, can you try again?

**Comment by nikkozp** [comment]
now is OK, thx
