### ISSUE TITLE
Speed on place order

### ISSUE THREAD

**Issue by dungtrandk** [JKorf/Binance.Net#1140]
Hi

I was wondering if anybody else would like to share how fast IT takes for you guys from placing a spot limit ordre in tour code, until the callback? In milliseconds/seconds.

My calls usually take between 500ms up to almost 1 second.

Can it somehow be done faster than this?

**Comment by JKorf** [comment]
With TradeRulesBehaviour not set to None it will request the trade rules first before placing the order, but this is not enabled by default. The other thing you can try is setting AutoTimestamp to false in the client options, which will prevent another initial request. You'll have to make sure your server time is in sync with the Binance server time though. 
Note that these things will only help for the first request in a while, when the library needs to resync these things.
