### ISSUE TITLE
Missing Enum-Type "TRD_GRP_005" in Binance.Net.Enums.AccountType

### ISSUE THREAD

**Issue by mga70** [JKorf/Binance.Net#1142]
Error-Message:
Cannot map enum value. EnumType: AccountType, Value: TRD_GRP_005, Known values: SPOT, MARGIN, FUTURES, LEVERAGED, TRD_GRP_002, TRD_GRP_003, TRD_GRP_004. If you think TRD_GRP_005 should added please open an issue on the Github repo.

**Comment by redquantum** [comment]
The problem persists after the last update.

Exception thrown: 'System.ArgumentException' in mscorlib.dll
2022.09.03 15:14:47:703 | Warning | Cannot map enum value. EnumType: AccountType, Value: TRD_GRP_005, Known values: SPOT, MARGIN, FUTURES, LEVERAGED, TRD_GRP_002, TRD_GRP_003, TRD_GRP_004. If you think TRD_GRP_005 should added please open an issue on the Github repo

**Comment by JKorf** [comment]
Fixed in version 8.1.10
