### ISSUE TITLE
Getting no data when GetKlinesAsync() called for OneMinute Interval

### ISSUE THREAD

**Issue by dumblearn** [JKorf/Binance.Net#1147]
Hi JKorf,
I am trying to get history data (UsdFuture) for one minute interval and I am getting no data when I call GetKlinesAsync() with Interval of OneMinute.

var result = await binanceClient.UsdFuturesApi.ExchangeData.GetKlinesAsync(symbol, interval, startTime, endTime);
result shows "Success" but Data.Count is zero

**Comment by JKorf** [comment]
Seems to work okay for me, what parameters are you using?
