### ISSUE TITLE
BestAskPrice is always 0 for SubscribeToTickerUpdatesAsync and SubscribeToAllTickerUpdatesAsync

### ISSUE THREAD

**Issue by port120** [JKorf/Binance.Net#1148]
BestAskPrice is always 0 for SubscribeToTickerUpdatesAsync and SubscribeToAllTickerUpdatesAsync. Is this correct? thx

 await socketClient.UsdFuturesStreams.SubscribeToTickerUpdatesAsync("BTCUSDT", dataAr =>
            {

                Console.WriteLine(dataAr.Data.Symbol + " " + dataAr.Data.BestAskPrice);

            });

using 8.1.10

**Comment by HypsyNZ** [comment]
The problem is you are trading futures.

I joke, I can't replicate this, because I don't trade futures.

that was another joke.

good luck.

**Comment by HypsyNZ** [comment]
Skill issue.

**Comment by HypsyNZ** [comment]
Did you solve this problem?

What have you tried to fix this?

is `socketClient` being disposed?

More people would be complaining if this was really an issue think about it.

**Comment by JKorf** [comment]
The futures streams used the same interface as the spot streams, however the futures stream doesn't include this information. I've adjusted the futures interface to reflect this
