### ISSUE TITLE
Some Problems>:

### ISSUE THREAD

**Issue by kingchenc** [JKorf/Binance.Net#115]
Anyone know what is this?

with older version;

```
2018.08.14 13:53:54:364 | Warning | Server returned an error: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Request blocked.

<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: ******************************************==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>

```
and with the newest verison i have this;

`Status: Forbidden-Forbidden, Message: The remote server returned an error: (403) Not allowed.
`
This is not clear, is this a IP ban? No it cant, ip ban return Error Code 429/418, mhmmm

**Comment by JKorf** [comment]
Hm it seems to work for me. What request was that? Can you reach the site via browser?

**Comment by kingchenc** [comment]
It make only sense, if i spamm binance api, but i had no IP ban, thats strange thing...
Yea, browser works, no message for ip ban or so...

After shutdown my programms for 10 min it works again, but i think i "spamm" a little bit to much the api, but i dont recieve a ban ;D

edit:
[https://support.binance.com/hc/en-us/articles/360004492232-API-Frequently-Asked-Questions-FAQ-#%E2%80%9Climits_waf%E2%80%9D](url)

Yea, it is for api spamming :s thx for responsing :)
