### ISSUE TITLE
How add Limit order MUST be maker, not taker order

### ISSUE THREAD

**Issue by prozerran** [JKorf/Binance.Net#1153]
I want to place a LIMIT order on let say BTCUSDT.
If the price is 20000, and i enter a BUY limit order at 19998, at the time when i click the buy, if the price is still at 20000, then i would expect my order to be placed to buy at 19998, the problem is that, once i hit the buy button, the price could suddenly DROP to let say 19995 and my order would IMMEDIDATELY go through as a TAKER/MARKET order. 

If this is the case, how do i ensure i get REJECTED from this order, that is my BUY LIMIT is priced OVER the current market price.
It should reject me and NOT go through as a taker order. 

Does the API support this? If so, how do i adjust code to ensure all my LIMIT orders are maker orders and never taker orders.

**Comment by HypsyNZ** [comment]
Use [`LIMIT_MAKER`](https://binance-docs.github.io/apidocs/spot/en/#new-order-trade) instead of `LIMIT`

**Comment by prozerran** [comment]
Thanks, seems good, but i see no simular enum for Futures and Inverse futures. (USDM and COINM)

**Comment by HypsyNZ** [comment]
Its more complicated for futures, naturally.

<html>
<body>


Type | Additional mandatory parameters
-- | --
LIMIT | timeInForce, quantity, price
MARKET | quantity
STOP/TAKE_PROFIT | price, stopPrice
STOP_MARKET/TAKE_PROFIT_MARKET | stopPrice
TRAILING_STOP_MARKET | callbackRate

<ul style="margin-right: 1156.5px; padding: 0px 28px 8px 43px; box-sizing: border-box; display: block; position: relative; z-index: 2; color: rgb(51, 51, 51); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(243, 247, 249); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li style="position: relative; z-index: 2; line-height: 1.6; margin-top: 0px;">Order with type<span> </span><code style="font-family: Consolas, Menlo, Monaco, &quot;Lucida Console&quot;, &quot;Liberation Mono&quot;, &quot;DejaVu Sans Mono&quot;, &quot;Bitstream Vera Sans Mono&quot;, &quot;Courier New&quot;, monospace, serif; font-size: 12px; line-height: 1.5; word-break: break-all; hyphens: auto; position: relative; z-index: 2; background-color: rgba(0, 0, 0, 0.05); padding: 3px; border-radius: 3px;">STOP</code>, parameter<span> </span><code style="font-family: Consolas, Menlo, Monaco, &quot;Lucida Console&quot;, &quot;Liberation Mono&quot;, &quot;DejaVu Sans Mono&quot;, &quot;Bitstream Vera Sans Mono&quot;, &quot;Courier New&quot;, monospace, serif; font-size: 12px; line-height: 1.5; word-break: break-all; hyphens: auto; position: relative; z-index: 2; background-color: rgba(0, 0, 0, 0.05); padding: 3px; border-radius: 3px;">timeInForce</code><span> </span>can be sent ( default<span> </span><code style="font-family: Consolas, Menlo, Monaco, &quot;Lucida Console&quot;, &quot;Liberation Mono&quot;, &quot;DejaVu Sans Mono&quot;, &quot;Bitstream Vera Sans Mono&quot;, &quot;Courier New&quot;, monospace, serif; font-size: 12px; line-height: 1.5; word-break: break-all; hyphens: auto; position: relative; z-index: 2; background-color: rgba(0, 0, 0, 0.05); padding: 3px; border-radius: 3px;">GTC</code>).</li><li style="position: relative; z-index: 2; line-height: 1.6; margin-top: 0px;">Order with type<span> </span><code style="font-family: Consolas, Menlo, Monaco, &quot;Lucida Console&quot;, &quot;Liberation Mono&quot;, &quot;DejaVu Sans Mono&quot;, &quot;Bitstream Vera Sans Mono&quot;, &quot;Courier New&quot;, monospace, serif; font-size: 12px; line-height: 1.5; word-break: break-all; hyphens: auto; position: relative; z-index: 2; background-color: rgba(0, 0, 0, 0.05); padding: 3px; border-radius: 3px;">TAKE_PROFIT</code>, parameter<span> </span><code style="font-family: Consolas, Menlo, Monaco, &quot;Lucida Console&quot;, &quot;Liberation Mono&quot;, &quot;DejaVu Sans Mono&quot;, &quot;Bitstream Vera Sans Mono&quot;, &quot;Courier New&quot;, monospace, serif; font-size: 12px; line-height: 1.5; word-break: break-all; hyphens: auto; position: relative; z-index: 2; background-color: rgba(0, 0, 0, 0.05); padding: 3px; border-radius: 3px;">timeInForce</code><span> </span>can be sent ( default<span> </span><code style="font-family: Consolas, Menlo, Monaco, &quot;Lucida Console&quot;, &quot;Liberation Mono&quot;, &quot;DejaVu Sans Mono&quot;, &quot;Bitstream Vera Sans Mono&quot;, &quot;Courier New&quot;, monospace, serif; font-size: 12px; line-height: 1.5; word-break: break-all; hyphens: auto; position: relative; z-index: 2; background-color: rgba(0, 0, 0, 0.05); padding: 3px; border-radius: 3px;">GTC</code>).</li><li style="position: relative; z-index: 2; line-height: 1.6; margin-top: 0px;"><p style="position: relative; z-index: 2; line-height: 1.6; margin-top: 0px;">Condition orders will be triggered when:</p><ul style="position: relative; z-index: 2;"><li style="position: relative; z-index: 2; line-height: 1.6; margin-top: 0px;">If parameter<code style="font-family: Consolas, Menlo, Monaco, &quot;Lucida Console&quot;, &quot;Liberation Mono&quot;, &quot;DejaVu Sans Mono&quot;, &quot;Bitstream Vera Sans Mono&quot;, &quot;Courier New&quot;, monospace, serif; font-size: 12px; line-height: 1.5; word-break: break-all; hyphens: auto; position: relative; z-index: 2; background-color: rgba(0, 0, 0, 0.05); padding: 3px; border-radius: 3px;">priceProtect</code>is sent as true:<ul style="position: relative; z-index: 2;"><li style="position: relative; z-index: 2; line-height: 1.6; margin-top: 0px;">when price reaches the<span> </span><code style="font-family: Consolas, Menlo, Monaco, &quot;Lucida Console&quot;, &quot;Liberation Mono&quot;, &quot;DejaVu Sans Mono&quot;, &quot;Bitstream Vera Sans Mono&quot;, &quot;Courier New&quot;, monospace, serif; font-size: 12px; line-height: 1.5; word-break: break-all; hyphens: auto; position: relative; z-index: 2; background-color: rgba(0, 0, 0, 0.05); padding: 3px; border-radius: 3px;">stopPrice</code><span> </span>，the difference rate between "MARK_PRICE" and "CONTRACT_PRICE" cannot be larger than the "triggerProtect" of the symbol</li><li style="position: relative; z-index: 2; line-height: 1.6; margin-top: 0px;">"triggerProtect" of a symbol can be got from<span> </span><code style="font-family: Consolas, Menlo, Monaco, &quot;Lucida Console&quot;, &quot;Liberation Mono&quot;, &quot;DejaVu Sans Mono&quot;, &quot;Bitstream Vera Sans Mono&quot;, &quot;Courier New&quot;, monospace, serif; font-size: 12px; line-height: 1.5; word-break: break-all; hyphens: auto; position: relative; z-index: 2; background-color: rgba(0, 0, 0, 0.05); padding: 3px; border-radius: 3px;">GET /dapi/v1/exchangeInfo</code></li></ul></li><li style="position: relative; z-index: 2; line-height: 1.6; margin-top: 0px;"><code style="font-family: Consolas, Menlo, Monaco, &quot;Lucida Console&quot;, &quot;Liberation Mono&quot;, &quot;DejaVu Sans Mono&quot;, &quot;Bitstream Vera Sans Mono&quot;, &quot;Courier New&quot;, monospace, serif; font-size: 12px; line-height: 1.5; word-break: break-all; hyphens: auto; position: relative; z-index: 2; background-color: rgba(0, 0, 0, 0.05); padding: 3px; border-radius: 3px;">STOP</code>,<span> </span><code style="font-family: Consolas, Menlo, Monaco, &quot;Lucida Console&quot;, &quot;Liberation Mono&quot;, &quot;DejaVu Sans Mono&quot;, &quot;Bitstream Vera Sans Mono&quot;, &quot;Courier New&quot;, monospace, serif; font-size: 12px; line-height: 1.5; word-break: break-all; hyphens: auto; position: relative; z-index: 2; background-color: rgba(0, 0, 0, 0.05); padding: 3px; border-radius: 3px;">STOP_MARKET</code>:<ul style="position: relative; z-index: 2;"><li style="position: relative; z-index: 2; line-height: 1.6; margin-top: 0px;">BUY: latest price ("MARK_PRICE" or "CONTRACT_PRICE") &gt;=<span> </span><code style="font-family: Consolas, Menlo, Monaco, &quot;Lucida Console&quot;, &quot;Liberation Mono&quot;, &quot;DejaVu Sans Mono&quot;, &quot;Bitstream Vera Sans Mono&quot;, &quot;Courier New&quot;, monospace, serif; font-size: 12px; line-height: 1.5; word-break: break-all; hyphens: auto; position: relative; z-index: 2; background-color: rgba(0, 0, 0, 0.05); padding: 3px; border-radius: 3px;">stopPrice</code></li><li style="position: relative; z-index: 2; line-height: 1.6; margin-top: 0px;">SELL: latest price ("MARK_PRICE" or "CONTRACT_PRICE") &lt;=<span> </span><code style="font-family: Consolas, Menlo, Monaco, &quot;Lucida Console&quot;, &quot;Liberation Mono&quot;, &quot;DejaVu Sans Mono&quot;, &quot;Bitstream Vera Sans Mono&quot;, &quot;Courier New&quot;, monospace, serif; font-size: 12px; line-height: 1.5; word-break: break-all; hyphens: auto; position: relative; z-index: 2; background-color: rgba(0, 0, 0, 0.05); padding: 3px; border-radius: 3px;">stopPrice</code></li></ul></li><li style="position: relative; z-index: 2; line-height: 1.6; margin-top: 0px;"><code style="font-family: Consolas, Menlo, Monaco, &quot;Lucida Console&quot;, &quot;Liberation Mono&quot;, &quot;DejaVu Sans Mono&quot;, &quot;Bitstream Vera Sans Mono&quot;, &quot;Courier New&quot;, monospace, serif; font-size: 12px; line-height: 1.5; word-break: break-all; hyphens: auto; position: relative; z-index: 2; background-color: rgba(0, 0, 0, 0.05); padding: 3px; border-radius: 3px;">TAKE_PROFIT</code>,<span> </span><code style="font-family: Consolas, Menlo, Monaco, &quot;Lucida Console&quot;, &quot;Liberation Mono&quot;, &quot;DejaVu Sans Mono&quot;, &quot;Bitstream Vera Sans Mono&quot;, &quot;Courier New&quot;, monospace, serif; font-size: 12px; line-height: 1.5; word-break: break-all; hyphens: auto; position: relative; z-index: 2; background-color: rgba(0, 0, 0, 0.05); padding: 3px; border-radius: 3px;">TAKE_PROFIT_MARKET</code>:<ul style="position: relative; z-index: 2;"><li style="position: relative; z-index: 2; line-height: 1.6; margin-top: 0px;">BUY: latest price ("MARK_PRICE" or "CONTRACT_PRICE") &lt;=<span> </span><code style="font-family: Consolas, Menlo, Monaco, &quot;Lucida Console&quot;, &quot;Liberation Mono&quot;, &quot;DejaVu Sans Mono&quot;, &quot;Bitstream Vera Sans Mono&quot;, &quot;Courier New&quot;, monospace, serif; font-size: 12px; line-height: 1.5; word-break: break-all; hyphens: auto; position: relative; z-index: 2; background-color: rgba(0, 0, 0, 0.05); padding: 3px; border-radius: 3px;">stopPrice</code></li><li style="position: relative; z-index: 2; line-height: 1.6; margin-top: 0px;">SELL: latest price ("MARK_PRICE" or "CONTRACT_PRICE") &gt;=<span> </span><code style="font-family: Consolas, Menlo, Monaco, &quot;Lucida Console&quot;, &quot;Liberation Mono&quot;, &quot;DejaVu Sans Mono&quot;, &quot;Bitstream Vera Sans Mono&quot;, &quot;Courier New&quot;, monospace, serif; font-size: 12px; line-height: 1.5; word-break: break-all; hyphens: auto; position: relative; z-index: 2; background-color: rgba(0, 0, 0, 0.05); padding: 3px; border-radius: 3px;">stopPrice</code></li></ul></li><li style="position: relative; z-index: 2; line-height: 1.6; margin-top: 0px;"><code style="font-family: Consolas, Menlo, Monaco, &quot;Lucida Console&quot;, &quot;Liberation Mono&quot;, &quot;DejaVu Sans Mono&quot;, &quot;Bitstream Vera Sans Mono&quot;, &quot;Courier New&quot;, monospace, serif; font-size: 12px; line-height: 1.5; word-break: break-all; hyphens: auto; position: relative; z-index: 2; background-color: rgba(0, 0, 0, 0.05); padding: 3px; border-radius: 3px;">TRAILING_STOP_MARKET</code>:<ul style="position: relative; z-index: 2;"><li style="position: relative; z-index: 2; line-height: 1.6; margin-top: 0px;">BUY: the lowest price after order placed &lt;=<span> </span><code style="font-family: Consolas, Menlo, Monaco, &quot;Lucida Console&quot;, &quot;Liberation Mono&quot;, &quot;DejaVu Sans Mono&quot;, &quot;Bitstream Vera Sans Mono&quot;, &quot;Courier New&quot;, monospace, serif; font-size: 12px; line-height: 1.5; word-break: break-all; hyphens: auto; position: relative; z-index: 2; background-color: rgba(0, 0, 0, 0.05); padding: 3px; border-radius: 3px;">activationPrice</code>, and the latest price &gt;= the lowest price * (1 +<span> </span><code style="font-family: Consolas, Menlo, Monaco, &quot;Lucida Console&quot;, &quot;Liberation Mono&quot;, &quot;DejaVu Sans Mono&quot;, &quot;Bitstream Vera Sans Mono&quot;, &quot;Courier New&quot;, monospace, serif; font-size: 12px; line-height: 1.5; word-break: break-all; hyphens: auto; position: relative; z-index: 2; background-color: rgba(0, 0, 0, 0.05); padding: 3px; border-radius: 3px;">callbackRate</code>)</li><li style="position: relative; z-index: 2; line-height: 1.6; margin-top: 0px;">SELL: the highest price after order placed &gt;=<span> </span><code style="font-family: Consolas, Menlo, Monaco, &quot;Lucida Console&quot;, &quot;Liberation Mono&quot;, &quot;DejaVu Sans Mono&quot;, &quot;Bitstream Vera Sans Mono&quot;, &quot;Courier New&quot;, monospace, serif; font-size: 12px; line-height: 1.5; word-break: break-all; hyphens: auto; position: relative; z-index: 2; background-color: rgba(0, 0, 0, 0.05); padding: 3px; border-radius: 3px;">activationPrice</code>, and the latest price &lt;= the highest price * (1 -<span> </span><code style="font-family: Consolas, Menlo, Monaco, &quot;Lucida Console&quot;, &quot;Liberation Mono&quot;, &quot;DejaVu Sans Mono&quot;, &quot;Bitstream Vera Sans Mono&quot;, &quot;Courier New&quot;, monospace, serif; font-size: 12px; line-height: 1.5; word-break: break-all; hyphens: auto; position: relative; z-index: 2; background-color: rgba(0, 0, 0, 0.05); padding: 3px; border-radius: 3px;">callbackRate</code>)</li></ul></li></ul></li><li style="position: relative; z-index: 2; line-height: 1.6; margin-top: 0px;"><p style="position: relative; z-index: 2; line-height: 1.6; margin-top: 0px;">For<span> </span><code style="font-family: Consolas, Menlo, Monaco, &quot;Lucida Console&quot;, &quot;Liberation Mono&quot;, &quot;DejaVu Sans Mono&quot;, &quot;Bitstream Vera Sans Mono&quot;, &quot;Courier New&quot;, monospace, serif; font-size: 12px; line-height: 1.5; word-break: break-all; hyphens: auto; position: relative; z-index: 2; background-color: rgba(0, 0, 0, 0.05); padding: 3px; border-radius: 3px;">TRAILING_STOP_MARKET</code>, if you got such error code.<br style="position: relative; z-index: 2;"><code style="font-family: Consolas, Menlo, Monaco, &quot;Lucida Console&quot;, &quot;Liberation Mono&quot;, &quot;DejaVu Sans Mono&quot;, &quot;Bitstream Vera Sans Mono&quot;, &quot;Courier New&quot;, monospace, serif; font-size: 12px; line-height: 1.5; word-break: break-all; hyphens: auto; position: relative; z-index: 2; background-color: rgba(0, 0, 0, 0.05); padding: 3px; border-radius: 3px;">{"code": -2021, "msg": "Order would immediately trigger."}</code><br style="position: relative; z-index: 2;">means that the parameters you send do not meet the following requirements:</p><ul style="position: relative; z-index: 2;"><li style="position: relative; z-index: 2; line-height: 1.6; margin-top: 0px;">BUY:<span> </span><code style="font-family: Consolas, Menlo, Monaco, &quot;Lucida Console&quot;, &quot;Liberation Mono&quot;, &quot;DejaVu Sans Mono&quot;, &quot;Bitstream Vera Sans Mono&quot;, &quot;Courier New&quot;, monospace, serif; font-size: 12px; line-height: 1.5; word-break: break-all; hyphens: auto; position: relative; z-index: 2; background-color: rgba(0, 0, 0, 0.05); padding: 3px; border-radius: 3px;">activationPrice</code><span> </span>should be smaller than latest price.</li><li style="position: relative; z-index: 2; line-height: 1.6; margin-top: 0px;">SELL:<span> </span><code style="font-family: Consolas, Menlo, Monaco, &quot;Lucida Console&quot;, &quot;Liberation Mono&quot;, &quot;DejaVu Sans Mono&quot;, &quot;Bitstream Vera Sans Mono&quot;, &quot;Courier New&quot;, monospace, serif; font-size: 12px; line-height: 1.5; word-break: break-all; hyphens: auto; position: relative; z-index: 2; background-color: rgba(0, 0, 0, 0.05); padding: 3px; border-radius: 3px;">activationPrice</code><span> </span>should be larger than latest price.</li></ul></li><li style="position: relative; z-index: 2; line-height: 1.6; margin-top: 0px;"><p style="position: relative; z-index: 2; line-height: 1.6; margin-top: 0px;">If<span> </span><code style="font-family: Consolas, Menlo, Monaco, &quot;Lucida Console&quot;, &quot;Liberation Mono&quot;, &quot;DejaVu Sans Mono&quot;, &quot;Bitstream Vera Sans Mono&quot;, &quot;Courier New&quot;, monospace, serif; font-size: 12px; line-height: 1.5; word-break: break-all; hyphens: auto; position: relative; z-index: 2; background-color: rgba(0, 0, 0, 0.05); padding: 3px; border-radius: 3px;">newOrderRespType</code><span> </span>is sent as<span> </span><code style="font-family: Consolas, Menlo, Monaco, &quot;Lucida Console&quot;, &quot;Liberation Mono&quot;, &quot;DejaVu Sans Mono&quot;, &quot;Bitstream Vera Sans Mono&quot;, &quot;Courier New&quot;, monospace, serif; font-size: 12px; line-height: 1.5; word-break: break-all; hyphens: auto; position: relative; z-index: 2; background-color: rgba(0, 0, 0, 0.05); padding: 3px; border-radius: 3px;">RESULT</code><span> </span>:</p><ul style="position: relative; z-index: 2;"><li style="position: relative; z-index: 2; line-height: 1.6; margin-top: 0px;"><code style="font-family: Consolas, Menlo, Monaco, &quot;Lucida Console&quot;, &quot;Liberation Mono&quot;, &quot;DejaVu Sans Mono&quot;, &quot;Bitstream Vera Sans Mono&quot;, &quot;Courier New&quot;, monospace, serif; font-size: 12px; line-height: 1.5; word-break: break-all; hyphens: auto; position: relative; z-index: 2; background-color: rgba(0, 0, 0, 0.05); padding: 3px; border-radius: 3px;">MARKET</code><span> </span>order: the final FILLED result of the order will be return directly.</li><li style="position: relative; z-index: 2; line-height: 1.6; margin-top: 0px;"><code style="font-family: Consolas, Menlo, Monaco, &quot;Lucida Console&quot;, &quot;Liberation Mono&quot;, &quot;DejaVu Sans Mono&quot;, &quot;Bitstream Vera Sans Mono&quot;, &quot;Courier New&quot;, monospace, serif; font-size: 12px; line-height: 1.5; word-break: break-all; hyphens: auto; position: relative; z-index: 2; background-color: rgba(0, 0, 0, 0.05); padding: 3px; border-radius: 3px;">LIMIT</code><span> </span>order with special<span> </span><code style="font-family: Consolas, Menlo, Monaco, &quot;Lucida Console&quot;, &quot;Liberation Mono&quot;, &quot;DejaVu Sans Mono&quot;, &quot;Bitstream Vera Sans Mono&quot;, &quot;Courier New&quot;, monospace, serif; font-size: 12px; line-height: 1.5; word-break: break-all; hyphens: auto; position: relative; z-index: 2; background-color: rgba(0, 0, 0, 0.05); padding: 3px; border-radius: 3px;">timeInForce</code>: the final status result of the order(FILLED or EXPIRED) will be returned directly.</li></ul></li><li style="position: relative; z-index: 2; line-height: 1.6; margin-top: 0px;"><p style="position: relative; z-index: 2; line-height: 1.6; margin-top: 0px;"><code style="font-family: Consolas, Menlo, Monaco, &quot;Lucida Console&quot;, &quot;Liberation Mono&quot;, &quot;DejaVu Sans Mono&quot;, &quot;Bitstream Vera Sans Mono&quot;, &quot;Courier New&quot;, monospace, serif; font-size: 12px; line-height: 1.5; word-break: break-all; hyphens: auto; position: relative; z-index: 2; background-color: rgba(0, 0, 0, 0.05); padding: 3px; border-radius: 3px;">STOP_MARKET</code>,<span> </span><code style="font-family: Consolas, Menlo, Monaco, &quot;Lucida Console&quot;, &quot;Liberation Mono&quot;, &quot;DejaVu Sans Mono&quot;, &quot;Bitstream Vera Sans Mono&quot;, &quot;Courier New&quot;, monospace, serif; font-size: 12px; line-height: 1.5; word-break: break-all; hyphens: auto; position: relative; z-index: 2; background-color: rgba(0, 0, 0, 0.05); padding: 3px; border-radius: 3px;">TAKE_PROFIT_MARKET</code><span> </span>with<span> </span><code style="font-family: Consolas, Menlo, Monaco, &quot;Lucida Console&quot;, &quot;Liberation Mono&quot;, &quot;DejaVu Sans Mono&quot;, &quot;Bitstream Vera Sans Mono&quot;, &quot;Courier New&quot;, monospace, serif; font-size: 12px; line-height: 1.5; word-break: break-all; hyphens: auto; position: relative; z-index: 2; background-color: rgba(0, 0, 0, 0.05); padding: 3px; border-radius: 3px;">closePosition</code>=<code style="font-family: Consolas, Menlo, Monaco, &quot;Lucida Console&quot;, &quot;Liberation Mono&quot;, &quot;DejaVu Sans Mono&quot;, &quot;Bitstream Vera Sans Mono&quot;, &quot;Courier New&quot;, monospace, serif; font-size: 12px; line-height: 1.5; word-break: break-all; hyphens: auto; position: relative; z-index: 2; background-color: rgba(0, 0, 0, 0.05); padding: 3px; border-radius: 3px;">true</code>:</p><ul style="position: relative; z-index: 2;"><li style="position: relative; z-index: 2; line-height: 1.6; margin-top: 0px;">Follow the same rules for condition orders.</li><li style="position: relative; z-index: 2; line-height: 1.6; margin-top: 0px;">If triggered,<strong style="font-weight: bold; position: relative; z-index: 2;">close all</strong><span> </span>current long position( if<span> </span><code style="font-family: Consolas, Menlo, Monaco, &quot;Lucida Console&quot;, &quot;Liberation Mono&quot;, &quot;DejaVu Sans Mono&quot;, &quot;Bitstream Vera Sans Mono&quot;, &quot;Courier New&quot;, monospace, serif; font-size: 12px; line-height: 1.5; word-break: break-all; hyphens: auto; position: relative; z-index: 2; background-color: rgba(0, 0, 0, 0.05); padding: 3px; border-radius: 3px;">SELL</code>) or current short position( if<span> </span><code style="font-family: Consolas, Menlo, Monaco, &quot;Lucida Console&quot;, &quot;Liberation Mono&quot;, &quot;DejaVu Sans Mono&quot;, &quot;Bitstream Vera Sans Mono&quot;, &quot;Courier New&quot;, monospace, serif; font-size: 12px; line-height: 1.5; word-break: break-all; hyphens: auto; position: relative; z-index: 2; background-color: rgba(0, 0, 0, 0.05); padding: 3px; border-radius: 3px;">BUY</code>).</li><li style="position: relative; z-index: 2; line-height: 1.6; margin-top: 0px;">Cannot be used with<span> </span><code style="font-family: Consolas, Menlo, Monaco, &quot;Lucida Console&quot;, &quot;Liberation Mono&quot;, &quot;DejaVu Sans Mono&quot;, &quot;Bitstream Vera Sans Mono&quot;, &quot;Courier New&quot;, monospace, serif; font-size: 12px; line-height: 1.5; word-break: break-all; hyphens: auto; position: relative; z-index: 2; background-color: rgba(0, 0, 0, 0.05); padding: 3px; border-radius: 3px;">quantity</code><span> </span>parameter</li><li style="position: relative; z-index: 2; line-height: 1.6; margin-top: 0px;">Cannot be used with<span> </span><code style="font-family: Consolas, Menlo, Monaco, &quot;Lucida Console&quot;, &quot;Liberation Mono&quot;, &quot;DejaVu Sans Mono&quot;, &quot;Bitstream Vera Sans Mono&quot;, &quot;Courier New&quot;, monospace, serif; font-size: 12px; line-height: 1.5; word-break: break-all; hyphens: auto; position: relative; z-index: 2; background-color: rgba(0, 0, 0, 0.05); padding: 3px; border-radius: 3px;">reduceOnly</code><span> </span>parameter</li><li style="position: relative; z-index: 2; line-height: 1.6; margin-top: 0px;">In Hedge Mode,cannot be used with<span> </span><code style="font-family: Consolas, Menlo, Monaco, &quot;Lucida Console&quot;, &quot;Liberation Mono&quot;, &quot;DejaVu Sans Mono&quot;, &quot;Bitstream Vera Sans Mono&quot;, &quot;Courier New&quot;, monospace, serif; font-size: 12px; line-height: 1.5; word-break: break-all; hyphens: auto; position: relative; z-index: 2; background-color: rgba(0, 0, 0, 0.05); padding: 3px; border-radius: 3px;">BUY</code><span> </span>orders in<span> </span><code style="font-family: Consolas, Menlo, Monaco, &quot;Lucida Console&quot;, &quot;Liberation Mono&quot;, &quot;DejaVu Sans Mono&quot;, &quot;Bitstream Vera Sans Mono&quot;, &quot;Courier New&quot;, monospace, serif; font-size: 12px; line-height: 1.5; word-break: break-all; hyphens: auto; position: relative; z-index: 2; background-color: rgba(0, 0, 0, 0.05); padding: 3px; border-radius: 3px;">LONG</code><span> </span>position side. and cannot be used with<span> </span><code style="font-family: Consolas, Menlo, Monaco, &quot;Lucida Console&quot;, &quot;Liberation Mono&quot;, &quot;DejaVu Sans Mono&quot;, &quot;Bitstream Vera Sans Mono&quot;, &quot;Courier New&quot;, monospace, serif; font-size: 12px; line-height: 1.5; word-break: break-all; hyphens: auto; position: relative; z-index: 2; background-color: rgba(0, 0, 0, 0.05); padding: 3px; border-radius: 3px;">SELL</code><span> </span>orders in<span> </span><code style="font-family: Consolas, Menlo, Monaco, &quot;Lucida Console&quot;, &quot;Liberation Mono&quot;, &quot;DejaVu Sans Mono&quot;, &quot;Bitstream Vera Sans Mono&quot;, &quot;Courier New&quot;, monospace, serif; font-size: 12px; line-height: 1.5; word-break: break-all; hyphens: auto; position: relative; z-index: 2; background-color: rgba(0, 0, 0, 0.05); padding: 3px; border-radius: 3px;">SHORT</code><span> </span>position side</li></ul></li></ul>
</body>
</html>

**Comment by JKorf** [comment]
Seems like you could use the Good Till Crossing timeInForce?
`GTX - Good Till Crossing (Post Only)`
