### ISSUE TITLE
futures USD-M

### ISSUE THREAD

**Issue by arsinteaalex** [JKorf/Binance.Net#1158]
Hello, when placing market transactions on USD-M futures, the price is 0 , my account is set to netting 

![T](https://user-images.githubusercontent.com/31989008/194293448-cb536826-5547-4e82-8daa-0e23ddcddc78.png)

**Comment by HypsyNZ** [comment]
is this on live or the testnet?

**Comment by arsinteaalex** [comment]
yes I tried more symbols

**Comment by arsinteaalex** [comment]
i always get 0 in the code above

**Comment by HypsyNZ** [comment]
Can you log the original data instead of the deserialized data? Maybe its not deserializing for some reason

**Comment by arsinteaalex** [comment]
![image](https://user-images.githubusercontent.com/31989008/194313046-56ec4da5-2701-4d44-8f59-0ed16abb40f5.png)

I get 0 from api so it's their fault

**Comment by HypsyNZ** [comment]
Have you turn on the `OriginalData` client option?

**Comment by arsinteaalex** [comment]
![image](https://user-images.githubusercontent.com/31989008/194314826-d3cbb22a-37f9-4420-bf42-ffdd00b99cb9.png)
this is what you are talking about

**Comment by HypsyNZ** [comment]
Yes, that is very strange.

**Comment by HypsyNZ** [comment]
```cs
newOrderRespType: OrderResponseType.RESULT
```

**Comment by HypsyNZ** [comment]
If newOrderRespType is sent as RESULT :

MARKET order: the final FILLED result of the order will be return directly.
LIMIT order with special timeInForce: the final status result of the order(FILLED or EXPIRED) will be returned directly.

**Comment by arsinteaalex** [comment]
![image](https://user-images.githubusercontent.com/31989008/194317548-dd368869-5f11-40fe-9686-835100599c29.png)

it worked, I have avgPrice

**Comment by HypsyNZ** [comment]
Nice, close the issue if it is resolved please.

**Comment by arsinteaalex** [comment]
thanks

**Comment by HypsyNZ** [comment]
@arsinteaalex the [api reference](https://binance-docs.github.io/apidocs/futures/en/#new-order-trade) can be good for solving issues like this
