### ISSUE TITLE
Problems with sockets

### ISSUE THREAD

**Issue by nikkozp** [JKorf/Binance.Net#116]
Hey. The problem is that sockets take a very long time to reach me.

> 16:28: 48.779 New Order Buy AGIBTC #5335133 price 0.00000715 (4683)
> 16:28:51.607 Cancel order AGIBTC #5335133
> 16:28:52.654 UNKNOWN_ORDER
> 16:28:53.717 Cancel order AGIBTC #5335133
> 16:28:53.748 UNKNOWN_ORDER
> 16:28:54.811 Cancel order AGIBTC #5335133
> 16:28:54.842 UNKNOWN_ORDER
> 16:28:55.858 Cancel order AGIBTC #5335133
> 16:28:56.467 UNKNOWN_ORDER
> 16:28:56.483 Filled AGIBTC #5335133 for price 0.00000715 (4683)

![image](https://user-images.githubusercontent.com/11537426/44176914-0c118180-a0ec-11e8-93e4-8f3d7013beb3.png)

Bought a second after placing the order, and the socket came later for 12 seconds. And this happens very often

Please check this problem. This happened in one of the latest updates. My bot that runs on your past dll does not have such problems.

**Comment by JKorf** [comment]
Hi can you please provide debug logging? Put LogVerbosity on Debug when creating the client and paste the results of when this happens here please.

**Comment by nikkozp** [comment]
Thanks mate

I found out what the reason was. In `BinanceStreamAccountInfo` I used the `client.DustLog()` is it slowed down the program.
