### ISSUE TITLE
I want to give the amount as a percentage

### ISSUE THREAD

**Issue by hyrllhsgr** [JKorf/Binance.Net#1161]
**Describe the bug**

**To Reproduce**
What endpoints and subscriptions are called.

**Expected behavior**

**Debug logging**
Add debug logging related to the issue. Enable Debug logging in the client options by settings LogLevel to Debug.

**Comment by hyrllhsgr** [comment]
Is there a method where I can give the amount as a percentage or in dollars when placing a new order for usdt futures. example: like $100 or 20% of the balance

**Comment by JKorf** [comment]
No, you have to check yourself how much USD you want to use
