### ISSUE TITLE
Replace order error: One or more errors occurred. (Object reference not set to an instance of an object.)

### ISSUE THREAD

**Issue by vaniakurd** [JKorf/Binance.Net#1166]
Code examlpe: 
[codeExample.txt](https://github.com/JKorf/Binance.Net/files/9923300/codeExample.txt).

Requset:
![image](https://user-images.githubusercontent.com/33133624/199581050-c75fd48d-dace-4ae2-8f71-957462328549.png)

InnerException:
[InnerException.xlsx](https://github.com/JKorf/Binance.Net/files/9923319/InnerException.xlsx)

All sended arguments are non-null

**Comment by vaniakurd** [comment]
I found where error thrown. NullReferenseException here:
![image](https://user-images.githubusercontent.com/33133624/199599511-959fc274-020d-4dff-b6cb-de629bbf4f18.png)

**Comment by gggonzalo** [comment]
I am experiencing the same issue

![Screen Shot 2022-11-24 at 01 10 32](https://user-images.githubusercontent.com/118962418/203717646-68af62ce-e8ec-41d9-bc71-216bd2ecf19c.png)

**Comment by JKorf** [comment]
Should be fixed in the latest release
