### ISSUE TITLE
Duplicate data when combine BinanceSocketClient and BinanceClient

### ISSUE THREAD

**Issue by EKGD** [JKorf/Binance.Net#1167]
I use this code to calculate the MA 5. of five mins

```
public async void GetKline()
        {
            decimal btcOpenPrice = 0;
        
            var clientSoket = new BinanceSocketClient();
           
            var GetBtcKline = clientSoket.UsdFuturesStreams.SubscribeToKlineUpdatesAsync("BTCUSDT", Binance.Net.Enums.KlineInterval.FiveMinutes,
                async data =>
                {
                    if (btcOpenPrice != data.Data.Data.OpenPrice)
                    {
                        btcOpenPrice = data.Data.Data.OpenPrice;
                        BinanceClient client = new BinanceClient();
                        var kline5 = await client.UsdFuturesApi.ExchangeData.GetMarkPriceKlinesAsync("BTCUSDT", Binance.Net.Enums.KlineInterval.FiveMinutes, 5);
                        decimal MA5 = CaculateMA(kline5.Data.ToList());
                        client.Dispose();

                      
                    }

                });
        }

```
```
private decimal CaculateMA (List<BinanceMarkIndexKline> klines)
        {
            klines.RemoveAt(klines.Count-1);
            decimal ma = 0;
            foreach (BinanceMarkIndexKline kline in klines)
            {
                ma  += kline.ClosePrice;
                Console.WriteLine(kline.ClosePrice+ "+++++++++"+klines.IndexOf(kline));

            }
            Console.WriteLine(klines.Count + "--------------------------------");
            return ma / klines.Count;
        }
```

however the result of `var kline5 = await client.UsdFuturesApi.ExchangeData.GetMarkPriceKlinesAsync("BTCUSDT",Binance.Net.Enums.KlineInterval.FiveMinutes, 5);`

not correct and duplicate 
![image](https://user-images.githubusercontent.com/116337615/199729662-e0c05011-dec1-423d-bcd9-0fe818541428.png)
![image](https://user-images.githubusercontent.com/116337615/199729826-3a1011b6-f95a-4ce1-a58a-f3cc0a1644fe.png)
![image](https://user-images.githubusercontent.com/116337615/199729970-989df2c8-5a4e-4458-99ef-52f3f3a4b3f9.png)
![image](https://user-images.githubusercontent.com/116337615/199730359-f50f8b6d-437e-45d4-8ba0-60b45542f9e2.png)

**Comment by eros1453** [comment]
Your Tradingview chart has Heikenashi candles.
Select Candles to see your value or convert your candle data to heikenashi

**Comment by EKGD** [comment]
> 
it not trading view. It is the chart on binance

**Comment by HypsyNZ** [comment]
I can't reproduce this.

**Comment by Hulkstance** [comment]
You're doing it wrong. The difference is that my code keeps track of the previously calculated value and uses it for the next calculation.

First of all, you should use `Close`, not `Open`. You should then warm up the indicator. If it's not warmed up, don't expect accuracy. 

![image](https://user-images.githubusercontent.com/33224919/210284603-ac275879-4702-4ce3-a068-a26052962b23.png)

![image](https://user-images.githubusercontent.com/33224919/210284621-6d0a6d29-3fce-4b6f-932a-aebbb41f0236.png)

https://github.com/Hulkstance/indicator-warmup/blob/main/src/Indicator/Program.cs

Have fun!

**Comment by EKGD** [comment]
@Hulkstance  love the world have guys like you. I'm  very appreciate . thank you.  <3
