### ISSUE TITLE
WebScoket.MarketStreams missing logic for 1d window_size

### ISSUE THREAD

**Issue by ThusMad** [JKorf/Binance.Net#1170]
**Describe the bug**
According to https://binance-docs.github.io/apidocs/spot/en/#all-market-tickers-stream
Acceptable window sizes are 1h,4h,1d 
in code, see https://github.com/JKorf/Binance.Net/blob/90af8d0ce0f5e0f131214522452e191f6cca12a0/Binance.Net/Clients/SpotApi/BinanceSocketClientSpotStreams.cs#L207 as well as related endpoints

**To Reproduce**
When subscribing
SpotStreams.SubscribeToAllRollingWindowTickerUpdatesAsync(TimeSpan.FromHours(24), Update24HourTicker);
as well as 
SpotStreams.SubscribeToAllRollingWindowTickerUpdatesAsync(TimeSpan.FromDays(1), Update24HourTicker);

**Expected behavior**
When subscribing with TimeSpan.FromHours(24) or TimeSpan.FromDays(1) in API call should be used "1d" instead of 24h

**Comment by kulikov-dev** [comment]
@ThusMad The bug was fixed.
@JKorf it can be closed.
