### ISSUE TITLE
When place a stop loss limit order, the response object contains no information about the order.

### ISSUE THREAD

**Issue by jejx355** [JKorf/Binance.Net#1172]
When I place a stop loss limit order, the response object `<BinancePlacedOrder>` contains no information about the order.

![immagine](https://user-images.githubusercontent.com/82181040/202814221-23a0d1ed-2f08-4e12-b275-60ada3e5e1d2.png)

**Comment by JKorf** [comment]
You can set the `orderResponseType` to Full to get all the data. This is the Binance description:
MARKET and LIMIT order types default to FULL, all other orders default to ACK.
