### ISSUE TITLE
ReconnectInterval and AutoReconnect broken/missing from BinanceSocketClientOptions in version 8.3?

### ISSUE THREAD

**Issue by MillerMark** [JKorf/Binance.Net#1174]
**BinanceSocketClientOptions** in version 8.3 of Binance.Net appears to missing the **ReconnectInterval** and **AutoReconnect** properties. What's the best way to get the same behavior?

Edit: Looks like these moved to BinanceSocketClientOptions.SpotStreamsOptions.

**Comment by JKorf** [comment]
Yes theyre moved to the specific API options
