### ISSUE TITLE
Websocket subscription does not work with proxy

### ISSUE THREAD

**Issue by ChrL73** [JKorf/Binance.Net#1176]
When I try to call 'SubscribeToBookTickerUpdatesAsync' on a 'BinanceSocketClient' with a 'Proxy' option, it triggers a 'NullReferenceException'

Example of code:

```
BinanceSocketClientOptions options = new BinanceSocketClientOptions();
options.Proxy = new ApiProxy(host, port, login, password);
BinanceSocketClient client = new BinanceSocketClient(options);
Task<CallResult<UpdateSubscription>> task = client.SpotStreams.SubscribeToBookTickerUpdatesAsync("btcusdt", (x) => { });

// The following line triggers a NullReferenceException
CallResult<UpdateSubscription> result = await task;
```
(Note: I tested the Rest API with the same proxy option, it works fine)

**Comment by JKorf** [comment]
Are you on the latest version?

**Comment by ChrL73** [comment]
I was using version 8.2.0. I updated to 8.3.0. Now, I no longer have 'NullReferenceException'. But I get 'Can’t connect to the server' in ‘result.Error’. The Proxy parameters seem correct since it works with the Rest API.

**Comment by JKorf** [comment]
I think the proxy is set correctly, maybe check with your proxy provider if you can use websockets
