### ISSUE TITLE
UsdFuturesStreams.SubscribeToKlineUpdatesAsync Not working correctly

### ISSUE THREAD

**Issue by redquantum** [JKorf/Binance.Net#1177]
Hello Friend,

I think there is a problem with Future Socket. Close price is always wrong. When I interpret the incoming data in indicators, there is no agreement. Constantly showing incompatibility and different data.

Please observe 1 Min socket close price for a while.

"  await socketClient.UsdFuturesStreams.SubscribeToKlineUpdatesAsync "

Thank you.

------------------My Connection Setup ----------

     BinanceClient.SetDefaultOptions(new BinanceClientOptions()
                {
                    UsdFuturesApiOptions = new BinanceApiClientOptions()
                    {
                        ApiCredentials = new ApiCredentials(Properties.Resources.FutureApiKey, Properties.Resources.FutureSecretKey)
                    }
                });
             

                BinanceSocketClient.SetDefaultOptions(new BinanceSocketClientOptions
                {
                    UsdFuturesStreamsOptions = new SocketApiClientOptions()
                    {
                        ApiCredentials = new ApiCredentials(Properties.Resources.FutureApiKey, Properties.Resources.FutureSecretKey),
                        AutoReconnect = true

                    }
                });

**Comment by JKorf** [comment]
The close price you see is just the latest price since the candle is not closed yet. So every trade updates the close price of the current candle. I don't see anything weird with the data coming in

**Comment by redquantum** [comment]
Hello

I understand what you mean, but I don't have this problem on spot Socket Klines. The problem I mentioned only appears in Future. While reading the binance docs today, I saw an option. I couldn't find this option in API. Do you have an opinion on the subject? I think maybe this is where the problem comes from.

Binance API document show this options:

Contract type:

perpetual
current_quarter
next_quarter

![image](https://user-images.githubusercontent.com/10393082/209981745-c4e2ef94-24eb-4970-9bb2-55af87969fc6.png)
