### ISSUE TITLE
Can i use this API in Windows form

### ISSUE THREAD

**Issue by awaismemon26** [JKorf/Binance.Net#118]

**Comment by JKorf** [comment]
Sure

**Comment by awaismemon26** [comment]
I also have asked a question regarding that in Stackoverflow so people are saying its because of UI thread which is causing deadlock

**Comment by JKorf** [comment]
Hm that could be, it means I've forgotten to put a ConfigureAwait(false) somewhere. What call is deadlocking?

**Comment by awaismemon26** [comment]
in async method its giving status of WaitingForActivation and in sync method its creating deadlock when calling sync methods in Windows form.

**Comment by JKorf** [comment]
What call from the library though?

**Comment by awaismemon26** [comment]
I am calling Time() Method from BinanceClientPublicEndpoints class

**Comment by awaismemon26** [comment]
In which VS version you have build this project ?

**Comment by JKorf** [comment]
It is targetting .NetStandard2.0, which means it supports .Net framework 4.6.1 and up including .Net core.
There is no method Time and no class BinanceClientPublicEndpoints in this library..
