### ISSUE TITLE
SubscribeToKlineUpdates method can't subscribe to more than 100 symbols!

### ISSUE THREAD

**Issue by AmirNorouzpour** [JKorf/Binance.Net#1180]
When I try to subscribe to KlineUpdate with more than 100 symbols I get this socket error!
*
![Screenshot 2023-01-02 114651](https://user-images.githubusercontent.com/24652732/210207480-22dc3262-17a0-4a56-955c-ae19339c98f4.jpg)
*No response on subscription request received**

**Comment by JKorf** [comment]
It's a known limitation on the Binance socket API, the subscribe request can't be larger than +-4096 bytes or it will ignore the message. You'll have to split it up in batches
