### ISSUE TITLE
IndexPrice in SubscribeToAllMarkPriceUpdatesAsync???

### ISSUE THREAD

**Issue by hcanak** [JKorf/Binance.Net#1182]
Hello,

There is no "IndexPrice" field in the **Mark Price Stream for All market** stream data. 
Can you check?

**Comment by hcanak** [comment]
Hi @HypsyNZ ,

Please see api documantion

https://binance-docs.github.io/apidocs/futures/en/#mark-price-stream


![image](https://user-images.githubusercontent.com/79494507/210636456-3c80673a-46c2-43f7-862e-45cb53104aba.png)

**Comment by JKorf** [comment]
Fixed in the latest version
