### ISSUE TITLE
Remove SubscribeToAllBookTickerUpdatesAsync as it was deleted from Binance

### ISSUE THREAD

**Issue by ThusMad** [JKorf/Binance.Net#1183]
**Describe the bug**
SubscribeToAllBookTickerUpdatesAsync  is not working.

**To Reproduce**
subscribe to SubscribeToAllBookTickerUpdatesAsync 

In the change log https://binance-docs.github.io/apidocs/spot/en/#change-log from 2022-12-05 the !bookTicker removed by December 7, 2022

**Comment by jkaa2** [comment]
Is there any workaround this issue ?

**Comment by JKorf** [comment]
Done
