### ISSUE TITLE
WebSocket API (trading)

### ISSUE THREAD

**Issue by vdm404** [JKorf/Binance.Net#1185]
Hi.
Are there any plans to implement the WebSocket API for trading? It was introduced in the changelog at 2022-12-26: [https://binance-docs.github.io/apidocs/websocket_api/en/#change-log](url)

Thanks.

**Comment by HypsyNZ** [comment]
This wouldn't be faster because it doesn't change the total amount of work that needs to happen.

Seems kind of pointless to implement this.

**Comment by JKorf** [comment]
I'll probably look into adding this at some point, but it isn't a high priority. @HypsyNZ  Benefit of using the websocket to do trading would be that it would reduce latency a bit as the connection is already open and ready to receive.

**Comment by HypsyNZ** [comment]
>@HypsyNZ Benefit of using the websocket to do trading would be that it would reduce latency a bit as the connection is already open and ready to receive.

Right good point

**Comment by HypsyNZ** [comment]
```cs
{"error":{"code":2,"msg":"Invalid request: unknown variant `TIME`, expected one of `SUBSCRIBE`, `UNSUBSCRIBE`, `LIST_SUBSCRIPTIONS`, `SET_PROPERTY`, `GET_PROPERTY` at line 1 column 16"},"id":11}

{"error":{"code":2,"msg":"Invalid request: streams must have non-zero length"},"id":11}
```

How do you even connect to these endpoints?

**Comment by HypsyNZ** [comment]
I was going to do this but now it isn't planned.

**Comment by HypsyNZ** [comment]
Binance added support for the `Websocket API` to their wrapper

https://github.com/binance/binance-connector-dotnet
