### ISSUE TITLE
Strategy event missing

### ISSUE THREAD

**Issue by bogdanIuga** [JKorf/Binance.Net#1187]
Strategy update is missing

Binance documentation: https://binance-docs.github.io/apidocs/futures/en/#event-strategy_update

**Comment by HypsyNZ** [comment]
_This would slow down the execution of every single data event, I don't think this should be added unless you separate the logic some how, Its already too much._

**Comment by bogdanIuga** [comment]
maybe an API endpoint? I couldn't find anything to retrieve the strategy from an open order ...

**Comment by JKorf** [comment]
I've added the Strategy and Grid updates in the latest version
