### ISSUE TITLE
Futures / UserStream / configUpdate confusion

### ISSUE THREAD

**Issue by tahsinuysal** [JKorf/Binance.Net#1189]
When I change the Asset Mode (between single-asset and multi-assets modes), configUpdate has triggerred with configUpdate.Data.ConfigUpdateData -> PositionMode (OneWay / Hedge Modes). 

To **single-asset mode**, it shows me position mode is switched to **one way** mode
To **multi-assets mode**, it shows me position mode is switched to **hedge** mode

And when I actually change the PositionMode, **nothing** comes up.

Thanks.

**Comment by HypsyNZ** [comment]
This sounds like an issue on the other end, maybe you should report this to Binance.

**Comment by tahsinuysal** [comment]
> This sounds like an issue on the other end, maybe you should report this to Binance.

Yeah, maybe. I'm waiting a response from @JKorf to be sure this issue is on the Binance's end. Thank you @HypsyNZ

**Comment by JKorf** [comment]
Hi, after reading the documentation again it seems like it was called PositionMode incorrectly. I've updated the model in the latest version
