### ISSUE TITLE
GetAllTrades Functionality Issue

### ISSUE THREAD

**Issue by SarahAyaz** [JKorf/Binance.Net#119]
Right now i am getting individual trade symbol from my account using 
[[ var myTrades = client.GetMyTrades("ETHBTC"); ]]
, is there any one function to get all trades at once without individually calling for each symbol?

**Comment by JKorf** [comment]
Hi, no currently that's to only way Binance offers the information. However if you listen to the order updates from the user stream using the BinanceSocketClient you can get aggregated stats about an order like `AccumulatedQuantityOfFilledTrades`, `PriceLastFilledTrade`, `Commission` and `CommissionAsset`. If you want full details you'd still have to use the GetMyTrades endpoint though.

**Comment by awaismemon26** [comment]
Can you specify which Method in BinanceSocketClient provide Aggregated status about an order like AccumulatedQuantityOfFilledTrades, PriceLastFilledTrade, Commission and CommissionAsset ?

**Comment by JKorf** [comment]
The BinanceSocketClient has a method `SubscribeToUserStream`, which takes a listen key and 2 update handlers. The listen key can be retrieved by calling `StartUserStream` on the BinanceClient. The 2 updates handlers are for receiving account updates (balances) and order updates. These order updates provide those fields.

**Comment by awaismemon26** [comment]
hey, can you tell me is there any method to get BTC price at the time of trade on all BTC pairs?

**Comment by JKorf** [comment]
At the time of what trade? The latest prices for all pairs can be retrieved using the `Get24HPricesList` method.
