### ISSUE TITLE
Is Ping/Keep-alive a ListenKey (USER_STREAM) implemented?

### ISSUE THREAD

**Issue by mohmog** [JKorf/Binance.Net#1190]
Greetings,

I am facing issue sometime user stream does not update when some orders are executed after placing them by many hours.

It seems the UserStream expire or something happen.

So Is Ping/Keep-alive a ListenKey (USER_STREAM) implemented?

**Comment by HypsyNZ** [comment]
You need to call `KeepAliveUserStreamAsync`

**Comment by JKorf** [comment]
As @HypsyNZ mentioned, the `KeepAliveUserStreamAsync` method should be called every  +- 30 minutes after subscribing to a user stream
