### ISSUE TITLE
Wrong Closing Values of klines (candle data) from Websocket / Binance!

### ISSUE THREAD

**Issue by Zain19900** [JKorf/Binance.Net#1191]
Hey Guys,
I am a newbie in coding, I just started learning about websocket and wanted to use it in getting data from Binance. At the beginning all the data and values of candles were being retrieved correctly. then I closed the connection multiple times to change somethings in my code. AAAAND all of a sudden the closing values of all the candles are wrong!! I was using Binance REST API to get this data and changed to Websocket just to get more accurate data but for some reason the closing values are wrong!! 
Please help me understand what is happening and why am i getting wrong close values?? note: it's a seconds interval candle so all the candles are closed and there values can't change. 

here is the simple code I wrote:

`import websocket
import json
import datetime

def on_message(ws, message):
    data = json.loads(message)
    print(datetime.datetime.fromtimestamp(data['k']['t'] / 1000), ' ', datetime.datetime.now())
    print('open: ', data['k']['o'], ' high: ', data['k']['h'], ' low: ', data['k']['l'], ' close: ', data['k']['c'])
    open = float(data['k']['o'])
    close = float(data['k']['c'])
    print('open: ', open, 'close: ', close)

def on_error(ws, error):
    print(error)

def on_close(close_msg):
    print(close_msg)

def Get_Share_Data(symbol, interval):

    socket = f'wss://stream.binance.com:9443/ws/{symbol}@kline_{interval}'
    ws = websocket.WebSocketApp(socket, on_message=on_message, on_error=on_error, on_close=on_close)
    ws.run_forever()

Get_Share_Data('btcusdt', '1s')
`

**Comment by HypsyNZ** [comment]
Maybe I am misunderstanding what you are saying but what are you comparing it to?

How do you know its wrong?

**Comment by Zain19900** [comment]
The values I get from the websocket code i wrote includes seconds based klines that have prices of a share (here it is bitcoin), the prices it includes are open, high, low, close. these values if they are correct must match exactly the values that are displayed on **Binance's trading chart**. When I check the values for the given interval (here it is seconds), I notice that the open, high, low prices are all exactly the same but when I check the close price (between the results of my code and the displayed price in the chart on Binance) they are different which means that something is wrong. That's the problem. 
Note that this problem didn't exist when I ran the code the first time ( i don't know why) but when I ran again after 2 hours the problem happened.
Did you understand my issue? 

I don't fully understand what you mean here:
(Also, Binance.Net uses ClientWebSocket)

Please guide me through this because I started learning coding 2 weeks ago (So I most probably don't fully know how things work generally in coding)

**Comment by HypsyNZ** [comment]
You aren't using `Binance.net`

**Comment by Zain19900** [comment]
Do you mean `Binance.com`? because as far a I know `Binance.net` doesn't exist!
