### ISSUE TITLE
Rate Limiter not working

### ISSUE THREAD

**Issue by ReaperOfTheSoul** [JKorf/Binance.Net#1194]
**Describe the bug**
if i debug my requests rate limiting schould be set to wait, but it is requesting anyway and i receive an error that i do to many requests 

**To Reproduce**
call endpoint 3 times short after eachother to retrive the full list
RestClient.SpotApi.Account.GetFiatDepositWithdrawHistoryAsync 

**Expected behavior**
3th call schould wait until it is rate limit is over

**Comment by JKorf** [comment]
How are you configuring the rate limiting?

**Comment by ReaperOfTheSoul** [comment]
Default in wait, tracked it withbthe debugger



Sent from my Galaxy



-------- Original message --------
From: Jan Korf ***@***.***>
Date: 2/5/23 17:11 (GMT+01:00)
To: "JKorf/Binance.Net" ***@***.***>
Cc: ReaperOfSouls ***@***.***>, Author ***@***.***>
Subject: Re: [JKorf/Binance.Net] Rate Limiter not working (Issue #1194)


How are you configuring the rate limiting?

**Comment by JKorf** [comment]
The weight of that request wasn't set correctly. I've updated it in the latest version.
