### ISSUE TITLE
sign in using PrivateKey

### ISSUE THREAD

**Issue by jkaa2** [JKorf/Binance.Net#1196]
Hello,

I used to login with a key/secret combination but yesterday I got an email from 
binance asking to use restricted ip configration in my api panel inorder to do actual trading (permissions other than reading),
now I can't use static ip, so I went to the self generated ip key choise and followed the steps shown in the link below and got two files
public and private key data, I tried to use the data in the private key file and plugin it into this constructor "ApiCredentials(PrivateKey privateKey)"
but I keep getting ("ApiKey/Secret needed") exception,

I don't know if I'm doing things wrong or this functionality is'nt supported, any suggestion is appriciated, thanks

https://www.binance.com/en/support/faq/how-to-generate-an-rsa-key-pair-to-send-api-requests-on-binance-2b79728f331e43079b27440d9d15c5db

**Comment by JKorf** [comment]
Hi, this isn't currently supported, but I'll have a look at adding it

**Comment by JKorf** [comment]
Hi, I've added support in the latest version. You can pass the private key in the secret parameter and then specify the AuthenticationType on the ApiCredentials as well. Let me know if you have any issues

**Comment by jkaa2** [comment]
Thanks
