### ISSUE TITLE
BinanceClientSpotApiTrading.GetConvertTransferHistoryAsync() is not working

### ISSUE THREAD

**Issue by grante** [JKorf/Binance.Net#1199]
**Current state**
Calling BinanceClientSpotApiTrading.GetConvertTransferHistoryAsync() results in an error response.

**Resolution**
This API should be called via an HTTP GET, but the code is using an HTTP POST.  Official Binance documentation says use GET.  I have tested GET and it works.

**Comment by JKorf** [comment]
Thanks, fixed it in the latest version
