### ISSUE TITLE
Version 8.3.1 to Version 8.4.0 got the Error 'Unable to cast object of type 'CryptoExchange.Net.Authentication.ApiCredentials' to type 'Binance.Net.Objects.BinanceApiCredentials

### ISSUE THREAD

**Issue by dante1989** [JKorf/Binance.Net#1202]
Dim clientBinance = New BinanceClient 'API Binance
                    clientBinance.SetApiCredentials(New ApiCredentials(API_Binance1, Secret_Binance1))

 Dim GiaCoin As WebCallResult(Of IBinance24HPrice)
                    GiaCoin = Await clientBinance.UsdFuturesApi.ExchangeData.GetTickerAsync(Symbol)

Version 8.3.1: it works normally
Version 8.4.0: it got the error **System.InvalidCastException: 'Unable to cast object of type 'CryptoExchange.Net.Authentication.ApiCredentials' to type 'Binance.Net.Objects.BinanceApiCredentials'.'**

![error new](https://user-images.githubusercontent.com/39071426/218286410-1e442b49-99ce-4316-a6d4-dc9dec5e4c04.png)

**<HTML>
<head>
<title>Document</title></head>
<body>

  | Name | Value | Type
-- | -- | -- | --
  | StackTrace | "   at Binance.Net.Clients.UsdFuturesApi.BinanceClientUsdFuturesApi.CreateAuthenticationProvider(ApiCredentials credentials)" & vbCrLf & "   at CryptoExchange.Net.BaseApiClient.get_AuthenticationProvider()" & vbCrLf & "   at CryptoExchange.Net.RestApiClient.ConstructRequest(Uri uri, HttpMethod method, Dictionary`2 parameters, Boolean signed, HttpMethodParameterPosition parameterPosition, ArrayParametersSerialization arraySerialization, Int32 requestId, Dictionary`2 additionalHeaders)" & vbCrLf & "   at CryptoExchange.Net.RestApiClient.<PrepareRequestAsync>d__26.MoveNext()" & vbCrLf & "   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)" & vbCrLf & "   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)" & vbCrLf & "   at CryptoExchange.Net.RestApiClient.<SendRequestAsync>d__25`1.MoveNext()" & vbCrLf & "   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)" & vbCrLf & "   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)" & vbCrLf & "   at Binance.Net.Clients.UsdFuturesApi.BinanceClientUsdFuturesApi.<SendRequestInternal>d__31`1.MoveNext()" & vbCrLf & "   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)" & vbCrLf & "   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)" & vbCrLf & "   at Binance.Net.Clients.UsdFuturesApi.BinanceClientUsdFuturesApiExchangeData.<GetTickerAsync>d__44.MoveNext()" & vbCrLf & "   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)" & vbCrLf & "   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)" & vbCrLf & "   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()" & vbCrLf & "   at Bot_Trade.FormMain.VB$StateMachine_412_MoPhongBotDailyTrade_TickerOn.MoveNext() in C:\Users\DELL\Documents\Bot Trade V2023.02.06\Bot Trade\FormMain.vb:line 22004" & vbCrLf & "   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)" & vbCrLf & "   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)" & vbCrLf & "   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()" & vbCrLf & "   at Bot_Trade.FormMain.VB$StateMachine_405_ButtonMoPhongDailyTrade_Click.MoveNext() in C:\Users\DELL\Documents\Bot Trade V2023.02.06\Bot Trade\FormMain.vb:line 13127" | String

</body>
</HTML>**

**Comment by JKorf** [comment]
Change `clientBinance.SetApiCredentials(New ApiCredentials(API_Binance1, Secret_Binance1))` to `clientBinance.SetApiCredentials(New BinanceApiCredentials(API_Binance1, Secret_Binance1))`

**Comment by dante1989** [comment]
> GiaCoin = Await clientBinance.UsdFuturesApi.ExchangeData.GetTickerAsync(Symbol)

done, thank you
