### ISSUE TITLE
Impossible to use GetFiatDepositWithdrawHistoryAsync

### ISSUE THREAD

**Issue by lukaszzborek** [JKorf/Binance.Net#1204]
After upgrade version to Binance v8.4.1, I can't get firat deposit history. Library throw error:
`Request limit reached without any prior request. This request can never execute with the current rate limiter. Request weight: 90000, Ratelimit: 12000`

Fiat `Deposit/Withdraw History` endpoint have UID weight, so it shouldn't be counted to ip limit. It should be counted to UID rate limit which is 180000 per minute. I check that and I can get fiat deposit history twice per minute, third one return rate limit error from Binance. For example `Fiat Payments History` have IP weight
![image](https://user-images.githubusercontent.com/8657646/219137523-b18b7a6e-1249-48eb-a6f7-2f7004cd54d0.png)
![image](https://user-images.githubusercontent.com/8657646/219137555-f1e0df55-387d-41cd-a94b-a85e9f11a2a9.png)

**Comment by JKorf** [comment]
Fixed in latest version.
unfortunately I don't have a way to differentiate between UID/IP limits so for now I've just upped the request limit to the UID limit.
