### ISSUE TITLE
Combine the currencies into a symbol

### ISSUE THREAD

**Issue by AntonC9018** [JKorf/Binance.Net#1207]
My issue is the complete opposite of [this one](https://github.com/JKorf/Binance.Net/issues/858).

I know a symbol consists of a pair of some currencies, but the order seems to be important too. Like the API call goes through with `BNBBTC` but not with `BTCBNB`. Is there any consistent logic of ordering, or do I have to resort to manual validation, like shown in the linked issue?

**Comment by HypsyNZ** [comment]
The asset on the left is the `Base` asset

The asset on the right is the `Quote` asset

This information is available from the exchange information endpoint.

**Comment by AntonC9018** [comment]
For the purposes of monitoring any trades between these two currencies, in my understanding, whichever is the base asset and whichever is the quote one makes no difference, since one is just getting traded for another.

**Comment by HypsyNZ** [comment]
`Symbols`

Your assumptions are incorrect.

**Comment by JKorf** [comment]
Cleaning up old issues, if you feel this issue is still relevant feel free to comment.
It matters in terms of what the data means. Price is denoted in the quote asset, so you can't flip the assets around since then the data is incorrect.
