### ISSUE TITLE
socketClient.SpotStreams.SubscribeToOrderBookUpdatesAsync does not work 

### ISSUE THREAD

**Issue by pantonis** [JKorf/Binance.Net#1209]
````socketClient.SpotStreams.SubscribeToOrderBookUpdatesAsync```` does not receive any updates

**Comment by gianlucacini** [comment]
everything is working for me. we cannot help you without more context

**Comment by luke313** [comment]
I have same problem.
`socketClient.SpotStreams.SubscribeToOrderBookUpdatesAsync ` return `null`
all method start with **Subscribe** return `null`
