### ISSUE TITLE
-2010: Filter failure: MAX_NUM_ALGO_ORDERS

### ISSUE THREAD

**Issue by salocinx** [JKorf/Binance.Net#1212]
Hi. I get the following error when placing some OCO orders:

`-2010: Filter failure: MAX_NUM_ALGO_ORDERS`

According to Binance API documentation:

`The MAX_NUM_ALGO_ORDERS filter defines the maximum number of "algo" orders an account is allowed to have open on a symbol. "Algo" orders are STOP_LOSS, STOP_LOSS_LIMIT, TAKE_PROFIT, and TAKE_PROFIT_LIMIT orders.`

Where can I get the maximum amount of algo orders I am allowed to make?

Thank you!

**Comment by JKorf** [comment]
You can get all filters using the `client.SpotApi.ExchangeData.GetExchangeInfoAsync()` call

**Comment by salocinx** [comment]
Thank you very much!
