### ISSUE TITLE
GetOrdersAsync - Symbol not so mandatory

### ISSUE THREAD

**Issue by Wizeep** [JKorf/Binance.Net#1217]
Hello,

I am following up on this discussion: https://github.com/JKorf/Binance.Net/issues/1030

I was able to recover all the trades without doing it symbol by symbol.
I use the endpoint '/fapi/v1/allOrders'.

Contrary to what the Binance documentation says, the symbol is not mandatory.
And in Note, we find this : "The query time period must be less then 7 days"

What I do to retrieve everything, I make a loop that starts in 2017 (opening date of binance), until today's date, week by week.

I would now like to use your dependency, but the problem is that for "UsdFuturesApi.Trading.GetOrdersAsync", the symbol parameter is mandatory.

Is there any way to change this?
Thanks you

**Comment by IM-001** [comment]
I would like to know more about this as well.  How do you know that the symbol is not mandatory??  This has been a nightmare for all developers since years, I'd be surprised that you can retrieve the trades all at once.  It would be a game changer though.

**Comment by JKorf** [comment]
Turns out this was actually correct; I've made the parameter optional in the latest version
