### ISSUE TITLE
SubscribeToKlineStreamAsync Issue

### ISSUE THREAD

**Issue by myhorses2you** [JKorf/Binance.Net#122]
Hi,

I am able to retreive data using GetKLinesAsync method, however I would like it to be retreived using websockets.

I tried this piece of code, but it actually never fires. Can you point out where the problem is? I am working on C# WinForms environment.
 
```
private BinanceSocketClient socketClient;

private async Task RetreiveData()
{
    socketClient = new BinanceSocketClient();

    var successKline = await socketClient.SubscribeToKlineStreamAsync("bnbbtc", KlineInterval.OneMinute, (data) =>
    {
        //
        //  handling data
        //
    });
}
```

Edit: Also, I am wondering whether it is possible to subscribe more than one symbol at a time or do I need to subscribe each symbol seperately? 

Thank you.

**Comment by JKorf** [comment]
I assume you've found the solution. If not let me know.
