### ISSUE TITLE
what happened with the BinanceSocketClient AutoReconnect?

### ISSUE THREAD

**Issue by deivid1** [JKorf/Binance.Net#1221]
Before it was nice, it auto reconnected itself. Now it doesn´t and I don´t see the old options :

            BinanceSocketClientOptions socketOption = new BinanceSocketClientOptions
            { 
                AutoReconnect = true
                , recReconnectInterval = TimeSpan.FromSeconds(3),
            };

And now I don´t even receive the disconnection event in subscriptionResult.Data.ConnectionLost

**Comment by dvpot** [comment]
I have a similar problem.
Subscriptions have started to fail over time, without any message. (All ConnectionLost, ConnectionClosed and ConnectionRestored events are connected to my subscriptions)

Maybe it's related to the latest update to Binance.Net.8.4.3 and CryptoExchange.Net.5.4.1.

There were no such problems before, so I rolled back for now 
   Binance.Net.8.4.3 -> Binance.Net.8.4.2
   CryptoExchange.Net.5.4.1 -> CryptoExchange.Net.5.4.0

**Comment by JKorf** [comment]
Thanks for the report, I'll look into it

**Comment by tbrbde** [comment]
I also had to go back to Binance.Net.8.4.2 and CryptoExchange.Net.5.4.0 to get the subscriptions working again (for a long time).

**Comment by nov30th** [comment]
I just start using the Binance.Net with issue #1220 , ah, it was functional, I will wait for the fixing then.
I was trying to throw the exception from the socket connection direct to the program but a bit more code without injection so I just used "BTCUSDT" trades to "detect" if the connection was broken.

**Comment by JKorf** [comment]
Should be working again with the latest version, let me know if you have any issues
