### ISSUE TITLE
TestNet error /sapi/

### ISSUE THREAD

**Issue by vadyaravadim** [JKorf/Binance.Net#1222]
If you try to use TestNet (I don't understand why there are such complexities with replacing BaseAddress, a huge chance of making a mistake, maybe there is another way that I don't know about?)

Then when calling the method .SpotApi.Account.GetBalancesAsync, a request is made to https://testnet.binance.vision/sapi/v3/asset/getUserAsset
As far as I understand, the error is in "/sapi/" - there's an extra letter "s".

Example:
var binanceClientOpt = new BinanceClientOptions()
    {
        ApiCredentials =
            new BinanceApiCredentials(cfg.ApiKey,
                cfg.SecretKey),
        LogLevel = LogLevel.Debug,
    };

binanceClientOpt.SpotApiOptions.BaseAddress = BinanceApiAddresses.TestNet.RestClientAddress;
binanceClientOpt.CoinFuturesApiOptions.BaseAddress = BinanceApiAddresses.TestNet.CoinFuturesRestClientAddress;
binanceClientOpt.UsdFuturesApiOptions.BaseAddress = BinanceApiAddresses.TestNet.UsdFuturesRestClientAddress;

_client = new BinanceClient(binanceClientOpt);
_client.SpotApi.Account.GetBalancesAsync("usdt")

Response:

OriginalData: 
400: <!DOCTYPE html>
<html lang="en">
<head>
    <title>Binance Spot Test Network</title>
    <link rel="shortcut icon" type="image/x-icon" href="/static/images/common/favicon.ico"/>
    <style>
..........
    </style>
    <link href="/static/fonts/index.min.css" rel="stylesheet" type="text/css">
</head>
<body>
    <header id="header">
        <a href="/">
        </a>
        <div id="title">Spot Test Network</div>
    </header>
    <div id="body">
        <main id="content">
            <div class="block">
                <h2>
                    Something bad happened :(
                </h2>
            </div>
            
            <div class="back">
                <a href="/">Back</a>
            </div>
        </main>
    </div>
    <footer id="footer">
        <a href="/terms">Terms</a>
        |
        <a href="/privacy">Privacy</a>
        |
        &copy; 2017 -  Binance.com. All rights reserved
    </footer>
</body>
</html>

RequestUrl: https://testnet.binance.vision/sapi/v3/asset/getUserAsset

**Comment by vadyaravadim** [comment]
@HypsyNZ 
I apologize, but how do I correctly set up the client for requests to the test server?

**Comment by JKorf** [comment]
`sapi` is a specific part of the Binance API, it's not a typo. The `sapi` api isn't supported on testnet though. I'll look into making it easier to switch environments
