### ISSUE TITLE
Duplicate/Incorrect entry found in SymbolFilterTypeConverter

### ISSUE THREAD

**Issue by mga70** [JKorf/Binance.Net#1224]
The last 2 entries in the "Mapping" have the same key "SymbolFilterType.TrailingDelta", indicating a copy & paste error.

    internal class SymbolFilterTypeConverter : BaseConverter<SymbolFilterType>
    {
        public SymbolFilterTypeConverter(): this(true) { }
        public SymbolFilterTypeConverter(bool quotes) : base(quotes) { }

        protected override List<KeyValuePair<SymbolFilterType, string>> Mapping => new List<KeyValuePair<SymbolFilterType, string>>
        {
            new KeyValuePair<SymbolFilterType, string>(SymbolFilterType.LotSize, "LOT_SIZE"),
            new KeyValuePair<SymbolFilterType, string>(SymbolFilterType.MarketLotSize, "MARKET_LOT_SIZE"),
            new KeyValuePair<SymbolFilterType, string>(SymbolFilterType.MinNotional, "MIN_NOTIONAL"),
            new KeyValuePair<SymbolFilterType, string>(SymbolFilterType.Price, "PRICE_FILTER"),
            new KeyValuePair<SymbolFilterType, string>(SymbolFilterType.PricePercent, "PERCENT_PRICE"),
            new KeyValuePair<SymbolFilterType, string>(SymbolFilterType.IcebergParts, "ICEBERG_PARTS"),
            new KeyValuePair<SymbolFilterType, string>(SymbolFilterType.MaxNumberOrders, "MAX_NUM_ORDERS"),
            new KeyValuePair<SymbolFilterType, string>(SymbolFilterType.MaxNumberAlgorithmicOrders, "MAX_NUM_ALGO_ORDERS"),
            new KeyValuePair<SymbolFilterType, string>(SymbolFilterType.MaxPosition, "MAX_POSITION"),
            new KeyValuePair<SymbolFilterType, string>(SymbolFilterType.PercentagePriceBySide, "PERCENT_PRICE_BY_SIDE"),
            new KeyValuePair<SymbolFilterType, string>(SymbolFilterType.TrailingDelta, "TRAILING_DELTA"),
            new KeyValuePair<SymbolFilterType, string>(SymbolFilterType.TrailingDelta, "NOTIONAL"),
        };
    }

**Comment by CitrusVento** [comment]
as result error "Value cannot be null. (Parameter 'value')" in method SpotApi.ExchangeData.GetExchangeInfoAsync()

**Comment by Nand2com** [comment]
Yes, the error is related to SpotApi.ExchangeData.GetExchangeInfoAsync(). I think it fails to deserialize the json for some reason. In the documentation it warned that there would be changes in that function.

**Comment by CitrusVento** [comment]
Filter "Notional" was added to 2 characters and this error occur
![image](https://user-images.githubusercontent.com/13800221/231432283-e73aa2de-7600-4a25-8a47-7d99b9cc2395.png)

**Comment by JozefGula** [comment]
@HypsyNZ Can we expect a new update for nuget?

**Comment by HypsyNZ** [comment]
> @HypsyNZ Can we expect a new update for nuget?

@JKorf has to do that

**Comment by HypsyNZ** [comment]
Fixed in https://github.com/JKorf/Binance.Net/commit/b6a78b1e66710b0c58533c2671eb9a46360c5330

**Comment by JKorf** [comment]
Has been fixed in version 8.4.4
