### ISSUE TITLE
GetExchangeInfoAsync some symbols (like MATICUSDT and SSVUSDT) returned error with null data

### ISSUE THREAD

**Issue by hossamnew** [JKorf/Binance.Net#1228]
Hello, kindly help, these specific symbols return null data at GetExchangeInfoAsync  even if within a big list of symbols, the all method return null at data:

MATICUSDT
SSVUSDT
XECBUSD

![image](https://user-images.githubusercontent.com/3645637/231512349-01ae48d3-d9da-4b26-99c6-a6d7e715103f.png)

 but when call the API link it's a good return data?
https://api.binance.com/api/v3/exchangeInfo?symbol=SSVUSDT

**Comment by HypsyNZ** [comment]
Fixed in https://github.com/JKorf/Binance.Net/commit/b6a78b1e66710b0c58533c2671eb9a46360c5330

**Comment by JKorf** [comment]
Has been fixed in latest version (8.4.4)

**Comment by hossamnew** [comment]
Many thanks ♥
