### ISSUE TITLE
GetAccountInfo sometimes return null

### ISSUE THREAD

**Issue by D0ctorWh0** [JKorf/Binance.Net#123]
I am using this code to get account info

```
            Binance.Net.BinanceClient client = new Binance.Net.BinanceClient();
            client.SetApiCredentials(public_key, secret_key);
            Binance.Net.Objects.BinanceAccountInfo result2 = client.GetAccountInfo(5000).Data;
```

But sometimes result2 value is just null

**Comment by JKorf** [comment]
You should check if the call is successful. Instead of doing `var result2 =client.GetAccountInfo(5000).Data`, call `var result2 = client.GetAccountInfo(5000)` and check the success flag: 
````C#
if(results2.Success)
{
   // Handle the data
}
else
{
    Console.WriteLine(result2.Error);
}
````

**Comment by D0ctorWh0** [comment]
I can't. GetAccountInfo return null, so result2 is null

**Comment by JKorf** [comment]
The `client.GetAccountInfo(5000)` call returns a `CallResult` object, which is never null. You're referring to `client.GetAccountInfo(5000).Data` which accesses the `Data` property of the `CallResult` object. That can be null if the `Error` property of the `CallResult` object is set.

**Comment by D0ctorWh0** [comment]
But it's null...
![default](https://user-images.githubusercontent.com/13037461/45230400-60fe7d00-b2d1-11e8-865c-5069332dc1fe.png)

**Comment by D0ctorWh0** [comment]
2 days it worked just fine, but today it return null very often. I am making project for android, may be this will help to resolve issue.

**Comment by JKorf** [comment]
Sorry, I missunderstood. Can you put logging on debug in the BinanceClientOptions and see what Binance returns? Because I'm pretty sure they're not sending the data then..

**Comment by D0ctorWh0** [comment]
From logs i found that error was "Timestamp for this request is outside of the recvWindow"
Now i set recvWindow to 10000000 and though debugger says that result2 is null it works

**Comment by JKorf** [comment]
Hi, can you try with the latest version?

**Comment by JKorf** [comment]
I assume this is fixed. If not, let me know.
