### ISSUE TITLE
Exception in the call _client.SpotApi.CommonSpotClient.GetSymbolsAsync()

### ISSUE THREAD

**Issue by masherak** [JKorf/Binance.Net#1232]
From today there is some problem with this endpoint:

<img width="813" alt="image" src="https://user-images.githubusercontent.com/15813908/231552163-725bca31-a278-4f6a-9348-bfdbff824b3d.png">

**Comment by JKorf** [comment]
Should be fixed in the latest version

**Comment by masherak** [comment]
@JKorf  Perfect, with the version 8.4.4 it is working well. Thank you very much for you quick answer!
