### ISSUE TITLE
Error from CoinFuturesApi.Trading.GetOrdersAsync

### ISSUE THREAD

**Issue by dante1989** [JKorf/Binance.Net#1234]
Dim ItemGetAllOrder As WebCallResult(Of IEnumerable(Of BinanceFuturesOrder)) = Await clientBinance.UsdFuturesApi.Trading.GetOrdersAsync("BTCUSDT") 
        MsgBox(ItemGetAllOrder.Data.Count)

>>>>It works normally

        Dim ItemGetAllOrder_Coin As WebCallResult(Of IEnumerable(Of BinanceFuturesOrder)) = Await clientBinance.CoinFuturesApi.Trading.GetOrdersAsync("BTCUSD_PERP") 
        
        MsgBox(ItemGetAllOrder_Coin.Data.Count)

>>>> i got the error like this picture

![error](https://user-images.githubusercontent.com/39071426/232806666-e6072b74-a1e7-41ab-b199-c31707637724.png)

Source: https://binance-docs.github.io/apidocs/delivery/en/#all-orders-user_data

**Comment by JKorf** [comment]
Can you check the ItemGetAllOrder_Coin Error property?

**Comment by dante1989** [comment]
I think the error from **Pair**
UsdFuturesApi do not have the "Pair"
CoinFuturesApi have the "Pair"

But we use the same **BinanceFuturesOrder** to get data

![Error3](https://user-images.githubusercontent.com/39071426/232826524-481919c7-6e5d-41cf-a5ff-6faa3250ce3c.png)

**Comment by dante1989** [comment]
I don't see this error appearing anymore, maybe this error comes from Binance's server and not from our API, thank you
