### ISSUE TITLE
Stream Error

### ISSUE THREAD

**Issue by JozefGula** [JKorf/Binance.Net#1236]
I detected the problem with SPOT stream.

Binance    | Deserialize JsonSerializationException: Error converting value "NONE" to type 'System.Nullable`1[System.Int64]'. Path 'data.V', line 37, position 15. data: { "e": "executionReport", "E": 1681989317915, "s": "........", "c": "........", "S": "BUY", "o": "LIMIT", "f": "GTC", "q": "........", "p": "0.00001064", "P": "0.00000000", "F": "0.00", "g": -1, "C": "........", "x": "CANCELED", "X": "CANCELED", "r": "NONE", "i": 690100719, "l": "0.00", "z": "0.00", "L": "0.00000000", "n": "0", "N": null, "T": 1681989317915, "t": -1, "I": 1470230425, "w": false, "m": false, "M": false, "O": 1681989187009, "Z": "0.00000000", "Y": "0.00000000", "Q": "0.00000000", "W": 1681989187009, **"V": "NONE"** }

Thanks

**Comment by JKorf** [comment]
Hi, thanks for the report. I've pushed version 8.5.1 which should fix it

**Comment by andresdrb** [comment]
seems the binance guys are playful today. I've stopped receiving price stream updates earlier today. Maybe they have updated/broken more stuff on the streaming appart from that one above?
