### ISSUE TITLE
macos xamarin VisualStudio .NET6/7: PlatformNotSupportedException when creating BinanceClient

### ISSUE THREAD

**Issue by ayartsev7** [JKorf/Binance.Net#1237]
Hi,
I tried to build minimal .NET 7.0 (also tried .NET 6.0) xamarin application that uses Binance.Net 8.5.1 NuGet package on macOS Ventura with VisualStudio 17.5.0.124 for Mac.
Ended up with `PlatformNotSupportedException` at line `var client = new BinanceClient();`
Does Binance.Net supposed to work with such configuration?
Thank you for working on the project!

**Comment by JKorf** [comment]
Hm hard to say. .NET 6.0 (and 7.0 as well) is supported, so I suspect it might be either because of xamarin or because of macOS. Unfortunately I don't have a macOS to try it. 
Do you have a stack trace or something? Or is that all the info you get?

**Comment by JKorf** [comment]
It seems like you're trying to use a proxy, that's not supported on mobile apps if im correct

**Comment by ayartsev7** [comment]
Thanks for the hint, will dig into it.

**Comment by HypsyNZ** [comment]
> Thanks for the hint, will dig into it.

does it work without the proxy

**Comment by ayartsev7** [comment]
> does it work without the proxy (easy test)
I've checked - proxy is disabled in macos settings, error persists. I am new to macos in general and to vs for macos in particular, still cannot find any other place to manage proxies.

**Comment by JKorf** [comment]
The issue shouldn't be in the operating system settings but rather in the client options of the BinanceClient. Are you specifying a proxy there?

**Comment by ayartsev7** [comment]
> The issue shouldn't be in the operating system settings but rather in the client options of the BinanceClient. Are you specifying a proxy there?

No, I do not pass any arguments `var client = new BinanceClient();`

**Comment by JKorf** [comment]
Can you try this?
```
var httpClient = new HttpClient();
var binanceClient = new BinanceClient(new BinanceClientOptions{
  SpotApiOptions = new BinanceApiClientOptions { HttpClient = httpClient },
  UsdFuturesApiOptions= new BinanceApiClientOptions { HttpClient = httpClient },
  CoinFuturesApiOptions= new BinanceApiClientOptions { HttpClient = httpClient }
});
```

**Comment by PavelSupenko** [comment]
The code above doesn't help unfortunately. I think proxy is not a problem. The real problem as I can see is 'System.Reflection.RuntimeMethodInfo.Invoke' because my app is building with MAUI (it uses the same logic as a Xamarin) has the same error on Mac / iOS but working well for Windows and Android.
I'm new in cross-platform .Net applications but from my experience in game developing Apple restricts using JIT and reflection usages and allow only AOT compiled code. I think this is the real problem.

**Comment by HypsyNZ** [comment]
> The issue shouldn't be in the operating system settings but rather in the client options of the BinanceClient. Are you specifying a proxy there?

> > The issue shouldn't be in the operating system settings but rather in the client options of the BinanceClient. Are you specifying a proxy there?
> 
> No, I do not pass any arguments `var client = new BinanceClient();`

Well if you are using the proxy transparently then it probably isn't the issue because your application isn't even aware of a proxy.

**Comment by HypsyNZ** [comment]
did you solve the issue @ayartsev7

**Comment by ayartsev7** [comment]
> Can you try this?
var httpClient = new HttpClient();
var binanceClient = new BinanceClient(new BinanceClientOptions{
  SpotApiOptions = new BinanceApiClientOptions { HttpClient = httpClient },
  UsdFuturesApiOptions= new BinanceApiClientOptions { HttpClient = httpClient },
  CoinFuturesApiOptions= new BinanceApiClientOptions { HttpClient = httpClient }
});

This worked for me, thank you!

**Comment by JKorf** [comment]
Great, the issue is that even though no proxy is actually being set, the HttpClient.Proxy porperty is still accessed by setting it to null. Apparentlyany access to the Proxy property will throw and exception, even when you try to set it to null.

I'll fix that in the library so that the above work around won't be needed.
