### ISSUE TITLE
Resyncing timestamp not working.

### ISSUE THREAD

**Issue by Kudwig** [JKorf/Binance.Net#124]
Good day
Thanks for a great api.
ive got a similar issue as :https://github.com/JKorf/Binance.Net/issues/82
 firstly, i set my client:
`  public static BinanceClient GetClient()
        {
            return new BinanceClient(new BinanceClientOptions
            {
                ApiCredentials = new CryptoExchange.Net.Authentication.ApiCredentials(key, secret),
                AutoTimestamp = true
            });
        }`
then, i use it later on as follow
` var info = exchange.Client.GetAccountInfo();

                if (info.Success)
                {
                 //handle some data
                }
                else
                {
                    _financeLog.AddError($"Account info error: {info.Error}");
                    if (info.Error.ToString().ToUpper().Contains("TIME"))
                    {
                        var time = exchange.Client.GetServerTime(resetAutoTimestamp: true);

                    }`

now, this mostly works for a while, but then after a few hrs, im starting to get in some instances where the timestamp is updated<by the log from api its visible >...but then, after another while, its still re-syncing, but then with every call, and igt keeps getting the error, not working at all...
any ideas?

**Comment by naviomg** [comment]
I have the exact same problem. Im initializing the client on the same way and after around 1 day i get the timestamp error.

**Comment by JKorf** [comment]
Hi, can you try with the latest version? I've added a recalculation interval and auto resync of timestamp after that period.
