### ISSUE TITLE
GetAssetDividendRecordsAsync returns "illegal parameter" error

### ISSUE THREAD

**Issue by nitrexx** [JKorf/Binance.Net#1241]
**Describe the bug**
Version: BInance.Net 8.5.1
When I call method **GetAssetDividendRecordsAsync** with **startTime and endTime** params it returns BadRequest with Error message: "{-1102: illegal parameter }"

**To Reproduce**
Call GetAssetDividendRecordsAsync with start and end time.
`await client.SpotApi.Account.GetAssetDividendRecordsAsync("ETH", startTime: someDate, endTime: DateTime.UtcNow, 
                        limit: 500)`

**Expected behavior**
Return data from startTime to endTime.

**Debug logging**
https://api.binance.com/sapi/v1/asset/assetDividend?asset=ETH&endTime=1682363701548&limit=500&recvWindow=5000&signature=XXXX&startTime=1640995200000&timestamp=1682450101435

**Comment by JKorf** [comment]
I can't reproduce this, specifying the parameters returns results as expected. Are you still having issues with this?
