### ISSUE TITLE
Version 8.6.0 WS stream

### ISSUE THREAD

**Issue by masherak** [JKorf/Binance.Net#1246]
Hello, please can you help me ? 

In the new version 8.6.0 I do not know how to replace these methods "_socketClient.SpotStreams.SubscribeToOrderBookUpdatesAsync" and "_socketClient.SpotStreams.SubscribeToUserDataUpdatesAsync"

Thank you

**Comment by JKorf** [comment]
Yes, the API has changed slightly, you can find them under
`binanceSocketClient.SpotApi.ExchangeData.SubscribeToOrderBookUpdatesAsync`
and 
`binanceSocketClient.SpotApi.Account.StartUserStreamAsync`

**Comment by masherak** [comment]
Thank you very much!
