### ISSUE TITLE
IBinanceSocketClient compile-time error after updating to version 8.6.0

### ISSUE THREAD

**Issue by Piggy69** [JKorf/Binance.Net#1248]
After updating to version 8.6.0 from 8.5.1 I got compile time errors CS1061:

'IBinanceSocketClient' does not contain a definition for 'SpotStreams' and no accessible extension method 'SpotStreams' accepting a first argument of type 'IBinanceSocketClient' could be found (are you missing a using directive or an assembly reference?)

The component is injected via Microsoft standard DI into my service class:

`        public BinanceSpotCandlestickStreamClient(ILogger<BinanceStreamClientBase<IBinanceStreamKlineData>> logger,
                                                  IOptions<CommonOptions> commonOptions,
                                                  IOptions<MarketDataFeedOptions> marketDataFeedOptions,
                                                  IBinanceSocketClient binanceSocketClient,
                                                  IDistributedCache cache) : base(logger,
                                                                                  commonOptions,
                                                                                  marketDataFeedOptions,
                                                                                  binanceSocketClient,
                                                                                  cache)`

and then the specfic point generating the error is:

`            
                await _binanceSocketClient.**SpotStreams**.SubscribeToKlineUpdatesAsync(symbol.Symbol,
                                                                                            symbol.CandlestickInterval ?? _interval,
                                                                                            ProcessDataEvent,
                                                                                            cancellationToken);

`
where the compiler identifies SpotStreams as the source of error.

I am sure the code was running smoothly just before the update because, restoring the reference to version 8.5.1 the error disappears and the project compiles and runs without any problem.

**Comment by vano-maisuradze** [comment]
Did you try to use SpotApi? `await _binanceSocketClient.SpotApi.SubscribeToKlineUpdatesAsync(...)`

**Comment by Piggy69** [comment]
Yes, I tried, but without success. The SpotApi property of the object is OK, but not the SubscribeToKlineUpdatesAsync method, which is not defined for SpotApi (it should be defined for SpotStreams).

**Comment by Piggy69** [comment]
After a quick test, changing `SpotStreams.SubscribeToKlineUpdatesAsync(...)` into `SpotApi.ExchangeData.SubscribeToKlineUpdatesAsync(...)` seems to be a valid workaround to the problem: the compile time error is solved and the runtime behavior seems to be as expected.

Should I find issues about this workaround, will reply into this issue to update.

Thank you @vano-maisuradze
