### ISSUE TITLE
Private endpoint, order  info update, not updating the same as api request

### ISSUE THREAD

**Issue by Kudwig** [JKorf/Binance.Net#125]
my second issue, 

```
public static List<BinanceStreamOrderUpdate> _orderData { get; set; }
.....
......

 binanceClient.SubscribeToUserStream(listenKey.Data.ListenKey, _data =>
                    {
                        // Hanlde account info data
                        //this feed equals this api call: var info = exchange.Client.GetAccountInfo();
                        //thus everytime my balances changes. i need an update on this data

                
                        ThirdBinanceAlgorithm.InfoData = _data;//this will work, updating correctly
                        OnEvent(_data);
                        //

                    },
                    _data =>
                    {

                        ThirdBinanceAlgorithm._orderData.Add(_data);//this doesn't reflect the same data as //var latestOrderscall = exchange.Client.GetAllOrders(_marketName)

                        OnEvent(_data);


                    });
```

right, so basically, im not sure if its an api issue, or an issue from binance socket feed, but, running from the socket feed data, ive found that the data from the socket feed does not reflect an acurate version of your account info, the data you get from the api request .GetAllOrders(_marketName), is more up to date than the socket feed, where orders thats filled or canceled can be picked up or handled better.

**Comment by JKorf** [comment]
Hi, can you give a little more details on what you mean with GetAccountInfo being more up to date? GetAccountInfo doesn't return order information. If you mean another api call, what info is missing/not up to date?

**Comment by Kudwig** [comment]
sorry, my mistake, 

>  ThirdBinanceAlgorithm.InfoData = _data;
represents basically the same data as the api call:
var info = exchange.Client.GetAccountInfo();
which is updating correctly mostly via the socket feed
the second part thou:
> _data =>
                    {

                        ThirdBinanceAlgorithm._orderData.Add(_data);
...
}
which represents the api call 
var latestOrderscall = exchange.Client.GetAllOrders(_marketName);

does not update from socket feed with the exact data as the api call will give,
example, i can cancel an order, then run the api call, and it doesnt reflect the same as the data from the socket feed

ive also found in some instances the socket feed is dropped by binance, thou im still collecting more info in this issue.
regards

**Comment by JKorf** [comment]
Still not sure what the exact data is that is not correct. I tried with this simple snippet:

````C#
socketClient.SubscribeToUserStream(client.StartUserStream().Data.ListenKey, data => { }, data =>
            {
                Console.WriteLine($"Order update: {data.OrderId}, {data.Symbol}, {data.Type}, {data.Side}, {data.Status}, price: {data.Price}, quant: {data.Quantity}");
                Task.Run(() =>
                {
                    var order = client.GetAllOrders("NANOBTC").Data.Single(o => o.OrderId == data.OrderId);
                    Console.WriteLine($"Order from api: {order.OrderId}, {order.Symbol}, {order.Type}, {order.Side}, {order.Status}, price: {order.Price}, quant: {order.OriginalQuantity}");
                });
            });
````
and this is the result: 
![image](https://user-images.githubusercontent.com/8448172/45343361-eff4e900-b5a0-11e8-89eb-0ab55df09bff.png)
So that seems fine. Can you elaborate?

**Comment by JKorf** [comment]
Does it not update any order after this time? Do you check to see if the socket connection is still up?
You can subscribe to the closed event like this: 
````C#
var sub = socketClient.SubscribeToUserStream(client.StartUserStream().Data.ListenKey, data => { }, data =>
            {
                 // Process data
            });
            sub.Data.Closed += () =>
            {
                Console.WriteLine("Closed");
            };
````
Also, the user stream should be kept alive by sending a KeepAlive request with the BinanceClient every 30 minutes after starting the user stream.

**Comment by Kudwig** [comment]
ok, ill try to implement, but might need some help on the "KeepAlive" section
here is a part of socket stream subscription:
` protected override bool Subscribe()
        {
            var binanceClient = (FeedInfo.Exchange as IBinanceExchange).SocketClient;

            var marketLower = _marketName.ToLower();

            SubscriptionExecute = () =>
            {
                
                    var successTrades = binanceClient.SubscribeToKlineStream(marketLower, KlineInterval.OneMinute, (data) =>
                    {
                        ThirdBinanceAlgorithm._dData = data.Data;
                        OnEvent(data);
                    });
                successTrades.Data.Closed += () =>
                {
                    Console.WriteLine("Closed");
                };

            };

            return true;
        }`

and then where i call it in the algorithm:

`  protected override void InitFeeds(IFeedService feedService)
        {
            // Here you can read additional data
            feedService = new FeedService( );
            Feeds = new List<IFeedListener>();
            var feedInfo = feedService.CreateBinanceFeed("BinanceFeedTwo");
            Feeds.Add(new Feeds.Implementations.ThirdBinanceAlgorithmSecondListener(feedInfo, _marketName));
            Feeds[0].FeedAction += ThirdBinanceAlgorithm_FeedAction1;
            
            
            feedInfo = feedService.CreateBinanceFeed("BinanceFeedOne");
            Feeds.Add(new Feeds.Implementations.ThirdBinanceAlgorithmFirstListener(feedInfo, _marketName));
            Feeds[1].FeedAction += ThirdBinanceAlgorithm_FeedAction;//is it possible to test if this feed has been opened yet by another algorithm?..if so, then we can only use the data

            base.InitFeeds(feedService);
            
            
            
           
        }

        private void ThirdBinanceAlgorithm_FeedAction(string arg1, string arg2, dynamic arg3)
        {
           
        }

        private void ThirdBinanceAlgorithm_FeedAction1(string exchangeName, string feedName, dynamic sunscriptionEvent)
        {
            //Here you implement your trading algorithm after feed or just call "Body"
            BodyAsync();
        }`

**Comment by JKorf** [comment]
The KeepAlive message is only neccessary for the UserStream, others like the KlineStream will just keep on running. After starting and subscribing to the user stream you could do something like this:
````C#

bool running = true;
            var listenKey = ""; // The listen key returned from StartUserStream request
            Task.Run(() =>
            {
                while (running)
                {
                    using (var client = new BinanceClient())
                    {
                        var keepAliveResult = client.KeepAliveUserStream(listenKey);
                        if (!keepAliveResult.Success)
                        {
                            // Some error handling
                        }
                    }

                    Thread.Sleep(1000 * 60 * 30); // Sleep 30 minutes

                }
            });

````

You might want to be able to stop it in a better way, but you get the idea I hope.

**Comment by Kudwig** [comment]
ok thnx, ive changed it a little, ive got a "stopwatch" im using for other purposes, so im going to run the request every 30 min...
as follow
```
if (((_myTimer.Elapsed.Seconds) % 1800) == 0)
            {
                var keepAliveResult = exchange.Client.KeepAliveUserStream(_listenkey);
                if (!keepAliveResult.Success)
                {
                    // Some error handling
                    _financeLog.AddError($"Keepalive failed :{keepAliveResult.Error}");
                }
            }

```
so this will basically cover this issue:
[API-Frequently-Asked-Questions-FAQ](https://support.binance.com/hc/en-us/articles/360004492232-API-Frequently-Asked-Questions-FAQ-)

> 
> Why are my websocket connections being dropped/disconnected?
> 
> Every 3 minutes, active websocket connections will receive a ping. If you do not respond with a properly framed pong, your connection will be terminated.
> 
> For user data streams, if a keep-alive is not received at least once every 60 minutes, the listen key will expire. This is also detailed in our WAPI Documentation.

i will test it as i get time and keep you updated
regards

**Comment by DigitalMystery** [comment]
I think my issue might be the same as this persons....  if not I will create a new thread.  When I subscribe to depth stream I get huge variations in price.  Example TRX/BNB I will get .0014 for a bid and .0023 for an ask.  But if I call get order book I get what is being shown on the Binance ticker at the time something like .002251 for a bid and .0023 for the ask.  I have no idea where the super low bid is even coming from.  I am removing all where quantity is 0 as well.....  I wish it was that wide of a variation!  Any ideas?

**Comment by JKorf** [comment]
Can you share your code for maintaining the order book?

**Comment by JKorf** [comment]
Closing this for not enough information, re-open and provide more information if this is still an issue.
