### ISSUE TITLE
Rolling window price change statistics

### ISSUE THREAD

**Issue by tbrbde** [JKorf/Binance.Net#1251]
I know GetTickerAsync, which provides data for the last 24 hours. But the Binance API also provides a data ticker for various other time frames:
https://github.com/binance/binance-spot-api-docs/blob/master/rest-api.md#rolling-window-price-change-statistics
I can't find any implementation for this in Binance.net. Did I miss something or is this functionality missing?

**Comment by JKorf** [comment]
Should be available under `client.SpotApi.ExchangeData.GetRollingWindowTickerAsync`

**Comment by tbrbde** [comment]
Thank you!
