### ISSUE TITLE
USD Futures `GetUserTradesAsync` does not support the `orderId` parameter

### ISSUE THREAD

**Issue by shaunsales** [JKorf/Binance.Net#1252]
**Describe the bug**
According to the [Binance Docs](https://binance-docs.github.io/apidocs/futures/en/#account-trade-list-user_data)  the API endpoint to get trades for a user (`GET /fapi/v1/userTrades`) should support supplying both a  `symbol` and `orderid` to get the trades related to an order. 

The implementation in Binance.Net v8.6.1 does not support the `orderId` param.

**Comment by JKorf** [comment]
Added it in the latest version
