### ISSUE TITLE
Problem with SpotApi.ExchangeData.GetExchangeInfoAsync()

### ISSUE THREAD

**Issue by Josip9989** [JKorf/Binance.Net#1253]
First I'm calling:
var res = CLIENT.SpotApi.ExchangeData.GetExchangeInfoAsync();

This returns a list, and then I'm looping over that list and I'm trying to get to this property:
Binance.Net.Objects.Models.Spot.BinanceSymbol.MinNotionalFilter.MinNotional

But it is null:

![image](https://github.com/JKorf/Binance.Net/assets/38858840/22ac3ef3-be9f-4fbb-9b3f-4d9eccf87737)

Any ideas?

Thank you1

**Comment by dvpot** [comment]
An old problem.
Add a condition:
If MinNotionalFilter == null
then use NotionalFilter

**Comment by Josip9989** [comment]
Ok, that seems to fix it.
Thank you!
