### ISSUE TITLE
SpotApi > GetProductsAsync stopped working ?

### ISSUE THREAD

**Issue by jkaa2** [JKorf/Binance.Net#1254]
Hi,

- Can you please check (.SpotApi.ExchangeData.GetProductsAsync), it stopped working for me suddenly, I think it's from binance side
- Also I tried to update from 8.5.1 to 8.6.2 but the socket spotstreams namespace doesn't show up as illustrated in the image

![sd](https://github.com/JKorf/Binance.Net/assets/110682637/36ed2360-d58b-4c67-97f8-8e531db9fa6e)

**Comment by jkaa2** [comment]
* First point has been solved from binance side

**Comment by dvpot** [comment]
var result = await SocketClient.**SpotApi.Account**.SubscribeToUserDataUpdatesAsync( . . .
