### ISSUE TITLE
Invalid Api Key with testnet trading

### ISSUE THREAD

**Issue by il2fsomuch2022** [JKorf/Binance.Net#1255]
**Describe the bug**
I try to test future trading API in binance testnet and got error Invalid API Key

Here is my test  client

using Binance.Net.Clients;
using Binance.Net.Enums;
using Binance.Net.Interfaces.Clients;
using Binance.Net.Objects;
using CryptoExchange.Net.Authentication;
using CryptoExchange.Net.Logging;
using CryptoExchange.Net.Objects;
using Microsoft.Extensions.Logging;

BinanceClient.SetDefaultOptions(new BinanceClientOptions()
{
    ApiCredentials = new ApiCredentials("a513ff99420db9fde0cc604028ce2b44011d433ca0807ce2d2c60173eb82da3d", "96f305ce3613b00f666ac13b6bac273956227e01f562e22f11f3a5cdedf0bc18"), // <- Provide you API key/secret in these fields to retrieve data related to your account
    LogLevel = LogLevel.Debug
});
BinanceSocketClient.SetDefaultOptions(new BinanceSocketClientOptions()
{
    ApiCredentials = new ApiCredentials("a513ff99420db9fde0cc604028ce2b44011d433ca0807ce2d2c60173eb82da3d", "96f305ce3613b00f666ac13b6bac273956227e01f562e22f11f3a5cdedf0bc18"),
    LogLevel = LogLevel.Debug
});

string? read = "";
while (read != "R" && read != "S") 
{
    Console.WriteLine("Run [R]est or [S]ocket example?");
    read = Console.ReadLine();
}

if (read == "R")
{
    using (var client = new BinanceClient())
    {
        ((BinanceClientOptions)client.ClientOptions).UsdFuturesApiOptions.BaseAddress = "https://testnet.binancefuture.com";
        //await HandleRequest("Symbol list", () => client.SpotApi.ExchangeData.GetExchangeInfoAsync(), result => string.Join(", ", result.Symbols.Select(s => s.Name).Take(10)) + " etc");
        await HandleRequest("BTCUSDT book price", () => client.SpotApi.ExchangeData.GetBookPriceAsync("BTCUSDT"), result => $"Best Ask: {result.BestAskPrice}, Best Bid: {result.BestBidPrice}");
        //await HandleRequest("ETHUSDT 24h change", () => client.SpotApi.ExchangeData.GetTickerAsync("ETHUSDT"), result => $"Change: {result.PriceChange}, Change percentage: {result.PriceChangePercent}");
        await HandleRequest("Buy BTC", () => client.UsdFuturesApi.Trading.PlaceOrderAsync(
                "BTCUSDT",
                OrderSide.Buy,
                FuturesOrderType.Limit,
                0.001m,
                25500,
                timeInForce: TimeInForce.GoodTillCanceled), result => $"Order Status: {result.Status}, Filled Quantity: {result.QuantityFilled}");

        
    }
}
else
{
    Console.WriteLine("Press enter to subscribe to BTCUSDT trade stream");
    Console.ReadLine();
    var socketClient = new BinanceSocketClient();
   
    var subscription = await socketClient.SpotStreams.SubscribeToTradeUpdatesAsync("BTCUSDT", data =>
    {
        Console.WriteLine($"{data.Data.TradeTime}: {data.Data.Quantity} @ {data.Data.Price}");
    });
    if (!subscription.Success)
    {
        Console.WriteLine("Failed to sub: " + subscription.Error);
        Console.ReadLine();
        return;
    }

    subscription.Data.ConnectionLost += () => Console.WriteLine("Connection lost, trying to reconnect..");
    subscription.Data.ConnectionRestored += (t) => Console.WriteLine("Connection restored");

    Console.ReadLine();
    /// Unsubscribe
    await socketClient.UnsubscribeAllAsync();
}

static async Task HandleRequest<T>(string action, Func<Task<WebCallResult<T>>> request, Func<T, string> outputData)
{
    Console.WriteLine("Press enter to continue");
    Console.ReadLine();
    Console.Clear();
    Console.WriteLine("Requesting " + action + " ..");
    var bookPrices = await request();
    if (bookPrices.Success)
        Console.WriteLine($"{action}: " + outputData(bookPrices.Data));
    else
        Console.WriteLine($"Failed to retrieve data: {bookPrices.Error}");
    Console.WriteLine();
}

//var socketClient = new BinanceSocketClient();
//// Spot | Spot market and user subscription methods
//socketClient.Spot.SubscribeToAllBookTickerUpdatesAsync(data =>
//{
//    // Handle data
//});

//// FuturesCoin | Coin-M futures market and user subscription methods
//socketClient.FuturesCoin.SubscribeToAllBookTickerUpdatesAsync(data =>
//{
//    // Handle data
//});

//// FuturesUsdt | USDT-M futures market and user subscription methods
//socketClient.FuturesUsdt.SubscribeToAllBookTickerUpdatesAsync(data =>
//{
//    // Handle data
//});
Console.ReadLine();

**Comment by JKorf** [comment]
Cleaning up old issues; I assume this is no longer relevant. If it is feel free to comment.
