### ISSUE TITLE
The data flow is automatically cut off.

### ISSUE THREAD

**Issue by SARPSARP090** [JKorf/Binance.Net#1258]
Hello. The API is very healthy and works fine. However, I couldn't solve a problem. In a program I created with WindowsForm, for some reason, the data flow is interrupted after a while. I'm starting to not get current prices. Sometimes this happens within an hour, sometimes within 10 hours. it varies. Another situation is that although there is data flow, my buy or sell conditions are fulfilled but the buy or sell orders are not triggered. I experience this more often in futures trading. Sometimes this happens within an hour or a few. How do you think I can overcome this fatal problem for me? I am sure there is no error in my code. Only after a while the data flow is interrupted or the order triggering somehow does not happen. I request your help.

```
var client = new BinanceClient(new BinanceClientOptions
                    {  
                         ApiCredentials = new BinanceApiCredentials(textapi.Text, textsecret.Text),
                         SpotApiOptions = new BinanceApiClientOptions
                        {
                            BaseAddress = BinanceApiAddresses.Default.RestClientAddress,
                            AutoTimestamp = true,
                        },
                        UsdFuturesApiOptions = new BinanceApiClientOptions
                        {
                            TradeRulesBehaviour = TradeRulesBehaviour.ThrowError,
                            AutoTimestamp = true
                        }    
                });
```

**Comment by JKorf** [comment]
Hi, is it possible to enable Trace logging? LogLevel = LogLevel.Trace in the client options. It might give a hint on what's going wrong.

**Comment by SARPSARP090** [comment]
This is how I started logging, I hope I'm recording correctly. I will post the output here at the time of the outage within a maximum of 48 hours.


```
 var services = new ServiceCollection();
                    services.AddBinance((restClientOptions, socketClientOptions) =>
                    {
                        restClientOptions.ApiCredentials = new BinanceApiCredentials(textapi.Text, textsecret.Text);
                        restClientOptions.SpotApiOptions = new BinanceApiClientOptions
                        {
                            AutoTimestamp = true,
                            TimestampRecalculationInterval = TimeSpan.FromMinutes(30),
                            RateLimitingBehaviour = RateLimitingBehaviour.Wait
                        };
                        restClientOptions.LogLevel = LogLevel.Trace;
                        restClientOptions.LogWriters = new List<ILogger> { new ConsoleLogger() };

                        socketClientOptions.ApiCredentials = new BinanceApiCredentials(textapi.Text, textsecret.Text);
                        socketClientOptions.UsdFuturesStreamsOptions = new BinanceSocketApiClientOptions
                        {
                            AutoReconnect = true,
                            ReconnectInterval = TimeSpan.FromSeconds(15)
                        };
                    }, ServiceLifetime.Transient);
```

**Comment by JKorf** [comment]
The error is coming from Linq, which means youre calling some linq method on a null object.

**Comment by SARPSARP090** [comment]
you are absolutely right. actually the problem is in internet outages and null calls. this is totally my fault. now everything is fine. Thanks

**Comment by SARPSARP090** [comment]
Thanks for your attention. I'm closing the issue.
