### ISSUE TITLE
An unknown error occured while processing the request || code -1000

### ISSUE THREAD

**Issue by avechuche** [JKorf/Binance.Net#126]
Hello, is it possible that Binance is not working correctly? or that something has changed and the API is not working? Last night, it worked perfectly, but not today. thx!

**2018/09/10 12:45:20:705 | Warning | Server returned an error: {"code":-1000,"msg":"An unknown error occured while processing the request."}**

**Comment by JKorf** [comment]
Hm well it's the server that returns the error, so I would expect it's a problem on their side. What call(s) do you get this on?

**Comment by avechuche** [comment]
Hi JKorf, the problem was solved some time later. The error appeared when I used **_binanceSocketClient.SubscribeToUserStream**

**Comment by JKorf** [comment]
Hm, well I didn't change anything, so I guess the Binance server was having some issues. Glad it's working again!
