### ISSUE TITLE
SpotApi.ExchangeData.GetProductsAsync not working

### ISSUE THREAD

**Issue by jkaa2** [JKorf/Binance.Net#1262]
Hi,

Please check (.SpotApi.ExchangeData.GetProductsAsync), it's not working anymore, I don't know if this is due to a change from binance side or not.

![247291955-8f668785-9651-4178-8ecd-fdb529f70d25](https://github.com/JKorf/Binance.Net/assets/110682637/ff674712-4c17-4d55-a8cf-8282007afdd9)

**Comment by nov30th** [comment]
#1260
