### ISSUE TITLE
Cannot map enum value TRD_GRP_013

### ISSUE THREAD

**Issue by IM-001** [JKorf/Binance.Net#1263]
Hi!  I get a Warning when I query the Spot Symbols.

If you use this.binanceClient.SpotApi.ExchangeData.GetExchangeInfoAsync() you get this warning, I think it wasn't there before.  It's hard for me to give you my code, I had to delete many parts and not sure it works in this state, but something along those lines:

//////////////////
var resultStatus = await this.binanceClient.SpotApi.ExchangeData.GetExchangeInfoAsync();

foreach (var asset in resultStatus.Data.Symbols)
{
     var symbol = new BinanceSpotSymbols { Symbol = asset.Name, Status = asset.Status.ToString(), BaseAsset = asset.BaseAsset, QuoteAsset = asset.QuoteAsset };
}
//////////////////

It gives this warning for all symbols:

Warning | Cannot map enum value. EnumType: AccountType, Value: TRD_GRP_013, Known values: SPOT, MARGIN, FUTURES, LEVERAGED, TRD_GRP_002, TRD_GRP_003, TRD_GRP_004, TRD_GRP_005, TRD_GRP_006, TRD_GRP_007, TRD_GRP_008, TRD_GRP_009. If you think TRD_GRP_013 should added please open an issue on the Github repo

It doesn't seem to happen with margin and Futures Symbols.

Thank you!

**Comment by dj-jordan** [comment]
Yes, I am experiencing exactly the same issue 'missing enum TRD_GRP_013' on the Binance.Net libary (version 8.5.1)

**Replication**:  
                using (var client = new BinanceClient()) {
                    var exinfo = await client.SpotApi.ExchangeData.GetExchangeInfoAsync();
                   // code handlers
                }
  

**Debug Output shows**...
2023/06/22 03:49:45:652 | Information | Binance    | [6] Creating request for https://api.binance.com/api/v3/exchangeInfo

2023/06/22 03:49:45:662 | Warning | Cannot map enum value. EnumType: AccountType, Value: TRD_GRP_013, Known values: SPOT, MARGIN, FUTURES, LEVERAGED, TRD_GRP_002, TRD_GRP_003, TRD_GRP_004, TRD_GRP_005, TRD_GRP_006, TRD_GRP_007, TRD_GRP_008, TRD_GRP_009. If you think TRD_GRP_013 should added please open an issue on the Github repo

2023/06/22 03:49:45:662 | Warning | Cannot map enum value. EnumType: AccountType, Value: TRD_GRP_013, Known values: SPOT, MARGIN, FUTURES, LEVERAGED, TRD_GRP_002, TRD_GRP_003, TRD_GRP_004, TRD_GRP_005, TRD_GRP_006, TRD_GRP_007, TRD_GRP_008, TRD_GRP_009. If you think TRD_GRP_013 should added please open an issue on the Github repo

With the above Warning repeated 4250 times (presumably once for each symbol)

**Comment by ASolomatin** [comment]
Hi! There is not all of permissions listed in [documentation](https://binance-docs.github.io/apidocs/spot/en/#public-api-definitions) were into the [Binance.Net/Enums/AccountType.cs](https://github.com/JKorf/Binance.Net/pull/1265/files#diff-2e7be42c133b1fb47b2a25d26dd1a20eb9f634ac3a8edca1ec21ed1b34d1ee41)

**Comment by IM-001** [comment]
Thanks JKorf!  🙏
