### ISSUE TITLE
Convert Endpoints

### ISSUE THREAD

**Issue by kingchenc** [JKorf/Binance.Net#1264]
Heyy @JKorf ,

any chance that you add all the convert endpoints?
Its atm only available for users where submited and approved for the function.. 

https://binance-docs.github.io/apidocs/spot/en/#convert-endpoints

thanks

**Comment by Owdares** [comment]
Added convert endpoints 
#1322

**Comment by kingchenc** [comment]
i close this, because of @Owdares work <3
