### ISSUE TITLE
'Full' klines for UsdFuturesStreams.SubscribeToKlineUpdatesAsync arrive late

### ISSUE THREAD

**Issue by nkonstas** [JKorf/Binance.Net#1267]
This may or may not be an issue, but I noticed that stream updates for 'full' klines can arrive +24seconds late for a 5-min interval. Is that normal behaviour? 

I'm using Binance.NET 8.5.1

**Comment by JKorf** [comment]
I think it can take some time before the server actually sends the finished/full kline yes. But I'd guess that value would be somewhat similar for any interval

**Comment by nkonstas** [comment]
Thanks, I wasn't sure if there is an issue or not, I tried to check the Binance docs but I couldn't see any ref to latencies. Sometimes it arrives on time (almost zero latency) and other times way too late.
