### ISSUE TITLE
"closePosition" not found in Multiple Order!

### ISSUE THREAD

**Issue by emin-karadag** [JKorf/Binance.Net#1269]
Hello,
I am using Binance.Net 9.0.

When I added Stop Loss to manually close the open position on Binance and examined the order, I saw that the "closePosition" value was set to "true".

I used your library to place the same order via API and was able to create StopMarket type orders in the same way as Binance.

However, I cannot make and send the same order in multiple ways. **Because there is no "ClosePosition" value inside the "BinanceFuturesBatchOrder" class.**

Thanks.

**Comment by JKorf** [comment]
Hi, according to the docs that parameter isn't available:
https://binance-docs.github.io/apidocs/futures/en/#place-multiple-orders-trade
So unfortunately I can't add it then
