### ISSUE TITLE
Proposal: Specific errors for rate limits and option to customize RateLimitPerSocketPerSecond for spot socket API

### ISSUE THREAD

**Issue by ASolomatin** [JKorf/Binance.Net#1270]
Current RateLimitPerSocketPerSecond is too low and not configurable. To keep request rate on the edge in different scenarious including multithreaded, we need option to disable built in limit in 4 requests per second and possibiliti to handle responses about rate limits. 

I suggest to make specific error classes for this errors derived from RateLimitError which will contain Data with serverTime and retryAfter properties.

Docs: https://developers.binance.com/docs/binance-trading-api/websocket_api#ip-limits

**Comment by JKorf** [comment]
I've commented on your PR on the CryptoExchange.Net repo, please have a look as it has an impact on this one

**Comment by JKorf** [comment]
Hi, I've updated the package to have specific error for ratelimiting. Both the rest and the socket client should now return a ServerRatelimitError error object if they receive a status 419 or 428. I've updated the socket client to have the correct ratelimiting behavior
