### ISSUE TITLE
All of these converters can be replaced with static versions to improve performance

### ISSUE THREAD

**Issue by NoParamedic** [JKorf/Binance.Net#1275]
```cs
new TimeInForceConverter(false)
```

There are lots of requests that are calling `new` when they don't need to, which slows down the request.

https://github.com/JKorf/Binance.Net/blob/e3c98cbc7d03b663a5a3bd43b19ae16cc00291f1/Binance.Net/Clients/SpotApi/BinanceRestClientSpotApi.cs#L134

This is one example from `PlaceOrderInternal` but this is true for anywhere you see the converters **outside of an attribute** like below

```cs
new OrderSideConverter(false);
new SpotOrderTypeConverter(false);
new TimeInForceConverter(false);
new SideEffectTypeConverter(false);
new OrderResponseTypeConverter(false);
etc....
```

I solved this by creating a [static version of all these converters](https://github.com/NoParamedic/BinanceAPI.NET/blob/master/Binance-API/Binance-API/Converters/StaticConverters.cs)

I could do something similar and open a pull request if you want, let me know.

**Comment by NoParamedic** [comment]
For some requests the difference is significant for example in `PlaceOrderInternal` you are calling new up to `5` times for no reason

https://github.com/JKorf/Binance.Net/blob/e3c98cbc7d03b663a5a3bd43b19ae16cc00291f1/Binance.Net/Clients/SpotApi/BinanceRestClientSpotApi.cs#L127-L139

**Comment by NoParamedic** [comment]
Merging https://github.com/JKorf/Binance.Net/pull/1276 will fix and close this issue

**Comment by NoParamedic** [comment]
@JKorf

Is this project still active?

**Comment by JKorf** [comment]
Has been discussed in different places; if this is going to be changed it should be to the EnumConverter class

**Comment by NoParamedic** [comment]
Your enum converter class is so painfully slow that I literally can't believe you are trying to compare these
