### ISSUE TITLE
Detecting Spot TrailingStop Orders

### ISSUE THREAD

**Issue by Maddest** [JKorf/Binance.Net#1279]
Hi,
I'm working with trailing stops when placing spot orders. This works great.

However, is there a way to detect TrailingStop orders when getting the list of all open orders? Or even, the currently set value of the trailing delta?

Thanks and regards, Bernd

**Comment by JKorf** [comment]
Cleaning up old issues; I assume this is no longer relevant. If it is feel free to comment.
