### ISSUE TITLE
Timestamp for this request is outside of the recvWindow

### ISSUE THREAD

**Issue by avechuche** [JKorf/Binance.Net#128]
Hi, sometimes I get this message when I want to query the API or connect to the socket. I need to synchronize the time of my PC to work, is there any other more automatic solution? Thank you!

**Comment by Kudwig** [comment]
1. look on closed issues, it has been addressed.
2. update to latest version.

**Comment by avechuche** [comment]
@Kudwig Hi, thanks for the help. It is necessary, every time I get that error, I must do GetServerTime (resetAutoTimestamp: true)? Why do you save the result of GetServerTime? Should you pass it by parameter in some side? This option is mandatory too? AutoTimestamp = true

**Comment by JKorf** [comment]
When you set `AutoTimestamp` to `true` in the `BinanceClient` it will automatically synchronize the server time with your local computer time. That should prevent the error you're seeing. Other than setting that parameter to `true` you don't have to do anything else. If you still see the error even when enabling `AutoTimestamp` let me know.

**Comment by JKorf** [comment]
I assume you got this fixed. If not let me know.

**Comment by kingchenc** [comment]
@JKorf dont want create new issue, yesterday my log was full spammed of the 1021 error ( 3h was the error, and after the 3h the bug/issue was gone).. how can i prevent this bug/issue? i was only using userstream and a websocket for ticker, and my internet connection works 100%


2019.02.05 23:28:04:156 | Warning | Server returned an error: {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}
2019.02.05 23:28:04:592 | Warning | Server returned an error: {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}
2019.02.05 23:28:05:023 | Warning | Server returned an error: {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}
2019.02.05 23:28:05:442 | Warning | Server returned an error: {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}
2019.02.05 23:28:06:383 | Warning | Server returned an error: {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}
2019.02.05 23:28:07:024 | Info | Time offset within 1 seconds (255.4257ms), no adjustment needed
2019.02.05 23:28:07:274 | Warning | Server returned an error: {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}
2019.02.05 23:28:07:948 | Warning | Socket 1 message processing slow (1396ms), consider offloading data handling to another thread. Data from this socket may arrive late or not at all if message processing is continuously slow.
2019.02.05 23:28:08:686 | Warning | Server returned an error: {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}
2019.02.05 23:28:09:123 | Warning | Server returned an error: {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}
2019.02.05 23:28:10:026 | Warning | Server returned an error: {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}
2019.02.05 23:28:10:458 | Warning | Server returned an error: {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}
2019.02.05 23:29:51:599 | Warning | Server returned an error: {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}
2019.02.05 23:29:52:033 | Info | Time offset within 1 seconds (206.4122ms), no adjustment needed
2019.02.05 23:58:08:430 | Info | Time offset within 1 seconds (298.9179ms), no adjustment needed
2019.02.05 23:58:09:444 | Warning | Socket 1 message processing slow (807ms), consider offloading data handling to another thread. Data from this socket may arrive late or not at all if message processing is continuously slow.
2019.02.06 00:28:09:962 | Info | Time offset within 1 seconds (377.7157ms), no adjustment needed
2019.02.06 00:58:10:783 | Info | Time offset within 1 seconds (465.6516ms), no adjustment needed
2019.02.06 01:28:11:602 | Info | Time offset within 1 seconds (558.9821ms), no adjustment needed
2019.02.06 01:28:11:885 | Warning | Socket 1 message processing slow (582ms), consider offloading data handling to another thread. Data from this socket may arrive late or not at all if message processing is continuously slow.
2019.02.06 01:58:12:427 | Info | Time offset within 1 seconds (650.9316ms), no adjustment needed
2019.02.06 02:28:13:266 | Info | Time offset within 1 seconds (730.0969ms), no adjustment needed
2019.02.06 02:28:14:202 | Warning | Socket 1 message processing slow (1140ms), consider offloading data handling to another thread. Data from this socket may arrive late or not at all if message processing is continuously slow.
2019.02.06 02:58:14:776 | Info | Time offset within 1 seconds (806.4122ms), no adjustment needed
2019.02.06 02:58:15:081 | Warning | Socket 1 message processing slow (668ms), consider offloading data handling to another thread. Data from this socket may arrive late or not at all if message processing is continuously slow.
2019.02.06 03:28:15:595 | Info | Time offset within 1 seconds (891.4041ms), no adjustment needed
2019.02.06 03:58:16:497 | Info | Time offset within 1 seconds (979.6447ms), no adjustment needed
2019.02.06 04:28:17:364 | Info | Time offset set to -1064.2665ms

**Comment by matebort** [comment]
@JKorf in what place i had to active this autotimestamp?? Is in the private void Configure(BinanceClientOptions options)??

**Comment by lwx-sabir** [comment]
What about the socket client? It is giving the same error on placing the order and no options to set AutoTimestamp as in the RestClient.
