### ISSUE TITLE
Timestamp for this request was ahead of the server's time.

### ISSUE THREAD

**Issue by masherak** [JKorf/Binance.Net#1280]
Hello @JKorf , please, sometimes I get this response from Binance: {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."}.

Can I fix it by configuration in the "AddBinance" method? How? 

I read that Binance doesn't sync server time very often.

I think I need larger tolerance or set time offset somehow.

Thank you very much

**Comment by JKorf** [comment]
Hi, there are different solutions depending on what causes the issue. By default the library will try to sync you local time with the server time. This is controlled by the AutoTimestamp client option. You can try disabling this and instead increasing the ReceiveWindow client option. It is 5 seconds by default, but can be set up to 60 seconds. 

Best solution would be to make sure your local server time is regulary synced with a time server to make sure it's correct.

**Comment by masherak** [comment]
Thank you very much for your answer, so far I have set it up as you say: AutoTimestamp = false and ReceiveWindow = 60s. I will check if problem persist.

Have a nice weekend.
