### ISSUE TITLE
Proxy options not working in BinanceRestClient

### ISSUE THREAD

**Issue by Tendx** [JKorf/Binance.Net#1283]
**Describe the bug**
I updated Binance.Net and proxy options did not work. I checked the source, and found proxy config was removed from RequestFactory in v6.0 CryptoExchange.Net.

**Comment by AAA001001** [comment]
No some bug. Proxy is work. I was test it at Binance and Bybit.

**Comment by Tendx** [comment]
I use socks5 proxy

**Comment by JKorf** [comment]
Has been fixed
