### ISSUE TITLE
Array Converter is slow and can be replaced with simple converters that perform much better

### ISSUE THREAD

**Issue by NoParamedic** [JKorf/Binance.Net#1284]
The `Array Converter` can be replaced with simple converters that perform much better.

This is possible because you already have all the information for the type ahead of time and the order/offset doesn't change.

### Example Kline Converter (Spot)

```cs
/// <summary>
/// Binance Kline Converter
/// </summary>
public class BinanceKlineConverter : JsonConverter
{
    private const int EXPECTED_LENGTH_DESERIALIZE = 11; // Ignore has been trimmed away
    private const int EXPECTED_LENGTH_FULL = 12;

    private const int OPEN_TIME = 0;
    private const int OPEN = 1;
    private const int HIGH = 2;
    private const int LOW = 3;
    private const int CLOSE = 4;
    private const int BASE_VOLUME = 5;
    private const int CLOSE_TIME = 6;
    private const int QUOTE_VOLUME = 7;
    private const int TRADE_COUNT = 8;
    private const int TAKER_BUY_BASE_VOLUME = 9;
    private const int TAKER_BUY_QUOTE_VOLUME = 10;
    private const int TICKS_IN_MILLISECOND = 10000;

    /// <inheritdoc />
    public override object? ReadJson(JsonReader reader, Type objectType, object? existingValue, JsonSerializer serializer)
    {
        JArray jArray = JArray.Load(reader);

        if (jArray.Count == EXPECTED_LENGTH_FULL || jArray.Count == EXPECTED_LENGTH_DESERIALIZE)
        {
            BinanceKline bkCached = CachedType<BinanceKline>.Instance();

            bkCached.OpenTime = TimestampConverter.ReadTimeStamp((long)jArray[OPEN_TIME]) ?? DateTime.MinValue;
            bkCached.Open = (decimal)jArray[OPEN];
            bkCached.High = (decimal)jArray[HIGH];
            bkCached.Low = (decimal)jArray[LOW];
            bkCached.Close = (decimal)jArray[CLOSE];
            bkCached.BaseVolume = (decimal)jArray[BASE_VOLUME];
            bkCached.CloseTime = TimestampConverter.ReadTimeStamp((long)jArray[CLOSE_TIME]) ?? DateTime.MinValue;
            bkCached.QuoteVolume = (decimal)jArray[QUOTE_VOLUME];
            bkCached.TradeCount = (int)jArray[TRADE_COUNT];
            bkCached.TakerBuyBaseVolume = (decimal)jArray[TAKER_BUY_BASE_VOLUME];
            bkCached.TakerBuyQuoteVolume = (decimal)jArray[TAKER_BUY_QUOTE_VOLUME];

            return bkCached;
        }

        return new BinanceKline();
    }

    /// <inheritdoc />
    public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
    {
        if (value == null)
        {
            return;
        }

        if (value is BinanceKline binanceKline)
        {
            writer.WriteStartArray();

            writer.WriteValue(binanceKline.OpenTime.Ticks / TICKS_IN_MILLISECOND);

            writer.WriteValue(binanceKline.Open);

            writer.WriteValue(binanceKline.High);

            writer.WriteValue(binanceKline.Low);

            writer.WriteValue(binanceKline.Close);

            writer.WriteValue(binanceKline.BaseVolume);

            writer.WriteValue(binanceKline.CloseTime.Ticks / TICKS_IN_MILLISECOND);

            writer.WriteValue(binanceKline.QuoteVolume);

            writer.WriteValue(binanceKline.TradeCount);

            writer.WriteValue(binanceKline.TakerBuyBaseVolume);

            writer.WriteValue(binanceKline.TakerBuyQuoteVolume);

            writer.WriteEndArray();
        }
    }

    /// <inheritdoc />
    public override bool CanConvert(Type objectType)
    {
        return true;
    }
}
```

The `new expression` is cached, which is faster then calling `new()` by about 30% even for small objects and that is pretty consistent across all runtimes etc.

```cs
namespace BinanceAPI.Converters
{
    /// <summary>
    /// Cache the New Expression for a given type T
    /// </summary>
    /// <typeparam name="T"></typeparam>
    public static class CachedType<T> where T : new()
    {
        /// <summary>
        /// Instance of the New Expression for given type T
        /// </summary>
        public static readonly Func<T> Instance = Expression.Lambda<Func<T>>(Expression.New(typeof(T))).Compile();
    }
}
```

**Comment by NoParamedic** [comment]
> EXPECTED_LENGTH_FULL

This is the path taken by the converter, including `Ignore`

> EXPECTED_LENGTH_DESERIALIZE

The path taken when deserializing the object with `Ignore` removed

**Comment by NoParamedic** [comment]
You can also `Cache the new expressions` you have in the `ArrayConverter` instead of using `Activator.CreateInstance`

```cs
namespace BinanceAPI.Converters
{
    /// <summary>
    /// Cache the New Expression for a given type T
    /// </summary>
    /// <typeparam name="T"></typeparam>
    public static class CachedType<T> where T : new()
    {
        static CachedType()
        {
            CachedType<BinanceKline>.Instance();
        }

        /// <summary>
        /// Instance of the New Expression for given type T
        /// </summary>
        public static readonly Func<T> Instance = Expression.Lambda<Func<T>>(Expression.New(typeof(T))).Compile();
    }
}
```

```cs
/// <inheritdoc />
public override object? ReadJson(JsonReader reader, Type objectType, object? existingValue, JsonSerializer serializer)
{
    JArray jArray = JArray.Load(reader);

    if (jArray.Count == EXPECTED_LENGTH_FULL || jArray.Count == EXPECTED_LENGTH_DESERIALIZE)
    {
        BinanceKline bkCached = CachedType<BinanceKline>.Instance();

        bkCached.OpenTime = TimestampConverter.ReadTimeStamp((long)jArray[OPEN_TIME]) ?? DateTime.MinValue;
        bkCached.Open = (decimal)jArray[OPEN];
        bkCached.High = (decimal)jArray[HIGH];
        bkCached.Low = (decimal)jArray[LOW];
        bkCached.Close = (decimal)jArray[CLOSE];
        bkCached.BaseVolume = (decimal)jArray[BASE_VOLUME];
        bkCached.CloseTime = TimestampConverter.ReadTimeStamp((long)jArray[CLOSE_TIME]) ?? DateTime.MinValue;
        bkCached.QuoteVolume = (decimal)jArray[QUOTE_VOLUME];
        bkCached.TradeCount = (int)jArray[TRADE_COUNT];
        bkCached.TakerBuyBaseVolume = (decimal)jArray[TAKER_BUY_BASE_VOLUME];
        bkCached.TakerBuyQuoteVolume = (decimal)jArray[TAKER_BUY_QUOTE_VOLUME];

        return bkCached;
    }

    return new BinanceKline();
}
```

https://github.com/NoParamedic/BinanceAPI.NET/commit/a77f15ce9b9aa93401e77384bf68da61a2677523

**Comment by JKorf** [comment]
If you know the type, why would you need Activator.CreateInstance (and subsequently the CachedType helper)? Just using new BinanceKline() would be more straigtforward and faster.

**Comment by NoParamedic** [comment]
You could use the alternative method if you wanted (new)

Using `Activator` is faster than calling `new()`

Using a `cached type` is faster than both of them.

**Comment by NoParamedic** [comment]
```cs
BinanceKline bkCached = CachedType<BinanceKline>.Instance();
```

This is literally just a faster way of calling a `new()` expression, The expression tree is compiled and cached so its faster.

**Comment by NoParamedic** [comment]
```cs
BinanceKline bkCached = CachedType<BinanceKline>.Instance();
```

This is literally just a faster way of calling a `new()` expression, The expression tree is compiled and cached so its faster.

You can use this literally anywhere you call `new()` with a default constructor and you could even add params to it but its annoying.

**Comment by NoParamedic** [comment]
If you were wondering, Its about 30% faster.

**Comment by JKorf** [comment]
I'm sorry I fail to see how
`var model = CachedType<BinanceKline>.Instance();`
would be faster than
`var model = new BinanceKline()`

How did you test this?

**Comment by NoParamedic** [comment]
I'm not going to debate something you could literally google

**Comment by NoParamedic** [comment]
The expression tree is compiled and cached so its faster.

```cs
Expression.Lambda<Func<T>>(Expression.New(typeof(T))).Compile()
```

I literally explained already.

**Comment by NoParamedic** [comment]
This isn't something I just made up.

**Comment by JKorf** [comment]
Expression trees are not faster than directly calling a method:
https://learn.microsoft.com/en-us/dotnet/api/system.linq.expressions.expression.new?view=net-7.0#system-linq-expressions-expression-new(system-reflection-constructorinfo)
It says it creates an expression tree to call the constructor, so how would that be faster than just calling te constructor?

Compile just makes it so the tree doesn't need to be evaluated run time every time its called. Calling a method directly doesn't need to be evaluated run time either. 

So with this reasoning I fail to see how it would be faster, but I'm open to be proven wrong

**Comment by NoParamedic** [comment]
```cs
  public static class CachedType<T> where T : new()
```

Its cached.

**Comment by NoParamedic** [comment]
Compile only gets called once per type

**Comment by NoParamedic** [comment]
Why don't you test it.

**Comment by NoParamedic** [comment]
You are right if you were only going to call the method once in the lifetime of your application it would be slower but these are converters.

**Comment by NoParamedic** [comment]
You are right if you were only going to call the method once in the lifetime of your application it would be slower but these are converters.

But that said you could also just warm these up at start up by spamming `CachedType<BinanceKline>.Instance();` etc and then it is always faster.

**Comment by NoParamedic** [comment]
I think you may have missed that the class is `static` and called `: new()`

**Comment by NoParamedic** [comment]
I think you may have missed that the class is `static` and called `: new()` so each type only gets compiled once and then `Instance()` just gets it after the first time

**Comment by NoParamedic** [comment]
I think you may have missed that the class is `static` and called `: new()` so each type only gets compiled once and then `Instance()` just gets it after the first time, Since you are creating nothing it is obviously going to be faster.

You could also make some complicated cache class so you only call compile once for each type but this is far simpler

**Comment by NoParamedic** [comment]
```cs
CachedType<ClientWebSocket>.Instance();
CachedType<AsyncResetEvent>.Instance();
CachedType<MemoryStream>.Instance();
CachedType<BinanceKline>.Instance();
CachedType<List<PendingRequest>>.Instance();
CachedType<ConcurrentQueue<JToken>>.Instance();
```

I do this at start up of the first client so its always faster, you are correct that using `Compile` directly instead of `new()` is wrong.

**Comment by NoParamedic** [comment]
Activator1 = new();
Activator2 = Activator.CreateInstance<T>();
Activator3 = CachedType<T>.Instance();

```cs
// * Summary *

BenchmarkDotNet=v0.13.2, OS=Windows 11 (10.0.22000.1098/21H2)
Intel Core i9-10900KF CPU 3.70GHz, 1 CPU, 20 logical and 10 physical cores
.NET SDK=6.0.402
  [Host]   : .NET 6.0.10 (6.0.1022.47605), X64 RyuJIT AVX2
  .NET 6.0 : .NET 6.0.10 (6.0.1022.47605), X64 RyuJIT AVX2

Job=.NET 6.0  Runtime=.NET 6.0  

|         Method |         x |           Mean |         Error |        StdDev | Ratio | RatioSD |        Gen0 |     Allocated | Alloc Ratio |
|--------------- |---------- |---------------:|--------------:|--------------:|------:|--------:|------------:|--------------:|------------:|
| ActivatorTest1 |      1000 |       9.946 μs |     0.1927 μs |     0.2142 μs |  1.00 |    0.00 |      3.8147 |      39.06 KB |        1.00 |
| ActivatorTest2 |      1000 |       9.808 μs |     0.0721 μs |     0.0674 μs |  0.98 |    0.02 |      3.8147 |      39.06 KB |        1.00 |
| ActivatorTest3 |      1000 |       6.219 μs |     0.1199 μs |     0.1427 μs |  0.63 |    0.02 |      3.8223 |      39.06 KB |        1.00 |
|                |           |                |               |               |       |         |             |               |             |
| ActivatorTest1 |   1000000 |   9,834.625 μs |    31.8609 μs |    26.6053 μs |  1.00 |    0.00 |   3812.5000 |   39063.26 KB |        1.00 |
| ActivatorTest2 |   1000000 |  10,671.712 μs |    47.0675 μs |    44.0269 μs |  1.09 |    0.01 |   3812.5000 |   39063.26 KB |        1.00 |
| ActivatorTest3 |   1000000 |   6,295.779 μs |   121.9964 μs |   186.3014 μs |  0.65 |    0.03 |   3820.3125 |    39062.5 KB |        1.00 |
|                |           |                |               |               |       |         |             |               |             |
| ActivatorTest1 | 100000000 | 995,902.729 μs | 7,355.4492 μs | 6,520.4141 μs |  1.00 |    0.00 | 382000.0000 | 3906325.27 KB |        1.00 |
| ActivatorTest2 | 100000000 | 982,209.783 μs | 6,630.1000 μs | 5,176.3460 μs |  0.99 |    0.01 | 382000.0000 | 3906335.95 KB |        1.00 |
| ActivatorTest3 | 100000000 | 618,402.807 μs | 4,305.6817 μs | 4,027.5373 μs |  0.62 |    0.01 | 382000.0000 | 3906253.48 KB |        1.00 |
```

**Comment by NoParamedic** [comment]
```cs
  public static class CachedType<T> where T : new()
```

I think you may have missed that the class is `static` and called `: new()` so each type only gets compiled once and then `Instance()` just gets it after the first time, Since you are creating nothing it is obviously going to be faster.

You could also make some complicated cache class so you only call compile once for each type but this is far simpler

```cs
CachedType<ClientWebSocket>.Instance();
CachedType<AsyncResetEvent>.Instance();
CachedType<MemoryStream>.Instance();
CachedType<BinanceKline>.Instance();
CachedType<List<PendingRequest>>.Instance();
CachedType<ConcurrentQueue<JToken>>.Instance();
```

I do this at start up of the first client so its always faster, you are correct that using `Compile` directly instead of `new()` is wrong.

----

`ActivatorTest1` = new();
`ActivatorTest2` = Activator.CreateInstance<T>();
`ActivatorTest3` = CachedType<T>.Instance();

```cs
// * Summary *

BenchmarkDotNet=v0.13.2, OS=Windows 11 (10.0.22000.1098/21H2)
Intel Core i9-10900KF CPU 3.70GHz, 1 CPU, 20 logical and 10 physical cores
.NET SDK=6.0.402
  [Host]   : .NET 6.0.10 (6.0.1022.47605), X64 RyuJIT AVX2
  .NET 6.0 : .NET 6.0.10 (6.0.1022.47605), X64 RyuJIT AVX2

Job=.NET 6.0  Runtime=.NET 6.0  

|         Method |         x |           Mean |         Error |        StdDev | Ratio | RatioSD |        Gen0 |     Allocated | Alloc Ratio |
|--------------- |---------- |---------------:|--------------:|--------------:|------:|--------:|------------:|--------------:|------------:|
| ActivatorTest1 |      1000 |       9.946 μs |     0.1927 μs |     0.2142 μs |  1.00 |    0.00 |      3.8147 |      39.06 KB |        1.00 |
| ActivatorTest2 |      1000 |       9.808 μs |     0.0721 μs |     0.0674 μs |  0.98 |    0.02 |      3.8147 |      39.06 KB |        1.00 |
| ActivatorTest3 |      1000 |       6.219 μs |     0.1199 μs |     0.1427 μs |  0.63 |    0.02 |      3.8223 |      39.06 KB |        1.00 |
|                |           |                |               |               |       |         |             |               |             |
| ActivatorTest1 |   1000000 |   9,834.625 μs |    31.8609 μs |    26.6053 μs |  1.00 |    0.00 |   3812.5000 |   39063.26 KB |        1.00 |
| ActivatorTest2 |   1000000 |  10,671.712 μs |    47.0675 μs |    44.0269 μs |  1.09 |    0.01 |   3812.5000 |   39063.26 KB |        1.00 |
| ActivatorTest3 |   1000000 |   6,295.779 μs |   121.9964 μs |   186.3014 μs |  0.65 |    0.03 |   3820.3125 |    39062.5 KB |        1.00 |
|                |           |                |               |               |       |         |             |               |             |
| ActivatorTest1 | 100000000 | 995,902.729 μs | 7,355.4492 μs | 6,520.4141 μs |  1.00 |    0.00 | 382000.0000 | 3906325.27 KB |        1.00 |
| ActivatorTest2 | 100000000 | 982,209.783 μs | 6,630.1000 μs | 5,176.3460 μs |  0.99 |    0.01 | 382000.0000 | 3906335.95 KB |        1.00 |
| ActivatorTest3 | 100000000 | 618,402.807 μs | 4,305.6817 μs | 4,027.5373 μs |  0.62 |    0.01 | 382000.0000 | 3906253.48 KB |        1.00 |
```

**Comment by JKorf** [comment]
Right, maybe I missunderstood. You're not creating anything new, just the first time it's called. However then couldn't you just replace 
`public static readonly Func<T> Instance = Expression.Lambda<Func<T>>(Expression.New(typeof(T))).Compile();`
with
`public static readonly T Instance = new T();`?

What threw me off initially was the example with the BinanceKline model. With `BinanceKline bkCached = CachedType<BinanceKline>.Instance();` in the sample code you're not creating a new object, you're  returning the same instance you used before. This can lead to issues with threading depending on your use case. If you have 2 methods using that functionality at the same time they will both return the same BinanceKline object instance and thus 1 of the 2 will have incorrect property values.

**Comment by NoParamedic** [comment]
Look, I'm going to be perfectly straight with you, I am new to this concept myself and I found this by just google "Fast replacement for Activator.GetInstance"

[fast-creation-of-objects-instead-of-activator](https://stackoverflow.com/questions/6582259/fast-creation-of-objects-instead-of-activator-createinstancetype/16162809#16162809)

> replace
public static readonly Func<T> Instance = Expression.Lambda<Func<T>>(Expression.New(typeof(T))).Compile();
with
public static readonly T Instance = new T();?

Sounds good to me?

> This can lead to issues with threading depending on your use case. 

No I think you are wrong here, The expression is run every time it is only compiled once.

**Comment by NoParamedic** [comment]
Your second point must be wrong or my trading app would have already blew up and thrown a million exceptions.

**Comment by NoParamedic** [comment]
I am using `CachedType<MemoryStream>.Instance();` if your second point was correct then I would die to an exception almost immediately.

**Comment by NoParamedic** [comment]
I am using CachedType<MemoryStream>.Instance() and have about 10 sockets subscribed right now.

if your second point was correct then I would die to an exception almost immediately.

**Comment by NoParamedic** [comment]
I am using `CachedType<MemoryStream>.Instance()` and have about 10 sockets subscribed right now.

if your second point was correct then I would die to an exception almost immediately.

**Comment by NoParamedic** [comment]
I am using `CachedType<MemoryStream>.Instance()` inside my socket implementation and have about 10 sockets subscribed right now.

if your second point was correct then I would die to an exception almost immediately.

**Comment by NoParamedic** [comment]
I'm already using this concept very heavily and have had no issues with threading

1. https://github.com/NoParamedic/BinanceAPI.NET
2. https://github.com/NoParamedic/INFINITY

**Comment by NoParamedic** [comment]
Please also note that `Instance()` is invoked.

**Comment by NoParamedic** [comment]
Please also note that `Instance()` is invoked, the compiled expression is executed.

This is not the same thing as `.Instance`

**Comment by NoParamedic** [comment]
Please also note that `Instance()` is invoked, the compiled expression is executed.

This is not the same thing as `.Instance`

Easy to miss the nuance.

**Comment by NoParamedic** [comment]
To put it simply, this is the same as calling `new()` its just slightly faster

**Comment by NoParamedic** [comment]
Please also note that `Instance()` is invoked, the compiled expression is executed every time.

This is not the same thing as `.Instance`, which would do what you said.

Easy to miss the nuance.

To put it simply, this is the same as calling `new()` its just slightly faster (after the first time)

**Comment by NoParamedic** [comment]
Please also note that `Instance()` is invoked, the compiled expression is executed every time.

This is not the same thing as `.Instance`, which would do what you said and could be replaced by `new T();`

Easy to miss the nuance, very easy to use it wrong.

To put it simply, this is the same as calling `new()` its just slightly faster (after the first time)

**Comment by NoParamedic** [comment]
You are right if you used it like this there would be threading issues

```cs
var neverDoThis = CachedType<ConcurrentQueue<JToken>>.Instance;
```

You should always invoke `Instance()`

```cs
var alwaysDoThis = CachedType<ConcurrentQueue<JToken>>.Instance();
```

**Comment by JKorf** [comment]
So here's where am at then:
Situation 1: The same instance is returned every time
This is what you want for Converter types, but not what you want for the model or stream types
Situation 2: A new instance is returned every time (which is what happens since you're not experiencing exception in your application)
This what you want for the models and stream types, but not for the converter types.

Also this is my benchmark for using cached type vs just new(), which shows no improvement as I suspected
```
BenchmarkDotNet v0.13.6, Windows 10 (10.0.19045.3208/22H2/2022Update)
Intel Core i7-6600U CPU 2.60GHz (Skylake), 1 CPU, 4 logical and 2 physical cores
.NET SDK 7.0.202
  [Host]     : .NET 6.0.15 (6.0.1523.11507), X64 RyuJIT AVX2 [AttachedDebugger]
  DefaultJob : .NET 6.0.15 (6.0.1523.11507), X64 RyuJIT AVX2


|          Method |     N |      Mean |     Error |    StdDev |    Median |
|---------------- |------ |----------:|----------:|----------:|----------:|
|         UseCtor |  1000 |  4.515 ns | 0.1685 ns | 0.1576 ns |  4.480 ns |
|    UseActivator |  1000 | 14.728 ns | 0.3051 ns | 0.2705 ns | 14.712 ns |
| UseCompiledExpr |  1000 |  4.163 ns | 0.1684 ns | 0.4408 ns |  3.979 ns |
|         UseCtor | 10000 |  4.243 ns | 0.1626 ns | 0.3501 ns |  4.187 ns |
|    UseActivator | 10000 | 14.824 ns | 0.3592 ns | 0.4137 ns | 14.761 ns |
| UseCompiledExpr | 10000 |  4.745 ns | 0.1717 ns | 0.3097 ns |  4.634 ns |
```

**Comment by NoParamedic** [comment]
Interesting results, `Activator` is even worse than I expected on your hardware, and the difference between the other choices is much smaller than I expected.

I think your results are more a testament to the `i7` than anything, but I can see how you came to the conclusion that it isn't better.

**Comment by NoParamedic** [comment]
I just realized you ran that benchmark with a debugging attached

You are such a piece of shit.

**Comment by NoParamedic** [comment]
You ran your benchmark with a debugger attached lmao.

This library is deliberately slow and the developer is malicious.
