### ISSUE TITLE
Missing optional `cancelRestrictions` for `DELETE /api/v3/order`

### ISSUE THREAD

**Issue by XHighIntell** [JKorf/Binance.Net#1286]
**Describe the bug**
https://binance-docs.github.io/apidocs/spot/en/#cancel-order-trade

Supported values:
ONLY_NEW - Cancel will succeed if the order status is NEW.
ONLY_PARTIALLY_FILLED - Cancel will succeed if order status is PARTIALLY_FILLED.

**Comment by JKorf** [comment]
Added in latest version
