### ISSUE TITLE
Getting all the messages to the log

### ISSUE THREAD

**Issue by AndyWinner** [JKorf/Binance.Net#1288]
Hi! First of all, thank you for your excellent project.

My question is about logging. 

I have my own created log writer, which is implementing ILogger interface, to show messages in UI and write them to the file as well. Log writer used in one instance per app session. 

LoggerProvider is wrapping a log writer:

`public class FileLoggerProvider : ILoggerProvider
    {        
        private LogWriter writer;

        public FileLoggerProvider(LogWriter writer)
        {
            this.writer = writer;
        }
        
        public ILogger CreateLogger(string categoryName) => this.writer;

        public void Dispose()
        {
            
        }
    }
`

In the code it looks like:

`this.fileLoggerProvider = new FileLoggerProvider(this.writer);
            var serviceCollection = new ServiceCollection();
            serviceCollection
                .AddBinance(a => a = binanceClientOptions, a => a = binanceSocketClientOptions)
                .AddLogging(options =>
                {
                    options.SetMinimumLevel(logLevel);
                    options.AddProvider(this.fileLoggerProvider);                    
                });
            MainForm.serviceProvider = serviceCollection.BuildServiceProvider();
`

After that I'm creating a rest or socket clients like:

`this.RestClient = MainForm.serviceProvider.GetRequiredService<IBinanceRestClient>();            
this.SocketClient = MainForm.serviceProvider.GetRequiredService<IBinanceSocketClient>();            
`
            
By the way, is serviceCollection should be saved to stored variable? Now I'm using it as temp variable, and its whole life-time has shown in the code part above.

Also I have noticed that BinanceOrderBookFactory class is using chosen logger as well, via _serviceProvider, so logging should be comprehensive and ok.

So, I want to be ensure that I'm getting all the messages to the log, like warning, error etc, about everything that is happening in the runtime, as it was in previous versions before your large update. Log verbosity is Information. Is it enough code to achieve this goal?

Best regards.

**Comment by JKorf** [comment]
Cleaning up old issues; I assume this is no longer relevant. If it is feel free to comment and I'll take another look.
