### ISSUE TITLE
 BinanceFutures >> GetAccountInfoAsync Timeout ERROR

### ISSUE THREAD

**Issue by hcanak** [JKorf/Binance.Net#1290]
Hello,

I am facing a connection issue for last 2-3 weeks. Let me describe;

1. While my application is running, all spot and futures price mini tickers stop streaming suddenly
2. Streaming starts again in 5-10 minutes spontaneously
3. When i restart my application all endpoints works except for  "BinanceFutures >> GetAccountInfoAsync", this gives timeout error.
4. In 5-10 minutes timeout issue fixes spontaneously, and everything runs properly.

All above i told are observed in my vps which is in Contabo-Singapore region. 
While observing above issues on my vps, i try to run the sam app in my PC; in my pc everything runs properly:d
(My pc's intenet connection is 100mbps and 1000ms ping to binance server)

I completely closed firewall on my vps, and it has 200mbps internet speed while facing issue.

Do you have any suggestion for this issue? Thanks already for your interest...

**Comment by JKorf** [comment]
Cleaning up old issues; I assume this is no longer relevant. If it is feel free to comment and I'll take another look.
