### ISSUE TITLE
Error in Margin Call Event

### ISSUE THREAD

**Issue by hcanak** [JKorf/Binance.Net#1293]
Hello,

Firstly, i am using this great library for more than 1 year, it works excellent, I would like to thank everyone who contributed this library.

I want to share my problem. Today i received Margin Call event when risk ratio reaches %80. onMarginUpdate action is triggered as expected but the parameter of this received event was NULL (DataEvent_BinanceFuturesStreamMarginUpdate_ == null).

Can you check the related pieces of code? Thanks in advance.

**Comment by JKorf** [comment]
Hi,

I've identified the problem, will be fixed in the next version. Thanks for the report!

**Comment by JKorf** [comment]
Fixed in latest version
