### ISSUE TITLE
ExchangeInfo - Cannot map enum value - TRD_GRP_014

### ISSUE THREAD

**Issue by dvpot** [JKorf/Binance.Net#1295]
**To Reproduce**
var resultInfo = await client.SpotApi.ExchangeData.GetExchangeInfoAsync("DOTBUSD");

**Debug logging**
2023.08.26 11:51:55:485 | Information | Binance | [36] Creating request for https://api.binance.com/api/v3/exchangeInfo
2023.08.26 11:51:55:921 | Debug | Binance | [36] Response received in 432ms
2023.08.26 11:51:55:924 | Warning | Cannot map enum value. EnumType: AccountType, Value: TRD_GRP_014, Known values: SPOT, MARGIN, FUTURES, LEVERAGED, TRD_GRP_002, TRD_GRP_003, TRD_GRP_004, TRD_GRP_005, TRD_GRP_006, TRD_GRP_007, TRD_GRP_008, TRD_GRP_009, TRD_GRP_010, TRD_GRP_011, TRD_GRP_012, TRD_GRP_013. If you think TRD_GRP_014 should added please open an issue on the Github repo

**Comment by JKorf** [comment]
Fixed in latest version
