### ISSUE TITLE
Problem getting started with Binance.Net

### ISSUE THREAD

**Issue by colingresty** [JKorf/Binance.Net#13]
Hi, Thanks for this package! just what i need, but i'm getting the following error as soon as i try and use the client:

CS0012	The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.

i have updated to VS 2017 and downloaded .NET Core 2.0 but still get the same error. Im not a C# expert so forgive me if this is a trivial issue.
Thanks from a grateful user.

**Comment by JKorf** [comment]
Hi, what version of the .Net framework do you use? You can find this by right clicking on your project, selecting Properties and it will tell you under Target Framework.

**Comment by colingresty** [comment]
Hi, ive tried 4.5.1 4.5.2 and 4.5 - all give the same error.
Thanks

**Comment by JKorf** [comment]
Is it possible for you to start using 4.6.1? The Binance.Net package is targeting .NetStandard 2.0, which sadly means .Net framework versions older than 4.6.1 are not supported, sorry!

**Comment by colingresty** [comment]
Hi, i just tried 4.6.1 and again got the exact same error. Here is how little is in the test project and im getting the error. :

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using Binance.Net;

namespace CP4
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private void button1_Click(object sender, EventArgs e)
        {
            using (var client = new BinanceClient())
            {
            }
        }
    }
}

**Comment by JKorf** [comment]
Hm, that's weird. When I create a new .net 4.6.1 console project and add Binance.Net via the package manager it works. So I'm guessing it is something to do with your develop environment, although I'm not sure what it is..

**Comment by JKorf** [comment]
Can you try to run your code in a separate Task?

**Comment by colingresty** [comment]
Im sorry, i dont know what that means - im not a c# expert :)

**Comment by colingresty** [comment]
in a separate thread?

**Comment by colingresty** [comment]
so i can now compile and run the extremely simple project, but i get no response, it just seems to run and do nothing. It can't be this hard?

**Comment by colingresty** [comment]
Hi, final comment before i give up on this.
everything in the example below compiles with no errors, textBox2.Text never gets populated.

(if i use c# WebClient Class i can talk to Binance exchange happily to get prices etc. so its not AV , Firewall etc)

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using System.Windows.Forms;
using Binance.Net;

namespace CP4
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private void button1_Click(object sender, EventArgs e)
        {
                using (var client = new BinanceClient())
                {
                textBox1.Text = "Before";
                var ping = client.Ping();
                textBox2.Text = "After";
                }

        }


    }



}

**Comment by colingresty** [comment]
I guess i have to give up then.
Thats a shame, because this would have saved me a lot of hassle, but i just cant make the simplest use of  Binance.Net work.
Thanks for trying anyway.

**Comment by JKorf** [comment]
The call hangs because you're trying to do an async await request from the UI thread, which probably isn't the best idea. If you use a seperate task for this as I suggested earlier it should work: 
````
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using System.Windows.Forms;
using Binance.Net;

namespace CP4
{
    public partial class Form1 : Form
    {
    public Form1()
    {
        InitializeComponent();
    }

    private void button1_Click(object sender, EventArgs e)
    {
        Task.Run(() =>
            {
                using (var client = new BinanceClient())
                {
                    var result = client.Get24HPrice("ETHBTC");
                    if (result.Success)
                    {
                        Invoke(new MethodInvoker(() =>
                        {
                            textBox1.Text = "ETH price: " + result.Data.LastPrice;
                        }));
                    }
                }
            });
    }
  }
}
````
Note that the `Invoke(new MethodInvoker() =>` is required because you update the UI from a different thread.

On another note, I've fixed some things in the latest version, if you download version 2.2.3 it should work with the code you had (no additional Task needed).

**Comment by colingresty** [comment]
Hi, Using a separate thread works :)
Thanks for your help (and patience)
