### ISSUE TITLE
Cant get exchangeInfo please help immediately!!!

### ISSUE THREAD

**Issue by basarkavas** [JKorf/Binance.Net#1301]
**Describe the bug**

when i call this code from binance.net  

 public static string URLPROD = "https://api.binance.com";
public static string URLPROD_FAPI = "https://fapi.binance.com";

var exchangeInfo = await client.FuturesUsdt.System.GetExchangeInfoAsync();
            List<string> pairList = exchangeInfo.Data.Symbols.Select(x => x.Pair).ToList<string>();
            return pairList;

**exchangeinfo data is null!!!**

you can see the debug window below
![image](https://github.com/JKorf/Binance.Net/assets/6178844/185ca250-fdf3-422f-93e8-8f49f97d4f51)

**Comment by JKorf** [comment]
I'm not sure if you're aware of this but your style of communication here is quite annoying. Why do you require help "immediately"? Also the 7 '!' don't help. 

That being said, I just tried the call and it works fine for me. Are you on the latest version of the library?

**Comment by basarkavas** [comment]
Hi Jan,
I am very sorry about my english, my tradebot was not working because of
this error, maybe i could be exited about problem,
bu it was working about 1 year without any problem, why it is not
working now, i couldnt understand,
my api url is right?
can you check detailed please,
thanks for advance.

**Comment by JKorf** [comment]
Alright, no worries. The API urls seem correct. Your problem is probably fixed when you update the library to the latest version. When Binance update their API there is a chance the client library needs an update as well. Which is why older versions of the library might stop working suddenly. 
Let me know if you still have issues after updating to the latest version

**Comment by basarkavas** [comment]
hi again jan,
this my solution, i am sorry but i dont know how can i update the library,
i think i am using source code not library, so how can i update it?
thanks in advance
[image: image.png]

**Comment by basarkavas** [comment]
and Jan,
my main question is
https://jkorf.github.io/CryptoExchange.Net/Migration%20Guide.html
when i read this documentation there is a code for binance client create:

var client = new BinanceClient(options => {
    options.OutputOriginalData = true;
    options.Environment = BinanceEnvironment.Testnet;
    // Other options});


BUT there is no BinanceClient class in binance.net project,
this is the main point for upgrade,
thank you very much

**Comment by basarkavas** [comment]
Hi Jan again,

i think i got progress on code, but i couldnt find for replacement code for

*old client code:*
var client = new BinanceClient(new BinanceClientOptions()
            {
                // Specify options for the client

                ApiCredentials = new ApiCredentials(apiKey, secretKey),
                BaseAddress = url,
                BaseAddressUsdtFutures = fapiURL
}

*new client code:*

*var *client = new BinanceRestClient();
            BinanceRestClient.SetDefaultOptions(options =>
            {
                options.ApiCredentials = new ApiCredentials(apiKey,
secretKey); // <- Provide you API key/secret in these fields to retrieve
data related to your account
            });

THE QUESTION IS HOW CAN I SET these values, because i want to use both
production and test urls, for testing and real trading.
BaseAddress
BaseAddressUsdtFutures

thanks in advance

**Comment by francnuec** [comment]
Hi @JKorf,

I am having the same issue with the same error. I am unable to get exchange info using the same code above.

I am using the latest Binance.Net version: 10.16.2
