### ISSUE TITLE
ExchangeInfo - Cannot map enum value. EnumType: AccountType, Value: TRD_GRP_016 ... TRD_GRP_020

### ISSUE THREAD

**Issue by kordenv** [JKorf/Binance.Net#1304]
Hello,

library version 9.1.2 literally an hour ago stopped working and gives warnings (and doesn't work)

var result = await this.client.SpotApi.SpotApi.ExchangeData.GetExchangeInfoAsync();

and here are the warnings in the console

2023.09.22 17:24:30:597 | Warning | Cannot map enum value. EnumType: AccountType, Value: TRD_GRP_016, Known values: SPOT, MARGIN, FUTURES, LEVERAGED, TRD_GRP_002, TRD_GRP_003, TRD_GRP_004, TRD_GRP_005, TRD_GRP_006, TRD_GRP_007, TRD_GRP_008, TRD_GRP_009, TRD_GRP_010, TRD_GRP_011, TRD_GRP_012, TRD_GRP_013, TRD_GRP_014, TRD_GRP_015. If you think TRD_GRP_016 should added please open an issue on the Github repo
2023.09.22 17:24:30:606 | Warning | Cannot map enum value. EnumType: AccountType, Value: TRD_GRP_017, Known values: SPOT, MARGIN, FUTURES, LEVERAGED, TRD_GRP_002, TRD_GRP_003, TRD_GRP_004, TRD_GRP_005, TRD_GRP_006, TRD_GRP_007, TRD_GRP_008, TRD_GRP_009, TRD_GRP_010, TRD_GRP_011, TRD_GRP_012, TRD_GRP_013, TRD_GRP_014, TRD_GRP_015. If you think TRD_GRP_017 should added please open an issue on the Github repo
2023.09.22 17:24:30:609 | Warning | Cannot map enum value. EnumType: AccountType, Value: TRD_GRP_018, Known values: SPOT, MARGIN, FUTURES, LEVERAGED, TRD_GRP_002, TRD_GRP_003, TRD_GRP_004, TRD_GRP_005, TRD_GRP_006, TRD_GRP_007, TRD_GRP_008, TRD_GRP_009, TRD_GRP_010, TRD_GRP_011, TRD_GRP_012, TRD_GRP_013, TRD_GRP_014, TRD_GRP_015. If you think TRD_GRP_018 should added please open an issue on the Github repo
2023.09.22 17:24:30:612 | Warning | Cannot map enum value. EnumType: AccountType, Value: TRD_GRP_019, Known values: SPOT, MARGIN, FUTURES, LEVERAGED, TRD_GRP_002, TRD_GRP_003, TRD_GRP_004, TRD_GRP_005, TRD_GRP_006, TRD_GRP_007, TRD_GRP_008, TRD_GRP_009, TRD_GRP_010, TRD_GRP_011, TRD_GRP_012, TRD_GRP_013, TRD_GRP_014, TRD_GRP_015. If you think TRD_GRP_019 should added please open an issue on the Github repo
2023.09.22 17:24:30:614 | Warning | Cannot map enum value. EnumType: AccountType, Value: TRD_GRP_020, Known values: SPOT, MARGIN, FUTURES, LEVERAGED, TRD_GRP_002, TRD_GRP_003, TRD_GRP_004, TRD_GRP_005, TRD_GRP_006, TRD_GRP_007, TRD_GRP_008, TRD_GRP_009, TRD_GRP_010, TRD_GRP_011, TRD_GRP_012, TRD_GRP_013, TRD_GRP_014, TRD_GRP_015. If you think TRD_GRP_020 should added please open an issue on the Github repo

thank you in advance for your help

**Comment by kordenv** [comment]
More warrnings were added today

2023.09.23 14:24:39:843 | Warning | Cannot map enum value. EnumType: AccountType, Value: TRD_GRP_016, Known values: SPOT, MARGIN, FUTURES, LEVERAGED, TRD_GRP_002, TRD_GRP_003, TRD_GRP_004, TRD_GRP_005, TRD_GRP_006, TRD_GRP_007, TRD_GRP_008, TRD_GRP_009, TRD_GRP_010, TRD_GRP_011, TRD_GRP_012, TRD_GRP_013, TRD_GRP_014, TRD_GRP_015. If you think TRD_GRP_016 should added please open an issue on the Github repo
2023.09.23 14:24:39:845 | Warning | Cannot map enum value. EnumType: AccountType, Value: TRD_GRP_017, Known values: SPOT, MARGIN, FUTURES, LEVERAGED, TRD_GRP_002, TRD_GRP_003, TRD_GRP_004, TRD_GRP_005, TRD_GRP_006, TRD_GRP_007, TRD_GRP_008, TRD_GRP_009, TRD_GRP_010, TRD_GRP_011, TRD_GRP_012, TRD_GRP_013, TRD_GRP_014, TRD_GRP_015. If you think TRD_GRP_017 should added please open an issue on the Github repo
2023.09.23 14:24:39:848 | Warning | Cannot map enum value. EnumType: AccountType, Value: TRD_GRP_018, Known values: SPOT, MARGIN, FUTURES, LEVERAGED, TRD_GRP_002, TRD_GRP_003, TRD_GRP_004, TRD_GRP_005, TRD_GRP_006, TRD_GRP_007, TRD_GRP_008, TRD_GRP_009, TRD_GRP_010, TRD_GRP_011, TRD_GRP_012, TRD_GRP_013, TRD_GRP_014, TRD_GRP_015. If you think TRD_GRP_018 should added please open an issue on the Github repo
2023.09.23 14:24:39:850 | Warning | Cannot map enum value. EnumType: AccountType, Value: TRD_GRP_019, Known values: SPOT, MARGIN, FUTURES, LEVERAGED, TRD_GRP_002, TRD_GRP_003, TRD_GRP_004, TRD_GRP_005, TRD_GRP_006, TRD_GRP_007, TRD_GRP_008, TRD_GRP_009, TRD_GRP_010, TRD_GRP_011, TRD_GRP_012, TRD_GRP_013, TRD_GRP_014, TRD_GRP_015. If you think TRD_GRP_019 should added please open an issue on the Github repo
2023.09.23 14:24:39:852 | Warning | Cannot map enum value. EnumType: AccountType, Value: TRD_GRP_020, Known values: SPOT, MARGIN, FUTURES, LEVERAGED, TRD_GRP_002, TRD_GRP_003, TRD_GRP_004, TRD_GRP_005, TRD_GRP_006, TRD_GRP_007, TRD_GRP_008, TRD_GRP_009, TRD_GRP_010, TRD_GRP_011, TRD_GRP_012, TRD_GRP_013, TRD_GRP_014, TRD_GRP_015. If you think TRD_GRP_020 should added please open an issue on the Github repo
2023.09.23 14:24:39:855 | Warning | Cannot map enum value. EnumType: AccountType, Value: TRD_GRP_021, Known values: SPOT, MARGIN, FUTURES, LEVERAGED, TRD_GRP_002, TRD_GRP_003, TRD_GRP_004, TRD_GRP_005, TRD_GRP_006, TRD_GRP_007, TRD_GRP_008, TRD_GRP_009, TRD_GRP_010, TRD_GRP_011, TRD_GRP_012, TRD_GRP_013, TRD_GRP_014, TRD_GRP_015. If you think TRD_GRP_021 should added please open an issue on the Github repo
2023.09.23 14:24:39:857 | Warning | Cannot map enum value. EnumType: AccountType, Value: TRD_GRP_022, Known values: SPOT, MARGIN, FUTURES, LEVERAGED, TRD_GRP_002, TRD_GRP_003, TRD_GRP_004, TRD_GRP_005, TRD_GRP_006, TRD_GRP_007, TRD_GRP_008, TRD_GRP_009, TRD_GRP_010, TRD_GRP_011, TRD_GRP_012, TRD_GRP_013, TRD_GRP_014, TRD_GRP_015. If you think TRD_GRP_022 should added please open an issue on the Github repo
2023.09.23 14:24:39:860 | Warning | Cannot map enum value. EnumType: AccountType, Value: TRD_GRP_023, Known values: SPOT, MARGIN, FUTURES, LEVERAGED, TRD_GRP_002, TRD_GRP_003, TRD_GRP_004, TRD_GRP_005, TRD_GRP_006, TRD_GRP_007, TRD_GRP_008, TRD_GRP_009, TRD_GRP_010, TRD_GRP_011, TRD_GRP_012, TRD_GRP_013, TRD_GRP_014, TRD_GRP_015. If you think TRD_GRP_023 should added please open an issue on the Github repo

i.e. 21 22 and 23 more warnings were added.

Is there a way to prevent these warnings from appearing every time? If they appear every time, then every time I have to create a problem here? This is inconvenient, and the application in debugging mode is terribly slow and the request takes a minute to complete.

Where did these warnings even come from? Did Binance add or change something?

**Comment by JKorf** [comment]
I'll have a look to see if I can prevent new values for this specific enum causing warnings. The warnings are generated in the client, and it happens when a new enum value is returned from the server which can't be mapped to an existing enum value. 
In this case Binance keeps adding more can more trade groups to the enum causing this warning to appear

**Comment by kordenv** [comment]
Aha, thanks, it's very inconvenient that the debug is clogged, and Binance can add new values every day, which will be inconvenient for everyone ))

Thanks again)

**Comment by IM-001** [comment]
Came here to report this as well.  Thank you!!  Indeed, Binance just keeps adding more and more categories without warning in here.

**Comment by JKorf** [comment]
Has been fixed in version 9.1.3. I also added that new enum values for this specific enum won't generate new warnings!

**Comment by kordenv** [comment]
Thank you very much )

**Comment by richardu** [comment]
I'm getting this issue with value UNKNOWN_1 but this value doesn't come from Binance. Any idea what's going on?

Thanks,
Richard
