### ISSUE TITLE
Incorrect URl for flexible product positions list

### ISSUE THREAD

**Issue by headshote** [JKorf/Binance.Net#1305]
https://github.com/JKorf/Binance.Net/blob/3cb3db58404533e4c4a0183204f8dd5ca70175b0/Binance.Net/Clients/GeneralApi/BinanceRestClientGeneralApiSavings.cs#L27C5-L27C5

According to https://binance-docs.github.io/apidocs/spot/en/#get-flexible-product-position-user_data the endpoint should be "/sapi/v1/simple-earn/flexible/position"

A bunch of other flexible earn product endpoints are incorrect as well, they all are under "simple-earn/flexible", like:
simple-earn/flexible/subscribe 
simple-earn/flexible/redeem 
etc.

NOT under "lending/daily/" which was removed according to https://binance-docs.github.io/apidocs/spot/en/#change-log:
2023-06-22
    New endpoints for Simple Earn.
    Delete endpoint for Lending:
        GET /sapi/v1/lending/daily/product/list
        GET /sapi/v1/lending/daily/userLeftQuota
        POST /sapi/v1/lending/daily/purchase
        GET /sapi/v1/lending/daily/userRedemptionQuota
        POST /sapi/v1/lending/daily/redeem
        GET /sapi/v1/lending/daily/token/position
        GET /sapi/v1/lending/union/account
        GET /sapi/v1/lending/union/purchaseRecord
        GET /sapi/v1/lending/union/redemptionRecord
        GET /sapi/v1/lending/union/interestHistory

Would have been nice to have a way to override these urls in my code, because your wrapper lib is very convenient otherwise, but resorting to reflection to fix some strings isn't nice :(.

**Comment by JozefGula** [comment]
I have the same problem with this endpoint. Binance returns this error:

Message: "This endpoint has been deprecated, please remove as soon as possible.", Code: "405"
