### ISSUE TITLE
Future grid bot

### ISSUE THREAD

**Issue by michcan52** [JKorf/Binance.Net#1308]
Hi everyone!

My question is if there is a way to get the information about a grid bot for futures?
I would love to get all the information on how the bots are doing within my application. is this possible?

Thanks!

**Comment by panoskj** [comment]
I have tried to do this but couldn't find an API for it. Instead, I logged in the web version, found the bot trade history page and then found the request made to retrieve it. I then modified the parameters of the request to get all data at once (the web page displays just 10 trades at a time).

I didn't try to use the undocumented API outside of their web page, so I don't know if it would work with the API tokens. I was thinking of a simple web browser extension script to give me the list would be instead.

**Comment by JKorf** [comment]
I don't think there is an official way to retrieve this data via the API
