### ISSUE TITLE
Uncaught exception when reconnecting in 3.2.4

### ISSUE THREAD

**Issue by NektoDron** [JKorf/Binance.Net#131]
I think this is like issue in the Bitfinex library. May be it has been fixed in the 3.2.5 version?

21:53:17.47[90]DEBUG:[Binance] API: 2018/09/14 21:53:17:473 | Error | Socket error Не удается прочитать данные из транспортного соединения: Попытка установить соединение была безуспешной, т.к. от другого компьютера за требуемое время не получен нужный отклик, или было разорвано уже установленное соединение из-за неверного отклика уже подключенного компьютера.
21:53:17.47[90]DEBUG:[Binance] API: 2018/09/14 21:53:17:473 | Info | Connection lost, going to try to reconnect
21:53:32.23[47]DEBUG:[Binance] API: 2018/09/14 21:53:32:230 | Info | Connection lost, going to try to reconnect
21:53:33.87[827]DEBUG:[Binance] API: 2018/09/14 21:53:33:875 | Info | Connection lost, going to try to reconnect
21:53:34.87[82]DEBUG:[Binance] API: 2018/09/14 21:53:34:874 | Info | Connection lost, going to try to reconnect
21:53:35.87[109]DEBUG:[Binance] API: 2018/09/14 21:53:35:874 | Info | Connection lost, going to try to reconnect
21:53:36.87[275]DEBUG:[Binance] API: 2018/09/14 21:53:36:875 | Info | Connection lost, going to try to reconnect
21:53:37.38[2]FATAL:UnobservedTaskException: AggregateException:
AggregateException:
Exception:The socket is connecting, cannot connect again!:   в SuperSocket.ClientEngine.TcpClientSession.Connect(EndPoint remoteEndPoint)
   в CryptoExchange.Net.Implementation.BaseSocket.<Connect>b__37_0()
   в System.Threading.Tasks.Task`1.InnerInvoke()
   в System.Threading.Tasks.Task.Execute()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   в CryptoExchange.Net.Implementation.BaseSocket.<Connect>d__37.MoveNext()

21:53:37.87[47]DEBUG:[Binance] API: 2018/09/14 21:53:37:875 | Info | Connection lost, going to try to reconnect
21:53:38.87[25]DEBUG:[Binance] API: 2018/09/14 21:53:38:874 | Info | Connection lost, going to try to reconnect
21:53:39.87[77]DEBUG:[Binance] API: 2018/09/14 21:53:39:875 | Info | Connection lost, going to try to reconnect
21:53:40.82[70]INFO :38:Info:Notification::Ping
21:54:37.05[2]FATAL:UnobservedTaskException: AggregateException:
AggregateException:
Exception:The socket is connecting, cannot connect again!:   в SuperSocket.ClientEngine.TcpClientSession.Connect(EndPoint remoteEndPoint)
   в CryptoExchange.Net.Implementation.BaseSocket.<Connect>b__37_0()
   в System.Threading.Tasks.Task`1.InnerInvoke()
   в System.Threading.Tasks.Task.Execute()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   в CryptoExchange.Net.Implementation.BaseSocket.<Connect>d__37.MoveNext()

21:54:38.06[2]FATAL:UnobservedTaskException: AggregateException:
AggregateException:
Exception:The socket is connecting, cannot connect again!:   в SuperSocket.ClientEngine.TcpClientSession.Connect(EndPoint remoteEndPoint)
   в CryptoExchange.Net.Implementation.BaseSocket.<Connect>b__37_0()
   в System.Threading.Tasks.Task`1.InnerInvoke()
   в System.Threading.Tasks.Task.Execute()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   в CryptoExchange.Net.Implementation.BaseSocket.<Connect>d__37.MoveNext()

21:54:39.40[2]FATAL:UnobservedTaskException: AggregateException:
AggregateException:
Exception:The socket is connecting, cannot connect again!:   в SuperSocket.ClientEngine.TcpClientSession.Connect(EndPoint remoteEndPoint)
   в CryptoExchange.Net.Implementation.BaseSocket.<Connect>b__37_0()
   в System.Threading.Tasks.Task`1.InnerInvoke()
   в System.Threading.Tasks.Task.Execute()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   в CryptoExchange.Net.Implementation.BaseSocket.<Connect>d__37.MoveNext()

21:54:40.18[2]FATAL:UnobservedTaskException: AggregateException:
AggregateException:
Exception:The socket is connecting, cannot connect again!:   в SuperSocket.ClientEngine.TcpClientSession.Connect(EndPoint remoteEndPoint)
   в CryptoExchange.Net.Implementation.BaseSocket.<Connect>b__37_0()
   в System.Threading.Tasks.Task`1.InnerInvoke()
   в System.Threading.Tasks.Task.Execute()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   в CryptoExchange.Net.Implementation.BaseSocket.<Connect>d__37.MoveNext()

21:54:40.82[109]INFO :38:Info:Notification::Ping
21:54:44.27[2]FATAL:UnobservedTaskException: AggregateException:
AggregateException:
Exception:The socket is connecting, cannot connect again!:   в SuperSocket.ClientEngine.TcpClientSession.Connect(EndPoint remoteEndPoint)
   в CryptoExchange.Net.Implementation.BaseSocket.<Connect>b__37_0()
   в System.Threading.Tasks.Task`1.InnerInvoke()
   в System.Threading.Tasks.Task.Execute()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   в CryptoExchange.Net.Implementation.BaseSocket.<Connect>d__37.MoveNext()

21:54:44.83[2]FATAL:UnobservedTaskException: AggregateException:
AggregateException:
Exception:The socket is connecting, cannot connect again!:   в SuperSocket.ClientEngine.TcpClientSession.Connect(EndPoint remoteEndPoint)
   в CryptoExchange.Net.Implementation.BaseSocket.<Connect>b__37_0()
   в System.Threading.Tasks.Task`1.InnerInvoke()
   в System.Threading.Tasks.Task.Execute()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   в CryptoExchange.Net.Implementation.BaseSocket.<Connect>d__37.MoveNext()

21:54:45.35[2]FATAL:UnobservedTaskException: AggregateException:
AggregateException:
Exception:The socket is connecting, cannot connect again!:   в SuperSocket.ClientEngine.TcpClientSession.Connect(EndPoint remoteEndPoint)
   в CryptoExchange.Net.Implementation.BaseSocket.<Connect>b__37_0()
   в System.Threading.Tasks.Task`1.InnerInvoke()
   в System.Threading.Tasks.Task.Execute()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   в CryptoExchange.Net.Implementation.BaseSocket.<Connect>d__37.MoveNext()

**Comment by JKorf** [comment]
Hi, this wasn't fixed in 3.2.5, but I just pushed 3.2.6 which should be available in a few minutes which should fix this. Let me know if you still have issues.

**Comment by NektoDron** [comment]
I've look to the code of BinanceSocketClient. The problem is in the Socket_OnClose method at 559 line. I think the Connect method can be called from another point when reconnection is started. Could you wrap it by try/catch?

**Comment by NektoDron** [comment]
I can't enable full logging because the issue happens once per 2-3 days and it will be big size of log. But I saw it in  the debugger.

**Comment by JKorf** [comment]
Hi, this should be fixed in the latest version 3.2.8 which should be available in a few minutes. Let me know if you still have problems
