### ISSUE TITLE
UsdFuturesApi.Trading.GetOpenOrdersAsync cant get openorders

### ISSUE THREAD

**Issue by basarkavas** [JKorf/Binance.Net#1311]
Hi,
I am using new restclient like below code, but cant return open orders.
public Binance.Net.Clients.BinanceRestClient client;
//create client here with options
client = new BinanceRestClient();
BinanceRestClient.SetDefaultOptions(options =>
{
    options.ApiCredentials = new ApiCredentials(apiKey, secretKey); // <- Provide you API key/secret in these fields to retrieve data related to your account                
    if (ENVIRONMENT.Contains("TEST"))
    {
        options.Environment = BinanceEnvironment.Testnet;
    }
    else if (ENVIRONMENT.Contains("PROD"))
    {
        options.Environment = BinanceEnvironment.Live;
    }

});
//important part here !!
var resultGetPositionInformationAsync = await client.UsdFuturesApi.Trading.GetOpenOrdersAsync(symbol);

//cant get result from this code, everything works then this part, i can get limit orders but i cant get openorders??

thx for help

**Comment by JKorf** [comment]
You're setting the default options after the client has already been created. Either set the default options before that or specify them for the specific client:
```csharp
BinanceRestClient.SetDefaultOptions(options =>{
  // Set options
});
var client = new BinanceRestClient();

// OR

var client = new BinanceRestClient(options => {
  // Set options
});
```

**Comment by basarkavas** [comment]
hi jkorf,

i have set options right, i can call all other functions, just there is a problem with this function, i cant get open order(current open position) from this function, it can get just limit orders.
thnks in advance.

**Comment by JKorf** [comment]
What is the value of `resultGetPositionInformationAsync.Error`?

**Comment by basarkavas** [comment]
there is no data in data property, but i have open position, but it is not limit position, just real open position, pls try for your account, call this function and you cant see your current open position from your function call result.
thnkx

**Comment by JKorf** [comment]
I didn't ask for the data property though. If you call `var resultGetPositionInformationAsync = await client.UsdFuturesApi.Trading.GetOpenOrdersAsync(symbol);` then either `resultGetPositionInformationAsync.Data` or `resultGetPositionInformationAsync.Error` will be filled.

I'm not currently able to try the call

**Comment by alaky2** [comment]
Hi basarkavas,
I think you want open "Positions" not "Orders". You need to use UsdFuturesApi.Account.GetPositionInformationAsync(Symbol). The UsdFuturesApi.Account.GetAccountInfoAsync also has a "Positions" property in response but it returns available coins (about 300). The UsdFuturesApi.Trading.GetOpenOrdersAsync(symbol) gives only open Orders not positions.

**Comment by basarkavas** [comment]
Thanks, I'll check it out.

**Comment by basarkavas** [comment]
yeah, ı have already tried this, but for the old version, getopernorders return also open positions, now i have to change to code like you said.
thx

**Comment by Steffx115** [comment]
You need to set UsdFuturesOptions.ApiCredentials separated from the standard ones
