### ISSUE TITLE
BinanceRestClient Isolated Allocated Margin

### ISSUE THREAD

**Issue by alaky2** [JKorf/Binance.Net#1312]
Hi,
There is no way to know the current Isolated "allocated margin" to an open position. The UsdFuturesApi.Account.ModifyPositionMarginAsync response has "Amount" property that is the amount of added or reduced amount to the allocated margin. How can we have the current allocated marging in Isolated Futures Position? Please see the picture.
![AllocatedMargin](https://github.com/JKorf/Binance.Net/assets/81215502/d598fc9c-72f3-4af1-9869-0af68fc8f4b4)

**Comment by JKorf** [comment]
Has been added, see #1314
