### ISSUE TITLE
Binance Futures PositionInfo/AccountInfo missing "isolatedWallet" field

### ISSUE THREAD

**Issue by ItsXor** [JKorf/Binance.Net#1314]
Hi.

Seems like classes with position information are missing a critical field that is used for isolated futures positions: "isolatedWallet"

My tests show that it returns exact margin amount allocated to isolated position (same as shown in binance app/web interfaces).

There are two functions for getting position info:
1. BinanceRestClient.UsdFuturesApi.Account.GetPositionInformationAsync() 
    Returns BinancePositionDetailsUsdt and it lacks "isolatedWallet"
    Docs: [https://binance-docs.github.io/apidocs/futures/en/#position-information-v2-user_data](https://binance-docs.github.io/apidocs/futures/en/#position-information-v2-user_data)

2. BinanceRestClient.UsdFuturesApi.Account.GetAccountInfoAsync() 
    Returns BinanceFuturesAccountInfo and Positions Field of type BinancePositionInfoUsdt lacks "isolatedWallet" too
    Docs: [https://binance-docs.github.io/apidocs/futures/en/#account-information-v2-user_data](https://binance-docs.github.io/apidocs/futures/en/#account-information-v2-user_data)
    Strangely docs don't show that AccountInfo will return positions with "isolatedWallet", but if you look at actual JSON data returned by server, this field is present.
    
I am not sure if it is appropriate to include undocumented field that is returned for positions in AccountInfo, but PositionsInfo documentation includes it and I see it as the only option to get currently allocated margin for isolated position.

Also resolving this issue will solve Issue [https://github.com/JKorf/Binance.Net/issues/1312](https://github.com/JKorf/Binance.Net/issues/1312)

Big thanks.

**Comment by JKorf** [comment]
Added it in the latest version
