### ISSUE TITLE
How can I get out of the loop?

### ISSUE THREAD

**Issue by HoLyDreaM** [JKorf/Binance.Net#1316]
Hello,
I can enter the function below and it returns the data according to the parameter I give, but what I want is something like this; After completing the operations, I want it to leave this area and return to the beginning within a while loop, but I could not do it.

var subscription = await socketClient.SpotApi.ExchangeData.SubscribeToKlineUpdatesAsync(SymBolName, Binance.Net.Enums.KlineInterval.OneMinute, async data =>
{

}

**Comment by JKorf** [comment]
Not an issue with the library

**Comment by HoLyDreaM** [comment]
I'm not saying it's a problem with the library. Once it gets into this loop, it doesn't come out. Is there any way to do this?
