### ISSUE TITLE
Bug in GetOpenInterestAsync 

### ISSUE THREAD

**Issue by hcanak** [JKorf/Binance.Net#1318]
Hello,

When you call **GetOpenInterestAsync** too frequently it gives error -1003 as expected. When this error occurs;

Error.Message is _"Server rate limit exceeded: {"code":-1003,"msg":"Too many requests; current limit of IP(194.233.xxxxx) is 2400 requests per minute. Please use the websocket for live updates to avoid polling the API."}"_

Error.Code is "_429_"

It seems that fails to correctly parse the json string. Can you check? @JKorf

**Comment by hcanak** [comment]
Above issue is also seen in **GetKlinesAsync** 
When  you call GetKlinesAsync too freguently Error.Message is _Server rate limit exceeded: {"code":-1003,"msg":"Too many requests; current limit of IP(194.233.****) is 2400 requests per minute. Please use the websocket for live updates to avoid polling_ the API."}

**Comment by JKorf** [comment]
Has been fixed
