### ISSUE TITLE
Bug in GetExchangeInfoAsync due to Binance backend changes?

### ISSUE THREAD

**Issue by FandangoOnCore** [JKorf/Binance.Net#1321]
**Describe the bug**

Hi @JKorf, the last 4 days, every time I'm calling the function BinanceSocketClient.SpotApi.ExchangeData.GetExchangeInfoAsync() I get the following  JSON deserialization exception:

"Deserialize JsonSerializationException: Error setting value to 'Type' on 'Binance.Net.Objects.Models.BinanceRateLimit'. "

IMHO the problem is Binance sending a new kind of rateLimitType ("CONNECTIONS") that cannot be mapped into a member of the enumerated type RateLimitType (as the only members are, at the moment, REQUESTED_WEIGHT, ORDERS and RAW_REQUESTS).

**Debug logging**

"Deserialize JsonSerializationException: Error setting value to 'Type' on 'Binance.Net.Objects.Models.BinanceRateLimit'. "
...
{
        "rateLimitType": "CONNECTIONS",   <--- this
        "interval": "MINUTE",
        "intervalNum": 5,
        "limit": 300
}

**Comment by JKorf** [comment]
Fixed in the latest version
