### ISSUE TITLE
ExchangeInfo - Cannot map enum value - TRD_GRP_024

### ISSUE THREAD

**Issue by Balint1** [JKorf/Binance.Net#1326]
**Describe the bug**
Cannot map AccountType  TRD_GRP_024

**To Reproduce**
var resultInfo = await client.SpotApi.ExchangeData.GetExchangeInfoAsync();

**Expected behavior**
Succesfully mapping the missing enum value

**Comment by HoLyDreaM** [comment]
I've been getting this error for 12 hours and I'm about to go crazy and sometimes it gives an error like this: "No response on query received"

**Comment by JKorf** [comment]
I'm not sure where you got that snippet from, it's not actually in the EnumConverter. The source of which can be found here:
https://github.com/JKorf/CryptoExchange.Net/blob/master/CryptoExchange.Net/Converters/EnumConverter.cs

**Comment by HoLyDreaM** [comment]
The code gives the error above.At least I didn't get it from somewhere

**Comment by AlgoExecutor** [comment]
> I'm not sure where you got that snippet from, it's not actually in the EnumConverter. The source of which can be found here: https://github.com/JKorf/CryptoExchange.Net/blob/master/CryptoExchange.Net/Converters/EnumConverter.cs

This was only my fix for the EnumConverter.cs Problem in Line 124.
