### ISSUE TITLE
IS THERE ANYWAY FOR TAKE_PROFIT_MARKET ORDER TYPE FOR FUTURESAPI

### ISSUE THREAD

**Issue by basarkavas** [JKorf/Binance.Net#1327]
I NEED TO SET A BUY ORDER WITH TAKEPROFIT PRICE
FOR EXAMPLE:
CURRENT PRICE 38000
LIMIT ORDER PRICE 37000
LIMIT ORDER TAKE PROFIT PRICE:37500 STOPLOSSPRICE:35000
CAN I DO THAT WITH

UsdFuturesApi.Trading.PlaceOrderAsync
                                        ("BTCUSDT" OrderSide.Buy, FuturesOrderType.TakeProfit, 

thanks

**Comment by JKorf** [comment]
Take profit / stop loss triggers need to be set after the position has been opened
