### ISSUE TITLE
Missing parameter "autoRepayAtCancel" in methods for creating new margin orders on Binance

### ISSUE THREAD

**Issue by cartoonle** [JKorf/Binance.Net#1329]
Hi!

It seems that parameter "autoRepayAtCancel" is missing in methods PlaceMarginOrderAsync(...) and PlaceMarginOCOOrderAsync(...). - Binance.Net/Binance.Net/Clients/SpotApi/BinanceRestClientSpotApiTrading.cs

https://binance-docs.github.io/apidocs/spot/en/#margin-account-new-order-trade
https://binance-docs.github.io/apidocs/spot/en/#margin-account-new-oco-trade

This is very important feature and it would be great if you could add it.

Kind regards,
Gregor

**Comment by JKorf** [comment]
I've added it in the latest version

**Comment by cartoonle** [comment]
It seems that parameter "autoRepayAtCancel" was only added in method PlaceMarginOrderAsync(...) but it's still missing in **PlaceMarginOCOOrderAsync**(...).

Kind regards,
Gregor

**Comment by JKorf** [comment]
Ah, missed that. Added in the latest version
