### ISSUE TITLE
Get24HPrice return wrong decimal

### ISSUE THREAD

**Issue by Shipolia** [JKorf/Binance.Net#133]
Hello,

Get24HPrice and other functions return me a wrong decimal if the coin have less then 8 decimal.

Example 
var getprices = client.Get24HPrice(getcoin);
BCCBTC -> Last Price: 0.069492 on Binance, the function return me 0.06949200

what im missing? thx

**Comment by JKorf** [comment]
I'm not sure what the problem is? 0.069492 == 0.06949200

**Comment by Shipolia** [comment]
Yes,  0.069492 == 0.06949200 is the same, but decimals not correct. 6 is not 8

if i want automatic buy/sell with last decimal increment 1, then this not work, because a 6 decimal coin can not have 8 decimal.

0.069492 + last decimal 1 increment = 0.069493 - this is right
0.06949200 + last decimal 1 increment = 0.06949201  - this buy/sell not working

**Comment by JKorf** [comment]
I see the problem. It's not really a problem in the library. The library simply returns what the Binance server returns. If you want know with what price you can increase/decrease at a minimum for a symbol have a look at the `GetExchangeInfo` method. It returns filters for each symbol. The `BinanceSymbolPriceFilter` will contain a `TickSize` property which is the value you're looking for.

**Comment by Shipolia** [comment]
Perfect, the TickSize is what i needed, thank you :)

**Comment by Steffx115** [comment]
Where is the GetExchangeInfo Method located? Cant find it unfortunately.
