### ISSUE TITLE
`/fapi/v1/fundingRate` API missed markPrice

### ISSUE THREAD

**Issue by XHighIntell** [JKorf/Binance.Net#1333]
**Describe the bug**
`UsdFuturesApi.ExchangeData.GetFundingRatesAsync` return `Binance.Net.Objects.Models.Futures.BinanceFuturesFundingRateHistory` missed markPrice

https://fapi.binance.com/fapi/v1/fundingRate?symbol=BTCUSDT
Read more: https://binance-docs.github.io/apidocs/futures/en/#get-funding-rate-history

**Comment by JKorf** [comment]
Added in the latest version
