### ISSUE TITLE
`Binance.Net.Objects.Models.Futures.BinanceFuturesOrder` Incorrect json map

### ISSUE THREAD

**Issue by XHighIntell** [JKorf/Binance.Net#1334]
**Describe the bug**
1. Places an new limit order at future (quantity = 0.004), wait for order to be `FILLED`
2. Get order by using `UsdFuturesApi.Trading.GetOrderAsync(symbol, orderId)`
3. Result is QuantityFilled is zero

![image](https://github.com/JKorf/Binance.Net/assets/15198165/11d554ab-8e81-47a4-8be6-8e1f7221b304)

Here is raw response from /fapi/v1/order?symbol=BTCUSDT&orderid=123
![image](https://github.com/JKorf/Binance.Net/assets/15198165/1285081d-0f4c-4287-8084-02d3c4b31b8a)

![image](https://github.com/JKorf/Binance.Net/assets/15198165/2ee93c3b-42fe-4f5f-b20c-0a34c447782e)

You maped `cumQty` to `QuantityFilled`. cumQty does not exist in response.
You maped `executedQty` to `LastFilledQuantity` that should be `QuantityFilled`

**Comment by dante1989** [comment]
Thank you. How about Coin-m Future? the same problem?

**Comment by XHighIntell** [comment]
@dante1989 I don't use Coin-M Future, I can't send real request right now.

Look at the document, Coin-M Future has some fields that are different.
https://binance-docs.github.io/apidocs/delivery/en/#query-order-user_data

Looks like `cumQty` does not exist either.
So Yes, the same problem for `QuantityFilled`

**Comment by JKorf** [comment]
Hm seems to mapped incorrectly yes. Not sure where that originates from. I'll have a look

**Comment by JKorf** [comment]
I've corrected the model(s), should be working correct now. Let me know if you have any issues

**Comment by dante1989** [comment]
For Example:
Dim ItemOrderBinance_USD As WebCallResult(Of BinanceUsdFuturesOrder)
ItemOrderBinance_USD = Await clientFutureBinance.UsdFuturesApi.Trading.GetOpenOrderAsync(Symbol, , ClientOrderId)

How could I make new ItemOrderBinance (class BinanceFuturesOrder) by converting from Class BinanceUsdFuturesOrder
Because, i want to combine BinanceUsdFuturesOrder and BinanceFuturesOrder Like Old Version
