### ISSUE TITLE
Error <WebCallResult<BinanceFuturesPlacedOrder> not found (Binance.Net 9.40)

### ISSUE THREAD

**Issue by eXcroll** [JKorf/Binance.Net#1337]
Hi, thanks for this library, I've been using it for a very long time, with the latest update I can't figure out how to call **<WebCallResult<BinanceFuturesPlacedOrder>>**. I upgraded from version 9.17 to version 9.40 and an error appeared at this point in the code:

        static async Task<WebCallResult<BinanceFuturesPlacedOrder>> PlaceSellOrder(string symb, decimal quantity)
        {
            var sellClient = new BinanceRestClient(options =>
            {
                options.ApiCredentials = new ApiCredentials(API_KEY, API_SECRET);
                options.UsdFuturesOptions.ApiCredentials = new ApiCredentials(API_KEY, API_SECRET);
                options.AutoTimestamp = true;
                options.UsdFuturesOptions.AutoTimestamp = true;
            });

            return await sellClient.UsdFuturesApi.Trading.PlaceOrderAsync(
                symb,
                OrderSide.Sell,
                FuturesOrderType.Market,
                quantity: quantity,
                newClientOrderId: lastOrderId.ToString()
            );

        }

**CS0246
The type or namespace name "BinanceFuturesPlacedOrder" could not be found (are you missing a using directive or an assembly reference?)**

I tried to find a replacement for this callback, but there was no such thing in the new version of the library...

**Comment by JKorf** [comment]
Hi, the response type of the PlaceOrderAsync method has changed. Previously it was WebCallResult<BinanceFuturesPlacedOrder>, now it is just WebCallResult<BinanceFuturesOrder>. The model itself still looks the same
