### ISSUE TITLE
Enum missing values: EXPIRED_IN_MATCH / TRADE_PREVENTION

### ISSUE THREAD

**Issue by paulquinn** [JKorf/Binance.Net#1339]
**Describe the bug**
I'm placing a spot order and getting:
1) a "Cannot map enum value" for TRADE_PREVENTION for Binance.Net.Enums.ExecutionType
2) a "Cannot map enum value" for EXPIRED_IN_MATCH despite the error message saying it's one of the permitted values

**To Reproduce**
SpotApi.Trading.PlaceOrderAsync

**Expected behavior**
Enums are mapped correctly

**Debug logging**

2024/01/30 22:21:15:050 | Warning | Cannot map enum value. EnumType: Binance.Net.Enums.ExecutionType, Value: TRADE_PREVENTION, Known values: NEW, CANCELED, REPLACED, REJECTED, TRADE, EXPIRED, AMENDMENT. If you think TRADE_PREVENTION should added please open an issue on the Github repo
2024/01/30 22:21:15:056 | Warning | Cannot map enum value. EnumType: Binance.Net.Enums.OrderStatus, Value: EXPIRED_IN_MATCH, Known values: NEW, PARTIALLY_FILLED, FILLED, CANCELED, PENDING_CANCEL, REJECTED, NEW_INSURANCE, NEW_ADL, EXPIRED, EXPIRED_IN_MATCH . If you think EXPIRED_IN_MATCH should added please open an issue on the Github repo

**Comment by JKorf** [comment]
Fixed in latest version
