### ISSUE TITLE
Buy with decimal

### ISSUE THREAD

**Issue by avechuche** [JKorf/Binance.Net#134]
Hi, I have a question. If I want to buy ADA, the web does not allow entering decimal numbers, but if I want to buy ETH, it does allow them. It is possible, through the API, which currency allows to buy with decimals? Thx!

**Comment by JKorf** [comment]
Yup, have a look at the result of the `GetExchangeState` call. It contains a list with symbol information. This information also contains a list of filters per symbol which you can use to check what is the valid input. The `BinanceSymbolPriceFilter` has a property `TickSize` which is the smallest price deviation you can use, and the `BinanceSymbolLotSizeFilter` has a property `StepSize` which is the smallest amount steps you can use.

**Comment by avechuche** [comment]
Perfect, thanks!

**Comment by binhtt6** [comment]
So it mean that min order for btc is 0.01 ?
![image](https://user-images.githubusercontent.com/30441291/59319954-b9e2c200-8cf6-11e9-803c-21bedab929fe.png)

**Comment by JKorf** [comment]
Hi, no it means the price you want to buy/sell it should be increments of 0.01. for the min amount you can check the lotsize filter.
