### ISSUE TITLE
Binance RestClient: Error "You are not authorized to execute this request." when calling ConvertQuoteRequestAsync

### ISSUE THREAD

**Issue by jaggyma** [JKorf/Binance.Net#1343]
**Bug**
I am using the BinanceRestClient. The SpotApi.Trading.PlaceOrderAsync works well but when using SpotApi.Trading.ConvertQuoteRequestAsync I get the Error "-1002: You are not authorized to execute this request." even though all permissions are set in the API.

**To Reproduce**
Call SpotApi.Trading.ConvertQuoteRequestAsync("Symbol1", "Symbol2", 0.01m, null, WalletType.Spot, null, null, default)

**Expected behavior**
Get a successful result.

**Comment by andresdrb** [comment]
That’s not a big. You have to explicitly request access to the convert API https://developers.binance.com/docs/convert/Introduction#:~:text=Would%20you%20like%20to%20have,we%20have%20approved%20your%20application.
