### ISSUE TITLE
BinanceSocketClient Orderbook explained

### ISSUE THREAD

**Issue by dungtrandk** [JKorf/Binance.Net#1348]
I am using the class BinanceSocketClient and IBinanceSocketClientUsdFuturesApi to get the orderbook updates on for instance btcusdt. I call the method SubscribeToOrderBookUpdatesAsync with the pair and 500 update interval.

Then in the handling of the data I get the Asks and Bids by: data.Data.Asks and data.Data.Bids.
In these lists I get bids/asks with price and quantities.

My question is, what do those price and quantities represent?

Is it the actual limit orders on the orderbook at that specific time?
Or is it limit orders added to the orderbook so its an accumulated value?
Or is it something else?

**Comment by JKorf** [comment]
It's aggregated orders per price level
