### ISSUE TITLE
Timestamp for this request is outside of the recvWindow

### ISSUE THREAD

**Issue by ndphuong** [JKorf/Binance.Net#135]
What does this mean ?
`Timestamp for this request is outside of the recvWindow`
And how to avoid it

Note that, I'm using proxy to consumer API

Thanks

**Comment by avechuche** [comment]
Hi! Check this https://github.com/JKorf/Binance.Net/issues/128

**Comment by ndphuong** [comment]
hi, does #128 work with Proxy ?

**Comment by JKorf** [comment]
It should, though I haven't tested it. Just try it and see if it works.
