### ISSUE TITLE
"SubscribeToUserDataUpdatesAsync" stop working after 9.5.0

### ISSUE THREAD

**Issue by hcanak** [JKorf/Binance.Net#1350]
Hello,

After updating to 9.5.0 **SubscribeToUserDataUpdatesAsync** endpoint seem to be not working. Below is ss of debug enviroment where you can see details.

![image](https://github.com/JKorf/Binance.Net/assets/79494507/93661690-7924-4306-9231-e58a24f87982)

**Comment by JKorf** [comment]
Hi, thanks for the report. This should be fixed in version 9.6.0 which I just pushed.

**Comment by drlivsi** [comment]
Thanks, fixed in version 9.6.0
