### ISSUE TITLE
UsdFuturesApi - onOrderUpdate

### ISSUE THREAD

**Issue by JozefGula** [JKorf/Binance.Net#1351]
Callback for onOrderUpdate from "UsdFuturesApi.SubscribeToUserDataUpdatesAsync" does not receive any data.

After each data reception, the library logs:

[Sckt 1] failed to evaluate message

The previous version worked correctly.

**Comment by JozefGula** [comment]
@JKorf may you please check this issue?

**Comment by JKorf** [comment]
Hi, I've pushed version 9.6.1 where I fixed a problem. I wasn't able to test if this completely fixes it right here and now, so please let me know if that fixes your issue :)

**Comment by JozefGula** [comment]
I will test it better and let you know during tomorrow. thank you very much for your work.

**Comment by JozefGula** [comment]
Hello @JKorf. I let it run for a few days and have not noticed any problems yet. It seems that it probably works correctly. Once again, thank you very much.

**Comment by JKorf** [comment]
Great, thanks for the feedback
