### ISSUE TITLE
how set socket5 proxy on BinanceRestClient or BinanceSocketClient at first dircetly?

### ISSUE THREAD

**Issue by robyle** [JKorf/Binance.Net#1354]
I'm trying set socket5 proxy,it will response error just like this, anyone can give me a suggestion to work it on . the proxy info I have test it on edge-browser is ok. but  on coding is fail.

**Comment by JKorf** [comment]
It seems the protocol should be `socks5`, can you try with this url? `new ApiProxy("socks5://127.0.0.1", 1080);`

Also you're showing part of your API key in the screenshot, please be careful with that. If you accidentally show your api key and secret anyone will be able to access your account

**Comment by robyle** [comment]
> It seems the protocol should be `socks5`, can you try with this url? `new ApiProxy("socks5://127.0.0.1", 1080);`
> 
> Also you're showing part of your API key in the screenshot, please be careful with that. If you accidentally show your api key and secret anyone will be able to access your account

OK, Thinks always.   this Api key is only use for reading.
