### ISSUE TITLE
https://jkorf.github.io/Binance.Net/ It's broken

### ISSUE THREAD

**Issue by cnyuqiang** [JKorf/Binance.Net#1356]
Excuse me, may I ask https://jkorf.github.io/Binance.Net/ Can't open it, do you have a new website?

**Comment by JKorf** [comment]
Hi, the documentation for the different libraries has been moved to https://jkorf.github.io/CryptoExchange.Net/  
It's still work in progress. Were you looking for anything in particular?

**Comment by cnyuqiang** [comment]
GET /sapi/v1/asset/wallet/balance
I can't find this interface

**Comment by JKorf** [comment]
Seems I missed this endpoints being added in the API, I'll add it in next release
