### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by KostyaLocal** [JKorf/Binance.Net#1357]
Hello, I am using Bybit and Binance packages. Binance consumes almost 10 times more CPU time, profiler shows the time in waiting for data in sockets. Can you check ?

**Comment by JKorf** [comment]
Hi, both libraries use the same websocket mechanic under the hood, assuming you're using the latest versions. Could it be that Binance just processes more data? 
If you can provide some more context I can have a look:

Library version numbers?
Which subscriptions are you using on both libraries?
Is this happening immediately or after some time?

**Comment by JKorf** [comment]
@KostyaLocal Is this still a thing?

**Comment by KostyaLocal** [comment]
> @KostyaLocal Is this still a thing?
No, performance is ok
