### ISSUE TITLE
Missing AUTO_BORROW_REPAY

### ISSUE THREAD

**Issue by cartoonle** [JKorf/Binance.Net#1360]
Missing...

POST /sapi/v1/margin/order：New enumerate value AUTO_BORROW_REPAY for the field of sideEffectType
POST /sapi/v1/margin/order/oco：New enumerate value AUTO_BORROW_REPAY for the field of sideEffectType

Kind regards...

**Comment by JKorf** [comment]
Is already available in the latest version
