### ISSUE TITLE
StartUserStreamAsync, too many parameters, version 9.9.0

### ISSUE THREAD

**Issue by glipitch** [JKorf/Binance.Net#1365]
**Describe the bug**

Version 9.9.0:

{[ServerError] -1101: Too many parameters; expected '0' and received '2'. } when calling 

`await client.SpotApi.Account.StartUserStreamAsync();`

**To Reproduce**

`var t= await client.SpotApi.Account.StartUserStreamAsync();`

t: {Error response: [ServerError] -1101: Too many parameters; expected '0' and received '2'. , 74 bytes received in 306ms}

**Expected behavior**

Return Success and a listen key.

**Debug logging**
Not currently available, but I'll gather some if needed

**Comment by JKorf** [comment]
Thanks for the report, fixed in version 9.9.1
