### ISSUE TITLE
Problem with latest version

### ISSUE THREAD

**Issue by tbrbde** [JKorf/Binance.Net#1366]
I just updated to the latest version, but now I get this error: 'The given key 'sapi/v1/capital/withdraw/historyGETGET sapi/v1/capital/withdraw/history authenticated' was not present in the dictionary' calling

Binance.Net.Clients.SpotApi.BinanceRestClientSpotApiAccount.GetWithdrawalHistoryAsync()

So I downgraded the library and it is working as before. There seems to be problem with the latest version.

**Comment by JKorf** [comment]
Thanks for the report, I just pushed a fix for this. Version 9.9.2 should work correctly

**Comment by tbrbde** [comment]
Ok, it seems to work now. Thanks!
