### ISSUE TITLE
Universal Transfer has some missing transfer types

### ISSUE THREAD

**Issue by hcanak** [JKorf/Binance.Net#1368]
Hello,

I see that some transfer types are missing in UniversalTransferType enum like;

- MAIN_ISOLATED_MARGIN Spot account transfer to Isolated margin account
- ISOLATED_MARGIN_MAIN Isolated margin account transfer to Spot account

Can you have a look in the next update? Thanks for your great efford @JKorf

**Comment by JKorf** [comment]
Yes, will be added in next update

**Comment by JKorf** [comment]
Added in latest version
