### ISSUE TITLE
Is there a way to get borrow interest rates?

### ISSUE THREAD

**Issue by winsrp** [JKorf/Binance.Net#1370]
I'm looking at this endpoint

https://binance-docs.github.io/apidocs/spot/en/#get-borrow-interest-rate-user_data

And I was wondering if this data can be pulled with this library?

Thanks for you help!

**Comment by JKorf** [comment]
Hi, no this is currently not available, the VIP Loans Endpoints are not implemented at this point

**Comment by winsrp** [comment]
I see, that is sad... still thanks so much for you efforts! keep up the good work!
