### ISSUE TITLE
how to establish websocket connection

### ISSUE THREAD

**Issue by MCaglarGuldiken** [JKorf/Binance.Net#1371]
Hi,

I would like to establish websocket connection but I am not able to get the values.

Should I made any extra API settings to manage it?

 

var binanceSocketClient = new BinanceSocketClient(options =>
                {

                    options.ApiCredentials = new CryptoExchange.Net.Authentication.ApiCredentials(ConfigurationManager.AppSettings["keyBinance"], ConfigurationManager.AppSettings["secretBinance"]);
                });

                var tickerSubscriptionResult = binanceSocketClient.SpotApi.ExchangeData.SubscribeToTickerUpdatesAsync("ETHUSDT", (update) =>
                {
                    var lastPrice = update.Data.LastPrice;
                });

Binance.Net 9.6.1
CryptoExchange.Net 7.0.0

**Comment by JKorf** [comment]
Should work, what do you mean with 'not able to get the values'?

**Comment by MCaglarGuldiken** [comment]
tickerSubscriptionResult status stays in "WaitingForActivation" so lastPrice is not updated.

**Comment by masherak** [comment]
I think you need to learn programming as first a little bit. BinanceSocketClient works perfectly.

**Comment by Steffx115** [comment]
Set opt.SpotOptions.ApiCredentials

**Comment by luke313** [comment]
@MCaglarGuldiken Did you solve this problem?
