### ISSUE TITLE
I want to see the USDT equivalents of my assets.

### ISSUE THREAD

**Issue by turgayacar** [JKorf/Binance.Net#1377]
Hello;
I have a question. The amount of my assets in my wallet is displayed. But I also want them to be displayed in USDT equivalents. How can I make this possible?

**Comment by Steffx115** [comment]
Tbh, i wouldnt create an issue for that as it interferes with developer productivity but there you go:

Asset * AssetPriceUSD * USDTPrice

**Comment by Steffx115** [comment]
Very Simplified:
new BinanceRestClient().UsdFuturesApi.ExchangeData.GetTickerAsync("<walletAsset>").Result.Data.WeightedAveragePrice

then multiply that with your respective Wallet asset
