### ISSUE TITLE
GetExchangeInfo - Can't get properties

### ISSUE THREAD

**Issue by avechuche** [JKorf/Binance.Net#138]
Hello, I need to get the value of a property within the filters of a symbol and I can not, are they private? The only one that I have access to is FilterType. Thx!

![1](https://user-images.githubusercontent.com/11781418/46033170-e6f13500-c0d3-11e8-8244-4c6243d7621d.png)

**Comment by JKorf** [comment]
Hi, you're seeing the base class, which is BinanceSymbolFilter, it only has one property which is the FilterType. If you want a specific filter you can use something like this:
````C#
Filters.OfType<BinanceSymbolLotSizeFilter>().First(); // Retrieves the BinanceSymbolLotSizeFilter
````

I'll probably change this at some point as its not really clear how to use them, but hope this helps you for now.
