### ISSUE TITLE
binanceRestClient.SpotApi.ExchangeData.GetProductsAsync() is not working

### ISSUE THREAD

**Issue by artastakenaka** [JKorf/Binance.Net#1381]
**Describe the bug**
binanceRestClient.SpotApi.ExchangeData.GetProductsAsync() is not working

**To Reproduce**
var binanceRestClient = new BinanceRestClient();
var response = await binanceRestClient.SpotApi.ExchangeData.GetProductsAsync();

**Debug logging**
![image](https://github.com/JKorf/Binance.Net/assets/152327362/10d5dd94-e022-4f38-a9c8-eb1892ea79f3)

**Comment by JKorf** [comment]
Binance seems to have added GZip compression to the endpoint. I'll add a fix for this in next version.
Until that time you can provide a httpclient to the BinanceRestClient to fix it:
```csharp
var handler = new HttpClientHandler();
handler.AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate;
var httpClient = new HttpClient(handler);
var client = new BinanceRestClient(httpClient, fac);
```

**Comment by JKorf** [comment]
Fixed in the latest version
