### ISSUE TITLE
Set specific HttpClient to use

### ISSUE THREAD

**Issue by Steffx115** [JKorf/Binance.Net#1385]
I am currently trying to read bulk data from BinanceApi into a DB, but cant modify the default httpclient as i assume it would interfere with other libraries using the default client.

Is it possible to set a specific httpclient(factory) to use?

**Comment by JKorf** [comment]
If you're using DI to register the Binance clients (`services.AddBinance(..);`) then the http client will be internally registered as a typed client like this 
```csharp
services.AddHttpClient<IBinanceRestClient, BinanceRestClient>(options =>
{
    options.Timeout = restOptions.RequestTimeout;
})
 ```

If you're not using DI you can pass an http client in the BinanceRestClient constructor:
```csharp
var client = new BinanceRestClient(httpClientInstance, loggerFactory, options =>{});
 ```

**Comment by Steffx115** [comment]
Thanks
Is there any performance optimization done library wise?

**Comment by Steffx115** [comment]
Is a different HttpClient used for each request if none is set?

**Comment by JKorf** [comment]
A single HttpClient is used per client. So if you're re-using the same client the same HttpClient is used, but if you're constructing clients each time then a new HttpClient is used each time

**Comment by Steffx115** [comment]
Hmmm ok
Any reason you can imagine why my azure fucntion exceeds the threshhold limit when reading Continous Klines for all symbols?
