### ISSUE TITLE
How do i initialize WebCallResults?

### ISSUE THREAD

**Issue by stephanie-rimel** [JKorf/Binance.Net#1390]
For instance i have this:           WebCallResult<BinancePlacedOrder> o = new WebCallResult<BinancePlacedOrder>();
but it says it doesnt have an empty constructor so it is not working for me. What goes in for the constructor if i just want to initialize it for an order in a try catch to be used outside?

**Comment by JKorf** [comment]
You do not need to initialize it; you can just either not set it or set it to null:
```csharp
WebCallResult result;
try{
    result = await client.xxx;
}
catch(Exception ex){

}
```
