### ISSUE TITLE
Visual Studio Nuget not found

### ISSUE THREAD

**Issue by HoLyDreaM** [JKorf/Binance.Net#1392]
It is not added as nuget in Visual Studio. It's not showing up anymore, can you check?

**Comment by JKorf** [comment]
Hi, yes this there is a known issue. I'm in contact with Nuget about this, but their support is quite slow unfortunately. I expect it to be fixed soon though.

**Comment by osmankuduu** [comment]
They may have hacked the Nuget package because when I search for Binance.Net, VozyakovAV.Binance.Net comes up. He also gave your nuget link. You've been doing this job for years, I know you, but 1.5k people who don't know have downloaded it. Shamelessly continuing the version from 9.9.2 :)

**Comment by JKorf** [comment]
It's not hacked, since the project is open source, anyone can take the code and do with it as they wish. There are a couple of people who have pushed the package to NuGet as wel. It's not illegal. It's weird that NuGet allows the author to be set to my username, but it is what it is. I tried getting a package removed for this reason earlier, but no dice. 

On topic; I still have not had any meaningful response from NuGet support. Unfortunately there is not much else I can do but wait.

**Comment by JKorf** [comment]
I'll just leave this here for people considering the usage of another library. This person is the owner of the package I reported on Nuget for artificial download numbers. Might be related to why my package is currently not available on NuGet. Comment is now removed.

![image](https://github.com/user-attachments/assets/3df8c02b-202a-4f71-bc00-f600a5f51d61)

**Comment by binanceapi-net** [comment]
You are literally a clown

**Comment by glipitch** [comment]
https://www.nuget.org/packages/VozyakovAV.Binance.Net/9.9.2/ReportAbuse

**Comment by osmankuduu** [comment]
> It's not hacked, since the project is open source, anyone can take the code and do with it as they wish. There are a couple of people who have pushed the package to NuGet as wel. It's not illegal. It's weird that NuGet allows the author to be set to my username, but it is what it is. I tried getting a package removed for this reason earlier, but no dice.
> 
> On topic; I still have not had any meaningful response from NuGet support. Unfortunately there is not much else I can do but wait.

What I mean is, hacking or not, but the important thing is that it can change your codes and harm people. In the past, people who used this type of software used all their accounts to pump, even if withdraw were prohibited.

Therefore, I would not make the mistake of using someone else's library other than you, and it is not certain whether this person is a hacker or not.

**Comment by JKorf** [comment]
> > It's not hacked, since the project is open source, anyone can take the code and do with it as they wish. There are a couple of people who have pushed the package to NuGet as wel. It's not illegal. It's weird that NuGet allows the author to be set to my username, but it is what it is. I tried getting a package removed for this reason earlier, but no dice.
> > On topic; I still have not had any meaningful response from NuGet support. Unfortunately there is not much else I can do but wait.
> 
> What I mean is, hacking or not, but the important thing is that it can change your codes and harm people. In the past, people who used this type of software used all their accounts to pump, even if withdraw were prohibited.
> 
> Therefore, I would not make the mistake of using someone else's library other than you, and it is not certain whether this person is a hacker or not.

Yes I agree, its questionable and I definitely wouldn't advice people to use it.

**Comment by osmankuduu** [comment]
> > > It's not hacked, since the project is open source, anyone can take the code and do with it as they wish. There are a couple of people who have pushed the package to NuGet as wel. It's not illegal. It's weird that NuGet allows the author to be set to my username, but it is what it is. I tried getting a package removed for this reason earlier, but no dice.
> > > On topic; I still have not had any meaningful response from NuGet support. Unfortunately there is not much else I can do but wait.
> > 
> > 
> > What I mean is, hacking or not, but the important thing is that it can change your codes and harm people. In the past, people who used this type of software used all their accounts to pump, even if withdraw were prohibited.
> > Therefore, I would not make the mistake of using someone else's library other than you, and it is not certain whether this person is a hacker or not.
> 
> Yes I agree, its questionable and I definitely wouldn't advice people to use it.

Thank you so much and I think you should share this link when we enter the Binance.Net github page.

https://www.nuget.org/packages/VozyakovAV.Binance.Net/9.9.2/ReportAbuse

**Comment by mexxBf** [comment]
I don't know if its any news to you, but I am in contact with someone from them and they are looking into it. I told them this could be a major threat and could lead to some more microsoft security backlash. They responded quite fast in my opinion. I suggested to disable the other package as well to prevent further potential damage.

**Comment by JKorf** [comment]
> I don't know if its any news to you, but I am in contact with someone from them and they are looking into it. I told them this could be a major threat and could lead to some more microsoft security backlash. They responded quite fast in my opinion. I suggested to disable the other package as well to prevent further potential damage.

You mean someone from Nuget? If possible, could you ask them about the status of the Binance.Net package? I can't seem to get any info from them and it's quite frustrating.

**Comment by mexxBf** [comment]
> > I don't know if its any news to you, but I am in contact with someone from them and they are looking into it. I told them this could be a major threat and could lead to some more microsoft security backlash. They responded quite fast in my opinion. I suggested to disable the other package as well to prevent further potential damage.
> 
> You mean someone from Nuget? If possible, could you ask them about the status of the Binance.Net package? I can't seem to get any info from them and it's quite frustrating.

Yes, they asked me if I could provide them with the nessesary information and I gave them all they needed I hope. I am sure they will get back to you soon. I also wrote to "heise" a german tech-news magazine. I think people should know that this is possible on NuGet. Maybe we get things going for you and for us :)

**Comment by JKorf** [comment]
> > > I don't know if its any news to you, but I am in contact with someone from them and they are looking into it. I told them this could be a major threat and could lead to some more microsoft security backlash. They responded quite fast in my opinion. I suggested to disable the other package as well to prevent further potential damage.
> > 
> > 
> > You mean someone from Nuget? If possible, could you ask them about the status of the Binance.Net package? I can't seem to get any info from them and it's quite frustrating.
> 
> Yes, they asked me if I could provide them with the nessesary information and I gave them all they needed I hope. I am sure they will get back to you soon. I also wrote to "heise" a german tech-news magazine. I think people should know that this is possible on NuGet. Maybe we get things going for you and for us :)

Thanks, I appreciate the help :)

**Comment by mexxBf** [comment]
Of course, you help us with your work, thats the least we can do :+1: They answered again. They confirmed working on it and they will give further information of the status "soon". I hope this will soon be over...

**Comment by glipitch** [comment]
Nuget said "We will communicate with the package owner and try to get the issue fixed as soon as possible". I'm not sure if they're taking it as seriously as they should, as this is an obvious hijack, and anything other than immediate action makes Nuget and .NET less reliable. I suggest other interested parties also use the 'report abuse' link above.

**Comment by mexxBf** [comment]
> Nuget said "We will communicate with the package owner and try to get the issue fixed as soon as possible". I'm not sure if they're taking it as seriously as they should, as this is an obvious hijack, and anything other than immediate action makes Nuget and .NET less reliable. I suggest other interested parties also use the 'report abuse' link above.

Yes, maybe it would be also a good idea to reach out to other tech-magazines. It should not be possible to hijack a package and this could happen to others as well.

**Comment by glipitch** [comment]
https://www.reddit.com/r/dotnet/comments/1e4l8d0/nuget_integrity_issue

**Comment by mexxBf** [comment]
The hijacked package is at least flagged as "This package has been deprecated as it is legacy and has critical bugs." https://www.nuget.org/packages/VozyakovAV.Binance.Net/

**Comment by JKorf** [comment]
> > I'll just leave this here for people considering the usage of another library. This person is the owner of the package I reported on Nuget for artificial download numbers. Might be related to why my package is currently not available on NuGet. Comment is now removed.
> 
> You got yourself banned from Nuget trying to get my legitimate package removed, so obviously it was you doing it.
> 
> Good job, hope it was worth it.

I'm not sure what your issue is, but anyone looking at your NuGet profile https://www.nuget.org/profiles/Samuel can see that these download numbers are not organic. Don't take your anger out on other people when you get caught doing something illegal.

**Comment by mexxBf** [comment]
Maybe we should report this clown to github as well.

**Comment by EricGarnier** [comment]
Maybe you should considere ID Prefix Reservation ?
https://learn.microsoft.com/en-us/nuget/nuget-org/id-prefix-reservation

Seems adapted if you name your package something like JKorf.Binance.Net, ...
At leat it is what Microsoft use to protect their own packages.

Never try myself.
Eric

**Comment by JKorf** [comment]
Hi Eric, I did think about that some time back. However, there is no way to rename a package. So if I were to use that I'd have to republish under that new name, and all history and stats would be gone which would be a shame.

**Comment by devbrsa** [comment]
> > > > I'll just leave this here for people considering the usage of another library. This person is the owner of the package I reported on Nuget for artificial download numbers. Might be related to why my package is currently not available on NuGet. Comment is now removed.
> > > 
> > > 
> > > You got yourself banned from Nuget trying to get my legitimate package removed, so obviously it was you doing it.
> > > Good job, hope it was worth it.
> > 
> > 
> > I'm not sure what your issue is, but anyone looking at your NuGet profile https://www.nuget.org/profiles/Samuel can see that these download numbers are not organic. Don't take your anger out on other people when you get caught doing something illegal.
> 
> Obviously you are doing it because you are salty and bad.
> 
> You got banned for a reason.
> 
> > Maybe we should report this clown to github as well.
> 
> Aww, not very smart are you bud.

I have decompiled and am still analyzing the IL code. Let's see what I can uncover in your "best version." Why is this code kept secret and not open-sourced?

**Comment by glipitch** [comment]
https://www.nuget.org/packages/Binance.Net is looking healthy today.

**Comment by JKorf** [comment]
> https://www.nuget.org/packages/Binance.Net is looking healthy today.

Yep, it looks like the package has been relisted and I've been able to push the latest versions. I've not yet received any update from NuGet support about it, but looks like it's fixed :)
