### ISSUE TITLE
GetTickerAsync seems to return incomplete data

### ISSUE THREAD

**Issue by Timmen** [JKorf/Binance.Net#1394]
GetTickerAsync and GetTickersAsync for [Usd-M](https://github.com/JKorf/Binance.Net/blob/master/Binance.Net/Clients/UsdFuturesApi/BinanceRestClientUsdFuturesApiExchangeData.cs) and [Coin-M](https://github.com/JKorf/Binance.Net/blob/master/Binance.Net/Clients/CoinFuturesApi/BinanceRestClientCoinFuturesApiExchangeData.cs) returns IBinance24HPrice type, but seems that it should return IBinanceTick type to include bid and ask prices too. I see in Binance docks that bid/ask are present in ticker.

**Comment by Timmen** [comment]
GetTickerAsync returns IBinance24HPrice type, but seems that it should return IBinanceTick type to include bid and ask prices too. I see in Binance docks that bid/ask are present in ticker.

**Comment by JKorf** [comment]
Can you link the docs? This one (for Usd-M futures) doesn't have bid/ask info
https://binance-docs.github.io/apidocs/futures/en/#24hr-ticker-price-change-statistics

**Comment by Timmen** [comment]
Hello, I checked this and figured out than I mislead you, sorry. I have to use bookTicker endpoint. Binance API is a mess after Bybit.

**Comment by Timmen** [comment]
Hello, I checked this and figured out than I mislead you, sorry. I have to use bookTicker endpoint. Binance API is a mess after Bybit.
