### ISSUE TITLE
method missing version 9.10

### ISSUE THREAD

**Issue by uponatime2019** [JKorf/Binance.Net#1397]
**Describe the bug**
Can't place new sell order after update Binance.Net and CryptoExchange.Net

**To Reproduce**
`SpotApi.Trading.PlaceOrderAsync()`

**Expected behavior**
Success status

**Debug logging**
```
System.MissingMethodException: Method not found: 'CryptoExchange.Net.Objects.RequestDefinition CryptoExchange.Net.Objects.RequestDefinitionCache.GetOrCreate(System.Net.Http.HttpMethod, System.String, CryptoExchange.Net.RateLimiting.Interfaces.IRateLimitGate, Int32, Boolean, System.Nullable`1, System.Nullable`1, System.Nullable`1, System.Nullable`1, System.Nullable`1)'.
   at Binance.Net.Clients.SpotApi.BinanceRestClientSpotApiExchangeData.d__10.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Binance.Net.Clients.SpotApi.BinanceRestClientSpotApiExchangeData.GetExchangeInfoAsync(IEnumerable`1 symbols, CancellationToken ct)
   at Binance.Net.Clients.SpotApi.BinanceRestClientSpotApiExchangeData.GetExchangeInfoAsync(String symbol, CancellationToken ct)
   at AutoTrade.Libs.BinanceOrderHelper.d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System....
```

**Comment by uponatime2019** [comment]
> Hi, there is probably a missmatch between the 2 versions. What versions are the packages?

I don't understand your question, just upgrade Binance.Net and CryptoExchange.Net to latest nuget

**Comment by JKorf** [comment]
Binance.Net is currently not available on NuGet due to a temporary issue with my account.
The version working with latest CryptoExchange.Net version is available here:
https://github.com/JKorf/Binance.Net/releases/tag/9.11.1

You can download the Binance.Net.9.11.1.nupkg file, at it as a local package.

**Comment by uponatime2019** [comment]
> Binance.Net is currently not available on NuGet due to a temporary issue with my account.
> 
> The version working with latest CryptoExchange.Net version is available here:
> 
> https://github.com/JKorf/Binance.Net/releases/tag/9.11.1
> 
> 
> 
> You can download the Binance.Net.9.11.1.nupkg file, at it as a local package. 

Thank, if I downgrade cryptoexchange.net which version I should do?

**Comment by JKorf** [comment]
If you're using Binance.Net 9..10.0 as you mention in the title then you should use CryptoExchange.Net version 7.6.0

**Comment by glipitch** [comment]
> Binance.Net is currently not available on NuGet due to a temporary issue with my account.

JKorf, I'm very sorry that this has happened to your account. Do you know when it will be back to normal?

**Comment by JKorf** [comment]
> > Binance.Net is currently not available on NuGet due to a temporary issue with my account.
> 
> JKorf, I'm very sorry that this has happened to your account. Do you know when it will be back to normal?

Unfortunately not. I'm getting basically no response via NuGet support. Only response I've had that the package allegedly violated the Terms, but I don't think I have and any questions about what terms or what to do to fix it go unanswered.

On Discord I've asked people to send a email to nuget support asking about it, maybe that'll help get the ball rolling.

**Comment by JKorf** [comment]
Lastest versions are available on NuGet again
