### ISSUE TITLE
PRICE_FILTER precision 

### ISSUE THREAD

**Issue by Phil795** [JKorf/Binance.Net#140]
When I make a purchase with the `placeOrder` function, the PRICE_FILTER error occurs. 
This is because I bought LTC/USDT at a price of 61.12000. If I buy for 61.12, there are no problems. The same with other trading pairs. 

If I call the Precision via `exchangeInfo()`, it says 8. Where is my error?

**Comment by JKorf** [comment]
Hi, the Precision you're looking at specifies how accurate the symbol can be. The value you're looking for is specified in the `BinanceSymbolPriceFilter` in the Filters property of a symbol. It can be retrieved using something like this:
````C#
Filters.OfType<BinanceSymbolPriceFilter>().First()
````

**Comment by Phil795** [comment]
Thank you so much.  That takes me further. 
 
Is it so that I must always provide the prices with the correct number of decimal places?

**Comment by JKorf** [comment]
You should yes.

**Comment by Phil795** [comment]
Okay, thanks for your help :-)
