### ISSUE TITLE
SubscribeToKlineUpdatesAsync OpenPrice

### ISSUE THREAD

**Issue by SoaresJunior** [JKorf/Binance.Net#1403]
Hi!

I´m using SubscribeToKlineUpdatesAsync with success to take every candle´s ClosePrice .
To candle´s ClosePrice is safe to use Kline.Data.Data.Final to identify last candle´s Price. 100%.
But I´d like to take every candle´s OpenPrice.
I´m trying to save last OpenTime to compare and identify new candle.
But do not works fine, I´m losting sometimes que correct candle´s OpenPrice.
Isn´t there a "First" flag to indicate the candle´s opening?

TIA

**Comment by SoaresJunior** [comment]
@JKorf
Could you please help me?

**Comment by JKorf** [comment]
No there is no First flag. Can you show the logic you tried to use comparing the open time?

**Comment by SoaresJunior** [comment]
Sorry!
Solved
Thanks
