### ISSUE TITLE
CrossUnrealizedPnL is not Correct after upgrading to Version 10.0.0 - 27 Jul 2024 UsdFuturesApi.Account.GetBalancesAsync to V3

### ISSUE THREAD

**Issue by dante1989** [JKorf/Binance.Net#1404]
i'm using Isolated Mode Margin

Dim ItemFuturesAccountBalance = Await clientBinance.UsdFuturesApi.Account.GetBalancesAsync
Dim BalanceUSD = Array.Find(ItemFuturesAccountBalance.Data.ToArray(), Function(m) m.Asset = "USDT")
In older version: the BalanceUSD.CrossUnrealizedPnl = 0 is correct because i'm using Isolated Mode Margin
After upgrading to Version 10.0.0 - 27 Jul 2024 UsdFuturesApi.Account.GetBalancesAsync to V3. BalanceUSD.CrossUnrealizedPnl <> 0 when i have a isolated position. It is not correct

**Comment by JKorf** [comment]
Hm that seems weird. Is it possible for you to share the response data of the request using `OutputOriginalData` in the client options?

**Comment by dante1989** [comment]
MsgBox(ItemFuturesAccountBalance.OriginalData.ToString)
![image](https://github.com/user-attachments/assets/5f2752d8-edb0-4ef6-8f5b-06d306360307)


                            MsgBox(BalanceUSD.CrossUnrealizedPnl)

![image](https://github.com/user-attachments/assets/b498d385-82ee-4c48-aa7c-49e69e7f75e3)

**Comment by dante1989** [comment]
We could integrate Both V2 and V3

**Comment by JKorf** [comment]
I've asked Binance about this, seems it's a bug:
![image](https://github.com/user-attachments/assets/88f92ed2-d82e-42cd-8606-11e55cacb6f1)

I'd rather not implement multiple versions of the same functionality unless there is a good reason. I'm assuming they'll fix this on their end which should make the V3 endpoint the same as V2 right?

**Comment by dante1989** [comment]
yeah, I also think it's not necessary to make multiple versions if binance fixes the error for us

**Comment by Malove98** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
