### ISSUE TITLE
Missing Leverage in Function UsdFuturesApi.Trading.GetPositionsAsync

### ISSUE THREAD

**Issue by dante1989** [JKorf/Binance.Net#1405]
Dim BinanceFuturesPositions_CheckBalance = Await clientBinance.UsdFuturesApi.Trading.GetPositionsAsync

 For Each LongShortPosition In BinanceFuturesPositions_CheckBalance.Data
Next

Missing LongShortPosition.Leverage 

we do not have Leverage Property For One-way position mode but we have Leverage Property For Hedge position mode:
Check here: https://binance-docs.github.io/apidocs/futures/en/#position-information-v3-user_data

**Comment by dante1989** [comment]
I think V2 is better V3. V2 have the full information of Leverage

**Comment by dante1989** [comment]
We could integrate Both V2 and V3

**Comment by kayahasa** [comment]
Same here, leverage is 0. I will return back to V2.

**Comment by Malove98** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by JKorf** [comment]
Closing this as it's not an issue with the library. Both V2 and V3 endpoints are available.

**Comment by ZERGULIO** [comment]
is there a method for websocket? to monitor profit or loss on an open position in real time? here is the method I need for websocket - UsdFuturesApi.Trading.GetPositionsAsync();

**Comment by ZERGULIO** [comment]
> Closing this as it's not an issue with the library. Both V2 and V3 endpoints are available.

is there a method for websocket? to monitor profit or loss on an open position in real time? here is the method I need for websocket - UsdFuturesApi.Trading.GetPositionsAsync();
