### ISSUE TITLE
Whenever trying to convert on Funding wallet, the convert actually happens on the spor wallet

### ISSUE THREAD

**Issue by andresdrb** [JKorf/Binance.Net#1408]
https://github.com/JKorf/Binance.Net/blob/ab975f73e28386042aeba06aad9544eb2d71012a/Binance.Net/Clients/SpotApi/BinanceRestClientSpotApiTrading.cs#L1213

**Comment by andresdrb** [comment]
More tha likely happening because in Binance API documentation the wallet type parameter values are Uppercase and may be it is case sensitive so defaulting to SPOT https://binance-docs.github.io/apidocs/spot/en/#send-quote-request-user_data

![image](https://github.com/user-attachments/assets/f40f5456-2486-4d82-9c9a-b38c93d57dec)

**Comment by JKorf** [comment]
Hi, I've fixed the serialization of this. Let me know if you have any other issues

**Comment by andresdrb** [comment]
Cool, thanks!Enviado desde mi iPhoneEl 18 ago 2024, a las 21:13, Jan Korf ***@***.***> escribió:﻿
Hi, I've fixed the serialization of this. Let me know if you have any other issues
