### ISSUE TITLE
BinanceSymbolIcebergPartsFilter Error

### ISSUE THREAD

**Issue by nikkozp** [JKorf/Binance.Net#141]
Hello :)
```
 BinanceSymbolIcebergPartsFilter filter = (BinanceSymbolIcebergPartsFilter)exchangeInfo.FirstOrDefault(x => x.Name == Symbol).Filters[4];

return filter.Limit;
```
Error in `BinanceSymbolIcebergPartsFilter filter = (BinanceSymbolIcebergPartsFilter)exchangeInfo.Filters[4]`

This mean what should be MaxNumberAlogitmicalOrders

> System.Invalidcastexception exception: "failed to cast object type" "Binance.Net.Objects.BinanceSymbolMaxAlgoritmicalOrdersFilter" "to type "Binance.Net.Objects.BinanceSymbolIcebergPartsFilter"."

**Comment by nikkozp** [comment]
![image](https://user-images.githubusercontent.com/11537426/46366187-c2203300-c67a-11e8-92f8-4d406f5c6d7f.png)

Here in `BinanceSymbolIcebergPartsFilter `you have 4

**Comment by nikkozp** [comment]
I found another way to `findCoin.Filters.OfType<BinanceSymbolIcebergPartsFilter>().First ().Limit`

But if this 1 and 2 post has a bug, please check :)

**Comment by JKorf** [comment]
Hi,
I've made the accessing of the symbol filter easier in the latest version (v3.2.8, should be available in a few minutes), so you can just call `findCoin.IceBergPartsFilter` to get the iceberg parts filter.
