### ISSUE TITLE
Internal Binance Transfer With Binance ID

### ISSUE THREAD

**Issue by CafeCode-cs** [JKorf/Binance.Net#1425]
Hello, I want to use the Withdraw method for internal transfer in Binance with the following inputs
coin : “USDT”
address : “5396*****” (BinanceId)
amount : 2
But I encountered such an error
Address verification failed. Please confirm the network is matched with the withdrawal address. You may consult with recipient’s platform for details.
Did I make a mistake? Thank you for helping me

**Comment by Malove98** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by Programmer-cs** [comment]
This is very risky. My users may be using addresses that Binance has banned, which could result in my account being blocked. Is there a way I can identify these addresses?

**Comment by CafeCode-cs** [comment]
This is very risky. My users may be using addresses that Binance has banned, which could result in my account being blocked. Is there a way I can identify these addresses?
