### ISSUE TITLE
 Adjust Contract Leverage for UsdFuturesApi

### ISSUE THREAD

**Issue by MihailDamian** [JKorf/Binance.Net#1432]
Is there a method to change leverage for a symbol in UsdFuturesApi?
Thanks

**Comment by MihailDamian** [comment]
My use case: I got 400+ symbols and unfortunately Binance dont provide a global leverage adjustment, so it can be helpful to have a method to do that, so you can call it for each symbol and dirty work is done in 1 minute instead of 1 month :))

**Comment by JKorf** [comment]
Hi, yes you can use the `restClient.UsdFuturesApi.Account.ChangeInitialLeverageAsync` method for this

**Comment by MihailDamian** [comment]
Thank you, working for copy trading account too!
