### ISSUE TITLE
doc vs implementation discrepancies on IBinanceRestClientGeneralApiAutoInvest.GetSubscriptionTransactionHistoryAsync

### ISSUE THREAD

**Issue by abstract195** [JKorf/Binance.Net#1433]
1. in binance documentation stays that planId is optional, please make it optional as well on the client

https://developers.binance.com/docs/auto_invest/trade/Query-subscription-transaction-history

`IBinanceRestClientGeneralApiAutoInvest.GetSubscriptionTransactionHistoryAsync(long planId, DateTime? startTime = null, DateTime? endTime = null, string? targetAsset = null, AutoInvestPlanType? planType = null, int? page = null, int? pageSize = null, CancellationToken ct = default);
`

2. it seems that binance api doc is incorrect about response type, because after calling the endpoint we end up with following exception
`Deserialize JsonException: The JSON value could not be converted to System.Collections.Generic.IEnumerable1[Binance.Net.Objects.Models.Spot.AutoInvest.BinanceAutoInvestPlanTransaction]. Path: $ | LineNumber: 0 | BytePositionInLine: 1., Path: $, LineNumber: 0, LinePosition: 1
`

original response data: `{"total":0,"list":[]}`

3. this seems to be incorrect as well
`parameters.AddOptional("page", page);
parameters.AddOptional("pageSize", pageSize);
`
should be 'current' and 'size'

**Comment by JKorf** [comment]
Thanks for the report, will be fixed in next version

**Comment by Malove98** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
