### ISSUE TITLE
Empty/null PriceDecimals

### ISSUE THREAD

**Issue by xaviergxf** [JKorf/Binance.Net#1441]
When using the exchange abstractions (ISpotSymbolRestClient) i was expecting to get the PriceDecimals with some value. Instead it's null. How to get how many decimals per trading pair using the abstraction?

Thanks

**Comment by JKorf** [comment]
Hi, which fields are filled depends on what the exchange API returns. In the case of Binance it doesn't return the Decimal fields, but instead the `PriceStep` and `QuantityStep` fields, which can be used for the same purpose. The price and quantity fields should be a multiple of the Step values.

**Comment by xaviergxf** [comment]
@JKorf what's the difference between PriceStep and PriceDecimal? There is none? Both fields relate to the amount of decimal precision and how to round the pricing?

**Comment by JKorf** [comment]
PriceDecimals is an integer for how many decimal places to use. For example, when PriceDecimals = 2 then prices should be specified like 1.01, 1.02 etc, 2 decimal places.
PriceStep would be a decimal, for example 0.001, then price should be specified as 1.001, 1.002 etc, increments of 0.001

**Comment by xaviergxf** [comment]
Thanks @JKorf, is much more clearer for me :)
