### ISSUE TITLE
ListenKey comes empty on socket onAccountPositionMessage events

### ISSUE THREAD

**Issue by andresdrb** [JKorf/Binance.Net#1443]
**Describe the bug**
When subscribing to an account position change socket channel (SubscribeToUserDataUpdatesAsync.onAccountPositionMessage), the Listen Key that identifies the channel comes empty when events are triggered

**To Reproduce**
Subscribe to an account SubscribeToUserDataUpdatesAsync.onAccountPositionMessage and trigger an update to come. The event Data.ListenKey comes empty

**Expected behavior**
ListenKey should come with the value of the subscription listen key

**Comment by andresdrb** [comment]
Any ideas about this? @JKorf

**Comment by andresdrb** [comment]
Cool, thanks! I think it may be the same when you start the socket channel that it is not returning the listenKey, so the code I was using to keep the channel alive was not working either….Enviado desde mi iPhoneEl 19 nov 2024, a las 9:31, Jan Korf ***@***.***> escribió:﻿
Hi, you're right. I'll fix it in next version.

**Comment by JKorf** [comment]
Fixed in latest version

**Comment by andresdrb** [comment]
Thanks!Enviado desde mi iPhoneEl 19 nov 2024, a las 15:12, Jan Korf ***@***.***> escribió:﻿
Fixed in latest version
