### ISSUE TITLE
unable to parse GetLockedProductPositionsAsync response

### ISSUE THREAD

**Issue by hcanak** [JKorf/Binance.Net#1445]
Hello @JKorf ,

When i call GetLockedProductPositionsAsync it returns as follows;

![image](https://github.com/user-attachments/assets/1403e0d1-3886-458d-8a42-f5a08f9630fc)

Keep in mind that i have one asset in locked earn wallet. Can you have a look? Thanks for your effford.

**Comment by JKorf** [comment]
Hi, should be fixed in the latest version
