### ISSUE TITLE
Can't change base address it's readonly

### ISSUE THREAD

**Issue by Dejavu333** [JKorf/Binance.Net#1451]

**Comment by Dejavu333** [comment]
Can't see anything about it in the documentation.

**Comment by minza55113151** [comment]
If you want to change base address you can use `BinanceEnvironment` to assign the client base address.
```c#
new BinanceRestClient(option =>
{
    option.ApiCredentials = new ApiCredentials(APIKEY, API_SECRET);
    option.Environment = isTestNet ? Binance.Net.BinanceEnvironment.Testnet : Binance.Net.BinanceEnvironment.Live;
});
```
That BinanceEnvironment have presets such as Testnet, Live or Us.
If you want to create custom address you can use `BinanceEnvironment.CreateCustom()` that you have to pass address such as `spotRestAddress`, `spotSocketStreamAddress`, `spotSocketApiAddress`.
