### ISSUE TITLE
"LD" prefix in the name of asset???

### ISSUE THREAD

**Issue by hcanak** [JKorf/Binance.Net#1452]
Hello @JKorf ,

I see that there is a prefix "**LD**" in the asset name while transfering asset in/out to Earn Wallet in balance update event.  What is the purpose of this prefix? Is it something defined in api?

![image](https://github.com/user-attachments/assets/9ab7f887-efb9-4997-ad61-80f50bc98b39)

**Comment by JKorf** [comment]
Hi, no sorry I don't know. It's not something added by the client, and I don't see it mentioned in the API documentation
