### ISSUE TITLE
What is broker id is for?

### ISSUE THREAD

**Issue by Tendx** [JKorf/Binance.Net#1455]
After LibraryHelper.ApplyBrokerId called in Place/Cancel Order, and a magic prefix string was added in client id. What is for, and why we should do this?

**Comment by JKorf** [comment]
Hi, it's a reference to the client which was used to place the order. The server uses this to identify the client and grants a portion of the trading fees paid by the user to the client owner. Important to note is that the user does not pay anything extra, just the normal trading fees.
It's a way to make some money back on developing the library.
