### ISSUE TITLE
Liquidation orders are incorrectly mapped as Limit 

### ISSUE THREAD

**Issue by demidyukvalentin** [JKorf/Binance.Net#1456]
I’ve noticed that in the Futures API, Liquidation orders are incorrectly mapped as Limit when using GetOpenOrdersAsync or GetOrdersAsync.

Steps To Reproduce
Manage to have small liquidated position on binance futures subaccount. Try to load orders from it. You will see 1 or two orders with client code prefix "autoclose" and Limit type. But on exchage's Sub Account  -> Order Management page their type is Liquidation.

**Comment by JKorf** [comment]
Hi, order type is independent of whether it is a liquidation order or not. Liquidation orders can be limit orders, the Binance UI just chooses to display them as liquidation orders.

In the latest version I've added the `IsLiquidationOrder` property on the futures order model which checks the ClientOrderId property to see if an order is a liquidation order or not. It's up to the client how to display this in the UI.

**Comment by demidyukvalentin** [comment]
Oh.. you are right. Thanks for clarification!
