### ISSUE TITLE
MyTrades

### ISSUE THREAD

**Issue by alirezamahmoudi** [JKorf/Binance.Net#146]
I've some problem with getmytrades function. I don't know this is a bug in the library or the bug in Binance.
No matter what symbol I've sent, every time the results are the same.

**Comment by alirezamahmoudi** [comment]
Yes, I'm using the last version. There is not any complex code, just calling getmytrades function with symbol.
I tried to check anything again, and found out that the result is not the same but contains some records that not appeared in binance trade history of my account!

**Comment by JKorf** [comment]
Is there something common in the records that you wouldn't expect?

**Comment by alirezamahmoudi** [comment]
For example I've lots of filled trade, but only three of them is returned as result for "ETHUSDT" and 2 of them is returned for "XRPUSDT".
Also, By converting the timestamps in the out put the dates are not matched with my trade dates. Generally I can't find any record matched by Trade history tab on binance (via binance website in my account).

**Comment by JKorf** [comment]
The timestamps are all in UTC time. If you want to convert that to local time you can use the ToLocalTime function in the DateTime object. 
Can you share debug logging if you are missing data?

**Comment by JKorf** [comment]
I'll assume you figured this out. If not please re-open and provide more information.
