### ISSUE TITLE
QueryOrder price variable always 0

### ISSUE THREAD

**Issue by hlstriker** [JKorf/Binance.Net#15]
Using QueryOrder the returned results always have the Price variable set to 0. I had to use GetMyTrades and traverse the results to get the price. It would be much better if QueryOrder would return the correct price result so it could be used to query a single order ID.

**Comment by JKorf** [comment]
Hi, I've just tried this locally and it seems to work as expected, price is filled with the price of the order. What version of the library are you using, and what was the type of the order?

**Comment by BenVlodgi** [comment]
@hlstriker was it a market order? Market orders come through as a price of 0, because no price was set.
Which is why you have to look at trade history to see what price it was actually sold at

**Comment by hlstriker** [comment]
@JKorf Version 2.2.3, although it's working as expected according to Ben.

@BenVlodgi It was indeed a market order. Thank's for the clarification.
