### ISSUE TITLE
Async Parallel call

### ISSUE THREAD

**Issue by NathanielCoding** [JKorf/Binance.Net#150]
Hi,
I see there is available Async method calls. Is there a parallel method calls available, as I think it could run faster. Note: I am still beginner in this.
Thanks

**Comment by JKorf** [comment]
Hi, I'm not sure what functionality you're asking for. Could you maybe explain a bit more what you're trying to achieve?

**Comment by NathanielCoding** [comment]
Hi,
I probably misunderstood. I am trying to run order book, trade history, all coin prices, open orders, my order history, my trades, and I am trying to get them all as fastest as possible. I thought parallel async call would be fastest. Basically, I am trying to wait to refresh data as fastest as possible using async calls.

**Comment by JKorf** [comment]
Parallel and async are closely related. You can do something like this:
````C#
var task1 = client.Get24HPriceAsync("ETHBTC");
var task2 = client.Get24HPriceAsync("BNBBTC");
var task3 = client.Get24HPriceAsync("NEOBTC");
Task.WaitAll(new [] { task1, task2, task3 });
````
These calls won't wait for eachother and therefor will run in parallel. The last line waits for all the tasks to complete. If you want realtime data the websocket might be more suitable though.
