### ISSUE TITLE
Getting exception. Something may have change on the Binance API...

### ISSUE THREAD

**Issue by tbrbde** [JKorf/Binance.Net#155]
Today I get a System.InvalidCastException using Binance.Net: 
Cannot cast from source type "Binance.Net.Objects.BinanceSymbolPercentPriceFilter" to destination type "Binance.Net.Objects.BinanceSymbolLotSizeFilter".
As it seems there are new filters available:
https://github.com/binance-exchange/binance-official-api-docs/blob/master/CHANGELOG.md

**Comment by HugoPeters1024** [comment]
I get a Deserialazation Error when calling `client.GetExchangeInfo()`. I expect this is related.

**Comment by tbrbde** [comment]
The Filters[] sequence has been changed. So we have to update our code related to this.

**Comment by HugoPeters1024** [comment]
> The Filters[] sequence has been changed. So we have to update our code related to this.

Could you be specific to what file we are talking about? I would to love to take a shot at fixing it but the code I see in `SymbolFilterConverter.cs` seems quite complete with regards to the API update.

**Comment by tbrbde** [comment]
There is a new filter's order:
                BinanceSymbolPriceFilter priceFilter = (BinanceSymbolPriceFilter)bs.Filters[0];
                        BinanceSymbolPercentPriceFilter percentPriceFilter = (BinanceSymbolPercentPriceFilter)bs.Filters[1];
                        BinanceSymbolLotSizeFilter lotSizeFilter = (BinanceSymbolLotSizeFilter)bs.Filters[2];
                        BinanceSymbolMinNotionalFilter notionalFilter = (BinanceSymbolMinNotionalFilter)bs.Filters[3];
                        BinanceSymbolIcebergPartsFilter icebergPartsFilter = (BinanceSymbolIcebergPartsFilter)bs.Filters[4];
                        BinanceSymbolMaxAlgoritmicalOrdersFilter maxAlgoOrdersFilter = (BinanceSymbolMaxAlgoritmicalOrdersFilter)bs.Filters[5];

**Comment by HugoPeters1024** [comment]
Is the issue then with the order in the `SymbolPriceFilter` of `Enums.cs` line 209

**Comment by avechuche** [comment]
I had a similar problem and looking there was a moment where binance did not send the BinanceSymbolLotSizeFilter filter. If you did not have a secure code, it breaks. If you look now, the filter is there, but MaxPrice and MinPrice are equal to 0. The price, for now, is handled with the BinanceSymbolPercentPriceFilter filter

https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md show **Filter** section

**Comment by JKorf** [comment]
Hi, do you guys get errors results from the GetExchangeInfo call, or you have errrors processing the data? The call works for me, but if it is what @avechuche says it might have been a temporary hickup on the Binance side. 

Either way, you should probably use the direct filter properties on the BinanceSymbol object instead of accessing the array on index. I.g. BinanceSymbol.LotSizeFilter.

**Comment by dejancrn** [comment]
GetExchangeInfo also fails for me since today. Here's the error i get:

{5: Error deserializing data: Deserialize Unknown Exception: Object reference not set to an instance of an object.. Received data:

**Comment by JKorf** [comment]
That's weird.. When I try to parse the data you linked it works for me. What version of Binance.Net are you using?

**Comment by GlubGlub** [comment]
I was getting the same error on GetExchangeInfo() but I think that was because I was on an old version (3.2.3). I updated to latest version and it seems to be working now.

**Comment by dejancrn** [comment]
I'm using 3.2.11

**Comment by HugoPeters1024** [comment]
> I was getting the same error on GetExchangeInfo() but I think that was because I was on an old version (3.2.3). I updated to latest version and it seems to be working now.

Ah thanks! that was indeed the problem!

**Comment by dejancrn** [comment]
Updated to 3.3.0 and now it works. Thanks

**Comment by JKorf** [comment]
Cool. Always see if there is a new version available if something is broken ;)
I'll assume it works for everyone with the latest version.
