### ISSUE TITLE
Error -1013 Invalid Price

### ISSUE THREAD

**Issue by fartmanly** [JKorf/Binance.Net#158]
Hello,
I am suddenly receiving errors when trying to place any buy or sell order. The error is the same:
"Error -1013 Invalid Price"
Haven't changed my code ... just suddenly started receiving these errors for the last day.
I reverted to older known-working versions of my code and now receive the same error.
When I place the exact same order using the web or mobile app, it goes through fine. However, using the API it fails.
I am positive my order quantites, lot size, minimums, etc are all correct.
For example, I tried to buy 1000 MITHBTC for .00002782 and received the error.
Every buy or sell order for any coin produces this error from Binance.

I've also tried uninstalling and reinstalling the Binance.net package and that didn't help.

Has Binance suddenly changed something that is causing this? Very strange.

**Comment by JKorf** [comment]
Hi, can you enable debug logverbosity and post the logging of when you're placing an order?

**Comment by swAucxis** [comment]
I had the same issue.
PlaceOrder("MFTBTC", OrderSide.Sell, OrderType.Limit, 10.0, price: 0.0000009595) ERROR -1013: Invalid price.

I'm using the following config: TradeRulesBehaviour.AutoComply

**Comment by fartmanly** [comment]
Thanks for the response. Setting TradeRulesBehavior to "none" has fixed the issue for now.

**Comment by fartmanly** [comment]
Just update to new version and getting a couple new code errors (using VB.net and Visual Studio 2017):
In the following code:

    Dim bsco As New BinanceSocketClientOptions
    With bsco
      .ApiCredentials = New Authentication.ApiCredentials(apiKey, apiSecret)
      **.RateLimitingBehaviour = Net.Objects.RateLimitingBehaviour.Wait**
     **.ReconnectTryBehaviour = ReconnectBehaviour.AutoReconnect**
    End With
    BinanceSocketClient.SetDefaultOptions(bsco)

Both properties ".RateLimitingBehaviour" and ".ReconnectTryBehaviour" no longer seem to exist.
Not sure how to recode those 2 lines.

**Comment by JKorf** [comment]
I've done some cleaning in the code so what you're seeing is correct:
* `RateLimitingBehaviour` is only a valid option for the `BinanceClient`, not the `BinanceSocketClient`. It didn't actually do anything before if you specified it on the socket client.
* 'ReconntectTryBehaviour' has been deprecated, socket will automatically try to reconnect.

I released version 4.0.0 before I was aware of the AutoComply issue, but expect a fix for that today.

**Comment by JKorf** [comment]
The last version (4.0.1) should work again with AutoComply!

**Comment by swAucxis** [comment]
Got the following error with AutoComply on.

PlaceOrder(SKYBTC, OrderSide.Sell, OrderType.Limit, 196.88300000, price: 0.0002703000) 

ERROR -1111: Precision is over the maximum defined for this asset.
