### ISSUE TITLE
New correct use of BinanceClient()

### ISSUE THREAD

**Issue by avechuche** [JKorf/Binance.Net#159]
In version 3.x I used the following code. 

```
using (var binanceClient = new BinanceClient())
{
	var binanceResult = await binanceClient.GetExchangeInfoAsync();
	if (binanceResult.Success)
	{
		...
	}
}
```

In the new version how do I get the same result? Thx!

**Comment by avechuche** [comment]
Perfect. Solved!

**Comment by LeonardoX77** [comment]
I have updated 
Binance.Net 4.0.1 to 6.3.2
CryptoExchange.Net 2.0.2 to 3.1.0

But I can't find GetExchangeInfoAsync() method in BinanceClient, even searching in the whole object explorer, where is it? how can I get the current list of asset pairs?
I also cleaned and rebuilt my solution but still same error

Also I can't find SubscribeToSymbolTickerAsync() method in BinanceSocketClient
Any help would be appreciated
