### ISSUE TITLE
client.GetExchangeInfo returning wrong ratelimittype

### ISSUE THREAD

**Issue by topproto** [JKorf/Binance.Net#16]
-		RateLimits	Count = 3	System.Collections.Generic.List<Binance.Net.Objects.BinanceRateLimit>
-		[0]	{Binance.Net.Objects.BinanceRateLimit}	Binance.Net.Objects.BinanceRateLimit
		Interval	Minute	Binance.Net.Objects.RateLimitInterval
		Limit	1200	int
		Type	Requests	Binance.Net.Objects.RateLimitType
-		[1]	{Binance.Net.Objects.BinanceRateLimit}	Binance.Net.Objects.BinanceRateLimit
		Interval	Second	Binance.Net.Objects.RateLimitInterval
		Limit	10	int
		Type	Requests	Binance.Net.Objects.RateLimitType
-		[2]	{Binance.Net.Objects.BinanceRateLimit}	Binance.Net.Objects.BinanceRateLimit
		Interval	Day	Binance.Net.Objects.RateLimitInterval
		Limit	100000	int
		Type	Requests	Binance.Net.Objects.RateLimitType

Should be

-		RateLimits	Count = 3	System.Collections.Generic.List<Binance.Net.Objects.BinanceRateLimit>
-		[0]	{Binance.Net.Objects.BinanceRateLimit}	Binance.Net.Objects.BinanceRateLimit
		Interval	Minute	Binance.Net.Objects.RateLimitInterval
		Limit	1200	int
		Type	Requests	Binance.Net.Objects.RateLimitType
-		[1]	{Binance.Net.Objects.BinanceRateLimit}	Binance.Net.Objects.BinanceRateLimit
		Interval	Second	Binance.Net.Objects.RateLimitInterval
		Limit	10	int
		Type	**Orders**	Binance.Net.Objects.RateLimitType
-		[2]	{Binance.Net.Objects.BinanceRateLimit}	Binance.Net.Objects.BinanceRateLimit
		Interval	Day	Binance.Net.Objects.RateLimitInterval
		Limit	100000	int
		Type	**Orders**	Binance.Net.Objects.RateLimitType

**Comment by JKorf** [comment]
You are right, this is fixed in the latest version (2.2.4)
