### ISSUE TITLE
BinanceSocketClient SubscribeToUserStream

### ISSUE THREAD

**Issue by gbonaros** [JKorf/Binance.Net#160]
Hi,

after last aupdate, calling SubscribeToUserStream hangs the programm

George

**Comment by GonzoKK** [comment]
I get the error - 'string' does not contain a definition for 'ListenKey' and no extension method 'ListenKey' accepting a first argument of type 'string' could be found 

var listenData = await binanceSocketClient.StartUserStreamAsync();
string listenKey = listenData.Data.ListenKey;

**Comment by JKorf** [comment]
Hi,
@gbonaros I forgot to add some `.ConfigureAwait(false)` calls, which means that it now blocks if called from the UI thread. Fix for this will be pushed today.
@GonzoKK The structure has changed slightly, instead of using `listenData.Data.ListenKey` just use `listenData.Data` now.

**Comment by gbonaros** [comment]
nice, thanks for the quick update :)

**Comment by JKorf** [comment]
New version is available now!
