### ISSUE TITLE
'BittrexClient': type in a using statement error

### ISSUE THREAD

**Issue by GonzoKK** [JKorf/Binance.Net#161]
I get the error: 'BittrexClient': type used in a using statement must be implicitly convertible to 'System.IDisposable'

Is this intentional? 

For now I'm using:             
client.Dispose();

**Comment by JKorf** [comment]
Hi, it is not intentional. You can upgrade to CrypoExchange.Net v2.0.1 in the package manager to fix it.

**Comment by GonzoKK** [comment]
perfect. thanks
