### ISSUE TITLE
Problem with limit orders after Binance API update

### ISSUE THREAD

**Issue by tbrbde** [JKorf/Binance.Net#162]
I was able to send a lot of limit orders for a long time. But after the last Binance API update most orders fail. I get this error message from Binance.Net:
"Trade rules check failed: Price filter failed. Original price: 0,32141, Closest allowed: 0"
0,32141 is only an example for one of my orders. What can be the reason for this? Why do I get "Closest allowed: 0" for most of my orders now? 
Any help appreciated.

**Comment by JKorf** [comment]
Hi, are you using the latest version? Binance did indeed update their server which meant the trade rules were interpreted incorrectly.
