### ISSUE TITLE
Websock error

### ISSUE THREAD

**Issue by muteddisk** [JKorf/Binance.Net#163]
Hi M. Korf,
That was a big update to stream line your APIs. Keep up the great work. I'll send a donation as soon as I can for your great work. The issue with the update is the "subscribe" to any of the call is not returning to the thread. So if you you subscribe to klines and ticker, the thread locks. I could start each stream on a different thread but then it creates a lot of connections.

Thanks

**Comment by JKorf** [comment]
Hi, thanks for the kind words again. Donations are always appreciated ;)
It was a lot of work, but it should make life easier for those who use multiple libraries. 

I'm not sure what problem you're seeing, could you perhaps add some code and what you would expect?

**Comment by muteddisk** [comment]
I put some code together to test it out

![image](https://user-images.githubusercontent.com/30062459/49610962-0f1bd080-f96e-11e8-8af4-110a1f0811fa.png)

It won't do the for/next. It calls the first websock call (symbolticker) won't return from the call and run allsymbolsticker or klinestream. it will run whatever code I put on ticker changes but won't come out of it. I would have to start each stream on a different thread to be able to call more than one websock call

**Comment by JKorf** [comment]
Okay so this seems like I forgot a ConfigureAwait(false) somewhere. Are you calling this from the UI thread? On a button click or a load event or something? If so, you could probably quickfix it by just calling it from a task. I'm not sure about the VB syntax, but in C# something like this would do the trick:
````C#
Task.Run(() =>{
    // Your loops and stuff
});
````
Tomorrow I'll look into where the hickup is.

**Comment by muteddisk** [comment]
no worries. I always test the new version before switching my code. That's what I was saying. I can go around on a different thread but 3 streams per symbol times X symbols make a shit loads of threads ;)

**Comment by muteddisk** [comment]
Same issue with coinEx. Let me try bittrex
