### ISSUE TITLE
AutoComply - ERROR -1111: Precision is over the maximum defined for this asset.

### ISSUE THREAD

**Issue by swAucxis** [JKorf/Binance.Net#164]
Got the following error with AutoComply on.

PlaceOrder(SKYBTC, OrderSide.Sell, OrderType.Limit, 196.88300000, price: 0.0002703000)

ERROR -1111: Precision is over the maximum defined for this asset.

**Comment by swAucxis** [comment]
The ClampPrice isn't working as expected because the symbolData.PriceFilter.MaxPrice and MinPrice is 0.0

**Comment by JKorf** [comment]
Hi, this should be fixed in version 4.0.2 which is available in a few minutes.
