### ISSUE TITLE
IP Ban Even Though I am only Using the WebSocket

### ISSUE THREAD

**Issue by mooningnow** [JKorf/Binance.Net#165]
Hi Korf,

I am using BinanceSocketClient to subscribe to over 100 symbols.

After updating to the latest version, I am frequently getting IP Bans even though I am using only the WebSockets. By any chance this could be a bug in the latest version?

**Comment by JKorf** [comment]
Can you maybe post some more logging of when you're subscribing and all? I'm not sure how you would get IP banned by just using the websocket. The logging says `2018/12/11 17:40:10:357 | Warning | Server returned an error: {"code":-1003,"msg":"Way too many requests; IP banned until 1544570770441. Please use the websocket for live updates to avoid bans."}`, what request is that returned from? That specific logging can only be returned from a Rest client request, so apparently you're still using that.

**Comment by mooningnow** [comment]
I can't reproduce the issue since yesterday. Closing this issue! Thank you for your time.
