### ISSUE TITLE
Working example of GetKlinesAsync in a console app?

### ISSUE THREAD

**Issue by mynameisibra** [JKorf/Binance.Net#17]
Been trying to get a working async of the klines, I get it to display the results but not get the new ones in.

**Comment by JKorf** [comment]
Hi, the GetKlinesAsync method will provide you with a snapshot and history of the requested symbol/interval. It won't automatically update these values for you. In order to receive updates you'll need to use the `BinanceSocketClient`. I've made a small test program for you which will initially retrieve the klines for a symbol and then keep it updated by subscribing to the socket stream:

````C#
private static void TrackKlines()
        {
            List<BinanceKline> lineData;

            using (var client = new BinanceClient())
                // Retrieve initial data
                lineData = client.GetKlines("ETHBTC", KlineInterval.OneMinute).Data.ToList();

            var socketClient = new BinanceSocketClient();
            // Subscribe to socket updates
            socketClient.SubscribeToKlineStream("ETHBTC", KlineInterval.OneMinute, data =>
            {
                var existingKline = lineData.SingleOrDefault(k => k.OpenTime == data.Data.StartTime);
                if (existingKline == null)
                {
                    // Create a new object if we don't have data for this period yet
                    existingKline = new BinanceKline()
                    {
                        CloseTime = data.Data.EndTime,
                        OpenTime = data.Data.StartTime
                    };
                    lineData.Add(existingKline);
                    Console.WriteLine($"Added new kline: {existingKline.OpenTime}-{existingKline.CloseTime}");
                }

                // Update the data of the object
                existingKline.High = data.Data.High;
                existingKline.Low = data.Data.Low;
                existingKline.Close = data.Data.Close;
                existingKline.Open = data.Data.Open;
                existingKline.Trades = data.Data.TradeCount;
                existingKline.Volume = data.Data.Volume;
                Console.WriteLine($"Kline updated. Last price: {lineData.OrderByDescending(l => l.OpenTime).First().Close}");
            });

            Console.ReadLine();
        }
````

**Comment by JKorf** [comment]
Did this help you?

**Comment by mynameisibra** [comment]
Thanks! I haven't gotten a chance to try it yet, I'll let you know

---
Ibrahim H / Technology Consultant
www.fixstop.com

<http://www.fixstop.com>

Fix Stop at Alafaya 1975 S. Alafaya Trail. Orlando, FL 32828
*(407) 456-7551*Fix Stop at Chickasaw 599 S. Chickasaw Trail Ste #300.
Orlando, FL 32825
*(407) 550-0015*Fix Stop at Altamonte 1501 E. Altamonte Dr Suite #1015.
Casselberry, FL 32730 *(407) 588-9711*
<http://www.fixstop.com>

**Comment by BenVlodgi** [comment]
@mynameisibra I have a forked repo of the sample clients from this repo, with added functionality.
https://github.com/BenVlodgi/BinanceClient
![image](https://user-images.githubusercontent.com/1462374/35695786-8bea0284-0753-11e8-9685-e8a441aad46d.png)

**Comment by JKorf** [comment]
I'll assume you've managed to get it working. If not please let me know.
