### ISSUE TITLE
Stops receiving account and orders updates

### ISSUE THREAD

**Issue by karloballa** [JKorf/Binance.Net#170]
After a while, usually 3-4 hours, the socket stops receiving account and orders updates. Socket is open, reconnect is true, ping is true, but does not receive any notifications.

**Comment by JKorf** [comment]
Hi, are you using the `KeepAliveUserStream` call? If not Binance will stop sending updates.

**Comment by NektoDron** [comment]
yes, I also confirm this. After several hours of operation, these events are not triggered, but after reconnect works fine. It can be tested by create/cancel order by web interface.

**Comment by NektoDron** [comment]
And another events (market trades, quotations and etc.) are received fine at this time.

**Comment by karloballa** [comment]
Thank you for answers. 
I'll try to use the KeepAliveUserStream method. To be honest, I tried to find it in the class BinanceSocketClient, and now that you mentioned it, I see that it is actually in the BinanceClient class. @NektoDron I did not understand your answer. Does the calling of the KeepAliveUserStream method solve the problem or not?

**Comment by NektoDron** [comment]
Haven't test it yet.. Sorry, I inattentively read the decision above.

**Comment by NektoDron** [comment]
I've tested it and KeepAliveUserStream  works fine.

**Comment by JKorf** [comment]
@karloballa I understand you'd expect to find it there, but it's a REST call, so it's not part of the socket client. Ask Binance why they made it this way ;)
