### ISSUE TITLE
withdrawFee.html not exist any more

### ISSUE THREAD

**Issue by m-rakic** [JKorf/Binance.Net#171]
Seams this endpoint is changed to tradeFee.html. The method "GetWithdrawalFee" gives 404.

see:
https://github.com/binance-exchange/binance-official-api-docs/blob/master/wapi-api.md

**Comment by JKorf** [comment]
Hi, thanks for the notice. The TradeFee is actaully a new endpoint, the withdrawal fee is not in the GetAssetDetails call.
