### ISSUE TITLE
WebRequest  Timeout

### ISSUE THREAD

**Issue by nikkozp** [JKorf/Binance.Net#172]
Hello ;)
WebRequest can cause for the requests to never complete.
I use it but it doesn't help:

```
public class MyBinanceClient : BinanceClient
    {
     public MyBinanceClient() : base(new BinanceClientOptions
            {
                AutoTimestamp = true,
                AutoTimestampRecalculationInterval = TimeSpan.FromMinutes(1),
                RequestTimeout = TimeSpan.FromMilliseconds(500),
            })
        {
        }
    public void TestMethod()
     {
        while (true)
         {
         //some code
          var BinanceData = base.GetAllBookPrices(); // here can waiting infinity time
         }
     }
}
```
this happens after a few hours of work.

Am I using timeout correctly?

**Comment by JKorf** [comment]
Hi, I can't reproduce this issue, however I've had reports earlier that sometimes calls freeze indefinately. Could you maybe try to see where in the library the call gets stuck?

**Comment by nikkozp** [comment]
Yeah, okay,I'll try check the library.
I also noticed that along with this there was a very common error `-1021: Timestamp for this request was 1000ms ahead of the server's time.`

**Comment by gensleralexander** [comment]
> I also noticed that along with this there was a very common error `-1021: Timestamp for this request was 1000ms ahead of the server's time.`

I also get this error. However I only get it, when using your code on my Raspberry Pi Project (Windows 10 IoT Core). When I use it on my normal machine the code executes fine.
Both use the windows ntp-server time.windows.com. Is this an issue on Binance-side or on mine?

**Comment by JKorf** [comment]
I've adjusted the timestamp calculation, can you try the latest version?
