### ISSUE TITLE
Add RateLimiter based on Weight

### ISSUE THREAD

**Issue by nikkozp** [JKorf/Binance.Net#174]
Hey. Noticed that you have a RateLimit which is responsible for requests per second.

Binance uses Weight in its queries. Do you have plans to add RateLimitBehaviour with Weight?

**Comment by JKorf** [comment]
Hi, I might add this add some point, but I'm currently busy with some other stuff. I'll keep this issue open so I won't forget it.

**Comment by nikkozp** [comment]
Thanks.
Want to leave their wishes:
1. Ability to set HighPriority for the request to work without delay, but not exceed the Weight. Globally and for each request separately.

**Comment by pyerpl** [comment]
Also thanks
 it will be very useful for me also (weighted + priority)

**Comment by MarkusGalant** [comment]
> Thanks.
> Want to leave their wishes:
> 
> 1. Ability to set HighPriority for the request to work without delay, but not exceed the Weight. Globally and for each request separately.

Maybe we have delayed because every  Api call check server time by Api call.

**Comment by JKorf** [comment]
The latest versions have a refactored rate limiting system, and a default rate limiter applied for the client. With this the weight of requests to the Binance API have been added. As for a `priority` request, this is not something I could easily add in. I would suggest working around this by creating a new client without rate limiter and using that for priority requests while maybe lowering the rate limit on the normal client.
