### ISSUE TITLE
Timestamp 1000ms ahead while using AutoTimestamp

### ISSUE THREAD

**Issue by gensleralexander** [JKorf/Binance.Net#175]
Hello and thanks for this awesome API implementation.

I get the 1021 error with my timestamp being ahead 1000ms, although I am using the AutoTimestamp-Feature. My project runs on a Raspberry Pi 3 with Windows 10 IoT Core. When I run the project with my normal machine no error appears.
Any advice on how to fix this?

**Comment by JKorf** [comment]
Hi, can try the latest version 4.0.5? I tried to make the timestamp calculation a bit more robust since more people were reporting this issue.

**Comment by Cooksauce** [comment]
Hi @JKorf 

I'm having the same issue. I believe the problem is in BinanceClient.cs => Line: 196

I'm getting log message:
"2019/01/10 02:06:43:773 | Info | Time offset within 1 seconds (-1481.4537ms), no adjustment needed"

Notice the negative value.

So line 196 should be:
var offset =  Math.Abs((result.Data.ServerTime - localTime).TotalMilliseconds);

**Comment by JKorf** [comment]
Hi, you're right. This issue is fixed in version 4.0.6 which should be available in a few minutes.

**Comment by gensleralexander** [comment]
> Hi, you're right. This issue is fixed in version 4.0.6 which should be available in a few minutes.

Hey @JKorf
with version 4.0.6 my program stopped working completly both on Raspi and my workstation.
When I use
client.GetAccountInfo()
it gets caught in a loop or something similar as it never finish this line.

When trying to debug step by step it stops in XamlTypeInfo.g.cs at line 403:
override public object ActivateInstance()
{
return Activator();
}

where it says can't find 'StandardInterfaces.cs not found'

**Comment by gensleralexander** [comment]
> It works fine for me, could you make sure you're using version 4.0.6 and also have the CryptoExchange.Net package version 2.0.7?

Both package versions are correct. However the problem fixed itself. Probably a bug in the visual studio code, after I updated to the most current version everything works fine (on both, raspi and workstation)
