### ISSUE TITLE
Can't Reconnect

### ISSUE THREAD

**Issue by xoxubepeso** [JKorf/Binance.Net#177]
2019/01/16 14:02:30:724 | Info | Socket 1 error: System.IO.IOException: Unable to read data from the transport connection: An established connection was aborted by the software in your host machine. ---> System.Net.Sockets.SocketException: An established connection was aborted by the software in your host machine
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.Security._SslStream.EndRead(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.EndRead(IAsyncResult asyncResult)
   at SuperSocket.ClientEngine.AuthenticatedStreamTcpSession.OnDataRead(IAsyncResult result)
2019/01/16 14:02:30:728 | Info | Socket 1 Connection lost, will try to reconnect
2019/01/16 14:02:35:734 | Debug | Socket 1 resetting
2019/01/16 14:02:35:734 | Debug | Socket 1 connecting
2019/01/16 14:02:35:736 | Info | Socket 1 error: System.Net.Sockets.SocketException (0x80004005): No such host is known
2019/01/16 14:02:35:738 | Debug | Socket 1 connection failed, state: Closed
2019/01/16 14:02:35:743 | Debug | Socket 1 failed to reconnect

**Comment by JKorf** [comment]
Hi, either there is no (stable) internet connection from your machine or the server is/was offline. Probably the first one. It should keep retrying until a connection could be made to the server again though.

**Comment by xoxubepeso** [comment]
**When I manually disconnect from internet it gives me this error**
2019/01/16 14:02:30:724 | Info | Socket 1 error: System.IO.IOException: Unable to read data from the transport connection: An established connection was aborted by the software in your host machine. ---> System.Net.Sockets.SocketException: An established connection was aborted by the software in your host machine
at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
--- End of inner exception stack trace ---
at System.Net.Security._SslStream.EndRead(IAsyncResult asyncResult)
at System.Net.Security.SslStream.EndRead(IAsyncResult asyncResult)
at SuperSocket.ClientEngine.AuthenticatedStreamTcpSession.OnDataRead(IAsyncResult result)
2019/01/16 14:02:30:728 | Info | Socket 1 Connection lost, will try to reconnect
2019/01/16 14:02:35:734 | Debug | Socket 1 resetting
2019/01/16 14:02:35:734 | Debug | Socket 1 connecting

**After when I connect to internet it gives this one**
2019/01/16 14:02:35:736 | Info | Socket 1 error: System.Net.Sockets.SocketException (0x80004005): No such host is known
2019/01/16 14:02:35:738 | Debug | Socket 1 connection failed, state: Closed
2019/01/16 14:02:35:743 | Debug | Socket 1 failed to reconnect

**and nothing else**

**Comment by JKorf** [comment]
Are you using the latest version?

**Comment by JKorf** [comment]
Hi, I found the issue, could you try to update CryptoExchange.Net to version 2.0.8? It is available in a few minutes and should fix the problem.

**Comment by xoxubepeso** [comment]
Perfect. Thank you!!!
