### ISSUE TITLE
Hi question not issue.

### ISSUE THREAD

**Issue by colingresty** [JKorf/Binance.Net#18]
Hi is there a LOT_SIZE calculator method in Binance.net?

**Comment by JKorf** [comment]
Hi, currently there is not. What would you expect if this?

**Comment by colingresty** [comment]
Hi, well when i send a quantity in a buy order, the quantity has to meet the LOT_SIZE filter on binance, or i get the following error,  -1013 "Filter failure: LOT_SIZE"
unless i am wrong , the quantity has to meet the requirements below.
I think other versions of this type of library (ccxt for example) have a function to convert your quantity to one that is divisible by "stepSize" .

This is from the Binance API documentation:

LOT_SIZE
The LOT_SIZE filter defines the quantity (aka "lots" in auction terms) rules for a symbol. There are 3 parts:

minQty defines the minimum quantity/icebergQty allowed.
maxQty defines the maximum quantity/icebergQty allowed.
stepSize defines the intervals that a quantity/icebergQty can be increased/decreased by.

In order to pass the lot size, the following must be true for quantity/icebergQty:
quantity >= minQty
quantity <= maxQty
(quantity-minQty) % stepSize == 0
/exchangeInfo format:

  {
    "filterType": "LOT_SIZE",
    "minQty": "0.00100000",
    "maxQty": "100000.00000000",
    "stepSize": "0.00100000"
  }

**Comment by JKorf** [comment]
I could add toggle-able functionality like this, where the library automatically complies to the ExchangeInfo filter rules, and return an error or auto adjust the parameters to comply. Would that be helpful to you?

**Comment by colingresty** [comment]
That would be awesome thank you 👍


Sent from Yahoo Mail for iPhone


On Wednesday, January 24, 2018, 09:56, Jan Korf <notifications@github.com> wrote:


I could add toggle-able functionality like this, where the library automatically complies to the ExchangeInfo filter rules, and return an error or auto adjust the parameters to comply. Would that be helpful to you?

**Comment by JKorf** [comment]
Hi, I've just pushed a new version in which BinanceClient contains a `TradeRulesBehaviour`. Setting this to ThrowError will return an error if the order doesn't comply. Setting it to AutoComply automatically complies the parameters to the rules (min/max price and quantity, and the step/tick sizes).

For manual usage there are also Clamp functions in the `BinanceHelpers` class which you can use to comply to the trading rules.

**Comment by colingresty** [comment]
Thanks JanDo you have a patreon page?


Sent from Yahoo Mail for iPhone


On Wednesday, January 24, 2018, 13:00, Jan Korf <notifications@github.com> wrote:


Hi, I've just pushed a new version in which BinanceClient contains a TradeRulesBehaviour. Setting this to ThrowError will return an error if the order doesn't comply. Setting it to AutoComply automatically complies the parameters to the rules (min/max price and quantity, and the step/tick sizes).

For manual usage there are also Clamp functions in the BinanceHelpers class which you can use to comply to the trading rules.

**Comment by JKorf** [comment]
After having to google what Patreon was, I´ve come to the conclusion that sadly I do not
