### ISSUE TITLE
error in GetAccountInfoAsync

### ISSUE THREAD

**Issue by mtad2002** [JKorf/Binance.Net#180]
when getting accountinfo using GetAccountInfoAsync 

it always return true for CanDeposit,CanTrade,CanWithdraw property of  BinanceAccountInfo object.

i only set Readinfo in binance website.

**Comment by JKorf** [comment]
Hi can you turn debug logging on (set LogVerbosity to LogVerbosity.Debug in the options) and check what the Binance API returns? It should be parsed correctly according to the documentation

**Comment by JKorf** [comment]
Seems like the response you get from the Binance server is not aligned with what you would expect based on your settings. It's not a Binance.Net issue though, you should probably contact Binance itself for this.

**Comment by nikkozp** [comment]
It's not what you think.
Binance assumes that you are not banned.

Note that there is no Deposit in Option, and there is one in the API.

**Comment by JKorf** [comment]
Closing this as it's not an issue related to the wrapper
