### ISSUE TITLE
Sub Account Support?

### ISSUE THREAD

**Issue by kingchenc** [JKorf/Binance.Net#183]
Hi Jkorf,

There are some Updates for Sub Accounts in the Api! Can you please add them? thank you

https://github.com/binance-exchange/binance-official-api-docs/blob/master/wapi-api.md#query-sub-account-listfor-master-account

https://github.com/binance-exchange/binance-official-api-docs/blob/master/wapi-api.md#query-sub-account-transfer-historyfor-master-account

https://github.com/binance-exchange/binance-official-api-docs/blob/master/wapi-api.md#sub-account-transferfor-master-account

and here another indicator/trigger/bans update (not sub accs)

https://support.binance.com/hc/en-us/articles/115003235691

**Comment by JKorf** [comment]
Hi, I've added this in release 4.0.8, should be available in a few minutes.
