### ISSUE TITLE
cannot install 

### ISSUE THREAD

**Issue by ramyarrk** [JKorf/Binance.Net#184]
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'Binance.Net 4.0.7'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0

**Comment by JKorf** [comment]
You'll need to update your visual studio / nuget client

**Comment by ramyarrk** [comment]
tnx problem solved.
