### ISSUE TITLE
Prevent Websocket - Timestamp for this request is outside of the recvWindow.

### ISSUE THREAD

**Issue by kingchenc** [JKorf/Binance.Net#185]
Hello,
My log yesterday was full spammed of the 1021 error ( 3h in row was the error, and after the 3h the bug/issue was gone).. how can i prevent/Fix this bug/issue? i was only using userstream and a websocket for ticker, and my internet connection works 100%, i know we can use  AutoTimestamp = true for the BinanceClient, but how for BinanceSocketClient? thanks :* 

Affects this bug/issue the Websocketstream or the Userstream or both?

2019.02.05 20:31:14:211 | Warning | Server returned an error: {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}

**............ 3h later..** 

2019.02.05 23:28:04:156 | Warning | Server returned an error: {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}
2019.02.05 23:28:04:592 | Warning | Server returned an error: {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}
2019.02.05 23:28:05:023 | Warning | Server returned an error: {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}
2019.02.05 23:28:05:442 | Warning | Server returned an error: {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}
2019.02.05 23:28:06:383 | Warning | Server returned an error: {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}
2019.02.05 23:28:07:024 | Info | Time offset within 1 seconds (255.4257ms), no adjustment needed
2019.02.05 23:28:07:274 | Warning | Server returned an error: {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}
2019.02.05 23:28:07:948 | Warning | Socket 1 message processing slow (1396ms), consider offloading data handling to another thread. Data from this socket may arrive late or not at all if message processing is continuously slow.
2019.02.05 23:28:08:686 | Warning | Server returned an error: {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}
2019.02.05 23:28:09:123 | Warning | Server returned an error: {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}
2019.02.05 23:28:10:026 | Warning | Server returned an error: {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}
2019.02.05 23:28:10:458 | Warning | Server returned an error: {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}
2019.02.05 23:29:51:599 | Warning | Server returned an error: {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}
2019.02.05 23:29:52:033 | Info | Time offset within 1 seconds (206.4122ms), no adjustment needed
2019.02.05 23:58:08:430 | Info | Time offset within 1 seconds (298.9179ms), no adjustment needed
2019.02.05 23:58:09:444 | Warning | Socket 1 message processing slow (807ms), consider offloading data handling to another thread. Data from this socket may arrive late or not at all if message processing is continuously slow.
2019.02.06 00:28:09:962 | Info | Time offset within 1 seconds (377.7157ms), no adjustment needed
2019.02.06 00:58:10:783 | Info | Time offset within 1 seconds (465.6516ms), no adjustment needed
2019.02.06 01:28:11:602 | Info | Time offset within 1 seconds (558.9821ms), no adjustment needed
2019.02.06 01:28:11:885 | Warning | Socket 1 message processing slow (582ms), consider offloading data handling to another thread. Data from this socket may arrive late or not at all if message processing is continuously slow.
2019.02.06 01:58:12:427 | Info | Time offset within 1 seconds (650.9316ms), no adjustment needed
2019.02.06 02:28:13:266 | Info | Time offset within 1 seconds (730.0969ms), no adjustment needed
2019.02.06 02:28:14:202 | Warning | Socket 1 message processing slow (1140ms), consider offloading data handling to another thread. Data from this socket may arrive late or not at all if message processing is continuously slow.
2019.02.06 02:58:14:776 | Info | Time offset within 1 seconds (806.4122ms), no adjustment needed
2019.02.06 02:58:15:081 | Warning | Socket 1 message processing slow (668ms), consider offloading data handling to another thread. Data from this socket may arrive late or not at all if message processing is continuously slow.
2019.02.06 03:28:15:595 | Info | Time offset within 1 seconds (891.4041ms), no adjustment needed
2019.02.06 03:58:16:497 | Info | Time offset within 1 seconds (979.6447ms), no adjustment needed
2019.02.06 04:28:17:364 | Info | Time offset set to -1064.2665ms

**Comment by JKorf** [comment]
Hi, the socket client doesn't use timestamps. It's basically a read only stream you connect to. I'm pretty sure these message were generated by the BinanceClient, not the BinanceSocketClient. It's weird though, since the time sync checks and says there is no adjustment needed, but the server replies with an error..
Can you check what you were doing at the time?

**Comment by kingchenc** [comment]
Thanks for reply :) Oh mhm, im confused now :o... I was only running a Websocket Ticker + Userstream  at the Time of the errors, nothing else.! So the Message comes from the Binance Client, thats mean, its not the Websocket for Ticker... That means for me, it can only be the userstream where generates the error...
then i think the userstream generates the errors with my mixxed code, or my code with BinanceClient/BinanceSocketClient is broken...

Is the Code something broken?

        async Task UserStream()
        {
            BinanceClient.SetDefaultOptions(new BinanceClientOptions()
            {
                ApiCredentials = new ApiCredentials(apikey, secretkey),
                AutoTimestamp = true
                //  LogVerbosity = LogVerbosity.Debug,
                //  LogWriters = new List<TextWriter> { Console.Out }
            });
            BinanceSocketClient.SetDefaultOptions(new BinanceSocketClientOptions()
            {
                ApiCredentials = new ApiCredentials(apikey, secretkey),
                //  LogVerbosity = LogVerbosity.Debug,
                //  LogWriters = new List<TextWriter> { Console.Out }
            });

            var socketClient = new BinanceSocketClient(new BinanceSocketClientOptions()
            {
                ApiCredentials = new ApiCredentials(apikey, secretkey),
            });

            string listenKey;
            using (var client = new BinanceClient()) listenKey = client.StartUserStream().Data;
            {
                var successAccount = socketClient.SubscribeToUserStreamAsync(listenKey, data =>
                {
    
                },
                    data =>
                    {

                    });
                while (true)
                {
                    await Task.Delay((1000 * 60) * 30);
                    using (var client = new BinanceClient())
                    {
                        var keepAliveResult = client.KeepAliveUserStream(listenKey);
                        if (!keepAliveResult.Success)
                        {
                        }
                    }
                }
            }
        }

Another Question: Can i Catch->Trigger from your lib outside the using'BinanceClient/Socket' a disconnect?

**Comment by HugoPeters1024** [comment]
Are you using debian? Installing the ntpd system time package seems to solve it for me: https://www.digitalocean.com/community/tutorials/how-to-set-up-time-synchronization-on-ubuntu-16-04 (scroll down)

**Comment by kingchenc** [comment]
Hi @HugoPeters1024 , thanks for u reply, but im using win 10 pro

**Comment by nikkozp** [comment]
Hi

When you use `using (var client = new BinanceClient())` need to use `BinanceClient.SetDefaultOptions` again.

**Comment by JKorf** [comment]
`edit: looks like this guys have the same problem -> [ccxt/ccxt#936 (comment)](https://github.com/ccxt/ccxt/issues/936#issuecomment-353774479) - kroitor mean, to sync the pc every 10-12 min instead of my sync time 9.2 hours... i think is worth a test :)`
That is not something I can help with, as it talks about how often the operating system time is synced, but you can surely see if it helps.

I don't see anything broken with your code, and I can't explain ( based on your code ) the issue you see. The logging shows something is requested every 500ms, but the code you posted doesn't do that.

Regarding the disconnect notification, you can use the result of a subscription to be notified of a lost connection:
````C#
 var a = socketClient.SubscribeToAllSymbolTicker(data => { Console.WriteLine("All ticker data: " + data[0].CurrentDayClosePrice); });
a.Data.ConnectionLost += () => Console.WriteLine("Connection lost");
a.Data.ConnectionRestored += (t) => Console.WriteLine("Connection restored");
````
There is no way to (in the wrapper) to detect that the computer has lost internet connection though.

**Comment by kingchenc** [comment]
> ```cs
>  var a = socketClient.SubscribeToAllSymbolTicker(data => { Console.WriteLine("All ticker data: " + data[0].CurrentDayClosePrice); });
> a.Data.ConnectionLost += () => Console.WriteLine("Connection lost");
> a.Data.ConnectionRestored += (t) => Console.WriteLine("Connection restored");
> ```

Nice, this is really helpfull, thanks Jkorf 👍 

I Think the Problem was rly the Sync Time(old sync time: 9,3h, new sync time 10 min)... Since 5 Days the Problem was gone and never happend again :) thx all for helping 👍

**Comment by JKorf** [comment]
Great, that's good to know. So this can be closed?

**Comment by kingchenc** [comment]
> Great, that's good to know. So this can be closed?

Sure Yes :)

**Comment by kingchenc** [comment]
Must reopen :( 
Looks like the the Main Warning  is gone, after few days.
`"Warning | Server returned an error: {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}"`

now i get this one.. mhmm (away after 1h..)

> 2019.02.20 13:58:58:390 | Info | Time offset set to -1024.8087ms                                                      
> 2019.02.20 14:00:01:008 | Warning | Server returned an error: {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."}
> 2019.02.20 15:58:53:502 | Warning | Server returned an error: {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."}
> 2019.02.20 15:59:17:846 | Info | Time offset set to -1367.8577ms
> 2019.02.20 15:59:58:329 | Info | Time offset set to -1372.2649ms


I'm now testing this... https://github.com/JKorf/Binance.Net/issues/147
`                AutoTimestampRecalculationInterval = TimeSpan.FromMinutes(10)
`

**Comment by HugoPeters1024** [comment]
I have had the same problem after two weeks of interrupted functionality. I've tried fancy internet time protocols to keep my system time up to date, without succes. I see two scenarios, binance has unscheduled moments of 'downtime' or the binance server has a wonky time source. In the first case I think it's best to keep trying with doubling intervals. In the seconds case one needs to find a way to sync up with the Binance server. Either way, I'm fairly sure the issue lies not within this code base as I've seen it across so many libraries.

**Comment by nikkozp** [comment]
I use the following code in my settings

```
new BinanceClientOptions
        {
            AutoTimestamp = false,
            RequestTimeout = TimeSpan.FromMilliseconds(500),
            TradeRulesBehaviour = TradeRulesBehaviour.None,
        }
```

To synchronize time, use a third-party program` SP Timesync ` to synchronize time on Windows. Always a time difference of +/- 15ms.  After that, I such errors do not occur, or very rarely.

The inspection is made every 10 seconds the request to Binance.

**Comment by HugoPeters1024** [comment]
Mm, 500 milliseconds may be a bit optimistic, the documentation defines a
healthy maximum of 5000

Op wo 20 feb. 2019 20:24 schreef Mykyta Kochetkov <notifications@github.com:

**Comment by nikkozp** [comment]
RequestTimeout and recvWindow are different things.

**Comment by kingchenc** [comment]
@nikkozp will testing now for few Days with SP TimeSync

**Comment by kingchenc** [comment]
@nikkozp
Thx buddy, i think i fixxed it with SP Timesync... since 5 Days i have no peoblems, thx for all help :)
