### ISSUE TITLE
Why does the last price take an extra 0?

### ISSUE THREAD

**Issue by redquantum** [JKorf/Binance.Net#186]
Hello Dear Friend,
Why does the last price take an extra 0?

binance normal price: 0,000245 but client.Get24HPrice method result lastprice: 0,0002450 ?? why?

How do I get the right price?

Thank you.

**Comment by nikkozp** [comment]
Hi
If u want to clamp price, can use static method  `BinanceHelpers.FloorPrice(tickSize, price);`

**Comment by redquantum** [comment]
hi, thank you for answer.
I'm not professional trader, and I dont know how get ticksize any method?
Would you like to send a sample?
I don't want to make a mistake on the price side when I order orders.

Thank you.

**Comment by JKorf** [comment]
Hi, I'm not sure why the Binance server returns that, it's not in my control. 
As @nikkozp suggested you can use the `BinanceHelpers.FloorPrice(tickSize, price);` function to get the correct price. The tickSize property can be retrieved using the `GetExchangeInfo` call:
````C#
var info = client.GetExchangeInfo();
var priceInfo = client.Get24HPrice("ETHBTC");
var tickSize = info.Data.Symbols.Single(s => s.Name == "ETHBTC").PriceFilter.TickSize;
var flooredPrice = BinanceHelpers.FloorPrice(tickSize, priceInfo.Data.LastPrice);
````

You can also set the `TradeRulesBehaviour` option to `AutoComply` to automatically do this for you when placing an order:
````C#
var client = new BinanceClient(new BinanceClientOptions()
{
      AutoTimestamp = true,
      TradeRulesBehaviour = TradeRulesBehaviour.AutoComply
});
````
