### ISSUE TITLE
Is there a limit of how many socket connections can be open at the same time?

### ISSUE THREAD

**Issue by cicaglisa80** [JKorf/Binance.Net#189]
I still have the problem with latest version of Binance.Net 4.0.7 and CryptoExchange.Net 2.0.9, I open like 200+ connections and it works for first 20-25mins then it just stops receiving data stream and I can't tell what's happening. There are no exceptions but this happened twice already today.

**Comment by cicaglisa80** [comment]
My bad looks like I forgot to add Console.Readline after opening connections and it would work for some time and then just close all the connections. Running it now again to see if things will change now.

**Comment by nikkozp** [comment]
Hey,
for fast and multi subscribe u need to use next methods:
`SubscribeToAllSymbolTicker(Action<BinanceStreamTick[]> onMessage)`
`SubscribeToDepthStreamAsync(string[] symbols, Action<BinanceOrderBook> onMessage)` and same methods with `string[] symbols` parametr.

example

>  var a = socketClient.SubscribeToAllSymbolTicker(data => 
> { 
>  foreach (var d in data)
>         Console.WriteLine($"{d.Symbol} {d.BestBidPrice}");
> });
> a.Data.ConnectionLost += () => Console.WriteLine("Connection lost");
> a.Data.ConnectionRestored += (t) => Console.WriteLine("Connection restored");

**Comment by cicaglisa80** [comment]
Hi Nikko,
Yeah make sense but I have a list of coins I have to remove from the tracking as I don't need every single pair so I don't think I can use Subscribe to all in my case.

**Comment by nikkozp** [comment]
For example you can subscribe to all BTC pairs. And black list pairs u can ignore `if (d.Symbol == "CMTBTC") continue;`

**Comment by JKorf** [comment]
@nikkozp is right, subscribing to all symbol ticker and ignoring the ones you don't need is a better solution for you I think

**Comment by cicaglisa80** [comment]
Right, I could try that. By ignoring you mean I'm still subscribed to all socket data but I just skip those updates?

**Comment by nikkozp** [comment]
Yes, just Binance sends you an array, and you already decide what data you need and what not

**Comment by cicaglisa80** [comment]
great thanks for your help guys will definitely do it this way then :)

**Comment by JKorf** [comment]
I assume you've gotten this working. If not let me know.

**Comment by cicaglisa80** [comment]
I think that was it thanks forgot to report as I was still running the test and it didn't break for days now.
