### ISSUE TITLE
Hi is this code working?

### ISSUE THREAD

**Issue by topproto** [JKorf/Binance.Net#19]
Hi again JKorf

Could you confirm the following code works

        private Binance.Net.Objects.BinanceStreamAccountInfo accountinfo;
        public Binance.Net.Objects.BinanceStreamAccountInfo AccountInfo
        {
            get
            {
                return accountinfo;
            }

            set
            {
                accountinfo = value;
            }
        }

                BinanceDefaults.SetDefaultApiCredentials(lblAPIKey.Text, lblSecret.Text);
                using (var client = new BinanceClient())
                using (var socketclient = new BinanceSocketClient())
                {
                    var successStart = client.StartUserStream();
                    var successAccount = socketclient.SubscribeToAccountUpdateStream(successStart.Data.ListenKey, (data) =>
                    {
                        AccountInfo = data; **<--- seems to skip this completely??**
                    });

                    socketclient.UnsubscribeFromAccountUpdateStream();
                }

**Comment by JKorf** [comment]
Hi,

Although the syntax is correct, this is not going to work. Basically you're subscribing to AccountInfo updates, defining what to do when such an update comes in, and then immediately unsubscribing from those updates again. Subscribing to the AccountUpdateStream is asynchronous and your code will continue after that call: 
````C#
using (var client = new BinanceClient())
            using (var socketclient = new BinanceSocketClient())
            {
                var successStart = client.StartUserStream();
                // Here you subscribe to updates
                var successAccount = socketclient.SubscribeToAccountUpdateStream(successStart.Data.ListenKey, (data) =>
                {
                    AccountInfo = data; // This only get's called when an account update actually comes in from the server
                });

                // Here you unsubscribe again
                socketclient.UnsubscribeFromAccountUpdateStream();
            }
````
Here's a quick example of what you'd want:
````C#
class Program
    {
        static async Task Main()
        {
            BinanceDefaults.SetDefaultApiCredentials(apikey, apisecret);
            var test = new Test();
            test.StartUpdates(); // <- subscribes you to the update stream
            Console.ReadLine();
            test.StopUpdates(); // <- unsubscribes you from the update stream
            Console.ReadLine();
        }

    }

    public class Test
    {
        private BinanceSocketClient socketClient;
        private string listenKey;

        public BinanceStreamAccountInfo AccountInfo { get; set; }

        public Test()
        {
            // create a persistent socket so it doesn't get garbage collected
            socketClient = new BinanceSocketClient();
        }

        public void StartUpdates()
        {
            using (var client = new BinanceClient())
                listenKey = client.StartUserStream().Data.ListenKey;

           // Subscribe to updates
            var success = socketClient.SubscribeToAccountUpdateStream(listenKey, data =>
            {
                AccountInfo = data;
                Console.WriteLine("Account info updated!");
            });

            Console.WriteLine("Subscribed to updates");
        }

        public void StopUpdates()
        {
            socketClient.UnsubscribeFromAccountUpdateStream();
            using (var client = new BinanceClient())
                client.StopUserStream(listenKey);
            Console.WriteLine("Stopped subscription");
        }
    }
````
You can test this by running the console application, wait for it to say `Subscribed to updates` and then placing or canceling an order on the Binance site. You should get an `Account info updated!` message after that.

**Comment by topproto** [comment]
Thanks JKorf, worked a treat!!
