### ISSUE TITLE
How to check http response code?

### ISSUE THREAD

**Issue by Deni35** [JKorf/Binance.Net#190]
I had write the following code and I just understand it has an error.
Problem is that `result.Error.Code` is binance code. But how to check http code? I didn't find it.

        public static async Task<long> GetPingAsync(IBinanceClient httpClient) {
            while (true) {
                var result = await httpClient.PingAsync().ConfigureAwait( false );
                if (result.TryGetData( out var data )) return data; // If success then return result. Else repeat request or throw exception.
            }
        }

        private static bool TryGetData<T>(this CallResult<T> result, out T data) {
            if (result.Success) {
                data = result.Data;
                return true;
            }
            if (result.IsError5xx()) {
                data = default;
                return false;
            }
            throw new Exception( result.Error.ToString() );
        }

        // Here is a bug !!!
        private static bool IsError5xx<T>(this CallResult<T> result) {
            // HTTP 5XX return codes are used for internal errors; the issue is on Binance's side. It is important to NOT treat this as a failure operation; the execution status is UNKNOWN and could have been a success.
            return !result.Success && result.Error.Code >= 500 && result.Error.Code <= 599; // todo: fix
        }

**Comment by nikkozp** [comment]
Hi.
On my observations
5хх -> `result.Error.Code = 5`
4xx -> `result.Error.Code = 4`
3xx -> `result.Error.Code = 3`

**Comment by Deni35** [comment]
If I understand right `result.Error.Code` should have those values
https://github.com/binance-exchange/binance-official-api-docs/blob/master/errors.md

**Comment by nikkozp** [comment]
Yes, but added static errors https://github.com/JKorf/CryptoExchange.Net/blob/master/CryptoExchange.Net/Objects/Error.cs

**Comment by Deni35** [comment]
You mean sub classes? 
Then when I should repeat? When CantConnectError and ServerError? 
What is WebError? And when is UnknownError happening?

**Comment by JKorf** [comment]
Hi, the error codes listed at https://github.com/JKorf/CryptoExchange.Net/blob/master/CryptoExchange.Net/Objects/Error.cs don't map to http status codes.
I've exposed the http status code for rest requests by changing the return type from `CallResult<T>` to `WebCallResult<T>` which has an extra ResponseStatusCode field which contains the http status code.
This is available in version 4.0.8 which should be on Nuget in a few minutes.

**Comment by Deni35** [comment]
[JKorf](/JKorf) Why PingAsync doesn't return JKorf?

**Comment by JKorf** [comment]
PingAsync is an overload with a base implementation in the RestClient base class in CryptoExchange.Net. It uses the C# ping implementation `ping.SendPingAsync(uri.Host)` which doesn't provide an HttpStatusCode in the result.

**Comment by Deni35** [comment]
A couple more questions.
- Why I shouldn't map to http status codes (ResponseStatusCode) ?
- When ResponseStatusCode is null? 
  Only when ```because no ApiCredentials were provided``` and ```failed because of rate limit``` ?

**Comment by Deni35** [comment]
Okey, I wrote the following code. Hope it should work right.

        public static async Task<DateTime> GetServerTimeAsync_(this IBinanceClient httpClient) {
            for (var i = 0; true; i++) {
                var result = await httpClient.GetServerTimeAsync().ConfigureAwait( false );
                if (result.Success) return result.Data;
                if (result.ShouldTryAgain( i )) continue;
                throw result.ToException();
            }
        }

        private static bool ShouldTryAgain<T>(this WebCallResult<T> result, int i) {
            if (i < 3 && !result.Success && result.Error.ShouldTryAgain()) {
                return true;
            }
            return false;
        }
        private static bool ShouldTryAgain(this Error error) {
            return
                error.Code == 1000 || // UNKNOWN
                error.Code == 1001 || // DISCONNECTED
                error.Code == 1006 || // UNEXPECTED_RESP
                error.Code == 1007; // TIMEOUT
        }

**Comment by JKorf** [comment]
You can use the http status codes, however the binance error codes are generally more specific as to what the problem is.
ResponseStatusCode is null when the request was either never send or there was no response from the server.
