### ISSUE TITLE
Updating API 2019-03-12

### ISSUE THREAD

**Issue by nikkozp** [JKorf/Binance.Net#194]
Hi :)

https://github.com/binance-exchange/binance-official-api-docs/blob/master/CHANGELOG.md#2019-03-12

**Comment by nikkozp** [comment]
@JKorf Can u add `X-MBX-USED-WEIGHT header added to Rest API responses`?  🙏

**Comment by JKorf** [comment]
Hi, I've added the response headers to the WebCallResult object. I also added a helper method to quickly retrieve the used weight header:
`var weight = client.GetAllOrders("ETHBTC").ResponseHeaders.UsedWeight();` (obviously you should check for errors)

**Comment by nikkozp** [comment]
Thx man, i'll check this
