### ISSUE TITLE
Can I disable auto reconnection?

### ISSUE THREAD

**Issue by Deni35** [JKorf/Binance.Net#196]
I'd like to handle all problems and errors manually. So, I want to throw exception when connection is lost instead of auto reconnection.
I found ```BaseSocket.ShouldReconnect``` property but it looks like I can not access it from my code. 
Could you put this property in ```IBinanceSocketClient``` or ```BinanceSocketClientOptions```?
Also I not found where ```BaseSocket.Timeout``` is assigned.

**Comment by JKorf** [comment]
Hi, I've added this option in the latest version, available in a few minutes. You could also subscribe to the ConnectionLost/ConnectionRestored events in the Subscribe result:
````C#
            var subResult = socketClient.SubscribeToAllSymbolTicker(data => { Console.WriteLine("All ticker data: " + data[0].CurrentDayClosePrice); });
            subResult.Data.ConnectionLost += () => Console.WriteLine("Lost");
            subResult.Data.ConnectionRestored += (e) => Console.WriteLine("Restored");
````
