### ISSUE TITLE
Weird Error with GetDepositHistory and GetWithdrawHistory

### ISSUE THREAD

**Issue by burakoner** [JKorf/Binance.Net#197]
Hi JKorf,

I'm using your nuget packages for  1 year. As I said before there were some weird problems in GetDepositHistory() and GetWithdrawHistory(). I downloaded your codes and found problem. In some cases (I think users disabled their 2FA after creating API credentials) Binance doesnt send error code. It sends only error message as in picture attached. I think you need to add a check point for this problem.

Have a nice day
![Screenshot_1](https://user-images.githubusercontent.com/21169085/54483607-143ec480-4867-11e9-9618-a0a68cf34b93.png)

**Comment by burakoner** [comment]
Something like below


`

        protected override Error ParseErrorResponse(JToken error)
        {
            if(!error.HasValues)
                return new ServerError(error.ToString());

            if (error["msg"] == null && error["code"] == null)
                return new ServerError(error.ToString());

            if (error["msg"] != null && error["code"] == null)
                return new ServerError((string)error["msg"]);

            return new ServerError((int)error["code"], (string)error["msg"]);
        }

`

**Comment by JKorf** [comment]
Hi Burak, fixed this in the latest version which should be available in a few minutes.

**Comment by burakoner** [comment]
Thank you very much @JKorf
