### ISSUE TITLE
BinanceSymbolPercentPriceFilter.AveragePriceMinutes should be int

### ISSUE THREAD

**Issue by Deni35** [JKorf/Binance.Net#198]
```BinanceSymbolMinNotionalFilter.AveragePriceMinutes``` is ```int```.
```BinanceSymbolPercentPriceFilter.AveragePriceMinutes``` is ```decimal```.
I guess minutes should be ```int```.
Also it looks like you forget to implement ```BinanceExchangeInfo.ExchangeFilters```.

**Comment by JKorf** [comment]
Fixed in the latest version.
I know `BinanceExchangeInfo.ExchangeFilters` isn't implemented, but I've never seen that contain any data, so I'm not sure what that should contain.
