### ISSUE TITLE
Day to day orders consolodated

### ISSUE THREAD

**Issue by topproto** [JKorf/Binance.Net#20]
![image](https://user-images.githubusercontent.com/35653813/35416664-d7481b80-0221-11e8-985a-43140dcd0330.png)

Hi JKorf

Is this behaviour expected?

I am using your app and it looks like its consolidated the orders into days with no way to break them out into individual sell/buy orders. The bottom image is from the binance app.

**Comment by JKorf** [comment]
Hi, it shouldn't aggregate the orders. I think what you see in the Binance app are the individual trades which filled the order, while the example shows the actual orders.

The two 2 sells you see in Binance are for the same order, just 2 different orders filled it. Same for the buy order. You can get the fills by doing a GetMyTrades request.

**Comment by topproto** [comment]
Thanks JKorf.

Turns out your information as usual is spot on.
I had to do a little conversion on the values returned to mimic the above screenshot.

                string ordertype = "";
                decimal ordertotal = 0;
                if(order.IsBuyer)
                {
                    ordertype = "Buy";
                }
                else
                {
                    ordertype = "Sell";
                }

                ordertotal = order.Quantity * order.Price;
