### ISSUE TITLE
what makes SubscribeToAllSymbolTickerAsync delayed?

### ISSUE THREAD

**Issue by vbwriter** [JKorf/Binance.Net#200]
Am i doing something wrong?

in form
`aAllTickPriceTask = BCSocket.SubscribeToAllSymbolTickerAsync(Sub(bst) HandleStreamAllTickTimer(bst))
        AllTickPriceTask = Await aAllTickPriceTask`

sub
`Private Async Sub HandleStreamAllTickTimer(bst As Binance.Net.Objects.BinanceStreamTick())

        For Each el In bst
            Try
                'Dim X = listaDeCandles.Find(Function(xx) xx.Par.ToUpper = el.Symbol.ToUpper And xx.TempoGrafico = "1h")
                'If Not X Is Nothing Then
                '    If X.ListaCandles.Last.closeprice <> el.CurrentDayClosePrice Then
                '        X.ListaCandles.Last.closeprice = el.CurrentDayClosePrice
                '    End If
                'End If
                If el.Symbol.Substring(el.Symbol.Length - 3) = "BTC" Or el.Symbol = "BTCUSDT" Then 'adicionei essa linha para poder ignorar o resto
                    Dim y = listaPrecos.Find(Function(yy) yy.Par.ToUpper = el.Symbol.ToUpper)
                    If Not y Is Nothing Then
                        If Not CDec(y.Price) = CDec(el.CurrentDayClosePrice) Then
                            If y.dtTick < el.EventTime Then
                                y.Price = el.CurrentDayClosePrice
                                y.dtTick = el.EventTime
                                y.Volume = el.TotalTradedQuoteAssetVolume
                            Else
                                System.Console.WriteLine(y.Par & " y.dtick " & y.dtTick & " > " & el.EventTime & " why ?")
                            End If
                        End If
                    Else
                        Dim sMan As String = ""
                        Dim sAlt As String = ""
                        Select Case el.Symbol.Substring(el.Symbol.Length - 3)
                            Case "BTC"
                                sMan = "BTC"
                                sAlt = el.Symbol.Replace("BTC", "")
                            Case "BNB"
                                sMan = "BNB"
                                sAlt = el.Symbol.Replace("BNB", "")
                            Case "ETH"
                                sMan = "ETH"
                                sAlt = el.Symbol.Replace("ETH", "")
                            Case "SDT"
                                sMan = "USDT"
                                sAlt = el.Symbol.Replace("USDT", "")
                            Case "SDC"
                                sMan = "USDC"
                                sAlt = el.Symbol.Replace("USDC", "")
                            Case "PAX"
                                sMan = "PAX"
                                sAlt = el.Symbol.Replace("PAX", "")
                            Case "TUSD"
                                sMan = "TUSD"
                                sAlt = el.Symbol.Replace("TUSD", "")
                        End Select
                        Dim nPrice As New PTick(el.Symbol.ToUpper, sMan, sAlt, el.CurrentDayClosePrice, el.EventTime, el.TotalTradedQuoteAssetVolume)
                        listaPrecos.Add(nPrice)
                    End If
                End If
            Catch ex As Exception
                System.Console.WriteLine( ex.Message)
            End Try
        Next
        Try
            Me.Invoke(Sub() lblPrecoUpdate.Text = bst(0).EventTime)
        Catch ex As Exception
        End Try
    End Sub`

but after sometime, the price get delayed, how is the best way to store prices ? any tips? or better restart the task after sometime (there is anyway to do this)? 

Thanks for you support.

**Comment by nikkozp** [comment]
Hi, I don't know much about `VB`, but I see a few comments

1. Use `ExchangeInfo `there you can easily find a pair by `BaseSymbol `and `QuoteSymbol`

2. Do not write a lot of code in the sockets, just add to the List. Then get the necessary information from another task or use delegates

**Comment by vbwriter** [comment]
> Hi, I don't know much about `VB`, but I see a few comments
> 
> 1. Use `ExchangeInfo `there you can easily find a pair by `BaseSymbol `and `QuoteSymbol`
> 2. Do not write a lot of code in the sockets, just add to the List. Then get the necessary information from another task or use delegates

ty, i have restarted the app yesterday, and now looking the app, the prices are updated, so i think, maybe de delay is happening from connections issues...
how you do in C#, if you need to close and open again BCSocket.SubscribeToAllSymbolTickerAsync ?

**Comment by nikkozp** [comment]
my code

```
var Ticker = ws.SubscribeToAllSymbolTicker(data =>
{
   try
   {
        foreach (var d in data)
        {
              if (!SymbolsInfo[d.Symbol].IsLoadInfo) //Blacklist
                    continue;
              SymbolsInfo[d.Symbol].Ticker = d;
         }
    }
    catch (Exception ex) { Logs?.Invoke(DateTime.Now, $"{System.Reflection.MethodBase.GetCurrentMethod().Name} {ex.ToString()}", LogType.CriticalErrors); }
 });

if (!Ticker.Success)
{
    ErrorHandling(Ticker.Error);
    goto startTicker;
}
Ticker.Data.ConnectionLost += () => Console.WriteLine("Connection lost");
Ticker.Data.ConnectionRestored += (t) => Console.WriteLine("Connection restored");
```

**Comment by vbwriter** [comment]
I have changed the code to
`Try
            For Each el In bst
                If Not NovaListaPrecos(el.Symbol).IsLoadInfo Then
                    Continue For
                Else
                    NovaListaPrecos(el.Symbol).Ticker = el
                End If
            Next
            Me.Invoke(Sub() lblPrecoUpdate.Text = bst(0).EventTime)
        Catch ex As Exception
        End Try
`

it works fine all day but now the ticker is delayed again.

**Comment by JKorf** [comment]
You probably shouldn't invoke an UI update for each symbol in every tick. Say you get +-200 symbols per update, and 1 update every second (I haven't checked if this is average or not, but I think this is pretty close). So your UI has to be invoked 200 times every seconds, which is too much.

You should either have a separate thread which handles the UI updating, or at least just have a single invoke updating all the labels.

**Comment by vbwriter** [comment]
Ty for support, i have removed the UI, and it delayed again. So i stop to use AllSymbol and now i'm using SubscribeToSymbolTicker. It's working aprox. 23hr and it's fine.

**Comment by vbwriter** [comment]
Two days and work fine. 2 Things are diferent.
1- using SubscribeToSymbolTicker (and only add the ticker i use 69 symbols).
2- you can only use SubscribeToSymbolTicker if you put api key and pass. The first way i'm not using api. Can this be the problem ?

**Comment by JKorf** [comment]
I'm not sure what you mean with `you can only use SubscribeToSymbolTicker if you put api key and pass. The first way i'm not using api. `?

**Comment by JKorf** [comment]
Closing, if you still need help with something let me know.
