### ISSUE TITLE
Getting actual minute aggregates every minute rather than second.

### ISSUE THREAD

**Issue by codebeaulieu** [JKorf/Binance.Net#202]
I'm attempting to gather minute aggregates by using the following subscription:

```
 var successKline = _socketClient.SubscribeToKlineStream(symbols.ToArray(), KlineInterval.OneMinute, (data) =>
{
    // twerk
});
```

I understand that this fires every second, but that doesn't make sense to me and I was hoping someone could shed some light on why it works this way.

My expectation is when using `KlineInterval.OneMinute`, that I would receive **One Minute** aggregates every minute rather than every second.

Please help me to understand why this makes sense to fire every second. Also, how can I receive minute aggregates every minute? 

I could accumulate my own minute aggregate, but then whats the point of asking for `KlineInterval.OneMinute`?

**Comment by nikkozp** [comment]
Hi, u can use it

```
var successKline = _socketClient.SubscribeToKlineStream(symbols.ToArray(), KlineInterval.OneMinute, (data) =>
{
    if (data.Final)
    {
      // twerk
    }
});
```

**Comment by codebeaulieu** [comment]
@nikkozp Awesome, thank you for getting back to me so quickly. I'll give this a shot and kill this issue shortly.
