### ISSUE TITLE
Both BinanceClient and BinanceSocketClient doesnt implement IDisposable

### ISSUE THREAD

**Issue by agecas** [JKorf/Binance.Net#208]
Both BinanceClient and BinanceSocketClient doesnt implement IDisposable. CryptoExchange.Net.BaseClient does implement this interface, however if we are using DI and injecting the client or its factory using an interface, it is not possible to dispose of the client via a USING statement, since IDisposable is only available on the CONCRETE implementation of both classes. Perhaps the IDisposable interface implementation should be moved from the base class to each of the CLIENT interfaces for every exchange.

**Comment by JKorf** [comment]
I've added the IDisposable interface to the base interfaces, so it should work for you with the latest version
