### ISSUE TITLE
BinanceStreamAccountInfo hasn't UpdateTime

### ISSUE THREAD

**Issue by Deni35** [JKorf/Binance.Net#209]
`BinanceStreamAccountInfo` hasn't `UpdateTime` property.
`"u": 1499405658848,           // Time of last account update`
https://github.com/binance-exchange/binance-official-api-docs/blob/master/user-data-stream.md

**Comment by Deni35** [comment]
Also `BinanceCanceledOrder` hasn't `transactTime`.

**Comment by nikkozp** [comment]
Since update 13-nov-2018 Binance dont return transactTime

```
2019-04-08 09:33:43:421 | Debug | Returned data: {
  "symbol": "BNBBTC",
  "origClientOrderId": "Zd8bsLdy5a1DPR7CggtD1j",
  "orderId": 138459719,
  "clientOrderId": "CQKpiRYmVLEZIedoO954Wz",
  "price": "0.00300000",
  "origQty": "1.00000000",
  "executedQty": "0.00000000",
  "cummulativeQuoteQty": "0.00000000",
  "status": "CANCELED",
  "timeInForce": "GTC",
  "type": "LIMIT",
  "side": "BUY"
}
```

**Comment by JKorf** [comment]
Time property for `BinanceStreamAccountInfo` has been added in the latest version
