### ISSUE TITLE
Api request

### ISSUE THREAD

**Issue by Kudwig** [JKorf/Binance.Net#214]
Good day Jan
I know i'm off topic, but was unsure on how to contact you otherwise
i'm very grateful for all the time you put in in creating the exchange api's.
If you got time, can you look at creating one for https://coinfalcon.com.
they are a , nice exchange as well, and i've been with them for about 2 years.
regards
Ludwig

**Comment by JKorf** [comment]
Hi, thanks for your request. I've added a list of planned/requested exchanges on https://github.com/JKorf/CryptoExchange.Net and added CoinFalcon to that. Note that I can't give a time indication on when I might get to it.
