### ISSUE TITLE
System.DivideByZeroException: 'Attempted to divide by zero.'

### ISSUE THREAD

**Issue by wofezwofez** [JKorf/Binance.Net#215]
Hello Jan. I'm getting some error.

**Code Init Client**
clientOptions = New BinanceClientOptions
ClientOptions.AutoTimestamp = True
clientOptions.ApiCredentials = New CryptoExchange.Net.Authentication.ApiCredentials(key, secret)
clientOptions.TradeRulesBehaviour = TradeRulesBehaviour.AutoComply

**Code Place Order**
client.PlaceTestOrderAsync(Symbol, OrderSide.Buy, OrderType.Market, quantity)
client = New BinanceClient(clientOptions)

I' getting this Error.
_2019/05/18 08:56:06:532 | Info | Time offset between 0 and 500ms (28.193ms), no adjustment needed
2019/05/18 08:56:09:123 | Info | Trade rules updated
Exception thrown: 'System.DivideByZeroException' in mscorlib.dll
Exception thrown: 'System.DivideByZeroException' in mscorlib.dll
Exception thrown: 'System.DivideByZeroException' in mscorlib.dll
Exception thrown: 'System.DivideByZeroException' in mscorlib.dll
An unhandled exception of type 'System.DivideByZeroException' occurred in mscorlib.dll
Attempted to divide by zero._

But when I remove this line ( clientOptions.TradeRulesBehaviour = TradeRulesBehaviour.AutoComply )
Everything works perfect.

**Comment by burakoner** [comment]
I get same error for 3-4 days. I found cause of this in ClampQuantity method and added a line to check stepSize. My way is not true way for long term, but it worked for me.

public static decimal ClampQuantity(decimal minQuantity, decimal maxQuantity, decimal stepSize, decimal quantity)
        {
            quantity = Math.Min(maxQuantity, quantity);
            quantity = Math.Max(minQuantity, quantity);
            if (stepSize == 0) return quantity;
            quantity -= quantity % stepSize;
            quantity = Floor(quantity);
            return quantity;
        }

**Comment by JKorf** [comment]
Hi, so you're saying that the stepSize can be 0? When I'm currently looking at the filters there is no symbol which has a stepSize of 0. Do you know when this can happen?

**Comment by swAucxis** [comment]
I have the same error when calling the PlaceOrder function with the following parameters.
PlaceOrder("BNBBTC", OrderSide.Buy, OrderType.Market, 0.5m)

**Comment by JKorf** [comment]
Ah I see. The problem is when the MarketLotSize filter doesn't specify a step size. I've pushed a fix for this, should be available in a few minutes.

**Comment by wofezwofez** [comment]
thank you. works for me
