### ISSUE TITLE
WebSocket OrderDetailUpdateAsync.FilledPartially

### ISSUE THREAD

**Issue by philipp-troxler** [JKorf/Binance.Net#217]
I use theBinance.net Nuget with the WebSocket OrderDetailUpdateAsync.
I have a question about that. If the event 'FilledPartially' is executed each time the fill level of an order changes. Or is it executed only once at the end when an order is canceled and not the whole order is filled.

Regards

**Comment by JKorf** [comment]
Hi, sorry I'm not following. What `OrderDetailUpdateAsync` do you mean?

**Comment by philipp-troxler** [comment]
Sorry. I have copied the wrong code :-) 

```
var successOrderBook = socketClient.SubscribeToUserStreamAsync(listenKey, async (accountInfoUpdate) =>
{
    await AccountInfoUpdateAsync(accountId, accountInfoUpdate);
},
```

the events that are being triggered are not very clear to me

**Comment by philipp-troxler** [comment]
it is not my day. This is the right code:

```
async (orderInfoUpdate) =>
{
 await OrderDetailUpdateAsync(accountId, orderInfoUpdate);
 })
```

**Comment by JKorf** [comment]
If I recall correctly it sends an update every time the order fill amount changes, where the status of the order will be PartiallyFilled. When canceling the status will change to Cancelled even when there was a partial fill.

**Comment by philipp-troxler** [comment]
Thank you very much
