### ISSUE TITLE
Add CancellationToken in each method

### ISSUE THREAD

**Issue by Deni35** [JKorf/Binance.Net#218]
Each HttpClient's method accepts CancellationToken to cancel request. But your API doesn't accept this parameter.

**Comment by Deni35** [comment]
I think I can use `Nito.AsyncEx.TaskExtensions.WaitAsync(this Task @this, CancellationToken cancellationToken)`. So it's not a big problem.

**Comment by JKorf** [comment]
I finally got around to adding this, from Binance.Net 5.0.0 (and CryptoExchange 3.0.0 in general) all requests have an optional CancellationToken parameter.
