### ISSUE TITLE
UnhandledException:  Newtonsoft.Json.JsonReaderException

### ISSUE THREAD

**Issue by NektoDron** [JKorf/Binance.Net#220]
17:55:06.38[73770]FATAL:UnhandledException: 
Newtonsoft.Json.JsonReaderException: Unterminated string. Expected delimiter: ". Path '[244].h', line 1, position 94403.
   в Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote) в /_/Src/Newtonsoft.Json/JsonTextReader.cs:строка 1119
   в Newtonsoft.Json.JsonTextReader.ParseProperty() в /_/Src/Newtonsoft.Json/JsonTextReader.cs:строка 1555
   в Newtonsoft.Json.Linq.JContainer.ReadContentFrom(JsonReader r, JsonLoadSettings settings) в /_/Src/Newtonsoft.Json/Linq/JContainer.cs:строка 853
   в Newtonsoft.Json.Linq.JContainer.ReadTokenFrom(JsonReader reader, JsonLoadSettings options) в /_/Src/Newtonsoft.Json/Linq/JContainer.cs:строка 736
   в Newtonsoft.Json.Linq.JArray.Load(JsonReader reader, JsonLoadSettings settings) в /_/Src/Newtonsoft.Json/Linq/JArray.cs:строка 140
   в Newtonsoft.Json.Linq.JToken.ReadFrom(JsonReader reader, JsonLoadSettings settings) в /_/Src/Newtonsoft.Json/Linq/JToken.cs:строка 2133
   в Newtonsoft.Json.Linq.JToken.Parse(String json, JsonLoadSettings settings) в /_/Src/Newtonsoft.Json/Linq/JToken.cs:строка 2183
   в CryptoExchange.Net.Sockets.SocketConnection.ProcessMessage(String data)
   в CryptoExchange.Net.Sockets.BaseSocket.Handle[T](List`1 handlers, T data)
   в CryptoExchange.Net.Sockets.BaseSocket.<Connect>b__80_3(Object o, MessageReceivedEventArgs s)
   в WebSocket4Net.WebSocket.OnDataReceived(Byte[] data, Int32 offset, Int32 length)
   в SuperSocket.ClientEngine.AuthenticatedStreamTcpSession.OnDataRead(IAsyncResult result)
   в System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   в System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   в System.Net.Security._SslStream.ProcessFrameBody(Int32 readBytes, Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   в System.Net.Security._SslStream.ReadFrameCallback(AsyncProtocolRequest asyncRequest)
   в System.Net.AsyncProtocolRequest.CompleteRequest(Int32 result)
   в System.Net.FixedSizeReader.CheckCompletionBeforeNextRead(Int32 bytes)
   в System.Net.FixedSizeReader.ReadCallback(IAsyncResult transportResult)
   в System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   в System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   в System.Net.ContextAwareResult.Complete(IntPtr userToken)
   в System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   в System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   в System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)

**Comment by NektoDron** [comment]
Binance.Net 4.0.13
CryptoExchange.Net 2.1.0

**Comment by JKorf** [comment]
Hm seems like some invalid json was received. Was this a single occurrence?

**Comment by NektoDron** [comment]
This happened once, but it causes a crash, because the exception is not processed.

**Comment by JKorf** [comment]
I added some check while parsing the json, will be in the next release of CryptoExchange.Net

**Comment by NektoDron** [comment]
With Binance.Net 4.0.16 and CryptoExchange.Net 2.1.3

10:37:36.12[161]FATAL:UnhandledException: 
Newtonsoft.Json.JsonReaderException: After parsing a value an unexpected character was encountered: e. Path 'data', line 1, position 35.
в Newtonsoft.Json.JsonTextReader.ParsePostValue(Boolean ignoreComments) в /_/Src/Newtonsoft.Json/JsonTextReader.cs:строка 1480
в Newtonsoft.Json.JsonTextReader.Read() в /_/Src/Newtonsoft.Json/JsonTextReader.cs:строка 426
в Newtonsoft.Json.Linq.JContainer.ReadContentFrom(JsonReader r, JsonLoadSettings settings) в /_/Src/Newtonsoft.Json/Linq/JContainer.cs:строка 853
в Newtonsoft.Json.Linq.JContainer.ReadTokenFrom(JsonReader reader, JsonLoadSettings options) в /_/Src/Newtonsoft.Json/Linq/JContainer.cs:строка 736
в Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings) в /_/Src/Newtonsoft.Json/Linq/JObject.cs:строка 424
в Newtonsoft.Json.Linq.JToken.ReadFrom(JsonReader reader, JsonLoadSettings settings) в /_/Src/Newtonsoft.Json/Linq/JToken.cs:строка 2131
в Newtonsoft.Json.Linq.JToken.Parse(String json, JsonLoadSettings settings) в /_/Src/Newtonsoft.Json/Linq/JToken.cs:строка 2183
в CryptoExchange.Net.Sockets.SocketConnection.ProcessMessage(String data)
в CryptoExchange.Net.Sockets.BaseSocket.Handle[T](List`1 handlers, T data)
в CryptoExchange.Net.Sockets.BaseSocket.<Connect>b__80_3(Object o, MessageReceivedEventArgs s)
в WebSocket4Net.WebSocket.OnDataReceived(Byte[] data, Int32 offset, Int32 length)
в SuperSocket.ClientEngine.AuthenticatedStreamTcpSession.OnDataRead(IAsyncResult result)
в System.Net.LazyAsyncResult.Complete(IntPtr userToken)
в System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
в System.Net.Security._SslStream.ProcessFrameBody(Int32 readBytes, Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
в System.Net.Security._SslStream.ReadFrameCallback(AsyncProtocolRequest asyncRequest)
в System.Net.AsyncProtocolRequest.CompleteRequest(Int32 result)
в System.Net.FixedSizeReader.CheckCompletionBeforeNextRead(Int32 bytes)
в System.Net.FixedSizeReader.ReadCallback(IAsyncResult transportResult)
в System.Net.LazyAsyncResult.Complete(IntPtr userToken)
в System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
в System.Net.ContextAwareResult.Complete(IntPtr userToken)
в System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
в System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
в System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)

**Comment by JKorf** [comment]
I've just pushed v2.1.4 of CryptoExchange.Net which has the additional checks. 2.1.4 has no interface changes to 2.1.3 so you should just be able to update the version.

**Comment by NektoDron** [comment]
Thanks! I'll test it.

**Comment by JKorf** [comment]
I'll assume this issue has been fixed, let me know if you run into things.
