### ISSUE TITLE
problem with SubscribeToAllSymbolTicker

### ISSUE THREAD

**Issue by NektoDron** [JKorf/Binance.Net#221]
I've updated the Binance library yesterday from 4.0.13 to 4.0.16.

There have been several communication losses.
After that, I close the API instances and create new ones. Everything has been working fine for months, but today the socketApi.SubscribeToAllSymbolTicker stops sending events. Other events (trades and queue) worked fine.

It happened around this time:
01:36:24.90[269]DEBUG:[Binance_DIHF] API: 2019/05/30 01:36:24:905 | Warning | No response from server | ConnectFailure - Невозможно соединиться с удаленным сервером
01:47:24.66[282]DEBUG:[Binance_DIHF] API: 2019/05/30 01:47:24:665 | Warning | No response from server | ConnectFailure - Невозможно соединиться с удаленным сервером

In the morning I made a reconnect (APIs recreation) and it all worked

**Comment by JKorf** [comment]
Hi, between version 4.0.13 and 4.0.16 no changes were made which could explain problems in connectivity. There were some fixes in the order book and in the trade rules. Same for the CryptoExchange.Net version from 2.1.2 to 2.1.3. 

So I think it might've just been a hickup at Binance side. Has it been stable now again?

**Comment by NektoDron** [comment]
It has happened only once.

**Comment by JKorf** [comment]
It's hard to detect if the server has stopped sending events. However, if you expect a constant stream of data you can detect when you stop receiving any data. You can use the `SocketNoDataTimeout` socket client option for this. I can't advise you what to set that to though as that depends on what data you subscribe to and how often you expect data.

**Comment by JKorf** [comment]
Closing this as I don't believe it's an issue in this library
