### ISSUE TITLE
Is there a plan to support Okex?

### ISSUE THREAD

**Issue by mirror222** [JKorf/Binance.Net#222]
thank you so much.

**Comment by kingchenc** [comment]
Okex is a Bad Exchange with many Fake-Volume and other Strange things...

**Comment by mirror222** [comment]
lol.... thank you all the same.

**Comment by nikkozp** [comment]
time to added Binance DEX 😄

https://docs.binance.org/index.html

**Comment by JKorf** [comment]
Seeing as I have multiple pending requests for other exchanges and Okex has a bit of questionable reputation I'll probably skip it (for now). 
You could make your own implementation based on the CryptoExchange.Net base library though.
(@nikkozp added Binance DEX to the todo list)
