### ISSUE TITLE
Still getting timestamps 1000ms ahead of server time using AutoTimestamp

### ISSUE THREAD

**Issue by NektoDron** [JKorf/Binance.Net#223]
https://github.com/JKorf/Binance.Net/issues/139

It's not working. I'm still getting this error when placing orders.
The connection can work properly for days, but when it stops work sometime.

This transaction failed:
14:38:08.62[297]DEBUG:[Binance_DIHF] PlaceOrder 1922600465:OrderType:Market; ContainerId:0; PortfolioOrderId:361032514; TradeName:DIHF_07_06_19_cycles_test
14:38:08.90[208]DEBUG:[Binance_DIHF] API: 2019/06/10 14:38:08:903 | Warning | Server returned an error: {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."}
14:38:08.93[293]DEBUG:[Binance_DIHF] transaction 1922600465 has been rejected.

But next has passed:
14:39:11.46[222]DEBUG:[Binance_DIHF] PlaceOrder 1585087423:OrderType:Market; ContainerId:0; PortfolioOrderId:361032418; TradeName:DIHF_07_06_19_cycles_test
14:39:14.23[96]DEBUG:[Binance_DIHF] NewOrderReply: 1585087423:428220661:10.06.2019 14:39:12:GoodTillCancel:Filled:0.00000000:0.00312800:0.00312800:2
14:39:14.23[76]DEBUG:[Binance_DIHF] OnOrderUpdateMessage: 428220661:-1:10.06.2019 14:39:12:GoodTillCancel:New:0.00000000:0.00000000:0.00312800:0.00000000:0.00000000

**Comment by nikkozp** [comment]
solved https://github.com/JKorf/Binance.Net/issues/185#issuecomment-465718910

**Comment by NektoDron** [comment]
It's not solved, I received it on the latest library version.

**Comment by JKorf** [comment]
It's not solved as there is only so much I can do from the library. The solution would be to make sure your machine time is synced at a more regular intervals, which is what the referenced comment also notes.

**Comment by kingchenc** [comment]
> It's not solved as there is only so much I can do from the library. The solution would be to make sure your machine time is synced at a more regular intervals, which is what the referenced comment also notes.

It is solved for me, and i thnk this solution work too for other peoples

@NektoDron try this

           in the Code: AutoTimestamp = true

           Third Party Tool:  SP TimeSync 2.4 < auto sync all 10 min or less

**Comment by JKorf** [comment]
@NektoDron have you tried using SP TimeSync?

**Comment by NektoDron** [comment]
We have already tried a bunch of ways to synchronize time. All the same, a problem arises several times a day. But it exists only if time runs forward. Can you add an option so that you can specify a "shift" that will be subtracted upon each request?

**Comment by JKorf** [comment]
What would you expect that option to look like?

**Comment by NektoDron** [comment]
Like a static shift value in ms which will be subtracted from current time.

**Comment by nikkozp** [comment]
@JKorf You need to change `private double timeOffset` to `public double timeOffset` in `BinanceClient`

@NektoDron You can make a fork for your test. And under successful tests do PR

**Comment by JKorf** [comment]
I've added a TimestampOffset option, in combination with the receive window you can shift the window forwards which should help with your problem.

**Comment by JKorf** [comment]
I'll assume this works for you, if not let me know.

**Comment by adrey** [comment]
@JKorf I suppose `localTime` should be calculated after receiving server time from binance or request processing time should be included in formula
```
     calculatedTimeOffset = (result.Data.ServerTime - localTime).TotalMilliseconds;
```
otherwise big latency will always be a cause to big positive values of calculatedTimeOffset
