### ISSUE TITLE
Question: How can I get user-balances in default/normal format (JSON) via Websocket?

### ISSUE THREAD

**Issue by thanasis-greece** [JKorf/Binance.Net#224]
Hello! Is there any other way to take the websocket result in default/normal format (JSON) ? I am trying to get user balances in json format, not parsed.
I want to be able to get the results like they are in GET "https://api.binance.com/api/v3/account?" but I havent found any way to do that.
Also, I cant edit the code as I am using nuget package. I only need to make the code in websocket because I dont want to send 1 request per second to API as my IP and API keys may be banned.
The code is:

`var sub = socketClient.SubscribeToUserStream(listenKey, OnAccountUpdate, OnOrderUpdate); `........

```
private void OnAccountUpdate(BinanceStreamAccountInfo data)
{
          Assets = new ObservableCollection<Form1>(data.Balances.Where(b => b.Free != 0 || b.Locked != 0).Select(b => new Form1() { Asset = b.Asset, Free = b.Free, Locked = b.Locked }).ToList());
// I want the return data to be in json format, unparsed so i can use them in other thread which doesnt use Binance.Net libraries.
}
```

Thank you!

**Comment by thanasis-greece** [comment]
Please, is there any update about my question or it can't be made?
Thanks.

**Comment by JKorf** [comment]
Hi, sorry for the delayed response, was on holiday. There is no build in way to do this currently, however you could serialize the data objects back to json again like so: 
````C#
            socketclient.SubscribeToSymbolTicker("ETHBTC", data =>
            {
                var jsonData = JsonConvert.SerializeObject(data);
                Console.WriteLine(jsonData);
            });
````

**Comment by thanasis-greece** [comment]
Thank you very much sir! I appreciate it. I had completely forgotten that you can convert a deserialized object back to the original JSON format.
Thanks again!
