### ISSUE TITLE
Gel all orders

### ISSUE THREAD

**Issue by miqteam** [JKorf/Binance.Net#227]
Is there an easier way to get all orders without trying every possible pair combinations?
Binance api supports without setting symbol to get all orders.
How i can do with your api

**Comment by nikkozp** [comment]
Hi
`var AllOpenOrders = Client.GetOpenOrders();`

**Comment by JKorf** [comment]
Hi, as @nikkozp suggested you can use `GetOpenOrders` to get a list of open orders. Where did you see the API supports retrieving a list of orders without providing a symbol?

**Comment by JKorf** [comment]
If you have any improvements please let me know. As far as I know there is no way to retrieve a full list of all orders at the moment, so I'll close this.

**Comment by dj-jordan** [comment]
Hi @Jkorf - what about the API call to Binance  /v3/allOrders ?
