### ISSUE TITLE
CancelMarginOrder

### ISSUE THREAD

**Issue by Onub3nse** [JKorf/Binance.Net#228]
Hi there, im trying to cancel a margin order, and getting all the time unknown order, i'll pass correctly the orderID, or maybe i'm doing something wrong?

CancelOrder = bClient.CancelMarginOrder(CurrentSymbol.Symbol.Name, MyOrder.OrderID,,,)

I never used the other parameters since the function doen't need them.

**Comment by JKorf** [comment]
Hi, can you share the debug output of this? Set LogVerbosity to Debug in the client options.

**Comment by Onub3nse** [comment]
Creating request for https://api.binance.com/api/v3/order
2019/08/12 09:08:11:241 | Debug | Sending DELETE signed request to https://api.binance.com/api/v3/order?symbol=BNBUSDT&timestamp=1565593691239&orderId=217302842&origClientOrderId=217302842&recvWindow=5000&signature=0BC27C1EC9435C2E1B22841E1B2D408BB56D0303F02CAFAF45C117305397D552 
2019/08/12 09:08:11:503 | Warning | Server returned an error: {"code":-2011,"msg":"Unknown order sent."}

Using the Async version it works fine.

**Comment by JKorf** [comment]
Ah I see the problem, the non-async method points to the non-margin cancel order method, instead of the margin endpoint. For now you can use the async version, I'll push a fix later today. Thanks for the report!

**Comment by Onub3nse** [comment]
Thanks for your fast response, you're awesome!
