### ISSUE TITLE
oco Orders

### ISSUE THREAD

**Issue by Onub3nse** [JKorf/Binance.Net#229]
Hello guys, now im totally confused about OCO Orders, yes i know, that's not the right place to ask, but can somebody provide me a little example how to call those orders, a buy and sell example.

I'm using VBA, but i have no problems converting them from any other language, thank you, help is very much appreciated.

**Comment by JKorf** [comment]
Hi, OneCancelsOther orders are explained here: https://www.binance.vision/glossary/one-cancels-the-other-order
As for how to place them using the API, here's an example
`client.PlaceOCOOrder("BNBBTC", OrderSide.Sell, 1, 0.0028m, 0.0024m, stopLimitPrice: 0.0023m, stopLimitTimeInForce: TimeInForce.GoodTillCancel);`
This will place a oco sell order for BNBBTC which in turn will place 2 orders. The first is a LimitMaker sell order for 1 BNB at a price of 0.0028btc(price parameter). The other is a StopLossLimit order for 1 BNB at a price of 0.0023btc(stopLimitPrice parameter) which gets triggered at 0.024btc(stopPrice parameter).

**Comment by Onub3nse** [comment]
Thank you very much, that was exactly what i was looking for, you're, once again, super!

**Comment by M22arius494** [comment]
Thanks for the example!
