### ISSUE TITLE
Problem with GetAccountInfo Balances

### ISSUE THREAD

**Issue by kingchenc** [JKorf/Binance.Net#23]
Hello,
im not the best c# programmer, im very new here... i cant "read" the full Balance, or the Balance from a single Coin in BTC/XY Coin...
i can only get the Count or Capacity..? 
With accountInfo.Data.Balances.Count/Capacity, but how //BTC/Xy Coin?
thank you :)

**Comment by JKorf** [comment]
Hi, 
The accountInfo.Data.Balances is a list of all your holdings. You can for example loop through the results:
````C#
foreach(var balance in accountInfo.Data.Balances)
{
    Console.WriteLine($"Balance of {balance.Asset}: {balance.Total}");
}
````
or search for a single asset using LINQ (add using System.Linq; to the top of your file)
````C#
var balance = accountInfo.Data.Balances.SingleOrDefault(x => x.Asset == "BTCETH"); // Or some other asset
````

**Comment by kingchenc** [comment]
Thanks Jkorf for your help and  great work, but can you give me please some Code snipet for a console/writeline application for search a single asset using linq? (with"foreach(var balance in accountInfo.Data.Balances)" i have no problems but the other code....) Its rly hard to undertand, when you learning fresh a "language", so not rly understand how to work with "var balance = accountInfo.Data.Balances.SingleOrDefault(x => x.Asset == "BTCETH"); // Or some other asset"
thank you :)

**Comment by JKorf** [comment]
Here is a Console application which will tell you the balance of something when you type it: 

````C#
using Binance.Net;
using Binance.Net.Objects;
using System;
using System.Linq;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            string apiKey = "YOUR API KEY";
            string apiSecret = "YOUR API SECRET";
            BinanceAccountInfo accountInfo;

            using (var client = new BinanceClient(apiKey, apiSecret))
            {
                client.AutoTimestamp = true;
                var infoResult = client.GetAccountInfo();
                if (!infoResult.Success)
                {
                    Console.WriteLine("Couldn't get account info! " + infoResult.Error.Message);
                    Console.ReadLine();
                }
                accountInfo = infoResult.Data;
            }

            Console.WriteLine("Insert asset to check balance for");
            while (true)
            {
                var input = Console.ReadLine();
                var asset = accountInfo.Balances.SingleOrDefault(balance => balance.Asset.ToLower() == input.ToLower());
                if (asset == null)
                    Console.WriteLine("No balance found for " + input);
                else
                    Console.WriteLine("Balance for " + input + ": " + asset.Total);
            }
        }
    }
}
````

Remember to change the apikey/secret. 

In my previous reaction I was talking about "BTCETH" where I should have said "BTC" or "ETH". Sorry for that. Anyway, if every thing goes okay when you type in "BTC" in this console application it should give you the amount of BTC you have.

Hope this helps!

**Comment by kingchenc** [comment]
Thank you very much and for your patience Jkorf, now i understand how this works with your Code sniped, thats helped my!
<3

**Comment by c4dx** [comment]
I cant find "GetAccountInfo" on the BinanceClient!?

**Comment by MohamadRezaSafari** [comment]
why are you dont answer ?
