### ISSUE TITLE
BinanceIndicator?

### ISSUE THREAD

**Issue by ErcinDedeoglu** [JKorf/Binance.Net#232]
Hi,
I just find "BinanceIndicator". What's it for? Because it come nullish.

**Comment by JKorf** [comment]
Hi, the `BinanceIndicator` is part of the response of the `GetTradingStatus()` call. It indicates how close you are to some of Binance limitations in regards to trading:
"GCR": 150,  // Number of GTC orders
"IFER": 150, // Number of FOK/IOC orders
"UFR": 300   // Number of orders
After pacing at least 1 order Binance will return the indicator status for the symbol:
![image](https://user-images.githubusercontent.com/8448172/63324084-a6238f80-c327-11e9-9631-1287a95e4f49.png)

**Comment by ErcinDedeoglu** [comment]
I supposed, it fetch financial indicators :( as macd, bollingers, etc. Anyway thanks a lot!

**Comment by JKorf** [comment]
Sadly no, Binance API doesn't provided those ;)
