### ISSUE TITLE
OCO requests

### ISSUE THREAD

**Issue by shotyme** [JKorf/Binance.Net#233]
Would be great if you could add the new OCO requests:

- New OCO (TRADE)
- Cancel OCO (TRADE)
- Query OCO (USER_DATA)
- Query all OCO (USER_DATA)
- Query Open OCO (USER_DATA)

https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#new-oco-trade

**Comment by JKorf** [comment]
Hi, the latest version already has those implemented

**Comment by shotyme** [comment]
Great! Have you a timeline for the release of the new version?

**Comment by JKorf** [comment]
Version 4.2.2 has this already, it's been available since Tuesday
