### ISSUE TITLE
Convert dust assets to BNB

### ISSUE THREAD

**Issue by prometheus82** [JKorf/Binance.Net#235]
Is there any option in this API to achieve that?

**Comment by JKorf** [comment]
Hi, not in the current version of Binance.Net, however when I looked into it I saw that the endpoint was added to the API documentation at the start of this month, so I'll add it. Probably pushing a new version tomorrow.

**Comment by JKorf** [comment]
I've pushed version 4.2.3, which has the new DustTransfer endpoint. You can use this to convert dust to BNB.

**Comment by anotherdeveloper** [comment]
Nice. Thanks.
