### ISSUE TITLE
Issue with testnet

### ISSUE THREAD

**Issue by crayse1** [JKorf/Binance.Net#236]
I tried use with the testnet api and my first error is
 
2019/09/03 22:09:17:805 | Warning | Server returned an error: {"timestamp":1567566567180,"status":404,"error":"Not Found","message":"No message available","path":"/api/v1/time"} 

The documentation shows to use "fapi"
https://testnet.binancefuture.com/fapi/v1/time

Can you add support for the binance testnet?

**Comment by crayse1** [comment]
I adjusted the code a little but it looks like there is much work to do.

2019/09/03 23:10:01:118 | Warning | Local object doesn't have property `totalInitialMargin` expected in type `BinanceAccountInfo`
2019/09/03 23:10:01:118 | Warning | Local object doesn't have property `totalMaintMargin` expected in type `BinanceAccountInfo`
2019/09/03 23:10:01:118 | Warning | Local object doesn't have property `totalWalletBalance` expected in type `BinanceAccountInfo`
2019/09/03 23:10:01:118 | Warning | Local object doesn't have property `totalUnrealizedProfit` expected in type `BinanceAccountInfo`
2019/09/03 23:10:01:118 | Warning | Local object doesn't have property `totalMarginBalance` expected in type `BinanceAccountInfo`
2019/09/03 23:10:01:118 | Warning | Local object doesn't have property `assets` expected in type `BinanceAccountInfo`
2019/09/03 23:10:01:118 | Warning | Local object has property `MakerCommission` but was not found in received object of type `BinanceAccountInfo`
2019/09/03 23:10:01:118 | Warning | Local object has property `TakerCommission` but was not found in received object of type `BinanceAccountInfo`
2019/09/03 23:10:01:118 | Warning | Local object has property `BuyerCommission` but was not found in received object of type `BinanceAccountInfo`
2019/09/03 23:10:01:118 | Warning | Local object has property `SellerCommission` but was not found in received object of type `BinanceAccountInfo`
2019/09/03 23:10:01:118 | Warning | Local object has property `AccountType` but was not found in received object of type `BinanceAccountInfo`
2019/09/03 23:10:01:118 | Warning | Local object has property `Balances` but was not found in received object of type `BinanceAccountInfo`
2019/09/03 23:10:01:118 | Debug | Returned data: {

**Comment by JKorf** [comment]
Hi, where is the documentation on the testnet api?

**Comment by JKorf** [comment]
Futures api will need a lot of changes, I'll add support for it at some point, but it will take more time than just adjusting the urls
