### ISSUE TITLE
Memory usage?

### ISSUE THREAD

**Issue by ErcinDedeoglu** [JKorf/Binance.Net#237]
I have some trouble with memory usage.

Example code:
```
BinanceKline[] binanceKlineList = binanceClient.GetKlines(_pair.ToString(), klineInterval, startTime, null).Data;
binanceKlineList = binanceClient.GetKlines(_pair.ToString(), klineInterval, startTime, null).Data;
binanceKlineList = binanceClient.GetKlines(_pair.ToString(), klineInterval, startTime, null).Data;
binanceKlineList = binanceClient.GetKlines(_pair.ToString(), klineInterval, startTime, null).Data;
```

Each line, it increases the memory usage dramatically.

<img width="170" alt="Screenshot_1" src="https://user-images.githubusercontent.com/6512072/64347535-c6786d00-cffc-11e9-971e-9c0c261240b4.png">

And i tried to dispose binanceClient object but it didn't affect memory usage... I tried to wait GC. No...
How can I hold it under control? Is it common problem?

**Comment by JKorf** [comment]
Hi, are you sure BinanceClient is what is causing this? I ran this simple test and the memory usage remains stable:
````C#
            var client = new BinanceClient();
            var klineInterval = KlineInterval.FiveMinutes;
            while (true)
            {
                var binanceKlineList = client.GetKlines("BTCUSDT", klineInterval).Data;
                Thread.Sleep(1000);
            }
````
![image](https://user-images.githubusercontent.com/8448172/64349435-43084d00-cff7-11e9-9f90-9c6843151425.png)

Could you maybe show (part of) the code that's increasing the memory usage?

**Comment by ErcinDedeoglu** [comment]
I found a strange results. 
When I tried with .net core console application, there is no memory leak.
But when I tried with a asp.net core mvc application, it started use a lot of memory and not clearing.

Please check the minified project:
https://github.com/ErcinDedeoglu/Binance.Net-Temp-Test

Here is:
https://github.com/ErcinDedeoglu/Binance.Net-Temp-Test/blob/master/AspNetCoreBinanceNetTest/Startup.cs

It's calling the method 
https://github.com/ErcinDedeoglu/Binance.Net-Temp-Test/blob/636bebcbf00514362e22b3ebde6b292c1f4aab3f/AspNetCoreBinanceNetTest/Startup.cs#L85

<img width="177" alt="Screenshot_2" src="https://user-images.githubusercontent.com/6512072/64424055-b02be900-d0b0-11e9-8e31-e740b7b852b4.png">

**Comment by JKorf** [comment]
Hi,  this seems to be an issue in .netcore, a lot of people having issues as seen in the gh issue: https://github.com/aspnet/AspNetCore/issues/1976
If you want a quick work around for the issue you can call garbage collection manually. Something like this keeps the memory usage stable:
````C#
            while (true)
            {
                using (var binanceClient = new BinanceClient())
                {
                    var binanceKlineList = binanceClient.GetKlines("BTCUSDT", KlineInterval.FiveMinutes, new DateTime(2000, 01, 01), null).Data;
                    Thread.Sleep(500);
                    GC.Collect();
                }
            }
````

Other than that, it's not an issue with this library, so I can't help you further.

**Comment by ErcinDedeoglu** [comment]
I tried to call gc manually but nothing changed. I think we have to consider to move another programming language...

**Comment by JKorf** [comment]
With the test project you send using the above code the memory stabilizes around 180mb, it isn't for you?
