### ISSUE TITLE
problem to install package binance

### ISSUE THREAD

**Issue by 30amak** [JKorf/Binance.Net#241]
Hi to all.
I have problem to install binance package :

Install-Package : Could not install package 'Binance.Net 4.3.2'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references 
or content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:1
+ Install-Package Binance.Net
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

Help please.

**Comment by JKorf** [comment]
Hi, make sure you've update you visual studio and nuget package manager to the latest versions

**Comment by 30amak** [comment]
Thank you for your respond.
