### ISSUE TITLE
binance sample code withdraw coin

### ISSUE THREAD

**Issue by 30amak** [JKorf/Binance.Net#242]
Hello dear friend.
Please send binance sample code for withdraw coin.
Thanks a lot.

**Comment by ThusMad** [comment]
Hello, this code work for me.
```

            BinanceClient _client = new BinanceClient(new BinanceClientOptions()
            {
                ApiCredentials = new ApiCredentials("your public key", "your private key")
            });

            var resp = _client.Withdraw("BTC" /* Or what u want */, "adress", 0.01M /* your amount in asset currency */);
            Console.WriteLine(resp.Data.Message);
```

I should mention that some assets need special tags for withdrawing, u can set it as param after an amount.

**Comment by 30amak** [comment]
> Hello, this code work for me.
> 
> ```
> 
>             BinanceClient _client = new BinanceClient(new BinanceClientOptions()
>             {
>                 ApiCredentials = new ApiCredentials("your public key", "your private key")
>             });
> 
>             var resp = _client.Withdraw("BTC" /* Or what u want */, "adress", 0.01M /* your amount in asset currency */);
>             Console.WriteLine(resp.Data.Message);
> ```
> 
> I should mention that some assets need special tags for withdrawing, u can set it as param after an amount.

Which version of framework do you use?

**Comment by ThusMad** [comment]
4.6.1

**Comment by JKorf** [comment]
I assume you've gotten this working, if not feel free to re-open
