### ISSUE TITLE
Can't serialize BinanceSymbol

### ISSUE THREAD

**Issue by anotherdeveloper** [JKorf/Binance.Net#243]
```
var info = new BinanceClient().GetExchangeInfo().Data;
var symbol = info.Symbols.First();
var json = JsonConvert.SerializeObject(symbol);
```

Serialization fails with System.NotImplementedException: 'The method or operation is not implemented.'

**Comment by JKorf** [comment]
Hi, the serialization method of the BinanceSymbolFilter objects wasn't implemented as it wasn't needed for normal usage. I've added it now though, so using the new 4.3.3 version it should work for you.

**Comment by anotherdeveloper** [comment]
Brilliant, thanks very much.
