### ISSUE TITLE
Depth Data : Missing Depth Delete Data

### ISSUE THREAD

**Issue by miqteam** [JKorf/Binance.Net#244]
I compare the depth data with binance application.
I often see more lines from binance. Especially top of book data is not been removed.
The data with default ignore value doesn't come. I try other libraries, they are correct.
What can the problem be?

Here is my code :

` var socketClient = new BinanceSocketClient();
            // Streams

            var localDepthCache = new Dictionary<string, DepthCacheObject> {{ "BTCUSDT", new DepthCacheObject()
            {
                Asks = new SortedDictionary<decimal, decimal>(),
                Bids = new SortedDictionary<decimal, decimal>(new DescendingComparer<decimal>()),
            }}};
            var bnbBtcDepthCache = localDepthCache["BTCUSDT"];
            var depthResults = await client.GetOrderBookAsync("BTCUSDT", 100);
            //Populate our depth cache
            depthResults.Data.Asks.ForEach(a =>
            {
                if (a.Quantity != 0.00000000M)
                {
                    bnbBtcDepthCache.Asks.Add(a.Price, a.Quantity);
                }
            });
            depthResults.Data.Bids.ForEach(a =>
            {
                if (a.Quantity != 0.00000000M)
                {
                    bnbBtcDepthCache.Bids.Add(a.Price, a.Quantity);
                }
            });

            long lastUpdateId = depthResults.Data.LastUpdateId;

            var successDepth = socketClient.SubscribeToDepthStreamAsync("BTCUSDT",1000, (data) =>
            {
                if (lastUpdateId < data.LastUpdateId)
                {
                    data.Bids.ForEach((bd) =>
                    {
                        CorrectlyUpdateDepthCache(bd, bnbBtcDepthCache.Bids);
                    });
                    data.Asks.ForEach((ad) =>
                    {
                        CorrectlyUpdateDepthCache(ad, bnbBtcDepthCache.Asks);
                    });
                }
                lastUpdateId = data.LastUpdateId;
                System.Console.Clear();
                System.Console.WriteLine($"{JsonConvert.SerializeObject(bnbBtcDepthCache.Bids, Formatting.Indented)}");
                System.Console.SetWindowPosition(0, 0);
                // handle data
            });`

` private static void CorrectlyUpdateDepthCache(BinanceOrderBookEntry bd, SortedDictionary<decimal, decimal> depthCache)
        {
            const decimal defaultIgnoreValue = 0.00000000M;
            Debug.WriteLine(bd.Price+"-"+bd.Quantity);
            if (depthCache.ContainsKey(bd.Price))
            {
                if (bd.Quantity == defaultIgnoreValue)
                {
                    depthCache.Remove(bd.Price);
                }
                else
                {
                    depthCache[bd.Price] = bd.Quantity;
                }
            }
            else
            {
                if (bd.Quantity != defaultIgnoreValue)
                {
                    depthCache[bd.Price] = bd.Quantity;
                }
            }
        }
        public class DepthCacheObject
        {
            public SortedDictionary<decimal, decimal> Asks { get; set; }
            public SortedDictionary<decimal, decimal> Bids { get; set; }
        }

class DescendingComparer<T> : IComparer<T> where T : IComparable<T>
        {
            public int Compare(T x, T y)
            {
                return y.CompareTo(x);
            }
        }`

**Comment by JKorf** [comment]
Hi, the first thing I notice is you first request the order book snapshot, then after receiving it you start subscribing. Updates between the snapshot and the subscribing are lost.

Note that Binance.Net provides an order book implementation:
````C#
var orderbook = new BinanceSymbolOrderBook("BTCUSDT");
orderbook.Start(); // <- starts syncing

foreach (var bid in ob.Bids.Take(3))
      Console.WriteLine(bid.Price + ": " + bid.Quantity);
````

**Comment by miqteam** [comment]
Hi,
How will get updates? What does BinanceSymbolOrderBook do?
Can you share an example to get depths correctly?

**Comment by miqteam** [comment]
I couldn't found the answer how should i get order depths realtime.

**Comment by JKorf** [comment]
Access the orderbook.Bids property at any time, it's the latest state of the book.

You can also subscribe to OnOrderbookUpdate to be notified when an update has occured, but it can be fired quite often.

**Comment by miqteam** [comment]
Thanks for your help. Where is OnOrderbookUpdate event?

**Comment by JKorf** [comment]
Ah my bad, that event doesn't exist yet in the latest version, it will be in next release.
Here's a snippet which starts an order book and displays the top 5 bids/asks in the console every 500ms:
````C#
            var orderBook = new BinanceSymbolOrderBook("BTCUSDT");
            orderBook.OnStatusChange += (oldStatus, newStatus) => Console.WriteLine($"Order book status changed from {oldStatus} to {newStatus}");
            
            var startResult = await orderBook.StartAsync();
            if (!startResult.Success)
            {
                Console.WriteLine("Failed to start order book: " + startResult.Error);
                Console.ReadLine();
            }

            while (true) 
            {
                Console.Clear();
                Console.WriteLine(orderBook.ToString(5));
                Thread.Sleep(500);
            }
````

You can access the orderBook.Bids/orderBook.Asks at any time and get the latest state of the book. 
In the next version orderBook.OnOrderBookUpdate can be used to be notified when the book has been updated. (On a high liquidity market like Btc/Usdt it will be constantly firing though)

**Comment by miqteam** [comment]
Hi,
Thanks for your help.
