### ISSUE TITLE
Issue after editing for Futures trading

### ISSUE THREAD

**Issue by captholley** [JKorf/Binance.Net#247]
I have downloaded the repository and have edited the endpoints and all domains in order to allow for futures trading. This was relatively simple but I am now having an issue starting up the API. When I initiate the api it continues to get stuck at the initial start-up during the StartUserStream(). The error appears to be happening within the cryptoexchange.net package. Here is the error:

MissingMethodException: Method not found: 'System.String CryptoExchange.Net.ExtensionMethods.CreateParamString(System.Collections.Generic.Dictionary`2<System.String,System.Object>, Boolean)'.

Any idea what is going on here? I have double checked the url that is being used for the GetServerTime() within the StartUserStream() and this url works in my browser. Any idea what's going on here? Or better yet, any idea when functionality for futures will be available?

**Comment by captholley** [comment]
I have resolved the above issue but now am running into problems with the stream for the futures contracts. Has anyone had a look at this? Does the futures endpoint even work? I tried it on websocket.org to test the connections and I am not getting anything. I have walked through the edits I made on the original Binance.Net in order to allow for futures and the stream connection processes fine, but I never receive any messages. Any help would be appreciated.

**Comment by ThusMad** [comment]
@captholley If this is still relevant, I tested the sockets in js and they work, I want to emphasize that the binance supports only one trading symbol (_btcusdt_).

**Comment by JKorf** [comment]
@captholley is this still relevant?

**Comment by captholley** [comment]
All is working and updating the repository for Futures Trading
