### ISSUE TITLE
ValidateBinanceSymbol doesn't allow HCBTC

### ISSUE THREAD

**Issue by anotherdeveloper** [JKorf/Binance.Net#249]
The regex doesn't match 5 character markets.

**Comment by JKorf** [comment]
Ah right, my bad. I've pushed a fix, should be available in a few minutes

**Comment by anotherdeveloper** [comment]
BCHABCBTC isn't working either. Sorry.

**Comment by JKorf** [comment]
Dang, well I'll validate everything, will be a little longer for a new version, but probably in a couple of hours.

**Comment by anotherdeveloper** [comment]
That works. Thanks.
