### ISSUE TITLE
How to set the endpoint to Binance US?

### ISSUE THREAD

**Issue by dooferorg** [JKorf/Binance.Net#250]
The API endpoint seems configured to only be api.binance.com ... how do I override it to be api.binance.us ?

BinanceClientOptions extends RestClientOptions but does not allow setting of the address?

**Comment by JKorf** [comment]
Hi, you can configure the base address in the options, it just isn't in the constructor:
````C#
            var options = new BinanceClientOptions()
            {
                BaseAddress = "http://api.binance.us",
                LogVerbosity = LogVerbosity.Debug
            };
            BinanceClient.SetDefaultOptions(options);
            var client = new BinanceClient();
````

**Comment by dooferorg** [comment]
Ah, thank you, yes that worked perfectly. I'm using https.

I was wondering why my API key was coming up as 'Invalid' and then finally realized it was the wrong endpoint URL. Hopefully this helps someone else too!
