### ISSUE TITLE
-1013: Filter failure: PERCENT_PRICE

### ISSUE THREAD

**Issue by AngeloRiega** [JKorf/Binance.Net#251]
Hello I'm currently using: 
`PlaceOrder("MANABTC", OrderSide.Sell, OrderType.Limit, 10, price: 1, timeInForce: TimeInForce.GoodTillCancel);`
and this is what's returning
`{-1013: Filter failure: PERCENT_PRICE }`

**Comment by JKorf** [comment]
Hi, that seems about right. You're trying to place a sell order for 10 MANA at 1 BTC each. Binance has some filters in place which make sure the orders you place make any sense. In your case the price is too far off from the current trading price. You can retrieve information about a symbol and what the current filters are by using the `GetExchangeInfo` call:
````C#
var client = new BinanceClient();
var exchangeInfoResult = client.GetExchangeInfo();
if (exchangeInfoResult)
{
      var symbol = exchangeInfoResult.Data.Symbols.Single(s => s.Name == "MANABTC");
      var filters = symbol.Filters; // <- List of filters/restrictions for placing orders
}
````
