### ISSUE TITLE
Web Sockets in ASP.NET Core

### ISSUE THREAD

**Issue by Warrolen** [JKorf/Binance.Net#252]
Hello,

what is the best way to use Web Sockets client with ASP.NET Core since the connection should be opened once and kept alive through the entire time.

Regards,
Warrolen

**Comment by JKorf** [comment]
Hi, it depends on your usecase, but you would have to use a Singleton implementation to make sure it stays alive. I've added a small Asp.Net Core MVC application to the examples folder. If you have any more questions let me know.

**Comment by Warrolen** [comment]
Thank you! How could I subscribe right there:

```
namespace Binance.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class BinanceController : ControllerBase
    {
        private readonly IBinanceService _binanceService;
        private readonly IMapper _mapper;

        public BinanceController(IBinanceService binanceService, IMapper mapper)
        {
            _binanceService = binanceService;
            _mapper = mapper;
        }

        // GET: api/Binance/BNBBTC/1
        [HttpGet("{symbol}/{interval}")]
        public async Task<ActionResult<List<BinanceKlineDto>>> GetAllKlinesAsync([FromRoute] string symbol, [FromRoute] KlineInterval interval)
        {
            var klines = await _binanceService.GetAllKlinesAsync(symbol, interval);
            return Ok(_mapper.Map<List<BinanceKlineDto>>(klines));
        }
    }
}
```

Basically to replace the normal client with web sockets.

**Comment by JKorf** [comment]
That's hard for me to answer, as I'm not entirely sure on what you're trying to do. If you want to retrieve all klines as you're doing with the GetAllKlines method, then you don't want to use the socket client and your current implementation is fine. 

The socket client would typically be used if you want to have live updates and do something with the data the moment it arrives.

Could you maybe explain what you're trying to do/achieve?

**Comment by Warrolen** [comment]
I wanted to use web sockets because `GetAllKlines` should be executed like 20 times within a second or two.

**Comment by JKorf** [comment]
Why do you need it to execute 20 times in a second? 
If you need the same data 20 times, then you should request the data once and cache it in your service, then return it every time it is requested.

**Comment by Warrolen** [comment]
The last (unfinished) candle changes frequently and I need to keep an eye on it in real time as well as on the ledgers when it comes to another strategy. The ledgers change a few times in a second.

**Comment by JKorf** [comment]
I see, take a look at the `BinanceDataProvider.cs` in the AspNetCore example. When you call the Start method (now done in the constructor, but could be at any point) it subscribes to the websocket. It has an OnKlineData event which gets triggered when something changes, which provides the latest candle. 

You can combine the updates with the BinanceClient.GetAllKlines method. First request all candles using the client and store the data. Then subscribe to the websocket using the BinanceSocketClient and update the last kline with the data which is constantly received from the socket client. This way you'll always have the latest data. Something like this:

````C#
            var klineData = client.GetKlines("BTCUSDT", KlineInterval.ThreeMinutes).Data.ToList();
            socketClient.SubscribeToKlineUpdates("BTCUSDT", KlineInterval.ThreeMinutes, data =>
            {
                var lastKnownKline = klineData.Last();
                if(lastKnownKline.OpenTime != data.Data.OpenTime)
                {
                    // New kline, add to list
                    klineData.Add(data.Data.ToKline());
                }
                else
                {
                    // Update for last kline
                    lastKnownKline.High = data.Data.High;
                    lastKnownKline.Low = data.Data.Low;
                    lastKnownKline.Close = data.Data.Close;
                    lastKnownKline.QuoteAssetVolume = data.Data.QuoteAssetVolume;
                    lastKnownKline.Volume = data.Data.Volume;
                    lastKnownKline.TradeCount = data.Data.TradeCount;
                    lastKnownKline.TakerBuyBaseAssetVolume = data.Data.TakerBuyBaseAssetVolume;
                    lastKnownKline.TakerBuyQuoteAssetVolume = data.Data.TakerBuyQuoteAssetVolume;
                }
            });
````

**Comment by Warrolen** [comment]
Thanks, I think I nearly got it! Btw, what is keeping the connection up? The way it is singleton service? I mean if I call `_socketClient.SubscribeToKlineUpdatesAsync` at `Start()`, then my logic and `Stop()` in the end, will the connection to binance be kept alive if I unsubscribe the event but leave the application up which means the singleton service will remain alive?

**Comment by gensleralexander** [comment]
The subscription only gives you updates on the current candle, as this is the only one that can change.
After the interval of the candle is completed there will be a candle that is declared 'final', after that the next candle will be pushed.
I advise you to do something like I did in my program:
https://github.com/gensleralexander/JACB/blob/master/JACB/Models/Bots/BinanceBot.cs

Before you start the subscription, use the REST Client to receive the last 20 candles into a collection, after that subscribe to the socket and when a candle is declared 'final' add it to the collection.

**Comment by Warrolen** [comment]
Thank you for that, @gensleralexander! In my case, I have to pull the last two (maybe 3) candles of a few crypto pairs at same time. Will everything work with the RestAPI Client? Have you tried it? By a few times I mean 5 at the most.

**Comment by gensleralexander** [comment]
I think so..
The limits from the binance api state the following:
https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#limits

REQUEST_WEIGHT - 1200 per minute - one kline call has a weight of 1, so that means you use up to 1200 kline calls per minute

As my bot is using rest for warmup data only this is not really a problem in my code, as only one call on initialization is done.
However in my backtest downloader I use a queue to limit the amount of calls..

**Comment by Hulkstance** [comment]
> 
> 
> I think so..
> The limits from the binance api state the following:
> https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#limits
> 
> REQUEST_WEIGHT - 1200 per minute
> one kline call has a weight of 1, so that means you can use up to 1200 kline calls per minute
> 
> As my bot is using rest for warmup data only this is not really a problem in my code, as only one call on initialization is done.
> However in my backtest downloader I use a queue to limit the amount of calls..

Thanks, that's it.

That's my current way of simulating the processing: https://stackoverflow.com/questions/59204399/delay-in-web-sockets-execution-maybe-and-a-few-other-problems but it's delaying, so I'm going to try what you guys did and especially @JKorf's example above. The problem is how do I calculate when there is **x time* before the end of the interval? More precisely, I mean that I have to detect if there aren't 10 minutes left, to execute some logic 1 minute before the end, if the time interval is `KlineInterval.OneHour`.

**Comment by gensleralexander** [comment]
@Hulkstance not quite sure if I understand your question right, however, by calling the REST-GetKlines without any start & end timestamp you will get the limit-parameter specified amount of klines, where the last one is not final, however all others are final.
The SOCKET-SubscribeToKlineUpdates will push the current kline every few seconds and after your Interval is full, it will push a kline, which is declared final.

If you're only interested in final klines, you can do the following:
- load warmup data with the REST-Client
- subscribe to Socket Client
- the whole handler should be an if-clause that only does something if data.Data.Final == true
- normally the first pushed kline of the socket client should have the same timestamp as the last warmup kline. you can overwrite the warmup one

However, if you're also interested in the non-final klines you can do the following (**Note:** if you want to do technical analysis or other compute-intensive tasks on the klines, this can lead to unwanted behaviour, as a new update is pushed every second):
- load warmup data with the REST-Client
- subscribe to Socket Client
- update the latest kline with the current pushed kline until it is declared final, then move on to the next

As most technical indicators don't need more than roughly 1000-2000 klines to be precise, I advise to not save more, as the plus of precision is not worth the plus of time needed for calculation.

**Comment by Hulkstance** [comment]
@gensleralexander, I'm working with both finished and unfinished klines. I'm not using any bound-in indicators and I only need the data from the last two klines. The algorithm performs backtesting for the last 20 candles on each interval which is probably fine.

The 10-minute thing is only with 1-hour interval (`KlineInterval.OneHour`). It's like a double confirmation for a condition. It checks on each 10 minutes for that condition's result until it gets double confirmations. If there aren't 10 minutes left, it should immediately execute the logic and return its final result.

```
public void Start(Bot bot)
{
    ApplyCredentialsOnClient();

    bool locked = false;

    BinanceKline lastKnownKline = null;
    _subscription = _socketClient.SubscribeToKlineUpdates(bot.CryptoPair.Symbol, bot.TimeInterval.Interval, async data =>
    {
        var helper = new HQBotHelper(_notificationService);
        List<BinanceKline> previousTwenty;

        if (data.Data.Final)
        {
            _logger.LogError($"Static | Open time: {data.Data.OpenTime.ToLocalTime()} | Close time: {data.Data.CloseTime.ToLocalTime()} | Close: {data.Data.Close}");

            // Backtesting
            previousTwenty = helper.GetCandles(redisBot, 20);

            lastKnownKline = data.Data.ToKline();
        }
        // This block won't be executed before the static block is executed first
        else if (lastKnownKline != null && lastKnownKline.Close != data.Data.Close)
        {
            if (!locked)
            {
                _logger.LogError($"Real time | Open time: {data.Data.OpenTime.ToLocalTime()} | Close: {data.Data.Close}");
                locked = true;

                // Long operation
                // If there are more than 10 minutes left by the end of the one hour interval, we wait 10 minutes and check for the condition again
                // If the condition is not met, we wait another 10 minutes and check again until the condition is met or there are less than 10 minutes left
                
                // In other words, it should simulate double check confirmation. The first check happens immediately and if it is true,
                // it should repeat the check after 10 minutes until it gets double confirmations or there aren't 10 minutes left.
                //if (DateTime.UtcNow.AddMinutes(10) < data.Data.CloseTime)
                //{
                //    await Task.Delay(10 * 60);
                //}

                locked = false;
            }

            lastKnownKline = data.Data.ToKline();
        }
    }).Data;
}
```

**Comment by Warrolen** [comment]
I think it's been answered very well, thanks to everyone and I'm closing this.
