### ISSUE TITLE
Is secret key required for orders?

### ISSUE THREAD

**Issue by Hulkstance** [JKorf/Binance.Net#257]
The title is pretty self explanatory. My app will pull balance information and put orders. Do I need only the API key or the secret key is required too? The documentation says that it is used for signing: https://github.com/JKorf/CryptoExchange.Net/blob/master/CryptoExchange.Net/Authentication/ApiCredentials.cs#L54. But still, I wanted to make sure.

According to my understanding, I only have to activate _Enable trading_ option for the API key in Binance API Management and the secret key is only if the API key is lost. Is that correct?

**Comment by JKorf** [comment]
To authenticate requests both the key and the secret are required. The secret is used to sign the messages to the server. The API key tells the server who you are (or say you are) and the secret is used to encrypt the message so the server can validate it's actually you.

**Comment by Hulkstance** [comment]
Ah, thank you! So, it's required to ask the user for them both.

**Comment by JKorf** [comment]
Yup that's right

**Comment by Hulkstance** [comment]
> 
> 
> Yup that's right

Thank you again! Closing this.
