### ISSUE TITLE
PlaceOrder issue?

### ISSUE THREAD

**Issue by thraxxus** [JKorf/Binance.Net#258]
Every so often when I fire a PlaceOrder the order shows up on the exchange but the response comes back null. Anyone else see this?

**Comment by thraxxus** [comment]
Nobody?

**Comment by JKorf** [comment]
I haven't seen this personally, but I don't place a lot of orders. When it is null, is the Error object in the CallResult set?

**Comment by thraxxus** [comment]
Call result is null

**Comment by JKorf** [comment]
Sorry for the late response, I've be quite busy,.
The CallResult object should never be null. If you still have this issue, could you share the code calling the PlaceOrder method? 

If you solved this, or it is no longer relevant please close the issue.

**Comment by JKorf** [comment]
Assuming this is solved, if not let me know
