### ISSUE TITLE
marginBuyBorrowAmount, marginBuyBorrowAsset, newOrderRespType, sideEffectType

### ISSUE THREAD

**Issue by Bozzano13** [JKorf/Binance.Net#259]
Hello, 

Is it possible to add marginBuyBorrowAmount, marginBuyBorrowAsset, newOrderRespType, sideEffectType for margin trading please ?

Regards,

**Comment by JKorf** [comment]
Hi, sorry for the late response.
Can you point me to the documentation of these properties please?

**Comment by Bozzano13** [comment]
Hello, no problem for delay, thanks to rely
Here the point in the doc:
https://binance-docs.github.io/apidocs/spot/en/#margin-account-new-order-trade

**Comment by JKorf** [comment]
Has been added in the latest version
