### ISSUE TITLE
Getting all balances info totals in BTC

### ISSUE THREAD

**Issue by topproto** [JKorf/Binance.Net#26]
Hi JKorf

is it possible to get the BTC value of each coin and a total of all coins? Similar to 
https://www.binance.com/userCenter/balances.html

I want to get these balance totals when i start my app (without any changes). It looks like you cant get them unless you get a response from SubscribeToAccountUpdateStream. The problem is you only get a response if Binance detects a change. 

Am i missing a way to get these values? Or is this something missing from Binance.Net.

edit - attached image just in case you don't have access to the above link.
![image](https://user-images.githubusercontent.com/35653813/35766715-165fb300-08d5-11e8-8934-28c506c97f31.png)

and
![image](https://user-images.githubusercontent.com/35653813/35766730-599d416e-08d5-11e8-8ae2-23a06b88e92c.png)

**Comment by JKorf** [comment]
Hi,

You can get the balances of the account associated with the Apikey/secret calling the GetAccountInfo method in the BinanceClient. After retrieving the amount of the asset you'll have to multiply that with the latest price for that assets btc/asset market to get the approximate BTC value.

**Comment by topproto** [comment]
Thanks for the reply JKorf.
I have manually done this with your suggestion :)
