### ISSUE TITLE
Error SubscribeToAllSymbolTickerUpdates

### ISSUE THREAD

**Issue by karloballa** [JKorf/Binance.Net#261]
I'm often getting this error: https://i.ibb.co/3shWzdK/binError.png

I think there was no such error in older versions, now I'm using the latest.

**Comment by nikkozp** [comment]
Hej, i am using last version, but its ok for me.

What you using in UpdateSymbol? Most likely the error in this method

**Comment by karloballa** [comment]
It seems that I found what is wrong.

In the older version, I had a problem that the private stream suddenly stops working after some time. Then I didn't know what to do, so after some time I manually reconnect the private stream. It seems I introduced some race conditions. Now it is OK.

Before I close the issue I have one question. Did you have problem with the private stream?

**Comment by nikkozp** [comment]
nothing problems
