### ISSUE TITLE
getPrice weirdness

### ISSUE THREAD

**Issue by thraxxus** [JKorf/Binance.Net#262]
var price = client.GetPrice("BNBBTC");

THAT sometimes returns ZERO. 
anyone else see that?

I see it happen all the time.
thoughts?

**Comment by nikkozp** [comment]
![image](https://user-images.githubusercontent.com/11537426/71661472-8b8a0a00-2d4e-11ea-97a1-6747aa63ff8a.png)

**Comment by thraxxus** [comment]
I don't know what your image means.
Like I said, SOMETIMES it returns zero.

**Comment by JKorf** [comment]
I haven't seen it myself. Do you mean the Price property is '0'?
If so it would be what Binance returned from the server, so not much to do about that. 
You can verify that by enabling Debug logging and checking in the output what the data was that was returned by the Binance server.

**Comment by JKorf** [comment]
I assume this is solved, if not let me know
