### ISSUE TITLE
100% order quantity

### ISSUE THREAD

**Issue by Hulkstance** [JKorf/Binance.Net#263]
Hello,

I wanna put a few orders with the entire quantity but I don't seem to find built-in solution, so I tried to make it myself.

```
var balance = _client.GetAccountInfo().Data.Balances.FirstOrDefault(e => e.Asset == "TRX").Free;
var orderId = _client.PlaceOrder("TRXUSDT", OrderSide.Sell, OrderType.Limit, quantity: balance, price: 0.01580m, timeInForce: TimeInForce.GoodTillCancel);
```

In my example, I'm selling my entire TRX balance for USDT at 0.01580.

The problem is that I have only the symbol saved into my database (`TRXUSDT`). How do I get only TRX or USDT. You may say Substring but there are coins with more than 3 letters, e.g. MATICUSDT.

Any idea how to solve that?

**Comment by anotherdeveloper** [comment]
```
var symbols = _client.GetExchangeInfo().Data.Symbols;
var symbol = symbols.Single(item => item.Name == "TRXUSDT");
var baseAsset = symbol.BaseAsset;
var quoteAsset = symbol.QuoteAsset;


```

**Comment by Hulkstance** [comment]
@anotherdeveloper, thanks a lot! @JKorf, isn't there a built-in functionality like there is in Binance's App?

**Comment by gensleralexander** [comment]
@Hulkstance sadly no, this however is a problem due to the Binance API and not the wrappers of @JKorf ..
I stumbled on this also, you can read my solution [here](https://github.com/gensleralexander/JACB/blob/master/JACB/Models/AccountInformation/AccountInformationStream.cs) at line 1047 following..
My version does also not get 100% percent, but around 99.9%.. this seems to be necessary, because using 100% the amount which you get by the OnBalanceUpdates, sometimes leads to insufficent amount errors. Hope this helps you

**Comment by Hulkstance** [comment]
@gensleralexander, thanks! Yes, exactly. If you look at the picture below, my balance differs from the actual amount that you can trade with. Not quite sure how they calculate the sum you can buy with (in my case `276.06288600 USD`).

![image](https://user-images.githubusercontent.com/33224919/72664940-2e5bad00-3a0c-11ea-9cf5-c4bb19a64568.png)

**Comment by gensleralexander** [comment]
@Hulkstance you need to use the Step Size and Precision Properties of the trading pair for correct rounding ;)
You can read about this also in the [Binance API Documentation](https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md)

**Comment by Hulkstance** [comment]
@gensleralexander, is that all you do:

```
var exchangeInfo = client.GetExchangeInfo().Data.Symbols.FirstOrDefault(e => e.Name == "TRXUSDT");

var stepSize = exchangeInfo.LotSizeFilter.StepSize;
var basePrecision = exchangeInfo.QuoteAssetPrecision; // unused

int decimalsStep;
if (stepSize != 0.0m)
{
	for (decimalsStep = -1; stepSize < 1; decimalsStep++)
	{
		stepSize *= 10;
	}
}
else
{
	decimalsStep = 0;
}

var symbol = client.GetExchangeInfo().Data.Symbols.FirstOrDefault(e => e.Name == "TRXUSDT"); // TRXUSDT
var baseAsset = symbol.BaseAsset; // TRX
var quoteAsset = symbol.QuoteAsset; // USDT
var availableBase = client.GetAccountInfo().Data.Balances.FirstOrDefault(e => e.Asset == baseAsset).Free; // Balance for TRX
var availableQuote = client.GetAccountInfo().Data.Balances.FirstOrDefault(e => e.Asset == quoteAsset).Free; // Balance for USDT
decimal price = 0.01740m;

if (availableBase > 0.0m)
{
	decimal amount = availableQuote * 0.9999m;
	var quantity = Math.Round(amount / price, decimalsStep, MidpointRounding.ToEven).Normalize();
}
```

because there are values that I don't know (makerFee) and thanks

**Comment by gensleralexander** [comment]
@Hulkstance yes. there are probably ways to do this better, but this works for me.
I use the default Fees and have an option for custom fee rate usage (was a feature request). However I believe there is also a query to get the current Fee rate..

**Comment by JKorf** [comment]
Thanks @gensleralexander for taking the time to help a fellow user :)
 @Hulkstance any questions still?

**Comment by Hulkstance** [comment]
@gensleralexander has already answered me, thanks! :)
