### ISSUE TITLE
newbie question - kline interval

### ISSUE THREAD

**Issue by OutkastedOne** [JKorf/Binance.Net#264]
i have been trying to get the kline data for btc on binance for a while but no matter how i try it refuse to take the interval

var x = clientx.GetKlinesAsync("BTCUSDT", 1m);
also tried interval=1m, tried "1m" as a string still no good, what does it want?

**Comment by JKorf** [comment]
Hi, it expects a value of the `KlineInterval` enum, which is found in `Binance.Net.Objects`.
Add this to the top of your file: `using Binance.Net.Objects;`
and use it like this:
`GetKlines("BTCUSDT", KlineInterval.OneMinute);`

**Comment by OutkastedOne** [comment]
you sir are a demi god in my eyes right now haha, thanks heaps, i will have a play with this and see what trouble i can get myself into now, thanks again!
