### ISSUE TITLE
Unsubscribe all freeze

### ISSUE THREAD

**Issue by Onub3nse** [JKorf/Binance.Net#266]
Using web sockets unsubscribe all freezes nearly everytime the app, version 5.0.4.
Not happening when using older versións.

Even in debug mode, i'm unable to catch up this error, it just freezes, no more info avaiable.

**Comment by Onub3nse** [comment]
It seems to happen with older version's too, but with less frequency.

**Comment by JKorf** [comment]
Hi, does this also happen with individual Unsubscribe() calls? And could you maybe share the last debug logging of when it freezes? ( setting LogVerbosity = LogVerbosity.Debug )

**Comment by Onub3nse** [comment]
Debug doesn't reveal anything, it's just freezes the whole app. It subscribes perfectly, info of the subs is given correctly, just when i try to change to another aset it freezes.

**Comment by JKorf** [comment]
I can't reproduce this issue. Using this simple test console application it works fine for me: 
````C#
        static async Task Main(string[] args)
        {
            var client = new BinanceSocketClient();

            while (true)
            {
                await client.SubscribeToKlineUpdatesAsync("BTCUSDT", KlineInterval.OneDay, data => Console.WriteLine("Kline"));
                await client.SubscribeToBookTickerUpdatesAsync("BTCUSDT", data => Console.WriteLine("Book ticker"));
                await client.SubscribeToTradeUpdatesAsync("BTCUSDT", data => Console.WriteLine("Trade update"));

                Console.ReadLine();
                await client.UnsubscribeAll();
            }
        }
````

Could you maybe try and make a small snippet which demonstrates the problem?

**Comment by karloballa** [comment]
I'm using Windows Forms App. 
client.UnsubscribeAll and client.Unsubscribe blocks the calling thread.

**Comment by karloballa** [comment]
It seems that client.Unsubscribe works with the private stream, but blocks with a public stream

**Comment by karloballa** [comment]
I synchronize everything with the main thread. It seems that I triggered a deadlock.

**Comment by JKorf** [comment]
I still can't reproduce this, using a windows form. It would be great if you could share a project/snippet which demonstrates the problem. Can't do much at this time.

**Comment by nikkozp** [comment]
This will only happen if you use unsubscribing in the `UI thread`. To avoid this, I use `ReactiveUI`

**Comment by karloballa** [comment]
I used to synchronize everything with the UI (which is probably a bad idea by itself, it could freeze the UI while waiting for data).

Instead of using locks for every thread, I used Invoke to UI thread. Later I decided to abandon that approach, and use locks. Now it is OK.

**Comment by JKorf** [comment]
Hi, I think I found the call that could cause a deadlock, could you see if you still have issues with the 5.1.1 version?
