### ISSUE TITLE
TradeRulesBehaviour.AutoComply doesn't work when placing an OCO Order

### ISSUE THREAD

**Issue by swAucxis** [JKorf/Binance.Net#270]
Example:
binanceClient.PlaceOCOOrder(GOBTC, OrderSide.Sell, 19011.0000000000, 0.00000289, 0.00000229, stopLimitPrice: 0.00000218, stopLimitTimeInForce: TimeInForce.GoodTillCancel)

Error:
Precision is over the maximum defined for this asset.

**Comment by JKorf** [comment]
Trade rules weren't checked for OCO orders, I've enabled that in the latest version. Let me know if you have any issues.
