### ISSUE TITLE
Indicators

### ISSUE THREAD

**Issue by Hulkstance** [JKorf/Binance.Net#271]
Is there like a sub library of this project which provides indicators like MA (Moving average), RSI or simply a library which uses this particular API wrapper?

**Comment by nikkozp** [comment]
Hi, you can count the indicators you need yourself using data from this API

**Comment by Hulkstance** [comment]
> 
> 
> Hi, you can count the indicators you need yourself using data from this API

Hello, I know that but if there is ready-to-use approach, I would rather use it instead of spending time on how all indicators and implementing their logic myself.

**Comment by gensleralexander** [comment]
@Hulkstance I really can recommend [Trady.Analysis](https://github.com/lppkarl/Trady)
You might want to give it a try ;)

**Comment by Hulkstance** [comment]
> 
> 
> @Hulkstance I really can recommend [Trady.Analysis](https://github.com/lppkarl/Trady)
> You might want to give it a try ;)

Thanks, I decided to do it myself in the end, because I needed only 2 indicators which is easy to calculate.
