### ISSUE TITLE
Buy order question

### ISSUE THREAD

**Issue by Hulkstance** [JKorf/Binance.Net#272]
Hello,
I wanted to buy 2 BNBs (exactly) the moment I have less than 3 BNBs with Market order. Can someone explain me how it works? I don't seem to be getting a successful order at all. I tried a few ways. 

```
var order = client.PlaceOrder("BNBUSDT", OrderSide.Buy, OrderType.Market, quoteOrderQuantity: 1);
```

**Comment by nikkozp** [comment]
MARKET orders using `quoteOrderQty` specifies the amount the user wants to spend (when buying) or receive (when selling) of the **quote asset**; the correct quantity will be determined based on the market liquidity and `quoteOrderQuantity`.
MARKET orders using `quoteOrderQuantitywill `not break `LOT_SIZE` filter rules; the order will execute a quantity that will have the notional value as close as possible to `quoteOrderQuantity`.
_(c) Binance docs_

Most likely you are violating the `MIN_NOTIONAL` filter, for `BNBUSDT` it is equal to 10

**Comment by Hulkstance** [comment]
> 
> 
> MARKET orders using `quoteOrderQty` specifies the amount the user wants to spend (when buying) or receive (when selling) of the **quote asset**; the correct quantity will be determined based on the market liquidity and `quoteOrderQuantity`.
> MARKET orders using `quoteOrderQuantitywill `not break `LOT_SIZE` filter rules; the order will execute a quantity that will have the notional value as close as possible to `quoteOrderQuantity`.
> _(c) Binance docs_
> 
> Most likely you are violating the `MIN_NOTIONAL` filter, for `BNBUSDT` it is equal to 10

Thank you!

In the end, that's the solution:

```
var availableBNB = client.GetAccountInfo().Data.Balances.FirstOrDefault(e => e.Asset == "BNB").Free; // Balance for BNB
if (availableBNB < 3)
{
	var lastBNBPrice = client.Get24HPrice("BNBUSDT").Data.LastPrice;

	var quoteOrderQuantity = Math.Round((5 - availableBNB) * lastBNBPrice, 8); // quotePrecision = 8
	var order = client.PlaceOrder("BNBUSDT", OrderSide.Buy, OrderType.Market, quoteOrderQuantity: quoteOrderQuantity);
}
```

I'm not sure for one thing tho: https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md says `"quotePrecision": 8`. Does that mean the value should be rounded up or rounded down to the nearest value?

**Comment by nikkozp** [comment]
u no need to round.

use this
```
public static decimal ClampQuantity(BinanceSymbol SymbolInfo, decimal Quantity)
{
            Quantity -= Quantity % SymbolInfo.LotSizeFilter.StepSize;
            Quantity = Math.Min(SymbolInfo.LotSizeFilter.MaxQuantity, Quantity);
            Quantity = Math.Max(SymbolInfo.LotSizeFilter.MinQuantity, Quantity);
            Quantity = Floor(Quantity);
            return Quantity;
}
```

**Comment by tomdegryse** [comment]
You can simply use:

var order = client.PlaceOrder("BNBUSDT", OrderSide.Buy, OrderType.Market, quantity: 2)

**Comment by Hulkstance** [comment]
> var order = client.PlaceOrder("BNBUSDT", OrderSide.Buy, OrderType.Market, quantity: 2)

Thanks, that's the best solution! It buys exactly 1 in quantity.

**Comment by Hulkstance** [comment]
> 
> 
> u no need to round.
> 
> use this
> 
> ```
> public static decimal ClampQuantity(BinanceSymbol SymbolInfo, decimal Quantity)
> {
>             Quantity -= Quantity % SymbolInfo.LotSizeFilter.StepSize;
>             Quantity = Math.Min(SymbolInfo.LotSizeFilter.MaxQuantity, Quantity);
>             Quantity = Math.Max(SymbolInfo.LotSizeFilter.MinQuantity, Quantity);
>             Quantity = Floor(Quantity, SymbolInfo.);
>             return Quantity;
> }
> 
> public static decimal Floor(decimal number, int premission = 8)
> {
>             int num = (int)Math.Pow(10, premission);
>             return Math.Floor(number * num) / num;
> }
> ```

I somehow missed your comment. Did you mean `SymbolInfo.BaseAssetPrecision` or `SymbolInfo.QuoteAssetPrecision`?

```
Quantity = Floor(Quantity, SymbolInfo.);
```

**Comment by nikkozp** [comment]
@Hulkstance my SymbolInfo its 
`var SymbolInfo  = GetExchangeInfo().Data.Symbols;`

**Comment by Hulkstance** [comment]
@nikkozp, thanks!
