### ISSUE TITLE
Running multiple API keys on multiple threads

### ISSUE THREAD

**Issue by Warrolen** [JKorf/Binance.Net#276]
Hello guys,

I have two running bots on two separate threads and they both set API key and Secret Key, separately (or at least I thought so):

```
private void ApplyCredentialsOnClient(string apiKey, string secretKey)
{
	BinanceClient.SetDefaultOptions(new BinanceClientOptions()
	{
		ApiCredentials = new ApiCredentials(apiKey, secretKey),
		AutoTimestamp = true,
		AutoTimestampRecalculationInterval = TimeSpan.FromMinutes(30)
	});

	BinanceSocketClient.SetDefaultOptions(new BinanceSocketClientOptions()
	{
		ApiCredentials = new ApiCredentials(apiKey, secretKey),
		AutoReconnect = true,
		ReconnectInterval = TimeSpan.FromHours(24)
	});
}
```

Both threads are running at same time and they both print messages for their analysis, Whenever it's time to put an order, they both put the order with second bot's API key.

In other words, `BinanceClient.SetDefaultOptions` is overriding first bot's API key. 

**Expected behavior:**
The threads shouldn't override each other's API keys but instead, they should both use different API keys.

```
public async Task AddBotAsync(string botName)
{
	// Resolve services
	using var scope = _serviceProvider.CreateScope();
	var botService = scope.ServiceProvider.GetRequiredService<IBotService>();
	var notificationService = scope.ServiceProvider.GetRequiredService<INotificationService>();

	var bot = await botService.GetByNameAsync(botName);

	// New thread
	if (bot.Status == Status.Started && !string.IsNullOrEmpty(bot.User.BinanceConfig.ApiKey) && !string.IsNullOrEmpty(bot.User.BinanceConfig.SecretKey))
	{
		CancellationTokenSource cts = new CancellationTokenSource();
		Task task = Task.Factory.StartNew(() => new BinanceBot(_logger, _serviceProvider).DoWork(bot, cts.Token));
		_bots.TryAdd(botName, new Tuple<Task, CancellationTokenSource>(task, cts));
	}
}

public void DoWork(Bot bot, CancellationToken token)
{
	ApplyCredentialsOnClient(bot.User.BinanceConfig.ApiKey, bot.User.BinanceConfig.SecretKey);

	...
```

Is there any way to fix that?

**Comment by JKorf** [comment]
This is expected behavior, it sets the default options for all clients created after that moment. You can however just specify options per client:
````C#
var options = new BinanceClientOptions(){
    // whatever options/credentials you need
}
var client = new BinanceClient(options);
````

**Comment by Warrolen** [comment]
> This is expected behavior, it sets the default options for all clients created after that moment. You can however just specify options per client:
> 
> ```cs
> var options = new BinanceClientOptions(){
>     // whatever options/credentials you need
> }
> var client = new BinanceClient(options);
> ```

Thanks, it makes sense now
