### ISSUE TITLE
Limits

### ISSUE THREAD

**Issue by Hulkstance** [JKorf/Binance.Net#277]
I have two running threads that analyze stuff. I noticed that after executing a few `BinanceClient` queries, I'm getting blocked by Binance's servers and let's say `_client.GetExchangeInfo().Data` returns null.

Example:

```
var orders = _client.GetAllOrders(bot.Symbol).Data.Where(e => e.Status == OrderStatus.New || e.Status == OrderStatus.PartiallyFilled || e.Status == OrderStatus.PendingCancel);

var symbol = _client.GetExchangeInfo().Data.Symbols.FirstOrDefault(e => e.Name == bot.Symbol);
```

How do you guys deal with it? I was thinking about adding multiple web socket subscriptions for anything I can, like for the orders, last price value, etc.

**Comment by nikkozp** [comment]
If `.Data` returns null, then `.Error` will show you an error
What error does Binance return to you?

Use a websocket subscription and minimize API requests.

**Comment by Hulkstance** [comment]
@nikkozp,

![image](https://user-images.githubusercontent.com/33224919/74713667-b0b8d600-5231-11ea-824a-0099a37c202b.png)

I only could optimize `LastPrice` with web sockets.

```
var availableBase = _client.GetAccountInfo().Data?.Balances.FirstOrDefault(e => e.Asset == baseAsset).Free; // Balance for TRX
var availableQuote = _client.GetAccountInfo().Data?.Balances.FirstOrDefault(e => e.Asset == quoteAsset).Free; // Balance for USDT
```
I don't think this one is possible.

**Comment by nikkozp** [comment]
you can get your balance via WebSocket

Example

```
var successAccount = socketClient.SubscribeToUserDataUpdates(listenKey, data =>
                {
                    // Handle account info data
                },
                data =>
                {
                    // Handle order update info data
                },
                null, // Handler for OCO updates
                null, // Handler for position updates
                null); // Handler for account balance updates (withdrawals/deposits)
```

**Comment by gensleralexander** [comment]
@Hulkstance as @nikkozp already mentioned, the WebSockets are the way to go here.
If you still want to stick with REST, you can at least cut your requests by half by improvising your code like this:

`var accountInfo = _client.GetAccountInfo().Data;`
`if(accountInfo != null){`
`var availableBase = accountInfo.Balances.FirstOrDefault(e => e.Asset == baseAsset).Free; // Balance for TRX`
`var availableQuote =accountInfo.Balances.FirstOrDefault(e => e.Asset == quoteAsset).Free; // Balance for USDT`
`}`

By the way, you should not use FirstOrDefault(), better use First() and catch an exception, if the asset is not contained. Or at least handle, if the default value is retrieved.

**Comment by Hulkstance** [comment]
> 
> 
> you can get your balance via WebSocket
> 
> Example
> 
> ```
> var successAccount = socketClient.SubscribeToUserDataUpdates(listenKey, data =>
>                 {
>                     // Handle account info data
>                 },
>                 data =>
>                 {
>                     // Handle order update info data
>                 },
>                 null, // Handler for OCO updates
>                 null, // Handler for position updates
>                 null); // Handler for account balance updates (withdrawals/deposits)
> ```

@nikkozp, This doesn't get invoked if nothing changes over the balance, I believe.

@gensleralexander, thanks for advice!

**Comment by nikkozp** [comment]
@Hulkstance Every time you do `_client.GetExchangeInfo().Data.Symbols.FirstOrDefault(e => e.Name == bot.Symbol);`, you send a new request to check your balance. When can you make this request once at the start, write the balance to a variable, and get a balance update for sockets? Then take your balance from the variable.

**Comment by Hulkstance** [comment]
> 
> 
> @Hulkstance Every time you do `_client.GetExchangeInfo().Data.Symbols.FirstOrDefault(e => e.Name == bot.Symbol);`, you send a new request to check your balance. When can you make this request once at the start, write the balance to a variable, and get a balance update for sockets? Then take your balance from the variable.

That's actually a nice idea, thanks!

**Comment by Hulkstance** [comment]
@nikkozp, I just did what you mentioned. What I don't get is why there is `BinanceAccountInfo` and `BinanceStreamAccountInfo` when they both are same. They are the reason I'm getting a compile-time error. Any recommendations?

```
public BinanceStreamAccountInfo AccountInfo { get; set; }

// Code
// Balance
BinanceAccountInfo accountInfo = _client.GetAccountInfo().Data;
if (accountInfo != null)
{
	AccountInfo = accountInfo; // Compile-time error: BinanceAccountInfo != BinanceStreamAccountInfo
}

string listenKey = _client.StartUserStream().Data;
if (listenKey != null)
{
	_socketClient.SubscribeToUserDataUpdates(listenKey, (data) =>
	{
		AccountInfo = data;

		Console.WriteLine(data.Balances);
	}, null, null, null, null);
}
```

**Comment by nikkozp** [comment]
Its my Example

```csharp
 private void GetBalance()
        {
            start:
            RateLimiterDelay(Weight: 5);
            var info = base.GetAccountInfo();

            if (!info.Success)
            {
                ErrorHandling(info.Error);
                goto start;
            }

            BinanceStreamAccountInfo BinanceAccountInfo = new BinanceStreamAccountInfo();
            BinanceAccountInfo.BuyerCommission = info.Data.BuyerCommission;
            BinanceAccountInfo.MakerCommission = info.Data.MakerCommission;
            BinanceAccountInfo.SellerCommission = info.Data.SellerCommission;
            BinanceAccountInfo.TakerCommission = info.Data.TakerCommission;

            BinanceAccountInfo.CanDeposit = info.Data.CanDeposit;
            BinanceAccountInfo.CanTrade = info.Data.CanTrade;
            BinanceAccountInfo.CanWithdraw = info.Data.CanWithdraw;

            BinanceAccountInfo.EventTime = info.Data.UpdateTime;

            List<BinanceStreamBalance> Balances = new List<BinanceStreamBalance>();

            foreach (var b in info.Data.Balances)
                Balances.Add(new BinanceStreamBalance
                {
                    Asset = b.Asset,
                    Free = b.Free,
                    Locked = b.Locked
                });

            BinanceAccountInfo.Balances = Balances;

            Balance = BinanceAccountInfo;
        }
```

Ideally, you should combine them with interfaces for more correct code. I'll do it after they add Futures

**Comment by Hulkstance** [comment]
> 
> 
> Its my Example
> 
> ```cs
>  private void GetBalance()
>         {
>             start:
>             RateLimiterDelay(Weight: 5);
>             var info = base.GetAccountInfo();
> 
>             if (!info.Success)
>             {
>                 ErrorHandling(info.Error);
>                 goto start;
>             }
> 
>             BinanceStreamAccountInfo BinanceAccountInfo = new BinanceStreamAccountInfo();
>             BinanceAccountInfo.BuyerCommission = info.Data.BuyerCommission;
>             BinanceAccountInfo.MakerCommission = info.Data.MakerCommission;
>             BinanceAccountInfo.SellerCommission = info.Data.SellerCommission;
>             BinanceAccountInfo.TakerCommission = info.Data.TakerCommission;
> 
>             BinanceAccountInfo.CanDeposit = info.Data.CanDeposit;
>             BinanceAccountInfo.CanTrade = info.Data.CanTrade;
>             BinanceAccountInfo.CanWithdraw = info.Data.CanWithdraw;
> 
>             BinanceAccountInfo.EventTime = info.Data.UpdateTime;
> 
>             List<BinanceStreamBalance> Balances = new List<BinanceStreamBalance>();
> 
>             foreach (var b in info.Data.Balances)
>                 Balances.Add(new BinanceStreamBalance
>                 {
>                     Asset = b.Asset,
>                     Free = b.Free,
>                     Locked = b.Locked
>                 });
> 
>             BinanceAccountInfo.Balances = Balances;
> 
>             Balance = BinanceAccountInfo;
>         }
> ```
> 
> Ideally, you should combine them with interfaces for more correct code. I'll do it after they add Futures

Thanks!
