### ISSUE TITLE
Error Getting Account Info

### ISSUE THREAD

**Issue by fernanespejo** [JKorf/Binance.Net#28]
Hi there,

Using Binance.NET to build a simple trading app on Visual Studio. I'm getting a code error -1021 when I call GetAccountInfo, thought it was my code first but the same call worked about an hour ago. Can you help? Thanks in advance!

![inkedimage 001_li](https://user-images.githubusercontent.com/13292024/35770653-1a56c6d2-0917-11e8-9522-5cd87aa723bf.jpg)

**Comment by JKorf** [comment]
Hi,
As the server is telling you you're ahead of their local time. You can auto synchronize the times by turning on the `AutoTimestamp` feature in the client:
````C#
bClient.AutoTimestamp = true;
````

**Comment by fernanespejo** [comment]
this fixed my issue, thank you!
