### ISSUE TITLE
Calculating EMA

### ISSUE THREAD

**Issue by Hulkstance** [JKorf/Binance.Net#281]
I'm trying to calculate EMA(20) for the pre-last candle but the values don't match those from Binance. More specifically, when I change `previousDayEMA = candles[i].Close; // SMA(period, candles);` to hard-coded number from Binance, it works fine. Can someone explain me what I am missing and it would be nice if someone knows how to round it the same way Binance do and the same way I did, but by not hard-coding the value (6). Because this rounding works for TRXUSDT but for example not for BTCUSDT.

Rounding:
```
Math.Round(EMA, 6, MidpointRounding.AwayFromZero);
```

Code:
```csharp
// Usage
var klines = _client.GetKlines("TRXUSDT", KlineInterval.ThirtyMinutes, limit: 21).Data.ToList();
var EMA20 = ExponentialMovingAverage.Calculate(20, klines);

// The actual code
using Binance.Net.Objects;
using System;
using System.Collections.Generic;

namespace Bot.Models.Indicators
{
    public class ExponentialMovingAverage
    {
        public static decimal SMA(int period, List<BinanceKline> candles)
        {
            if (candles.Count >= period)
            {
                decimal sum = 0;
                for (int i = 0; i < period; i++)
                {
                    sum += candles[i].Close;
                }
                return sum / period;
            }
            return 0;
        }

        public static decimal EMA(decimal close, decimal previousDayEMA, decimal period)
        {
            decimal multiplier = 2 / (period + 1);
            return (close - previousDayEMA) * multiplier + previousDayEMA;
        }

        public static decimal Calculate(int period, List<BinanceKline> candles)
        {
            decimal previousDayEMA = 0;
            if (candles.Count >= period)
            {
                decimal sum = 0;
                for (int i = 0; i < period; i++)
                {
                    if (i == 0)
                    {
                        previousDayEMA = candles[i].Close; // SMA(period, candles);
                    }

                    decimal EMA = ExponentialMovingAverage.EMA(candles[i].Close, previousDayEMA, period);

                    Console.WriteLine(Math.Round(EMA, 6, MidpointRounding.AwayFromZero));

                    sum += EMA;
                    previousDayEMA = EMA;
                }
                return sum / period;
            }
            return 0;
        }
    }
}
```

**Comment by CharlesZHENG** [comment]
Hi, bro, do you have any other codes? I am interested in quantitative trading with c#.

**Comment by nikkozp** [comment]
@Hulkstance too many code lines :)

```csharp
var klines = _client.GetKlines("TRXUSDT", KlineInterval.ThirtyMinutes, limit: 21).Data.ToList();

var MA20 = Math.Round(klines.Take(20).Sum(x=> x.Close) / 20, 2);
```

**Comment by Hulkstance** [comment]
> 
> 
> @Hulkstance too many code lines :)
> 
> ```cs
> var klines = _client.GetKlines("TRXUSDT", KlineInterval.ThirtyMinutes, limit: 21).Data.ToList();
> 
> var MA20 = Math.Round(klines.Take(20).Sum(x=> x.Close) / 20, 2);
> ```

I know but that code is only experimental. That value drift was because I needed to calculate the EMA for more candles. If you know a better way, let me know.

**Comment by nikkozp** [comment]
@Hulkstance This is a great option. You need to add the first time you receive data, write their variables, then update / add on the socket

**Comment by Hulkstance** [comment]
> 
> 
> @Hulkstance This is a great option. You need to add the first time you receive data, write their variables, then update / add on the socket

I made them in different classes as it is supposed to be convention-wise. And I kinda got nearly accurate values by calculating it for more values.

**Comment by odurmus06** [comment]
public static decimal FloorPrice(decimal tickSize, decimal price)
        {
            price -= price % tickSize;
            price = Floor(price);
            return price;
        }
decimal tickSize = 0.00000100m; https://api.binance.com/api/v3/exchangeInfo?symbol=BTCUSDT
var EMA20 = FloorPrice(tickSize  ,ExponentialMovingAverage.Calculate(20, klines));
