### ISSUE TITLE
Order update

### ISSUE THREAD

**Issue by karloballa** [JKorf/Binance.Net#283]
OnOrderUpdate handler does not fire all the time. Especially on orders that are canceled. 
Does anyone have such a problem?

**Comment by nikkozp** [comment]
@karloballa all working good

**Comment by JKorf** [comment]
Are you still experiencing this problem? If so, could you share some data using debug logging where you think updates are missing?

**Comment by karloballa** [comment]
Sometimes, but I need to explain

The source of "evil" is that at some random time interval (>45 minutes)  Binance stops sending data to private streams. Simply KeepAlive doesn't work. It is well-known and I assume that we all have that problem.  

To offsets that problem I need to reconnect private streams from time to time (public streams work properly). 

Now, the OnOrderUpdate problem. When I use only one instance of program it seems that everything works fine, except that sometimes I loose 1-2 ordered updates (when program reconnects while order update is receiving). But that is OK, I can live with that.

The bigger problem is when I have 2 instances of the program. I have one Binance account with two different API keys. At some moment one instance of the program stops receiving OnOrderUpdate. I suppose that it is due to reconnecting. Programs are with different API keys, on different computers, even different IP-s, but the problem remains. Must say again that with one instance of the program it seems that everything works properly.

**Comment by nikkozp** [comment]
This can happen if you use the same API keys. When you create a key, it can be re-created

To support an active connection I use this example
```csharp
var keepAliveListenKey = Observable.Timer(TimeSpan.FromSeconds(1), TimeSpan.FromMinutes(29))
                                 .Do(async x =>
                                 {
                                     _listenKey = await GetListenKey().ConfigureAwait(false);
                                 })
                                 .Subscribe();
```

**Comment by karloballa** [comment]
@nikkozp 
I used something similar but without success. 
Can you elaborate, where to put that code?

**Comment by Hulkstance** [comment]
@karloballa, @nikkozp, when is that happening? Here as an example?

```csharp
public void GetAccountInfo()
{
	var accountInfo = Client.GetAccountInfo();

	while (!accountInfo.Success)
	{
		var weight = BinanceHelpers.UsedWeight(accountInfo.ResponseHeaders);
		Globals.Instance.HandleRateLimits(weight.Value);

		accountInfo = Client.GetAccountInfo();
	}

	BinanceStreamAccountInfo BinanceAccountInfo = new BinanceStreamAccountInfo
	{
		BuyerCommission = accountInfo.Data.BuyerCommission,
		MakerCommission = accountInfo.Data.MakerCommission,
		SellerCommission = accountInfo.Data.SellerCommission,
		TakerCommission = accountInfo.Data.TakerCommission,

		CanDeposit = accountInfo.Data.CanDeposit,
		CanTrade = accountInfo.Data.CanTrade,
		CanWithdraw = accountInfo.Data.CanWithdraw,

		EventTime = accountInfo.Data.UpdateTime
	};

	List<BinanceStreamBalance> balances = new List<BinanceStreamBalance>();

	foreach (BinanceBalance balance in accountInfo.Data.Balances)
	{
		balances.Add(new BinanceStreamBalance
		{
			Asset = balance.Asset,
			Free = balance.Free,
			Locked = balance.Locked
		});
	}

	BinanceAccountInfo.Balances = balances;

	AccountInfo = BinanceAccountInfo;

	string listenKey = Client.StartUserStream().Data;
	SocketClient.SubscribeToUserDataUpdates(listenKey, data => AccountInfo = data, null, null, null, null);
}
```

More specifically this line:

```csharp
string listenKey = Client.StartUserStream().Data;
```

@karloballa, what do you mean by private stream?

**Comment by karloballa** [comment]
> @karloballa, what do you mean by private stream?


I meant the UserStream.

With one account, one key, and one instance of program everything is working fine. At the moment I think we should close this issue.
