### ISSUE TITLE
Watching multiple intervals

### ISSUE THREAD

**Issue by Warrolen** [JKorf/Binance.Net#286]
I wanted to subscribe to a few time intervals at same time, e.g. 1 hr, 2 hrs and 4 hrs, so I could watch the data simultaneously. The thing is that I have 2 threads (bots) and each of them should be watching those 3 intervals (1, 2, 4 hrs).

```
public void Start(Bot bot, CancellationToken token)
{
	_socketClient.SubscribeToKlineUpdates(bot.Symbol, KlineInterval.OneHour, data =>
	{
		// things
	});

	_socketClient.SubscribeToKlineUpdates(bot.Symbol, KlineInterval.TwoHours, data =>
	{
		// things
	});

	_socketClient.SubscribeToKlineUpdates(bot.Symbol, KlineInterval.FourHours, data =>
	{
		// things
	});
}

// Usage
Task task = Task.Factory.StartNew(() => strategy.Start(bot, cts.Token));
task.Wait();
```

I know many of you did that. How did you do it? Just like I did it above?

**Comment by nikkozp** [comment]
@Warrolen Why do this ? Subscribe once for different periods, write incoming data in the parameter.
Then, in each task, we get the specified variable.

P.S. I would recommend using delegates to transfer data to the strategy

**Comment by Warrolen** [comment]
How? I don't find a suitable method overload.

```
public CallResult<UpdateSubscription> SubscribeToKlineUpdates(string symbol, KlineInterval interval, Action<BinanceStreamKlineData> onMessage);
public CallResult<UpdateSubscription> SubscribeToKlineUpdates(IEnumerable<string> symbols, KlineInterval interval, Action<BinanceStreamKlineData> onMessage);
```

**Comment by nikkozp** [comment]
@Warrolen you don 't need to overload anything. 

For example, subscribe to the intervals you need during initialization, not at Start. Write down the data in a separate class. When you click on start, get the latest data from this class. Or create your own delegate, and subscribe to it at the start, then the data will come to you in the strategy automatically.

**Comment by nikkozp** [comment]
@Warrolen 

```csharp
//Class1
public event BinanceFuturesKlineStateHandler KlineEvent;
public delegate void BinanceFuturesKlineStateHandler(BinanceStreamKline Kline);

_socketClient.SubscribeToKlineUpdates(bot.Symbol, KlineInterval.OneHour, data =>
{
	KlineEvent?.Invoke(kline);
});

_socketClient.SubscribeToKlineUpdates(bot.Symbol, KlineInterval.TwoHours, data =>
{
	KlineEvent?.Invoke(kline);
});

_socketClient.SubscribeToKlineUpdates(bot.Symbol, KlineInterval.FourHours, data =>
{
	KlineEvent?.Invoke(kline);
});


//Class2
public void Start(Bot bot, CancellationToken token)
{
    KlineEvent += (BinanceStreamKline Kline) => { /* TODO */ };
}

// Usage
Task task = Task.Factory.StartNew(() => strategy.Start(bot, cts.Token));
task.Wait();
```

**Comment by Warrolen** [comment]
@nikkozp, so this logic subscribes to all 3 intervals at same time?

I should have a check in all of these three intervals and if it is true for all of them, it should execute additional logic. Is this possible?

**Comment by nikkozp** [comment]
@Warrolen Yes, you sign up at the same time.
Further any logic for you . I wouldn't unsubscribe if I had to reconnect. For example, if Stop, then `return;`

**Comment by Warrolen** [comment]
@nikkozp, `UnsubscribeAll` won't allow me to reconnect later on?

This is my stop function. How do I temporary stop the socket subscription in that case?
```
private void CancelTask(CancellationToken token)
{
	if (token.IsCancellationRequested)
	{
		try
		{
			token.ThrowIfCancellationRequested();
		}
		catch (OperationCanceledException)
		{
			_socketClient.UnsubscribeAll();
			Console.WriteLine("Task canceled.");
		}
	}
}
```

**Comment by nikkozp** [comment]
Each time you receive data on sockets, check whether the strategy is running

**Comment by Warrolen** [comment]
@nikkozp, actually if I stop a bot, it unsubscribes from the socket (UnsubscribeAll) and if I have to start the bot again, I'm subscribing to all events once again. Since it starts a new subscription, UnsubscribeAll doesn't have an impact on it, right?

**Comment by nikkozp** [comment]
in your case, you can only unsubscribe if you close the app. and then not necessarily
