### ISSUE TITLE
how to i connect to Binance Future ?

### ISSUE THREAD

**Issue by TarrahArshad** [JKorf/Binance.Net#291]
i need balance and position and order websocket subscription and price also

**Comment by nikkozp** [comment]
Hi. You can download the alpha version `Install-Package Binance.Net -Version 5.1.0-alpha7`

**Comment by TarrahArshad** [comment]
i installed but i can't find mewthod for subscripton inwebsocket for future

**Comment by TarrahArshad** [comment]
GetFuturesAccountBalance i can't find sample or document for this or other method

**Comment by nikkozp** [comment]
```csharp
var Account = await Ws.SubscribeToUserDataUpdatesAsync(listenKey,
                Balance =>
                {

                },
                Position =>
                {

                },
                Order =>
                {

                },
                ListenKeyExpired =>
                {

                }).ConfigureAwait(false);
```

**Comment by JKorf** [comment]
The futures implementation is still in alpha release, so there are bound to be some things which aren't complete/not documented or just broken. If you have any questions or remarks just ask.

**Comment by TarrahArshad** [comment]
what is type of WS in ur code?

**Comment by TarrahArshad** [comment]
> ```cs
> var Account = await Ws.SubscribeToUserDataUpdatesAsync(listenKey,
>                 Balance =>
>                 {
> 
>                 },
>                 Position =>
>                 {
> 
>                 },
>                 Order =>
>                 {
> 
>                 },
>                 ListenKeyExpired =>
>                 {
> 
>                 }).ConfigureAwait(false);
> ```

type of Ws ?

**Comment by TarrahArshad** [comment]
> ```cs
> var Account = await Ws.SubscribeToUserDataUpdatesAsync(listenKey,
>                 Balance =>
>                 {
> 
>                 },
>                 Position =>
>                 {
> 
>                 },
>                 Order =>
>                 {
> 
>                 },
>                 ListenKeyExpired =>
>                 {
> 
>                 }).ConfigureAwait(false);
> ```

what is listenKey ?

**Comment by nikkozp** [comment]
```csharp
BinanceFuturesSocketClient Ws = new BinanceFuturesSocketClient();
BinanceFuturesClient Client = new BinanceFuturesClient();

Client.SetApiCredentials(ApiKey, SecretKey);
Ws.SetApiCredentials(ApiKey, SecretKey);

var listenKey = await Client.StartUserStreamAsync().ConfigureAwait(false);

var Account = await Ws.SubscribeToUserDataUpdatesAsync(listenKey,
                Balance =>
                {

                },
                Position =>
                {

                },
                Order =>
                {

                },
                ListenKeyExpired =>
                {

                }).ConfigureAwait(false);
```

**Comment by TarrahArshad** [comment]
[image: image.png]
again error

**Comment by nikkozp** [comment]
`listenKey.Data`

**Comment by TarrahArshad** [comment]
[image: image.png]

**Comment by TarrahArshad** [comment]
now code work without error but i have error in     
var bf = Client.GetFuturesAccountBalance();

signatuyre erroir

**Comment by nikkozp** [comment]
Checked on the `testnet` `Client.GetFuturesAccountBalance();` - working

**Comment by TarrahArshad** [comment]
but i'm on mainnet

**Comment by nikkozp** [comment]
it doesn't matter.
what version of alpha do you use? and what error does it give you

**Comment by TarrahArshad** [comment]
alpha version Install-Package Binance.Net -Version 5.1.0-alpha7

**Comment by TarrahArshad** [comment]
> it doesn't matter.
> what version of alpha do you use? and what error does it give you

Hi. You can download the alpha version Install-Package Binance.Net -Version 5.1.0-alpha7

**Comment by nikkozp** [comment]
I use it

**Comment by TarrahArshad** [comment]
> I use it

why erro ?

**Comment by nikkozp** [comment]
show me your error

**Comment by TarrahArshad** [comment]
> show me your error



> show me your error

http://snap.ashampoo.com/YTPCBQLi5jeoxmFrXVEtPkvsqtP4gCIaWyCYJOBhXgvqs3clRh9cRuUCif9OHHO0

**Comment by nikkozp** [comment]
check your secret key

**Comment by TarrahArshad** [comment]
> check your secret key

its correct on sport wallet work fine but oin future not work and i checked future feature checked

**Comment by nikkozp** [comment]
for spot and futures, do you use different keys?

**Comment by TarrahArshad** [comment]
> for spot and futures, do you use different keys?

no i use same

**Comment by nikkozp** [comment]
separate keys are created for futures

**Comment by TarrahArshad** [comment]
> separate keys are created for futures

where i create ? i use mainnet no test

**Comment by TarrahArshad** [comment]
http://snap.ashampoo.com/8X5vXbSwNcUiDctCxQoFLt1hlMNl5Eh35erUFfmthc3lepN4A5cMq6T3KChHhOeE

see just i ckecked future but not work

**Comment by TarrahArshad** [comment]
> Checked on the `testnet` `Client.GetFuturesAccountBalance();` - working

what is testnet how to i create testnet api and how to set testnet ?

**Comment by nikkozp** [comment]
```csharp
public BinanceFuturesClient Client = new BinanceFuturesClient(new BinanceFuturesClientOptions("https://testnet.binancefuture.com")
        {
            LogVerbosity = LogVerbosity.Debug,
            LogWriters = new List<TextWriter> { Console.Out }
        });
```

**Comment by TarrahArshad** [comment]
> ```cs
> public BinanceFuturesClient Client = new BinanceFuturesClient(new BinanceFuturesClientOptions("https://testnet.binancefuture.com")
>         {
>             LogVerbosity = LogVerbosity.Debug,
>             LogWriters = new List<TextWriter> { Console.Out }
>         });
> ```

where i can crate testnetapi ?
an what is mainnet address ?

**Comment by TarrahArshad** [comment]
error is stile
http://snap.ashampoo.com/kmCwlv8LCYfxSEZXxuAuPMl21xF02NPg1s5gI2sluXdi57busBJCoU7JMejIRYOM

**Comment by TarrahArshad** [comment]
solved now work fine

**Comment by TarrahArshad** [comment]
on mainnet code work fine but in testnet not work show invalid api.
i not found api area for testaccount u can help me?

**Comment by TarrahArshad** [comment]
http://snap.ashampoo.com/BDsznEtvYjPwozjsuzs8QX0wfIaVKdgmhygu7ZKxD2osvXfkRxIDqIZvrZL57sjf

**Comment by TarrahArshad** [comment]
your code not work on testnet i have error can't continue

**Comment by nikkozp** [comment]
One key for spot and futures, and another for testnet

**Comment by TarrahArshad** [comment]
> One key for spot and futures, and another for testnet

where i can crate api key for testnet ?

**Comment by nikkozp** [comment]
![image](https://user-images.githubusercontent.com/11537426/77008904-4ba6ec00-6967-11ea-94da-46cf7c0aecd7.png)

**Comment by TarrahArshad** [comment]
> https://testnet.binancefuture.com/en/futures/BTCUSDT
> ![image](https://user-images.githubusercontent.com/11537426/77008904-4ba6ec00-6967-11ea-94da-46cf7c0aecd7.png)

now i connected and work fine but event of order and balance and position after updates not handle

                var Account = await Ws.SubscribeToUserDataUpdatesAsync(listenKey.Data,
                                Balance =>
                                {
                                    //  label1.Text = Balance.WalletBalance.ToString();

                                },
                                Position =>
                                {
                                    grvPosition.DataSource = Position;
                                },
                                Order =>
                                {
                                    grvPosition.DataSource = Order;

                                },
                                ListenKeyExpired =>
                                {

                                }).ConfigureAwait(false);

**Comment by nikkozp** [comment]
year, error on JsonProperty
send RP #293  https://github.com/JKorf/Binance.Net/pull/293/commits/4889ebd0237fbf00f21e3febcac1129642bc94e2

**Comment by TarrahArshad** [comment]
> year, error on JsonProperty
> send PR #293 [4889ebd](https://github.com/JKorf/Binance.Net/commit/4889ebd0237fbf00f21e3febcac1129642bc94e2)

but nothing show error . code do not have a error

**Comment by nikkozp** [comment]
You have 2 options
1. Wait for @JKorf to add my PR
2. Use my fork to test the update now

**Comment by TarrahArshad** [comment]
> You have 2 options
> 
> 1. Wait for @JKorf to add my PR
> 2. Use my fork to test the update now

how to test ur fork ? update ?

**Comment by nikkozp** [comment]
download and Compile `Binance.Net` from my account

**Comment by TarrahArshad** [comment]
> download and Compile `Binance.Net` from my account

download or update byt nuget ?

**Comment by nikkozp** [comment]
No, without nuget, just as a project

**Comment by TarrahArshad** [comment]
> No, without nuget, just as a project

but i need use my current project how to add to my project i never before use that

**Comment by JKorf** [comment]
I've pushed alpha8 version to nuget, should be available in a few minutes

**Comment by TarrahArshad** [comment]
error
http://snap.ashampoo.com/4U39eCfemmrwZRXItAs8BPGYQcLlakJ4aF3eIbivNzmimfrAge9HTgbFiMQIx1Fx

**Comment by nikkozp** [comment]
`BinanceSocketClientOptions` uses the new `using Binance.Net.Objects.Spot`. Check in your code

**Comment by TarrahArshad** [comment]
> using Binance.Net.Objects.Spot

i added but stile error

**Comment by TarrahArshad** [comment]
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Windows.Forms;
using Binance.Net;
using Binance.Net.Objects;
using CryptoExchange.Net.Authentication;
using CryptoExchange.Net.Logging;

using System.IO;
using Telerik.WinControls.UI;
using BinanceBOT.Model;
using System.Linq;

using Binance.Net.Objects.Spot;
using Binance.Net.Objects.Futures;

namespace BinanceBot.Wizo
{
    public partial class frmFutures : Telerik.WinControls.UI.RadForm
    {
        public frmFutures()
        {
            InitializeComponent();
        }

        private async void frmFutures_Load(object sender, EventArgs e)
        {
            try
            {


                new BinanceBOT.Connector.BinanceApi(AppSettings.GetApiKey(), AppSettings.GetSecretKey());


                //  var successFuture = socketClientF.GetFuturesAccountBalance();

                BinanceFuturesSocketClient Ws = new BinanceFuturesSocketClient();
                BinanceFuturesClient Client = new BinanceFuturesClient(new BinanceFuturesClientOptions("https://testnet.binancefuture.com")
                {
                    LogVerbosity = LogVerbosity.Debug,
                    LogWriters = new List<TextWriter> { Console.Out }
                });

                Client.SetApiCredentials(AppSettings.GetApiKey(), AppSettings.GetSecretKey());
                Ws.SetApiCredentials(AppSettings.GetApiKey(), AppSettings.GetSecretKey());



                var listenKey = await Client.StartUserStreamAsync().ConfigureAwait(false);

                var bf = Client.GetFuturesAccountBalance();
               // lblFutureBalance.Text = string.Format("Future Balance ${0} - BND{1}", bf.Data.ToList()[0].Balance, bf.Data.ToList()[1].Balance);

                // label1.Text = Client.GetFuturesAccountBalance().Data;

                var Account = await Ws.SubscribeToUserDataUpdatesAsync(listenKey.Data,
                                Balance =>
                                {
                                    //  label1.Text = Balance.WalletBalance.ToString();

                                },
                                Position =>
                                {
                                    grvPosition.DataSource = Position;
                                },
                                Order =>
                                {
                                    grvPosition.DataSource = Order;

                                },
                                ListenKeyExpired =>
                                {

                                }).ConfigureAwait(false);

            }
            catch (Exception ex)
            {
                // txtLogs.Text += $"\n ${ex.Message}";
            }
        }
    }
}

**Comment by nikkozp** [comment]
you use `testnet `for the client, and `mainnet `for sockets. Use one thing

**Comment by TarrahArshad** [comment]
> you use `testnet `for the client, and `mainnet `for sockets. Use one thing

its correct ?

                BinanceFuturesSocketClient Ws = new BinanceFuturesSocketClient(new BinanceFuturesSocketClientOptions("https://testnet.binancefuture.com") {
                    LogVerbosity = LogVerbosity.Debug,
                    LogWriters = new List<TextWriter> { Console.Out }
                });

**Comment by nikkozp** [comment]
```csharp
public BinanceFuturesSocketClient Ws = new BinanceFuturesSocketClient(new BinanceFuturesSocketClientOptions("wss://stream.binancefuture.com/ws/")
        {
            BaseAddress = "wss://stream.binancefuture.com/ws/",
            BaseSocketCombinedAddress = "wss://stream.binancefuture.com/",
            LogVerbosity = LogVerbosity.Debug,
            LogWriters = new List<TextWriter> { Console.Out },
        });
```

**Comment by TarrahArshad** [comment]
new erro show
http://snap.ashampoo.com/FDchPogvLSCdL2YirwejRKvlzZw69sSfwUmGDS4pg0ss1m1MD0wVKmcEhyCgLvlC

**Comment by TarrahArshad** [comment]
good now work fine and i recive positions and order and balance realtime
one question
when i recieve balance poistion and order is changed or no everytime i recive ?

**Comment by nikkozp** [comment]
You always get the balance first , then the position and orders. At Binance, this is done perfectly, unlike other exchanges. Based on my experience.

**Comment by TarrahArshad** [comment]
> You always get the balance first , then the position and orders. At Binance, this is done perfectly, unlike other exchanges. Based on my experience.

great thank u 
i going to complext my project binance future UI is slow and i will implement myself platform for fast and easy trade stop losee take profite close or join to pump

**Comment by TarrahArshad** [comment]
hi
i need know how to get realtime Trades , OrderBook , Depth , Chart , Market Price and price of all coin available in binance future in same time , and other data Funding/8h 24h changes , 24h high and 24h low and 25h volume
and for calculator its have api we call or need we implement myself if yes where is formula for calc PNL ROE
