### ISSUE TITLE
Stream Disconnect after a few days although KeepAlive is sent

### ISSUE THREAD

**Issue by gensleralexander** [JKorf/Binance.Net#292]
I'm currently having problems with SubscribeToUserDataUpdates().
I'm opening the stream and sending a KeepAlive every 30 Minutes.
This works well for a few days, but after some days (7-10 days were the cases I have experienced), the stream seems to close, as I don't get any account updates anymore.

Anyone experienced the same problems?
Or maybe some advices on how to track the problem down?

You can find the code [here at line 145](https://github.com/gensleralexander/JACB/blob/master/JACB.Library.UWP/Account/AccountInformationStream.cs)

**Comment by nikkozp** [comment]
try to added

```csharp
callResult.Data.ConnectionLost += () => {  };
callResult.Data.ConnectionRestored += (e) => { ); 
callResult.Data.Exception += (ex) => {  };
```

**Comment by gensleralexander** [comment]
@nikkozp Thank you very much!

**Comment by Hulkstance** [comment]
@gensleralexander, @nikkozp, doesn't `ReconnectInterval = TimeSpan.FromMinutes(1)` mean that?

```csharp
_socketClient = new BinanceSocketClient(new BinanceSocketClientOptions()
{
	ApiCredentials = new ApiCredentials(apiKey, secretKey),
	AutoReconnect = true,
	ReconnectInterval = TimeSpan.FromMinutes(1)
});
```

Or it is necessary to add the one you said?
