### ISSUE TITLE
Disconnecting stream after a few days question (not issue)

### ISSUE THREAD

**Issue by Hulkstance** [JKorf/Binance.Net#294]
I saw https://github.com/JKorf/Binance.Net/issues/292 and a few similar issues, that they should be fixed as following:

```csharp
callResult.Data.ConnectionLost += () => {  };
callResult.Data.ConnectionRestored += (e) => { ); 
callResult.Data.Exception += (ex) => {  };
```

Isn't `ReconnectInterval = TimeSpan.FromMinutes(1)` also supposed to do that?

```csharp
_socketClient = new BinanceSocketClient(new BinanceSocketClientOptions()
{
	ApiCredentials = new ApiCredentials(apiKey, secretKey),
	AutoReconnect = true,
	ReconnectInterval = TimeSpan.FromMinutes(1)
});
```

If not, what does it do?

If yes, how could you reconnect all 3 subscriptions in this case? Or there is a way to reconnect the entire BinanceSocketClient? 

```csharp
public event BinanceKlineStateHandler KlineEvent;
public delegate void BinanceKlineStateHandler(BinanceStreamKline Kline);

_socketClient.SubscribeToKlineUpdates(Symbols, KlineInterval.OneHour, data =>
{
	KlineEvent?.Invoke(data);
});

_socketClient.SubscribeToKlineUpdates(Symbols, KlineInterval.TwoHours, data =>
{
	KlineEvent?.Invoke(data);
});

_socketClient.SubscribeToKlineUpdates(Symbols, KlineInterval.FourHours, data =>
{
	KlineEvent?.Invoke(data);
});

//Class2
public void Start(Bot bot, CancellationToken token)
{
    KlineEvent += (BinanceStreamKline Kline) => { /* TODO */ };
}
```

or reconnecting one reconnects all of them?

```csharp
public event BinanceKlineStateHandler KlineEvent;
public delegate void BinanceKlineStateHandler(BinanceStreamKline Kline);

var subResult = _socketClient.SubscribeToKlineUpdates(Symbols, KlineInterval.OneHour, data =>
{
	KlineEvent?.Invoke(data);
}).Data;

subResult.ConnectionLost += () =>
{
	Console.ForegroundColor = ConsoleColor.Red;
	Console.WriteLine("Connection dropped.");
	Console.ResetColor();
};

subResult.ConnectionRestored += (e) =>
{
	Console.ForegroundColor = ConsoleColor.Green;
	Console.WriteLine("Connection restored.");
	Console.ResetColor();
};

_socketClient.SubscribeToKlineUpdates(Symbols, KlineInterval.TwoHours, data =>
{
	KlineEvent?.Invoke(data);
});

_socketClient.SubscribeToKlineUpdates(Symbols, KlineInterval.FourHours, data =>
{
	KlineEvent?.Invoke(data);
});

//Class2
public void Start(Bot bot, CancellationToken token)
{
    KlineEvent += (BinanceStreamKline Kline) => { /* TODO */ };
}
```

I tried the code above I got the following messages when I disconnected my Wi-Fi:

```
Connection dropped. Current time: 3/22/2020 11:04:10 AM
5m | Open time: 3/22/2020 11:00:00 AM
Connection restored. Current time: 3/22/2020 11:05:11 AM
```
Connection dropped message was too slow (it came up when I reconnected to the Wi-Fi.
Connection restored was slow as well.
5m's socket message was before the restoration because there are 3 separate subscriptions. Is there any way to involve all those 3 subscriptions, so that restoration message pops first? Something like don't let any message come out until all 3 subscriptions are back.

**Comment by walterX12** [comment]
I suppose, you have tested that your solution is OK. I did similar test some time ago and I rely on following code:

`            BinanceSocketClient.SetDefaultOptions(new BinanceSocketClientOptions()
            {
                ApiCredentials = new ApiCredentials(ApiKey, ApiSecret),
                AutoReconnect = true,
                ReconnectInterval = new TimeSpan(0,0,5),
                SocketNoDataTimeout = new TimeSpan(0, 0, 10)
            });`

I am having client subscibed for 30 days already and I do not experience any issues. Have you come accross any issue ?

**Comment by Hulkstance** [comment]
@walterX12, thank you! I haven't experienced any issues even with mine. I asked it because there was an issue/question on GitHub.
