### ISSUE TITLE
SubscribeToAllMarkPriceUpdatesAsync not working

### ISSUE THREAD

**Issue by TarrahArshad** [JKorf/Binance.Net#295]
i need realtime get price but this method bnot work
     var market = Ws.SubscribeToAllMarkPriceUpdatesAsync(3,
                    onMessage =>
                    {
                        DataBind(onMessage, "market");
                        DataBind(null, "");
                    }
                    );

**Comment by nikkozp** [comment]
Update Speed: 3000ms or 1000ms

```csharp
var MarkPrice = await Ws.SubscribeToAllMarkPriceUpdatesAsync(1000, MarkPrices =>
            {
            }).ConfigureAwait(false);
```

**Comment by TarrahArshad** [comment]
> Update Speed: 3000ms or 1000ms
> 
> ```cs
> var MarkPrice = await Ws.SubscribeToAllMarkPriceUpdatesAsync(1000, MarkPrices =>
>             {
>             }).ConfigureAwait(false);
> ```

great thank u

**Comment by TarrahArshad** [comment]
now code work fine but its market price i need future price

**Comment by nikkozp** [comment]
```csharp
var Ticker = await Ws.SubscribeToAllTickerUpdatesAsync(Tickers =>
            {
            }).ConfigureAwait(false);
```

**Comment by TarrahArshad** [comment]
> ```cs
> var Ticker = await Ws.SubscribeToAllTickerUpdatesAsync(Tickers =>
>             {
>             }).ConfigureAwait(false);
> ```

that good
