### ISSUE TITLE
Getting trading history

### ISSUE THREAD

**Issue by Hulkstance** [JKorf/Binance.Net#296]
I wanted to get the trade history. Here is what I did. Did I do everything alright? Because there are multiple BinanceClient trade methods, e.g. GetHistoricalSymbolTrades, GetAggregatedTrades, etc. 
As far as I can see, the different between all of them is the different criteria/different input properties. https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#recent-trades-list

I also don't find a property for order's side (buy/sell). How do I know if the trade is bought/sold?

```csharp
public List<BinanceStreamTrade> Trades { get; set; }

private void GetTrades(string symbol)
{
	var trades = _client.GetSymbolTrades(symbol);

	while (!trades.Success)
	{
		trades = _client.GetSymbolTrades(symbol);
	}

	var binanceTrades = new List<BinanceStreamTrade>();

	foreach (BinanceRecentTrade price in trades.Data)
	{
		binanceTrades.Add(new BinanceStreamTrade
		{
			TradeId = price.Id,
			Price = price.Price,
			Quantity = price.Quantity,
			TradeTime = price.Time,
			BuyerIsMaker = price.IsBuyerMaker
		});
	}

	Trades = binanceTrades;

	_socketClient.SubscribeToTradeUpdates(symbol, (data) =>
	{
		if (data.TradeId != binanceTrades.Last().TradeId)
			binanceTrades.Add(data);
	});
}

// Main.cs
GetTrades("TRXUSDT");

foreach (var trade in Trades)
{
	Console.WriteLine($"Id: {trade.TradeId} | Price: {trade.Price} | Quantity: {trade.Quantity} | {trade.TradeTime}");
}
```

![image](https://user-images.githubusercontent.com/33224919/77377012-99ae5c00-6d7a-11ea-8213-652331dfed45.png)

You can see on the picture that there are buy/sell orders (green/red).

**Comment by JKorf** [comment]
Seems fine to me. The different methods request different data. From the top of my head:
GetSymbolTrades -> most recent trades on a market
GetHistoricalSymbolTrades -> older trades (I think this is the same as GetSymbolTrades if you don't specify the fromId, however it has a weight of 5 while the other has 1)
GetAggregatedTrades -> gets trades but combines trade which have the same price into a combined quantity

The way you make a difference between buy/sell is provided by the IsBuyerMaker. If the buyer is the maker, that means the order was on the Bids list, and someone filled it by selling -> sell. If the buyer is the taker that means the order was on the Asks list and someone filled it by buying -> buy

**Comment by Hulkstance** [comment]
> 
> 
> Seems fine to me. The different methods request different data. From the top of my head:
> GetSymbolTrades -> most recent trades on a market
> GetHistoricalSymbolTrades -> older trades (I think this is the same as GetSymbolTrades if you don't specify the fromId, however it has a weight of 5 while the other has 1)
> GetAggregatedTrades -> gets trades but combines trade which have the same price into a combined quantity
> 
> The way you make a difference between buy/sell is provided by the IsBuyerMaker. If the buyer is the maker, that means the order was on the Bids list, and someone filled it by selling -> sell. If the buyer is the taker that means the order was on the Asks list and someone filled it by buying -> buy

Thanks! I was curious why do Binance merges some trades but you already answered me with that :)
