### ISSUE TITLE
How to get Candlestick data ?

### ISSUE THREAD

**Issue by TarrahArshad** [JKorf/Binance.Net#298]
i need bind data to my chartview How to get Candlestick data ?

**Comment by TarrahArshad** [comment]
i found this
                var candles = Client.GetKlines("BTCUSDT", Binance.Net.Enums.KlineInterval.OneHour);
                DataBind(candles.Data, "candles");

**Comment by dante1989** [comment]
Do you know how to get Future (not exchange) Candlestick  data? i'm finding this. Thank you
