### ISSUE TITLE
Project is VS2017 only

### ISSUE THREAD

**Issue by algotek** [JKorf/Binance.Net#3]
The project not open on VS2015, the project format is in VS2017
Provide VS2015 SLN/CSPROJ

**Comment by BenVlodgi** [comment]
[Visual Studio 2017 Community](https://www.visualstudio.com/) is free.

**Comment by JKorf** [comment]
As @BenVlodgi mentioned, you could download VS2017 if you need to open it. I don't intend to change the csproj file.
