### ISSUE TITLE
OrderId missing in BinanceTrade class

### ISSUE THREAD

**Issue by Episodex** [JKorf/Binance.Net#30]
I need to check Fills of my TakeProfit order that was filled in whole. I can't see this data in any Orders endpoint in Binance API, so I guess, I need to use myTrades endpoint for this.

The problem is that in Binance API docs there is OrderId field returned when I query for myTrades and Binance.Net does not return this field and I can't match trades with my order.

Is it a bug or should I query this data different way?

**Comment by JKorf** [comment]
You're right, that field is apparently missing. Should be fixed later today.

**Comment by JKorf** [comment]
Should be fixed in the latest version!

**Comment by Episodex** [comment]
Thanks for great work!
