### ISSUE TITLE
Add missing optional Network parameter to Withdraw methode

### ISSUE THREAD

**Issue by philipp-troxler** [JKorf/Binance.Net#303]
We have to do a lot of small USDT withdrawals and with the TRC20 network the fee can be saved.

**Comment by JKorf** [comment]
Hi, It's been added in the 5.1.1 version

**Comment by philipp-troxler** [comment]
great, thank you very much

**Comment by mdm183** [comment]
Hi, i have the exact same issue and have tried to use the networkID as per the update, but i am seeing an error of 4001 (Invalid Operation). I get this error when i pass in the network ID, i have tried 'Tron' and 'TRC20' but same issue. Could you please advise what it needs to be ? If i remote the network ID, it defaults back to ETH and works. However i need to pass in for TRC20
