### ISSUE TITLE
Downloading historical candle data

### ISSUE THREAD

**Issue by Hulkstance** [JKorf/Binance.Net#304]
I'm about to code backtesting and I'm curious how do people in Gekko and other bots download historical data for a larger period of time e.g. xx/xx/2013 - xx/xx/2014.

BinanceClient.GetKlines allows up to 1000 candles at a time.

```csharp
public class Importer
{
	public void Download(string symbol, KlineInterval interval)
	{
		using var client = new BinanceClient();
		client.GetKlines(symbol, interval, limit: 1000);
	}
}
```

**Comment by nikkozp** [comment]
[Binance docs](https://binance-docs.github.io/apidocs/spot/en/#kline-candlestick-data)

**Comment by Hulkstance** [comment]
> 
> 
> [Binance docs](https://binance-docs.github.io/apidocs/spot/en/#kline-candlestick-data)

No no, I know that. I'm talking about larger array of data e.g. candles for 1 year.

There is one solution I can think of with `client.GetKlines` and it is to do `client.GetKlines` with startDate/endDate args until we get the data for 1 year but I thought there might be another solution.

**Comment by McoreD** [comment]
Is it actually possible to download like 1 year of historical prices using this API? That would be awesome!

**Comment by nikkozp** [comment]
You can upload all the binance data via `client.GetKlines`, but it will be returned 1000 items at a time

**Comment by walterX12** [comment]
Make sure to use AddRateLimiter
e.g.             binanceClient.AddRateLimiter(new RateLimiterTotal(xxxx);

**Comment by Hulkstance** [comment]
Thank you for your advices. Closing it for now.
