### ISSUE TITLE
Data is loss if connection restored

### ISSUE THREAD

**Issue by NektoDron** [JKorf/Binance.Net#307]
In the event of a disconnection, the library restores sockets, but at the same time ticks may be skipped, and you won’t even know about it. How to make the library signal that the connection is broken and you need to do reinitialization manually?

**Comment by nikkozp** [comment]
https://github.com/JKorf/Binance.Net/issues/292#issuecomment-599669923

**Comment by JKorf** [comment]
As @nikkozp linked, you can add event handlers on the result of a subscription call.
````C#
callResult.Data.ConnectionLost += () => {  };
callResult.Data.ConnectionRestored += (e) => { ); 
callResult.Data.Exception += (ex) => {  };
````
