### ISSUE TITLE
Futures NewOrder Parameters

### ISSUE THREAD

**Issue by himura1123** [JKorf/Binance.Net#308]
Hi, I am using your library well.

BinanceFuturesClient.PlaceOrder Method is not positionSide(BOTH, LONG, SHORT) parameter.
I need positionSide parameter.

https://binance-docs.github.io/apidocs/testnet/en/#new-order-trade

Thank You.

**Comment by JKorf** [comment]
Hi, it's been added in the 5.1.1 version.
