### ISSUE TITLE
dont work futures change leverage 

### ISSUE THREAD

**Issue by kirill190497** [JKorf/Binance.Net#309]
var le = client.ChangeInitialLeverage("BTCUSDT", 50);
le.Data.Leverage // always null

**Comment by JKorf** [comment]
Hi, it is implemented as described in the docs; https://binance-docs.github.io/apidocs/futures/en/#change-initial-leverage-trade
Can you have a look at the data returned to see if that differs from the docs?
If you enable Debug logging in the client options you can see the data in you debug output.

**Comment by JKorf** [comment]
Hi, this should be fixed in version 5.1.1, let me know if it doesn't work
