### ISSUE TITLE
Thread-safety while initiating subscriptions

### ISSUE THREAD

**Issue by asymetrixs** [JKorf/Binance.Net#310]
Hi,
I want to know if the library is thread-safe when subscribing to streams.

When following the traditional way (one after the other) it takes around one+ second per subscription.

```
await this._binanceSocketClient.SubscribeToKlineUpdatesAsync(symbol, KlineInterval.OneMinute, (BinanceStreamKlineData bskd) => { ... });
await this._binanceSocketClient.SubscribeToKlineUpdatesAsync(symbol, KlineInterval.FiveMinute, (BinanceStreamKlineData bskd) => { ... });
await this._binanceSocketClient.SubscribeToKlineUpdatesAsync(symbol, KlineInterval.FifteenMinute, (BinanceStreamKlineData bskd) => { ... })
```

Instead I want to subscribe using Task.WhenAll which seems to work, but maybe I am just lucky:

```
var subscribeTasks = new List<Task<CallResult<UpdateSubscription>>>();
subscribeTasks.Add(this._binanceSocketClient.SubscribeToKlineUpdatesAsync(symbol, KlineInterval.OneMinute, (BinanceStreamKlineData bskd) => {...}));
subscribeTasks.Add(this._binanceSocketClient.SubscribeToKlineUpdatesAsync(symbol, KlineInterval.FiveMinute, (BinanceStreamKlineData bskd) => {...}));
subscribeTasks.Add(this._binanceSocketClient.SubscribeToKlineUpdatesAsync(symbol, KlineInterval.FifteenMinute, (BinanceStreamKlineData bskd) => {...}));

await Task.WhenAll(subscribeTasks.ToArray()).ConfigureAwait(true);
```

Can you please clarify, thanks.
Apart from that, your library is awesome.

**Comment by JKorf** [comment]
Hi, your second method should work fine. If not please let me know, but I haven't had any issues with it. You might still want to limit the amount of calls done in parallel, I don't know if Binance has any measures in place to block clients sending hundreds of requests at the same time.

**Comment by asymetrixs** [comment]
Hi, thanks. Yes it works good. Haven't seen any problem so far.
