### ISSUE TITLE
MaxNumberOrders Null value exception

### ISSUE THREAD

**Issue by eros1453** [JKorf/Binance.Net#314]
Hi
I have updated to alpha09 after GetExchangeInfo issue.
I'm still getting Deserialization error (MaxNumberOrders Null value exeption).
Looking in the code looks fine.
Received data is like this:

"timezone":"UTC",
"serverTime":1588499325223,
"rateLimits":[{
"rateLimitType":"REQUEST_WEIGHT",
"interval":"MINUTE",
"intervalNum":1,
"limit":2400},
{"rateLimitType":"ORDERS",
"interval":"MINUTE",
"intervalNum":1,"limit":1200}],
"exchangeFilters":[],
"symbols":[
{
"symbol":"BTCUSDT",
"status":"TRADING",
"maintMarginPercent":"2.5000",
"requiredMarginPercent":"5.0000",
"baseAsset":"BTC",
"quoteAsset":"USDT",
"pricePrecision":2,
"quantityPrecision":3,
"baseAssetPrecision":8,
"quotePrecision":8,
"filters":[
{"minPrice":"0.01","maxPrice":"100000","filterType":"PRICE_FILTER","tickSize":"0.01"},
{"stepSize":"0.001","filterType":"LOT_SIZE","maxQty":"1000","minQty":"0.001"},
{"stepSize":"0.001","filterType":"MARKET_LOT_SIZE","maxQty":"2775.517","minQty":"0.001"},
{"limit":0,"filterType":"MAX_NUM_ORDERS"},
{"limit":0,"filterType":"MAX_NUM_ALGO_ORDERS"},
{"multiplierDown":"0.7000","multiplierUp":"1.3000","multiplierDecimal":"4","filterType":"PERCENT_PRICE"}],
"orderTypes":["LIMIT","MARKET","STOP","STOP_MARKET","TAKE_PROFIT","TAKE_PROFIT_MARKET"],
"timeInForce":["GTC","IOC","FOK","GTX"]},

**Comment by eros1453** [comment]
![resim](https://user-images.githubusercontent.com/8195310/80912137-9330de00-8d43-11ea-8dcf-270a1d13fb4a.png)

**Comment by nikkozp** [comment]
#300
@JKorf

**Comment by eros1453** [comment]
Solved
Converters/SymbolFilterConverters.cs
"
case SymbolFilterType.MaxNumberOrders:
                    result = new BinanceSymbolMaxOrdersFilter
                    {
                        MaxNumberOrders = (int)obj["limit"]
                    };
                    break;

                case SymbolFilterType.IcebergParts:
                    result = new BinanceSymbolIcebergPartsFilter
                    {
                        Limit = (int)obj["limit"]
                    };
                    break;
"
