### ISSUE TITLE
What would be the best solution for SELL using MARKET for 100% of base asset

### ISSUE THREAD

**Issue by tkowalczyk** [JKorf/Binance.Net#317]
I have research this repository back and forth and still have one question.

I am using `MARKET` as a type of my order and buying (spending quote asset is clear for me) as follows:

    var availableQuote = accountInfo.Data.Balances.FirstOrDefault(e => e.Asset == quoteAsset).Free;
    var buyOrderResult = await client.PlaceOrderAsync(
                                                    availableStrategy.Symbol,
                                                    OrderSide.Buy,
                                                    OrderType.Market,
                                                    quoteOrderQuantity: availableQuote);

I would like also to calculate the quantiny of quote asset I would get to use 100% of my base asset as follows:

    var availableBase = accountInfo.Data.Balances.FirstOrDefault(e => e.Asset == baseAsset).Free;
    var q = ClampQuantity(symbol, price * availableBase);

                                                var sellOrderResult = await client.PlaceOrderAsync( 
                                                    availableStrategy.Symbol,
                                                    OrderSide.Sell,
                                                    OrderType.Market,
                                                    quoteOrderQuantity: q);

where `ClampQuantity` I took from here: https://github.com/JKorf/Binance.Net/issues/272#issuecomment-586179045

but it still left some small change. What would be the best method to calculate `quoteOrderQuantity` while using `OrderSide.Sell` and `OrderType.Market` ?

**Comment by nikkozp** [comment]
Hi. I would recommend using `Quantity `for `Sell`, since you know the number of coins in advance. And `quoteOrderQuantity `for `Buy`.

**Comment by tkowalczyk** [comment]
Yeah, thank you but still something is not clear for me.

I am trading on symbol `ETHBTC` and using below code for calculate available `BASE` and `QUOTE`:

    var availableBase = accountInfo.Data.Balances.FirstOrDefault(e => e.Asset == baseAsset).Free;
    var availableQuote = accountInfo.Data.Balances.FirstOrDefault(e => e.Asset == quoteAsset).Free;

In my opinion when we want to:

`SELL` on `MARKET` with all of the `BASE` (here `ETH`) we have to use:

    var sellOrderResult = await client.PlaceOrderAsync(
                                                    availableStrategy.Symbol,
                                                    OrderSide.Sell,
                                                    OrderType.Market,
                                                    quantity: availableBase);

`BUY` on `MARKET` with all of the `QUOTE` (here `BTC`) we have to use:

    var buyOrderResult = await client.PlaceOrderAsync(
                                                    availableStrategy.Symbol,
                                                    OrderSide.Buy,
                                                    OrderType.Market,
                                                    quoteOrderQuantity: availableQuote);

Is this correct? or maybe I missed something?
