### ISSUE TITLE
Can we Rely on This Nuget Package | Are you Officially Appointed by Binance to develop client APIs ??

### ISSUE THREAD

**Issue by Shyam200408** [JKorf/Binance.Net#320]
Hi Team,
I was googling about Binance API, and I found your APIs which are quite handy to integrate.
But my concern is , can I rely on your APIs? are you certified/approved by Binance to develop C# clients for them ?

**Comment by JKorf** [comment]
Hi, I'm the author of the package, supported by the help I get from other developers who use the package as well, but I'm in no way affiliated with Binance and I develop/maintain this package in my own free time.

I do my best to keep the package updated, but I can't give you any guarantees, so you should make your own choice whether or not that is okay for you :)

**Comment by Shyam200408** [comment]
Thanks @JKorf
