### ISSUE TITLE
SymbolFilterConverter: MaxNumberOrders serialize/deserialize property name mismatch

### ISSUE THREAD

**Issue by anotherdeveloper** [JKorf/Binance.Net#321]
This relates to #312 

SymbolFilterConverter: MaxNumberOrders serialize/deserialize property name mismatch:

```
//deserialize
 case SymbolFilterType.MaxNumberOrders:
                    result = new BinanceSymbolMaxOrdersFilter
                    {
                        MaxNumberOrders = (int)obj["maxNumOrders"]
                    };
                    break;


//serialize
 case SymbolFilterType.MaxNumberOrders:
                    var orderFilter = (BinanceSymbolMaxOrdersFilter)filter;
                    writer.WritePropertyName("limit");
                    writer.WriteValue(orderFilter.MaxNumberOrders);
                    break;
```

**Comment by nikkozp** [comment]
fixed #323

**Comment by anotherdeveloper** [comment]
Any word on the pending merge?

**Comment by JKorf** [comment]
I'm currently working on getting al the new endpoints and changes in, will merge and make a new version soon.

**Comment by nikkozp** [comment]
@JKorf do you have a ping-pong answer implemented? I didn't find it anywhere in the code.

**Comment by anotherdeveloper** [comment]
if anyone isn't too busy, what's a ping-pong answer?

**Comment by anotherdeveloper** [comment]
or does it just depend on the ping-pong question?

**Comment by JKorf** [comment]
@nikkozp what do you mean by ping-pong answer?

**Comment by nikkozp** [comment]
@JKorf https://binance-docs.github.io/apidocs/spot/en/#websocket-market-streams `Ping frame` `Pong frame`

**Comment by JKorf** [comment]
Ah, yes it is handled by the Websocket4Net library used internally for websocket communication.

**Comment by JKorf** [comment]
@anotherdeveloper Merge is done, version 5.1.1 should work for everyone

**Comment by anotherdeveloper** [comment]
Thanks very much
