### ISSUE TITLE
How do we calculate fees?

### ISSUE THREAD

**Issue by Hulkstance** [JKorf/Binance.Net#322]
Here is the fee schedule from Binance: https://www.binance.com/en/fee/schedule.

The title is pretty self explanatory. I have the following output from my backtesting:
```
BUY | Open time: 2020/05/12 07:30 | Price: 0.01411000
SELL | Open time: 2020/05/12 09:00 | Price: 0.01421000
```

I want to calculate the fees if I buy at 0.01411000 and sell at 0.01421000.

There was a guy with a [similar question](https://github.com/JKorf/Binance.Net/issues/278), but his code is related to real orders, because they can be obtained through the REST API. Does Binance log the test orders somewhere (`client.PlaceTestOrder`), so we might calculate the fees that way?

Have somebody done that?

**Comment by nikkozp** [comment]
Hej
You can find your `VIP` for `Spot `here `Client.GetAccountInfo();`. And already according to the Commission calculate the approximate cost of the Commission.
For Margin or Futures, can use similar methods.

>client.PlaceTestOrder 
Test new order creation and signature/recvWindow long. Creates and validates a new order but does not send it into the matching engine.

The test order does not count the Commission, it only checks the validity of the specified parameter.

**Comment by Hulkstance** [comment]
> 
> 
> Hej
> You can find your `VIP` for `Spot `here `Client.GetAccountInfo();`. And already according to the Commission calculate the approximate cost of the Commission.
> For Margin or Futures, can use similar methods.
> 
> > client.PlaceTestOrder
> > Test new order creation and signature/recvWindow long. Creates and validates a new order but does not send it into the matching engine.
> 
> The test order does not count the Commission, it only checks the validity of the specified parameter.

![image](https://user-images.githubusercontent.com/33224919/81727077-131c1e00-9491-11ea-854d-7835cd371993.png)

I kinda don't understand how to calculate it.

I saw that website https://blockduo.com/binance-calculator/ and according to https://www.binance.com/en/fee/schedule, VIP 0 with BNB is 0.0750%.

![image](https://user-images.githubusercontent.com/33224919/81727258-5bd3d700-9491-11ea-9ec4-4c6b8d54f791.png)

Is that even accurate?

**Comment by nikkozp** [comment]
If I understand correctly, `10 `is `0.1%`
If you have enough `BNB`, then at the time of execution of the order, the binance itself will recalculate to `0.075%.`
There is also the `Client.GetTradeFee();` method but I prefer it for margin trading

**Comment by Hulkstance** [comment]
> 
> 
> If I understand correctly, `10 `is `0.1%`
> If you have enough `BNB`, then at the time of execution of the order, the binance itself will recalculate to `0.075%.`
> There is also the `Client.GetTradeFee();` method but I prefer it for margin trading

I have 1.52 BNB, which is weird that it says 10. 

Result from GetTradeFree():

![image](https://user-images.githubusercontent.com/33224919/81734825-cd655280-949c-11ea-907c-342374de5a47.png)

**Comment by CarlosPacheco** [comment]
GetTradeFree ->  Gets the withdrawal fee for an symbol

**Comment by Hulkstance** [comment]
Problem solved a long time ago. Closing this.

For these who wonder:

Buy orders: current balance / buy_price * tax_rate
Sell orders: current balance * sell_price * tax_rate

**Comment by frostrock7** [comment]
Have the same problem. Especially when you need to find out comission of past orders. Because it calculates in BNB and you need to know price of BNB when order was filled.
