### ISSUE TITLE
BinanceOrderBook object event time

### ISSUE THREAD

**Issue by mishavetl** [JKorf/Binance.Net#324]
[BinanceOrderBook.cs](https://github.com/JKorf/Binance.Net/blob/master/Binance.Net/Objects/BinanceOrderBook.cs) does not include event time member as seen at [Diff. Depth Stream](https://github.com/binance-exchange/binance-official-api-docs/blob/master/web-socket-streams.md#diff-depth-stream).

If I am not mistaken, event time information can be used to correctly identify the order book's snapshot creation timestamp.

**Comment by nikkozp** [comment]
you don't need time to do this, you need to use LastUpdateId

**Comment by mishavetl** [comment]
Thank you for your reply. If I need to create a history of order book based on time, what can I use?

**Comment by DanTheManGC** [comment]
@mishavetl  I am having your exact same issue.  I think BinanceOrderBook.cs should have a EventTime property as per your link to Binance documentation.  I don't see that LastUpdateId can be used to establish the time of the bid/ask prices either.  

I tried adding the following to BinanceOrderBook.cs...

        [JsonProperty("E"), JsonConverter(typeof(TimestampConverter))]
        public DateTime EventTime { get; set; }

...but got the following error...

2020/07/06 15:04:05:557 | Warning | Failed to deserialize data into type Binance.Net.Objects.BinanceCombinedStream`1[Binance.Net.Objects.Spot.MarketData.BinanceOrderBook]: 5: Error deserializing data Deserialize Unknown Exception: Input string was not in a correct format.. Received data: {
  "stream": "btcusdt@depth@100ms",
  "data": {
    "e": "depthUpdate",
    "E": 1594011844284,
    "s": "BTCUSDT",
    "U": 4833106939,
    "u": 4833106945,
    "b": [

Please let me know if you found a solution.

**Comment by DanTheManGC** [comment]
@mishavetl   If I add the following code to BinanceOrderBook.cs...

        [JsonProperty("E")]
        public string EventTime { get; set; } = "";

... then the EventTime gets populated with a Unix timestamp (EG "1594013457") which I can then convert to a DateTime in C#. 

Of course this isn't a great long term solution as we don't want to be editing Binance.NET source code with each new release.

**Comment by mishavetl** [comment]
@DanTheManGC You will probably need DateTimeOffset for precise timestamp storage. I am using the following class for event time deserialization.

```c#
    public class MillisecondEpochConverter : DateTimeConverterBase
    {
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            if (reader.Value == null) { return null; }
            return DateTimeOffset.FromUnixTimeMilliseconds((long) reader.Value);
        }
    }
```

**Comment by JKorf** [comment]
Hi, I've pushed version 5.1.9 which includes an EventTime property for this.
@DanTheManGC the reason you got the `Input string was not in a correct format` error is because it tried to deserialize lower case 'e' property as wel as the upper case 'E' property into the field. Lowercase e is a string value though, so that doesn't match. By adding the mapping for the lower case e as well as the upper case E Json.Net understands that they are case sensitive.

**Comment by DanTheManGC** [comment]
@JKorf @mishavetl  Ah... thank you both so much!
