### ISSUE TITLE
Get ledger data

### ISSUE THREAD

**Issue by Hulkstance** [JKorf/Binance.Net#325]
I wanted to get ledger's data and keep it updated for the last 20 orders. It has to be exactly like Binance's Desktop app speed-wise. I'm not quite sure what they use. I currently set the `updateInterval` to `null`. Any suggestions about the code?

https://binance-docs.github.io/apidocs/spot/en/#diff-depth-stream

> Update Speed: 1000ms or 100ms

```csharp
/// <summary>
/// Gets order book.
/// </summary>
public BinanceOrderBook OrderBook { get; set; }

/// <summary>
/// Subscribes to order book web socket.
/// </summary>
/// <param name="symbol"></param>
public void GetOrderBook(string symbol)
{
	var orderBook = Client.GetOrderBook(symbol, 20);

	while (!orderBook.Success)
	{
		var weight = BinanceHelpers.UsedWeight(orderBook.ResponseHeaders);
		StaticHelper.Instance.HandleRateLimits(weight.Value);

		orderBook = Client.GetOrderBook(symbol);
	}

	OrderBook = orderBook.Data;

	SocketClient.SubscribeToPartialOrderBookUpdates(symbol, 20, null, (data) => OrderBook = data);
}
```

This is how I tested it:

```csharp
GetOrderBook("BTCUSDT");

while (true)
{
	var orders = OrderBook.Asks.ToList();
	foreach (var order in orders)
		Console.WriteLine(order.Price);
	Thread.Sleep(100);
	Console.WriteLine();
}
```

**Comment by nikkozp** [comment]
Update interval in milliseconds, either 100 or 1000. Defaults to 1000

To avoid using while(true) and loading the processor with useless checks, I recommend using events when changing the order book. Personally, I use IObserver/IObservable

**Comment by Hulkstance** [comment]
> 
> 
> Update interval in milliseconds, either 100 or 1000. Defaults to 1000
> 
> To avoid using while(true) and loading the processor with useless checks, I recommend using events when changing the order book. Personally, I use IObserver/IObservable

Setting it to `null` was the correct timing.
