### ISSUE TITLE
No longer working with www.binance.com base address

### ISSUE THREAD

**Issue by HorstBock** [JKorf/Binance.Net#33]
All calls are no longer working with the base address: https://www.binance.com . For example https://www.binance.com/api/v1/ping gives an error but with https://api.binance.com/api/v1/ping

Can you make the base address adjustable or simple cahnge it to https://api.binance.com ?

**Comment by JKorf** [comment]
Hi, I didn't notice this, thanks for letting me know. It's been changed in the latest version (2.3.3) currently being pushed to nuget.

**Comment by HorstBock** [comment]
Thank you for the very quick fix. Now it's working again.
