### ISSUE TITLE
SubscribeToKlineUpdatesAsync problem

### ISSUE THREAD

**Issue by redquantum** [JKorf/Binance.Net#330]
Hello dear friend,
I have a bad problem.
When I want to connect a coin with the letter "i or I" in time, the socket does not return data. GetKline runs smoothly, but the socket does not fetch data. for example, ZILUSDT. Please try and tell about the problem. thank you.
I am trying to connect as follows.

string CoinSymbol = "ZILUSDT";

            CoinSymbol = CoinSymbol.ToUpper(new CultureInfo("en-US", true));

         if (list1Min.Count == 0)
            {
                list1Min = binanceClient.GetKlines(CoinSymbol, KlineInterval.OneMinute).Data.ToList();

            }
            if (list1Min.Count > 3)
            {
           await socketClient.SubscribeToKlineUpdatesAsync(CoinSymbol, KlineInterval.OneMinute, 
           data =>
                {
                   
                  CallCulateData1minListAsync(data, list1Min);
                  
                 });
            }

**Comment by jkorf-bloemert** [comment]
Hi,

This works for me:
````C#
await socketClient.SubscribeToKlineUpdatesAsync("ZILUSDT", KlineInterval.OneMinute,
              data =>  Console.WriteLine(data.Data.Close));
````
Can you put log verbosity to debug in the client options and check to see what the output is?

**Comment by JKorf** [comment]
Hi, I found the issue. I'm guessing you're from Turkey? Apparently when you call `ToLower()` on a string without specifying a culture (so it takes the local computer culture) the upper case `I` will be converted to a lower case `i` which is a different character as the default lower case `i`.

I've pushed a new version which should fix the issue for you.

**Comment by redquantum** [comment]
Hello Dear Friend.
Thank you for the help and update.

**Comment by redquantum** [comment]
I tested,it is working fine .. Thank you again ..

**Comment by HoLyDreaM** [comment]
Hello, in this section, when it enters this area, it enters an endless loop. There is no problem here, but how can we get it back to the beginning? So, how do I need to follow so that the system finishes its work and exits?
