### ISSUE TITLE
Socket stream stops receiving order updates

### ISSUE THREAD

**Issue by vahdetunal** [JKorf/Binance.Net#331]
Hello,

First, I would like to thank you for your work on this great library.

We are working on an application which uses Binance.Net. Recently, we have updated to version 5.1.2 and during our tests, we have encountered a problem.

Sometimes, socket stream stops getting order updates. REST requests keep working perfectly but no updates arrive from socket stream. I will share a part of our login code in case there is something you would like to check there.

```csharp
BinanceClient.SetDefaultOptions(new BinanceClientOptions()
{
    ApiCredentials = new ApiCredentials(message.CustomerNo, message.Password),
    LogVerbosity = LogVerbosity.Debug,
    LogWriters = new List<TextWriter> { debugTextWriter }
});
            
BinanceSocketClient.SetDefaultOptions(new BinanceSocketClientOptions()
{
    ApiCredentials = new ApiCredentials(message.CustomerNo, message.Password),
    LogVerbosity = LogVerbosity.Debug,
    LogWriters = new List<TextWriter> { debugTextWriter },
    AutoReconnect = true
});

_client = new BinanceClient();
_socketClient = new BinanceSocketClient();

var result = await _client.GetAccountInfoAsync();

// Skipping some code here for brevity
_listenKey = (await _client.StartUserStreamAsync()).Data;

var successAccount = _socketClient.SubscribeToUserDataUpdates(_listenKey,
                    data => { BinancePositionUpdate(data, account); },
                    orderData => { OnExecutionReport(orderData, account); },
                    accountMessage => { },
                    ocoMessage => { },
                    null);
```

Attached is a part of a log file from a session. At the time these logs were taken, we had a trading algorithm running. Starting from 2020.05.29 01:35:21.8298 there are only logs from REST messages. Logger times are in UTC+3. 

Thank you.

[BinanceLog.txt](https://github.com/JKorf/Binance.Net/files/4702469/BinanceLog.txt)

**Comment by JKorf** [comment]
Hi, thanks for the detailed report. Do you have any logic in place to send a keep alive for the listen key every < 30 minutes? Once you've started a user steam and got a listen key, you should send a keep alive within every 30 minutes or the server will stop sending data. Use the `KeepAliveUserStreamAsync` call for this.

**Comment by vahdetunal** [comment]
Thank you for the quick response.

Keep alive was what we had been missing. After implementing the logic to send periodic keep alives, we have been able to keep receiving stream order updates in sessions longer than 60 minutes.
