### ISSUE TITLE
Deserialisation error sending IOC order

### ISSUE THREAD

**Issue by tbrbde** [JKorf/Binance.Net#333]
Hi, with the latest version I get an deserialization error sending some IOC orders:
2020.06.02 09:12:33:602 | Debug | Data received: {"symbol":"ICXBNB","orderId":50615365,"orderListId":-1,"clientOrderId":"tg1xP8X96snen3okQAhYnx","transactTime":1591081955081,"price":"0.01915000","origQty":"10.00000000","executedQty":"0.70000000","cummulativeQuoteQty":"0.01340500","status":"EXPIRED","timeInForce":"IOC","type":"LIMIT","side":"BUY","fills":[{"price":"0.01915000","qty":"0.70000000","commission":"0.00001006","commissionAsset":"BNB","tradeId":1419170}]}
2020.06.02 09:12:33:611 | Error | Deserialize JsonSerializationException: Error setting value to 'Status' on 'Binance.Net.Objects.Spot.SpotData.BinancePlacedOrder'., data: 

It seems that the status "Expired" cannot be received correctly in this case.

Regards,
Jens

**Comment by JKorf** [comment]
Hi, I've fixed this in 5.1.3. The Expired status was missing a mapping.
Thanks for the report!

**Comment by JKorf** [comment]
Ah you're right, introduced a little bug. Will release a new nuget package later tonight or tomorrow morning. A little more patience ^^

**Comment by JKorf** [comment]
Should be fixed

**Comment by tbrbde** [comment]
Thanks! It is working now.
