### ISSUE TITLE
Signature for this request is not valid.

### ISSUE THREAD

**Issue by noahwalugembe** [JKorf/Binance.Net#334]
I am getting {Signature for this request is not valid. error } my code just work only for a small time and the stops. the cod blow has bean working for 4 weeks but now it gives me
{ Signature for this request is not valid. error}

PATH = '/api/v3/account'

timestamp = int(time.time() * 1000)
params = {
   
   'recvWindow': 5000,
   'timestamp': timestamp
}

query_string = urlencode(params)
params['signature'] = hmac.new(self.SECRET_KEY.encode('utf-8'), query_string.encode('utf-8'), hashlib.sha256).hexdigest()

url = urljoin(self.BASE_URL, PATH)
r = requests.get(url, headers=self.headers, params=params)

**Comment by JKorf** [comment]
This is not an official Binance repository, just a wrapper for C# to use the API
