### ISSUE TITLE
client.WithdrawAsync get error 'Signature for this request is not valid'

### ISSUE THREAD

**Issue by philipp-troxler** [JKorf/Binance.Net#336]
[BinanceWithdrawError.txt](https://github.com/JKorf/Binance.Net/files/4732444/BinanceWithdrawError.txt)

A few days ago the withdraw was working normally, but now the method returns an error. I have the feeling that the API has changed on the Binance side, but I'm not sure. (see https://binance-docs.github.io/apidocs/spot/en/#signed-trade-user_data-and-margin-endpoint-security)
Attached is the log when I run the Widthraw.

**Comment by JKorf** [comment]
Hi, thanks for the report. I'll look into it. Did you by any chance update to a new version of Binance.Net or did the same version you used before suddenly stopped working?

**Comment by philipp-troxler** [comment]
Hi. With version 5.0.7 the withdraw certainly worked on May 1st. On June 4th it didn't work with the same version. I have now switched to the latest version 5.1.4 and it still does not work.

**Comment by yetiwolf** [comment]
I get this same issue with DustTransfer

**Comment by JKorf** [comment]
Thanks for the info, I'm working on it.

**Comment by JKorf** [comment]
Hi guys, both issues should be fixed with the latest version. If you're still having problems please let me know!

**Comment by yetiwolf** [comment]
fixed. thanks!
