### ISSUE TITLE
How to get Klines from BTCUSDT Future, not exchange

### ISSUE THREAD

**Issue by dante1989** [JKorf/Binance.Net#337]
i'm using this code to get exchange's Klines btcusdt exchange

        Dim clientBinance = New BinanceClient 'API Tài Khoản Binance
        clientBinance.SetApiCredentials(API_Binance1, Secret_Binance1)
        Dim m1d As CallResult(Of IEnumerable(Of BinanceKline))
        m1d = Await clientBinance.GetKlinesAsync(Symbol, TickTimeFrame1d, fromtime, totime)
But, now I want to get future's Klines data instead of exchange. how do i get future data?
Thank you so much

**Comment by JKorf** [comment]
Hi, you'll need to use the futures client, which is separate from the normal client. For futures use the `BinanceFuturesClient` class.

**Comment by dante1989** [comment]
Thank you
