### ISSUE TITLE
Please remove IncomeType enum and makes string type for it

### ISSUE THREAD

**Issue by NektoDron** [JKorf/Binance.Net#338]
Please remove IncomeType enum and makes string type for it. It becouse Binance has undocumented income type. For example COMMISSION_REBATE and some other rebates.

**Comment by JKorf** [comment]
You mean in `GetIncomeHistory`?

**Comment by NektoDron** [comment]
yes

**Comment by JKorf** [comment]
I've changed it to a string in the latest version

**Comment by NektoDron** [comment]
good

**Comment by NektoDron** [comment]
parameters.AddOptionalParameter("incomeType", incomeType != null ? JsonConvert.SerializeObject(incomeType, new IncomeTypeConverter(false)) : null);
