### ISSUE TITLE
default http address

### ISSUE THREAD

**Issue by muteddisk** [JKorf/Binance.Net#34]
Is it possible to change the default hostname for binance API? With the ongoing issue with the servers right now....it won't let me use your API. I have to use host us.binance.com as www.binance.com ain't working due to a DDOS attack going at their cloud provider....

Thanks

**Comment by JKorf** [comment]
Hi, sorry for taking so long, but this is now available.

**Comment by muteddisk** [comment]
Lol no problems bud. I solved my issue in the mean time by adding their host to my hosts.ini.   




Thanks for the update.






Get Outlook for Android







On Tue, Mar 6, 2018 at 2:56 AM -0500, "Jan Korf" <notifications@github.com> wrote:












Hi, sorry for taking so long, but this is now available.
