### ISSUE TITLE
How to get initial leverage of symbol?

### ISSUE THREAD

**Issue by AtesDANIS** [JKorf/Binance.Net#340]
hi, I can set initial leverage but how can I get initial leverage of symbol on futures when the application start? thanks

**Comment by eros1453** [comment]
Hi
https://fapi.binance.com/fapi/v1/positionRisk is the point.
You can extract it from there.
Response will be like :
{
	"symbol":"BTCUSDT",
	"positionAmt":"-0.010",
	"entryPrice":"9333.69000",
	"markPrice":"9522.64831421",
	"unRealizedProfit":"-1.88958314",
	"liquidationPrice":"9705.90",
	**"leverage":"25",**
	"maxNotionalValue":"1000000",
	**"marginType":"isolated",**
	"isolatedMargin":"2.22070863",
	"isAutoAddMargin":"false",
	"positionSide":"BOTH"},
 {
	"symbol":"ETHUSDT",
	"positionAmt":"0.000",
	"entryPrice":"0.00000",
	"markPrice":"201.70978720",
	"unRealizedProfit":"0.00000000",
	"liquidationPrice":"0",
	**"leverage":"20",**
	"maxNotionalValue":"250000",
	**"marginType":"cross",**
	"isolatedMargin":"0.00000000",
	"isAutoAddMargin":"false",
	"positionSide":"BOTH"}

**Comment by AtesDANIS** [comment]
Thank you @eros1453 you are right. That end point on binance api gives leverages by symbols.
And I used

`BinanceFuturesClient futuresClient = new BinanceFuturesClient(new Binance.Net.Objects.Futures.BinanceFuturesClientOptions()
            {
                ApiCredentials = new ApiCredentials(myApiKey, myApiSecret),
                LogVerbosity = LogVerbosity.Debug,
                LogWriters = new List<TextWriter> { Console.Out }
            });

var openPositions = await futuresClient.GetOpenPositionsAsync();
`

this runs binance api as you said and I can reach default/last set leverages of symbols
