### ISSUE TITLE
Error: Margin is insufficient

### ISSUE THREAD

**Issue by dante1989** [JKorf/Binance.Net#341]
I'm trying make order Stop Limit in Binance Future by API: 

 Dim clientFutureBinance = New BinanceFuturesClient  'API Binance Future
        clientFutureBinance.SetApiCredentials(API_Binance2, Secret_Binance2)

        Dim Symbol As String = "BTCUSDT"

        Dim ItemFuturesAccountBalance As WebCallResult(Of IEnumerable(Of BinanceFuturesAccountBalance))
        ItemFuturesAccountBalance = Await clientFutureBinance.GetFuturesAccountBalanceAsync

        MsgBox(ItemFuturesAccountBalance.Data(0).Balance.ToString)

        Await clientFutureBinance.ChangeInitialLeverageAsync(Symbol, 50,)
        Await clientFutureBinance.ChangeMarginTypeAsync(Symbol, FuturesMarginType.Isolated)

        Dim ItemBuyLongBinance As WebCallResult(Of BinanceFuturesPlacedOrder)
        ItemBuyLongBinance = Await clientFutureBinance.PlaceOrderAsync(Symbol, BinanceOjectsOrderSide.Buy, BinanceOjectsOrderType.Stop, 1, price:=20000, stopPrice:=20000)

        MsgBox(ItemBuyLongBinance.Error.Message)

Result: My balance is 1000 USDT, but i got Error: Margin is insufficient
I have tested place order by manually, it is ok. I can put max (2.5 Bit) with Leverage X50 by manually, but API have that error for 2 bit, 1 bit, 0.5 bit. but 0.05 bit is success. Maybe something wrong

Could you help me to fix that error, thank you so much. Please put your comment with your USDT wallet, i want to donate for your hard working

**Comment by eros1453** [comment]
Price 20000 ?? Really

**Comment by dante1989** [comment]
i found the problem, because i use price 20K (so high)
