### ISSUE TITLE
BinanceFuturesClient GetExchangeInfo() Error

### ISSUE THREAD

**Issue by himura1123** [JKorf/Binance.Net#342]
Hi, I am using your library well.
'https://testnet.binancefuture.com' is go very well
But, 'https://fapi.binance.com' is Error

Error: {5: Error deserializing data ,"GTX"]}]}}

Please solve this problem.
Thanks.

**Comment by eros1453** [comment]
Hi
I got this problem before and solved it.
How did you solve it ?

**Comment by himura1123** [comment]
Hi, I couldn't solve it.
But, This problem occurs between 08:00 and 09:00 UTC.

**Comment by eros1453** [comment]
Check data for null return happens often.
Can be from your connection or anyting else.
You can go with "if (Result.Data != null) { }" maybe
