### ISSUE TITLE
GetAccountInfo() has started returning "404 Not found"

### ISSUE THREAD

**Issue by DanTheManGC** [JKorf/Binance.Net#347]
This error started occurring some time in the last 5 days.  I've tried updating to latest version of Binance.Net (5.1.8) but issue remains.

![image](https://user-images.githubusercontent.com/65847426/85252877-409cb400-b4a0-11ea-9b4e-9c8041a833f4.png)

Any assistance would be much appreciated, thank you.

**Comment by JKorf** [comment]
Hi, seems the Binance API is a bit unstable. Not much I can do about that. I suggest checking for success and using some sort of retry mechanism. Pseudo code:
````
for(var i = 0; i < maxRetries; i++){
  var accountInfoResult = client.GetAccountInfo();
  if(accountInfoResult.Success)
    break;
  Task.Delay(500);
}

````

**Comment by DanTheManGC** [comment]
No worries.  Thank you for looking into it.
