### ISSUE TITLE
SubscribeToAccountUpdateStream no data recieved

### ISSUE THREAD

**Issue by mdobson8** [JKorf/Binance.Net#35]
I could do with some help with my code here, I'm sure I am missing something. I run the below code in a windows form, but I do not get anything fed back to the debug. I have set the API keys in the default and get a listen key back.

        public void UserStream()
        {
            using (var client = new BinanceClient())
            using (var socketclient = new BinanceSocketClient())
            {
                var successStart = client.StartUserStream();
                System.Diagnostics.Debug.WriteLine(successStart.Data.ListenKey);
                var successAccount = socketclient.SubscribeToAccountUpdateStream(successStart.Data.ListenKey, (data) =>
                {
                    foreach (var value in data.Balances)
                    {
                        System.Diagnostics.Debug.WriteLine(value.Asset + " = " + value.Free + " = " + value.Locked + " = " + value.Total);

                    }
                });
            }
        }

all I see in the output is my listen key and the below;
'BinanceTestApi.exe' (CLR v4.0.30319: BinanceTestApi.exe): Loaded '<dir>\WebSocket4Net.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'BinanceTestApi.exe' (CLR v4.0.30319: BinanceTestApi.exe): Loaded '<dir>\SuperSocket.ClientEngine.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.

**Comment by JKorf** [comment]
Hi, 

The problem is that when the socketClient gets disposed the connection also closes. So in your case you probably don't want to be using a using statement for that BinanceSocketClient.

**Comment by mdobson8** [comment]
Apologies if this is a bit basic, but I still don't seem to be able to get it working. Can you send an example of how it should work?

Thanks for all the work on the API, it's great!

**Comment by JKorf** [comment]
No problem. Here's a small Console application that does a Debug.WriteLine of you balances. Note that this will only trigger if something changes. So have this code running and then try to place an order on the Binance website, you should see your balances written in the debug window.

````C#
class Program
    {
        static void Main()
        {
            BinanceDefaults.SetDefaultApiCredentials("YOUR API KEY", "YOUR API SECRET");
            UserSubscription userSubscription = null;
            using (var client = new BinanceClient())
            {
                var userStreamSuccess = client.StartUserStream();
                if (userStreamSuccess.Success)
                {
                    userSubscription = new UserSubscription(userStreamSuccess.Data.ListenKey);
                    userSubscription.Start();
                }
            }

            Console.ReadLine();
            userSubscription?.Stop();
            Console.ReadLine();
        }
    }

    public class UserSubscription
    {
        private BinanceSocketClient socketClient;
        private string listenKey;
        private BinanceStreamSubscription userStreamSub;

        public UserSubscription(string listenKey)
        {
            this.listenKey = listenKey;
            socketClient = new BinanceSocketClient();   
        }

        public void Start()
        {
            var success = socketClient.SubscribeToUserStream(listenKey, AccountUpdate, OrderUpdate);
            userStreamSub = success.Data;
            System.Diagnostics.Debug.WriteLine("Subscribed");
        }

        public void Stop()
        {
            socketClient.UnsubscribeFromStream(userStreamSub);
        }

        static void AccountUpdate(BinanceStreamAccountInfo info)
        {
            foreach (var value in info.Balances)
            {
                System.Diagnostics.Debug.WriteLine(value.Asset + " = " + value.Free + " = " + value.Locked + " = " + value.Total);
            }
        }

        static void OrderUpdate(BinanceStreamOrderUpdate ou)
        {

        }
    }
````

**Comment by JKorf** [comment]
Did you manage to get it working?

**Comment by mdobson8** [comment]
Yes, thanks for the support and the great API.
