### ISSUE TITLE
client.GetPurchaseRecordsAsync(LendingType.CustomizedFixed) get {5: Error deserializing data }

### ISSUE THREAD

**Issue by philipp-troxler** [JKorf/Binance.Net#352]
Hello
The endpoint https://api.binance.com/sapi/v1/lending/union/purchaseRecord
returns the correct data, but there is an error when deserializing.
The extract from the log is attached

thank you
[BinanceNet Error.txt](https://github.com/JKorf/Binance.Net/files/4840867/BinanceNet.Error.txt)

**Comment by JKorf** [comment]
Hi, this has been fixed in the latest version, thanks for the detailed report!

**Comment by philipp-troxler** [comment]
you welcome
