### ISSUE TITLE
client.GetRedemptionRecordsAsync(LendingType.CustomizedFixed) get {5: Error deserializing data }

### ISSUE THREAD

**Issue by philipp-troxler** [JKorf/Binance.Net#357]
Hello
The endpoint https://api.binance.com/sapi/v1/lending/union/redemptionRecord
returns the correct data, but there is an error when deserializing.
I'm using version 5.1.9.
The extract from the log is attached

thank you
[BinanceNet.Error01.txt](https://github.com/JKorf/Binance.Net/files/4882634/BinanceNet.Error01.txt)

**Comment by JKorf** [comment]
Hi, thanks for your report. I fixed it and pushed a new version 5.1.10. I've also checked the objects for missing converter attributes on datetime objects and they should all be fine now.

Let me know if you find something else

**Comment by philipp-troxler** [comment]
OK.
Next time i will try to report all issues together. It's easier that way.
