### ISSUE TITLE
Question with WebSockets

### ISSUE THREAD

**Issue by ExceedingLife** [JKorf/Binance.Net#358]
Hello,
I have a question with Websockets. I am currently working on getting this to work with Binance.US.
I got it to work 1 time it did 1 trade quantity the data displayed on my console. But it only did once. When more came in no other data displayed.
How do i set up the websocket so i get continuous data in a Console? Just for testing purposes once i get this then i can move on and code everything else up how I want it.
Here is my console app. Do I need to create a new event so itll constantly display each new record in the window.

`static void Main(string[] args)
        {
            Console.WriteLine("Starting ...");

           // BinanceSocketClientOptions socketclient = new BinanceSocketClientOptions();
            using(var client = new BinanceSocketClient())
            {
                var tickerupdate = client.SubscribeToSymbolTickerUpdates("ETHBTC", (data) =>
                {
                    Console.WriteLine("data: " + data.BidPrice);
                });

                //var ticker = client.SubscribeToSymbolMiniTickerUpdates("BTCUSD", (data) =>
                //{
                //    Console.WriteLine(data.LastPrice);
                //});
                var tick = client.SubscribeToTradeUpdates("BTCUSD", (data) =>
                {
                    Console.WriteLine(data.Price + "/t" + data.Quantity);
                });
            }

            Console.ReadLine();
        }`

**Comment by ExceedingLife** [comment]
nvm I got it working! Here is what I used.

Awesome API! I got this working with Binance.US.

`using(var client = new BinanceSocketClient())
            {
                /// LIVE BITCOIN TRADE DATA BELOW !!!!! 7/7/2020 [testTick]
                var testTick = await client.SubscribeToTradeUpdatesAsync("BTCUSD", (data) =>
                {
                    Console.WriteLine("BTC-trade");
                    Console.WriteLine(data.Quantity + "/t" + data.Price);
                });`

**Comment by JKorf** [comment]
Great to hear you got it working. The issue with your initial code is the socket client getting disposed after leaving the using block. Placing the Console.ReadLine inside the using block would fix that!
