### ISSUE TITLE
How do you get this value?

### ISSUE THREAD

**Issue by topproto** [JKorf/Binance.Net#36]
Hi JKorf

I have made really good use of your code but there is one thing i am stuck on.

You give us the BestAskPrice and BestBidPrice, but how do we know which one to display as the current price? do i need to read the trade history to know which way the trade went?

![image](https://user-images.githubusercontent.com/35653813/36074136-ad22bcec-0f33-11e8-8fda-94327d8dbc47.png)

Thanks in advance and keep up the good work! :)

**Comment by JKorf** [comment]
Hi, 

I assume you're talking about the object you get from updates from the SymbolTicker stream. The last trade that was closed, and thus the latest price, is the CurrentDayClosePrice field.

**Comment by topproto** [comment]
thanks again mate. that was what i was looking for! :)
