### ISSUE TITLE
Is margin trade supported ?

### ISSUE THREAD

**Issue by tenebriox** [JKorf/Binance.Net#360]
Hello, 
I am trying to use Margin trade but I am struggling to get that working.

In this snippet provided in your examples, it is working fine for the spot market but I don't see where I am supposed to change that for the Margin market :

`private void SubscribeUserStream()
        {
            if (ApiKey == null || ApiSecret == null)
                return;

            Task.Run(() =>
            {
                using (var client = new BinanceClient())
                {
                    var startOkay = client.StartUserStream();
                    if (!startOkay.Success)
                        //messageBoxService.ShowMessage($"Error starting user stream: {startOkay.Error.Message}", "error", MessageBoxButton.OK, MessageBoxImage.Error);
                        return;

                    var subOkay = socketClient.SubscribeToUserDataUpdates(startOkay.Data, OnAccountUpdate,
                        OnOrderUpdate, null, null, null);
                    if (!subOkay.Success)
                        //messageBoxService.ShowMessage($"Error subscribing to user stream: {subOkay.Error.Message}", "error", MessageBoxButton.OK, MessageBoxImage.Error);
                        return;

                    var accountResult = client.GetAccountInfo();
                    if (accountResult.Success)
                        Assets = new ObservableCollection<ViewModelAsset>(accountResult.Data.Balances
                            .Where(b => b.Free != 0 || b.Locked != 0).Select(b => new ViewModelAsset
                                {Asset = b.Asset, Free = b.Free, Locked = b.Locked}).ToList());
                    //else
                    //messageBoxService.ShowMessage($"Error requesting account info: {accountResult.Error.Message}", "error", MessageBoxButton.OK, MessageBoxImage.Error);

                }
            });
        }`

The "Assets" are from the spot market but I cannot see the ones that are on the Margin part of my account.
I have seen it is possible to use "BinanceClient" or "BinanceFuturesClient", is there something like "BinanceMarginClient" that I should use ?
Or maybe that feature is not supported (but I have seen in the readme it should, that's why I am confused) ?

Thanks for this awesome work

**Comment by JKorf** [comment]
I think you're looking for the `GetMarginAccountInfo` call. It has a property Balances which lists your assets.

**Comment by tenebriox** [comment]
Thank you so much :) now I feel stupid not find it by myself ! It was exactly what I was looking from (i hope maybe it would help another stupid person like me lol)

var accountMarginResult = client.GetMarginAccountInfo();
                    if (accountMarginResult.Success)
                        MarginAssets = new ObservableCollection<ViewModelAsset>(accountMarginResult.Data.Balances
                            .Where(b => b.Free != 0 || b.Locked != 0).Select(b => new ViewModelAsset
                                { Asset = b.Asset, Free = b.Free, Locked = b.Locked }).ToList());

Thanks again, really appreciate your very reactive help
