### ISSUE TITLE
BinanceClient.GetAllOrders returns zero price for Market orders

### ISSUE THREAD

**Issue by algosayir** [JKorf/Binance.Net#361]
Greetings,

When I use BinanceClient.GetAllOrders method, it returns good information for most of the orders except market order, it returns zero in the price.

Please advice.

**Comment by JKorf** [comment]
That is correct. Binance doesn't return a price for market orders because there isn't necessarily one price. A market order could be filled by different trades of different prices. You can look up trades for an order using the `GetMyTrades` method and mapping it by order id.

**Comment by algosayir** [comment]
Thanks a lot for the clarification.
