### ISSUE TITLE
Choose between Isolated Or Cross on Margin trading 

### ISSUE THREAD

**Issue by tenebriox** [JKorf/Binance.Net#369]
Hi, 
I would like to know if it is possible to deal with **isolated** margin trading ?
I have no problem accessing my (cross) margin Assets with this snippet:

`var accountMarginResult = client.GetMarginAccountInfo();
                    if (accountMarginResult.Success)
                        MarginAssets = new ObservableCollection<ViewModelAsset>(accountMarginResult.Data.Balances
                            .Where(b => b.Free != 0 || b.Locked != 0).Select(b => new ViewModelAsset
                                { Asset = b.Asset, Free = b.Free, Locked = b.Locked }).ToList());`

But I cannot find how to deal with my Isolated Margin Assets.

And I would have the same question to place an order, it works fine with "client.PlaceMarginOrder()" but I don't know how I could place an order on an isolated margin pair.

Thanks again for this awesome work

**Comment by tenebriox** [comment]
I just found that sadly it is actually not supported by Binance API :(
[](https://dev.binance.vision/t/endpoint-to-handle-isolated-margin-pairs/248
)

On this thread, there is a suggest to deal with the endpoints used by the web interface:
[](https://www.binance.com/gateway-api/v1/private/isolated-margin/transfer-in)
[](https://www.binance.com/gateway-api/v1/private/isolated-margin/borrow )

If I want to use these endpoints at my own risks, is that possible ?

**Comment by tenebriox** [comment]
A little update
I have ended up cloning the git source to be able to do the changes. I understood that if would not be possible by just changing some parameters!
I've added a new Client and now I have some work to make it work!

```
public class BinanceIsolatedMarginClient : RestClient, IBinanceClient
    {

    }
```

If it could interest you to add this feature, it would be a pleasure to share my work after.

**Comment by tenebriox** [comment]
I have moved up, but struggling to get authenticated :/
This is my code (simplified version without comments or not useful stuff):

```

namespace MyApp
{
	 private void SubscribeIsolatedMarginUserStream()
        {
            if (ApiKey == null || ApiSecret == null)
                return;

            Task.Run(() =>
            {
                using (var client = new BinanceIsolatedMarginClient())
                {
                    client.SetApiCredentials(apiKey, apiSecret);
                    var startOkay = client.StartIsolatedMarginUserStream();
                    if (!startOkay.Success)
                        //handle error
                        return;
                }
            });
        }
}


namespace Binance.Net
{
    public class BinanceIsolatedMarginClient : RestClient, IBinanceClient
    {
		
		private const string IsolatedMarginBaseAddress = "https://www.binance.com";
        private const string IsolatedMarginMarginVersion = "1";
        private const string IsolatedMarginApi = "gateway-api";
		private const string IsolatedMarginAssetsEndpoint = "private/margin/account-details";
	
       
        public static void SetDefaultOptions(BinanceClientOptions options)
        {
            defaultOptions = options;
        }
		
        public void SetApiCredentials(string apiKey, string apiSecret)
        {
            SetAuthenticationProvider(new BinanceAuthenticationProvider(new ApiCredentials(apiKey, apiSecret)));
        }        

        #region Create a ListenKey for Isolated Margin

       
			public WebCallResult<string> StartIsolatedMarginUserStream(CancellationToken ct = default) => StartIsolatedMarginUserStreamAsync(ct).Result;        
			public async Task<WebCallResult<string>> StartIsolatedMarginUserStreamAsync(CancellationToken ct = default)
			{
				var timestampResult = await CheckAutoTimestamp(ct).ConfigureAwait(false);
				if (!timestampResult)
					return new WebCallResult<string>(timestampResult.ResponseStatusCode, timestampResult.ResponseHeaders, null, timestampResult.Error);

				//var result = await SendRequest<BinanceListenKey>(GetIsolatedMarginUrl(GetIsolatedMarginListenKeyEndpoint, Api, UserDataStreamVersion), HttpMethod.Post, ct).ConfigureAwait(false);
				var result = await SendRequest<BinanceListenKey>(new Uri("https://www.binance.com/exchange-api/v1/private/mbxgateway/user-stream/start"), 
					HttpMethod.Post, ct).ConfigureAwait(false);
				return new WebCallResult<string>(result.ResponseStatusCode, result.ResponseHeaders, result.Data?.ListenKey, result.Error);
			}

        #endregion
		
		#region Get All Isolated Margin Assets
			
			public WebCallResult<IEnumerable<BinanceMarginAsset>> GetIsolatedMarginAssets(CancellationToken ct = default) => GetIsolatedMarginAssetsAsync(ct).Result;
			
			public async Task<WebCallResult<IEnumerable<BinanceMarginAsset>>> GetIsolatedMarginAssetsAsync(CancellationToken ct = default)
			{
				return await SendRequest<IEnumerable<BinanceMarginAsset>>(GetIsolatedMarginUrl(IsolatedMarginAssetsEndpoint, IsolatedMarginApi, IsolatedMarginMarginVersion), HttpMethod.Get, ct).ConfigureAwait(false);
			}

        #endregion
		
		
		private Uri GetIsolatedMarginUrl(string endpoint, string api, string version)
        {
            var result = $"{IsolatedMarginBaseAddress}/{api}/v{version}/{endpoint}";
            return new Uri(result);
        }
    }
}

```
Each time I try to StartIsolatedMarginUserStream() or to get my assets with GetIsolatedMarginAssetsAsync(),
I have an error {"code":"100001005","message":"Need to log in to access","success":false}

I can't find how to get authenticated when playing with this API.
Does someone have an idea please ?!

**Comment by JKorf** [comment]
Hi, the SendRequest method has an additional parameter; `signed`. Try setting it to true for authenticated requests. I'm not sure if it will work though.

**Comment by tenebriox** [comment]
Hi!
I really appreciated your help Jan, I tried with signed parameter (and also many other things!) but I cannot get it working.
In the same time, I have asked to Binance support when they plan to support it officially:

> Dear user, 
> 
> Thank you for your inquiry.
> 
> At this moment, the isolated Margin API is still under testing, we hope it will be released as soon as possible. We will make sure it functions nicely before the release. Therefore, unfortunately, we could not estimate the date.
> 
> Kindly look forward to it together with us, and your patience is much appreciated.
> 
> Sorry for any inconvenience it causes you. Your understanding is much appreciated.
> 
> Best regards, Binance Support Team

Maybe the best thing is just to wait for an official support :/

**Comment by JKorf** [comment]
Sad to hear you didn't get it working. I was kinda doubting it would, since authentication for requests using the website is probably done different than authentication using the API. I think the best thing is just to wait support in the API instead of trying to break into their website authentication ;)

Hopefully it won't take too long on their end!
