### ISSUE TITLE
GetExchangeInfoAsync

### ISSUE THREAD

**Issue by Cjay93** [JKorf/Binance.Net#37]
Hi love you wrapper. 
Im a little stuck on getting GetExchangeInfoAsync for specific coin for its STEP_SIZE

Anychance of a little example.

Thanks

**Comment by JKorf** [comment]
Sure, here's a little console program which looks up the step size for a specific coin you type in. Note that step size is a property for a specific market, not a coin. NEO-BTC stepsize is probably different from NEO-ETH stepsize for example. This test program just assumes BTC as quote asset.

````C#
    class Program
    {
        static void Main()
        {
            Test().Wait();
        }

        public static async Task Test()
        {
            BinanceExchangeInfo info = null;
            using (var client = new BinanceClient())
            {
                var exchangeInfoResult = await client.GetExchangeInfoAsync();
                if (!exchangeInfoResult.Success)
                {
                    Console.WriteLine("Error getting info: " + exchangeInfoResult.Error.Message);
                    Console.ReadLine();
                    return;
                }
                info = exchangeInfoResult.Data;
            }

            while (true)
            {
                var coin = Console.ReadLine();
                // Assuming BTC quote asset
                var stepSize = GetStepSizeForAsset(info, coin, "BTC");
                if (stepSize == null)
                    Console.WriteLine("Couldn't find info for coin " + coin);
                else
                    Console.WriteLine("Step size for coin " + coin + " is " + stepSize);
            }
        }

        public static decimal? GetStepSizeForAsset(BinanceExchangeInfo info, string baseAsset, string quoteAsset)
        {
            var asset = info.Symbols.SingleOrDefault(s => s.QuoteAsset.ToLower() == quoteAsset.ToLower() && s.BaseAsset.ToLower() == baseAsset.ToLower());
            return asset?.Filters.OfType<BinanceSymbolLotSizeFilter>().First().StepSize;
        }
    }

````

**Comment by Cjay93** [comment]
Thanks for the example. appreciated.
The reason i need to get step size is becuase im struggling with invaild quantity
for example
AmountInBTC / CoinToBuy.Data.AskPrice
Gives Lotsize error
so i then need to round it down using Maths.round(AmountInBTC / CoinToBuy.Data.AskPrice, stepsize)
Does this sound correct to you?
Once again thank you.

**Comment by JKorf** [comment]
That makes sense yes

**Comment by JKorf** [comment]
Btw, you can also enable automatic compliance of the trade rules by setting TradeRulesBehaviour to AutoComply. It will automatically floor the quantity using the stepsize it gets from the server.

**Comment by Cjay93** [comment]
wow enabling that does everything for me.
only problem is i somtimes get  Illegal characters found in parameter 'quantity'; legal range is '^([0-9]{1,20})(\.[0-9]{1,20})?$'.

This is just from entering BtcAmount / CoinToBuyAskPrice

Any ideas of what it could be and a decent methodical way of correcting that.
Sorry for bothering you.

**Comment by Cjay93** [comment]
Decimal.Round(amount / ask, 8) seems to do it.

**Comment by JKorf** [comment]
Hm that's weird. What values we're you using when you got that error?

**Comment by Cjay93** [comment]
0.00200000 / 0.00000639
BtcAmount   /   XVG last Ask

**Comment by JKorf** [comment]
I see, the problem is the wrapper sends too many trailing zero's. I've fixed it and pushing it to Nuget.

**Comment by Cjay93** [comment]
ok cool i supose that just making it to 8 decimal places?

**Comment by JKorf** [comment]
Yes
