### ISSUE TITLE
How to place a Stop-Limit Order

### ISSUE THREAD

**Issue by ExceedingLife** [JKorf/Binance.Net#370]
Hello, 
I have tried so many combinations and all I would like to do is to be able to place a 'Stop-Limit' trade with this API. I would also like to do a 'Market' trade. I have only successfully been able to do a 'Limit' Trade so far. 
Could any1 show me examples of code for Stop-Limit' and 'Market' 
Whenever I try Stop-Limit. I get the error: "Order would trigger immediately." and the docs: "The order's stop price is not valid when compared to the last traded price." I've tried with stop prices higher and lower and it hasn't made a difference. I also have gotten the error: not able to access a disposed object which im not really sure about. well anyways here is my code for a successful limit and tries on a stop-limit.

```
var orderResult =
                            await BinanceClient.PlaceOrderAsync(
                                                        symbol: stopOrder.TradeSymbol,
                                                        side: OrderSide.Sell,
                                                        type: OrderType.Limit,
                                                        timeInForce: TimeInForce.GoodTillCancel,
                                                        quantity: stopOrder.CryptoAmount,
                                                        price: stopOrder.LimitPrice);
//var orderResult =
                        //    await BinanceClient.PlaceOrderAsync(
                        //                                symbol: stopOrder.TradeSymbol,
                        //                                side: OrderSide.Sell,
                        //                                type: OrderType.StopLossLimit,
                        //                                timeInForce: TimeInForce.GoodTillCancel,
                        //                                quantity: stopOrder.CryptoAmount,
                        //                                price: stopOrder.LimitPrice,
                        //                                stopPrice: stopOrder.StopPrice); 
```

**Comment by Kudwig** [comment]
_stoppPrice = Truncate((currentPrice + (currentPrice / 100 * (1+_topUpPercent))), _roundingBuy); //on buy action, my stop price will be higher than current price
             limitPrice = Truncate((_stoppPrice + (_stoppPrice/ 80)), _roundingBuy);// on buy action limit price will be higher than stop price<trigger price>
            amount = _buyWallet/ _stoppPrice;

                if ((amount != 0) && (amount >= _volSize[count] / currentPrice))
                {
                    var order = Client.PlaceOrder(_marketName,
                                                                    OrderSide.Buy, 
                                                                    OrderType.StopLossLimit,
                                                                    Truncate(amount, _roundingSell), 
                                                                    null,
                                                                    null,
                                                                    limitPrice, 
                                                                    TimeInForce.GoodTillCancel,
                                                                    _stoppPrice,
                                                                     null, null, null, default(CancellationToken));
                    if (ord.Success)
{
....
}

**Comment by ExceedingLife** [comment]
Thank you for your replies! I will give them a shot and let you know how the outcome is.
1 quick question.
StopLossLimit - is 'Stop-Limit' trade on the Binance Exchange?
Do you also have the code for a regular Market trade?

**Comment by ExceedingLife** [comment]
It WORKED!
but im a bit confused now.
I posted a Stop-Limit trade with the API just liked i wanted. But it would not post a Stop-Limit BUY unless i put the 'stop price' ABOVE the current price. why is that? wouldnt I want to buy it when its hits a certain price below what its currently at?

**Comment by Kudwig** [comment]
ord = Client.PlaceOrder(_marketName, OrderSide.Sell, OrderType.Market,
                        Truncate(amount, _roundingSell));
                    if (ord.Success)
                    {
}

**Comment by Kudwig** [comment]
yes its confusing :)
it allows yo to put an order in an area that would normally be triggered on a limit order
https://binance.zendesk.com/hc/en-us/articles/115003372072

**Comment by Kudwig** [comment]
mine i used in a trailing stop loss scenario...eg stop limit buy that trails the current price by xx % while price drop...or stop limit sell that trails the current price by xx% while it climbs.

**Comment by ExceedingLife** [comment]
I got it figured out!
I really appreciate your help man.
So I use type: OrderType.TakeProfitLimit, when the current price is lower and
type: OrderType.StopLossLimit, when the current price is higher!

Now i am going to get the websockets working with current orders being placed which you also helped me with in the other comment.
Thank you so much!

**Comment by Kudwig** [comment]
example using JS https://github.com/BlockchainWhispers/trailingstoploss3
