### ISSUE TITLE
Websockets User Active Trades

### ISSUE THREAD

**Issue by ExceedingLife** [JKorf/Binance.Net#371]
Hello, I have a question with Websockets. I would like to watch my active trade/trades and when once is completed would I get a notification that 1 is been completed. I got websockets working with all incoming trades. I'm not sure about the User Data Socket which 1 it would be im assuming:  SubscribeToUserDataUpdatesAsync.
Does any1 have an example on doing this? here is my guess to watch active trades by the user connected to the ListenKey.

```
 private async Task GetUserStream()
        {
            //string userListenKey;
            using(var client = tradingClient.BinanceClient)
            {
                userListenKey = client.StartUserStreamAsync().Result.Data;

                var userActiveData = BinanceSocketClient.SubscribeToUserDataUpdatesAsync(userListenKey, data =>
                {
                    // Handle Account Information Data.
                }, data =>
                {
                    // Handle Order Update Information Data.
                },
                null, // Handle OCO Update Information Data.
                null, // Handle Position Update Information Data.
                null);// Handle Account Balance Update Information Data. (Withdrawals/Deposits)
            }
        }
```

**Comment by Kudwig** [comment]
public static BinanceStreamAccountInfo InfoData { get; set; }
public static List<BinanceStreamOrderUpdate> _orderData { get; set; }

....
....

binanceClient.SubscribeToUserDataUpdates(ThirdBinanceAlgorithm._listenkey, _data =>
                        {
                            InfoData = _data;//updating my account balances
                            OnEvent(_data);

                        },
                        _data =>
                        {

                            if (ThirdBinanceAlgorithm._marketName==_data.Symbol.ToUpper())
                            _orderData.Add(_data);//adding this specific order execution data for this symbol to its own list, then i check if the list was modified, and use the last list entry as my last action that has taken place
                            
                            
                            OnEvent(_data);//handle data for this event, eg. placed a new order...or canceled an order, or order was filled


                        }, null, // Handler for OCO updates
                    null, // Handler for position updates
                    null); // Handler for account balance updates (withdrawals/deposits)

**Comment by ExceedingLife** [comment]
So I been trying to turn on IncomingTrades, and then my UserOrder Trades. then when i go to create a new order i get the error 'cannot access a disposed object' im not to sure why maybe cuz im using the object for my userorder trades then I try the same object to create an order? but that shouldnt dispose of it... i guess im just confused here is the code starting both streams then i have another button click which simply just creates a trade.

```
 private void BtnStartCapture_Click(object sender, RoutedEventArgs e)
        {
            if (!running)
            {
                running = true;
                IncomingStreamOn();
            }
            //else { running = false; IncomingStreamOff(); }

            //using (var client = new BinanceSocketClient())
            using (BinanceSocketClient)            
            {                   //client.SubscribeToTradeUpdatesAsync("BTCUSD", (data) =>
                var incomingBTC = BinanceSocketClient.SubscribeToTradeUpdatesAsync("BTCUSD", (data) =>
                {
                    UpdateCurrentPrice(data.Price.ToString("C"));
                    AddNewIncomingTrade(data);

                   // AddNewTrade(data);
                   // UpdateLstIncoming();                   
                   // tradingClient.AddNewTrade(data);

                   
                });

                using (var client = tradingClient.BinanceClient)
                {
                    userListenKey = client.StartUserStreamAsync().Result.Data;

                    var userActiveData = BinanceSocketClient.SubscribeToUserDataUpdatesAsync(userListenKey, data =>
                    {   ///BinanceStreamAccountInfo
                        // Handle Account Information Data.

                    }, async data =>
                    {   ///BinanceStreamOrderUpdate
                                // Handle Order Update Information Data.
                        await YourUpdates(data);
                    },
                    null, // Handle OCO Update Information Data.
                    null, // Handle Position Update Information Data.
                    null);// Handle Account Balance Update Information Data. (Withdrawals/Deposits)
                }
            }
```

**Comment by JKorf** [comment]
Your problem probably originates from using the socket client with a `using` statement. When the code leaves the using statement the client gets disposed. Try removing the `using (BinanceSocketClient)` statement.

**Comment by ExceedingLife** [comment]
Wow! Thanks man!
Taking the 'using' out of the trade methods worked! i can now do multiple trades. Now next i just gotta figure out getting websockets to work with current user trade streams.

**Comment by JKorf** [comment]
I'm assuming you got the stream working (the code in the initial issue was fine by the looks of it). If not let me know what the issue is.
