### ISSUE TITLE
EventTime is populated in SubscribeToOrderBookUpdates but not SubscribeToPartialOrderBookUpdates

### ISSUE THREAD

**Issue by DanTheManGC** [JKorf/Binance.Net#373]
Both of the following websocket streams return BinanceOrderBook objects... 
            
SubscribeToOrderBookUpdates
SubscribeToPartialOrderBookUpdates

The first stream returns BinanceOrderBook with EventTime property populated but the 2nd stream returns EventTimes that are null.

Issue is present in the latest version of Binance.NET (5.1.11).

Any assistance would be greatly appreciated, thanks!

**Comment by JKorf** [comment]
Hi, I've taken a look but this is an issue at Binance side. As per documentation (https://binance-docs.github.io/apidocs/spot/en/#partial-book-depth-streams) the partial book depth stream doesn't send an event time unlike the diff depth stream. I've updated the order book models to reflect this.

**Comment by DanTheManGC** [comment]
Ah, well that makes sense.  Thank you for looking into it Jan... and so quickly!  :)
