### ISSUE TITLE
CancelMultipleOrders not actually added?

### ISSUE THREAD

**Issue by yetiwolf** [JKorf/Binance.Net#374]
Release notes say that CancelMultipleOrders was added, but I don’t see it.

**Comment by JKorf** [comment]
Hi, the `CancelMultipleOrder` method was added for the futures client, not the regular spot client. Binance only has two cancellation method in the spot API, a single cancel (`CancelOrder`) or canceling all open orders for a symbol (`CancelAllOpenOrders`).
