### ISSUE TITLE
Mandatory parameter 'closePosition' was not sent, was empty/null, or malformed.

### ISSUE THREAD

**Issue by kerohero** [JKorf/Binance.Net#377]
I'm getting this error, and for sure I'm sending the 'closePosition', 3rd parameter from the end (true) 

`var res = await Constants.Master.Client.PlaceOrderAsync(symbol, side, type, decimal.Round(Constants.Master.Balance / decimal.Parse(price) * leverage, precision), posSide, TimeInForce.GoodTillCancel, reduceOnly, decimal.Parse(price), null, decimal.Parse(price), null, null, null, true, null, Constants.recvWindow);
                    if (res.Error != null)
                        throw new Exception(res.Error.Message);`

Any ideas?

**Comment by JKorf** [comment]
Can you try again with the latest version? The value was send as a capital boolean string ('True') instead of the documented lower case bool value ('true'). I've changed it to the lower case variant. Let me know if that helps.

**Comment by kerohero** [comment]
@JKorf My side was sell and the posSide was short which means adding more short (that doesn't work with closePosition) so I knew my fault and adjusted posSide to Long and it closed my long Position 

Maybe you can add a check, a validation check. If closePosition is true, side and posSide can't be the same

**Comment by JKorf** [comment]
Thanks for letting me know. Check will be added in next version.
