### ISSUE TITLE
Strange behavior while using Margin Websocket

### ISSUE THREAD

**Issue by Gustavobbr** [JKorf/Binance.Net#378]
Hi There,
I've compared times between websocket for Spot and Margin (Account Websocket) raised after placing an order.

Curiously the websocket for Margin account is getting in average 150~200ms more latency then websocket for spot to get called.

I've contacted Binance Support to investigate if it in fact was expected, and the answer is that we shouldn't be facing any divergence between latency of these two streams.

_"Dear user, 
Thank you for your inquiry.
At this moment we have not observed a significant difference between these two streams. 
If you have further questions, feel free to contact us at any time."_

My code has nothing besides placing order and measuring time until websocket is called, is there anything I could do, or you suggest to investigate even more why is it happening ? Also, I've noticed that websocket for margin has way more oscilating latency then spot.

Best Regards,

**Comment by Gustavobbr** [comment]
A little update
I've investigate a little further, actually, the returning from a request from Margin Market is taking 100ms+ to return if compared to spot requests.

I've opened a ticket into binance's support to check if that's expected

**Comment by JKorf** [comment]
So it looks like placing the order is actually slower on the margin API compared to spot? Please let me know what Binance support says about this and let me know if I can help.

**Comment by Gustavobbr** [comment]
They've replied showing that we shouldn't expect higher latency on Margin, however, on the screenshots they've sent to point that up, the latency on Margin is in fact ~ 56ms higher.

I've replied that asking about those difference, and still waiting for answer, but, so far, it seems that request from margin in fact have higher latency then spot.

![image](https://user-images.githubusercontent.com/37227910/89197629-624e8800-d582-11ea-91d0-b9a35e089a19.png)

![image](https://user-images.githubusercontent.com/37227910/89197594-56fb5c80-d582-11ea-8c06-280793c37f9b.png)

I'll get back here when I get their answer.

**Comment by Gustavobbr** [comment]
I'll use this topic to ask if is there any plans on implementing Isolated Margin on the Margin Library ?

https://binance-docs.github.io/apidocs/spot/en/#change-log

DIfferences on Update Log 2020-07-28

**Comment by Gustavobbr** [comment]
I've received a return, so, Margin endpoints is in fact slower then SPOT.

_"We also have forwarded this issue to our tech team. They have tested multiple times, the margin endpoints are truly a little bit slower than the spot endpoints. They have known this performance issue and would adjust and optimize the margin endpoints later. But the adjustment needs the time. So we recommend you reduce the frequency to call these endpoints.

If you want to check the margin account information, we recommend you subscribe to the user data stream. If you have any further questions, please feel free to contact us.

Thank you for your understanding."_

**Comment by JKorf** [comment]
Isolated margin will be added in next version.
