### ISSUE TITLE
Using library from Blazor WASM without Azure functions

### ISSUE THREAD

**Issue by arcayne** [JKorf/Binance.Net#383]
Hi guys,

I am struggling to run the library on Blazor WASM without Azure functions. Might very well be poor understanding of few basic concepts on my side and asked for help at https://stackoverflow.com/questions/63287639/binance-net-app-with-blazor-wasm-authentication-provider-unhandled-exception-r

Wondering if you have an example otherwise of how to use it? 

Thanks.

**Comment by JKorf** [comment]
Little luck on StackOverflow I see. I haven't tried Blazor client side yet, I'll see if I can get it working. The error (`Property Proxy not supported`) would suggest a limitation in the framework though.

**Comment by pingouin84** [comment]
hi, have you found a solution to your problem. I have the same problem.

**Comment by DieGrysWolf** [comment]
> 
> 
> hi, have you found a solution to your problem. I have the same problem.

Ok, and what was that solution?
For future people.

**Comment by JKorf** [comment]
See #1051
