### ISSUE TITLE
"No credentials provided for private endpoint"

### ISSUE THREAD

**Issue by SayidJafari** [JKorf/Binance.Net#384]
Hi 
when I use this code I see ""No credentials provided for private endpoint"  "error inside orderResult 

private void button1_Click(object sender, EventArgs e)
        {
            var orderResult = MainForm.BClinet.PlaceOrder("BTCUSDT", OrderSide.Buy, OrderType.Limit, 10, price: 0.0002m, timeInForce: TimeInForce.GoodTillCancel);
           
        }

**Comment by JKorf** [comment]
Have you entered your API key and API secret into the client using the options?

````C#
var client = new BinanceClient(new BinanceClientOptions(){
    ApiCredentials = new ApiCredentials("API KEY HERE", "API SECRET HERE")
});
````

**Comment by SayidJafari** [comment]
yes I receive quotes

**Comment by developocalypse** [comment]
Do you mean yes, you have entered your API key and API secret, and you have also received several quotes for a new kitchen, or what do you mean?

**Comment by SayidJafari** [comment]
> Have you entered your API key and API secret into the client using the options?
> 
> ```cs
> var client = new BinanceClient(new BinanceClientOptions(){
>     ApiCredentials = new ApiCredentials("API KEY HERE", "API SECRET HERE")
> });
> ```

I mean  yes  I have problem only with order send the connection and receiving price work but there is a problem with the order send

**Comment by developocalypse** [comment]
I suggest this. Start a new console project, get your api key and secret from Binance ready, then try this code in the new console project.

```
(This goes inside the private static void Main(string[] args) method)

var key = put your api key here (in "quotes");
var secret = put your api secret here (in "quotes");
var restClient = new BinanceClient(new BinanceClientOptions
{
    ApiCredentials = new ApiCredentials(key, secret),
});

var orderResult = restClient.PlaceOrder("BTCUSDT", OrderSide.Buy, OrderType.Limit, .01M, price: 8000m, timeInForce: TimeInForce.GoodTillCancel);
```

**Comment by SayidJafari** [comment]
Hi again and thank you for all help getprice works but still I have a problem with PlaceOrder but the error is new   {-2015: Invalid API-key, IP, or permissions for action. 
this key and secret  is for testnet.binancefuture.com account not for real account



           var key = "e20bf202572468da51703b44362f8b80c1b931bfc19dc72d97d4c2cbacd0cb67";
            var secret = "b78f31ae2b46a2994a9d97ac8d4fe6e179c8dee4b599221789322c85b01dbbcf";
            var restClient = new BinanceClient(new BinanceClientOptions
            {
                ApiCredentials = new ApiCredentials(key, secret),
            });
           
            
            var price = restClient.GetPrice("BTCUSDT");
            Console.WriteLine(price.Data.Price);


            var orderResult = restClient.PlaceOrder("BTCUSDT", OrderSide.Buy, OrderType.Limit, .01M, price: 8000m, timeInForce: TimeInForce.GoodTillCancel);

            Console.ReadKey();

**Comment by JKorf** [comment]
I see you're using the 5.1.x version, you'll need to use the `BinanceFuturesClient` class instead of the `BinanceClient` class. In the 6.0.0 version which is now in beta you can access the futures API through the same `BinanceClient` class.

Since you're using the test net, you'll also have to change the base API address. You can do this in the 6.0.0-beta.1 version using the BinanceClientOptions overload to pass it to the client:
````
var client = new BinanceClient(new BinanceClientOptions("https://api.binance.com", "https://testnet.binancefuture.com"){ 
    ApiCredentials = new ApiCredentials(key, secret),
});
````

**Comment by SayidJafari** [comment]
if it's possible  add  beta version to NuGet package

**Comment by JKorf** [comment]
It is already on Nuget: https://www.nuget.org/packages/Binance.Net/6.0.0-beta.1

Though you might have to enable the include pre-release checkbox:
![image](https://user-images.githubusercontent.com/8448172/90117919-d4c82080-dd57-11ea-8dcb-6b9dbf6c15cb.png)

**Comment by SayidJafari** [comment]
API work with real  acc very good but how I can change spot  futures and how do I know which one is active right now

**Comment by JKorf** [comment]
You'll have to make 2 seperate clients; 1 with credentials for the Spot API and 1 with credentials for the futures API

**Comment by SayidJafari** [comment]
May I ask you write code for me I am a new programmer  Thanks

**Comment by SayidJafari** [comment]
![image](https://user-images.githubusercontent.com/45521073/90150146-97d14d80-dd9a-11ea-8a9b-aab22d1661b9.png)

I Think this API not work with futures account am I right?

**Comment by developocalypse** [comment]
It looks like that key won't work because it was created before you had a futures account. Create a new key, see if that works.

**Comment by walterX12** [comment]
You have compromisd your credentials by publishing them here. You should change API key and API secret asap.
