### ISSUE TITLE
Implement Margin OCO order

### ISSUE THREAD

**Issue by zachy** [JKorf/Binance.Net#385]
Currently OCO orders are supported only for Spot trading. Could you enable OCO trade queries for Margin trading too?
CancelOCOOrder
GetOCOOrder
GetOCOOrders
GetOpenOCOOrders
and most important is PlaceOCOOrder
Thanks!

**Comment by JKorf** [comment]
If you can point me to the API docs describing this, sure.

**Comment by zachy** [comment]
Aha I see now, I was expecting they have this already documented. Sorry closing :)
