### ISSUE TITLE
User stream won't die

### ISSUE THREAD

**Issue by developocalypse** [JKorf/Binance.Net#386]
I've had a user stream (SubscribeToUserDataUpdatesAsync) running for three days without sending KeepAliveUserStream (I forgot to implement it). It's receiving order updates perfectly. I'm going to implement it now, but has anyone noticed similar behaviour, or heard anything from Binance about this requirement being removed?

**Comment by JKorf** [comment]
I've heard from people saying that the stream would stop sending updates after x period, which was fixed when they implemented the keep alive. Binance documentation also still says it will stop sending data after 60 min if no keep alive is send. It doest note though that sending a new POST requests (so another StartUserStream call) will extend the existing listen key for 60 minutes, same as a keep alive. Maybe that is what kept your listen key alive?

**Comment by developocalypse** [comment]
Nothing apart from the original subscribe request and some order requests was sent to Binance. It must have been a functional change on the exchange. I'm going to pretend it didn't happen.
