### ISSUE TITLE
Proxy support?

### ISSUE THREAD

**Issue by ErcinDedeoglu** [JKorf/Binance.Net#389]
Hi,
thanks for awesome library!

I'm looking for proxy support? Any plan about adding proxy support?

**Comment by JKorf** [comment]
Hi, you can set the proxy in the client options like this:
````C#
var client = new BinanceClient(new BinanceClientOptions
{
   LogVerbosity = LogVerbosity.Debug,
   Proxy = new ApiProxy("http://test.com", 11000)
});
````

**Comment by little-fish-foundation** [comment]
BinanceSocketClient how to set?
