### ISSUE TITLE
Cannot retrieve isolated margin trade history

### ISSUE THREAD

**Issue by myhorses2you** [JKorf/Binance.Net#393]
I want to get all my trades history in isolated margin account but could not find it. 

"await client.GetMyMarginAccountTrades" only returns trades that are in **cross margin** account,  trades that are in **isolated margin** account are not included. 

Is it possible to get that information?

Thank you for all your hard work.

**Comment by JKorf** [comment]
Hi, Isolated margin is only supported in the beta version at the moment. Using the beta 6.0 version the `isIsolated` parameter can be used: `client.Margin.Order.GetMyMarginAccountTrades("SYMBOL", isIsolated: true);`

**Comment by myhorses2you** [comment]
Thanks! That is exactly what I am looking for.
