### ISSUE TITLE
SubAccount transfer not working

### ISSUE THREAD

**Issue by yetiwolf** [JKorf/Binance.Net#394]
Attempt to do a TransferSubAccount from one sub to another and get a success and an “OK” but nothing happens.  

Edit: this was done with the master account, which should be able to transfer from sub to sub.

**Comment by JKorf** [comment]
Hi, can you enable debug logging in the client options and paste the logging of the call here? (leave out any sensitive info by replacing it)

**Comment by yetiwolf** [comment]
Well, you solved my problem.  I wasn't aware that there is an "internal transfer" permission on the API key.  Debug told me right away.   Cheers!

2020/08/24 10:10:29:384 | Debug | Data received: {"msg":"You are not authorized to execute this request."}
