### ISSUE TITLE
Question: Machine Learning Limits on Binance

### ISSUE THREAD

**Issue by walterX12** [JKorf/Binance.Net#395]
Hi, this is not an issue with Binance.NET API. I would like to ask for a help with Machine Learning Limits on Binance. Binance doc is not very specific on this matter and they suggest to "use trial and error to achieve your ideal trading pattern". Before trying to write some "Method for testing Machine Learning Limits", I would like to ask for any experience with acceptable "Conversation rate" or acceptable  "Weight". 

The only information form _**Binance Doc**_ is (https://binance.zendesk.com/hc/en-us/articles/360004492232-API-Frequently-Asked-Questions-FAQ):
- Your "conversation rate" is low. "Conversation rate" is defined as your number of trades divided by the total order creations and cancellations over a 24-hour period (num Trades / (orders + cancels)).

- Your "weight" is low. "Weight" is defined as your total traded quantity divided by the total order creations and cancellations over a 24-hour period (total Traded Qty / (orders + cancels)).
    When trading pairs that have BNB as the base or quote asset, your abuse score will be amplified.

More specific information than the above will not be provided. Please use trial and error to achieve your ideal trading pattern, or discuss optimal behavior with other API users.

Please suggest if I should place this question elsewhere.

Thank you fro sharing.

**Comment by JKorf** [comment]
Sorry for the late response. 

I personally have 0 experience using machine learning, so sadly I can't help you. Looking at the number of responses on this from other uses it seems that this isn't something most users here have tried.
