### ISSUE TITLE
client.PlaceOrder question

### ISSUE THREAD

**Issue by thraxxus** [JKorf/Binance.Net#396]
When  I place an order I want it to work like this:

I place a sell of something at 1USDT
The Market is presently at 1.25 USDT

I want it to fill the 1.25 price.

I asked Binance, they said that is how a limit order works.

It never works. It fills at 1 USDT, instead of at the open high bid of 1.25 usdt.

So the question is: Do I use OrderType.TakeProfit?

If so, what are the required values to send with it? I cannot find that in the documentation.

**Comment by JKorf** [comment]
If Binance says that is how limit orders work than I would expect that to work. It always was my understanding as wel that the limit order will fill at the best price, even if the price specified is lower. Are you sure you're making the right method call?

**Comment by thraxxus** [comment]
orderResult = client.PlaceOrder(MyTransactionEntry.edge.symbol, os, OrderType.Limit, units, null, newClientOrderId: MyTransactionEntry.MyID.ToString(), price: price, timeInForce: TimeInForce.GoodTillCancel);

**Comment by thraxxus** [comment]
Is that wrong?

**Comment by JKorf** [comment]
Seems fine as far as I can see. Can you turn on debug logging and make a limit order with a lower price than the current best order book offer and paste it here so we can validate that it's actually not filling at the best price?

**Comment by thraxxus** [comment]
"turn on debug logging " ?

**Comment by JKorf** [comment]
in the client options:
````c#
var client = new BinanceClient(new BinanceClientOptions{
  LogVerbosity = LogVerbosity.Debug
});
````

**Comment by Kudwig** [comment]
also have a look at https://github.com/JKorf/Binance.Net/issues/370
