### ISSUE TITLE
COIN-M Futures

### ISSUE THREAD

**Issue by Mathemagician** [JKorf/Binance.Net#397]
Apologies if this has been asked and answered (I promise, I looked!), but how do we access the COIN-M Futures section of Binance?

Thanks!

M

**Comment by JKorf** [comment]
Hi, I'm currently working on it. Will be available soon.

**Comment by Mathemagician** [comment]
Outstanding, thanks!

**Comment by JKorf** [comment]
Hi, first support for Coin-M futures are in version 6.0.0-beta.4. Let me know if you have any issues using it!
