### ISSUE TITLE
stop limit orders

### ISSUE THREAD

**Issue by muoi** [JKorf/Binance.Net#4]
I think your library doesn't like stop limit orders

![image](https://user-images.githubusercontent.com/536678/34013342-f6fc6ac8-e10e-11e7-9670-20f3628b0a56.png)

![image](https://user-images.githubusercontent.com/536678/34013345-fc951ebc-e10e-11e7-8ef7-b0bc5868d75a.png)

Also there are new order types

![image](https://user-images.githubusercontent.com/536678/34013378-2e31ba5c-e10f-11e7-9182-7911ee818ab7.png)

https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md

Good job though (Y)

**Comment by JKorf** [comment]
Hi, sorry for taking so long, I've been busy. I've updated the library according to the github documentation. Should work for you with the latest version!

**Comment by muoi** [comment]
No problem. Awesome work man I also use your bittrex library. Keep up the good work!
