### ISSUE TITLE
Timestamp for this request was 1000ms ahead of the server's time. Error

### ISSUE THREAD

**Issue by Serjster** [JKorf/Binance.Net#40]
When I call the `client.GetAccountInfoAsync();`

I am getting error: 

> "Timestamp for this request was 1000ms ahead of the server's time."

**Comment by JKorf** [comment]
Try enabling AutoTimestamp: `client.AutoTimestamp = true;`

**Comment by Serjster** [comment]
Yes, that did work. Thanks!
