### ISSUE TITLE
Exception in log on incoming order execution report from user data stream

### ISSUE THREAD

**Issue by ikorman** [JKorf/Binance.Net#404]
Hi

I tried for the first time to use socket to monitor user data stream. I subscribed without any problem and in the debug log I can see data received from the socket, but then the next line in the log is following:

Exception: System.MissingMethodException: Method not found: 'CryptoExchange.Net.Objects.CallResult`1<!!0> CryptoExchange.Net.BaseClient.Deserialize(Newtonsoft.Json.Linq.JToken, Boolean, Newtonsoft.Json.JsonSerializer)'.
   at Binance.Net.BinanceSocketClient.<>c__DisplayClass63_0.<SubscribeToUserDataUpdatesAsync>b__0(String data)
   at CryptoExchange.Net.SocketClient.<>c__DisplayClass52_0`1.<AddHandler>g__InternalHandler|0(SocketConnection socketWrapper, JToken data)
   at CryptoExchange.Net.Sockets.SocketConnection.HandleData(JToken tokenData)
Data: {...

Same thing also hapend for outboundAccountInfo, outboundAccountPosition. Any idea?

Thank you 
Ivan

**Comment by JKorf** [comment]
Hi, I think there is a mismatch between the versions of Binance.Net and CryptoExchange.Net you're using. What versions are you using?

**Comment by ikorman** [comment]
Hi Jan

I'm using following versions:

Binance.Net 5.1.14
CryptoExchange.Net v3.0.14

I'm hoping issue is only this :)

BR
Ivan

**Comment by JKorf** [comment]
Use CryptoExchange.Net v3.0.12, that should fix your issue. I'm working on the update to 3.0.14 still.

**Comment by ikorman** [comment]
Thank you, will try it at evening and let you know.

BR
Ivan

**Comment by ikorman** [comment]
Hi

I just tested with v3.0.12 - no more exceptions in the debug log :) Thank
you very much for your help and also for the time you invest into
development.

Best regards
Ivan

**Comment by danielhw2** [comment]
Same with me... Had to downgrade to CryptoExchange.Net  v3.0.12 =(

**Comment by JKorf** [comment]
3.0.14 works with the Binance.Net beta version only atm
