### ISSUE TITLE
How to use in testnet?

### ISSUE THREAD

**Issue by MohKardan** [JKorf/Binance.Net#405]
I change BaseAddress to testnet.binancefuture.com and  try use this API to connect testnet.binancefuture.com and send orders but I'm not successful. please help me.

**Comment by JKorf** [comment]
Hi, I haven't personally used the test net, but it seems you'll need an actual test net account from `https://testnet.binancefuture.com/`

**Comment by nikkozp** [comment]
My example
```csharp
BinanceClientOptions clientOption = new BinanceClientOptions
                                                       {
                                                           AutoTimestamp = false,
                                                           TradeRulesBehaviour = TradeRulesBehaviour.None,
                                                           //LogVerbosity = LogVerbosity.Debug,
                                                           //LogWriters = new List<TextWriter> { Console.Out },
                                                        };

            BinanceSocketClientOptions socketOption = new BinanceSocketClientOptions
                                                             {
                                                                 AutoReconnect = true,
                                                                 ReconnectInterval = TimeSpan.FromMinutes(1),
                                                                 //LogVerbosity = LogVerbosity.Debug,
                                                                 //LogWriters = new List<TextWriter> { Console.Out },
            };

            if (isTestenet)
            {
                clientOption.FuturesBaseAddress = "https://testnet.binancefuture.com";

                socketOption.BaseAddressFutures = "wss://stream.binancefuture.com/ws/";
                socketOption.BaseAddressFuturesCombined = "wss://stream.binancefuture.com/";
            }

            Client = new BinanceClient(clientOption);

            Ws = new BinanceSocketClient(socketOption);
```

**Comment by MohKardan** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'BinanceClientOptions' does not contain a definition for 'FuturesBaseAddress' and no accessible extension method 'FuturesBaseAddress' accepting a first argument of type 'BinanceClientOptions' could be found (are you missing a using directive or an assembly reference?)	BinanceTrader	C:\Users\Mohammad\source\repos\BinanceTrader\BinanceTrader\Form1.cs	331	Active
Error	CS1061	'BinanceSocketClientOptions' does not contain a definition for 'BaseAddressFutures' and no accessible extension method 'BaseAddressFutures' accepting a first argument of type 'BinanceSocketClientOptions' could be found (are you missing a using directive or an assembly reference?)	BinanceTrader	C:\Users\Mohammad\source\repos\BinanceTrader\BinanceTrader\Form1.cs	333	Active
Error	CS1061	'BinanceSocketClientOptions' does not contain a definition for 'BaseAddressFuturesCombined' and no accessible extension method 'BaseAddressFuturesCombined' accepting a first argument of type 'BinanceSocketClientOptions' could be found (are you missing a using directive or an assembly reference?)	BinanceTrader	C:\Users\Mohammad\source\repos\BinanceTrader\BinanceTrader\Form1.cs	334	Active

**Comment by JKorf** [comment]
In the latest beta version these properties have been changed to `FuturesCoinBaseAddress` and `FuturesUsdtBaseAddress`.

**Comment by nikkozp** [comment]
@JKorf  At the latest alpha version, I can't find CombinedAdress for sockets.

**Comment by JKorf** [comment]
Combined address is automatically resolved in beta. For all implementations the single stream endpoint is `/ws/xxx` and the combined address is `/stream?stream=xxx`. So only the base address is needed anymore.

**Comment by johann-combrink** [comment]
api.UsdFuturesApi.BaseAddress is readonly now...

how does one use the test net please ?
