### ISSUE TITLE
Latest build uses incorrect JsonConverter for ActivationPrice in BinanceFuturesStreamOrderUpdate

### ISSUE THREAD

**Issue by grante** [JKorf/Binance.Net#406]
The latest build corrects the return type of BinanceFuturesStreamOrderUpdate.ActivationPrice but the JsonConverter is incorrect:

        /// <summary>
        /// Activation Price, only pushed with TRAILING_STOP_MARKET order
        /// </summary>
        [JsonProperty("AP"), JsonConverter(typeof(PositionSideConverter))]
        public decimal ActivationPrice { get; set; }

**Comment by JKorf** [comment]
Thanks for the notice, I've pushed a new version where it's fixed.
