### ISSUE TITLE
Servertime in Unix

### ISSUE THREAD

**Issue by mircofx** [JKorf/Binance.Net#407]
Hi, 
when i use the function 
using (var client = new BinanceClient())
            {
                var serverTime = client.GetServerTime();
            }
 it returns the time not in unix. How can I convert it ?

**Comment by developocalypse** [comment]
Google c# convert datetime to unix

**Comment by mircofx** [comment]
serverTime return a datetime.
I need a unix time to post an order on futures.

If I pass the value to another variable it gives null

**Comment by developocalypse** [comment]
```
//Version="5.1.14"
DateTime time1 = client.GetServerTime().Data;

//Version="6.0.0-beta.4"
DateTime time2 = client.Spot.System.GetServerTime().Data;

```

**Comment by nikkozp** [comment]
```csharp
public static long ToUnixTimestamp(this DateTime time)
{
    return (long)(time - new DateTime(1970, 1, 1)).TotalMilliseconds;
 }
```
