### ISSUE TITLE
How do you get the trade history from spot?

### ISSUE THREAD

**Issue by ivandrofly** [JKorf/Binance.Net#409]
![image](https://user-images.githubusercontent.com/6579818/91660943-d6704300-ead0-11ea-9623-1837f13b4e81.png)

**Comment by JKorf** [comment]
Hi, in 5.1.14 via `client.GetMyTrades(..)`, in 6.0.0-beta via `client.Spot.Order.GetMyTrades(..)`.

**Comment by ivandrofly** [comment]
> Hi, in 5.1.14 via `client.GetMyTrades(..)`, in 6.0.0-beta via `client.Spot.Order.GetMyTrades(..)`.

![image](https://user-images.githubusercontent.com/6579818/91669966-0ccdb280-eb11-11ea-971e-2cc61556ef12.png)

`client.Spot.Order.GetMyTrades(..)` "order" is not visible

**Comment by JKorf** [comment]
You have an instance of the socket client there, which is used for subscribing to streams. To use the rest API use an instance of `BinanceClient` instead of `BinanceSocketClient`.

**Comment by ivandrofly** [comment]
> You have an instance of the socket client there, which is used for subscribing to streams. To use the rest API use an instance of `BinanceClient` instead of `BinanceSocketClient`.

thank you I found it... my namespace (BinanceClient) was making it undercovered 😆 .. "
