### ISSUE TITLE
Cannot receive events anymore with version 5.1.14

### ISSUE THREAD

**Issue by tbrbde** [JKorf/Binance.Net#412]
I am subscribing for order update, account position and price messages as follows:

var subOkay = socketClient.SubscribeToUserDataUpdates(listenKey, null, OnOrderUpdate, null, OnAccountPositionMessage, null);
var subOkayPrices = socketClient.SubscribeToAllSymbolTickerUpdates(OnPriceMessage);

This has been working for a long time. Since August, 26th, I cannot receive any event messages for orders or positions. Only the price messages are still working. What can be the reason?

Regards,
Jens

**Comment by JKorf** [comment]
Hi, that's hard for me to say. Could you set LogVerbosity to Debug in the client options, and check what the output is when you expect such a message? There'll probably be more information there.

**Comment by tbrbde** [comment]
Hi Jan,
When I start I get the following debug log entries:
2020.09.01 09:06:27:876 | Debug | [3] Creating request for https://api.binance.com/api/v1/userDataStream
2020.09.01 09:06:27:883 | Debug | [3] Sending POST request to https://api.binance.com/api/v1/userDataStream with request body 
2020.09.01 09:06:28:181 | Debug | [3] Response received in 296ms: {"listenKey":"SmEMxQMGwXGsNO7EncdwduugVy3Do2kiz1fWvnjtuD4w3GWOiK9obluhx6tH"}
But I get no entries when I create an order which is filled. I also set a break point into OnOrderUpdate and OnAccountPositionMessage, but these break points are not working because there are no events at all.

**Comment by nikkozp** [comment]
All because of the fact that CryptoExchange.Net is not the latest version.

**Comment by tbrbde** [comment]
It seems to be related to the stable version. I now uninstalled version 5.1.14 and installed the latest beta version. With the beta version the events are working. So I will start using the beta version in order to solve the issue.
