### ISSUE TITLE
Simple example request

### ISSUE THREAD

**Issue by jakubedr** [JKorf/Binance.Net#415]
Hi, I am pretty newbie in C# and I need to make very simple WindowsForm with couple of buttons like Buy/Sell. Also read current prices from Binance. I know about ClientWPF, but I don't undrestand it. I just need simple langueage like _Buy(symbol, volume, _price)__
Could anybody give me simple example of it?

Thank you very much!

**Comment by Kudwig** [comment]
https://github.com/JKorf/Binance.Net/tree/master/Examples
