### ISSUE TITLE
How Binance calculates the order average?

### ISSUE THREAD

**Issue by tkowalczyk** [JKorf/Binance.Net#416]
Please tell me how do Binance calculates the order average from trades?

![obraz](https://user-images.githubusercontent.com/1682564/91994222-a75b0b00-ed36-11ea-8104-9f9c07425761.png)

Do I need to calculate it manually or there is something build into this library?

![obraz](https://user-images.githubusercontent.com/1682564/91994389-d5404f80-ed36-11ea-9c94-7f0f6a63a3b8.png)

**Comment by nikkozp** [comment]
```csharp
var avgPrice = QuantityQuoteFilled / QuantityFilled;
```

**Comment by tkowalczyk** [comment]
@nikkozp could you be more specific? from where can I get these values? There are not such properties in `BinanceOrderTrade`

**Comment by nikkozp** [comment]
From any data related to an Order (not a Trade)

**Comment by JKorf** [comment]
A trade is always at a single price, an order can have multiple trades at multiple price points.
