### ISSUE TITLE
'BinanceClient' does not contain a definition for 'Spot'

### ISSUE THREAD

**Issue by salocinx** [JKorf/Binance.Net#418]
Hi. Thanks for sharing your library! I have set up a Visual Studio C# project and installed the Binance.NET (5.1.14) package by using the packet manager console as described in your readme file.

I am faced with the following error:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'BinanceClient' does not contain a definition for 'Spot' and no accessible extension method 'Spot' accepting a first argument of type 'BinanceClient' could be found (are you missing a using directive or an assembly reference?)	BinanceTestCore	D:\BinanceTestCore\Program.cs	17	Active
```

Screenshot: https://ibb.co/RTSF0TF

Any idea what I am doing wrong?

**Comment by JKorf** [comment]
Hi, the documentation has been updated already for version 6.0.0 which is currently in beta. I would suggest you'd use that version. It is available via the nuget package manager in Visual Studio, though you have to enable the preview versions checkbox on the top.

**Comment by salocinx** [comment]
Thanks for the quick answer! I understand. I now have updated to 6.0.0 beta-6 and the issue above disappeared and I was able to fetch some first data. However, when trying the second sample on this repository's main page, I found some bugs in the second example (missing "new" keyword and missing "braces"). Please compare to the screenshot below. When fixed, the compiler cannot find the `socketClient.Spot.SubscribeToUserStream` function. Do you have renamed this one or has the design completely changed? 

Screenshot: https://ibb.co/p43vLZ7

**Comment by JKorf** [comment]
Ah my bad, that's what you get for writing code without IDE haha.
The `SubscribeToUserStream` has been renamed to `SubscribeToUserDataUpdates`, try that.

**Comment by salocinx** [comment]
Great, perfect! Thank you! Closed.
