### ISSUE TITLE
How to use WebSocket

### ISSUE THREAD

**Issue by asafieh** [JKorf/Binance.Net#42]
Hello JKorf,

I need some help in using web socket, I am getting below response.
and what event will be triggered on new data arrival ! basically how to consume the data.

Thanks in advance.

Output Log:

05:54:45:618 | Error | Socket error The requested name is valid, but no data of the requested type was found.
The thread '<No Name>' (0x1ca8) has exited with code 0 (0x0).
The thread '<No Name>' (0x1c1c) has exited with code 0 (0x0).

The Code:

       Dim _binClient As BinanceClient
        Dim _socketClient As BinanceSocketClient

        Dim result As BinanceStreamKline = Nothing

        If APIKEY IsNot Nothing OrElse APISECRET IsNot Nothing Then
            BinanceDefaults.SetDefaultApiCredentials(APIKEY, APISECRET)
            BinanceDefaults.SetDefaultMaxRetries(3)
            BinanceDefaults.SetDefaultLogOutput(Console.Out)
        Else
            Exit Sub
        End If

        Try
               _binClient = New BinanceClient
                Dim ping As BinanceApiResult(Of Boolean) = _binClient.Ping()
            If Not ping.Success Then
                MsgBox("Ping not responding")
                Exit Sub
            End If

            _socketClient = New BinanceSocketClient
            _socketClient.SubscribeToKlineStream("xrpbtc", KlineInterval.OneMinute, Function(data)
                                                                                           Console.WriteLine("ok")
                                                                                        Return Nothing
                                                                                    End Function)
        Catch ex As Exception
            MsgBox(ex.Message)
        End Try

**Comment by JKorf** [comment]
Hi, the code seems correct, if I run it locally I successfully connect. The error message indicates some problem in the DNS lookup on your network. Could you try on a different network to see if that works? 

The place to process the data is where your Console.WriteLine("ok") is currently. The data object will contain the kline data.

**Comment by asafieh** [comment]
Hi, I have tried on different network and i got the same previous result, I don't think it is related to network I am able to receive data using BinanceClient. 

Dim _binClient As BinanceClient
Dim klines = _binClient.GetKlines("XRPBTC", KlineInterval.FiveMinutes, DateTime.UtcNow.AddHours(-1), DateTime.UtcNow, 10)

 For Each K In klines.Data
                Console.WriteLine($"{K.AssetVolume} : {K.Close} : {K.CloseTime} : {K.High} : {K.Low} : {K.Open} :  
                {K.OpenTime} : {K.TakerBuyBaseAssetVolume} : {K.TakerBuyQuoteAssetVolume} : {K.Trades} : 
                 {K.Volume}")
   Next
 
Is BinanaceClient and BinanceWebSocket using different web sockets ? 
is there any configuration i need to do for BinanceWebSocket or it is plug and play can i change port number ?

Regards,

**Comment by asafieh** [comment]
Hello, I have been trying to resolve connection error without any luck.
my DNS can resolve stream.binance.com  but not  wss://stream.binance.com:9442/ws/bnbbtc@depth5

I was able to connect .net websocket using stream.binance.com .
The strange thing i use profit trailer bot and it connects to wss://stream.binance.com:9442/ws/ without any issues.

Any Idea how i can resolve this problem.

Regards,


Test Output Log:

Dislplay Resolved Endpoint Info..
Endpoint Address : 54.95.98.82
Endpoint AddressFamily : InterNetwork
Endpoint Port : 9443
Endpoint ToString() : 54.95.98.82:9443

Socket connected to 54.95.98.82:9443

HTTP/1.1 400 Bad Request
Server: awselb/2.0
Date: Sat, 24 Feb 2018 14:46:17 GMT
Content-Type: text/html
Content-Length: 138
Connection: close

<html>
<head><title>400 Bad Request</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
</body>
</html>


Test Code:


    Public Sub TestConnection()
        Dim Host As String = "stream.binance.com"
        Dim Port As Integer = 9443
        Call StartClient(Host, Port)
    End Sub

    Public Sub StartClient(host As String, Port As Integer)

        Try

            Dim ipHostInfo As IPHostEntry = Dns.GetHostEntry(host)
            Dim ipAddress As IPAddress = ipHostInfo.AddressList(0)
            Dim remoteEP As IPEndPoint = New IPEndPoint(ipAddress, Port)
            Dim sender As Socket = New Socket(ipAddress.AddressFamily, SocketType.Stream, ProtocolType.Unspecified)

            Call displayEndpointInfo(remoteEP)

            Try

                sender.Connect(remoteEP)
                Console.WriteLine("Socket connected to {0}", sender.RemoteEndPoint.ToString() + vbCrLf)

                Dim httpReq As String = "wss://stream.binance.com:9442/ws/bnbbtc@depth5" & ControlChars.CrLf & ControlChars.CrLf
                sender.Send(ASCII.GetBytes(httpReq))

                Dim buffer(1024) As Byte
                Dim byteCount As Int16 = sender.Receive(buffer, buffer.Length, 0)
                Console.WriteLine(ASCII.GetString(buffer, 0, byteCount))

                sender.Shutdown(SocketShutdown.Both)
                sender.Close()

            Catch ane As ArgumentNullException
                Console.WriteLine("ArgumentNullException : {0}", ane.ToString())
            Catch se As SocketException
                Console.WriteLine("SocketException : {0}", se.ToString())
            Catch e As Exception
                Console.WriteLine("Unexpected exception : {0}", e.ToString())
            End Try


        Catch e As Exception
            Console.WriteLine(e.ToString())
        End Try


    End Sub


    Private Sub displayEndpointInfo(ByVal endpoint As IPEndPoint)

        Console.WriteLine(vbCrLf & "Dislplay Resolved Endpoint Info..")
        Console.WriteLine("Endpoint Address : " + endpoint.Address.ToString())
        Console.WriteLine("Endpoint AddressFamily : " + endpoint.AddressFamily.ToString())
        Console.WriteLine("Endpoint Port : " + endpoint.Port.ToString())
        Console.WriteLine("Endpoint ToString() : " + endpoint.ToString() + vbCrLf)
    End Sub

**Comment by JKorf** [comment]
The BinanceClient is another connection method as BinanceSocketClient. The BinanceClient uses webrequests to request data, whereas the socket client connects to a different endpoint and receives updates. These use different protocols.

Can you put the logverbosity of the client to Debug using `client.SetLogVerbosity(LogVerbosity.Debug)` and post the full log output using Binance.Net?

**Comment by asafieh** [comment]
Hello,
It seems it was something to do with compatibility between dependencies
This morning I got to to work using the follow:
WebSocket4Net                  version 0.15.1.10
SuperSocket.ClientEngine   version 0.9.0.0
Newtonsoft.json                  version 10.0.0.0
netstandard                          version 2.0.0.0           
Binanace.net                         version 2.3.4.0
Target Framework                  4.6  or 4.6 ( works with both ) not above.

However if you remember I was only able to clone using 4.7 framework.

By the way I have sent an email to Binance there is something wrong with GetAllAccountTrades()
some of filled buy trades continuously shows 0 prices.

Thanks for your usual support.

**Comment by asafieh** [comment]
Target Framework 4.6 or 4.5 ( works with both ) not above.

**Comment by JKorf** [comment]
So you got it working now? Or do you still need help? It doesn't work with .net 4.7?
