### ISSUE TITLE
BinanceFuturesClient GetExchangeInfo() throws error

### ISSUE THREAD

**Issue by kerohero** [JKorf/Binance.Net#422]
Error message : "Error deserializing data"
Error code : 5
Error data : e":"MARKET_LOT_SIZE","maxQty":"10000000","minQty":"1"},{"limit":0,"filterType":"MAX_NUM_ORDERS"},{"multiplierDown":"0.8500","multiplierUp":"1.1500","multiplierDecimal":"4","filterType":"PERCENT_PRICE"}],"orderTypes":["LIMIT","MARKET","STOP","STOP_MARKET","TAKE_PROFIT","TAKE_PROFIT_MARKET","TRAILING_STOP_MARKET"],"timeInForce":["GTC","IOC","FOK","GTX"]}]}

**Comment by JKorf** [comment]
Can't reproduce this, but there might've been an unknown value in the data. If this happens again, could you have a look in the output logging? It should contain more info on what went wrong.

**Comment by kerohero** [comment]
I gave up on the method, all I need is the Symbols and Quantity Precision. Made my own method to get those. I'm just letting you know of the issue
