### ISSUE TITLE
Large websocket latency

### ISSUE THREAD

**Issue by viosee** [JKorf/Binance.Net#423]
There is an issue with websocket latency. I tested BookTicker updates of BTCUSDT (FUT) on AWS server for a few hours, just receiving messages and comparing TransactionTime and DateTime.UtcNow. Average latency was 2.5 sec with 5.7 sec peaks! How could it be possible? Something difinitely wrong here.

**Comment by Hulkstance** [comment]
Even tho, we are talking about difference things, may you have look at: https://github.com/JKorf/Binance.Net/issues/430?

**Comment by JKorf** [comment]
Are you sure that your DateTime.UtcNow time is correct? DateTime.UtcNow relies on your local computer time. If the computer time isn't synced regularly this can deviate quite a bit from the server time, which is kept synced. Checking the server time vs the my local computer time right now there is actually a +- 8 seconds difference. 

Issues with timestamps have been known to be resolved when installing SP TimeSync 2.4 and setting the sync interval < 10 minutes.

**Comment by viosee** [comment]
I am aware that my local time and Binance server time are likely not in sync, so I removed the difference from latencies:
`var min = times.DefaultIfEmpty().Min();`
`times = times.Select(span => span - min).ToList();`
`var avg = new TimeSpan((long) times.DefaultIfEmpty().Average(span => span.Ticks));`
`var max = times.DefaultIfEmpty().Max();`
Here i made an assumption that at least one event comes without delay, and this is how I've got 2.5 sec average and 5.7 sec max.
`times` here is a `List<TimeSpan>` with `DateTime.UtcNow - transactionTime` inside.
The local time on my server is updated once a day, I'll try to do another test and make sure that the local time is not updated during it.

**Comment by thomasd3** [comment]
It's worth taking note that Binance's sockets have been having problems for the past few weeks. I have talked to people that are not using Binance.Net and they see similar issues, with disconnections, delayed updates, etc.
This is discussed regularly on the telegram chat dedicated to the Binance API.
Check this tool written by one of the chat's users (Mike): https://github.com/Mike-Mercer/Binance-ws-lags
it tracks the socket lag.

**Comment by viosee** [comment]
We've done a lot of tests on different locations. Along with Binance.Net socket, we tested custom sockets written in python, c++ and c#, and saw no difference between them. Obviously, these latencies are not a software problem. I think we can close this issue.
