### ISSUE TITLE
Sample RegisterTo Stream in firstPage documentation doesn't work!

### ISSUE THREAD

**Issue by Mojtaabaa** [JKorf/Binance.Net#424]
var client = new BinanceClient(new BinanceClientOptions{
	ApiCredentials = new ApiCredentials("APIKEY", "APISECRET")
});
var startResult = client.Spot.UserStream.StartUserStream();
the sample provided in first page doesn't work.
i think it is deprecated.?
am i right?
does first page documentation needs an update?

**Comment by developocalypse** [comment]
Try the latest beta version instead - it's at least as good as the latest non-beta as far as I can tell, and the documentation is correct, or more correct.

**Comment by Mojtaabaa** [comment]
tnx
