### ISSUE TITLE
Updates to the User Data Stream Websocket Payloads (Binance)

### ISSUE THREAD

**Issue by philipp-troxler** [JKorf/Binance.Net#426]
Hello,
I received an email from Binance today that requires adjustments to the websockets. Is there anything planned for the next few days?
Click here for the announcement:
[Updates to the User Data Stream Websocket Payloads](https://www.binance.com/en/support/articles/c386a9ce44e74e15a796f56289a763d6)

greetings from Switzerland
Philipp Troxler

**Comment by JKorf** [comment]
Hi, latest update on that is that they'll leave in the update for now, though they marked it as deprecated and it will be removed at some later unknown date. I've noted it as such in the library.
