### ISSUE TITLE
GET /api/v3/klines (rest-api)

### ISSUE THREAD

**Issue by pdx2k** [JKorf/Binance.Net#427]
Hello!

I Love That Sharp Libary!

In That Offical Binance Rest-API Documentation At "**GET /api/v3/klines**" Follow That JSON Response:

[
  [
    1499040000000,      // Open time
    "0.01634790",       // Open
    "0.80000000",       // High
    "0.01575800",       // Low
    "0.01577100",       // Close
    "148976.11427815",  // Volume
    1499644799999,      // Close time
    "2434.19055334",    // Quote asset volume
    308,                // Number of trades
    "1756.87402397",    // Taker buy base asset volume
    "28.46694368",      // Taker buy quote asset volume
    **"17928899.62484339" // Ignore.**
  ]
]

  **"17928899.62484339" // Ignore.** That Token Did Not Exist Yet In Binance.Net Response Data Object As Property.

I Hope You Can Include Them, I Really Think Its Also An Important Variable For Analysis!

Thanks For Reading, Marcel S.

**Comment by JKorf** [comment]
Added it in the latest 6.0.0 version, though I'm not sure if it is any good to use since it's specifically labeled 'Ignore'
