### ISSUE TITLE
Binance Client  client.GetOpenOrdersAsync() and client.GetAccountInfoAsync() error

### ISSUE THREAD

**Issue by BenDavison** [JKorf/Binance.Net#429]
Hi,
  Before the latest version of Binance dll both of these api calls worked for me.  Now both fail with error "Signature for this request is not valid."

  Is this a known issue?

  Again I might get a chance to look myself but hoping this is already being looked at?

Ben

**Comment by JKorf** [comment]
I'm going to assume fixing the versions as described in #428 will fix this as well.

**Comment by BenDavison** [comment]
Hi,

  Thanks for getting back to me so quickly, yes this did indeed fix both of
the issues.

  I can carry on developing.... had a bit of a break over the summer but
when/if this app starts to make some profit I will be sure to send some
love in your direction.

  Keep up the good work

Ben

**Comment by BenDavison** [comment]
Hi Jan,

  FYI my application is listening and interacting with multiple accounts on
multiple exchanges, chiefly Binance, Bittrex and Kraken.  After downgrading
the version of CryptoExchange.Net to get my Binance connection back up and
running, the other exchanges no longer connect.  It has made me question my
design a little and I may consider running the exchange connections in
separate services with separate dependencies but at the moment this is
causing me a bit of a headache.  In the short term is there a combination
of Binance, Bittrex and Kraken versions that all work with the same
downgraded CryptoExchange.Net without introducing other instabilities?

  Many thanks

Ben

**Comment by JKorf** [comment]
I guess you should either update Binance to use the latest version (6.0.0 just pushed), or you'll have to downgrade Bittrex and Kraken one version so they work with the CryptoExchange.Net v3.0.12 version.

**Comment by JKorf** [comment]
Closing this since with the latest version there should be no more library miss matches

**Comment by BenDavison** [comment]
Thanks I will update my packages
