### ISSUE TITLE
The Final property

### ISSUE THREAD

**Issue by Hulkstance** [JKorf/Binance.Net#431]
What happened to the `Final` property in v6.0.0?

```csharp
var subResult = await SocketClient.Spot.SubscribeToKlineUpdatesAsync(symbol, interval, async data =>
{
	if (data.Data.Final)
	{
	}
	else
	{
	}
}).ConfigureAwait(false);
```

**Comment by JKorf** [comment]
Ah, seems like it got forgotten in the interface. Do you have any other missing properties? I'll fix it right away.

**Comment by Hulkstance** [comment]
@JKorf, thanks. Anyway, I don't think there is. I almost refactored everything.

**Comment by JKorf** [comment]
Try 6.0.1, should have the Limit property again.

**Comment by Hulkstance** [comment]
> 
> 
> Try 6.0.1, should have the Limit property again.

Thanks :)
