### ISSUE TITLE
How we can get Mark price for btc

### ISSUE THREAD

**Issue by SayidJafari** [JKorf/Binance.Net#433]
This is my code
 double btc = Convert.ToDouble(BClinet.GetPrice("BTCUSDT").Data.Price);

**Comment by JKorf** [comment]
I suggest using the 6.0.1 version of Binance.Net. With that version it is `client.FuturesUsdt.Market.GetMarkPrices("BTCUSDT");`

**Comment by SayidJafari** [comment]
That code returns  1   but the real price is 10,294.27

**Comment by developocalypse** [comment]
I can confirm that Bitcoin are not currently available for a dollar on Binance.

**Comment by SayidJafari** [comment]
that code did not work for ETCUSDT

**Comment by developocalypse** [comment]
if you are still having problems, can you post the binance.net version and the simplest failing code without the converter, something like decimal price = ...

**Comment by SayidJafari** [comment]
I am new in programming and this is my code

        double BTUSDbid;       

	   private void BtnBinanceConnect_Click(object sender, EventArgs e)
        {

            global::Binance.Net.BinanceClient.SetDefaultOptions(new BinanceClientOptions()
            {
                ApiCredentials = new CryptoExchange.Net.Authentication.ApiCredentials("m5pNMyUwgsbU9YN???????", "HKtWmDxdbArU?????"),
                LogVerbosity = CryptoExchange.Net.Logging.LogVerbosity.Debug,
            });



                while (true)
                {
    				BTUSDbid = Convert.ToDouble(BClinet.FuturesUsdt.Market.GetMarkPrices(BTCUSDT));          

                    Thread.Sleep(1);
                }
         
        }
		api version is 6.0.1

if there is a sample code which work please send me 
Regards

**Comment by developocalypse** [comment]
I'm not using futures and I don't know what mark prices are, but I can see that GetMarkPrices returns one or more items, rather than a single item. If you use this code then you will at least get a single price.

put this inside your while loop
```
//get one price (hopefully)
var price = BClinet.FuturesUsdt.Market.GetMarkPrices(BTCUSDT).Data.FirstOrDefault().MarkPrice;
//convert it if you must (decimals are pretty good though)
BTUSDbid = Convert.ToDouble(price);
```
