### ISSUE TITLE
IBinanceTick vs IBinance24HPrice

### ISSUE THREAD

**Issue by nikkozp** [JKorf/Binance.Net#435]
Hi

This two interfaces have same properties for Spot / USDT-M / Coin-M

Why u added IBinance24HPrice?

**Comment by JKorf** [comment]
IBinance24HPrice doesn't have best bid/ask info, where IBinanceTick does. On the futures API's the Get24hPrices call doesn't return the BestBids/BestAsks. I see the spot API does return this, so I'll change the return type of that into IBinanceTick to expose the data.

I'll also make IBinanceTick extend IBinance24hPrice which in turn extends IBinanceMiniTick to make it easier to process the return objects.

**Comment by JKorf** [comment]
Updated in latest version
