### ISSUE TITLE
problem with communication with binanace

### ISSUE THREAD

**Issue by azarlift** [JKorf/Binance.Net#436]
hi dear users
im new in git hub and wanna to write a simple code in c# to get price of btc or server time from binance
 i download client console code and execute it in vs2019.
"https://github.com/JKorf/Binance.Net/tree/master/Examples/ClientConsole"

i.v installed binance.net to my project. and there is no error in code compiling and execution
but i receive this error in console window when i run the program
"an error occurred while sending the request"
below link is image of execution of program 
https://ibb.co/DRLfy2c

tanks for helping

**Comment by JKorf** [comment]
Seems like an issue with the network, not with the library. Can you try reaching the API in the browser? For example, do you see data returned when going to this link? 
https://api.binance.com/api/v3/ticker/price

**Comment by azarlift** [comment]
there is no problem with this link
it returned a line contain price list of coins in array format
[{"symbol":"ETHBTC","price":"0.03483800"},{"symbol":"LTCBTC","price":"0.00460400"},{"symbol":"BNBBTC","price":"0.00266650"} .....
and similar links like https://api.binance.com/api/v3/avgPrice?symbol=BTCUSDT
returns correct response
{"mins":5,"price":"10719.40268371"}

in this case that there is response from binance in browser u think i.v problem with network connection ?
if yes , what kind of problem? 
permission to accessing to network ? or other

thanks to accompaniment

**Comment by JKorf** [comment]
Might be a firewall issue. Are you on a public network?

**Comment by azarlift** [comment]
im in private network . i turned off windows firewall  too.
i think maybe problem is related to  vpn o other similar things.
let me check all of them.

i.ll explain here if solved.

tanks again

**Comment by azarlift** [comment]
hi again
problem solved.

my browser extension vpn  was active and my ip was changed to london in browser.
and in browser, api commands (like this"https://api.binance.com/api/v3/ticker/price" ) execute with no problem.
but in windows my ip is differ from browser. that is belong to country that binance not service them.
i install a Vpn and change my ip.

and problem fiiinaly solved.  : )

thank u sooooo much. Jkorf.

**Comment by JKorf** [comment]
Great to hear you got it working
