### ISSUE TITLE
Has Coin-M been supported?

### ISSUE THREAD

**Issue by tamuLA** [JKorf/Binance.Net#438]
Thank you for your updating. 
I tried new methods, but Coin-M APIs don't work.
 
example:
Client.FuturesUsdt.Account.GetAccountInfo works
Client.FuturesCoin.Account.GetAccountInfo doesn't work

Possibly, isn't it supported yet?

**Comment by JKorf** [comment]
Hi, they should both work. For me they both return the account info. Can you have a look in the output logging when setting LogVerbosity = LogVerbosity.Debug in the client options?

**Comment by tamuLA** [comment]
Hi, I solved my topic. The reason is probably windows 7.
I tried on Windows 10 PC, then the same code worked. 
On 7 PC with the same code, 400 Bad Request was returned.
Thanks a lot, JKorf.
