### ISSUE TITLE
proper auto-reconnection from sockets

### ISSUE THREAD

**Issue by thomasd3** [JKorf/Binance.Net#439]
Hi Jan,

Here's how we do the connection / reconnection to sockets in F#:

```
        let rec subscribeToTrades () =
            let r =
                socketClient.SubscribeToAggregatedTradeUpdatesAsync(symbol, fun trade -> tradesProcessor.Post(trade))
                |> Async.AwaitTask
                |> Async.RunSynchronously
            if not r.Success then failwithf "couldn't subscribe to trades updates -  %i:%s" r.Error.Code r.Error.Message
            else
                r.Data.add_ConnectionLost     (fun _ -> eprintfn "%A - trades socket connection lost" DateTime.UtcNow)
                r.Data.add_ConnectionRestored (fun _ -> eprintfn "%A - trades socket connection restored" DateTime.UtcNow
                                                        subscribeToTrades())

```

as you wrote the lib, could you confirm if this is optimal, or if there would be something you'd do differently when it comes to the subscription / reconnection mechanism?

**Comment by JKorf** [comment]
Hi Thomas. The library handles reconnecting and resubscribing out of the box, so you shouldn't have to do the subscribeToTrades call in the ConnectionRestored event. You can test it by subscribing and pulling out your ethernet cable or disconnecting your wifi for example. When the connection is restored you should see the data coming in again.

**Comment by thomasd3** [comment]
oh ok, so the connection lost and restored events are purely informational?

**Comment by JKorf** [comment]
Yes. It could be used for example to stop trading when the connection is lost since the data might not be up to date, and to resume trading when connection is restored.

**Comment by thomasd3** [comment]
ok, very good; thanks for the clarification!

**Comment by thomasd3** [comment]
actually a related question: do you handle the listen key directly too, for the SubscribeToUserDataUpdatesAsync call?

right now I resubscribe when if the license key is expired

**Comment by JKorf** [comment]
No, listenkey should indeed be handles manually. The advise is to call KeepAlive every 30 minutes, but I don't think there is any downside to calling it every 10 minutes. I think you only get the listen key expired after 60 minutes without keep alive, so you shouldn't run into that.

Looks just fine they way you're handling it.
