### ISSUE TITLE
Problem with Binance.Net library build

### ISSUE THREAD

**Issue by dyrdaw** [JKorf/Binance.Net#44]
Hello,
I was trying lot of things but i just cannot compile the project.
I have following errors:

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'WebRequest' could not be found (are you missing a using directive or an assembly reference?)	Binance.Net(netstandard2.0)	D:\Users\Dawid\Desktop\Binance.Net-master\Binance.Net\Implementations\Request.cs	8	Active
Error	CS0246	The type or namespace name 'WebRequest' could not be found (are you missing a using directive or an assembly reference?)	Binance.Net(netstandard2.0)	D:\Users\Dawid\Desktop\Binance.Net-master\Binance.Net\Implementations\Request.cs	10	Active
Error	CS0246	The type or namespace name 'WebHeaderCollection' could not be found (are you missing a using directive or an assembly reference?)	Binance.Net(netstandard2.0)	D:\Users\Dawid\Desktop\Binance.Net-master\Binance.Net\Implementations\Request.cs	15	Active
Error	CS0246	The type or namespace name 'WebHeaderCollection' could not be found (are you missing a using directive or an assembly reference?)	Binance.Net(netstandard2.0)	D:\Users\Dawid\Desktop\Binance.Net-master\Binance.Net\Interfaces\IRequest.cs	7	Active
Error	CS0534	'TraceTextWriter' does not implement inherited abstract member 'TextWriter.Write(char)'	Binance.Net(netstandard2.0)	D:\Users\Dawid\Desktop\Binance.Net-master\Binance.Net\Logging\TraceTextWriter.cs	7	Active
Error	CS0246	The type or namespace name 'WebResponse' could not be found (are you missing a using directive or an assembly reference?)	Binance.Net(netstandard2.0)	D:\Users\Dawid\Desktop\Binance.Net-master\Binance.Net\Implementations\Response.cs	9	Active
Error	CS0246	The type or namespace name 'WebResponse' could not be found (are you missing a using directive or an assembly reference?)	Binance.Net(netstandard2.0)	D:\Users\Dawid\Desktop\Binance.Net-master\Binance.Net\Implementations\Response.cs	11	Active

It looks like missing System.Net namespace but it is not. I think the solution is simple but I cannot find it.

I have Visual Studio 2017, Windows 8.1

**Comment by JKorf** [comment]
Hm that is weird. You forked the library? Or used Nuget?

**Comment by dyrdaw** [comment]
Problem solved:
I installed net core 2.0 and updated Visual Studio
