### ISSUE TITLE
Order Book Question display like Binance and Save the data.

### ISSUE THREAD

**Issue by ExceedingLife** [JKorf/Binance.Net#442]
Hello all, I would like to display and save the orderbook like it shows up on binance in my project. I believe I am close but not completely sure how to do this. Once I display it correctly and dont have duplicates completely refreshing my listview then I can just add a SQL query to save the data to a table. 
Has anyone done this and how would I set this up?
Here is what I currently have.
` var bookData = BinanceSocketClient.SubscribeToPartialOrderBookUpdates("BTCUSD", 10, null, (data) =>
                {
                    OrderBookV0(data);
                });
 private async Task OrderBookV0(BinanceOrderBook book)
        {
            //lstBook.Items.Clear();
            if (book != null)
            {
                try
                {
                    await lstBook.Dispatcher.InvokeAsync(() =>
                    {
                        foreach(var askItem in book.Asks)
                        {
                            var ask = string.Format("{0,10} {1,10} ", askItem.Price, askItem.Quantity);
                            //lstBook.Items.Insert(0, ask);
                            lstBook.Items.Add(ask);
                        }
                        foreach(var bidItem in book.Bids)
                        {
                            var bid = string.Format("{0,10} {1,10} ", bidItem.Price, bidItem.Quantity);
                            //lstBook.Items.Insert(lstBook.Items.Count - 1, bid);
                            lstBook.Items.Insert(0, bid);
                        }
                    });
                    // update.Status
                }
                catch (Exception ex) { }
            }
        }
`

**Comment by ExceedingLife** [comment]
So I got my listview behaving like the Binance Orderbook. Now my question is how should I save the data so there isnt duplicates ? The asks and bids only show Price/Quantity. In the BinanceOrderBook the only other value is "LastUpdateId"... Here is my code that makes it behave correctly but the saving im unsure about.
`
private async Task OrderBookV0(BinanceOrderBook book)
        {
            //lstBook.Items.Clear();
            if (book != null)
            {
                try
                {
                    await lstBook.Dispatcher.InvokeAsync(() =>
                    {
                        lstBook.Items.Clear();
                        foreach (var askItem in book.Asks)
                        {
                            var ask = string.Format("{0,19} {1,18} {2,10} ", askItem.Price, askItem.Quantity, "A");
                            //lstBook.Items.Insert(0, ask);
                            lstBook.Items.Add(ask);
                        }
                        foreach(var bidItem in book.Bids)
                        {
                            var bid = string.Format("{0,19} {1,18} {2,10}", bidItem.Price, bidItem.Quantity, "B");
                            //lstBook.Items.Insert(lstBook.Items.Count - 1, bid);
                            lstBook.Items.Insert(0, bid);
                        }
                    });
                    // update.Status
                }
                catch (Exception ex) { }
            }
        }
`

**Comment by JKorf** [comment]
Have you taken a look at the BinanceSymbolOrderBook class?

**Comment by ExceedingLife** [comment]
I use the websockets in your API
BinanceSocketClient.SubscribeToOrderBookUpdates("BTCUSD", null, async (data) =>
I am close to building this order book the correct way but it updates every second changing the orders... I would like it to only change the newly added or changed orders not all of them.
Have you ever build an in memory object of the current binance order book ~12 trades each way ?
Sorry on the late reply

**Comment by JKorf** [comment]
Have you seen my last comment? There is an implementation available which you can look at. Running this in an console application will print the current order book with 12 entries each way:
````C#

            var orderBook = new BinanceSpotSymbolOrderBook("BTCUSDT");
            orderBook.OnStatusChange += (from, to) =>
            {
                Console.WriteLine($"Changed from {from} to {to}");
            };

            var startResult = await orderBook.StartAsync();
            if (!startResult)
            {
                Console.WriteLine("Failed to start: " + startResult.Error);
                Console.ReadLine();
            }

            while (true)
            {
                Console.Clear();
                Console.WriteLine(orderBook.ToString(12));
                await Task.Delay(500);
            }

````

**Comment by ExceedingLife** [comment]
I will give it a shot this weekend and let you know how it turns out.
Sorry for the late reply and thanks for the info. 
I hope this is what I'm looking for!!

**Comment by ExceedingLife** [comment]
There is no 'BinanceSpotSymbolOrderBook()' in the class. I see a 
`var orderbook = new BinanceSymbolOrderBook("BTCUSD");`
I'm trying to just display the order book in a listview but so far no luck..

```
var orderbook = new BinanceSymbolOrderBook("BTCUSD");
               // var bk = new BinanceSpotSymbolOrderBook("BTCUSD");
                var start = orderbook.Start();


                orderbook.OnStatusChange += (from, to) =>
                {
                    lstOB.Items.Add(orderbook.ToString(12));
                };
```

**Comment by ExceedingLife** [comment]
Thank you for this!
I actually got this working yesterday.
But now I want these records to be in memory and to update and only show 12 each way. I see how it returns the records every second depending what the delay is.
How can I set it up so it puts them in an object and removes and replaces them or they stay the same depending on the new ones coming in. I been playing with this for awhile now but I have not been successful with this yet.. Do I have to use lastrecordID ? or compare the new object coming in with that I already have. I also am thinking I should use 
``Ob_OnOrderBookUpdate`` instead of ``while (true)``

Do you have any examples of this? 

```
 var ob = new BinanceSymbolOrderBook("BTCUSD");
            ob.OnStatusChange += Ob_OnStatusChange;

            var start = await ob.StartAsync();
            if (!start)
            {
                Console.WriteLine("Failed to start" + start.Error);
            }

            ob.OnOrderBookUpdate += Ob_OnOrderBookUpdate;

            while (true)
            {
                Console.WriteLine(ob.ToString(12));
                await Task.Delay(5000);
            }

            Console.ReadLine();
        }

        private static void Ob_OnOrderBookUpdate(IEnumerable<CryptoExchange.Net.Interfaces.ISymbolOrderBookEntry> arg1, IEnumerable<CryptoExchange.Net.Interfaces.ISymbolOrderBookEntry> arg2)
        {
            Console.WriteLine(arg1.ToString());
        }

        private static void Ob_OnStatusChange(CryptoExchange.Net.Objects.OrderBookStatus from, CryptoExchange.Net.Objects.OrderBookStatus to)
        {
            Console.WriteLine($"Changed from {from} to {to}");
        }
```

**Comment by JKorf** [comment]
You can access the bids/asks on the order book object, they will be the latest version of the data. If you change the update interval from 1000 to 100 you'll see the console updating every 100ms. You can access book.Bids or book.Asks yourself to get the current state of the book at any moment.

````C#
            var book = new BinanceSpotSymbolOrderBook("BTCUSDT", new BinanceOrderBookOptions(null, 1000));
            book.OnOrderBookUpdate += (o) =>
            {
                Console.Clear();
                Console.WriteLine(book.ToString(12));
            };

            await book.StartAsync();

            Console.ReadLine();
````
