### ISSUE TITLE
BinanceFuturesStreamORderUpdates not receiving fills or partial fills for trailing stop order types

### ISSUE THREAD

**Issue by ajhici** [JKorf/Binance.Net#447]
I have a BinanceFuturesStreamORderUpdates which doesn't seem to be gettign all of the order updates for a trailing stop order type.  Binance accepts the order, and processes and executes the order but I never get any order updates on the partial or fill updates.

**Comment by thomasd3** [comment]
it is systematic? or just in some random cases?

**Comment by ajhici** [comment]
Sorry for the delayed response.  This was happening on every trailing stop order that was being partially filled.  However, I upgraded to the latest build and this has resolved itself.  I was 3 builds behind. Not sure if that means it's fully resolved but I have not seen any more instances since upgrading.

**Comment by JKorf** [comment]
Let us know if this happens again, for now I'll assume it was an issue with the version.
