### ISSUE TITLE
BinanceFuturesStreamOrderUpdate doesn't have UpdateTime field

### ISSUE THREAD

**Issue by NektoDron** [JKorf/Binance.Net#449]
It can be obtained from "T" - Transaction time.

It would also be great if BinanceFuturesStreamOrderUpdate and BinanceStreamOrderUpdate(and other similar class pairs) have common interface.

**Comment by JKorf** [comment]
The tansaction time has been added in the models. I'll look at common interfaces at a later date.

**Comment by NektoDron** [comment]
it's worked
