### ISSUE TITLE
How to use data WebSocket

### ISSUE THREAD

**Issue by Swisization** [JKorf/Binance.Net#45]
how to use websocket data in another method

`var successKline = socketClient.SubscribeToKlineStream("bnbbtc", KlineInterval.OneMinute, (data) =>
                {
                    // it is possible here
                });

//need here
`

**Comment by JKorf** [comment]
Hi, 

What are you trying to do? I understand what your question is, but why would you need it outside the handler? You can make it a seperate method if that helps you:
````C#
var successKline = socketClient.SubscribeToKlineStream("bnbbtc", KlineInterval.OneMinute, HandleData);

function void HandleData(BinanceStreamKline data)
{
    // Handle data
}
````
