### ISSUE TITLE
Field name consistency (low priority)

### ISSUE THREAD

**Issue by thomasd3** [JKorf/Binance.Net#450]
In BinanceFuturesStreamPosition, there is the field: UnRealizedPnL
whereas in BinanceFuturesPosition there is the field: UnrealizedPnL

Notice the difference of capitalization for the 'R' in Realized.

It would be nice to eventually make it consistent (although I'm not sure which one would be better)

**Comment by JKorf** [comment]
Adjusted in the latest version, they should all be UnrealizedPnl now.
