### ISSUE TITLE
Timestamp for futures balance api call

### ISSUE THREAD

**Issue by thomasd3** [JKorf/Binance.Net#451]
When I use postman with: {{url}}/fapi/v1/balance?timestamp={{timestamp}}&signature={{signature}}
I get:

{
        "accountAlias": "sRTimYoCfWXq",
        "asset": "USDT",
        "balance": "100.90511956",
        "withdrawAvailable": "100.90511956",
        "updateTime": 1596479387646
    },

but when it is read by Binance.Net, the updateTime field is DateTime.MinValue

**Comment by JKorf** [comment]
The model is based on the Coin-M API, but it's slightly different from the USDT-M API. I'll create separate models for these.

Note; The library calls the V2 endpoint instead of V1: /fapi/v2/balance

**Comment by JKorf** [comment]
Updated the models in the latest version
