### ISSUE TITLE
PlaceOrder

### ISSUE THREAD

**Issue by SayidJafari** [JKorf/Binance.Net#453]
Hi dear sir
May I ask you wite sample code for place order

Con.FuturesUsdt.Order.PlaceOrder("BTCUSDT",   
I could not write this code

Thank you for all your help

**Comment by SayidJafari** [comment]
![Untitled](https://user-images.githubusercontent.com/45521073/94134445-dadd1100-fe6e-11ea-80e3-5361d6a844e2.png)


this is error

**Comment by JKorf** [comment]
It seems like you have a bool variable called Binance somewhere in your code which is causing issues.
Check if you have something like this `bool Binance = true;` and rename the variable.

**Comment by SayidJafari** [comment]
right but my code returns this error {2: No credentials provided for private endpoint } how can I fix this

private void button1_Click(object sender, EventArgs e)
        {
            var Order = SER1_BinanceClient.FuturesUsdt.Order.PlaceOrder("BTCUSDT", OrderSide.Buy, Binance.Net.Enums.OrderType.Market, 0.001m,
                null, Binance.Net.Enums.TimeInForce.GoodTillCancel, null, Convert.ToDecimal(SER1_B_XBTUSDbid), null, null, null, null, null, null, null, default(CancellationToken));

        }

**Comment by SayidJafari** [comment]
please answer this question

**Comment by JKorf** [comment]
You'll need to pass your APIKEY and APISECRET to the client. It is described in the ReadMe of CryptoExchange.Net: https://github.com/JKorf/CryptoExchange.Net
