### ISSUE TITLE
Price on StopLossLimit order wrong

### ISSUE THREAD

**Issue by otium99** [JKorf/Binance.Net#454]
When a stop loss is triggered and the actual trading price is above the limit price, it shows the limit price from the stop loss instead of the actual trading price.

**Example for a StopLossLimit**
Price: 0.00002680 (Which is the limit price, but **not** necessarily the trading price!)
StopPrice: 0.00002700

Actual Trading Price: 0.00002694, this is what shows on the Website as "Average" or "Trading price". But you don't get this information in the API, it just returns the Price that you set originally as limit price.

So how do we get the actual trading price?

Thank You

**Comment by JKorf** [comment]
I don't see a way in the API documentation (you can have a look for yourself to make sure) to get this via an order, so you might need to get the individual trades using `client.Spot.Order.GetMyTrades()`, grouping them by order and checking the prices on those.

**Comment by otium99** [comment]
Yep! That is the solution. Thank you. I wasn't aware of the difference between Order and Trade.
