### ISSUE TITLE
Binance Futures Testnet Websocket

### ISSUE THREAD

**Issue by emin-karadag** [JKorf/Binance.Net#455]
Hello,
I want to use a websocket for BinanceFutures Testnet. However, I could not establish a connection.
The code block is as follows. Where am I making a mistake?

The value of startResult returns false.

```
var client = new BinanceClient(new Binance.Net.Objects.Spot.BinanceClientOptions
{
     FuturesUsdtBaseAddress = "wss://stream.binancefuture.com/",
     ApiCredentials = new ApiCredentials(_options.ApiKey, _options.ApiSecret)
});

var startResult = client.FuturesUsdt.UserStream.StartUserStream();
if (!startResult.Success) throw new Exception($"Failed to start user stream: {startResult.Error}");
```

**Comment by JKorf** [comment]
What is the value of the Error property?
Also, did you make an account / api key specifically for the test net?

**Comment by emin-karadag** [comment]
Hello,
You can see the error on the screen below.
Also, yes I am using a separate ApiKey / SecretKey for Binance Futures Testnet.




![binancenet](https://user-images.githubusercontent.com/7556164/94600868-41ad6080-029b-11eb-9554-ffbcb4bde7e9.png)

**Comment by mdsoni** [comment]
**Spot API URL	                                          Spot Test Network URL**
https://api.binance.com/api	                  https://testnet.binance.vision/api
wss://stream.binance.com:9443/ws	   wss://testnet.binance.vision/ws
wss://stream.binance.com:9443/stream	   wss://testnet.binance.vision/stream

**Comment by mdsoni** [comment]
![image](https://user-images.githubusercontent.com/37260725/94984446-9f76cc80-0569-11eb-88fb-4158e96b48e2.png)

**Comment by emin-karadag** [comment]
Hello @mdsoni 

Thank you for your answer. However, what you have stated applies to Binance Spot and Binance Spot Testnet. I cannot connect to Binance Futures Testnet. (websocket)

**Comment by JKorf** [comment]
Oh I see what is wrong. You're passing the websocket address to the Rest api client. The BinanceClient class is used to communicate with the Rest api, the BinanceSocketClient class is used to connect to streams. 

When using the BinanceClient to start the user stream (which is the correct thing to do before actually subscribing with the socket client) you should set the base address property in the options to the Rest address of the testnet, not the websocket address.

**Comment by emin-karadag** [comment]
Hello @JKorf ,
I tried to do as I understand what you said. However, I still haven't been successful.
I will share the screenshots.
Couldn't find exactly where I went wrong? :(




![Ekran Alıntısı](https://user-images.githubusercontent.com/7556164/95238816-b9870800-0812-11eb-8e3a-069cc7a7f5a1.png)






========================================
========================================
========================================






![Adsız](https://user-images.githubusercontent.com/7556164/95238975-f7842c00-0812-11eb-8c53-ebf4756b4d4e.png)






========================================
========================================
========================================






![Adsız2](https://user-images.githubusercontent.com/7556164/95239130-30bc9c00-0813-11eb-81a6-3a1c73fc829d.png)






========================================

**Comment by JKorf** [comment]
I see there is an issue with generating the URL when manually settings the base address when the URL doesn't end with '/'.
Can you try setting the URL in the socket client to `wss://stream.binancefuture.com/` instead of `wss://stream.binancefuture.com`?

Also, the Subscribe methods also return a CallResult, so when you're having issues you could also check if there is any useful information in the Error property of that, same as you're already doing with the `StartUserStream` call.

**Comment by emin-karadag** [comment]
@JKorf 
I did what you said yes and it worked. Thank you. :))
