### ISSUE TITLE
Implement Simple KLine data for BTCUSDT in asp.net core mvc (Example project not working)

### ISSUE THREAD

**Issue by samanatabaki** [JKorf/Binance.Net#457]
hi
I have problem in showing price board in my websites main page. What is the best approach to get data and show the chart for btcusdt price? 
I want the best approach to get live data from binance and update it on my home page (home/index)

**Comment by JKorf** [comment]
I've updated the examples, have a look in that. As far as I can see they worked before though.
In regards of having a chart for the price, I've used the TradingView widget before with success:
https://www.tradingview.com/widget/advanced-chart/
