### ISSUE TITLE
POST method not support for  GetSubAccountBtcValuesAsync

### ISSUE THREAD

**Issue by hungvv07** [JKorf/Binance.Net#458]
I got error Post Method not support when trying to run "GetSubAccountBtcValuesAsync" in SubClients/BinanceClientSubAccounts

request should be config to HttpMethod.Get instead of HttpMethod.Post

Thanks

**Comment by JKorf** [comment]
You're right, I'll fix it in the next release. Thanks for the notice!

**Comment by JKorf** [comment]
Is fixed in the latest version
