### ISSUE TITLE
Trailing Stop Loss?

### ISSUE THREAD

**Issue by nybroe** [JKorf/Binance.Net#460]
How do I execute a trailing stop loss order? I can't find any order type that seems to be able to do this.

**Comment by Kudwig** [comment]
there is no trailing stop loss order type on binance...they do have stop-limit orders that you can use with the correct logic to perform that fuction.

**Comment by Kudwig** [comment]
https://github.com/JKorf/Binance.Net/issues/370 is examples of stop limit orders

**Comment by nybroe** [comment]
Thank you for the quick reply.
I might have missunderstood something or this post from Binance is outdated but it sure looks like it is possible:
https://www.binance.com/en/support/faq/360042299292

But maybe not available from their api yet?

**Comment by JKorf** [comment]
As far as I can see this doesn't seem to be supported be the API

**Comment by nybroe** [comment]
That's unfortunate! Thank you for the quick responses though!

**Comment by Kudwig** [comment]
looks like its on the futures trading market under stop-limit...https://www.binance.com/en/futures/BTCUSDT.
would be nice if it can be incorporated in the api and on the spot trading aswell.

**Comment by Kudwig** [comment]
https://binance-docs.github.io/apidocs/futures/en/#new-order-trade
