### ISSUE TITLE
UsedWeight returns null

### ISSUE THREAD

**Issue by brandtr** [JKorf/Binance.Net#462]
I believe there is a bug in the UsedWeight method in the BinanceHelper.
My code stopped working and this method always returns null. I believe  `s.Key.StartsWith("X-MBX-USED-WEIGHT-")).Value;`
should be case insensitive, as my headers are x-mbx-used-weight-.

I don't know why this doesn't work anymore, but for me this code works:

`s.Key.StartsWith("X-MBX-USED-WEIGHT-",StringComparison.InvariantCultureIgnoreCase)).Value;`

Could you please verify this?

**Comment by JKorf** [comment]
You're right, I guess they must've changed it server side. Will be fixed in the next release.

**Comment by brandtr** [comment]
> You're right, I guess they must've changed it server side. Will be fixed in the next release.

Great! Thanks!

**Comment by JKorf** [comment]
Latest version included the fix
