### ISSUE TITLE
TransferFuturesAccount does only transfer non-fractional numbers

### ISSUE THREAD

**Issue by Amannda123** [JKorf/Binance.Net#464]
`decimal amountToSave = (decimal) 5.012354;`

`var id = client.Spot.Futures.TransferFuturesAccount("USDT", amountToSave , FuturesTransferType.FromUsdtFuturesToSpot);`
=> returns  "-1022: Signature for this request is not valid"

`var id2 = client.Spot.Futures.TransferFuturesAccount("USDT", Decimal.Round(amountToSave ,0), FuturesTransferType.FromUsdtFuturesToSpot);`
=> works (but only transfers the non-fractional amount so $5 )

am i doing something wrong here?

**Comment by JKorf** [comment]
Hi, this should be fixed in 6.1.0
