### ISSUE TITLE
List of Tickers

### ISSUE THREAD

**Issue by blancacacatua** [JKorf/Binance.Net#465]
Hello.  Is there a method to obtain a list of all the pars available in Binance?.  Also is there a list of methods available in the API?.  Sorry,  i'm new to visual studio.

**Comment by Amannda123** [comment]
Yes there is :) 

`var exchangeInfo = client.FuturesUsdt.System.GetExchangeInfo();`
`List<BinanceFuturesSymbol> listOfAllSymbols = new List<BinanceFuturesSymbol>(exchangeInfo.Data.Symbols.ToList());`

**Comment by blancacacatua** [comment]
Hi Amannda123.  thanks for your answer.  It worked.  but i have another problem.  I got the list of symbols and when i tried to get the list of open orders on a symbol i get nothing on the variable i have assigned the result.  

i used this code :  

`Imports Binance.Net
Imports Binance.Net.Enums
Imports Binance.Net.Objects.Spot
Imports CryptoExchange.Net

public Class Ticker_Alarm
	Dim info_exchange As Object
	Dim binClient As New BinanceClient

	Private Sub Ticker_Alarm_Load(sender As Object, e As EventArgs) Handles MyBase.Load
		Dim bco As New BinanceClientOptions
		With bco
			.ApiCredentials = New Authentication.ApiCredentials(My.Resources.ApiKEY, My.Resources.APISecret)
			.AutoTimestamp = True
			.TradeRulesBehaviour = TradeRulesBehaviour.AutoComply
		End With
		BinanceClient.SetDefaultOptions(bco)
		info_exchange = binClient.Spot.System.GetExchangeInfo
       End Sub

       Private Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
		Dim ordenes As Object
		For Each item As ListViewItem In lvListaSeguimiento.Items
			ordenes = binClient.Spot.Order.GetOpenOrders(item.Text)
		Next
	End Sub
`
i added a watch  on the variable **ordenes** and the error is 

**"No credentials provided for private endpoint"**

i think that i can get the symbols because are on a  public endpoint but the orders are on a private one and i miss something on the client creation.

by the way sorry for my English. And also I forgot to mention  I use VB in VS19 community

can you please advise me on what I'm doing wrong.

**Comment by JKorf** [comment]
Hi, it seems that you're settings the default options for the client (using SetDefaultOptions) after you already created the client instance. Default options only get applied to clients created after setting them.

**Comment by blancacacatua** [comment]
thanks a lot.  you are right.  its already working.  i have another question. one of the features i want to implement is a watchlist like the one in tradingview where i update the prices every second.  but when i add more than 3 coins the app gets really slow.  i can even write in a textbox or move the app window.  i have a loop inside the tick function of a timer that cicles the simbols in the list and get the price of each one.  **Is this the correct way of implementing this?**


`Private Sub reloj_Tick(sender As Object, e As EventArgs) Handles reloj.Tick

        Dim indice As Integer

        If lvListaSeguimiento.Items.Count > 0 Then 

            Dim Precio_simbolo As String

            For indice = 0 To lvListaSeguimiento.Items.Count - 1

                Precio_simbolo = Cliente.Spot.Market.GetPrice(lvListaSeguimiento.Items(indice).Text).Data.Price.ToString

                lvListaSeguimiento.Items(indice).SubItems(1).Text = Formatear_precio(Precio_simbolo)

            Next

        End If

    End Sub`

![Untitled](https://user-images.githubusercontent.com/69939022/95369695-6017eb00-089d-11eb-8e0d-ded2c896cf43.jpg)

**Comment by JKorf** [comment]
The problem with your code is that your timer tick runs on your UI thread. That thread is responsible for keeping the user interface responsible. You're telling it to go fetch data from a remote server, which takes some time. During the time this fetching takes the UI won't be processing any input. 

Ideally what you want to do is have a separate thread which takes care of the data fetching, so the UI thread doesn't get blocked. Using C# you can start a new Task (which isn't quite the same as a Thread, but it does take the work away from the UI thread) with something like this:

````C#
Task.Run(() => {
  // Do the data fetching in here.
});
````

I'm sure you;ll be able to convert that to VB.Net.

**Comment by blancacacatua** [comment]
Thanks a lot JKorf. That was really fast.  I will check it out.
