### ISSUE TITLE
Timestamp in GetMyTrades() is not valid

### ISSUE THREAD

**Issue by Amannda123** [JKorf/Binance.Net#466]
Hi,

tried to get my FuturesUSDT trades there, Timestamp from the Data array is incorrect (always 01.01.0001 00:00:00)

just to let you know :)

![grafik](https://user-images.githubusercontent.com/61044409/95026013-874c9d80-068e-11eb-86c1-d785e5b5b328.png)

**Comment by JKorf** [comment]
Thanks, should be fixed in 6.1.0
