### ISSUE TITLE
Need help on closing positions.

### ISSUE THREAD

**Issue by Amannda123** [JKorf/Binance.Net#467]
Hi, 

what is the fastest way to close open positions? Either Market sell them one by one or something like the "close all positions" button on binance website. I thought i just get all open positions via GetPositionInformation() and there would be a function to close it.. but there isn't :/

Thanks in advance

**Comment by Amannda123** [comment]
Never mind... feel a bit stuipid there... 🤦‍♂️  i just cycle through every position and place market at the opposite direction 😄

**Comment by Adamszsz** [comment]
I just can't figure how can i close position?  For example i have open position and want to close it by market price.
How can i do it ? Help please

**Comment by Amannda123** [comment]
Just use `client.FuturesUsdt.Order.PlaceOrder(Symbol, OrderSide, OrderType.Market, Qty ... )`

**Comment by Adamszsz** [comment]
no no i don't want place market order . I want to modify open position on futures  like chage stop limi on opened position.

**Comment by Amannda123** [comment]
> ... For example i have open position and want to close it by market price.

well you literally asked how to close it by market... and my answer is 100% accurate on that one... if you want do like stop market you still use the PlaceOrder function just with another order type..
