### ISSUE TITLE
No TransactionTime on BookTickerUpdates

### ISSUE THREAD

**Issue by soulmars** [JKorf/Binance.Net#468]
Hello,

I'm subscribing with the method SubscribeToBookTickerUpdates, and I obtain the data:

> { "Event" : "", "EventTime" : ISODate("0001-01-01T00:00:00Z"), "TransactionTime" : null, "UpdateId" : NumberLong("6112596258"), "Symbol" : "BTCUSDT", "BestBidPrice" : "10616.41000000", "BestBidQuantity" : "0.29539600", "BestAskPrice" : "10616.42000000", "BestAskQuantity" : "5.68328600" }

But the field TransactionTime and EventTime stay null, even though in the documentation there is an EventTime & TransactionTime ?
https://binance-docs.github.io/apidocs/futures/en/#individual-symbol-book-ticker-streams

`
var client = new BinanceSocketClient();
client.Spot.SubscribeToBookTickerUpdates("BTCUSDT", data =>
            {
                Debug.WriteLine(data.ToJson());
            });`

**Comment by JKorf** [comment]
Hi, you're using the Spot API, but the link you mention is for the Futures API. These are similair but not the same. The Spot API doesn't return these times.
I'll update the models to reflect this.

**Comment by soulmars** [comment]
Ok my bad, thank you
