### ISSUE TITLE
Different value of GetPrice at version 6.xxx

### ISSUE THREAD

**Issue by jakubedr** [JKorf/Binance.Net#469]
When I called `client.GetPrice("BTCUSDT");` at version 5.xx, I got exactly the same value as shown on Binance webside.
But at newest version 6.1.0 when I call `client.FuturesUsdt.Market.GetPrice("BTCUSDT");` I receive very different price.

Any ideas?

Thanks 👍

**Comment by JKorf** [comment]
Hi, I can confirm the price seems to be off, however it's not because of the version. I've tested it with earlier versions as well, and that makes no difference. The data received from the Binance server seems off. Not sure what is causing it though.

**Comment by jakubedr** [comment]
Maybe I have found it:
`client.FuturesUsdt.Market.GetPrice("BTCUSDT");` shows [this future](https://www.binance.com/en/futures/BTCUSDT).

But `client.GetPrice("BTCUSDT");` from 5.xx was showing [this](https://www.binance.com/en/trade/BTC_USDT).

Now I use `client.Spot.Market.GetBookPrice("BTCUSDT")` ... `.Data.BestAskPrice` :-)

**Comment by JKorf** [comment]
`client.FuturesUsdt.Market.GetPrice("BTCUSDT");`
is the same as `client.GetPrice("BTCUSDT");` from 5.1.14 IF the client was a BinanceFuturesClient instance.

Using BinanceClient with `client.GetPrice("BTCUSDT")` in 5.1.14 is the same as `client.Spot.Market.GetPrice("BTCUSDT")` in 6.1.0.

Note the difference between asking the Futures API and the Spot API
