### ISSUE TITLE
Question: Is there a sandbox to test my application?

### ISSUE THREAD

**Issue by salocinx** [JKorf/Binance.Net#470]
Hi. I previously experimented with Coinbase Pro and there I had a sandbox URL to test my application (placing orders, getting server responses, etc.). Is there anything similar for the Binance API ?

**Comment by JKorf** [comment]
There is the `PlaceTestOrder` method on the Spot API. Next to that there is also a whole separate environment called the testnet. That's probably what you're looking for.

**Comment by salocinx** [comment]
Thanks a lot for the quick response! I will close this issue/question.
