### ISSUE TITLE
Could i change timezone in Binance API?

### ISSUE THREAD

**Issue by dante1989** [JKorf/Binance.Net#471]
How could i change time zone to get klines data in my time zone
In default, time zone in binance is UTC 
But now i want to change timezone to get klines data in my time zone. For example, UTC+7
Could i do that for binance API?

**Comment by JKorf** [comment]
There is no default way to do that. Generally you'd want to do the conversion from UTC to local time either in the user interface, or when sending the data to the user interface. 

Using C# you can use `ToLocalTime()` to go from UTC to the environment time.

**Comment by dante1989** [comment]
Dim m1d As WebCallResult(Of IEnumerable(Of IBinanceKline))
m1d = Await clientBinance.FuturesUsdt.Market.GetKlinesAsync(Symbol, KlineIntervalBinance.OneDay, fromtime, totime)

For example to UTC: m1d.Data(i).OpenTime is 07/24/2020 00:00:00 AM (UTC), m1d.Data(i).High is 10200

But now i want to change my time zone (UTC+7) before i get klines data. The result could be: m1d.Data(i).OpenTime is 07/24/2020 00:00:00 AM (UTC+7), m1d.Data(i).High is 10400

Do you understand what i mean? It's a bit difficult to explain

**Comment by JKorf** [comment]
Can't you just adjust the times you sent? Since 00:00:00 UTC +7 is the same as 00:07:00 local time, just make sure you sent it in you local time, something like `DateTime.UtcNow.ToLocalTime()` should work I think.

**Comment by dante1989** [comment]
I will try again at your suggestion and let you know the results

**Comment by dante1989** [comment]
This is the same questin like me: https://stackoverflow.com/questions/60655580/getting-binance-historical-data-for-specific-timezone

**Comment by Hulkstance** [comment]
When you are using `.ToLocalTime()`, you might be confused because for example I'm GMT+2 and the daily notifications were pushed up at 02:00 AM because it is 00:00 AM UTC.
