### ISSUE TITLE
Please remove IncomeType enum and makes string type for it

### ISSUE THREAD

**Issue by NektoDron** [JKorf/Binance.Net#473]
I can't reopen issue 338 but the problem remains the same.
The parameter is string now, but converter converts all not declared types to null, because:
            parameters.AddOptionalParameter("incomeType", incomeType != null ? JsonConvert.SerializeObject(incomeType, new IncomeTypeConverter(false)) : null);

It should be:
            parameters.AddOptionalParameter("incomeType", incomeType);

**Comment by JKorf** [comment]
Fixed in 6.3.0
