### ISSUE TITLE
Why does GetAllOrders() return no results when using with startTime and endTime ?

### ISSUE THREAD

**Issue by salocinx** [JKorf/Binance.Net#475]
Hi. I am trying to request my past orders with the following code:

```
int limit = 100;
string asset = "BTCUSDT";
DateTime startTime = DateTime.UtcNow.AddDays(-90);
DateTime endTime = DateTime.UtcNow;
var orders = client.Spot.Order.GetAllOrders(asset, startTime: startTime, endTime: endTime, limit: limit).Data;
foreach(BinanceOrder order in orders) {
    Console.WriteLine($"Spot order: {order.CreateTime} {order.Type} {order.Symbol} {order.Side} {order.Quantity} @ {order.Price} [{order.Status}]");
}	
```

But I don't get any results back, although I am sure there are orders for the this particular time frame (past 90 days). I can successfully request them by calling `client.Spot.Order.GetAllOrders(asset);`.

Some idea?

**Comment by JKorf** [comment]
You should check if the result of the call is successful. You're instantly calling .Data on the result, which may be null if the server returns an error. Do something like this and you should see an error message telling you that the start/end time need to be within 24h of eachother.

````C#
var orderResult = client.Spot.Order.GetAllOrders(asset, startTime: startTime, endTime: endTime, limit: limit);
if(orderResult.Success)
{
    foreach(BinanceOrder order in orders)
        Console.WriteLine($"Spot order: {order.CreateTime} {order.Type} {order.Symbol} {order.Side} {order.Quantity} @ {order.Price} [{order.Status}]");
}
else
{
    Console.WriteLine($"Request failed: {orderResult.Error}");
}


````
