### ISSUE TITLE
Deserialize JsonSerializationException

### ISSUE THREAD

**Issue by Onub3nse** [JKorf/Binance.Net#476]
Hi there, im trying to getting exchangeinfo, and is returning following error:

Error | [1] Deserialize JsonSerializationException: Error setting value to 'Status' on 'Binance.Net.Objects.Futures.MarketData.BinanceFuturesSymbol'

**Comment by JKorf** [comment]
I'm not having any issues calling it just now. Are you still getting errors?

**Comment by Onub3nse** [comment]
No, errors are gone, ill suppose its an issue with Binance itself, cuz it's not the first time i was getting this error over the days, but they suddenly disappear. Thanks for your fast response.

**Comment by JKorf** [comment]
It might be an unknown value for the Status field, which isn't mapped. Is it possible for you to check the log output for the full data returned from the server?
