### ISSUE TITLE
Enable margin for subaccount

### ISSUE THREAD

**Issue by mazyarzirak** [JKorf/Binance.Net#477]
Hi.
I'm trying to enable margin for subaccount but i got this error : signature for this request is not valid.
here is my code : 
   var client = new BinanceClient(new BinanceClientOptions
            {
                ApiCredentials = new ApiCredentials("key", "secret")
            });
            var result = await client.SubAccount.EnableMarginForSubAccountAsync("emailAddress");

**Comment by JKorf** [comment]
Hi, it seems to work for me. Can you paste some debug logging of the call? You can enable debug logging in the options as well, by setting LogVerbosity to Debug.
