### ISSUE TITLE
BinanceSocketClient unexpectively closes connection

### ISSUE THREAD

**Issue by elscript** [JKorf/Binance.Net#478]
Hi everybody!
I've yesterday noticed the strange behaviour of BinanceSocketClient. It occasionally closes connection as I could understand it. Use Subscribe methods for UsdtFeatures. Right after subscription everything is good, callbacks call. But after some time, maybe few minutes callbacks stops calling. What happens? Maybe there are some setting for prevention of this behaviour?

**Comment by elscript** [comment]
@JKorf

**Comment by Kudwig** [comment]
enable the debug log with logverbosity and paste it here

**Comment by JKorf** [comment]
The socket should automatically reconnect if connection is lost. What subscription are you using (what method) and can you provide some debug logging as Kudwig suggested?

**Comment by elscript** [comment]
2020.10.19 17:55:25:299 | Debug | Client configuration: LogVerbosity: Debug, Writers: 1, Credentials: Set, BaseAddress: https://api.binance.com/, Proxy: -, RateLimiters: 0, RateLimitBehaviour: Wait, RequestTimeout: 00:00:30
2020.10.19 17:55:25:441 | Debug | [1] Creating request for https://api.binance.com/api/v3/time
2020.10.19 17:55:25:470 | Debug | [1] Sending GET request to https://api.binance.com/api/v3/time
2020.10.19 17:55:26:342 | Debug | [1] Response received in 846ms: {"serverTime":1603119327283}
2020.10.19 17:55:26:634 | Debug | [2] Creating request for https://api.binance.com/api/v3/time
2020.10.19 17:55:26:634 | Debug | [2] Sending GET request to https://api.binance.com/api/v3/time
2020.10.19 17:55:26:914 | Debug | [2] Response received in 279ms: {"serverTime":1603119327871}
2020.10.19 17:55:26:915 | Info | Time offset set to 1236,6466ms
2020.10.19 17:55:26:917 | Debug | [3] Creating request for https://fapi.binance.com/fapi/v1/listenKey
2020.10.19 17:55:26:920 | Debug | [3] Sending POST request to https://fapi.binance.com/fapi/v1/listenKey with request body
2020.10.19 17:55:27:437 | Debug | [3] Response received in 517ms: {"listenKey":"somesecketkey"}

**Comment by elscript** [comment]
@JKorf My code:
`var client = new BinanceClient(new BinanceClientOptions
            {
                ApiCredentials = new ApiCredentials(accessKey, accessSecret),
                LogVerbosity = CryptoExchange.Net.Logging.LogVerbosity.Debug,
                LogWriters = new List<TextWriter> { Console.Out }
            });
            var startResult = client.FuturesUsdt.UserStream.StartUserStream();

            if (!startResult.Success)
                throw new Exception($"Failed to start user stream: {startResult.Error}");

            var socketClient = new BinanceSocketClient();

            socketClient.FuturesUsdt.SubscribeToUserDataUpdates(startResult.Data,
                marginUpdate => { 
                },
                accountUpdate => {
                    foreach (var position in accountUpdate.UpdateData.Positions)
                    {
                        WhatsupMessageSender.SendMessage($"Позиция изменилась для {position.Symbol} на {position.PositionAmount}");
                    }// Handle order update
                },
                orderUpdate => { 
                },
                listenKeyUpdate => {
                    
                });`

**Comment by elscript** [comment]
Here is some onListenKeyExpired event, maybe I need to handle expiration somehow on my side?

**Comment by Kudwig** [comment]
keepAliveResult = Client.Spot.UserStream.KeepAliveUserStream(_listenkey);
                       
                        if (!keepAliveResult.Success)
                        {
                            // Some error handling
}



//this needs to be be done i think once / hr...i do mine every 30 mins

**Comment by Kudwig** [comment]
[https://binance-docs.github.io/apidocs/testnet/en/#user-data-streams](url)

**Comment by elscript** [comment]
Thank you much! I will try

**Comment by elscript** [comment]
Everything is ok. I close the ticket
