### ISSUE TITLE
SubscribeToAllSymbolTicker long time tick make exception json convert error

### ISSUE THREAD

**Issue by BlackDangerousK** [JKorf/Binance.Net#48]
Json convert error with data:
{"e":"24hrTicker","E":1520341252749,"s":"AEBTC","p":"-0.00000540","P":"-2.671","w":"0.00019750","x":"0.00020220","c":"0.00019680","Q":"46.09000000","b":"0.00019490","B":"68.00000000","a":"0.00019650","A":"585.12000000","o":"0.00020220","h":"0.00020760","l":"0.00018600","v":"460572.91000000","q":"**90.964L**","f":"0.00000000","l":"0.00000000"},{"a":"NAV","f":"0.00000000","l":"0.00000000"},{"a":"VIBE","f":"0.00000000","l":"0.00000000"},{"a":"LUN","f":"0.00000000","l":"0.00000000"}

90.964**L** could not case to decimal TotalTradedQuoteAssetVolume

**Comment by JKorf** [comment]
I've done some researching, and apparently the L suffix is for a long double in C++. I find it weird that Binance would push a value like this since it isn't a universal thing, especially since there is no reason for it to be a long. Have you seen it more often or was this a single occurrence? I have the stream running now, but don't have any problem deserializing.

**Comment by BlackDangerousK** [comment]
i get data from SubscribeToAllSymbolTicker  about 20min then L appear

using (var clientSocket = new BinanceSocketClient())
            {
                var successDepth = clientSocket.SubscribeToAllSymbolTicker((data) =>
                {
                    binance.AddDataAllTick(data, path);
                });
                successDepth.Data.Closed += delegate
                {
                    Console.WriteLine("Socket closed");
                };
                successDepth.Data.Error += delegate(Exception exception)
                {
                    Console.WriteLine("Socket exception");
                };
            }

**Comment by JKorf** [comment]
I haven't seen it locally, I've run it for some time. Anyway, it's an issue on Binance side. The L suffix isn't part of the JSON protocol, so it's their responsibility to not send data like that. I've added error checking in the library in the latest version (3.0.5) to prevent exceptions to be thrown when deserialization fails, it will now log the error and ignore the message. Hope that helps you!
