### ISSUE TITLE
Void CryptoExchange.Net.Objects.RestClientOptions.set_HttpClient(System.Net.Http.HttpClient)

### ISSUE THREAD

**Issue by captholley** [JKorf/Binance.Net#480]
I am receiving the following error when I try and initialize the BinanceClient Object: 

Method not found: 'Void CryptoExchange.Net.Objects.RestClientOptions.set_HttpClient(System.Net.Http.HttpClient)'.

See below for my implementation. What am I doing wrong here? This worked with previous versions of the Binance.Net Client

`
        private BinanceClient _apiClient;
        public void InitializeBinanceSavingsAccount()
        {
BinanceClient.SetDefaultOptions(new BinanceClientOptions()
            {
                ApiCredentials = new ApiCredentials(Config.Get(currentAccount + "-api-key"), Config.Get(currentAccount + "-api-secret"))
            });

            BinanceSocketClient.SetDefaultOptions(new BinanceSocketClientOptions()
            {
                ApiCredentials = new ApiCredentials(Config.Get(currentAccount + "-api-key"), Config.Get(currentAccount + "-api-secret")),
            });
            _apiClient = new BinanceClient();
}`

It is failing out at the constructor in BinanceClientOptions.cs here:

`public BinanceClientOptions(string spotBaseAddress, string futuresUsdtBaseAddress, string futuresCoinBaseAddress, HttpClient? client) : base(spotBaseAddress)
        {
            HttpClient = client;
            BaseAddressCoinFutures = futuresCoinBaseAddress;
            BaseAddressUsdtFutures = futuresUsdtBaseAddress;
        }`

**Comment by captholley** [comment]
I have removed the constructor in BinanceClientOptions.cs that takes in the HttpClient and was able to work around this issue.

**Comment by JKorf** [comment]
Seems like a missmatch in versions. What version of Binance.Net are you using and which one were you using previously? Also what versions of CryptoExchange.Net?
