### ISSUE TITLE
Placed Orders are expired

### ISSUE THREAD

**Issue by soulmars** [JKorf/Binance.Net#481]
Hello,

Everytime I place an order, it become directly expired, even thought I did sync the time on my machine. I can't find what is wrong.

Creation of the client:
`            var clientOptions = new BinanceClientOptions
            {
                ApiCredentials = new ApiCredentials(key, secret)
            };
            clientOptions.BaseAddress = "https://testnet.binance.vision";
            clientOptions.FuturesUsdtBaseAddress = "wss://testnet.binance.vision/ws";
            clientOptions.FuturesCoinBaseAddress = "wss://testnet.binance.vision/stream";
            return new BinanceClient(clientOptions);`

PlaceOrder
`            var ret = client.Spot.Order.PlaceOrder(arg.Symbol, (arg.Volume > 0 ? OrderSide.Sell : OrderSide.Buy)
                , (OrderType)Market
                , Math.Abs(arg.Volume));`

And on Market orders, ret.Data.Status is directly equal to Expired. Could you help me on that please ?

Thank you

**Comment by JKorf** [comment]
Hm that seems weird. Can you turn on debug logging in the settings by setting LogVerbosity to Debug in the options and share the request/response?

**Comment by soulmars** [comment]
Yes thank you, here is the log:
```2020/10/21 14:41:09:117 | Debug | Client configuration: LogVerbosity: Debug, Writers: 1, Credentials: Set, BaseAddress: https://testnet.binance.vision, Proxy: -, RateLimiters: 0, RateLimitBehaviour: Wait, RequestTimeout: 00:00:30
21/10/2020 12:41:09
2020/10/21 14:41:09:127 | Debug | [1] Creating request for https://testnet.binance.vision/api/v3/time
2020/10/21 14:41:09:129 | Debug | [1] Sending GET request to https://testnet.binance.vision/api/v3/time 
2020/10/21 14:41:09:892 | Debug | [1] Response received in 756ms: {"serverTime":1603284068730}
2020/10/21 14:41:09:911 | Debug | [2] Creating request for https://testnet.binance.vision/api/v3/time
2020/10/21 14:41:09:912 | Debug | [2] Sending GET request to https://testnet.binance.vision/api/v3/time 
2020/10/21 14:41:10:623 | Debug | [2] Response received in 711ms: {"serverTime":1603284069463}
2020/10/21 14:41:10:624 | Info | Time offset set to -448,151ms
2020/10/21 14:41:10:649 | Debug | [3] Creating request for https://testnet.binance.vision/api/v3/order
2020/10/21 14:41:10:652 | Debug | [3] Sending POST signed request to https://testnet.binance.vision/api/v3/order with request body quantity=2000&recvWindow=20000&side=SELL&signature=4708EB6E2E348B97A123192E7CA4D6FB16D2151DF15B266CE6A3C24B26CC94A2&symbol=TRXUSDT&timestamp=1603284070201&type=MARKET
2020/10/21 14:41:11:361 | Debug | [3] Response received in 707ms: {"symbol":"TRXUSDT","orderId":161,"orderListId":-1,"clientOrderId":"u6EfdLUH3aRXy8SX9KEa2x","transactTime":1603284070204,"price":"0.00000000","origQty":"2000.00000000","executedQty":"0.00000000","cummulativeQuoteQty":"0.00000000","status":"EXPIRED","timeInForce":"GTC","type":"MARKET","side":"SELL","fills":[]}
2020/10/21 14:41:11:363 | Warning | [3] Local object has property `origQuoteOrderQty` but was not found in received object of type `BinancePlacedOrder`
2020/10/21 14:41:11:369 | Debug | [3] Returned data: {
  "symbol": "TRXUSDT",
  "orderId": 161,
  "orderListId": -1,
  "clientOrderId": "u6EfdLUH3aRXy8SX9KEa2x",
  "transactTime": 1603284070204,
  "price": "0.00000000",
  "origQty": "2000.00000000",
  "executedQty": "0.00000000",
  "cummulativeQuoteQty": "0.00000000",
  "status": "EXPIRED",
  "timeInForce": "GTC",
  "type": "MARKET",
  "side": "SELL",
  "fills": []
}```

**Comment by JKorf** [comment]
To be honest I'm not sure why this would happen. Seems to me like it should work. Haven't found any info that this is expected behavior either. 

I'm not sure about the state of the testnet, can you verify there are enough orders in the order book for TRXUSDT to fill your order?
