### ISSUE TITLE
BinanceStreamKlineData missing Interval

### ISSUE THREAD

**Issue by Trebmint2** [JKorf/Binance.Net#482]
Hi, just got back to coding my app from over a year ago and trying to get it running with the new updates.

Spot.MarketStream.BinanceStreamKlineData which use to be BinanceStreamKlineData had an interval indicating the klineinterval
 xx.Data.Interval but this is no longer there?? Sorry for the question

**Comment by JKorf** [comment]
Hi, it seems like it was missing in the interface. Should be fixed in version 6.3.1 I just pushed.
