### ISSUE TITLE
Reintroduction of "Multithreading or Asyncing and HMACSHA256 (signature) #77"

### ISSUE THREAD

**Issue by MiniRoman** [JKorf/Binance.Net#483]
Hi,

In multi-threaded environment, HMACSHA256.ComputeHash() sometimes returns not proper values (like just null hash) due to lack of Thread Safety of the algorithm. This change was already fixed in PR https://github.com/JKorf/Binance.Net/pull/78, but this bug was later reintroduced in following commit: https://github.com/JKorf/Binance.Net/commit/b962fa10e5538c2bf8460ed43fb3e6ea37ed9b24#diff-9ace7a7bfc55d955f95df1ba54135ca81f6bc38a425847599af6d1ef88190a2d

It's hard to reproduce, but with 10 concurrent request initiation it can already happen.

Shall we just reintroduce changes from PR #78?

Best regards

**Comment by JKorf** [comment]
Hi,

Thanks for the heads-up, must've forgotten about it when doing some restructuring.

I've added it in again.
