### ISSUE TITLE
BinanceOrderBook

### ISSUE THREAD

**Issue by thraxxus** [JKorf/Binance.Net#484]
I just updated...

so much has changed...

My entire codebase is now broken.

Where did these go?
client.GetOrderBook(Symbol)
Get24HPrices(Symbol)
client.GetKlines(pair, KlineInterval.OneMinute);
client.GetOpenOrders();
client.GetUserCoins()

I cannot believe how much of my code just broke.

**Comment by JKorf** [comment]
The changes are mostly methods being moved to a slightly different place.

GetOrderBook, Get24HPrices, GetKlines are in client.Spot.Market.xxx

GetOpenOrders is in client.Spot.Orders.GetOpenOrders

GetUserCoins is in client.General.GetUserCoins

I understand it is a bit annoying to have to change most calls, but I had to make some separation in the clients to make the whole thing maintainable.
