### ISSUE TITLE
Question: getting the original JSON with a message

### ISSUE THREAD

**Issue by thomasd3** [JKorf/Binance.Net#486]
Is there a way, for debugging purpose, to get a copy of the original JSON with each message?

There is an issue I'd like to troubleshoot with Binance but it happens only in some specific situations and they request the JSON that originated from their server.

**Comment by JKorf** [comment]
There is no way to get this at the moment, but what you could do is put LogVerbosity to Debug in the options and add a log writer which writes to a file. That should log every call and the response to that file.

**Comment by thomasd3** [comment]
ok, I'll add a logger then. thanks!

**Comment by digital-swap** [comment]
Is there a chance to get the logwriter data into SQL actual?
