### ISSUE TITLE
Binanace Spot Multiple Orders

### ISSUE THREAD

**Issue by emin-karadag** [JKorf/Binance.Net#487]
Hello,
Multiple order submissions are available for Binance Futures at the same time. However, I couldn't see the same function for Binance Spot.
Does it not support Binance or is it not included in this repository?
Thanks.

**Comment by JKorf** [comment]
Binance only supports this on the Futures API.

**Comment by emin-karadag** [comment]
hımm okey. thanks.
So let me ask one more question.
When we send an order request to Binance spot via API, if the price is greater than the current price, the market order is executed. I don't want this to happen. Can I have orders over the current price rejected?

**Comment by JKorf** [comment]
I'm guessing you're looking for a Limit order, which will execute at a specific price. If you combine that with a TimeInForce of FillOrKill it gets cancelled if it can't be filled at the price you specified.
