### ISSUE TITLE
Condition for timestamp

### ISSUE THREAD

**Issue by thelesia** [JKorf/Binance.Net#488]
![Binance NetBinanceClient cs at master · JKorfBinance Net - Mozilla Firefox](https://user-images.githubusercontent.com/49877609/97990243-4e682b80-1de8-11eb-810c-a6edda7d681a.jpg)

Dear Jan,

Could you please explain this fragment of code.
If I got correctly, the timestamp is mandatory for order placement.

**Comment by JKorf** [comment]
It checks the result of the CheckAutoTimestamp call. AutoTimestamp is an option which automatically corrects the local computer time with the server time. 
The idea is that if the server is for example 20 seconds ahead of the local computer time, the timestamp parameter which is send with each authenticated request is upped with 20 seconds to match the server time.

To know the server time a request is made, which can fail if for example there is no internet connection. The if statement you highlighted checks if the result of correcting the local time with the server time has been successful. If not, it returns an error result.

**Comment by thelesia** [comment]
Dear Jan,

Thanks for answer.

Why  if (!timestampResult)?

**Comment by thelesia** [comment]
And AuthenticationProvider is internal.
How I should initilize it?
I will use code with copyrights

**Comment by JKorf** [comment]
Explanations and examples are available in the repository ReadMe and examples folder..
