### ISSUE TITLE
Cannot map enum. Type: Binance.Net.Enums.TimeInForce, Value: GTE_GTC

### ISSUE THREAD

**Issue by ng-designs** [JKorf/Binance.Net#495]
Cannot map enum. Type: Binance.Net.Enums.TimeInForce, Value: GTE_GTC
2020.11.10 01:15:25:348 | Error | Deserialize JsonSerializationException: Error setting value to 'TimeInForce' on 'Binance.Net.Objects.Futures.UserStream.BinanceFuturesStreamOrderUpdateData'.. 
Received data: 
{
  "e": "ORDER_TRADE_UPDATE",  "T": 1604952925625, "E": 1604952925629,
  "o": 
    {
    "s": "BTCUSDT", "c": "android", "S": "BUY", "o": "TAKE_PROFIT_MARKET", "f": "GTE_GTC", "q": "0", "p": "0", "ap": "0", "sp": "14250",
    "x": "CANCELED", "X": "CANCELED", "i": 8951362682, "l": "0", "z": "0", "L": "0", "T": 1604952925625, "t": 0, "b": "0", "a": "0",
    "m": false, "R": true, "wt": "MARK_PRICE", "ot": "TAKE_PROFIT_MARKET", "ps": "SHORT", "cp": true, "rp": "0", "si": 0, "ss": 0
    }
}

2020.11.10 01:15:25:376 | Warning | Couldn't deserialize data received from order stream: 5: Error deserializing data Deserialize JsonSerializationException: Error setting value to 'TimeInForce' on 'Binance.Net.Objects.Futures.UserStream.BinanceFuturesStreamOrderUpdateData'.. 
Received data:
{
  "e": "ORDER_TRADE_UPDATE", "T": 1604952925625, "E": 1604952925629, 
  "o": 
        {
           "s": "BTCUSDT", "c": "android_", "S": "BUY", "o": "TAKE_PROFIT_MARKET", "f": "GTE_GTC", "q": "0", "p": "0", "ap": "0",
           "sp": "14250", "x": "CANCELED", "X": "CANCELED", "i": 8951362682, "l": "0", "z": "0", "L": "0", "T": 1604952925625, "t": 0,
           "b": "0", "a": "0", "m": false, "R": true, "wt": "MARK_PRICE", "ot": "TAKE_PROFIT_MARKET", "ps": "SHORT", "cp": true,
          "rp": "0", "si": 0, "ss": 0
        }
}

**Comment by JKorf** [comment]
Hi, thanks for the report.
This should be fixed in version 6.3.4.
