### ISSUE TITLE
Cant set newOrderRespType on PlaceOrder function

### ISSUE THREAD

**Issue by Amannda123** [JKorf/Binance.Net#497]
Hi, 

according to https://binance-docs.github.io/apidocs/futures/en/#new-order-trade 
you can set the newOrderRespType to either "ACK" or "RESULT". I searched in your code and found it on like PlaceOrderInteral .. but however the parameter doesnt appear on the BinanceClient.FuturesUsdt.Order.PlaceOrder where i expected it to be. 

Any soloution for that?

Thanks in advance

**Comment by JKorf** [comment]
Hi, you're right. I've added the parameter in 6.3.4. Let me know if you have any other issues.

**Comment by Amannda123** [comment]
Hi, thanks for adding the parameter but it doesnt seem to have any effect. 
The OrderUpdate infomations i receive with "Result" are the same as with "Acknowledge".

So as example a marketorder results in 2 events:  
1) Marketorder New with only quantity
2) Market order filled with quantity and average price 

Somehow I expected only to receive one event with all the order informations, like only 2) from the example above. Or am i wrong here? What else would be the diffrence then?

**Comment by JKorf** [comment]
With events you mean on the socket client subscription? The parameter has nog effect on that. It only specifies how much information should be returned on the initial REST place order call.
