### ISSUE TITLE
FuturesUSDT GetExchangeInfo, error deserializing data.

### ISSUE THREAD

**Issue by Onub3nse** [JKorf/Binance.Net#498]
Hello, im getting this error, after going through the results, i've found one aset with has a "PENDING_TRADING" status, not sure if this causes the error.

Deserialize JsonSerializationException: Error setting value to 'Status' on 'Binance.Net.Objects.Futures.MarketData.BinanceFuturesSymbol'

all the other asets have "TRADING" status.

Cannot map enum. Type: Binance.Net.Enums.SymbolStatus, Value: PENDING_TRADING

**Comment by JKorf** [comment]
Thanks for the info, the PENDING_TRADING status isn't mentioned in the docs. I've added it in the mapping in v6.3.5, so next time the status is brought up it should work.

**Comment by Onub3nse** [comment]
Thanks for fast response...
