### ISSUE TITLE
FuturesUsdt.GetBrackets another error

### ISSUE THREAD

**Issue by Onub3nse** [JKorf/Binance.Net#499]
Im getting, sometimes, this error, today and a few days ago.

Error | [12] Deserialize JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Binance.Net.Objects.Futures.MarketData.BinanceFuturesSymbolBracket' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array

**Comment by JKorf** [comment]
Hm is it possible for you to have a look in the logging to see what the data returned is when this is error is thrown?

**Comment by Onub3nse** [comment]
Returned data was:

  {
    "symbol": "BTCUSDT",
    "brackets": [
      {
        "bracket": 1,
        "initialLeverage": 125,
        "notionalCap": 50000,
        "notionalFloor": 0,
        "maintMarginRatio": 0.004,
        "cum": 0
      },
      {
        "bracket": 2,
        "initialLeverage": 100,
        "notionalCap": 250000,
        "notionalFloor": 50000,
        "maintMarginRatio": 0.005,
        "cum": 50
      },
      {
        "bracket": 3,
        "initialLeverage": 50,
        "notionalCap": 1000000,
        "notionalFloor": 250000,
        "maintMarginRatio": 0.01,
        "cum": 1300
      },
      {
        "bracket": 4,
        "initialLeverage": 20,
        "notionalCap": 5000000,
        "notionalFloor": 1000000,
        "maintMarginRatio": 0.025,
        "cum": 16300
      },
      {
        "bracket": 5,
        "initialLeverage": 10,
        "notionalCap": 20000000,
        "notionalFloor": 5000000,
        "maintMarginRatio": 0.05,
        "cum": 141300
      },
      {
        "bracket": 6,
        "initialLeverage": 5,
        "notionalCap": 50000000,
        "notionalFloor": 20000000,
        "maintMarginRatio": 0.1,
        "cum": 1141300
      },
      {
        "bracket": 7,
        "initialLeverage": 4,
        "notionalCap": 100000000,
        "notionalFloor": 50000000,
        "maintMarginRatio": 0.125,
        "cum": 2391300
      },
      {
        "bracket": 8,
        "initialLeverage": 3,
        "notionalCap": 200000000,
        "notionalFloor": 100000000,
        "maintMarginRatio": 0.15,
        "cum": 4891300
      },
      {
        "bracket": 9,
        "initialLeverage": 2,
        "notionalCap": 9223372036854775807,
        "notionalFloor": 200000000,
        "maintMarginRatio": 0.25,
        "cum": 24891300
      }
    ]
  }
]

**Comment by JKorf** [comment]
Hi, I think this should be fixed in the latest version. Let me know if you have any issues.
