### ISSUE TITLE
Winform does not fire action from websocket

### ISSUE THREAD

**Issue by OhmPopy** [JKorf/Binance.Net#50]
Version 3.0.7
I try with console app it run, but try with GUI action not callback. Tests with 2012 and 2017 all have the same results

var socketClient = new BinanceSocketClient(socketClientOptions);
// Streams
var successDepth = socketClient.SubscribeToDepthStream("bnbbtc", (data) =>
**{
// handle data
});**

**Comment by JKorf** [comment]
Hi, this should be fixed in the latest version (3.0.8)
