### ISSUE TITLE
FuturesUsdt.Order.PlaceOrder TakeProfitLimit working?

### ISSUE THREAD

**Issue by McoreD** [JKorf/Binance.Net#503]
Thanks again for this wrapper - the best Binance Wrapper I have come across!

I have got the following code, but I was hoping you could kindly guide me through how to set TakeProfit in the same order placement. Is that possible? 

Basically, in my code below I have got everything I need except for a takeProfitPrice optional parameter. 

```
        public override bool PlaceBuyOrder(TradingData trade, bool closePosition)
        {
            using (var client = new BinanceClient())
            {
                var buyOrder = client.FuturesUsdt.Order.PlaceOrder(
                   trade.CoinPair.ToString(),
                   OrderSide.Buy,
                   OrderType.Limit,
                   quantity: Math.Round(trade.CoinQuantityToTrade, 3),
                   reduceOnly: closePosition,
                   price: Math.Round(trade.Price, 2),
                   timeInForce: TimeInForce.GoodTillCancel);

                if (buyOrder.Success)
                    trade.BuyOrderID = buyOrder.Data.OrderId;
                else
                    Console.WriteLine(buyOrder.Error.Message.ToString());

                return buyOrder.Success;
            }
        }
```

Thanks in advance!

**Comment by McoreD** [comment]
![](https://mike.getsharex.com/2020/11/20201124_7ylntCnxoV.png)

For clarity, something like this below would be ideal:

```
                var buyOrder = client.FuturesUsdt.Order.PlaceOrder(
                   trade.CoinPair.ToString(),
                   OrderSide.Buy,
                   OrderType.Limit,
                   quantity: Math.Round(trade.CoinQuantityToTrade, 3),
                   reduceOnly: closePosition,
                   price: Math.Round(trade.Price, 2),
                   takeProfitPrice: Math.Round(trade.Price, 2) + 100m,
                   timeInForce: TimeInForce.GoodTillCancel);

```

**Comment by JKorf** [comment]
Hi, to do this the order type should be set to TakeProfit, and you can use the stopPrice parameter to specify the trigger price.
Have a look at https://binance-docs.github.io/apidocs/futures/en/#new-order-trade, the different order types and parameters are explained there.

**Comment by McoreD** [comment]
Thanks @JKorf  for the response.

Do you think I have got it right with your advice below?

```
                var buyOrder = client.FuturesUsdt.Order.PlaceOrder(
                   trade.CoinPair.ToString(),
                   OrderSide.Buy,
                   OrderType.TakeProfitLimit,
                   quantity: Math.Round(trade.CoinQuantityToTrade, 3),
                   price: Math.Round(trade.Price, 2),
                   stopPrice: takeProfitPrice,
                   timeInForce: TimeInForce.GoodTillCancel);
```
Typical values would be:

                   quantity: 4.0
                   price: 18300
                   stopPrice: 18900

**Comment by JKorf** [comment]
Seems fine to me, try it and see if it does what you expect it to ;)

**Comment by McoreD** [comment]
Hi @JKorf ,

Strangely, I did not get the desired outcome. 
I got the following error:
`Invalid order type
`
Instead I used the following function twice (one to open, and one to close using the reduceOnly):
This is not ideal but works.

```
                var sellOrder = client.FuturesUsdt.Order.PlaceOrder(
                   trade.CoinPair.ToString(),
                   OrderSide.Sell,
                   OrderType.Limit,
                   quantity: Math.Round(trade.CoinQuantityToTrade, 3),
                   reduceOnly: closePosition,
                   price: Math.Round(trade.Price, 2),
                   timeInForce: TimeInForce.GoodTillCancel);
```
Wonder why simply changing 
                   OrderType.Limit to OrderType.TakeProfitLimit
and using
stopPrice
broke it?

**Comment by McoreD** [comment]
Hey Jan, would you be keen to the idea of having a community supported Telegram group?
Probably a Discord Server would be more suited to support so the products you have been making!
What do you think?

**Comment by wasimjee** [comment]
How can we send Both Take profit and Stoploss for a limit order

**Comment by McoreD** [comment]
@wasimjee I am afraid that is possible without introducing a new variable because we are currently using the stopPrice for taking profit - which did not work for me as my previous comment, but that's besides the point.

**Comment by wasimjee** [comment]
How can we implement this, any solutions

**Comment by sirrobinii** [comment]
@wasimjee  I came across the same issue, there's no stop order that works like a take profit or stoploss. 
If you check the trigger conditions in the API, it's not supported. You place either a Take profit or a stop loss. 
![image](https://user-images.githubusercontent.com/7092679/104713477-38e67a80-5724-11eb-9d03-641f3f39bb05.png)

**Comment by romanrakus** [comment]
Hi guys,

Any update on placing StopLossLimit and TakeProfitLimit orders? 

I experiencing `Invalid order type` on this as well.

**Comment by Adamszsz** [comment]
Hi ,
@JKorf  still we don't have any solution to create to TakeProfit in the same order placement ? It's May 2021 and still we don't have solution for this ;(

**Comment by JKorf** [comment]
If it's not supported/allowed by the Binance API there's not much I can do about it
