### ISSUE TITLE
Error converting EventTime property in BinanceStreamFuturesBookPrice class

### ISSUE THREAD

**Issue by Sergey-A-Dvortsov** [JKorf/Binance.Net#504]
The converter of EventTime property receives value of field "e", not field "E", which results in an invalid data format error.
 "stream": "btcusd_201225@bookTicker",
  "data": {
    "u": 9848122975,
    "e": "bookTicker",
    "s": "BTCUSD_201225",
    "ps": "BTCUSD",
    "b": "19308.4",
    "B": "350",
    "a": "19308.5",
    "A": "131",
    "T": 1606254344400,
    "E": 1606254344403
  }

**Comment by JKorf** [comment]
Hi, thanks for the report. This has been fixed in 6.4.0.
