### ISSUE TITLE
Market orders: Price 0

### ISSUE THREAD

**Issue by darderik** [JKorf/Binance.Net#507]
Hi! 
I'm just here to ask whether this behaviour is wanted or not.
Basically all market orders have a price set to 0.0.

Here's a picture

![](https://i.imgur.com/PIA326g.png)

P.S: not a big deal anyway, i can easily calculate the price using the working properties, just wanted to let you know

**Comment by Kudwig** [comment]
no its not...see that you are parsing the json correctly...you can verify your output with the debug, by logging the debug output

**Comment by darderik** [comment]
yep no errors at all, i fear this could be something that is related to the library itself. If i find anything i'll report back to you and eventually make a pr

**Comment by Kudwig** [comment]
i had a similar issue on my app a few weeks ago, only to discover i changed the naming strategy of the json parsing, so my fix was:
```
JsonConvert.DefaultSettings = () => new JsonSerializerSettings
            {
                Formatting = Formatting.Indented,
                ContractResolver = new DefaultContractResolver
                {
                    NamingStrategy = new CamelCaseNamingStrategy()
                }
            };
```

**Comment by darderik** [comment]
I can confirm it's working! Closing the issue.

**Comment by darderik** [comment]
Sorry about that, but unfortunately the 'market' orders prices are still showing 0.0 $. All others kinds of orders are showing price value correctly. Weird

![](https://i.imgur.com/Rqy4iTD.jpg)

**Comment by Kudwig** [comment]
looks like when its not an active order anymore, eg. "is working" = false, it shows a price....i might be wrong...seems like that one filled order was not completely filled...

**Comment by darderik** [comment]
Definitely makes sense, but the order result as completed on the binance app, it has been filled this morning. It seems 'market' orders are resulting always with 'isWorking' = true . I guess i'll calculate the price as the other properties are correctly set.

**Comment by Kudwig** [comment]
on another app i used : `myTrades = Client.Spot.Order.GetMyTrades(symbolpair)
_buySuccAmnt = myTrades.Data.Last().Price;
`
i used the last one in the array, but im sure you can get it by ordId

**Comment by Kudwig** [comment]
that worked with market orders

**Comment by darderik** [comment]
Yeah indeed it's working! thank you so much, didn't really know the differences between the two functions

**Comment by JKorf** [comment]
Hi, I see this issue is already been resolved, but I just wanted to give you some context on this. The reason the price is 0 on order level is because for market orders the price isn't necessarily a single value. Market orders can fill at multiple price points, in which case a single price field doesn't make sense. 

As suggested by @Kudwig you can get the individual trades of the market order using the `GetMyTrades` function to retrieve price information for the order.
