### ISSUE TITLE
Inconsistent order ID types (long VS int)

### ISSUE THREAD

**Issue by spcfran** [JKorf/Binance.Net#51]
Some methods expect `orderId`s to be `long` and some `int`. As per Binance API specs it should be `long`

**Comment by JKorf** [comment]
Hi, this is fixed in the latest version (3.0.8).

**Comment by Deni35** [comment]
Anybody here? Maybe I need to open new issue?

**Comment by JKorf** [comment]
Should probably be a long aswel. Open a new issue please, I'll fix it somewhere in the coming days
