### ISSUE TITLE
Isolated Margin

### ISSUE THREAD

**Issue by DontKnowGuy** [JKorf/Binance.Net#510]
Hey,

is there a way to recieve all open isolated margin orders without a symbol?

can only see this;

`client.Margin.Order.GetAllMarginAccountOrders("BTCUSDT", isIsolated: true);`

And another question:
why i dont see with this my isolated margin acc infos? just see normal margin infos but no infos about isolated margin money/and so on, because i have some money on isolated margin wallet, but its totally empty with getmarginaccountinfo :/

`client.Margin.GetMarginAccountInfo();`

**Comment by JKorf** [comment]
Hi, you can only request closed orders by symbol, no solution for that.
Regarding the isolated margin account info you should use `client.Margin.GetIsolatedMarginAccountAsync()`.
