### ISSUE TITLE
SubscribeToUserDataUpdates - Is it possible get continuous data?

### ISSUE THREAD

**Issue by myhorses2you** [JKorf/Binance.Net#512]
Hi, 

I am using websockets to retrieve active trade information such as PNL, size, current price and etc. However, websocket does not get triggered until there was any change in the trade such as stop is triggered or order is cancelled. 

What I want to do is to get information continuously from my active trades. How can I achieve this?

Thanks for creating this awesome API! 

Cheers.

**Comment by Amannda123** [comment]
You can trigger manually via API Calls, but be aware of the max rating from binance 

https://www.binance.com/en/support/articles/360004492232-API-Frequently-Asked-Questions-FAQ-

```Hard-Limits:

1,200 request weight per minute (keep in mind that this is not necessarily the same as 1,200 requests)
100 orders per 10 seconds
200,000 orders per 24 hours```

**Comment by JKorf** [comment]
As @Amannda123 pointed out, you can poll the API for this. No way to get this continuously from the websocket as far as I'm aware.

**Comment by myhorses2you** [comment]
Thanks for the reply. Case is closed then.
