### ISSUE TITLE
Cannon get TradeFees from testate

### ISSUE THREAD

**Issue by strakamichal** [JKorf/Binance.Net#514]
**Describe the bug**
Cannot get trade fees via client.Spot.Market.GetTradeFeeAsync(). It's returning 404. I'm using a testnet.

**To Reproduce**
Call client.Spot.Market.GetTradeFeeAsync()

**Expected behavior**
The list of fees should be returned, but I'm getting Success = false and error 404.

**Debug logging**
2020.12.08 21:07:20:488 | Debug | [4] Creating request for https://testnet.binance.vision/wapi/v3/tradeFee.html
2020.12.08 21:07:20:557 | Debug | [4] Sending GET signed request to https://testnet.binance.vision/wapi/v3/tradeFee.html?timestamp=1607458041886&symbol=BTCUSDT&recvWindow=5000&signature=88B2AC10EC511A59570944669279A406FA1C8CDE4C9BF999427A315CA46E1EF8
2020.12.08 21:07:21:736 | Debug | [4] Error received: 
2020.12.08 21:07:21:746 | Error | Empty data object received

**Comment by JKorf** [comment]
This endpoint works for the normal spot API, but not for the test net. Probably because the call returns the withdraw fees for all symbols, and withdrawing from the test net is not possible.

**Comment by ruzbeh8** [comment]
Hi can you help me to how connect testnet binance.can you show me the codes?
