### ISSUE TITLE
BinanceSocketClient.FuturesCoin.SubscribeToBookTickerUpdatesAsync()  does not work

### ISSUE THREAD

**Issue by Sergey-A-Dvortsov** [JKorf/Binance.Net#516]
Does not return values in the callback.  Below is an example of a method call. Spot works fine.

var subscription = BoardType == BoardTypes.Spot ? await Socket.Spot.SubscribeToBookTickerUpdatesAsync(pair.Symbol, OnBestQuoteUpdate)  : await Socket.FuturesCoin.SubscribeToBookTickerUpdatesAsync(pair.Symbol, OnFutureBestQuoteUpdate);

**Comment by JKorf** [comment]
Hi, this is probably because your symbol name isn't correct. The Binance socket doesn't return an error when the symbol is incorrect, but just doesn't give updates. Try this:
````C#
var x = await _client.FuturesCoin.System.GetExchangeInfoAsync();
await _socketClient.FuturesCoin.SubscribeToBookTickerUpdatesAsync(x.Data.Symbols.First().Name, OnFutureBestQuoteUpdate);
````
