### ISSUE TITLE
GetSubAccountTransferHistoryForSubAccountAsync HttpMethod should be Get

### ISSUE THREAD

**Issue by Marius2020** [JKorf/Binance.Net#518]
I tried to use GetSubAccountTransferHistoryForSubAccountAsync and got the error "Request method 'POST' not supported".

In the file "BinanceClientSubAccounts.cs ", on line 917, you used the method Post instead of Get, is probably the source of the problem.

**Comment by JKorf** [comment]
Thanks for the report, this is fixed in the latest version.

**Comment by Marius2020** [comment]
Working now, thank you!
