### ISSUE TITLE
TransferSubAccountToSubAccountAsync not working

### ISSUE THREAD

**Issue by Marius2020** [JKorf/Binance.Net#519]
Hello,

I am not able to make a transfer from a sub account to another sub account within the same master using "TransferSubAccountToSubAccountAsync".

The autorisation is activated for the API of this sub account in the master account and I am also able to transfer to the master using "TransferSubAccountToMasterAsync", but not to another sub account. I always get the error "-1022: Signature for this request is not valid.".

No idea what I am doing wrong, can anyone help?

**Comment by Grepsy** [comment]
Are you trying to do directly futures to futures? That's not supported.

**Comment by Marius2020** [comment]
Is not futures, I am trying spot to spot. As I said it is working from this sub account to the master, but not to another sub.

**Comment by JKorf** [comment]
Hi, I've fixed a parameter which was wrongly named. Can you try again?

**Comment by Marius2020** [comment]
Hi, not working. I still have the same error.

**Comment by JKorf** [comment]
Can you share the debug logging of the request? Turn on debug logging with LogVerbosity = LogVerbosity.Debug in the client options.

**Comment by Marius2020** [comment]
Hi, here the debug data:

![LogFile_Binance](https://user-images.githubusercontent.com/59507476/102881192-c6e48380-444c-11eb-932f-a24cbb9b33ef.jpg)

Do you or anyone has an idea why the requests are sent twice? I am just doing it once actually and it happens like that for some calls.

Thank you very much for your support and great work

**Comment by Marius2020** [comment]
Hi JKorf,

in the last screenshot I didn't take the error too, here a new one with this error

![Screenshot 2021-01-04 161616](https://user-images.githubusercontent.com/59507476/103550020-923ee600-4ea8-11eb-8f95-a7287037b39a.jpg)

**Comment by JKorf** [comment]
Should be fixed #674
