### ISSUE TITLE
Futures SL/TP?

### ISSUE THREAD

**Issue by chababuu** [JKorf/Binance.Net#521]
Hello,

Is there a way we can Edit a Order to set a New SL or TP in the Futures Market?

thx

**Comment by JKorf** [comment]
Not that I'm aware of. You can have a look at https://binance-docs.github.io/apidocs/futures/en/ to see all available API functionality.

**Comment by thomasd3** [comment]
People are regularly asking on the Telegram chat about this and it is not implemented in the API yet.
