### ISSUE TITLE
how to use testnet?

### ISSUE THREAD

**Issue by ruzbeh8** [JKorf/Binance.Net#522]
hi all.any body know how i can connect to testnet?
i have api and secret key but not connected.
can any one share the code of this?

**Comment by JKorf** [comment]
I haven't used the testnet personally, but I know there are people who use this library with the testnet. As far as I know you just need to change the base address of the client to point to the testnet api, something like this:
````C#
var client = new BinanceClient(new BinanceClientOptions{
    BaseAddress = "Testnet address here"
});
````
