### ISSUE TITLE
Subscription spitting hundreds repetetive price.

### ISSUE THREAD

**Issue by MachineTrader** [JKorf/Binance.Net#523]
Hi, I'm new to Websockets so forgive me if this question is uneducated. 

I'm wondering why the socket ticker/data subscription function spits out hundreds of  repetitive prices when there has been no change in bid/ask price or new last price?

Isn't that putting load on our machine or on the server for Binance, or is it a problem with this library?
Thanks in advance any one giving an answer to this question.

**Comment by MachineTrader** [comment]
Ok, to answer my own question. Maybe people are that frenetic at changing the quantity even when the price doesn't change.. I get it..

**Comment by JKorf** [comment]
The websocket sends an update when anything changes in the data it sends. So as you mentioned, if you subscribe to an order book and anyone changes any quantity of an order they have open anywhere in the book the websocket will send a new update. There shouldn't be any updates with exactly the same data. 

I can imagine the web page buffers the updates and only refreshes every xx milliseconds, but I'm not sure about that.
