### ISSUE TITLE
RealizedPNL from PositionUpdate not accurate

### ISSUE THREAD

**Issue by Amannda123** [JKorf/Binance.Net#524]
Hi, 

looks like there is some kind of conversion error.

In comparison: The data im get via the wrapper vs. the binance trading history 
https://i.imgur.com/YMeqxsa.png

PS: Im trading with leverage 15, if thats any usefull

**Comment by JKorf** [comment]
Please have a look in the logging with LogVerbosity.Debug to see what data is returned.
