### ISSUE TITLE
New Order 

### ISSUE THREAD

**Issue by ManuelJH76** [JKorf/Binance.Net#526]
Hello
I followed the code from the example:
var result = client.Spot.Order.PlaceOrder(SelectedSymbol.Symbol, OrderSide.Buy, OrderType.Limit, SelectedSymbol.TradeAmount, price: SelectedSymbol.TradePrice, timeInForce: TimeInForce.GoodTillCancel);

No matter what change I make, there are a number of error messages. I can't quite understand this, I'm trying to execute various short with the order, for example: SelectedSymbol.TradeAmount = 0.00200000M.

For courses, for example. Price: 0.00000023 I get the error Price * QTY is zero or less.
For courses, for example. Price: 0.00002468 comes the message LOT_SIZE.

If I trigger the order directly via Binance, it will be placed.

Thank you for your support.

**Comment by eros1453** [comment]
Hi 
It's better to use Quantity and Price Precision on every order. Like:

decimal trade_amount = Math.Round(TradeAmount / TradePrice, QUANTITYPRECISION);

**Comment by ManuelJH76** [comment]
Hi. Thx
I had a wrong relationship.  I thought that I have to state the price from BTC to ETH for example.  But in the last few days I only understood that I have to specify the amount how much I want to buy at, for example, ETH.  It's more elegant that way, of course.
