### ISSUE TITLE
Websocket - SubscribeToOrderBookUpdates returning "IBinanceOrderBook" instead "BinanceEventOrderBook"

### ISSUE THREAD

**Issue by Gustavobbr** [JKorf/Binance.Net#527]
Hi There,
I was trying to manage Orderbook locally, and when subscribing to OrderBookUpdates I was only able to use elements from IBinanceOrderBook, that missed Event Type, and FirstUpdateID.
In order to get it I've hard converted the variable to BinanceEventOrderBook before throwing it to the method..
![image](https://user-images.githubusercontent.com/37227910/103152521-94e26280-4767-11eb-894a-da09a8354e33.png)

**Comment by JKorf** [comment]
This should be fixed. Let me me know if you're having any other issues.
