### ISSUE TITLE
Futures : How to open a position with 75% of my balance ?

### ISSUE THREAD

**Issue by ShayanFiroozi** [JKorf/Binance.Net#528]
How to open a position with 75% of my balance ? 
Why the Binance Long and Short amount of a same price are different ?

![Futures](https://user-images.githubusercontent.com/43654826/103422048-bf437e00-4bb4-11eb-961d-f0cbeed8838e.jpg)

How to properly calculate these numbers with my balance and the current price of a symbol to properly pass the Binance price filters ?

Thanks in advance.

**Comment by eros1453** [comment]
Get balance from balance api.
Then use it like asset.balance*trade_percent.
I prefer to use percent on trades.

**Comment by eros1453** [comment]
My code is like

TradeAmount = tradeable_balance * (Convert.ToDecimal(Properties.Settings.Default.TRADEPERCENT) / 100);
            decimal trade_amount = Math.Round(TradeAmount * Leverage / bestBid, QUANTITYPRECISION);

Where "TRADEPERCENT" is my desired % of my tardeable balance witch i get from;

using (var futures_client = new BinanceClient())
                {
                    var bf = futures_client.FuturesUsdt.Account.GetBalance();
                    if (bf.Success && bf.Data != null)
                    {
                        var futuresBalanceArray = bf.Data.ToArray();
                        tradeable_balance = Math.Round(futuresBalanceArray.FirstOrDefault(a => a.Asset == USDT").MaxWithdrawAvailable, 8);
                    }
                };.

**Comment by ShayanFiroozi** [comment]
> My code is like
> 
> TradeAmount = tradeable_balance * (Convert.ToDecimal(Properties.Settings.Default.TRADEPERCENT) / 100);
> decimal trade_amount = Math.Round(TradeAmount * Leverage / bestBid, QUANTITYPRECISION);
> 
> Where "TRADEPERCENT" is my desired % of my tardeable balance witch i get from;
> 
> using (var futures_client = new BinanceClient())
> {
> var bf = futures_client.FuturesUsdt.Account.GetBalance();
> if (bf.Success && bf.Data != null)
> {
> var futuresBalanceArray = bf.Data.ToArray();
> tradeable_balance = Math.Round(futuresBalanceArray.FirstOrDefault(a => a.Asset == USDT").MaxWithdrawAvailable, 8);
> }
> };.

Thank you very much , 
Is this code pass the Binance price filters ? 
Also i've found the Buy and Sell price in the Binance feutures are different , how to calculate them ?

**Comment by eros1453** [comment]
Hi
Thats not the complete code. It passes.
I'm getting the orderbook for the asset and take the ask or bid price on trade time.

**Comment by ShayanFiroozi** [comment]
Thank you.
