### ISSUE TITLE
FuturesUsdt.UserStream.StartUserStream(); connection dies. Keep Alive broken, does not work, in Spot.UserStream.StartUserStream(); it does

### ISSUE THREAD

**Issue by vburwitz3** [JKorf/Binance.Net#529]
**Describe the bug**
When opening a connection with BinanceClient.FuturesUsdt.UserStream.StartUserStream(); then the FuturesUsdt connection dies after some time.
When opening with BinanceClient.Spot.UserStream.StartUserStream(); then there is a automatic Keep Alive with the ListenKey that keeps the connection to Binance for the web socket open until the connection or application is closed.
This automatic keep alive functionality for Spot is a great feature and sadly it is somehow broken for FuturesUsdt.

**To Reproduce**
BinanceClient.FuturesUsdt.UserStream.StartUserStream(); is being called.

**Expected behavior**
The connection should be keept alive with an automatic ping to Binance using the listen key for that connection like in the Spot functionality.

**Debug logging**
Connection simply dies without error but on any update on Binance - like cancelling a order there - the application does not get any update of it anymore through Binance.Net.
Also when the application sends an order there is no more update through SubscribeToUserDataUpdates(onOrderUpdate event).
It works at the beginning but not after some hours anymore.
With the Spot implementation there is no problem even if it runs for days or weeks.

**Comment by JKorf** [comment]
To be clear what the issue is:
1. You call the KeepAliveUserStream method but the connection dies anyway.
2. You don't call the KeepAliveUserStream at all, but the connection stays alive on spot but dies on futures.

If number 2; there is no automatic keep alive implemented for spot, and as per Binance documentation the KeepAlive method should be called every +- 30 minutes.

**Comment by vburwitz3** [comment]
In my Spot implementation I call "var binanceListenKey=binanceClient.Spot.UserStream.StartUserStream();"
and the connection stays alive also over weeks. Great compared to the old API I used before, fantastic feature in Binance.Net.

In my FutureUsdt implementation I call "var binanceListenKey=binanceClient.FuturesUsdt.UserStream.StartUserStream();"
and the connection dies randomly after minutes or maybe just after many hours and does get no callback if there is a OrderStatus change like execution, cancellation or so. I can still send order cancellations or new orders but do not get any callback anymore where the same implementation for Spot does.

**Comment by vburwitz3** [comment]
I added code to use BinanceClient.FuturesUsdt.UserStream.KeepAliveUserStream(listenKey); the websocket. Thats works fine and in case the ListenKey dies (like an hour of interupted Network connection) I redo the SubscribeToUserDataUpdates().
Now it works for FuturesUsdt like Spot but Spot does it out of the box and that is way nicer as a coder using the API. I checked that and the Spot API does all that out of the box, which is really nice and keeps the programs code much nicer.

**Comment by sleepymatto** [comment]
@vburwitz3 how do you detect when the listenkey dies / when you need to reestablish the connection?

**Comment by vburwitz3** [comment]
On:
var result	=binanceClient.FuturesUsdt.UserStream.KeepAliveUserStream(listenKey);
if (result.Success==false) {
 // listenKey is dead (if its not a network error which would throw an exception, therefore you would not be here)
}

**Comment by JKorf** [comment]
It is recommended by Binance to just call the KeepAliveUserStream every 30 minutes to extend the lifetime.

**Comment by vburwitz3** [comment]
Thats what I need to do for Futures. As said on Spot its already works out of the box which is a great functionality. It would be great if that would also be added to the Futures.
Otherwise every coder needs to do this for each application using websockets which is really a big overhead that could be totally avoidable like with Spot and that would make the Futures part of the API really fantastic too!

**Comment by vburwitz3** [comment]
Thats what I need to do for Futures. As said on Spot its already works out of the box which is a great functionality. It would be great if that would also be added to the Futures.
Otherwise every coder needs to do this for each application using websockets which is really a big overhead that could be totally avoidable like with Spot and that would make the Futures part of the API really fantastic too!
