### ISSUE TITLE
Subscribing to klines

### ISSUE THREAD

**Issue by wallace1981** [JKorf/Binance.Net#53]
It looks like after one of the releases subscription to streams are going longer? Or previously when you put to log something like"03:39:04:262 | Info | Started kline stream for wavesbnb: OneMinute" wasn't really a truth. Currently what im seeing is subscribing to all symbols klines took 5-6 minutes. Previously I saw (according to the log) it was much much faster, Please advise.

**Comment by JKorf** [comment]
Hi, I think you previously used a version where the code continued without waiting for the socket to actually connect. It now waits till it is connected which might take a little longer. You might want to connect multiple sockets in parallel if you're not already.
