### ISSUE TITLE
Issue with FuturesUsdt.System.GetExchangeInfo

### ISSUE THREAD

**Issue by scipius** [JKorf/Binance.Net#530]
I'm trying to get symbols for the USDT Futures market with FuturesUsdt.System.GetExchangeInfo

I'm receiving errors all of a sudden : 

{: Deserialize JsonSerializationException: Error setting value to 'ContractType' on 'Binance.Net.Objects.Futures.MarketData.BinanceFuturesUsdtSymbol'. 00","baseAsset":"BTC","quoteAsset":"BUSD","marginAsset":"BUSD","pricePrecision":2,"quantityPrecision":3,"baseAssetPrecision":8,"quotePrecision":8,"underlyingType":"COIN","underlyingSubType":[],"settlePlan":0,"triggerProtect":"0.1500","filters":[{"minPrice":"0.01","maxPrice":"100000","filterType":"PRICE_FILTER","tickSize":"0.01"},{"stepSize":"0.001","filterType":"LOT_SIZE","maxQty":"1000","minQty":"0.001"},{"stepSize":"0.001","filterType":"MARKET_LOT_SIZE","maxQty":"500","minQty":"0.001"},{"limit":200,"filterType":"MAX_NUM_ORDERS"},{"limit":100,"filterType":"MAX_NUM_ALGO_ORDERS"},{"multiplierDown":"0.8500","multiplierUp":"1.1500","multiplierDecimal":"4","filterType":"PERCENT_PRICE"}],"orderTypes":["LIMIT","MARKET","STOP","STOP_MARKET","TAKE_PROFIT","TAKE_PROFIT_MARKET","TRAILING_STOP_MARKET"],"timeInForce":["GTC","IOC","FOK","GTX"]}]}}

Has something changed on Binance API side ?

**Comment by JKorf** [comment]
Seems they introduced some (undocumented) contract type values. I've pushed version 6.6.0, which should fix this issue.

**Comment by deepthoughtlaplateforme** [comment]
Hi it is missing 
new KeyValuePair<ContractType, string>(ContractType.NextMonth, "NEXT_MONTH"),
Thanks

**Comment by JKorf** [comment]
Should be fixed in version 6.6.0

**Comment by yalcingoben** [comment]
Hi, 

I updated last nuget package(6.6.0) on my app but it has still some error. 

![image](https://user-images.githubusercontent.com/7137668/103640057-67b06400-4f60-11eb-842a-cde5cf46b30f.png) 
![image](https://user-images.githubusercontent.com/7137668/103640199-a0e8d400-4f60-11eb-95d2-fdfbd57e2afd.png)

Thanks for your help.

**Comment by nikkozp** [comment]
fixed #532

**Comment by JKorf** [comment]
6.6.1 is online, let me know if there are still issues.

**Comment by scipius** [comment]
Awesome, thanks for the quick update! I'm trying it now.
