### ISSUE TITLE
UserDataUpdates

### ISSUE THREAD

**Issue by karloballa** [JKorf/Binance.Net#535]
Hi,

it seems that OnAccountInfoMessage (socketClient.Spot.SubscribeToUserDataUpdates) doesn't fire anymore.
Is it intentional, or is it something else?

Thanks.

**Comment by nikkozp** [comment]
Hi, read this pls

https://www.binance.com/en/support/articles/8154893b1be34870aee9253828642290

**Comment by JKorf** [comment]
Per 01/01/2021 the accountInfo event has been removed by Binance. Have a look at the link @nikkozp posted.

**Comment by karloballa** [comment]
Thanks! :)
