### ISSUE TITLE
Address verification failed

### ISSUE THREAD

**Issue by 5appz** [JKorf/Binance.Net#537]
**Describe the bug**
Address verification failed when I try to withdraw balance USDT

**To Reproduce**
var a = public_variable.general_client.WithdrawDeposit.Withdraw("USDT", "address here",16, null,null, null, null, null, default);

**Expected behavior**
Should withdraw amount to the desired address

**Debug logging**
Address verification failed

**Comment by JKorf** [comment]
You can check the logging of what is send to the server by enabling Debug logging in the client options:
````C#
var client = new BinanceClient(new BinanceClientOptions()
{
  LogVerbosity = LogVerbosity.Debug
});
````

Can you check if the data is send correctly to the server?

**Comment by 5appz** [comment]
https://api.binance.com/wapi/v3/withdraw.html?asset=USDT&address=THEADDRESSOFRECEIVER&amount=16&timestamp=1610362499712&recvWindow=5000&signature=THESIGNATUREGENERATED

![Screenshot_1](https://user-images.githubusercontent.com/72450361/104172404-7e453800-5404-11eb-8291-55158c0f9952.png)

**Comment by 5appz** [comment]
Manually I can withdraw USDT to the desired address, but when I try to withdraw with your api, it gives this error, I don't know if there is a procedure to verify address? In fact I need to know which address to verify, mine or the receiver?

**Comment by Amannda123** [comment]
Sounds like you forgot to enable withdraw on your api key :)

**Comment by 5appz** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/72450361/104306519-502c2a80-54ce-11eb-9bf3-0365c4b50d6a.png)
 
It is enabled, and again is not allowing me to withdraw. Can you please check? It is giving me the same error!

**Comment by 5appz** [comment]
Can you simulate a withdraw from a c# so I can see where is the mistake!

**Comment by 5appz** [comment]
> Sounds like you forgot to enable withdraw on your api key :)
> Also you must apply the IP Access Restriction filter in order to enable withdrawals.

It is all enabled, I can make conversion and other, it is very strange why I cant withdraw funds from my account using this API, it is asking to verify address, but which address to verify?!

**Comment by 5appz** [comment]
After a lot of testing, the problem was, you cant withdraw to TRC20 address with this API, I tried with another address, and it worked. So, let's solve the problem, so we can make withdrawals with TRC20.

**Comment by JKorf** [comment]
Hi, so looking through the API documentation, I think you'll need to provide the network parameter when withdrawing, which should be set to TRX to withdraw to a TRC20 address.

**Comment by 5appz** [comment]
Solved the solution. Thank you for the help.

**Comment by CafeCode-cs** [comment]
> Hi, so looking through the API documentation, I think you'll need to provide the network parameter when withdrawing, which should be set to TRX to withdraw to a TRC20 address.

Hello, I want to use the Withdraw method for internal transfer in Binance with the following inputs
coin : “USDT”
address : “5396*****” (BinanceId)
amount : 2
But I encountered such an error
Address verification failed. Please confirm the network is matched with the withdrawal address. You may consult with recipient’s platform for details.
Did I make a mistake? Thank you for helping me
