### ISSUE TITLE
An error occurred while sending the request.

### ISSUE THREAD

**Issue by nikkozp** [JKorf/Binance.Net#538]
In recent versions, I very often started getting the message "**An error occurred while sending the request.**" on Spot and Futures. Most likely, this is partly due to the exchange's lags. But there is an error with the request itself, since I don't get the error code. @JKorf  what could this be related to?

**Comment by nikkozp** [comment]
Previously, this error sent code 3, now null. Why did you remove it? Is there any way to get it back?

**Comment by JKorf** [comment]
The error code 3 was just some made up number which didn't point to anything. I changed it so the error code property always reflects the error code that was returned from the server. Previously it was either the error code from the server, or some error code which was created internally in the library. 

To detect when something went wrong with sending the request you can check if the error returned was a WebError. So something like this:
````C#
if (!call.Success)
{
    if (call.Error is WebError)
    {
        // Error sending the request
    }
    else
    {
        // Some other error
    }
}
````

**Comment by JKorf** [comment]
By the way, I've also adjusted the exception reporting, so the error should contain some more information on what went wrong.

**Comment by nikkozp** [comment]
I understood. Thanks a lot
