### ISSUE TITLE
Limit for Order Book

### ISSUE THREAD

**Issue by Fuze5k** [JKorf/Binance.Net#539]
**discrepancy**
![image](https://user-images.githubusercontent.com/51718249/103882039-ec77bb00-50e3-11eb-90a3-767c6bba3f71.png)
![image](https://user-images.githubusercontent.com/51718249/103882215-247efe00-50e4-11eb-8c7f-0d1b34697b0c.png)

**Comment by JKorf** [comment]
Hi, the endpoint you reference is of the REST API request, which only retrieves the initial order book. Updates to the order book are received via the websocket using this method which only accepts 5, 10 or 20:
![image](https://user-images.githubusercontent.com/8448172/104162277-9745ed00-53f4-11eb-8e36-2dd93063ab41.png)

If you're just looking to get the order book snapshot you should use `client.Spot.Market.GetOrderBook("symbol", 100);`

**Comment by Fuze5k** [comment]
thank you
