### ISSUE TITLE
code -1021 Timestamp for this request...

### ISSUE THREAD

**Issue by Swisization** [JKorf/Binance.Net#54]
![image](https://user-images.githubusercontent.com/36995625/37401123-25340336-2798-11e8-8976-742dcf7da4ab.png)
After a while, I get this error permanently. Earlier there was "AutoTimestamp", which alternative is now

**Comment by JKorf** [comment]
AutoTimestamp still exists, just have to set it in the defaults before creating the client using
````C#
BinanceClient.SetDefaultOptions(new BinanceClientOptions(){
    AutoTimestamp = true
});
````
or pass it in the constructor:
````C#
var client = new BinanceClient(new BinanceClientOptions(){
    AutoTimestamp = true
});
````
