### ISSUE TITLE
Local Endpoint Configuration

### ISSUE THREAD

**Issue by eyonys** [JKorf/Binance.Net#541]
I want to know how can I set a fixed port for local endpoint when I create a BinanceSocketClient for subscribing to account updates. The thing is that I want to deploy a Console Application on Linux, but everytime I run it on my server, firewall blocks it. I want to setup a fixed port to configure my firewall to allow it.

**Comment by JKorf** [comment]
If it is possible it will need to be configured on the HttpClient. The client can then be passed to the BinanceClient.
If you are using dotnet 5.0, you can try playing around with this:
````C#
var handler = new HttpClientHandler();
var field = typeof(HttpClientHandler).GetField("_underlyingHandler", BindingFlags.Instance | BindingFlags.NonPublic);
var socketsHandler = (SocketsHttpHandler) field?.GetValue(handler);
socketsHandler.ConnectCallback = async (context, token) =>
{
    var s = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);
    s.Bind(new IPEndPoint(ipAddress, **PORT**));
    await s.ConnectAsync(context.DnsEndPoint, token);
    s.NoDelay = true;
    return new NetworkStream(s, ownsSocket: true);
};

var httpClient = new HttpClient(handler);
var client = new BinanceClient(new BinanceClientOptions(){
  HttpClient = httpClient
});
````

Snippet is taking from https://github.com/bonesoul/dotnet_5_httpclient_rest_bind
