### ISSUE TITLE
Newbie confusion on markets availability

### ISSUE THREAD

**Issue by GiganteX** [JKorf/Binance.Net#548]
I looked into the markets BNBUSDC and USDCBNB. I assumed they are just reversed ie selling on one is the same as buying on the other.

When trying to buy/sell on BNBUSDC it works fine, but on USDCBNB I get "Market is closed". Using PlaceTestOrder().

Why?

Status for both is "Trading" and IsSpotTradingAllowed is true...

**Comment by JKorf** [comment]
To be honest, I don't know why both markets are returned, when only 1 is functional. Currently the USDCBNB market returns status Break, but I'm not sure why it even exists.
If you're really curious you can ask Binance.

**Comment by GiganteX** [comment]
You're right, now it doesn't return Trading any more but Break instead. Hmm. Curious. A Binance bug I suppose. 
It's just that if I can't trust Binance to return correct data it can potentially be very costly.... I might check with them, yes. Thanks!
