### ISSUE TITLE
Spot.SubscribeToPartialOrderBookUpdatesAsync missing FirstUpdateID

### ISSUE THREAD

**Issue by beany** [JKorf/Binance.Net#549]
The IBinanceOrderBook interface seems to be missing the FirstUpdateId.

FirstUpdateId is available in the Binance.Net.Objects.Spot.MarketData.BinanceOrderBook class which implements IBinanceOrderBook.

**Comment by beany** [comment]
Oeps, duplicate with issues #527

**Comment by beany** [comment]
Sorry, no... its not the same. This is about partial updates on the orderbook. BinanceOrderBook has FirstUpdateId but it never seems to be filled.

**Comment by JKorf** [comment]
I've moved the FirstUpdateId. It's not returned on the partial updates stream, which is why it was never filled.
