### ISSUE TITLE
Auto Comply

### ISSUE THREAD

**Issue by Cjay93** [JKorf/Binance.Net#55]
in previous versions, AutoComply will take a number such as 0 and auto comply it to min trade.
Or lets say 123.0434034034034304 a number like that and autocomply it.
instead I get the invalid quantity, legal range is 1^([0-91(1,20))(W[0-9)(1,20))?$1.") 
seems like auto comply scince changing the way you set binance rules isnt the working.
Thanks,

**Comment by JKorf** [comment]
Hi, I haven't changed anything in that part, so not sure what's going wrong. Can you enable Debug log verbosity and paste the debug logging that is produced here?

**Comment by JKorf** [comment]
Do you still get this error?
