### ISSUE TITLE
Invalid Symbol

### ISSUE THREAD

**Issue by gvardal** [JKorf/Binance.Net#553]
Hi, i am a new user of binance nuget,
and i have a problem with klines,

i used this lines get klines of ETHTRY
var klines = client.FuturesCoin.Market.GetKlines("ETHTRY", KlineInterval.ThirtyMinutes, limit: 21);
but i recevied this kind of error code
{-1121: Invalid symbol. }

how can i solve this
thx

**Comment by nikkozp** [comment]
U need use SPOT not FuturesCoin

**Comment by JKorf** [comment]
As @nikkozp suggested, it seems like you're trying to get Spot klines, so instead of using `client.FuturesCoin.Market.GetKlines("ETHTRY", KlineInterval.ThirtyMinutes, limit: 21);` you should use `client.Spot.Market.GetKlines("ETHTRY", KlineInterval.ThirtyMinutes, limit: 21);`
