### ISSUE TITLE
Change a Path

### ISSUE THREAD

**Issue by bousalem** [JKorf/Binance.Net#554]
Hello Everyone;

Can i change a path in Binance.net /api/v3/ to /fapi/v1 to use https://testnet.binancefuture.com/?

Thank you

**Comment by deadheadblues** [comment]
Yes, check out the issue I raised [here](https://github.com/JKorf/Binance.Net/issues/545) which shows how you can set the default options of BinanceClients to use the futures testnet api.

**Comment by bousalem** [comment]
Thank you
