### ISSUE TITLE
Example about futures?

### ISSUE THREAD

**Issue by iegestesi** [JKorf/Binance.Net#555]
Is there any example to use the futures side? I just couldn't decode the code. So can you give an example or help?

**Comment by deadheadblues** [comment]
Check out the issue I raised [here](https://github.com/JKorf/Binance.Net/issues/545) that contains an example for raising a futures order and subscribing to trade updates. You have to create an account on the Binance futures testnet site and use the api key and api secret to create an ApiCrendentials object that you use as shown in the example.

Note you won't receive coin-m futures order updates, which is why I raised the issue.

**Comment by iegestesi** [comment]
I created an account from test address but cannot create api. How do I do that. Also, are futures data, not spot market data, required for transactions?
I leave an example below but it gives a symbol error.
var klines = client.FuturesUsdt.Market.GetKlines ("ETHUSD", Binance.Net.Enums.KlineInterval.OneMinute, limit: 500);

**Comment by deadheadblues** [comment]
You don't need to create the api key or api secret as it gets created when you create the account. Go to the futures testnet site, sign in, and click on "API Key" as shown in the below pic. You can then copy/paste the api key and api secret into your code.
![image](https://user-images.githubusercontent.com/28539723/105387101-38962580-5be3-11eb-8f19-b9d5634c725d.png)



Data is not required to send orders.

Also, the symbols of all usdt futures end in "USDT" so if you want to trade the ETH future, the symbol is ETHUSDT.

**Comment by iegestesi** [comment]
Ok i got this part. So why can't I see this data in the API that I normally add? In other words, the necessary permissions are given in my API information, but it cannot extract data. Also worked in test net. How do I pull data in real network? After all, I will not always work in a test environment.

**Comment by deadheadblues** [comment]
To change the environment, you have to supply the URLs that you want to use when creating the BinanceClient and BinanceSocketClient. Check out the issue I mentioned you should check out in my first comment reply to you and you'll see how I use the SetDefaultOptions() function to supply the BaseAddress, BaseAddressUsdtFutures, and BaseAddressCoinFutures URLs for the api I want to use. I can't help you with the actual URLs as I don't have access to the normal binance.com api.
