### ISSUE TITLE
Future All Coin List?

### ISSUE THREAD

**Issue by iegestesi** [JKorf/Binance.Net#558]
How can we get the list of all coins traded in futures?

**Comment by JKorf** [comment]
You can use `client.FuturesUsdt.System.GetExchangeInfo`. It contains a list of all tradable symbols.

**Comment by jeb1384** [comment]
How loaded this data on datagridview.

Thank You

**Comment by jeb1384** [comment]
> You can use `client.FuturesUsdt.System.GetExchangeInfo`. It contains a list of all tradable symbols.

How loaded this data on datagridview.

Thank You
