### ISSUE TITLE
No Updates received for SubscribeToUserDataUpdates.

### ISSUE THREAD

**Issue by armanhamzehlou** [JKorf/Binance.Net#560]
I have been trying to receive account balance updates in C# .NET and so far my following attempt has failed. There are no issues with "SubscribeToAllBookTickerUpdates" and I receive updates on it, but for "SubscribeToUserDataUpdates", It is silent and doesn't give any updates.  I followed the documentation and still no luck.

I am including all my code for this function below, please let me know if you need any further details:

`var client = new BinanceClient(new BinanceClientOptions
            {
                ApiCredentials = new ApiCredentials(apiKey, secretKey)
            });

            var results = client.Spot.UserStream.StartUserStream();

            // General | General/account endpoints

            var socketClient = new BinanceSocketClient();

            // Spot | Spot market and user subscription method

            socketClient.Spot.SubscribeToUserDataUpdates(results.Data, data =>
                {
                    this.Invoke((MethodInvoker) delegate()
                    {
                        MessageBox.Show("Hello World!");
                    });
                }, null
                , null, null, data =>
                {
                    this.Invoke((MethodInvoker) delegate()
                    {
                        MessageBox.Show("Hello World!");
                    });
                });`

**Comment by bydevelopertr** [comment]
+1

**Comment by JKorf** [comment]
Updates are only given if there is a change in the balance.. Also you should check the success result of retrieving the listen key and the subscribing

**Comment by Hulkstance** [comment]
First of all, you might have a request timeout settings into your BinanceSocketClient, just like I did some time ago. An example of how it should be:

```csharp
_socketClient = new BinanceSocketClient(new BinanceSocketClientOptions()
{
	ApiCredentials = new ApiCredentials(exchangeOptions.ApiKey, exchangeOptions.SecretKey),
	AutoReconnect = true,
	ReconnectInterval = TimeSpan.FromSeconds(15),
#if DEBUG
	LogVerbosity = LogVerbosity.Debug
#endif
});
```

You should also do something like the following to keep the listen key up below the SubscribeToUserDataUpdates call.

```csharp
var keepAliveSubscription = Observable.Timer(TimeSpan.FromSeconds(1), TimeSpan.FromMinutes(29))
	.SelectMany(_ => Observable.FromAsync(async () =>
	{
		await KeepAliveListenKeyAsync().ConfigureAwait(false);
	}))
	.Subscribe();
```

**Comment by JKorf** [comment]
@armanhamzehlou Is this still relevant?
