### ISSUE TITLE
BinanceClient.FuturesCoin.Account.GetAccountInfoAsync() method return 0 for PositionAmount.

### ISSUE THREAD

**Issue by Sergey-A-Dvortsov** [JKorf/Binance.Net#565]
BinanceClient.FuturesCoin.Account.GetAccountInfoAsync() method always return 0 for BinanceFutureAccountPosition.PositionAmount property. As a result, it is impossible to find out the position size at the start of the program.

**Comment by JKorf** [comment]
Hi, the position amount is not returned in that call, it is however in GetPositionInformationAsync so I suggest you use that. I've updated the models to represent this.
