### ISSUE TITLE
Which in WS corresponds to a subscription to <listenKey>@position?

### ISSUE THREAD

**Issue by Sergey-A-Dvortsov** [JKorf/Binance.Net#567]
Which in WS corresponds to a subscription to <listenKey>@position? How to get the liquidation price of a position in WS?

**Comment by JKorf** [comment]
I think you refer to this? https://binance-docs.github.io/apidocs/delivery/en/#request-user-39-s-position which is a request on the websocket, not an actual subscription. The websocket request is not implemented, but the same information can be retrieved with the rest client with this call:
`client.FuturesCoin.GetPositionInformation()`
