### ISSUE TITLE
FuturesUsdt [SubscribeToMarkPriceUpdates] deserialization problem

### ISSUE THREAD

**Issue by HGitTest** [JKorf/Binance.Net#568]
The property "P" is returned for the MarkPrice but "p" (lowercase) should be used.

See below to reproduce.

```c#
var socketOpts = new BinanceSocketClientOptions() {
      AutoReconnect = true,
    ApiCredentials = new ApiCredentials(_apiKey, _apiSecret),
    LogVerbosity = LogVerbosity.Debug, // Must be set to see the raw data received
    LogWriters = new List<TextWriter> { Console.Out }
};

var socketClient = new BinanceSocketClient(socketOpts);

await socketClient.FuturesUsdt.SubscribeToMarkPriceUpdatesAsync("BTCUSDT", 1000, msg => {
    Console.WriteLine($"[{msg.Symbol}] markPrice: {msg.MarkPrice}");
});
```

-- Output --

Debug | Socket 2 received data: {"stream":"btcusdt@markPrice","data":{"e":"markPriceUpdate","E":1611567129000,"s":"BTCUSDT","p":"33288.96000000","P":"33335.25847598","i":"33243.78686000","r":"0.00070480","T":1611590400000}}
[BTCUSDT] markPrice: 33335.25847598

-- Expected --
[BTCUSDT] markPrice: 33288.96

**Comment by JKorf** [comment]
Hi thanks for the heads up, this should be fixed in 6.7.0
