### ISSUE TITLE
Single tasks executed twice or multiple times

### ISSUE THREAD

**Issue by Marius2020** [JKorf/Binance.Net#569]
Hello,

I have sometimes the problem, that one task/action is triggered twice or multiple times. For example one simple buy order which usually works fine will sometimes be executed twice or more even I just put only one order.

Anyone ever faced this problem or has an idea what the soltuion can be?

Best regards

**Comment by 5appz** [comment]
Hi, this is executed multiple times when you order currency. for example you want to buy 1 eth, but on the market is 0.3 with price 1243USD , 0.5 with price 1244USD and 0.2 with price 1245USD, so the execution to fill your request goes 3 times.

**Comment by Marius2020** [comment]
Hi,

thank you for your feedback, but is not the same. It wouldn't be a problem for me if I order 1 ETH and it makes multiple orders to bring me the 1 ETH. 

In my case, I order 1 ETH, but it orders 2 ETH or 3 ETH and so on.

**Comment by JKorf** [comment]
Hi, I haven't seen or heard of this behavior before. Can you validate if the request is send maybe multiple times?

**Comment by JKorf** [comment]
I'm assuming this isn't an error in the library
