### ISSUE TITLE
Request for new function UPDATE

### ISSUE THREAD

**Issue by 5appz** [JKorf/Binance.Net#570]
**Describe the bug**
transactionFeeFlag there is not implemented, but is very important
Can you also add network address detection?

**To Reproduce**
on the withdraw function, add option transactionFeeFlag that tells which one gets to pay the commission.

**Expected behavior**
update depositwithdraw method, adding transactionFeeFlag value

**Comment by 5appz** [comment]
.General.GetUserCoins(); can be achieved the second one using the coin regex function.
Binance solved it :)

**Comment by JKorf** [comment]
I've added the transactionFeeFlag.
