### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by allcasper99** [JKorf/Binance.Net#572]
Where can I find documentation related to this application. I will use it for the first time, so which method buy for futures, which methos sell, margin insertion, which one close the position? It wouldn't hurt to have documentation.

**Comment by JKorf** [comment]
The documentation is mostly in the code. Use intilisense in VisualStudio to find out which methods are available. You can check the Binance documentation to see what endpoints are available.

**Comment by allcasper99** [comment]
hello, I couldn't see the Perpetual Margin Mode and Adjust Leverage settings in the BinanceFuturesBatchOrder method. Can you help me with that?

**Comment by mchurlet** [comment]
Visual Studio F2 ((Object Explorer))
