### ISSUE TITLE
testnet.binancefuture.com connection issue

### ISSUE THREAD

**Issue by wil70** [JKorf/Binance.Net#576]
**Describe the bug**
Hello, I'm not able to get order working on testnet (https://testnet.binancefuture.com/en/delivery/BTCUSD_QUARTER?theme=dark)
I'm able to get the data feed (but from binance.com, not from the testnet), and I do not get the balance or the order.
So my guess is it is still going to binance.com instead of testnet.binancefuture.com

I also tried to add BaseAddress = "https://testnet.binancefuture.com", to the clientOptions but that didn't work
**To Reproduce**
CryptoExchange.Net.Authentication.ApiCredentials apiCredential = new CryptoExchange.Net.Authentication.ApiCredentials(
					"my key from https://testnet.binancefuture.com/en/delivery/BTCUSD_QUARTER?theme=dark", 
					"my secret key from https://testnet.binancefuture.com/en/delivery/BTCUSD_QUARTER?theme=dark"
					);//"BinanceKey", "BinanceSecret");

				// ref: https://github.com/JKorf/Binance.Net/issues/545
				var clientOptions = new BinanceClientOptions
				{
					BaseAddressUsdtFutures = "https://testnet.binancefuture.com",
					BaseAddressCoinFutures = "https://testnet.binancefuture.com"
				};
				clientOptions.ApiCredentials = apiCredential;

				var socketClientOptions = new BinanceSocketClientOptions
				{
					BaseAddress = "wss://stream.binancefuture.com",
					BaseAddressUsdtFutures = "wss://stream.binancefuture.com",
					BaseAddressCoinFutures = "wss://stream.binancefuture.com",
				};
				socketClientOptions.ApiCredentials = apiCredential;

				_socketExchange = new BinanceClient(clientOptions);
				_socketClient = new BinanceSocketClient(socketClientOptions);// new Binance.Net.Objects.Spot.BinanceSocketClientOptions();

				_isConnected = true;

				var symbols = await _socketExchange.GetSymbolsAsync();
				Console.WriteLine($"{((CryptoExchange.Net.RestClient)_socketExchange).ClientName}: {symbols.Data?.Count()} symbols returned, first = {symbols.Data?.First().CommonName}");

				var balances = await _socketExchange.GetBalancesAsync();
				var btcBalance = balances.Data?.Where(b => b.CommonAsset.ToUpperInvariant() == "BTC").FirstOrDefault();
				Console.WriteLine($"{((CryptoExchange.Net.RestClient)_socketExchange).ClientName}: {balances.Data?.Count()} balance returned, BTC balance = {btcBalance?.CommonTotal}");

				var symbolName = _socketExchange.GetSymbolName("BTC", "USDT");
				var klines = await _socketExchange.GetKlinesAsync(symbolName, TimeSpan.FromHours(1));
				Console.WriteLine($"{((CryptoExchange.Net.RestClient)_socketExchange).ClientName}: {klines.Data?.Count()} klines returned, first klines @ {klines.Data?.First().CommonClose}");

				var orderResult = await _socketExchange.PlaceOrderAsync(
	"BTCUSDT",
	CryptoExchange.Net.ExchangeInterfaces.IExchangeClient.OrderSide.Buy,
	CryptoExchange.Net.ExchangeInterfaces.IExchangeClient.OrderType.Market,
	(decimal).2,
	null,
	null
	);

**Expected behavior**
[2021.01.29 8:20:40] Binance: 1273 symbols returned, first = ETHBTC
[2021.01.29 8:20:42] Binance:  balance returned, BTC balance = 10000000
[2021.01.29 8:20:44] Binance: 500 klines returned, first klines @ 40075.82000000

**Debug logging**
The error is -2015 "Invalid API-key, IP, or permissions for action." Unauthorized
so it means something is not align between the calls I do and my keys

thanks!

**Comment by wil70** [comment]
For testnet, with perpertual future conract, It doesn't seem to be using the "fapi" and "v1"
The BinanceClientFutureUsdt is created within BinanceClient and it uses "api" and "v3"
Is there a way to make it work with testnet and perpetual future contrats?

**Comment by JKorf** [comment]
Hi, you seem to be using the IExchangeClient interface, which is currently only suited for Spot trading. If you want to use the futures (testnet) you can use the IBinanceClient interface instead.
````C#
 IExchangeClient _socketExchange; // <- only supports a selection of common functions
 IBinanceClient _socketExchange; // <- the full binance library
````
To place an order you can then use _ socketExchange.FuturesUsdt.Order.PlaceOrder() to place an order, and _socketExchange.FuturesUsdt.Market.xx to get market info.

**Comment by wil70** [comment]
Working - thank you!

I'm having difficulty login into the testnet website itself lately
https://testnet.binancefuture.com/en/futures/BCH_USDT
![image](https://user-images.githubusercontent.com/7807709/108002648-1c4c9500-6fa5-11eb-9726-24a50fcda55a.png)

**Comment by Mafyou** [comment]
It's half fixed now lol! You can login but when go to charte, it's seems gone.

**Comment by wil70** [comment]
;)
Do you experience this too?
How do we fix this? I entered a ticket at Binance but they do not seem super responsive.

**Comment by JKorf** [comment]
Binance Testnet availability is out of scope for this library
