### ISSUE TITLE
Order Type

### ISSUE THREAD

**Issue by NoNickCode** [JKorf/Binance.Net#578]
Thanks for this wrapper.
can you explain me the difference between this order types:
Stop
Stop Loss 
Stop Market

can i create a buy order with stop loss and take profity on the same order ? 
Thanks

**Comment by Hulkstance** [comment]
I think Stop, Stop Loss and Trailing Stop Loss orders are only available on Binance Futures. They are pretty much what their name says.

More information about the order types:
https://github.com/binance-us/binance-official-api-docs/blob/master/rest-api.md#enum-definitions
https://www.binance.com/en/support/articles/360033779452-Types-of-Order

### Stop Market
> Similarly to a stop-limit order, a stop-market order uses a stop price as a trigger. However, when the stop price is reached, it triggers a market order instead. 

### Limit vs Market

https://binance.zendesk.com/hc/en-us/articles/360007720071-Maker-vs-Taker

Limit orders are *makers*. Market orders are *takers*.

### Limit orders (Makers)

> These orders add volume to the order book, helping to "make the market," and are therefore termed the "maker" for any subsequent trades.

### Market orders (Takers)

> Trades from Market orders are always Takers, as Market orders can never go on the order book. These trades are "taking" volume off of the order book, and therefore called the "taker."

**Comment by NoNickCode** [comment]
Thanks
