### ISSUE TITLE
Receiving: "code":-2015,"msg":"Invalid API-key, IP, or permissions for action.

### ISSUE THREAD

**Issue by rvflyer01** [JKorf/Binance.Net#579]
Hi,
I'm a 1st time user of your api, it is very helpful, but, I configured an account & api keys with Binance.
Tested them through Postman, all good;
Used the same keys with your api and receive the above message.
Any help gratefully received.

**Comment by Hulkstance** [comment]
If you are on binance.us, you have to specify `BaseAddress = "https://api.binance.us"`.

**Comment by rvflyer01** [comment]
Hi, 
Many thanks, I tried that but alas it didn't work;
This is what I tried...
(from your examples)
            BinanceClient.SetDefaultOptions(new BinanceClientOptions()
            {
                ApiCredentials = new ApiCredentials("xxxxxxxxxxxxxxxxxxxxxxxxx", "yyyyyyyyyyyyyyyyyyyyyyyyyy"),
                BaseAddress = "https://api.binance.us",
                LogVerbosity = LogVerbosity.Debug,
                LogWriters = new List<TextWriter> { Console.Out }
            });

**Comment by Hulkstance** [comment]
In that case, you can go on Binance's API management page and whitelist your IP address.

**Comment by wil70** [comment]
I would like to try perpetual futures orders on testnet
I tried BaseAddress = "https://testnet.binancefuture.com",
but that doesn;t work, it seems to be using "api" "v3" instead of "fapi" "v1"
When I look at the code it seems only Spot has the implementation for PlaceOrderAsync, shall I re-use this one for perpetual futures or I need to code it?

**Comment by rvflyer01** [comment]
Hi, thanks again;
I have my IP address whitelisted but still getting same  message. I'm a bit puzzled!

**Comment by JKorf** [comment]
What call are you trying to do? Can you check the logging to see if everything is as expected?

**Comment by dante1989** [comment]
Try to delete API, and creat new API again. It will be fixed. Somtime, i have the same problem like you, this problem come from Binance

**Comment by wil70** [comment]
Hello, rght now I can not login into the testnet right now, I was able before
login: bill.rodin@gmail.com
ThanksWilhelm
    On Sunday, February 14, 2021, 03:19:16 PM PST, dante1989 <notifications@github.com> wrote:  
 
 


Try to delete API, and creat new API again. It will be fixed. Somtime, i have the same problem like you, this problem come from Binance
