### ISSUE TITLE
is BinanceFuturesStreamMarginUpdate in use?

### ISSUE THREAD

**Issue by thomasd3** [JKorf/Binance.Net#580]
When subscribing to .FuturesUsdt.SubscribeToUserDataUpdatesAsync, the first callback (BinanceFuturesStreamMarginUpdate) doesn't seem to ever be called.

Is it in use?

**Comment by nikkozp** [comment]
Hello. Based on the documentation, it is called:

- When the user's position risk ratio is too high, this stream will be pushed.
- This message is only used as risk guidance information and is not recommended for investment strategies.
- In the case of a highly volatile market, there may be the possibility that the user's position has been liquidated at the same time when this stream is pushed out.


But under debug I do not receive sockets. Apparently it is called extremely rarely
