### ISSUE TITLE
UserDataStream Deprecated 

### ISSUE THREAD

**Issue by maxhleonard-uchicago** [JKorf/Binance.Net#583]
The UserDataStream endpoint/uri is no longer consistent with the Binance documentation. It should be on "v3" but when "SubscribeToUserDataUpdates" is called is uses the "v1" endpoint.

**Comment by SpaceMonkeyForever** [comment]
Hey, why did you close this?
I created a PR fix here: https://github.com/JKorf/Binance.Net/pull/608/files

**Comment by SpaceMonkeyForever** [comment]
Actually, it should be "v1" according to the documentation

https://binance-docs.github.io/apidocs/spot/en/

Maybe that's why you closed this.  Ignore my previous comment, I was wrong.
