### ISSUE TITLE
lost liquidationPrice on new version 6.7.0

### ISSUE THREAD

**Issue by dante1989** [JKorf/Binance.Net#584]
Hello, after updating to new version 6.7.0 (Updated futures position info models)
i do not see liquidationPrice anymore 
I think you forget integrating liquidationPrice 
Check it again
Thank you so much

**Comment by JKorf** [comment]
Hi, thanks for the report, it should be fixed again in 6.8.0.

**Comment by dante1989** [comment]
Thank you
