### ISSUE TITLE
How to manage a local order book correctly ?

### ISSUE THREAD

**Issue by mGungorr** [JKorf/Binance.Net#586]
Hello, 

How to manage a local order book correctly  ?
I want to keep order book update of a coin always. But couldn't figure out how to do it. 

**- UPDATE -**

            socketClient.Spot.SubscribeToPartialOrderBookUpdates("BTCUSDT",20, 100, data => {
                var a = data.Asks.ToList();
                Console.WriteLine(a[0].Price);
            });
`socketClient.Spot.Market.GetOrderBook("symbol", 100);`

these helps me but when updating and deleting prices and quantities ?
Is there an example code ?

Any help appreciated.

**Comment by JKorf** [comment]
Hi, the `SubscribeToPartialOrderBookUpdates` pushes the complete book for the levels requested. So in the example above every update has the a full 20 level order book. 

If you want to maintain a bigger order book, you could use the BinanceSymbolOrderbook class, which does this for you. If you want to do it yourself you can have a look at the source for that class and the base class to see how it is implemented.

**Comment by mGungorr** [comment]
Thank you for great library, I will check BinanceSymbolOrderbook class
