### ISSUE TITLE
Error with GetOpenOrdersAsync(Symbol)

### ISSUE THREAD

**Issue by dante1989** [JKorf/Binance.Net#588]
When i use GetOpenOrdersAsync()
For example: 
_Dim BinanceOpenOrders As WebCallResult(Of IEnumerable(Of BinanceFuturesOrder))
BinanceOpenOrders = Await clientBinance.FuturesUsdt.Order.GetOpenOrdersAsync()_
I got BinanceOpenOrders1.Data.Count = 9. It is working

**### But I have 3 errors below:**

**1. When i use symbol, for example:**
_BinanceOpenOrders = Await clientBinance.FuturesUsdt.Order.GetOpenOrdersAsync("BTCUSDT",,,,)_
I got error like that: 2021/02/11 06:00:51:168 | Binance    | Debug | Client configuration: LogVerbosity: Debug, Writers: 1, Credentials: -, BaseAddress: https://api.binance.com/, Proxy: -, RateLimiters: 0, RateLimitBehaviour: Wait, RequestTimeout: 00:00:30
2021/02/11 06:00:51:179 | Binance    | Debug | Setting api credentials
Exception thrown: 'System.ArgumentException' in mscorlib.dll
An unhandled exception of type 'System.Reflection.TargetInvocationException' occurred in mscorlib.dll
Exception has been thrown by the target of an invocation.

**2. i have tried another way like this:** _BinanceOpenOrders = Await clientBinance.FuturesUsdt.Order.GetOpenOrdersAsync("BTCUSDT")_
i got error like the picture
![error](https://user-images.githubusercontent.com/39071426/107584362-e454f300-6c2e-11eb-8cf4-2a13014f624d.PNG)

**3. i have tried another way like this:** _BinanceOpenOrders = Await clientBinance.FuturesUsdt.Order.GetOpenOrdersAsync("BTCUSDT",origClientOrderId:="VCiikLyxwSNUiyBXFnabfK")_
i got error:
2021/02/11 06:45:22:519 | Binance    | Debug | Client configuration: LogVerbosity: Debug, Writers: 1, Credentials: -, BaseAddress: https://api.binance.com/, Proxy: -, RateLimiters: 0, RateLimitBehaviour: Wait, RequestTimeout: 00:00:30
2021/02/11 06:45:22:536 | Binance    | Debug | Setting api credentials
2021/02/11 06:45:22:550 | Binance    | Debug | [1] Creating request for https://api.binance.com/api/v3/time
'Bot Trade.exe' (CLR v4.0.30319: Bot Trade.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_32\System.Web\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Web.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
2021/02/11 06:45:22:576 | Binance    | Debug | [1] Sending GET request to https://api.binance.com/api/v3/time 
2021/02/11 06:45:22:873 | Binance    | Debug | [1] Response received in 282ms: {"serverTime":1613000723008}
2021/02/11 06:45:22:902 | Binance    | Debug | [2] Creating request for https://api.binance.com/api/v3/time
2021/02/11 06:45:22:903 | Binance    | Debug | [2] Sending GET request to https://api.binance.com/api/v3/time 
2021/02/11 06:45:22:993 | Binance    | Debug | [2] Response received in 88ms: {"serverTime":1613000723134}
2021/02/11 06:45:22:994 | Binance    | Info | Time offset between 0 and 500ms (231.4925ms), no adjustment needed
2021/02/11 06:45:22:996 | Binance    | Debug | [3] Creating request for https://fapi.binance.com/fapi/v1/openOrder
2021/02/11 06:45:23:002 | Binance    | Debug | [3] Sending GET signed request to https://fapi.binance.com/fapi/v1/openOrder?symbol=BTCUSDT&timestamp=1613000722996&origClientOrderId=VCiikLyxwSNUiyBXFnabfK&recvWindow=5000&signature=78F6D0C1A6D45FB44321FEA7D3219300283597CFF2AAE07FCC8260798D378528 
2021/02/11 06:45:23:566 | Binance    | Debug | [3] Response received in 562ms: {"orderId":14019998846,"symbol":"BTCUSDT","status":"NEW","clientOrderId":"VCiikLyxwSNUiyBXFnabfK","price":"0","avgPrice":"0.00000","origQty":"0.146","executedQty":"0","cumQuote":"0","timeInForce":"GTC","type":"STOP_MARKET","reduceOnly":true,"closePosition":false,"side":"BUY","positionSide":"SHORT","stopPrice":"46686","workingType":"CONTRACT_PRICE","priceProtect":false,"origType":"STOP_MARKET","time":1612989862997,"updateTime":1613000723708}
2021/02/11 06:45:23:577 | Binance    | Error | [3] Deserialize JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.IEnumerable`1[Binance.Net.Objects.Futures.FuturesData.BinanceFuturesOrder]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'orderId', line 1, position 11.
Exception thrown: 'System.ArgumentNullException' in System.Core.dll
An exception of type 'System.ArgumentNullException' occurred in System.Core.dll but was not handled in user code
Value cannot be null.

**The same problem for CoinFuture**

**Comment by JKorf** [comment]
Hi there was an issue with an overloaded method of GetOpenOrders which should actually have been called GetOpenOrder. I've fixed it in 6.8.2. Let me know if you have any other issues.

**Comment by dante1989** [comment]
ok wait for me

**Comment by dante1989** [comment]
I have checked for usdt future and coin future
I work very well now
Thanks for your enthusiastic support, I will send donation to your wallet in the next few hours
