### ISSUE TITLE
Using SubAccount.GetSubAccountDepositAddress (POST error)

### ISSUE THREAD

**Issue by scipius** [JKorf/Binance.Net#589]
Using method SubAccount.GetSubAccountDepositAddress(email, asset), get the following error : 

{-1000: Request method 'POST' not supported }

From the documentation, we should be using GET but POST is used.

Thanks!

**Comment by JKorf** [comment]
Hi thanks for the report, you're right. I've fixed it in version 6.8.2. Let me know if you have any other issues!

**Comment by scipius** [comment]
Amazing, thanks for the quick fix 😊

 

I’ll be sending some BTC your way 😃
