### ISSUE TITLE
GetAllOrdersAsync orderId is int

### ISSUE THREAD

**Issue by marinkobabic** [JKorf/Binance.Net#59]
When reading the order uisng GetAllOrdersAsync then an int is expected. When placing the order, the BinancePlacedOrder is of type long.

Would be great to pass the BinancePlacedOrder as override of the method in order to get the actual state of the order.

**Comment by JKorf** [comment]
Hi, what version are you using? In the latest (v3.0.9 atm) all the Id's should be of type long.

**Comment by marinkobabic** [comment]
looks good with the newest version
