### ISSUE TITLE
Need help with the interfaces

### ISSUE THREAD

**Issue by ozgur640** [JKorf/Binance.Net#591]
Hi I am a beginner/intermediate C# user and try to use Binance.Net. I am lost with the usage of the interfaces that SubscribeToKlineUpdatesAsync function returns. Below code was working fine before i update to the latest version from the one that I have been using for 6 months. 
```
BinanceStreamKlineData Data = new BinanceStreamKlineData();
SocketClient.Spot.SubscribeToKlineUpdatesAsync(SymbolString, KlineInterval.OneMinute, (data) =>
{
        Data = data;
});
```

After the upgrade new data type of the "data" seems to be IBinanceStreamKlineData and when i try to build the project I get the following error
_CS0266	Cannot implicitly convert type 'Binance.Net.Interfaces.IBinanceStreamKlineData' to 'Binance.Net.Objects.Spot.MarketStream.BinanceStreamTick'. An explicit conversion exists (are you missing a cast?)_	

Why did the datatype changed and should I use casting to get a BinanceStreamKlineData object as below? or is there a more clever usage with the interfaces.

```
BinanceStreamKlineData Data = new BinanceStreamKlineData();
SocketClient.Spot.SubscribeToKlineUpdatesAsync(SymbolString, KlineInterval.OneMinute, (data) =>
{
        Data = (BinanceStreamKlineData)data;
});
```
Any help would be greatly appreciated.
Best Regards,
Özgür.

**Comment by 8AWESOME4** [comment]
Binance.Net.Interfaces.IBinanceStreamKlineData

**Comment by Hulkstance** [comment]
Use `IBinanceStreamKlineData` instead.

```charp
IBinanceStreamKlineData data = null;
```

**Comment by ozgur640** [comment]
Thanks for the help.
