### ISSUE TITLE
How to get Funding Rate?

### ISSUE THREAD

**Issue by NashTools** [JKorf/Binance.Net#593]
How can I get the funding rate for perpetual futures?

**Comment by kedarnath97** [comment]
Hey, I am looking for the same, could you please advise on how you got it?

**Comment by ViniciusHSAraujo** [comment]
For other people who have the same question, to get the Funding Rate in real time I'm using the following call:

![image](https://user-images.githubusercontent.com/44041869/189540033-d0b600a7-88bc-4c4d-8aa1-8c558d2fec02.png)

Binance API reference: https://binance-docs.github.io/apidocs/futures/en/#mark-price
