### ISSUE TITLE
OCO ORDER NEWBIE HELP

### ISSUE THREAD

**Issue by mixaDD** [JKorf/Binance.Net#595]
Thanks to the authors for the code, 
Please show an example of placing an **OCO order**

I'm new to C #, please help me figure it out

**Comment by mixaDD** [comment]
**my request:**   
         var result = client.Spot.Order.PlaceOcoOrder(
                "BTCUSDT", 
                OrderSide.Sell,
                decQuantity,
                decPrice,
                decStop,
                decStopLimitPrice,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                default);

**Binance answer:**
| Binance    | Debug | [3] Error received: {"code":-1128,"msg":"Combination of optional parameters invalid. Recommendation: 'stopLimitTimeInForce' should also be sent."} 

**how to send it 'stopLimitTimeInForce'??**

**Comment by Hulkstance** [comment]
The error is pretty self explanatory.

```csharp
var pair = "BTCUSDT";
var quantity = your_quantity;

var symbolInfo = await _client.Spot.System.GetExchangeInfoAsync().ConfigureAwait(false).Data?.Symbols.FirstOrDefault(e => e.Name.Equals(pair));

var clampedQuantity = BinanceHelpers.ClampQuantity(
	symbolInfo.LotSizeFilter.MinQuantity,
	symbolInfo.LotSizeFilter.MaxQuantity,
	symbolInfo.LotSizeFilter.StepSize,
	quantity);
	
var result = _client.Spot.Order.PlaceOcoOrderAsync("BTCUSDT", OrderSide.Sell, clampedQuantity, price, stopPrice, stopLimitTimeInForce: TimeInForce.GoodTillCancel).ConfigureAwait(false);
```

Depending on where you are taking the price from, you might have to clamp it as well, using `BinanceHelpers.ClampPrice`. If you are taking the current price from the ticker or the order book, you don't have to round/clamp it.

Anyway, the logs are showing everything to you. You simply provide whatever it requires.
