### ISSUE TITLE
Changes to New Order response

### ISSUE THREAD

**Issue by Hulkstance** [JKorf/Binance.Net#598]
Recently, I started to make use of the data returned by the order response (`BinancePlacedOrder`) and it's a bit confusing when you see Price = 0 with a market order.

Look at the following implementation: https://github.com/ccxt/ccxt/blob/25a55895a46a41f399c96e68aa4f82aaf4ace15a/python/ccxt/binance.py#L1537-#L1585. 

My suggestions are to:
- Add `Remaining` property
- Add `Average` property
- the whole logic I marked on the link above, including when the price is 0 with a market order

The marked lines on the link above are pretty self explanatory.

**Comment by JKorf** [comment]
I've added these in 6.10.0, let me know if this works for you.

**Comment by Hulkstance** [comment]
@JKorf, thanks for your update! Are you sure that QuantityRemaining won't become negative at some point?

```csharp
public decimal QuantityRemaining => Math.Max(Quantity - QuantityFilled, 0);
```
