### ISSUE TITLE
Api with MVC Web Application

### ISSUE THREAD

**Issue by turgayacar** [JKorf/Binance.Net#6]
Greetings;
I would like to use it in an MVC application, but when I run tests in Global.asax it works fine in an Actionresult and it does not give me a value.
I waited for about 1 hour to test it, but nothing happened.
What is the implementation way on the MVC side?

`public ActionResult GetBinanceAccount()
        {
            var assetList = new List<BinanceAssets>();
            using (var client = new BinanceClient("key", "secret"))
            {
                client.AutoTimestamp = true;
                var accountInfo = client.GetAccountInfo();
                foreach (var item in accountInfo.Data.Balances)
                {
                    var asset = new BinanceAssets { Symbol = item.Asset, Free = item.Free, Locked = item.Locked, Total = item.Total };
                    assetList.Add(asset);
                }
            }
            var model = assetList;
            return PartialView(model);
        }`

**Comment by JKorf** [comment]
Hi, if you take the latest version (2.2.0) it should work!
