### ISSUE TITLE
Mandatory parameter 'quoteQty' was not sent, was empty/null, or malformed

### ISSUE THREAD

**Issue by WimVG** [JKorf/Binance.Net#600]
Hello everyone,

I try to swap between currencies using the following code;

```
                WebCallResult<BinanceBSwapResult> binanceBSwapResult= await binanceClient.BSwap.SwapAsync(quoteAssetCurrency, baseAssetCurrency, quoteQuantity);

                if (binanceBSwapResult.ResponseStatusCode == HttpStatusCode.OK)
                {
                    // Store SwapID
                    result = true;
                }
                else
                {
                    result = false;
                }
```

In the reponse, I get 'Bad Request' as Http status code, and the following error message;

`-1102: Mandatory parameter 'quoteQty' was not sent, was empty/null, or malformed. `

What went wrong please? I was thinking about the decimal separator. My system is configured for decimal comma, while the server may expect a decimal point.

Thank you very much for any help.

**Comment by JKorf** [comment]
Hi, the parameter name was incorrectly send, I've fixed this in 6.9.1. Let me know if you have any other issues.

**Comment by WimVG** [comment]
Hi JKorf,
Thank you very much for your quick help and the update! I will test it in detail and keep you updated.

**Comment by JKorf** [comment]
Assuming it's fixed, if not let me know.
