### ISSUE TITLE
FuturesCoin.Market.GetPriceAsync JSON Error

### ISSUE THREAD

**Issue by Mafyou** [JKorf/Binance.Net#603]
**Describe the bug**
When using FuturesCoin.Market.GetPriceAsync I get a JSON Error

**To Reproduce**
Call client.FuturesCoin.Market.GetPriceAsync(symbol)

**Expected behavior**
Have the price of the symbol!

**Debug logging**
"Deserialize JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Binance.Net.Objects.Spot.MarketData.BinancePrice' because the type requires a JSON object (e.g. {\"name\":\"value\"}) to deserialize correctly.\r\nTo fix this error either change the JSON to a JSON object (e.g. {\"name\":\"value\"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.\r\nPath '', line 1, position 1."

**Comment by JKorf** [comment]
Hi, the coin futures API handles this call a little different than the usdt futures/spot API. I've removed the GetPrice method, and instead added the symbol and pair parameters to the GetPrices() call, so you can use that instead from version 6.9.1 on.

**Comment by Mafyou** [comment]
Thanks!
