### ISSUE TITLE
Using https://testnet.binance.vision

### ISSUE THREAD

**Issue by mchurlet** [JKorf/Binance.Net#604]
Is it possible to use "https://testnet.binance.vision" instead of "https://api.binance.com"?

**Comment by Hulkstance** [comment]
Add `BaseAddress = "https://testnet.binance.vision"` to your BinanceClient object.

**Comment by mchurlet** [comment]
![image](https://user-images.githubusercontent.com/8840295/108317710-96a03380-71b6-11eb-8829-9dcd8903707f.png)
It is read only!

**Comment by JKorf** [comment]
You can set it in the options: 
````C#
var client = new BinanceClient(new BinanceClientOptions() {
    BaseAddress = "https://testnet.binance.vision"
});
````

**Comment by Hulkstance** [comment]
Yes. Read-only means it cannot be set later on, but it can through the constructor.

```csharp
var client = new BinanceClient(new BinanceClientOptions()
{
     BaseAddress = "https://testnet.binance.vision"
}
```
