### ISSUE TITLE
Close Position on FuturesBatchOrders

### ISSUE THREAD

**Issue by Mafyou** [JKorf/Binance.Net#606]
**Describe the bug**
At the moment, we cannot put a close Position on BinanceFuturesBatchOrders. 

**Expected behavior**
Have the possibility to put close orders in PlaceMultipleOrders

**Comment by JKorf** [comment]
As per https://binance-docs.github.io/apidocs/futures/en/#place-multiple-orders-trade it doesn't seem to be supported by the Binance API at the moment.

**Comment by Mafyou** [comment]
:'(
