### ISSUE TITLE
Unable to resolve dependency 'WebSocketSharp'

### ISSUE THREAD

**Issue by JMedon** [JKorf/Binance.Net#61]
Hi I want install via nuget in VS2015 and I received below error.
What can I do?

Attempting to gather dependency information for package 'Binance.Net.1.0.0' with respect to project 'CS_Bitmex', targeting '.NETFramework,Version=v4.5.2'
Gathering dependency information took 1.88 sec
Attempting to resolve dependencies for package 'Binance.Net.1.0.0' with DependencyBehavior 'Highest'
Unable to resolve dependency 'WebSocketSharp'. Source(s) used: 'nuget.org', 'Microsoft and .NET', 'Microsoft Visual Studio Offline Packages'.
========== Finished ==========
Time Elapsed: 00:00:01.9579874

**Comment by JKorf** [comment]
Hi, any particlair reason you are trying to install version 1.0.0? Latest version is 3.1.0, can you try that?

**Comment by JMedon** [comment]
Hi I tried to install via Nuget in my VS2015.
Now I try install version 3.1.0 but I recevied below error

Could not install package 'Binance.Net 3.1.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
========== Finished ==========
Time Elapsed: 00:00:02.0315670

**Comment by JKorf** [comment]
I've seen that before, can you try to update your nuget client?
https://dist.nuget.org/visualstudio-2015-vsix/latest/NuGet.Tools.vsix
Also make sure your Visual Studio is up to date.

**Comment by JMedon** [comment]
Hi I treid install from your link but I see that Nuget is up to date.
Also, I tried VS2017 and still have the same issue.
any idea?

**Comment by JKorf** [comment]
Was the VS2017 up to date, or at least version 15.3? It should have build in support for .NetStandard2.0 which the Binance.Net package is. Can you try installing the 'support package' as mentioned here?
https://github.com/dotnet/standard/issues/514

**Comment by JMedon** [comment]
Hi, I change .NET framework to 4.7 and reinstalled Nuget.
Now package was succesfully installed.
Thanks
