### ISSUE TITLE
bracket order for futures

### ISSUE THREAD

**Issue by andristarr** [JKorf/Binance.Net#610]
I would like to ask whether I see it correctly that there is no way to place a bracket order for futures? (Order with a limit as entry, stop as a stoploss and a third limit order as a take profit.) Since the entry order is not guaranteed to fill 100% and may be partially filled, I suspect the best I can do is check whether my order is partially filled and modify my SL and TP order's quantity accordingly?

**Comment by JKorf** [comment]
I don't think bracket orders as you describe are supported no. Checking the filled quantity is the way to go I think.
