### ISSUE TITLE
socketClient.UnsubscribeAll is very slow

### ISSUE THREAD

**Issue by orionflame** [JKorf/Binance.Net#612]
Hi,

I am subscribing to some symbols but later I want to update the list of symbols that are subscribed without having to restart my app. So I used socketClient.UnsubscribeAll but then refreshing the subscriptions including the unsubbing takes more than 10 seconds.

Is there a faster method to update the subscriptions?

I just want to add or remove a symbol from the list of subs.

Thanks a lot in advance.

**Comment by JKorf** [comment]
Binance takes a socket connection per subscription, and calling UnsubscribeAll means those connections get closed, which can take a little time. You don't really have to wait for that though, so instead of calling `await client.UnsubscribeAll()` you can probably just call `_ = client.UnusbscribeAll()` and let the task complete in the background.

**Comment by orionflame** [comment]
Thanks a lot for replying. Actually I am only doing this because the list of coins I am watching gets less or more, i.e. I add more coins or I removed a few from the list.

In these cases, is there a way to update the subscriptions without unsubscribing?

Thanks a lot.

**Comment by orionflame** [comment]
Btw even with the other version of this function, because it takes some time to reconnect WPF UI everything goes to default values like the all values in the UI zero out.

Is there a better way to keep adding new coins to the subscription without disconnecting? What I mean is, if I pass a public collection to subscribe function, and change this collection, would the subscription automatically update?

**Comment by JKorf** [comment]
No, once sockets are connected the subscription can't be changed.
