### ISSUE TITLE
How to place a margin OCO order?

### ISSUE THREAD

**Issue by evren320** [JKorf/Binance.Net#613]
How to place a margin OCO order?

binanceClient.Margin.Order.PlaceMarginOrder(...)
binanceClient.Spot.Order.PlaceOcoOrder(...)
i could not find PlaceMarginOcoOrder method, despite i found those two methods work well, but i need to place a margin oco just similar way to it is exist on the binance web interface.

**Comment by JKorf** [comment]
Margin OCO orders are currently not supported by the Binance API.

**Comment by evren320** [comment]
i see, bad news
