### ISSUE TITLE
missing Margin SubscribeToUserDataUpdates method

### ISSUE THREAD

**Issue by evren320** [JKorf/Binance.Net#614]
We need a method for getting margin userdata updates on the socket client, like:
socketClient.Margin.SubscribeToUserDataUpdates(...);
this is missing in the library, and doing margin actions do not trigger spot subscription events.
despite this method is exist: binanceClient.Margin.UserStream.StartUserStream();
passing return value to other subscription methods do not do anything.

**Comment by JKorf** [comment]
These are the available flavours, depending on which listenkey you start you will receive updates for that type when using the subscribe on the socket client. This is as per Binance API documentation. 

````C#
var listenKeyResultMargin = await client.Margin.UserStream.StartUserStreamAsync();
var listenKeyResultIsolatedMargin = await client.Margin.IsolatedUserStream.StartIsolatedMarginUserStreamAsync("xxx");
var listenKeyResultSpot = await client.Spot.UserStream.StartUserStreamAsync();

var subResult = socketClient.Spot.SubscribeToUserDataUpdatesAsync('"listenkey", etc);
````

Make sure to check the result of the SubscribeToUserDataUpdates call to make sure subscription was completed correctly.

**Comment by evren320** [comment]
thank you i have managed to make it work with this information
