### ISSUE TITLE
Futures USDT new order issues

### ISSUE THREAD

**Issue by evren320** [JKorf/Binance.Net#617]
i am using this method to create positions and orders which works good:
binanceClient.FuturesUsdt.Order.PlaceMultipleOrders(...);
except there is an issue:
if i set ReduceOnly = false , it gives an error code of result.Code = 400 without any message attached to this error.

**Comment by JKorf** [comment]
Hi, this should be fixed in the latest version. ReduceOnly wasn't serialized correctly.

**Comment by GithubZhengYongzhi520** [comment]
> 我正在使用此方法創建效果很好的倉位和訂單：
> binanceClient.FuturesUsdt.Order.PlaceMultipleOrders（...）;
> 除非有問題：
> 如果我將ReduceOnly設置為false，它會給出錯誤代碼result.Code = 400，而此錯誤沒有附加任何消息。

Hello, can I refer to your code
I am facing a problem in use



> i am using this method to create positions and orders which works good:
> binanceClient.FuturesUsdt.Order.PlaceMultipleOrders(...);
> except there is an issue:
> if i set ReduceOnly = false , it gives an error code of result.Code = 400 without any message attached to this error.

Hello, can I refer to your code
I am facing a problem in use

**Comment by GithubZhengYongzhi520** [comment]
> i am using this method to create positions and orders which works good:
> binanceClient.FuturesUsdt.Order.PlaceMultipleOrders(...);
> except there is an issue:
> if i set ReduceOnly = false , it gives an error code of result.Code = 400 without any message attached to this error.

Hello, can I refer to your code
I am facing a problem in use
