### ISSUE TITLE
How to calculate socket ping rate m/s ?

### ISSUE THREAD

**Issue by bydevelopertr** [JKorf/Binance.Net#619]
Hi Dear Team,

I use socket connection but can't get socket m/s rate. 

How can i get this information? I could not see in the examples.

Best Regards.

**Comment by bydevelopertr** [comment]
done

**Comment by naserkaka** [comment]
Hi @bydevelopertr , how did you solve it?

**Comment by bydevelopertr** [comment]
Hi @naserkaka problem is solved. Thank you.
