### ISSUE TITLE
question about up step scenario

### ISSUE THREAD

**Issue by masihnazari** [JKorf/Binance.Net#621]
hello Jan 
thank you for this useful library
 i want to know is there any built-in features for pump time ?
for example i buy at 1000 and set sell for time when price reach 990 . i think its can be  done with stop-lost 
if current market price go up for example 1010 , set sell lost price to 1000, if current reach 1020 set stop-lost to 1010 and ...
I'm new to this program
my current scenario is to buy at current market price and after buy set stop-lost for -10 then check current market price few time in second and if price go up delete old stop-lost with `CancelAllOpenOrdersAsync()` and set new stop lost 
is this good or there is better option for this case ?

**Comment by Hulkstance** [comment]
You are talking about trailing stop loss with -10% offset. And no, it doesn't have such built-in stuff. It's an API wrapper. You should make it yourself.

**Comment by masihnazari** [comment]
thank you
