### ISSUE TITLE
-1013: Stop loss orders are not supported for this symbol. 

### ISSUE THREAD

**Issue by Ruthy85** [JKorf/Binance.Net#622]
Hello, I am getting the title error when I am testing a Sell order with StopLoss. This error is not related with the symbol, because it's the same behaviour for all symbols that I tested. Am I missing anything? 

```
 decimal quantityOfAsset = 3000m; 
 decimal priceOfAssetStopLoss = 0.00001m;

 using (var client = new BinanceClient())
            { 
                var reply = client.Spot.Order.PlaceTestOrder("IOTABTC", OrderSide.Sell, OrderType.StopLoss, quantity: quantityOfAsset, stopPrice: priceOfAssetStopLoss);
            }
```

**Comment by JKorf** [comment]
Hi, you can check which order types are allowed for a symbol using the GetExchangeInfo call:
````C#
var exchangeInfo = await client.Spot.System.GetExchangeInfoAsync();
var supportedOrderTypes = exchangeInfo.Data.Symbols.Single(s => s.Name == "IOTABTC").OrderTypes;
````

**Comment by Ruthy85** [comment]
Hi, thank you. Placing a StopLossLimit order instead was the solution, with both stop prices equal. Thank you!
