### ISSUE TITLE
Futures USDT issue, Liquidation Price is zero

### ISSUE THREAD

**Issue by evren320** [JKorf/Binance.Net#625]
This issue is recently introduced, it was not exist several days ago:
i use this method to get positions:
binanceClient.FuturesUsdt.Account.GetAccountInfo();
foreach (var pos in accountInfo.Data.Positions) {
then, i check pos, turned out pos.MarkPrice and pos.LiquidationPrice are zero.
It was working well before, recently i think something changed.
I have up to date binance net library as for now.

**Comment by JKorf** [comment]
LiquidationPrice isn't returned from that call, use client.FuturesUsdt.GetPositionInformationAsync() instead.

**Comment by evren320** [comment]
thank you
