### ISSUE TITLE
Futures Placing a Market Buy Order 

### ISSUE THREAD

**Issue by oguzhnorhn** [JKorf/Binance.Net#627]
Hello,
I want to place an usdt-futures market order which margin mode and leverage and usdt cost are set before. When I decide on the pair, I type in the name of the coin and  I expect the program to open the position. Here is the code I use for it: 

`string symbol = Console.ReadLine()+"USDT";
                //client.FuturesUsdt.Market.GetPrice(symbol);
                
                client.FuturesUsdt.ChangeInitialLeverage(symbol, 2);
                client.FuturesUsdt.ChangeMarginType(symbol, FuturesMarginType.Isolated);
                client.FuturesUsdt.Order.PlaceOrder(symbol, OrderSide.Buy, OrderType.Market, null);`

As you can see, leverage is set to 2, symbol is written by the user and order is placed. Instead of null, I need to type in the quantity. Instead of quantity, I want to type the total USDT value for the position.
I've tried to get the price of the pair and divide it by the total USDT value to find the quantity but this method 
`client.FuturesUsdt.Market.GetPrice(symbol);` do not return a number value.

I appriciate your help

**Comment by JKorf** [comment]
Hi, I'm not sure what you mean with 'do not return a number value'? You can get the price with:
````C#
var priceResult = client.FuturesUsdt.Market.GetPrice(symbol);
var price = priceResult.Data.Price;
````

**Comment by oguzhnorhn** [comment]
> Hi, I'm not sure what you mean with 'do not return a number value'? You can get the price with:
> 
> ```cs
> var priceResult = client.FuturesUsdt.Market.GetPrice(symbol);
> var price = priceResult.Data.Price;
> ```

You helped a lot, thank you so much.
