### ISSUE TITLE
USDT-M Futures Klines for symbol = "BTCUSDT_210326" Fails Without Bugfix

### ISSUE THREAD

**Issue by jinglenose** [JKorf/Binance.Net#628]
When you try to download the Klines for the symbol BTCUSDT_210326 the bug validation routine containing a regular expression throw and error.  

You can check that this is a valid symbol with following GET...
https://fapi.binance.com/fapi/v1/klines?symbol=BTCUSDT_210326&interval=1m

Here's my VB code that was failing obviously very similar in C#..

Dim oKlines As CryptoExchange.Net.Objects.WebCallResult(Of IEnumerable(Of Interfaces.IBinanceKline))
oKlines = oClient.FuturesUsdt.Market.GetKlines("BTCUSDT_210326", KlineInterval.OneMinute, Date.UtcNow().AddHours(-1), Date.UtcNow(), 1500)

**You can fix this by remming out the error checking as below, you don't need this regular expression.**
        public static void ValidateBinanceSymbol(this string symbolString)
        {
            if (string.IsNullOrEmpty(symbolString))
                throw new ArgumentException("Symbol is not provided");

            //if (!Regex.IsMatch(symbolString, "^([A-Z|a-z|0-9]{5,})*$"))
            //    throw new ArgumentException($"{symbolString} is not a valid Binance symbol. Should be [BaseCurrency][QuoteCurrency], e.g. BTCUSDT");
        }

**Comment by JKorf** [comment]
I've removed the check from the call

**Comment by jinglenose** [comment]
Great thanks
