### ISSUE TITLE
apierror(code=-1021) timestamp error

### ISSUE THREAD

**Issue by prometheus82** [JKorf/Binance.Net#63]
I'm having a problem with above error that started to appear couple days ago.

**Comment by JKorf** [comment]
Does it help if you enable the AutoTimestamp option?

**Comment by jukoson** [comment]
Although this issue was closed, I get the same error only occassionally even with autotimestamp in setDefaultOptions set to true. It seems that whenever this happens, it happens multiple times consecutively but then the request succeeds eventually.

**Comment by habeebmatrix** [comment]
Just to help out anyone who is confused in this regard, I will paste the fixed code here:

> BinanceClient.SetDefaultOptions(new BinanceClientOptions(){ ApiCredentials = new ApiCredentials(apiKey, apiSecret), AutoTimestamp=true});

The extra setting to fix the error is 

> AutoTimestamp=true
