### ISSUE TITLE
Can't connect to the server

### ISSUE THREAD

**Issue by sbrfarhadi** [JKorf/Binance.Net#637]
## The error message ": Can't connect to the server" 

`<PackageReference Include="Binance.Net" Version="6.11.1" />`

```
List<string> lstSymbol = new List<string>();
lstSymbol.Add("BTCUSDT");
lstSymbol.Add("SXPUSDT");
lstSymbol.Add("IOTAUSDT");
lstSymbol.Add("EGLDUSDT");
lstSymbol.Add("SOLUSDT");
lstSymbol.Add("BNBUSDT");

var socketClient = new BinanceSocketClient(//new BinanceSocketClientOptions()
            //{
            //    LogVerbosity = LogVerbosity.Debug,
            //    ApiCredentials = new ApiCredentials(APIKEY, APISECRET)
            //}
            );

 var subResult = await _socketClient.Spot.SubscribeToKlineUpdatesAsync(lstSymbol , KlineInterval.FifteenMinutes, async data =>
            {
                LastKline = data;
                OnKlineData?.Invoke(data);

                await _hub.Clients.All.SendAsync("BroadcastMessage", data?.Symbol, (data?.Data.Close.ToString() ?? "not known yet"));
            });
            if (subResult.Success)
                _subscription = subResult.Data;
```

**Comment by Hulkstance** [comment]
The problem is in your hub, that's what's not able to connect. `SubscribeToKlineUpdatesAsync` works fine.

Anyway, you don't have to use null propagation. `data.Data` won't become null. I edited your code a bit:

```csharp
var symbols = new[]
{
    "BTCUSDT", "SXPUSDT","IOTAUSDT", "EGLDUSDT", "SOLUSDT", "BNBUSDT"
};

var socketClient = new BinanceSocketClient();

var subResult = await socketClient.Spot.SubscribeToKlineUpdatesAsync(symbols, KlineInterval.FifteenMinutes, 
    async data =>
    {
        LastKline = data;
        OnKlineData?.Invoke(data);

        Console.WriteLine($"{data.Symbol} | {data.Data.Close}");

        //await _hub.Clients.All.SendAsync("BroadcastMessage", data.Symbol, data.Data.Close);
    })
    .ConfigureAwait(false);

if (subResult.Success)
{
    _subscription = subResult.Data;
}
```

**Comment by sbrfarhadi** [comment]
Thank you for your answer

I think sometimes this error happens
It is currently connecting with the same code (without your editing)
I did not understand the reason
This happened a few more times and it was fixed the next day

I use the signalR to send information to the ui (is there a better way?)

**Comment by Hulkstance** [comment]
@sbrfarhadi, to rule out any problems with the socket, have you used `SocketNoDataTimeout` in BinanceSocketClient? You shouldn't.

That's how my BinanceSocketClient looks like:

```csharp
new BinanceSocketClient(new BinanceSocketClientOptions
{
    ApiCredentials = new ApiCredentials(exchangeOptions.ApiKey, exchangeOptions.SecretKey),
    AutoReconnect = true,
    ReconnectInterval = TimeSpan.FromSeconds(15),
#if DEBUG
    LogVerbosity = LogVerbosity.Debug
#endif
```

That way, it should work fine for you, which means the problem should be in your hub.

What exactly are you trying to accomplish? AFAIK, SignalR is used whenever you want your server to send information to the client when that information is available without the client manually requesting it, which comes in handy when you want to automatically update the client side without user's request. Is that your case?
