### ISSUE TITLE
Did the API change recently? Recent code is broken

### ISSUE THREAD

**Issue by orionflame** [JKorf/Binance.Net#638]
Hi,

I am porting my app from Winforms to WPF and when I copy paste the same code that's working in Winforms to WPF, I am getting completely different parameters:

socketClient.Spot.SubscribeToUserDataUpdates

In Winforms, I see the signature as:

		CallResult<UpdateSubscription> SubscribeToUserDataUpdates ( string listenKey, Action<BinanceStreamAccountInfo>? onAccountInfoMessage, Action<BinanceStreamOrderUpdate>? onOrderUpdateMessage, Action<BinanceStreamOrderList>? onOcoOrderUpdateMessage, Action<BinanceStreamPositionsUpdate>? onAccountPositionMessage, Action<BinanceStreamBalanceUpdate>? onAccountBalanceUpdate );

In WPF I see this:

		CallResult<UpdateSubscription> SubscribeToUserDataUpdates ( string listenKey, Action<BinanceStreamOrderUpdate>? onOrderUpdateMessage, Action<BinanceStreamOrderList>? onOcoOrderUpdateMessage, Action<BinanceStreamPositionsUpdate>? onAccountPositionMessage, Action<BinanceStreamBalanceUpdate>? onAccountBalanceUpdate );

Why is it like this?
I have code like:
if ( data.Side == OrderSide.Sell )

which doesn't exist in the second function.

Any ideas on how to fix this?

Thanks in advance.

**Comment by Hulkstance** [comment]
`onAccountInfoMessage` was deprecated for a while and Binance completely removed it. It's no longer part of it. This is the current overload:

```csharp
CallResult<UpdateSubscription> SubscribeToUserDataUpdates(
    string listenKey,
    Action<BinanceStreamOrderUpdate>? onOrderUpdateMessage,
    Action<BinanceStreamOrderList>? onOcoOrderUpdateMessage,
    Action<BinanceStreamPositionsUpdate>? onAccountPositionMessage,
    Action<BinanceStreamBalanceUpdate>? onAccountBalanceUpdate);
```

**Comment by orionflame** [comment]
Thanks but how can I convert my existing code? There is no way to know if the order is buy or sell, etc?

Did the author update the example file inside?


Thanks a lot.
