### ISSUE TITLE
No credentials provided for private endpoint

### ISSUE THREAD

**Issue by emin-karadag** [JKorf/Binance.Net#639]
Hello,
For orders in **BTC parity** (CHZBTC, ETHBTC...), I get the following error: **No credentials provided for private endpoint**
There are no problems with **USDT** parities. (CHZUSDT, ETHUSDT...)

I'm using the following version of the Binance.Net library: **v6.11.1**

Binance API permissions are as follows:
**Enable Reading**                        -> true
**Enable Margin**                          -> true
**Enable Spot & Margin Trading** -> true
**Enable Futures**                          -> true

The code block I have used is as follows:

```
const string symbol = "CHZBTC";
BinanceHelper._lastPrices.TryGetValue(symbol, out decimal lastPrice);
if (lastPrice > 0)
{
    var symbolInfo = BinanceHelper._symbols.Find(p => p.Name == symbol);
    if (symbolInfo != null)
    {
        var pricePrecission = OrderHelper.GetDecimalStep(symbolInfo.PriceFilter.TickSize);
        if (pricePrecission < 0) pricePrecission = 0;

        var quantityPrecission = OrderHelper.GetDecimalStep(symbolInfo.LotSizeFilter.StepSize);
        if (quantityPrecission < 0) quantityPrecission = 0;

        var client = new BinanceClient(new BinanceClientOptions
        {
            ApiCredentials = new ApiCredentials("xxxxxxxxxxxxx", "xxxxxxxxxxxxx")
        });

        var quantityPerTrade = 0.001M;
        var quantity = Math.Round(quantityPerTrade / lastPrice, quantityPrecission);

        var marketOrderResult = await _client.Spot.Order.PlaceOrderAsync(symbol, OrderSide.Buy, OrderType.Market, quantity, ct: stoppingToken).ConfigureAwait(false);
        if (!marketOrderResult.Success && marketOrderResult.Error.Code != -1013 && marketOrderResult.Error.Code != -2010)
        {
            // .......
        }
    }
}
```

**Comment by JKorf** [comment]
You're creating a new BinanceClient instance with ApiCredentials `client` but use `_client` (with underscore) to place the order. The `_client` probably doesn't have the ApiCredentials defined.

**Comment by emin-karadag** [comment]
Yes, it escaped my attention. Thank you very much, solved now. :))
