### ISSUE TITLE
How to subscribe to margin account?

### ISSUE THREAD

**Issue by orionflame** [JKorf/Binance.Net#640]
Hi,

I know I can sub to spot account using:
			var successAccount = socketClient.Spot.SubscribeToUserDataUpdates ( spotUserStreamResult.Data,

But what about margin account? I remember this used to work but maybe it's my mind playing tricks on me:

			var successAccount = socketClient.Margin.SubscribeToUserDataUpdates ( spotUserStreamResult.Data,

Any ideas please?

Thanks a lot!

**Comment by Hulkstance** [comment]
You should use the Spot socket client. There isn't Margin socket client.

**Comment by orionflame** [comment]
Then how do we get margin account activity stream?

**Comment by JKorf** [comment]
By providing a different listenkey:
````C#
var client = new BinanceClient();
var marginListenKey = client.Margin.UserStream.StartUserStreamAsync();
var spotListenKey = client.Spot.UserStream.StartUserStreamAsync();
````

**Comment by orionflame** [comment]
Thanks a lot JKorf!
