### ISSUE TITLE
i try connect to ur websocket from my websocket server but failed

### ISSUE THREAD

**Issue by TarrahArshad** [JKorf/Binance.Net#642]
i try connect my server websocket to binance websocket

**Comment by Hulkstance** [comment]
Your question makes no sense. Show some code and logs. You can enable the logging via `LogVerbosity = LogVerbosity.Debug` under BinanceClient/BinanceSocketClient.

**Comment by JKorf** [comment]
This is a client for the Binance API, not the Binance API it self. Problems related to connecting to Binance while not using this library are not in scope.
