### ISSUE TITLE
How to log orders properly

### ISSUE THREAD

**Issue by orionflame** [JKorf/Binance.Net#645]
Hi,

When there is a buy or sell by me, I am trying to log these. If the order is completed it's easy. But if I include partially filled orders, I am getting repeated orders that exceed the number of coins bought. So for example the buy order might have 1000 coins but I am getting repeated logs like:

buy ... 100
buy ... 200
buy ... 800
etc like when the order is still getting filled. Unless I am missing something. I want to include any buy or sell whether the order is partially filled, or fully filled, as long as any coin is bought or sold.

My code is like this:

```
var successAccount = socketClient.Spot.SubscribeToUserDataUpdates ( spotListenKey.Result.Data,
data =>
{
	// Order update
	if ( data.Side == OrderSide.Buy )
	{
		if ( data.Status == OrderStatus.Filled || data.Status == OrderStatus.PartiallyFilled )
		{
			string order = String.Format ( "{0}\t{1}\t{2}\t{3}\t{4}\t{5}", data.Symbol, data.Price, data.QuantityFilled, data.QuoteQuantityFilled, data.OrderId, data.EventTime );
			Utility.AddCoinToBuyOrderLogs ( order );
			Console.WriteLine ( order );
		}
	}
	else if ( data.Side == OrderSide.Sell )
	{
		if ( data.Status == OrderStatus.Filled || data.Status == OrderStatus.PartiallyFilled )
		{
			decimal balance = GetBalanceFromAccount ( data.Symbol.Replace ( "USDT", "" ).Replace ( "BUSD", "" ) );
			if ( balance < 1 )
			{
				Utility.RemoveCoinFromBuyOrderLogs ( data.Symbol );
				Console.WriteLine ( "{0} : Removed from buy logs", data.Symbol );
			}
		}
	}
},
// OCO updates
null,
// Position updates
null,
// Balance updates
null
);
```

Thanks a lot in advance.

**Comment by JKorf** [comment]
If you subscribe to the order update stream you will get an update for every (partially) filled order. The latest update will contain the full information for the order, so if you receive an update for an order you already received an update for you can replace the already known data with the new. That way you'll have the latest info all order. How/when you want to output that is up to you.
