### ISSUE TITLE
Balance update doesn't seem to fire

### ISSUE THREAD

**Issue by orionflame** [JKorf/Binance.Net#646]
Hi,

Is balance update supposed to fire when there is a coin bought or sold? Or if you move some coins between margin and spot account?

Mine doesn't fire in the first case, I didn't test the second case:

var successAccount = socketClient.Spot.SubscribeToUserDataUpdates ( spotListenKey.Result.Data,
data =>
{
//...
},
// OCO updates
null,
// Position updates
null,
// Balance updates
data =>
{
	string symbol = data.Asset.Replace ( "USDT", "" ).Replace ( "BUSD", "" );
	if ( symbol != "" )
	{
		Utility.Coins.FirstOrDefault ( c => c.Symbol == symbol )?.Balance.UpdateAvailableAmount ( );

		decimal balance = GetBalanceFromAccount ( symbol );
		if ( balance < 1 )
		{
			Utility.RemoveCoinFromBuyOrderLogs ( data.Asset );
			Console.WriteLine ( "{0} : Sold everything from spot wallet", data.Asset );
		}
	}
}
);

Thanks a lot in advance.

**Comment by JKorf** [comment]
It should fire. In the snippet you posted you never update the available amount for as far as I can see. You can add a Console.WriteLine message as the first line within the handler to see if the handler gets called.

**Comment by orionflame** [comment]
Thanks JKorf. I thought if I sell or buy something it would fire balance update change no? If so, I thought I could get the balance of that coin from the wallet and then if it's less than 1, remove it from my logs.

**Comment by JKorf** [comment]
You're supposed to use the data parameter you receive in the data handler.
