### ISSUE TITLE
How to get my trades by all symbols?

### ISSUE THREAD

**Issue by BobMakhlin** [JKorf/Binance.Net#647]
I want to create a trades report. So, I need to get the collection of all trades of my binance-account.
I found the method `GetMyTradesAsync`:
```
using BinanceClient client = ...;
WebCallResult<IEnumerable<BinanceTrade>> callResult = await client.Spot.Order.GetMyTradesAsync("BTCBUSD");
```
But this method takes the concrete symbol as a parameter. Maybe there is another method that allows to get all trades of all symbols?

Thank you

**Comment by JKorf** [comment]
As far as I'm aware this is not possible. Binance generally works on a 'per symbol' basis.

**Comment by BobMakhlin** [comment]
Yes, you are right. I asked about this on the [binance forum](https://dev.binance.vision/t/get-all-my-trades/2183). By now it's not possible to get all trades via binance api, but we can do it inside of the account.
