### ISSUE TITLE
Pause all subscriptions

### ISSUE THREAD

**Issue by Hulkstance** [JKorf/Binance.Net#648]
I was going to implement `Pause Bot` functionality using `ManualResetEvent`, but what should I do with the web socket subscriptions that I have? Can you expose a method which could pause them?

```csharp
public class Trader
{
	private readonly ManualResetEvent _mre = new(true);
	
	public async Task RunAsync(CancellationToken cancellationToken)
	{
		await _client.SubscribeToCandleUpdatesAsync("TRXUSDT", KlineInterval.OneMinute,
			data =>
			{
				WaitIfPaused(); // TODO: This ain't gonna work
			
				...
			})
			.ConfigureAwait(false);
	}

	public void WaitIfPaused() => _mre.WaitOne();

	public void Pause() => _mre.Reset();

	public void Resume() => _mre.Set();
}
```

**Comment by JKorf** [comment]
What would you expect to happen? As you said you cant wait inside the handler. Buffering the data until the subscription is resumed doesn't really seem that useful and would introduce problems like what if it is paused for too long? The memory usage would keep increasing.

So if we don't buffer the data that is received then what is the difference between pause and stop/starting again?

**Comment by Hulkstance** [comment]
It could unsubscribe and then subscribe again

**Comment by JKorf** [comment]
Or you could just add a `if(paused) return;` in the handler. I'm not sure pause functionality is really useful.
