### ISSUE TITLE
Can't access variables of object! => BinanceSymbolLotSizeFilter

### ISSUE THREAD

**Issue by 5appz** [JKorf/Binance.Net#650]
![cant access](https://user-images.githubusercontent.com/72450361/110672200-a7e5ca00-81cf-11eb-82ee-50e521bf31e5.png)
![cant access 2](https://user-images.githubusercontent.com/72450361/110672212-aae0ba80-81cf-11eb-8ea3-da984a20bfed.png)

**Comment by JKorf** [comment]
If you access a filter by the list they are typed as the base BinanceSymbolFilter type. You can cast it to the appropriate type using something like this: `var f_lot = (BinanceSymbolLotSizeFilter)item.Filters.First(x => x.FilterType == SymbolFilterType.LotSize);` or you can access the according property on the BinanceSymbol instead: `var f_lot = item.LotSizeFilter;`.
