### ISSUE TITLE
Can we have an overload that returns a collection for socketClient.Spot.SubscribeToSymbolTickerUpdates?

### ISSUE THREAD

**Issue by orionflame** [JKorf/Binance.Net#651]
Basically I am getting better results when I am calling this function for each coin I want to subscribe, store the return result in a dictionary for each coin.

Then if I sell that coin, I just unsubscribe from that specific coin. No need to unsub from all. And conversely adding new coins to subscription is very easy.

The only issue is, when I call this function one by one, it takes much longer to initialize the app with 50+ coins. So it would be useful to have a version that takes a collection of symbols which it does, but also return a collection of UpdateSubscription.

Unless it will still be slow to do this.

**Comment by JKorf** [comment]
You can concurrently subscribe to multiple symbols using something like this:
````C#
var socketClient = new BinanceSocketClient();
var subTask1 = socketClient.Spot.SubscribeToSymbolTickerUpdatesAsync("Symbol1", handler);
var subTask2 = socketClient.Spot.SubscribeToSymbolTickerUpdatesAsync("Symbol2", handler);
var subTask3 = socketClient.Spot.SubscribeToSymbolTickerUpdatesAsync("Symbol3", handler);
await Task.WhenAll(new [] { subTask1, subTask2, subTask3 });
````

**Comment by orionflame** [comment]
Thanks JKorf I didn't know this. How would you do it for this code though?

		public static List<Task<CallResult<UpdateSubscription>>> AddNewSubscription ( BinanceSocketClient socketClient, Coin coin )
		{
			List<Task<CallResult<UpdateSubscription>>> tasks = new List<Task<CallResult<UpdateSubscription>>> ( );
			List<UpdateSubscription> subs = new List<UpdateSubscription> ( );

			var sub = socketClient.Spot.SubscribeToSymbolTickerUpdatesAsync ( coin.SymbolPair, data =>
			{
				coin.Price = data.LastPrice;
				coin.LowestDailyPrice = data.LowPrice;
				coin.HighestDailyPrice = data.HighPrice;
				coin.PriceChangeInPercentDaily = data.PriceChangePercent;
			} );
			tasks.Add ( sub );
			subs.Add ( sub.Result.Data );

			//socketClient.Spot.SubscribeToSymbolTickerUpdates ( "BTCUSDT", data =>
			//{
			//	var coin = coins [ data.Symbol ];
			//	if ( coin != null )
			//		coin.TotalVolume = data.BaseVolume;
			//} );

			sub = socketClient.Spot.SubscribeToKlineUpdatesAsync ( coin.SymbolPair, KlineInterval.OneHour, data =>
			{
				coin.LastHourOpenPrice = data.Data.Open;
				coin.LastHourVolume = data.Data.BaseVolume;
				coin.TotalBuyVolume = data.Data.TakerBuyBaseVolume;
				coin.TotalSellVolume = coin.LastHourVolume - coin.TotalBuyVolume;
			} );
			tasks.Add ( sub );
			subs.Add ( sub.Result.Data );

			sub = socketClient.Spot.SubscribeToKlineUpdatesAsync ( coin.SymbolPair, KlineInterval.OneMinute, data =>
			{
				coin.LastMinuteOpenPrice = data.Data.Open;
			} );
			tasks.Add ( sub );
			subs.Add ( sub.Result.Data );

			sub = socketClient.Spot.SubscribeToKlineUpdatesAsync ( coin.SymbolPair, KlineInterval.OneMinute, data =>
			{
				//	BUY VOLUME: data.Data.TakerBuyBaseVolume
				coin.LastMinuteVolume = data.Data.TakerBuyBaseVolume - ( data.Data.BaseVolume - data.Data.TakerBuyBaseVolume );
			} );
			tasks.Add ( sub );
			subs.Add ( sub.Result.Data );

			Utility.ActiveSubscriptions.Add ( coin.Symbol, subs );

			return tasks;
		}

		public static async Task AddNewSubscriptions ( BinanceSocketClient socketClient, IEnumerable<Coin> coins )
		{
			List<Task<CallResult<UpdateSubscription>>> tasks = new List<Task<CallResult<UpdateSubscription>>> ( );
			int index = 0;

			foreach ( var coin in coins )
			{
				var subs = Utility.AddNewSubscription ( socketClient, coin );
				Console.WriteLine ( "{0}/{1} : {2}", index, coins.Count ( ), coin.Symbol );
				++index;

				tasks.Union ( subs );
			}

			//foreach(var task in tasks)
			//	Utility.ActiveSubscriptions.Add ( coin.Symbol, task.Result.Data );

			await Task.WhenAll ( tasks );
		}

Would you do it like this or do it in the first method. I just don't know if gathering all tasks like this and then calling WhenAll works, but when I run it the speed didn't improve.

So I guess I will use WhenAll in the first method.

**Comment by JKorf** [comment]
Calling .Result on a task will block the thread until the task is completed. Make sure you're only looking at the Result property of a task after you awaited it.
