### ISSUE TITLE
Incorrect websocket kline 'Close' values reported when subscribing to multiple streams

### ISSUE THREAD

**Issue by keithl8041** [JKorf/Binance.Net#652]
**Describe the issue**
When subscribing to websocket kline updates for a symbol, the closing price is incorrectly reported when multiple subscriptions are made to the same symbol using different kline intervals. Each candlestick interval reports back the same closing price, which is impossible. I assume this is a concurrency issue somewhere.

**To Reproduce**
Sample code: 

    `    const string symbol = "BTCUSDT";
            using var socketClient = new BinanceSocketClient();
            var output = new Dictionary<KlineInterval, decimal>();
            var klines = new[]
            {
                KlineInterval.OneMinute,
                KlineInterval.FiveMinutes,
                KlineInterval.ThirtyMinutes,
                KlineInterval.OneDay,
                KlineInterval.OneWeek,
                KlineInterval.OneMonth
            };

            foreach (var interval in klines)
            {
                output.Add(interval, 0M);
                await socketClient.FuturesUsdt.SubscribeToKlineUpdatesAsync(symbol, interval,
                    data =>
                    {
                        // Console.WriteLine(interval.ToString("G") + ": " + data.Data.Close);
                        output[data.Data.Interval] = data.Data.Close;

                        var count = output.Select(x => x.Value).GroupBy(x => x).Select(x => new { x.Key, Count = x.Count() });
                        foreach (var row in count)
                        {
                            Console.WriteLine($"{DateTime.Now:O} : There are {row.Count} identical 'Close' values across {output.Count} different intervals");
                        }
                    });
            }

            ConsoleKey input;
            do
            {
                input = Console.ReadKey().Key;
            } while (input != ConsoleKey.X);

            await socketClient.UnsubscribeAll();
`

**Expected behavior**
I would expect each separate web-socket response to contain kline data only relating to the interval that was subscribed to.

**Debug logging**
See the 'c' value of '56198.72' is represented many times across different klines, from one minute up to one month in duration.

2021/03/10 23:35:52:059 | Binance    | Debug | Socket 4 received data: {"stream":"btcusdt@kline_1d","data":{"e":"kline","E":1615419351226,"s":"BTCUSDT","k":{"t":1615334400000,"T":1615420799999,"s":"BTCUSDT","i":"1d","f":582498974,"L":586896365,"o":"54917.78","c":"56198.72","h":"57500.92","l":"53061.00","v":"396777.469","n":4397362,"x":false,"q":"22033760183.26929","V":"194933.916","Q":"10828040124.81314","B":"0"}}}
2021/03/10 23:35:52:060 | Binance    | Debug | Socket 5 received data: {"stream":"btcusdt@kline_1w","data":{"e":"kline","E":1615419351226,"s":"BTCUSDT","k":{"t":1615161600000,"T":1615766399999,"s":"BTCUSDT","i":"1w","f":575907047,"L":586896365,"o":"50991.35","c":"56198.72","h":"57500.92","l":"49310.00","v":"990722.133","n":10989263,"x":false,"q":"53098750406.30707","V":"490904.528","Q":"26306717873.84176","B":"0"}}}
2021/03/10 23:35:52:064 | Binance    | Debug | Socket 6 received data: {"stream":"btcusdt@kline_1M","data":{"e":"kline","E":1615419351226,"s":"BTCUSDT","k":{"t":1614556800000,"T":1617235199999,"s":"BTCUSDT","i":"1M","f":552038774,"L":586896365,"o":"45162.64","c":"56198.72","h":"57500.92","l":"44972.49","v":"3135316.472","n":34857385,"x":false,"q":"158141109901.08595","V":"1555769.087","Q":"78479899564.01658","B":"0"}}}
2021/03/10 23:35:52:064 | Binance    | Debug | Socket 2 received data: {"stream":"btcusdt@kline_5m","data":{"e":"kline","E":1615419351225,"s":"BTCUSDT","k":{"t":1615419300000,"T":1615419599999,"s":"BTCUSDT","i":"5m","f":586894216,"L":586896365,"o":"56122.97","c":"56198.72","h":"56224.50","l":"56118.44","v":"153.497","n":2150,"x":false,"q":"8621543.40099","V":"79.551","Q":"4468505.46246","B":"0"}}}
2021-03-10T23:35:52.0706225+00:00 : There are 4 identical close values across 6 different intervals
2021/03/10 23:35:52:074 | Binance    | Debug | Socket 1 received data: {"stream":"btcusdt@kline_1m","data":{"e":"kline","E":1615419351225,"s":"BTCUSDT","k":{"t":1615419300000,"T":1615419359999,"s":"BTCUSDT","i":"1m","f":586894216,"L":586896365,"o":"56122.97","c":"56198.72","h":"56224.50","l":"56118.44","v":"153.497","n":2150,"x":false,"q":"8621543.40099","V":"79.551","Q":"4468505.46246","B":"0"}}}
2021-03-10T23:35:52.0744351+00:00 : There are 1 identical close values across 6 different intervals
2021-03-10T23:35:52.0758924+00:00 : There are 4 identical close values across 6 different intervals
2021/03/10 23:35:52:077 | Binance    | Debug | Socket 3 received data: {"stream":"btcusdt@kline_30m","data":{"e":"kline","E":1615419351225,"s":"BTCUSDT","k":{"t":1615419000000,"T":1615420799999,"s":"BTCUSDT","i":"30m","f":586868268,"L":586896365,"o":"56186.82","c":"56198.72","h":"56317.25","l":"55900.00","v":"2317.699","n":28098,"x":false,"q":"129991668.79594","V":"1167.217","Q":"65483022.77876","B":"0"}}}
2021-03-10T23:35:52.0786402+00:00 : There are 5 identical close values across 6 different intervals

**Comment by JKorf** [comment]
The websocket sends continuous updates for the last kline which isn't closed yet, updating it when new data is available. When a trade is made on a symbol which changes the price the close price for all unclosed klines changes to that price, regardless of the interval. 
It makes sense that all klines across all intervals which aren't closed yet have the same close value.

**Comment by keithl8041** [comment]
Yep actually that does make sense. Thanks for the explanation - glad I didn't spend time trying to fix a design issue.
