### ISSUE TITLE
Filter failure: Min_Notional

### ISSUE THREAD

**Issue by aks3213** [JKorf/Binance.Net#654]
`var replyStopLossSell = await client.Spot.Order.PlaceTestOrderAsync(symbol, OrderSide.Sell, OrderType.StopLossLimit,9, null, "2",0.5m, TimeInForce.GoodTillCancel,0.5m, null, OrderResponseType.Full,null, default);`

![Untitled3](https://user-images.githubusercontent.com/68645565/110903620-bba74280-832d-11eb-96d3-66977df0d451.png)

**Comment by aks3213** [comment]
if you can provide examples of coding other than details for how to use all endpoints that will be helpful.
by the way appreciate your work.

**Comment by JKorf** [comment]
See https://binance-docs.github.io/apidocs/spot/en/#filters for filter info.
