### ISSUE TITLE
Logging to NLog, Log4Net or Microsoft.Extensions.Logging.ILogger

### ISSUE THREAD

**Issue by walterX12** [JKorf/Binance.Net#655]
Hi,

thank you very much for sharing useful libarry. I am using NLog i my app and I would logg Binance.Net logs usning NLog. I am able to set up Binance.Net to log to the console (generally speaking System.IO.TextWiter). Is there any chance inject/use Nlog, Log4Net or Microsoft.Extensions.Logging.ILogger ? 

My code for Console logging.
```
      {
            BinanceClient.SetDefaultOptions(new BinanceClientOptions()
            {
                ApiCredentials = new ApiCredentials(apiKey, apiSecret),
                LogVerbosity = LogVerbosity.Warning,
                LogWriters = new List<TextWriter> { Console.Out }
            });
            BinanceSocketClient.SetDefaultOptions(new BinanceSocketClientOptions()
            {
                ApiCredentials = new ApiCredentials(apiKey, apiSecret),
                LogVerbosity = LogVerbosity.Warning,
                LogWriters = new List<TextWriter> { Console.Out },
                AutoReconnect = true,
                ReconnectInterval = new TimeSpan(0, 0, 5),
                SocketNoDataTimeout = new TimeSpan(0, 0, 10)
            });
        }
```

Thank you

**Comment by JKorf** [comment]
You can add a small wrapper for this. Make a class which implements the TextWriter base class and implement the WriteLine methods. Pass that to the LogWriters list.

**Comment by JKorf** [comment]
FYI, in the latest beta releases the logging is done via the Microsoft.Extensions.Logging.ILogger.

**Comment by walterX12** [comment]
Thank you very much. It helps.
