### ISSUE TITLE
Websocket errors : Socket 49 message processing slow (1743ms), consider offloading data handling to another thread. Data from this socket may arrive late or not at all if message processing is continuously slow.

### ISSUE THREAD

**Issue by jurgenBE** [JKorf/Binance.Net#659]
Hi I have this code in a winform (I don't know if winforms is the best option though) 👍 

In a button click "start" : i have this code 

socketClient1.Spot.SubscribeToBookTickerUpdates("ADABRL", (data) => { Handledata("BinanceTradingPairs", data); });
            socketClient1.Spot.SubscribeToBookTickerUpdates("ADATRY", (data) => { Handledata("BinanceTradingPairs", data); });
            socketClient1.Spot.SubscribeToBookTickerUpdates("ADAUSDT", (data) => { Handledata("BinanceTradingPairs", data); });
            socketClient1.Spot.SubscribeToBookTickerUpdates("AVAXTRY", (data) => { Handledata("BinanceTradingPairs", data); });
            socketClient1.Spot.SubscribeToBookTickerUpdates("AVAXUSDT", (data) => { Handledata("BinanceTradingPairs", data); });
            socketClient1.Spot.SubscribeToBookTickerUpdates("BNBBIDR", (data) => { Handledata("BinanceTradingPairs", data); });
            socketClient1.Spot.SubscribeToBookTickerUpdates("BNBBRL", (data) => { Handledata("BinanceTradingPairs", data); });
           ....
I have 78 lines like that : in my Handledata function I do the following : 

try
            {
                SetText(data.Symbol);
                if (dictTickers.ContainsKey(data.Symbol + "-bid"))
                {
                    dictTickers[data.Symbol + "-bid"].BestPrice = data.BestBidPrice;
                    dictTickers[data.Symbol + "-bid"].BestQuantity = data.BestBidQuantity;
                    //here do some calculations
                }

                if (dictTickers.ContainsKey(data.Symbol + "-ask"))
                {
                    dictTickers[data.Symbol + "-ask"].BestPrice = data.BestAskPrice;
                    dictTickers[data.Symbol + "-ask"].BestQuantity = data.BestAskQuantity;
                    //here do some calculations
                }
            }
            catch (Exception ex)
            {
                lstExceptions.Add(DateTime.Now.ToString() + "|" + ex.Message);
            }

But my winform app a lot of the times throws this error in the console :

Warning | Socket 49 message processing slow (1743ms), consider offloading data handling to another thread. Data from this socket may arrive late or not at all if message processing is continuously slow.
2021/03/15 16:15:10:836 | Binance    | Warning | Socket 68 message processing slow (1808ms), consider offloading data handling to another thread. Data from this socket may arrive late or not at all if message processing is continuously slow.
2021/03/15 16:15:10:840 | Binance    | Warning | Socket 59 message processing slow (1753ms), consider offloading data handling to another thread. Data from this socket may arrive late or not at all if message processing is continuously slow.
2021/03/15 16:15:10:846 | Binance    | Warning | Socket 72 message processing slow (1758ms), consider offloading data handling to another thread. Data from this socket may arrive late or not at all if message processing is continuously slow.

Am I doing it wrong the way i do this websocket subscriptions, or should i use multiple socketclients?

Now if I want to place 2 orders after my calculations, should i do it in this handledata functions, andI want to 'pauze' the handledata after i submitted htese 2 orders to verify before i procedd, is that possible in .net. I am not too much experienced in this async and websockets methodology since i am sick several years, and my knowledge of c# is not really up-to-date anymore.

Thanks for suggestions or help.
Jurgen

**Comment by blahblehblah** [comment]
1. You could simply send an array of symbols; SubscribeToBookTickerUpdates([array]) instead of the way you're already doing.
2. Run the data handler in a separate thread.

**Comment by thomasd3** [comment]
it is essential to acknowledge the message right away and process the data on another thread. Otherwise they will not send you all messages anymore.

**Comment by JKorf** [comment]
As suggested, your handling of the data takes too long.
