### ISSUE TITLE
recvWindow error when sending trade order

### ISSUE THREAD

**Issue by mclean25** [JKorf/Binance.Net#66]
Hi JKorf,

I'm running an app using this libary on a Linux server. I'm getting the following error when attempting to execute `PlaceOrder()`:

```
"Server Error: {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}
```

I see that there is not optional `param` for `revWindow`. Would it make sense to add this as a field to the `BinanceClient` so that all methods could use a custom `recvWindow`?

**Comment by mclean25** [comment]
I created a branch adding `recvWindows` as an optional `param` but GitHub isn't letting my push the branch to this repo...

**Comment by JKorf** [comment]
That's weird. I'll add the parameter, since it's part of the API, but in the mean time you might want to enable the AutoTimestamp option to sync your local computer time with the server time. That should normally prevent the error you're getting.

**Comment by mclean25** [comment]
Still seem to be getting this error somehow even with `AutioTimeStamp = true`

**Comment by JKorf** [comment]
I've added the receiveWindow parameter in the latest version
