### ISSUE TITLE
BinanceFuturesStreamOrderUpdateData "Realized Profit of the trade" missing

### ISSUE THREAD

**Issue by Tyreens** [JKorf/Binance.Net#660]
Hey,

in the userdata "Event: Order Update" for binance futures is the field "rp (Realized Profit of the trade)" missing.
https://binance-docs.github.io/apidocs/futures/en/#event-balance-and-position-update

**Comment by JKorf** [comment]
Thanks for the report, should be fixed in 6.13.0
