### ISSUE TITLE
Mining endpoints should be used as signed

### ISSUE THREAD

**Issue by appsettings** [JKorf/Binance.Net#661]
I'm trying to use mining endpoints, like this:

`2021/03/17 22:33:24:411 | Binance    | Debug | [2] Creating request for https://api.binance.com/sapi/v1/mining/payment/list
2021/03/17 22:33:24:411 | Binance    | Debug | [2] Sending GET request to https://api.binance.com/sapi/v1/mining/payment/list?algo=ETHASH&userName=test 
2021/03/17 22:33:24:754 | Binance    | Debug | [2] Error received: {"code":-1002,"msg":"You are not authorized to execute this request."}`

I found out that those endpoints are marked as signed on Binance documentation and so they need hmac signature. I reproduced the issue with a postman call: if I add the signature I correctly get a response from those endpoints.

Can it be fixed?
Thanks

**Comment by JKorf** [comment]
Thanks for the report, should be fixed in 6.13.0

**Comment by appsettings** [comment]
Thanks, I've tried 6.13 but now I receive:

`2021/03/31 21:36:10:024 | Binance    | Debug | [5] Creating request for https://api.binance.com/sapi/v1/mining/payment/list
2021/03/31 21:36:10:024 | Binance    | Debug | [5] Sending GET signed request to https://api.binance.com/sapi/v1/mining/payment/list?algo=ETHASH&userName=test&signature=F5D6D1CF9A91117C8514B91DD25169C322F8B8EE33EDACEE97B4AAC3EF3FC8E3 
2021/03/31 21:36:10:396 | Binance    | Debug | [5] Error received: {"code":-1102,"msg":"A mandatory parameter was not sent, was empty/null, or malformed."}`

**Comment by appsettings** [comment]
@JKorf I don't know how to reopen this. Thanks

**Comment by JKorf** [comment]
It should work in 6.13.1 now
