### ISSUE TITLE
how to i detect which APIKey have a order ?

### ISSUE THREAD

**Issue by TarrahArshad** [JKorf/Binance.Net#662]
i write tool for copytrading i need know how to implement this system
1. how to connect my client websocket to binance websocket ( server to server )
2. how to i can detect which apikey have a trade ( how to i track when i have 100 apikey )
3. i can implement in service base or web socket server or need console or desktop app

thank you for guide me

**Comment by JKorf** [comment]
Your questions are outside the scope of this library
