### ISSUE TITLE
Is there a limit of symbols that i can subscribe?

### ISSUE THREAD

**Issue by tmdwns7809** [JKorf/Binance.Net#663]
I found that when i subscribe symbols, i cannot receive any data if i subscribe too many symbols at once.

Like if i send more than 1000 symbols to this method
SocketClient.Spot.SubscribeToAggregatedTradeUpdates
i cannot get any data after but only 500 works fine

Is there a limit?

**Comment by JKorf** [comment]
I'm not aware of a limit of connections, but there might be one. You could maybe try to combine connections to create less separate connections by passing multiple symbols to a single `SubscribeToAggregatedTradeUpdates` call, which then will subscribe those symbols on a single connection.

**Comment by thomasd3** [comment]
there is a practical limit: above 40 or so symbols, you start to have missing trades at some point. I guess Binance is limiting how much data they send you.
You can verify this by looking at the trade ids: the aggregated blocks will still arrive with sequential numbers, but the first / last trade ids, inside the blocks, will sometimes not match anymore.

**Comment by hipo760** [comment]
> I'm not aware of a limit of connections, but there might be one. You could maybe try to combine connections to create less separate connections by passing multiple symbols to a single `SubscribeToAggregatedTradeUpdates` call, which then will subscribe those symbols on a single connection.

Is there any option i can set for BinanceSocketClient to reuse the same connection? thx!

**Comment by tmdwns7809** [comment]
Thanks! i get it
