### ISSUE TITLE
How to get Isolated Margin balance for one asset in a single pair.

### ISSUE THREAD

**Issue by martensthedude** [JKorf/Binance.Net#665]
I'm trying to get balance of an asset in a Isolated Margin pair but I can't find a way that works.

Example:

I have deposited 100 USDT in BTCUSDT Isolated Margin wallet.
Then I bought BTC with those 100USDT x10.
How do I get my BTC balance now?

**Comment by JKorf** [comment]
client.Margin.GetIsolatedMarginAccountAsync();
