### ISSUE TITLE
Symbol Ticker Updates on Testnet

### ISSUE THREAD

**Issue by eouree** [JKorf/Binance.Net#666]
Hi all,

As per below code, when am subscribing to production Binance Socket Client am getting Symbol Ticker Updates normally. Then if uncomment the BaseAddress as below in order to subscribe to the Testnet Binance Socket Client then i get no Symbol Ticker Updates at all. 

Can anyone figure out what am doing wrong?

        public async Task GetSymbol(BinanceSymbol binanceSymbol)
        {
            BinanceClient.SetDefaultOptions(new BinanceClientOptions
            {
                AutoTimestamp = true,
                AutoTimestampRecalculationInterval = TimeSpan.FromMinutes(30),
                // BaseAddress = "https://testnet.binance.vision",
            });

            BinanceSocketClient.SetDefaultOptions(new BinanceSocketClientOptions()
            {
                AutoReconnect = true,
                // BaseAddress = "wss://testnet.binance.vision/ws",
                ReconnectInterval = TimeSpan.FromSeconds(15)
            });

            using (BinanceClient binanceClient = new BinanceClient())
            {
                WebCallResult<BinancePrice> result = await binanceClient.Spot.Market.GetPriceAsync(binanceSymbol.Symbol);

                if (result.Success)
                    Symbol = new BinanceSymbol(result.Data.Symbol, result.Data.Price);
                else
                    MessageBox.Show($"Error requesting Symbol data: {result.Error.Message}", @"Error", MessageBoxButton.OK, MessageBoxImage.Error);
            }

            _binanceSocketClient = new BinanceSocketClient();

            _binanceSocketClient.Spot.SubscribeToSymbolTickerUpdates(binanceSymbol.Symbol, data =>
            {
                Symbol.Price = data.LastPrice;
                Symbol.HighPrice = data.HighPrice;
                Symbol.LowPrice = data.LowPrice;
                Symbol.PriceChangePercent = data.PriceChangePercent;
                Symbol.TradeAmount = data.TotalTrades;
                Symbol.Volume = data.BaseVolume;
            });
        }

**Comment by eouree** [comment]
Console logs give the following:

2021/03/24 18:26:01:920 | Binance    | Debug | Client configuration: LogVerbosity: Debug, Writers: 1, Credentials: -, BaseAddress: wss://testnet.binance.vision/ws/, Proxy: -, AutoReconnect: True, ReconnectInterval: 00:00:15, SocketResponseTimeout: 00:00:10, SocketSubscriptionsCombineTarget:
2021/03/24 18:26:01:945 | Binance    | Debug | Created new socket for wss://testnet.binance.vision/ws/stream?streams=xrpusdt@ticker
2021/03/24 18:26:01:968 | Binance    | Debug | Socket 1 connecting
2021/03/24 18:26:03:334 | Binance    | Info | Socket 1 **error: System.Exception: unknown server protocol version**
2021/03/24 18:26:03:335 | Binance    | Debug | Socket 1 connection failed, state: Connecting
2021/03/24 18:26:03:337 | Binance    | Info | Socket 1 closed
2021/03/24 18:26:03:337 | Binance    | Debug | Socket 1 disposing websocket
2021/03/24 18:26:03:337 | Binance    | Info | Socket 1 error: System.Net.Sockets.SocketException (0x80004005): A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied
2021/03/24 18:26:03:338 | Binance    | Info | Socket 1 closed

**Comment by JKorf** [comment]
I think you have to remove the /ws postfix from the websocket testnet address

**Comment by eouree** [comment]
Hi JKorf. Thanks for responding. Yes i did it and works. Just now saw that already answered here https://github.com/JKorf/Binance.Net/issues/557.

The prices refreshing rate of Testnet doesn't seems realistic. In fact prices barely change. From your experience this is how the Testnet works or am doing something wrong?

**Comment by JKorf** [comment]
I don't have any notable experience with the testnet so I can't help you with that, sorry.

**Comment by eouree** [comment]
Thank you
