### ISSUE TITLE
Is there any way to subscribe to a symbol trades ?

### ISSUE THREAD

**Issue by ShayanFiroozi** [JKorf/Binance.Net#673]
Hi,

I need to **subscribe** to a symbol trade in order to get recent trades info like a stream.

I am aware of the **GetSymbolTrades** function , but it takes about 7 seconds to get the data , also the function pulling the whole list which is not optimum.

I appreciate any suggestion.

**Comment by JKorf** [comment]
Are you looking for `socketClient.Spot.SubscribeToTradeUpdates`?

**Comment by ShayanFiroozi** [comment]
> Are you looking for `socketClient.Spot.SubscribeToTradeUpdates`?

Yes , exactly what I need , I was looking at the BinanceClient class !

Thank you.
