### ISSUE TITLE
Feature request: Market Cap value

### ISSUE THREAD

**Issue by hcanak** [JKorf/Binance.Net#675]
May you consider to add support for retrive the "market cap" value?  I see that it can be GET from this endpoint; https://www.binance.com/exchange-api/v2/public/asset-service/product/get-products

It is defined here: https://stackoverflow.com/questions/66132843/is-there-a-way-to-get-the-market-cap-or-market-cap-rank-of-a-coin-using-the-bina

**Comment by JKorf** [comment]
This has been added to the beta release package

**Comment by hcanak** [comment]
Thanks for your quick response...
