### ISSUE TITLE
How does CoinStats calculate all time and current PNL for Binance?

### ISSUE THREAD

**Issue by orionflame** [JKorf/Binance.Net#676]
Hi,

I installed that app and connected my wallet, and they are able to show me how much profit and loss I have currently as well as all time.

I don't know my all time PNL for each coin but I can see its current holding PNL is looks like within the ball park.

I ask because there is no way to get all past orders using the binance API, right?

That's why I am not sure how they are doing this.

**Comment by JKorf** [comment]
No there is no way to get all orders. They probably save the current value of your assets every minute or so. You can then compare the current value with the value it was 24 hours ago by looking up the value at the same minute 24 hours ago.

Or it might be some other method, this just is what came to my mind first.
