### ISSUE TITLE
null trades received from SubscribeToAggregatedTradeUpdatesAsync when using SendPeriodic

### ISSUE THREAD

**Issue by thomasd3** [JKorf/Binance.Net#677]
I have this code (f#):

    let! result = socket.FuturesUsdt.SubscribeToAggregatedTradeUpdatesAsync(instrument.Ticker, fun trade -> tradesProcessor.Post(trade)) |> Async.AwaitTask

so just a classic trade subscription and then I was checking if sending a regular ping could help stability:

    socket.SendPeriodic(TimeSpan.FromSeconds(15.), (fun _ -> box "ping"))

the trade event will fire at the interval I'm sending periodic data and receive a null trade.

**Comment by JKorf** [comment]
The task update handler will see the pong message from the Binance server and try to interpret it as a Trade message. Or so I expect.

**Comment by JKorf** [comment]
This isn't really an easy in the library
