### ISSUE TITLE
Update version / Error request

### ISSUE THREAD

**Issue by Bozzano13** [JKorf/Binance.Net#68]
Hello,

First, I Thanks you for your project.

I did the new update and now I have an issue when I do a request.
Now, I have this error : 
Original in French :
3: Web error: No response from server | SecureChannelFailure - La demande a été abandonnée : Impossible de créer un canal sécurisé SSL/TLS.
Translated: 
3: Web error: No response from server | SecureChannelFailure - The request has been aborted: Unable to create SSL / TLS secure channel.

Do I need to do something special ? 
Do you know why this error happened ?

Thank,
Regards,

**Comment by JKorf** [comment]
Hi, should work if you enable Tls1.2 as security protocol at the start of your program:
`ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;`
