### ISSUE TITLE
How to Subscribe the 24Hours of all symbols ?

### ISSUE THREAD

**Issue by ShayanFiroozi** [JKorf/Binance.Net#681]
Hi ,
I need to subscribe the 24 hours information of all symbols ( Price change , lowest , highest and etc..).
I am aware of the **Get24HPrices** function , but it's slow and not **Realtime**.

How can I subscribe the 24Hours market information and receive data like a **stream**.

Thank you.

**Comment by JKorf** [comment]
You can use the BinanceSocketClient for this.
````C#
binanceSocketClient.Spot.SubscribeToAllSymbolTickerUpdatesAsync(data =>
{
    // handle
});
````
