### ISSUE TITLE
Update Interval

### ISSUE THREAD

**Issue by ZigmundL** [JKorf/Binance.Net#683]
IBinanceSocketClientSpot.SubscribeToPartialOrderBookUpdates I would like to use updateInterval 0 to get all messages. Current minimum value is 100ms which is 5-10 times less updates than really happens there. Is there something I can do about it?

**Comment by JKorf** [comment]
Nothing we can do about that, it's just how often Binance sends updates, which is every 100ms at most for that endpoint.
