### ISSUE TITLE
Unable to check balance or open trades : it says no API Creds were provided, but i did provide

### ISSUE THREAD

**Issue by hdshivambu** [JKorf/Binance.Net#684]
**Describe the bug**

**To Reproduce**
What endpoints and subscriptions are called.
this is the function i am trying to call : 
client.FuturesUsdt.Account.GetBalanceAsync().Result.Data;

and this is the response i get : 

| Binance    | Warning | [25] Request /fapi/v2/balance failed because no ApiCredentials were provided

**Expected behavior**

**Debug logging**
Add debug logging related to the issue. Enable Debug logging in the client options by settings LogVerbosity to Debug.

**Comment by hdshivambu** [comment]
Please help me out

**Comment by ZigmundL** [comment]
`BinanceClient.SetDefaultOptions(new BinanceClientOptions()
            {
                ApiCredentials = new ApiCredentials("apikey", "apisecret"),
                LogVerbosity = LogVerbosity.None
            });`

**Comment by hdshivambu** [comment]
> `BinanceClient.SetDefaultOptions(new BinanceClientOptions() { ApiCredentials = new ApiCredentials("apikey", "apisecret"), LogVerbosity = LogVerbosity.None });`

Thanks a lot. you really helped. Now I have open orders, how do i set take profit and stop loss?

**Comment by JKorf** [comment]
Have a look at the api docs
