### ISSUE TITLE
How to get the last buy order for a particular coin?

### ISSUE THREAD

**Issue by orionflame** [JKorf/Binance.Net#686]
Hi,

Basically in my app I want to show the last buy order so I can see the last price I bought a coin. How can I do this? For example for CAKE.

Do I have to randomly try all pairs like CAKE/USDT, CAKE/BUSD, etc and then if there is an order compare their dates?

Thanks a lot in advance.

**Comment by testEntwickler1234** [comment]
Hi!
It's possible that there is a better way but my suggestion would be:
If you know the orderID, use GetOrder(..), if you don't use GetAllOrders(...) and select the last one.
BR

**Comment by orionflame** [comment]
Thanks a lot man it works!
