### ISSUE TITLE
Binance    | Warning | Socket 95 message processing slow (895ms), consider offloading data handling to another thread.

### ISSUE THREAD

**Issue by orionflame** [JKorf/Binance.Net#689]
Hi,

I am getting these warnings, how can I fix these?

2021/04/16 14:32:04:133 | Binance    | Warning | Socket 95 message processing slow (895ms), consider offloading data handling to another thread. Data from this socket may arrive late or not at all if message processing is continuously slow.

My code is basically this:

`
public static void HandleBuyOrder ( BinanceStreamOrderUpdate data )
		{
			if ( data.Status == OrderStatus.Filled || data.Status == OrderStatus.Canceled || data.Status == OrderStatus.New )
			{
				if ( data.QuantityFilled > 0 )
				{
					var pairSymbol = Utility.GetPairSymbol ( data.Symbol );
					if ( pairSymbol != "" )
						MarketData.UpdateStableCoinBalance ( pairSymbol );

					string order = String.Format ( "{0}\t{1}\t{2}\t{3}\t{4}\t{5}", data.Symbol, data.Price, data.QuantityFilled, data.QuoteQuantityFilled, data.OrderId, data.EventTime );
					Utility.AddCoinToOrderLogs ( order, data.OrderId );

					var newAction = new UpdateAction ( UpdateType.NewCoinAdded, data.Symbol );
					Utility.UpdateActions.Enqueue ( newAction );

					Console.WriteLine ( order );
				}
			}
		}

		public static void HandleSellOrder ( BinanceStreamOrderUpdate data )
		{
			if ( data.Status == OrderStatus.Filled || data.Status == OrderStatus.Canceled || data.Status == OrderStatus.New )
			{
				if ( data.QuantityFilled > 0 )
				{
					var pairSymbol = Utility.GetPairSymbol ( data.Symbol );
					if ( pairSymbol != "" )
						MarketData.UpdateStableCoinBalance ( pairSymbol );

					string symbol = Utility.GetBaseSymbol ( data.Symbol );

					var price = Utility.Coins.FirstOrDefault ( c => c.Symbol == symbol )?.Balance.Price;

					var balance = GetBalanceFromAccount ( symbol );
					if ( balance.AvailableAmount * price < 1 )
					{
						Utility.RemoveCoinFromBuyOrderLogs ( symbol );

						var newAction = new UpdateAction ( UpdateType.CoinRemoved, data.Symbol );
						Utility.UpdateActions.Enqueue ( newAction );

						Console.WriteLine ( "{0} : Removed from buy logs", data.Symbol );
					}
				}
			}
		}

		public static void HandleBalanceUpdate ( BinanceStreamBalanceUpdate data )
		{
			Utility.Coins.FirstOrDefault ( c => c.Symbol == data.Asset )?.Balance.UpdateAvailableAmount ( );
		}

		public static async Task SubscribeToSymbolTickerUpdates ( BinanceSocketClient socketClient, ObservableCollection<Coin> coins )
		{
			var symbolPairs = coins.Select ( c => c.SymbolPair ).ToList ( );

			int index = 1;
			foreach ( var coin in coins )
			{
				await Utility.AddNewSubscription ( socketClient, coin );

				Console.WriteLine ( "{0}/{1} : {2}", index, coins.Count, coin.Symbol );
				++index;
			}

			socketClient.Spot.SubscribeToSymbolTickerUpdates ( "BTCUSDT", data =>
			{
				MarketData.BitcoinPriceInUSD = data.LastPrice;
				MarketData.BitcoinPriceChangeDaily = data.PriceChangePercent;
			} );

			var spotListenKey = client.Spot.UserStream.StartUserStreamAsync ( );
			var marginListenKey = client.Margin.UserStream.StartUserStreamAsync ( );

			// Subscribe to a user stream | SPOT account
			socketClient.Spot.SubscribeToUserDataUpdates ( spotListenKey.Result.Data,
				// Order update
				data =>
				{
					// Order update
					string symbol = Utility.GetBaseSymbol ( data.Symbol );
					if ( data.Side == OrderSide.Buy )
						Utility.HandleBuyOrder ( data );
					else if ( data.Side == OrderSide.Sell )
						Utility.HandleSellOrder ( data );

					Utility.Coins.FirstOrDefault ( c => c.Symbol == symbol )?.Balance.UpdateAvailableAmount ( );
				},
				// OCO updates
				null,
				// Position updates
				null,
				// Balance updates
				data =>
				{
					Utility.HandleBalanceUpdate ( data );
				}
				);

			// Subscribe to a user stream | MARGIN account
			socketClient.Spot.SubscribeToUserDataUpdates ( marginListenKey.Result.Data,
				// Order update
				data =>
				{
					string symbol = Utility.GetBaseSymbol ( data.Symbol );
					if ( data.Side == OrderSide.Buy )
						Utility.HandleBuyOrder ( data );
					else if ( data.Side == OrderSide.Sell )
						Utility.HandleSellOrder ( data );

					Utility.Coins.FirstOrDefault ( c => c.Symbol == symbol )?.Balance.UpdateAvailableAmount ( );
				},
				// OCO updates
				null,
				// Position updates
				null,
				// Balance updates
				data =>
				{
					Utility.HandleBalanceUpdate ( data );
				}
				);
		}
`

Should I be removing everything from the subscribe sections but just leave a function call, or is it related to async stuff?

Thanks a lot in advance.

**Comment by JKorf** [comment]
The warning is pretty self explanatory. You should refrain from blocking the update thread for too long. How to do this depends on your implementation. You can add the update to a queue and have a separate task process it, or maybe start a new task to handle the data update. Again, how to handle the data is up to the implementation.
