### ISSUE TITLE
can't get klines of delivery future symbol

### ISSUE THREAD

**Issue by tmdwns7809** [JKorf/Binance.Net#690]
thank you for making this amazing wrapper.

when i get future symbols from            

var a= client.FuturesUsdt.Account.GetAccountInfo();

there is symbols that are not perpetual like BTCUSDT Quarterly0625

It appears that the name is BTCUSDT_210625 from the method 

and when i tried to get kilines from BTCUSDT_210625, i can't make it and if i change it to BTCUSDT210625 is succeed but there is no data.

I tried BTCUSDT0625, BTCUSDTQuarterly210625, BTCUSDTQuarterly0625...

It didn't work.

Could you tell me how to get delivery futures data if you know?

 Thanks

**Comment by tmdwns7809** [comment]
I'm sorry i thought Quarterly futures in usd-m market but it was in coin-m thank you

**Comment by JKorf** [comment]
You can get the symbol names using client.FuturesUsdt.System.GetExchangeInfoAsync(). This contains a list of symbols that is available, with details on each symbol. The name of the symbol returned there should work in other methods.
