### ISSUE TITLE
Since Binance Upgrade last night: GetOrder is returning null

### ISSUE THREAD

**Issue by testEntwickler1234** [JKorf/Binance.Net#692]
**Describe the bug**
Since the upgrade last night the following appears most of times (not every time).
When I'm placing an order with the API by using PlaceOrder and using GetOrder to load it some seconds later, I'm getting "-2013: Order does not exist." Not every time, but most of times this happens.

**To Reproduce**
Binance.Net.BinanceClient binanceClient = new BinanceClient();
binanceClient.SetApiCredentials(API_Key, API_secretKey);
var result = binanceClient.PlaceOrder(Symbol, Buy, StopLossLimit, Amount, NULL, NULL, price, GoodTillCancel, StopPrice).Data;
var order = binanceClient.getOrder(symbol, result.orderID) ;

**Expected behavior**
I except that the function binanceClient.getOrder(symbol, result.orderID) gets the information of the order before. 

**Debug logging**
"-2013: Order does not exist."

Would be great if you can have a look if it's on binance or the Binance.Net-Wrapper. 

BR and thanks

**Comment by nikkozp** [comment]
Hi, its only Binance bug

**Comment by testEntwickler1234** [comment]
Ok, thanks. It's working now again.
