### ISSUE TITLE
How to get Historical Kline Data?

### ISSUE THREAD

**Issue by LaGrange-Group** [JKorf/Binance.Net#693]
**Describe the bug**
I simply cannot find how to get historical data. In the previous version of the package there was a method directly on the BinanceClinet for "GetKlines". 

Where has this be relocated to?

**Comment by JKorf** [comment]
I've moved around the methods to keep the library maintainable while the Binance API grows ever larger. The GetKlines for spot (and other spot market related methods) can now be found at client.Spot.Market.GetKlines
