### ISSUE TITLE
I want to buy and sell a contract at a limit price,And limit the percentage of USDT amount,Then close the position at a certain price.

### ISSUE THREAD

**Issue by GithubZhengYongzhi520** [JKorf/Binance.Net#695]
I want to buy and sell a contract at a limit price,
And limit the percentage of USDT amount,
Then close the position at a certain price,
How should I use it?

My English is very poor, I hope you can understand

**Comment by JKorf** [comment]
This library provides endpoints with which you can interact with the Binance API. You can look at the Binance API docs to see what functionality is available in the API
