### ISSUE TITLE
How to get Yesterday's PNL as well as the 30 days PNL for Spot?

### ISSUE THREAD

**Issue by LaGrange-Group** [JKorf/Binance.Net#699]
Is this a capability of the package? 

I checked all of the account methods under General and was unable to find it. 

I did find "GetDailySpotAccountSnapshot" which returns 4 days of change in BTC value but for my current project I am interested more in USD change rather than BTC change.

Thanks for your replies! This package is amazing!

(I feel bad even asking here as its not an "issue") If this is not a good place to ask this I will close it!

**Comment by sleepymatto** [comment]
This is how I collect yesterdays and today's PNL. Very simple piece of code but should be enough to get you going. The API only returns 1000 entries at a time so if you do high volume trading and you want 30 days worth, you'll need to make multiple requests to the API to get 30 days worth of income history.


  ```
  var client = new BinanceClient();
  DateTime dtYesterday = Convert.ToDateTime(DateTime.UtcNow.ToString("yyyy-MM-dd")).AddDays(-1);
  DateTime dtToday = Convert.ToDateTime(DateTime.UtcNow.ToString("yyyy-MM-dd"));
  decimal yesterdayPnl = 0;
  decimal todayPnl = 0;
  
  var updates = client.FuturesUsdt.GetIncomeHistory(null, "REALIZED_PNL", dtYesterday, null, 1000, null);
  if (updates.Success)
  {
      foreach (var update in updates.Data)
      {
          if (update.Time < dtToday)
          {
              yesterdayPnl += update.Income;
          }
          if (update.Time > dtToday)
          {
              todayPnl += update.Income;
          }
      }
  }
```
