### ISSUE TITLE
Trouble accessing account data through websockets

### ISSUE THREAD

**Issue by prometheus82** [JKorf/Binance.Net#70]
I just can't figure it out what I'm doing wrong here.

successAccount.Success returns True, but messages "???1" and "???2" won't appear no matter what I do

Example:

BinanceClient.SetDefaultOptions(new BinanceClientOptions()
            {
                ApiCredentials = new ApiCredentials(BinanceAPIKey, BinanceAPISecret),
            });

            var socketClient = new BinanceSocketClient();
            string listenKey;

            using (var client = new BinanceClient())
            {
                listenKey = client.StartUserStream().Data.ListenKey;

                var successAccount = socketClient.SubscribeToUserStream(listenKey, data =>
                {
                    // Hanlde account info data
                    MessageBox.Show("???1");
                },
               data =>
               {
                   // Hanlde order update info data
                   MessageBox.Show("???2");                    
                });

                if (successAccount.Success)
                {
                    MessageBox.Show("successAccount.Success: " + successAccount.Success.ToString());
                }                
            }

**Comment by mclean25** [comment]
I think it's because your code is leaving the `using` block. As from the `readme.md`:

```
 // Doesn't leave the using block
using(var client = new BinanceSocketClient())
{
	var successDepth = client.SubscribeToDepthStream("bnbbtc", (data) =>
	{
		// handle data
	});

	Console.ReadLine();
}

// Without using block
var client = new BinanceSocketClient();
client.SubscribeToDepthStream("bnbbtc", (data) =>
{
	// handle data
});
```

**Comment by JKorf** [comment]
@mclean25 that's only true for the socket client, but the socketClient variable is declared outside the using, so that's fine.

 I've ran your code locally and it works for me. Note that you only get an update when something changes. So after running this code go to the Binance website and place an order, you should see the messages.

**Comment by prometheus82** [comment]
Ok I didn't know that, I did what you said and it works now. Thank you for your help.
