### ISSUE TITLE
How get Margin Trading fee

### ISSUE THREAD

**Issue by justicenzy** [JKorf/Binance.Net#701]
please help me get trading fee , old method is not found anymore : B.GetTradeFee(TICKER);

**Comment by JKorf** [comment]
What do you mean is not working anymore?

**Comment by justicenzy** [comment]
> What do you mean is not working anymore?

it's removed in lastest version 6.13 , can't find method , B.GetTradeFee(),  B.Margin.GetTradeFee()  not exist

**Comment by JKorf** [comment]
It is found in client.Spot.Market.GetTradeFeeAsync()
