### ISSUE TITLE
How should i solve Futures order　Code":-1116,"msg":"Invalid id orderType. What went wrong? 

### ISSUE THREAD

**Issue by GithubZhengYongzhi520** [JKorf/Binance.Net#703]
How should i solve
Futures order

""Code":-1116,"msg":"Invalid id orderType. What went wrong? "

This is my code

                foreach (var i in client.FuturesUsdt.Market.GetBookPrices("ADAUSDT").Data.ToArray())
                {
                    client.FuturesCoin.Order.PlaceOrder("ADAUSDT",
                        OrderSide.Buy, OrderType.StopLoss,
                      quantity: 99, PositionSide.Short,
                        TimeInForce.GoodTillCancel, reduceOnly: false, price: i.BestAskPrice, null, stopPrice: i.BestAskPrice - 1, null, null, WorkingType.Contract, null, orderResponseType: OrderResponseType.Result);
                }

**Comment by GithubZhengYongzhi520** [comment]
Hope someone can answer my question,
I just want to simply place a futures order first,
thank you very much.

**Comment by GithubZhengYongzhi520** [comment]
I also tried this setting, but still -1116

    foreach (var i in client.FuturesUsdt.Market.GetBookPrices("ADAUSDT").Data.ToArray())
                {
                    client.FuturesCoin.Order.PlaceOrder("ADAUSDT",
                        OrderSide.Buy, OrderType.StopLoss,
                      quantity: 10, PositionSide.Short,
                        TimeInForce.GoodTillCancel, reduceOnly: false
                        , price:i.BestAskPrice, null, null
                        , null, null, null, null
                        , null);
                }

**Comment by JKorf** [comment]
I think the issue might be that the StopLoss order type is not allowed. You can check the allowed order types using the client.FuturesCoin.System.GetExchangeInfo call.

**Comment by GithubZhengYongzhi520** [comment]
After repeated attempts, this problem has been resolved

    client.FuturesUsdt.Order.PlaceOrder("BTCUSDT",
                                         OrderSide.Buy, OrderType.Limit,
                                       quantity:0.01M, null,
                                         TimeInForce.GoodTillCancel, null
                                         , price: 50000, null, null
                                         , null, null, null
                                         , null);

**Comment by quanghuy9111991** [comment]
I have same error!
When I use Stoploss, it not working. How can I place a Stoploss Order? With "OrderType.Limit" I placed Buy or Sell order, but cannot use "OrderType.StopLossLimit" or "OrderType.StopLoss". Please help me!
![image](https://user-images.githubusercontent.com/26562449/128852246-d295eca3-1c5a-4d25-99ec-05d033c27906.png)
