### ISSUE TITLE
Can I check the latest transaction of a symbol? I want to calculate the current buying and selling volume.

### ISSUE THREAD

**Issue by GithubZhengYongzhi520** [JKorf/Binance.Net#704]
Can I check the latest transaction of a symbol?
I want to calculate the current buying and selling volume.

**Comment by heavymanto** [comment]
like this?
```

 var _ticker = _client.Spot.Market.GetBookPrice(_symbol);
            if (_ticker.Success)
            {
                _exchangeInfo = new ExchangeInfo
                {
                    BestAsk = _ticker.Data.BestAskPrice,
                    BestBid = _ticker.Data.BestBidPrice,
                    BestAskSize = _ticker.Data.BestAskQuantity,
                    BestBidSize = _ticker.Data.BestBidQuantity,
                };

                _exchangeInfo.Fee = _exchange.Fee;
                _exchangeInfo.Name = this.Name.ToString();
            }

```

**Comment by JKorf** [comment]
What info do you mean? If you want the current best ask/offer prices and quantities you can use the `GetBookPrice` call as @heavymanto mentioned. If you want a list of the most recent trades you can use the `GetSymbolTrades` method. 

If you're looking for live updates you can subscribe to the `SubscribeToTradeUpdates` method on the socket client.

**Comment by GithubZhengYongzhi520** [comment]
@JKorf 
@heavymanto 

What I want is the latest order completed by others to calculate the current transaction volume
Can I limit the display to only the latest display?
 
[https://prnt.sc/126adb5](url)

I want to capture the latest completed orders on the URL image one by one
Use this to judge whether the moment may fall or rise

**Comment by GithubZhengYongzhi520** [comment]
@heavymanto
@JKorf 

GetBookPrice is the best order commissioned, but not necessarily the completed order

GetSymbolTrades seems to show too much at once, the time zone I got is studying how to adjust it to suit my country

Maybe use SubscribeToTradeUpdates, but I'm still studying how to use it


I use Google Translate to make my statement as correct as possible. Thank you very much for your answer

**Comment by GithubZhengYongzhi520** [comment]
@heavymanto
@JKorf

I used socketClient.Spot.SubscribeToBookTickerUpdates
It is found that there will be no duplicate results except the results given by Debug, and there will be duplicate results when using Data to return. How to make it return only one?

                   socketClient.Spot.SubscribeToBookTickerUpdates("BTCUSDT", data =>
                    {
                        Lock (Locker1)
                        {
                            Console.WriteLine($"{data.BestAskPrice} {data.BestAskQuantity}");
                        }
                    });

**Comment by heavymanto** [comment]
the implementaion is different by exchange. Binancre terurno only one resulta but other a list of price. 
In general this is the base role

```
  var ASK = Data.Ask.OrderBy(x => x.Price).FirstOrDefault();//MIN ASK
  var BID =  Data.Bid.OrderByDescending(x => x.Price).FirstOrDefault();//MAX BID
```

Or You can use the mehod of IExchangeClient

![image](https://user-images.githubusercontent.com/6449169/116537772-ef8ef500-a8e6-11eb-93ea-27d34cb26261.png)

in specific IExchangeClient.GetTickerAsync(string symbol);
it return

![image](https://user-images.githubusercontent.com/6449169/116537853-10efe100-a8e7-11eb-8753-68d325b43cee.png)

**Comment by GithubZhengYongzhi520** [comment]
@heavymanto 

Thank you very much, I will study how to use this interface

**Comment by GithubZhengYongzhi520** [comment]
https://githubmemory.com/repo/LecksC/CryptoExchange.Net

I found a usage example from here for those who need it
Is studying how to use it

**Comment by GithubZhengYongzhi520** [comment]
I think by calculating the trading volume in a few seconds, maybe I can predict a short-term rise or fall

**Comment by GithubZhengYongzhi520** [comment]
I try to use CryptoExchange.Net.ExchangeInterfaces
But it's not better

**Comment by GithubZhengYongzhi520** [comment]
This is my final result, although I am not sure if the return repeat is correct

  var socketClient = new BinanceSocketClient();
                ArrayList Coin = new ArrayList(2);
                Coin.Add("DOGEUSDT");
                Coin.Add("BTCUSDT");
                IEnumerable<string> s1 = Coin.Cast<string>();
            socketClient.Spot.SubscribeToTradeUpdates(s1, data =>
            {
                Console.WriteLine($"{data.Price} {data.Quantity} {data.IsBestMatch} {data.BuyerIsMaker}");
            });

**Comment by GithubZhengYongzhi520** [comment]
This is my final result, although I am not sure if the return repeat is correct


![image](https://user-images.githubusercontent.com/83016217/116644644-7f47a880-a9a6-11eb-9742-afb7343d78d6.png)
