### ISSUE TITLE
[281] Request Timed Out

### ISSUE THREAD

**Issue by MarcelloBugnoli** [JKorf/Binance.Net#706]
Hello everyone,
I tried to place a sell order using the following code:

`
{
var placeResult = client.Spot.Order.PlaceOrder(
                    symbol: Symbol,
                    side: side,
                    type: type,
                    quantity: qty,
                    newClientOrderId: clientOrderId,
                    price: limit,
                    timeInForce: tif,
                    stopPrice: stop);

                if (!placeResult.Success)
                {
                    throw new Exception($"PlaceOrder error: {placeResult.Error.Message}");
                }
}
`

but, after about 30s the request timed out (as you can see from the title).
The point being, i can't find this [281] error code anywhere, both on Binance and this library.

The application was running on a AWS EC2 instance, that's why i'm opening this issue, i wasn't expecting it to happen, and it's quite hard to reproduce in this environment.

Please let me know if i can be of further help.

You can find the log attached.
[client.log](https://github.com/JKorf/Binance.Net/files/6382723/client.log)

Thanks in advance.

**Comment by heavymanto** [comment]
can specify argument pass? check the required data based on the type of the order

**Comment by MarcelloBugnoli** [comment]
Sure, here's the arguments:

symbol: ETHUSDT,
side: Sell,
type: Limit,
quantity: 9.71,
newClientOrderId: {client id},
price: {calculated in real time},
timeInForce: GTC

**Comment by JKorf** [comment]
The 281 number isn't the error code, it's a unique Identifier for the request, generated  by this library to make it easier to track log messages per request. There is no additional info available as the server has never returned any data in response to the request. 

As to why the request would timeout I can't help you with that I'm afraid.

**Comment by MarcelloBugnoli** [comment]
I see, I thought that it was an error code.
I'll look into it, if it ever happens again.

Thanks everyone.
