### ISSUE TITLE
I think that using DateTime as a parameter wrong selection...

### ISSUE THREAD

**Issue by dengere** [JKorf/Binance.Net#708]
**Describe the bug**
Binance Client could be any timezone, so many functions signed with DateTime parameter instead of DateTimeOfset...

**To Reproduce**
DateTime.Now (produce 18:00:00 in Turkey, produce 21:00 in Netherland) 

**Expected behavior**
DateTimeOffset.UtcNow better choice.

**Comment by JKorf** [comment]
DateTime.UtcNow is used, which is refers to the same point in time as DateTimeOffset.UtcNow. Are you having any issues?
