### ISSUE TITLE
Web Error: No Response from server

### ISSUE THREAD

**Issue by Cjay93** [JKorf/Binance.Net#71]
I get this error logging into binance with api keys.
Any ideas on what it is, this is only on some users pcs but on someones vps they got this error.

Thanks Jkorf

**Comment by JKorf** [comment]
It basically means the server couldn't be reached. Are they maybe using a proxy?

**Comment by Cjay93** [comment]
You mean a proxy on there vps?

**Comment by JKorf** [comment]
Yes? Is it possible to ping the binance server wherever you get this?

**Comment by Cjay93** [comment]
No cant ping, also no proxy.

**Comment by Cjay93** [comment]
ok let me double check ping, think is all the other part of the app works which is all internet based, only thing that doesnt is the biniance part.

**Comment by Cjay93** [comment]
![image](https://user-images.githubusercontent.com/31392716/38859700-8112c220-4226-11e8-9c19-9ca7259c1411.png)


I set the debug output to a console and this is what happens, so weird.

**Comment by JKorf** [comment]
Can you try installing the latest version? It has a little extra logging when there is no server response.

**Comment by Cjay93** [comment]
Nice that update gave me a little more info to work with.

![image](https://user-images.githubusercontent.com/31392716/38864527-e9ae613e-4232-11e8-9192-933102bec549.png)

Still not sure though.

**Comment by JKorf** [comment]
Add this to the start of your program:
'ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;'
I'm pretty sure that fixes it.

**Comment by Cjay93** [comment]
wow, no stop help from you, thanks so much jkorf.
