### ISSUE TITLE
Futures - strange error

### ISSUE THREAD

**Issue by jurgenBE** [JKorf/Binance.Net#710]
Hi, I today wanted to try futures, so i first updated the binance and cryptoexchange nuget to the latest updates, and then i tried a simple thing : get exchangeinfo but i got an error , then i tried another simple method to get the bookprice  

![image](https://user-images.githubusercontent.com/10328935/116400214-1509f900-a82a-11eb-9076-e1c5d1300c4b.png)

it seems something in the cryptoexchange.net but i don't know what to do next...

**Comment by jurgenBE** [comment]
OK, i just reverted binance.net to 6.13.1 and cryptoexchange to 3.8.1 and then it works, so i think it's something with the nuget updates... too difficult for me..

**Comment by JKorf** [comment]
Generally speaking you'll want to stick with the CryptoExchange.Net nuget package which is referenced in the Binance.Net project. So for version Binance.Net 6.13.1 that is CryptoExchange.Net version 6.8.1. I'm currently in the process of updating all the packages to CryptoExchange 6.9.0, during this small timeframe there might be some errors when updating all packages to the latest version.
So in short:

If you use multiple CryptoExchange.Net implementations and you just updated to the latest version you were a bit unlucky with your timing, try installing the latest version again in an hour.

If you're only using Binance.Net stick to the CryptoExchange.Net referenced by the project.
