### ISSUE TITLE
Websocket subscription via proxy not working

### ISSUE THREAD

**Issue by AmyPond99** [JKorf/Binance.Net#711]
Hi.
I ran into an issue when tried to subscribe to kline updates (also tested ticker updates - same result) via proxy.
The error message received: "Can't connect to the server".

Log output:

2021/04/28 16:40:08:979 | Binance    | Debug | Client configuration: LogVerbosity: Debug, Writers: 1, Credentials: Set, BaseAddress: https://api.binance.com/, Proxy: http://xx.xxx.xxx.xxx, RateLimiters: 0, RateLimitBehaviour: Wait, RequestTimeout: 00:00:30                                                                                                        
2021/04/28 16:40:09:034 | Binance    | Debug | Client configuration: LogVerbosity: Debug, Writers: 1, Credentials: Set, BaseAddress: wss://stream.binance.com:9443/, Proxy: xx.xxx.xxx.xxx, AutoReconnect: True, ReconnectInterval: 00:00:05, SocketResponseTimeout: 00:00:10, SocketSubscriptionsCombineTarget:                                                        
2021/04/28 16:40:09:104 | Binance    | Debug | Created new socket for wss://stream.binance.com:9443/stream?streams=btcusdt@kline_1h                                                                                                             
2021/04/28 16:40:09:167 | Binance    | Debug | Socket 1 connecting                                                      
2021/04/28 16:40:09:564 | Binance    | Info | Socket 1 error: System.Exception: proxy error                              
---> System.Exception: receive buffer size has been exceeded                                                              
--- End of inner exception stack trace ---                                                                           
2021/04/28 16:40:09:565 | Binance    | Debug | Socket 1 connection failed, state: Closed                                
2021/04/28 16:40:09:574 | Binance    | Debug | Socket 1 disposing websocket                                             
2021/04/28 16:40:09:576 | Binance    | Info | Socket 1 closed 

Sample code:
`BinanceSocketClientOptions BinanceSocketClientOptions = new BinanceSocketClientOptions();`
`BinanceSocketClientOptions.LogVerbosity = LogVerbosity.Debug;`
`BinanceSocketClientOptions.LogWriters = new List<TextWriter> { Console.Out };`
`BinanceSocketClientOptions.ApiCredentials = new ApiCredentials("xxx", "xxx");`
`BinanceSocketClientOptions.Proxy =  new ApiProxy(host: "xxx", port: xxxx, login: "xxx", password: "xxx");`
`BinanceSocketClient SocketClient = new BinanceSocketClient(options: BinanceSocketClientOptions);`
`var subscriptionRes = await SocketClient.Spot.SubscribeToKlineUpdatesAsync("BTCUSDT",KlineInterval.OneHour, data =>`
`{`
    `Debug.WriteLine($"{data.Symbol}, last price: {data.Data.Close}");`
`});`

Proxy is working and has been tested.
It seems to be more likely an issue of the dependency - websocket4net.
Can you help with any workaround?
Huge thanks in advance.

**Comment by JKorf** [comment]
The websocket implementation is using the WebSocket4Net library, which by now is a bit dated and doesn't seem to work too well with proxies. 
I've created a beta version which uses the native dotnet ClientWebSocket, can you try that? You'll need to update Binance.Net to 3.14.0-beta1, and manually install CryptoExchange.Net 4.0.0-beta3.

**Comment by AmyPond99** [comment]
Works perfectly, warmest thanks.
(Guess you meant 6.14.0-beta1 version for future reference)

**Comment by JKorf** [comment]
Sorry yes, 6.14.0-beta1. Good to hear. I'll keep it in beta for some time while also testing it myself and will merge it into the stable version later on. Let met know if you have any issues.

**Comment by hyperms** [comment]
Hi
I have this problem too.
The error message received: "Can't connect to the server".
