### ISSUE TITLE
PlaceOrder throwing exception "Unable to read data from the transport connection: Connection reset by peer."

### ISSUE THREAD

**Issue by MateusAngelo97** [JKorf/Binance.Net#712]
Both Spot and Futures objects are throwing an exception on PlaceOrder() Method, this happens once every 10-20 orders. 

I have a trading bot (at least 8 months old) and didn`t touch a single line of code, I simply updated it from version 6.8.0 to 6.13.2, then it started happening.

Tell me if I can provide any other info in order to help.

**Comment by JKorf** [comment]
Connection reset just means the connection to the server was broken while waiting on the response for a request. I don't suspect it's an issue with the library, though you could check this by switching back to 6.8.0, make sure it doesn't happen and switch to 6.13.2 and check that it is happening again. 

But again, this just seems like a hickup in the connection, not an issue in the library.
