### ISSUE TITLE
Futures - close immedietaly position by market 

### ISSUE THREAD

**Issue by Adamszsz** [JKorf/Binance.Net#713]
I just can't figure how can i close position?  For example i have open position and want to close it by market price.
How can i do it ? 

I try searhch by client.FuturesUsdt.GetPositionInformation and close position but can't figure it out.
How can i get id of specific position and close is by market price?  or just modify opened position and change stop limit?

**Comment by JKorf** [comment]
See response as #727

**Comment by techno2mahi** [comment]
You have to place an opposite new order of that position quantity. if for Buy order place a SELL order.
