### ISSUE TITLE
I used the socket Client.Spot.SubscribeToBookTicker Updates and it repeated the result. How to make it return only one? It seems too fast. I'm not sure if this result is correct. Can it show exactly the same results as Exchange? How should I verify that it is a valid order?

### ISSUE THREAD

**Issue by GithubZhengYongzhi520** [JKorf/Binance.Net#714]
I used the socket Client.Spot.SubscribeToBookTicker Updates and it repeated the result. How to make it return only one? It seems too fast. I'm not sure if this result is correct. Can it show exactly the same results as Exchange?

Are there really so many duplicate results?

How should I verify that it is a valid order?

             var socketClient = new BinanceSocketClient();
                var socketClient1 = new BinanceSocketClient();
                var socketClient2 = new BinanceSocketClient();
                socketClient.Spot.SubscribeToBookTickerUpdates("BTCUSDT", data =>
                {
                    Console.WriteLine($"{data.BestAskPrice}\t{data.BestAskQuantity}\t{data.BestAskPrice * data.BestAskQuantity}");
                });

                socketClient1.FuturesUsdt.SubscribeToBookTickerUpdates("BTCUSDT", data =>
                {

                    //Console.WriteLine($"{data.BestAskPrice}\t{data.BestAskQuantity}\t{data.BestAskPrice * data.BestAskQuantity}");
                });

                socketClient2.FuturesCoin.SubscribeToBookTickerUpdates("BTCUSD_PERP", data =>
                {
                    //Console.WriteLine($"{data.BestAskPrice}\t{data.BestAskQuantity}\t{data.BestAskPrice * data.BestAskQuantity}");
                });

![image](https://user-images.githubusercontent.com/83016217/116647448-2596ac80-a9ad-11eb-8f69-f96a8face28b.png)

![image](https://user-images.githubusercontent.com/83016217/116648565-f0d82480-a9af-11eb-85c7-7357e7f75256.png)

![image](https://user-images.githubusercontent.com/83016217/116649340-a22b8a00-a9b1-11eb-9bfa-67c05aff6110.png)

![image](https://user-images.githubusercontent.com/83016217/116649690-76f56a80-a9b2-11eb-982f-2eedfbf6c14e.png)

**Comment by GithubZhengYongzhi520** [comment]
I found that the debugging results will be repeated. How are they exactly the same as the results provided by the exchange?

**Comment by GithubZhengYongzhi520** [comment]
The speed seems to be too fast, while capturing duplicate results

**Comment by JKorf** [comment]
You get duplicate lines because you do a writeline every time you get an update, however the ticker provides more data than just the best ask/bid price. So if anything else changes while the best bid/ask price stays the same you'll still get an update and it will get the same best ask/bid. 
A solution for this would for example be keeping track of the last best bid/ask and don't do a writeline if a new update has te same values as the last.
