### ISSUE TITLE
Websocket suddenly stops

### ISSUE THREAD

**Issue by blahblehblah** [JKorf/Binance.Net#715]
Websocket randomly stops with no reason what so ever, it just stops passing values after updating to latest version of Binance nuget package.

I checked logs, and everything. nothing happens... it just stops

**Comment by JKorf** [comment]
With the latest you mean the beta version? Have you installed the CryptoExchange.Net 4.0.0-beta3 with it?

**Comment by blahblehblah** [comment]
No actually the latest stable one which is 6.13.3, this has caused issues with websocket's data, after 2 hours i was surprised that it stopped getting data out of no where, just reverted back to 6.13.1, been running for almost 6 hours now no issues so far.

**Comment by JKorf** [comment]
I don't  see any  changes between 6.13.3 and  6.13.1 which could explain this. Was this on the user stream? If so, are you sending a keep alive for the listen key every < 60 minutes?

**Comment by orionflame** [comment]
it happens to me too, i see price updates but it stops receiving updates on spot and margin streams that when i buy and sell, it doesn't trigger the proper actions. so then i have to restart the app, then it works again for a while.

how can i send keep alive?

**Comment by JKorf** [comment]
The keep alive is only needed for streams that take a listen key ( the `StartUserStream` calls ). It is advised to call `KeepAliveUserStream` on the rest client every 30 minutes with the listen key used to call `SubscribeToUserDataUpdates`.

**Comment by blahblehblah** [comment]
This happens when listening to futures stream, anyway i believe this is an ISP issue and not really related to this library, as i've tested it on multiple environments and can confirm it works awesome.

thank you - closing this.

**Comment by orionflame** [comment]
Oh I see, I am using:
socketClient.Spot.SubscribeToUserDataUpdates ( spotListenKey.Result.Data,

so I have listen keys.

I tried to find that KeepAliveUserStream function but I couldn't find it. Is it supposed to be on the socketClient?


Thanks a lot.

**Comment by salocinx** [comment]
> Oh I see, I am using:
> socketClient.Spot.SubscribeToUserDataUpdates ( spotListenKey.Result.Data,
> 
> so I have listen keys.
> 
> I tried to find that KeepAliveUserStream function but I couldn't find it. Is it supposed to be on the socketClient?
> 
> Thanks a lot.

Having same issue? Is there an actual `KeepAliveUserStream` function that can be called every 30 minutes or do I have to accomplish this in another way?

**Comment by salocinx** [comment]
I found it: client.Spot.UserStream.KeepAliveUserStream(key)
