### ISSUE TITLE
Price not increased by tick size error.

### ISSUE THREAD

**Issue by PatriQ94** [JKorf/Binance.Net#716]
**Describe the bug**
As of today, 01/05/2021, I've started receiving errors "4014: Price not increased by tick size." when trying to place an order using 
``client.FuturesUsdt.Order.PlaceOrderAsync`` function with symbol ANKRUSDT. A few days ago, Binance release an update on some of the pairs about changing tick size (https://www.binance.com/en/support/announcement/12b1f181fcc74847b5419b29bddf239f?ref=JLI1VBLA&utm_source=BinanceTwitter&utm_medium=GlobalSocial&utm_campaign=GlobalSocial). These exact pairs started throwing the above mentioned errors when trying to buy them and I have zero clue why because the ``PlaceOrderAsync`` doesn't need tick size parameters anyways, so I have no clue what would be the cause of this error. 

**To Reproduce**
Place order with ``FuturesUsdt.Order.PlaceOrderAsync`` for symbol "ANKRUSDT", side "Buy" and type "Limit", for quantity I simply do something like ``Math.Round(quantityValue, symbol.QuantityPrecision)``, similar with the price so ``Math.Round(priceValue, symbol.PricePrecision)`` and WorkingType is set to Contract.

**Expected behavior**
A normally placed order.

**Comment by JKorf** [comment]
The error would be in the price parameter. The tick size is the minimum step the price can change up or down. So when a coin has step size 0.01 and the price is 5.50, the next accepted prices are 5.51 and 5.49. If you send a price of 5.501, you'll get an error. The tick size is returned in the GetExchangeInfo call.

**Comment by PatriQ94** [comment]
> The error would be in the price parameter. The tick size is the minimum step the price can change up or down. So when a coin has step size 0.01 and the price is 5.50, the next accepted prices are 5.51 and 5.49. If you send a price of 5.501, you'll get an error. The tick size is returned in the GetExchangeInfo call.

Aha I see. So can I use the ``BinanceHelpers.FloorPrice(tickSize, price)`` to successfuly round prices and post them?

**Comment by JKorf** [comment]
Yup that should work
