### ISSUE TITLE
client.Margin.GetMarginAccountInfo(); Return 404 NotFound

### ISSUE THREAD

**Issue by MesutFi** [JKorf/Binance.Net#717]
Hello there,

Thank you for this support.

var a = client.Margin.GetMarginAccountInfo ();
When I want to get my Margin account information, I get the following error;
Error.Code: 404
Error.Message: Deserialize JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0., Path:, LineNumber: 0, LinePosition: 0

I've done some research and when I query postman and api, I can get margin information.
{{url}} / sapi / v1 / margin / account? timestamp = {{timestamp}} & signature = {{signature}}

When I review the Binance Api Documents;
(https://binance-docs.github.io/apidocs/spot/en/#query-cross-margin-account-details-user_data)

I saw that you wanted a mandatory timestamp.

I don't know where I went wrong.

Note:
My Margin account is active.
I made a transfer to a Margin account.
I chose margin in API `settings.`
![Ekran Alıntısı](https://user-images.githubusercontent.com/44943547/116824233-d2ca1a00-ab91-11eb-8951-ef72769f4731.png)
``

**Comment by JKorf** [comment]
It seems to work fine for me. Can you enable debug logging and check what that says?

Enable debug logging like this:
````C#
BinanceClient.SetDefaultOptions(new BinanceClientOptions{
    LogVerbosity = LogVerbosity.Debug
});
````

**Comment by MesutFi** [comment]
I'm sorry for the delay.
I tried both binance.com and binance.cc for the BaseAddress parameter. I can get my Spot account information in two parameters, but I am getting 404 for a Margin account.

`2021.05.14 16:11:49:175 | Binance    | Debug | [4] Creating request for https://www.binance.com/sapi/v1/margin/account
2021.05.14 16:11:49:177 | Binance    | Debug | [4] Sending GET signed request to https://www.binance.com/sapi/v1/margin/account?timestamp=1620997909174&recvWindow=5000&signature=49D3CFC32F839A04C23E367DFB4E2B254A5408928E34E98F3509764A82A8731D 
'BinanceAPI.ClientConsole.exe' (CLR v4.0.30319: BinanceAPI.ClientConsole.exe): 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.resources\v4.0_4.0.0.0_tr_b77a5c561934e089\System.resources.dll' yüklendi. Modül semboller olmadan üretildi.
2021.05.14 16:11:49:491 | Binance    | Debug | [4] Error received: <!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="format-detection" content="telephone=no,email=no,address=no" />
    <script src="https://bin.bnbstatic.com/static/sensors/sensorsdata@1.15.1.min.js"></script>
    <title>Binance</title>
    <link rel="shortcut icon" type="image/x-icon" href="https://bin.bnbstatic.com/static/images/common/favicon.ico">
    <style>
      html,
      body {
        font-family: BinancePlex, Arial, PingFangSC-Regular, "Microsoft YaHei",
          sans-serif;
      }
      body {
        margin: 0;
      }
      .not-fount-container {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
        flex-direction: column;
        background: #fafafa;
      }
      .not-fount-image {
        width: 340px;
      }
      .not-fount-tips {
        margin-top: 65px;
        display: flex;
        align-items: center;
      }
      .not-fount-tips-bold {
        font-size: 24px;
        line-height: 28px;
        color: #1e2026;
        font-weight: 500;
      }
      .link {
        color: #d0980b;
        font-size: 14px;
        line-height: 20px;
      }
      img {
        width: 100%;
        display: block;
      }
      .not-found-board-logo {
        width: 56px;
      }
      .not-found-board-left {
        display: flex;
      }
      .not-found-board-text {
        margin-left: 16px;
        color: #1e2026;
        font-weight: bold;
        margin-top: 6px;
        font-size: 16px;
      }
      .not-found-board-text-inner {
        display: flex;
      }
      .text-inner-icons {
        margin-left: 16px;
        display: flex;
        align-items: center;
      }
      .text-inner-icons span {
        display: inline-block;
        width: 16px;
        height: 16px;
        margin-right: 10px;
        background-position: center;
        background-repeat: no-repeat;
      }
      .icon-mac {
        background-image: url("https://bin.bnbstatic.com/static/images/electron/macicon.svg");
      }
      .icon-linux {
        background-image: url("https://bin.bnbstatic.com/static/images/electron/linux.svg");
      }
      .icon-windows {
        background-image: url("https://bin.bnbstatic.com/static/images/electron/windows.svg");
      }
      .not-found-board-right {
        margin-top: 6px;
      }
      button {
        padding: 10px 16px;
        border: none;
        outline: none;
        background: linear-gradient(180deg, #f8d12f 0%, #f0b90b 100%);
        border-radius: 4px;
        cursor: pointer;
        font-size: 14px;
        color: #1e2026;
        font-weight: 500;
      }
      @media only screen and (max-device-width: 1024px) {
        .not-found-board {
          display: none;
        }
      }
      @media only screen and (min-device-width: 1025px) {
        .not-found-board {
          background: #ffffff;
          padding: 0 16px;
          height: 80px;
          box-shadow: 0px 0px 1px rgba(20, 21, 26, 0.1),
            0px 3px 6px rgba(71, 77, 87, 0.04),
            0px 1px 2px rgba(20, 21, 26, 0.04);
          border-radius: 4px;
          width: 496px;
          margin-top: 56px;
          display: flex;
          justify-content: space-between;
          align-items: center;
        }
      }
    </style>
  </head>
  <body>
    <div class="not-fount-container">
      <div class="not-fount-image">
        <img
          width="100%"
          src="https://bin.bnbstatic.com/static/images/electron/404-error.png"
          alt=""
        />
      </div>
      <div class="not-fount-tips">
        <span class="not-fount-tips-bold"
          >Sorry! The page you’re looking for cannot be found.</span
        >
        <span style="margin-left: 16px"
          ><a href="/" class="link"
            >Go to Homepage</a
          ></span
        >
      </div>
      <div class="not-found-board">
        <div class="not-found-board-left">
          <div class="not-found-board-logo">
            <img
              src="https://bin.bnbstatic.com/static/images/electron/logo_01.png"
              alt=""
            />
          </div>
          <div class="not-found-board-text">
            <div class="not-found-board-text-inner">
              <div>Binance desktop</div>
              <div class="text-inner-icons">
                <span class="icon-windows"></span>
                <span class="icon-linux"></span>
                <span class="icon-mac"></span>
              </div>
            </div>
            <div
              style="
                font-size: 14px;
                color: #474d57;
                font-weight: 400;
                margin-top: 6px;
              "
            >
              A secure, fast and smooth trading experience.
            </div>
          </div>
        </div>
        <div class="not-found-board-right">
          <button id="njewuisj-404-desktop-download">Download Now</button>
        </div>
      </div>
    </div>
    <script>
      window.sensors = window["sensorsDataAnalytic201505"];
      if (sensors) {
        sensors.init({
          show_log: false,
          name: "sensors",
          server_url: "https://sensors.binance.cloud/sa?project=binance",
          heatmap: {
            // collect_elements: "all",
          },
          heatmap_url:
            "https://bin.bnbstatic.com/static/sensorsdata/heatmap.min.js",
          batch_send: false,
          send_type: "beacon",
          callback_timeout: 2000,
        });
        sensors.quick("autoTrack", {
          canary: "beta",
        });
      }
      window.onload = function () {
        var downloadBtn = document.getElementById(
          "njewuisj-404-desktop-download"
        );
        var p = navigator.platform;
        var isMac = p.indexOf("Mac") == 0;
        var isWin = p.indexOf("Win") == 0;
        var isLinux = p == "X11" || p.indexOf("Linux") == 0;
        downloadBtn.addEventListener("click", function () {
          if (isMac) {
            window.location.href =
              "https://ftp.binance.com/electron-desktop/mac/production/binance.dmg";
          }
          if (isWin) {
            window.location.href =
              "https://ftp.binance.com/electron-desktop/windows/production/binance-setup.exe";
          }
          if (isLinux) {
            window.location.href =
              "https://ftp.binance.com/electron-desktop/linux/production/binance-x86_64-linux.rpm";
          }
        });
      };
    </script>
  </body>
</html>

`

**Comment by JKorf** [comment]
Seems like you're sending the request to https://www.binance.com instead of https://api.binance.com. Make sure the BaseAddress is correct.
