### ISSUE TITLE
FuturesUsdt.UserStream.StartUserStream error "No value provided for parameter..."

### ISSUE THREAD

**Issue by tinngv** [JKorf/Binance.Net#719]
I try to subcribe futures user data update with this code 
` var client = GetBinanceClient();
            var startResult = client.FuturesUsdt.UserStream.StartUserStream();

            await client.FuturesUsdt.UserStream.KeepAliveUserStreamAsync(startResult.Data, ct: cancellationToken);

            if (!startResult.Success) //error throw in this code
                throw new Exception($"Failed to start user stream: {startResult.Error}");

            _listenKey = startResult.Data;
            var socketClient = new BinanceSocketClient();

            socketClient.FuturesUsdt.SubscribeToUserDataUpdates(_listenKey,
                data =>
                {
                    _logger.LogInformation("Leverage" + data.Dump());        
                },
                data => { _logger.LogInformation("Leverage update" + data.Dump()); },
                data => { _logger.LogInformation("Margin update" + data.Dump()); },
                data => { _logger.LogInformation("Account update" + data.Dump()); },
                data => { _logger.LogInformation("Order update" + data.Dump()); });`

but when run, it throw an error

`No value provided for parameter listenKey (Parameter 'listenKey')

System.ArgumentException: No value provided for parameter listenKey (Parameter 'listenKey')
   at CryptoExchange.Net.ExtensionMethods.ValidateNotNull(String value, String argumentName)
   at Binance.Net.SubClients.Futures.BinanceClientFuturesUserStream.KeepAliveUserStreamAsync(String listenKey, CancellationToken ct)...`

Please help.

**Comment by JKorf** [comment]
Seems like there  is no listenkey returned. Can you check what the `.Data` and `.Error` of `startResult` is?

**Comment by tinngv** [comment]
This occurs due to I create API Key before open futures account. Delete api key and re-create -> everything go well.
![image](https://user-images.githubusercontent.com/1137682/116884451-f1dbb100-ac50-11eb-9960-d1a9836e8853.png)
