### ISSUE TITLE
Do not use STOP_MARKET、TAKE_PROFIT_MARKET，Can I close the position directly at the market price?

### ISSUE THREAD

**Issue by GithubZhengYongzhi520** [JKorf/Binance.Net#720]
Do not use STOP_MARKET、TAKE_PROFIT_MARKET
Can I close the position directly at the market price?

I designed a shortcut key. I want to close a position with one click, and then enter a new contract with one click. If the price limit is not closed, the speed may be affected.

Please help me, thank you

-----------------------------------------------------------------------------------
client.FuturesUsdt.Order.PlaceOrder("ETHUSDT",
                OrderSide.Buy,
                OrderType.Limit,
                quantity: amount, PositionSide.Short,
                price: LimitPrice, timeInForce: TimeInForce.GoodTillCancel);
------------------------------------------------------------------------------------

client.FuturesUsdt.Order.PlaceOrder("ETHUSDT",
                OrderSide.Buy,OrderType.Market, null,PositionSide.Short, null, null, null, null,null, closePosition:true);

![image](https://user-images.githubusercontent.com/83016217/116930886-ec9f5600-ac92-11eb-88ff-728c608322df.png)

![image](https://user-images.githubusercontent.com/83016217/116932068-65eb7880-ac94-11eb-8c22-695f3f9cb9ca.png)

Is there any way to close the position at the market price?

**Comment by Adamszsz** [comment]
i have the same question...
Also it is possible to PlaceOrder with stop loss or take profit value? 
Or how can i set it later when position is opened?

**Comment by tiodor** [comment]
@Adamszsz 
looking at the source, it definitely looks possible, but I think that you have to set workingType and closePosition:

        //   stopPrice:
        //     Used with STOP/STOP_MARKET or TAKE_PROFIT/TAKE_PROFIT_MARKET orders.
        //
        //   activationPrice:
        //     Used with TRAILING_STOP_MARKET orders, default as the latest price（supporting
        //     different workingType)
        //
        //   callbackRate:
        //     Used with TRAILING_STOP_MARKET orders
        //
        //   closePosition:
        //     Close-All，used with STOP_MARKET or TAKE_PROFIT_MARKET.
        //
        //   workingType:
        //     stopPrice triggered by: "MARK_PRICE", "CONTRACT_PRICE"

**Comment by basarkavas** [comment]
same issue

**Comment by yellow444** [comment]
very strange I place a normal market order `(symbol: orderSymbol, side: side, type: FuturesOrderType.Market, quantity: quantity, positionSide: null /*PositionSide.Both*/, closePosition: null, receiveWindow: receiveWindow)` then I create a TakeProfitMarket  `(symbol: orderSymbol, side: orderSide, type: FuturesOrderType.TakeProfitMarket, quantity: null /*rec.Vol*/, positionSide: null /*PositionSide.Both*/, stopPrice: stopPrice, closePosition: true, receiveWindow: receiveWindow)` but it executes like a normal market order

**Comment by JKorf** [comment]
Cleaning up old issues, if you feel this issue is still relevant feel free to comment
