### ISSUE TITLE
Get All Position and All OpenOrder 

### ISSUE THREAD

**Issue by moslem7026** [JKorf/Binance.Net#721]
`client.FuturesUsdt.Order.GetAllOrders();` for useing this mehtod parameter symbole should defined , how is it possible to get all order with no filter on one symbol?

**Comment by JKorf** [comment]
As far as I'm aware this is only available on a per symbol basis.

**Comment by moslem7026** [comment]
so , it is not possible to show open order list ?!

**Comment by JKorf** [comment]
It is if you keep track of the orders yourself. Use the SubscribeToUserDataUpdates on the socket client to subscribe to changes on orders. When you place an order, you'll get an update, so it's fairly easy to manage your own in-memory orders list, but I don't believe it is possible to get all open orders for all symbols no.
