### ISSUE TITLE
PlaceOrder Trailing stop throw  null error 

### ISSUE THREAD

**Issue by moslem7026** [JKorf/Binance.Net#723]
I want to place `TrailingStop` order 

` client.FuturesUsdt.Order.PlaceOrder(
                                ObjLimitOrder.symbol,
                                Binance.Net.Enums.OrderSide.Buy,
                                Binance.Net.Enums.OrderType.TrailingStopMarket,
                                OpenOrder.OriginalQuantity,
                                Binance.Net.Enums.PositionSide.Both,
                                Binance.Net.Enums.TimeInForce.GoodTillCancel,
                                false,
                                null, null, null, ActivePrice, 0.1M`
it show error 'OpenOrder' is null

**Comment by JKorf** [comment]
Not an issue with the library, your OpenOrder object is null, and you're not showing any info where that is coming from
