### ISSUE TITLE
Terminology clarification 

### ISSUE THREAD

**Issue by tiodor** [JKorf/Binance.Net#724]
Hi All,

is there any information describing OrderTypes/SideEffectTypes and some other parameters such as stopPrice and icebergQuantity?

Some kind of exemplary application will be much appreciated, i.e. application that can place order with STOP LOSS and TAKE PROFIT parameters included. Even a code part covering aforementioned use case will help a lot in library understanding.

**Comment by HypsyNZ** [comment]
[Order Types](https://github.com/JKorf/Binance.Net/blob/9e3572dc68a36e4680f22e130e63e5e6ddf06cb2/Binance.Net/Enums/OrderType.cs)

[Side Effect Type](https://github.com/JKorf/Binance.Net/blob/9e3572dc68a36e4680f22e130e63e5e6ddf06cb2/Binance.Net/Enums/SideEffectType.cs)

[Public API Definitions](https://binance-docs.github.io/apidocs/spot/en/#public-api-definitions)

**Comment by JKorf** [comment]
Documentation will be improved in next version, but as already mentioned, the definitions are available in the API documentation or even with a search. (most definitions aren't bound to Binance but are more widely used in trading)
