### ISSUE TITLE
.Net Core Web Project API microservice questions websockets and client calls

### ISSUE THREAD

**Issue by ExceedingLife** [JKorf/Binance.Net#725]
Hello,
I have a WPF project that works with this old version. Now I want to upgrade to a microservice (my first microservice I’m building.) I added cryptoexchange and the binance.net library to my project. At first I added the newest one and it wouldn’t let me do any trades, then I added the older version that I have in my WPF project, cryptoexchance 3.0.11 and I believe binance.net is 4.3 I wanna say. But not positive.
I have the code to do an API place order but when I have the newest version it doesn’t find the ‘.spot.order’ part of the class.
My main question here is how do I setup websockets with an API then I have a .net core MVC UI that I want the websockets to update the values on (current price).
I’m not sure how to open a connection on an api and send data to the UI continous. I usually send API calls back and forth, UI calls httpclient with a post/get/patch and api sends a OK/BadRequest/NotFound with data back to the ui.
How would this work with a websocket?
Thank you

```
`        [HttpPost("CreateStopOrderSell")]
        public async Task<IActionResult> CreateStopOrderSell(StopOrderVM model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    using (var client = _binanceClient)
                    {
                        var orderResult = await _binanceClient.PlaceOrderAsync(symbol: model.TradeSymbol,
                                                                            side: OrderSide.Sell,
                                                                            type: OrderType.StopLossLimit,
                                                                            quantity: model.CryptoAmount,
                                                                            price: model.LimitPrice,
                                                                            timeInForce: TimeInForce.GoodTillCancel,
                                                                            stopPrice: model.StopPrice,
                                                                            orderResponseType: OrderResponseType.Full);
                        //var orderResult = await _binanceClient.Spot.Order.PlaceOrderAsync(symbol: model.TradeSymbol,
                        //                                                    side: OrderSide.Sell,
                        //                                                    type: OrderType.StopLossLimit,
                        //                                                    quantity: model.CryptoAmount,
                        //                                                    price: model.LimitPrice,
                        //                                                    timeInForce: TimeInForce.GoodTillCancel,
                        //                                                    stopPrice: model.StopPrice,
                        //                                                    orderResponseType: OrderResponseType.Full);

                        if (orderResult.Success)
                        {
                            return Ok(orderResult.Data);
                        }
                    }
                }
                catch (Exception ex)
                {
                    return BadRequest(ex.Message);
                }
            }
            return BadRequest();
        }

        [HttpGet("StartCapture")]
        public async Task<IActionResult> StartCapture()
        {
            if (_binanceSocketClient != null)
            {
                var incomingBTC = _binanceSocketClient.SubscribeToTradeUpdatesAsync("BTCUSD", async (data) =>
                {
                    //(data);
                    _logger.LogInformation(data.Price.ToString());
                });
            }
            return BadRequest();
        }`
```

**Comment by ExceedingLife** [comment]
Ok! So I got my websockets to capture and stop capturing data!.

Now here is my new main question.
I currently have an API.
This is where my websocket starts and stops as well as where I execute my trades.
I understand how to make my UI execute my trades by using httpclient and json to send data back and forth.
How would I do this with my WebSocket?
How would I send the Data incoming to my API to my UI?
Data continously comes in on the API (from the websockets) How can I send that to my front end?
Here is my API method.
`
[HttpGet("StartBTCCapture")]
        public async Task<IActionResult> StartBTCCapture()
        {
            if (_binanceSocketClient != null)
            {
                _logger.LogInformation("Capture Starting...");
                _marketFeed.StartBTCCapture();
                //var incomingBTC = _binanceSocketClient.SubscribeToTradeUpdatesAsync("BTCUSD", async (data) =>
                //{
                //    //(data);
                //    _logger.LogInformation(data.Price.ToString());
                //});
                return Ok();
            }
            return BadRequest();
        }
 public async Task StartBTCCapture()
        {
            try
            {
                if (_binanceSocketClient != null)
                {
                    var incomingBTC = await _binanceSocketClient.SubscribeToTradeUpdatesAsync("BTCUSD", async (data) =>
                    {
                        //(data);
                        // _logger.LogInformation(data.Price.ToString());
                        Console.WriteLine(data.Price);
                    });
                }
            }
            catch(Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
        }
`

**Comment by ExceedingLife** [comment]
I also did it on the front end, I have my websocket. I just want to update the data on my UI in real time.  the trades that are coming in.
What would be the best way to do this?
I have my view then I have a partialview on my view. The data is coming in as C# so i cant use the ajax websockets method to update the UI like I originally thought.
` public async Task<IActionResult> GetPartial(List<TradeResult> trades)
        {


            var incomingBTC = await _binanceSocketClient.SubscribeToTradeUpdatesAsync("BTCUSD", (data) =>
            {
                //(data);
                // _logger.LogInformation(data.Price.ToString());
                Console.WriteLine(data.Price);
                trades.Add(new TradeResult
                {
                    Price = data.Price
                });

            });

            return PartialView("BoxView", trades);
        }`

**Comment by JKorf** [comment]
If you want a live connection between your frontend and backend you're going to need a socket connection, something like SignalR. With a socket connection you can keep pushing data to the frontend, which is not possible with your current structure. 

Currently you're stuck with a request/response architecture, i.e. the frontend sends a request for data to the backend and it sends the response. You can request this in a loop to get constantly updated data, but it's not real time. 

I suggest you take a look at server-sided Blazor. You can write the normal C# backend and put a html/C# frontend on it, in which you don't need to worry (too much) about the communication between them, which is automatically handled in the background with a SignalR websocket).
