### ISSUE TITLE
Futures modify  : Take profit and stop loss

### ISSUE THREAD

**Issue by Adamszsz** [JKorf/Binance.Net#727]
How can i set take profit price or stop loss to my opened position in futures?

I searched a lot and can't find where i can modify my opened position in M-Future.

i would like to edit take profit exacly how can i do on website  👍 
Is there any possible to set take profit in opened position? And how can i do that.
![image](https://user-images.githubusercontent.com/47539520/117473477-51400680-af5a-11eb-8a99-3234abf6c3cd.png)

**Comment by JKorf** [comment]
To be honest, I don't know enough about the futures implementation to give you an answer on this. Have a look in the API documentation to see if you see the functionality in there somewhere. If so, there should be a corresponding method in this wrapper.

**Comment by Antiox** [comment]
If you place a long for example, you'll place it like this :
`_client.FuturesUsdt.Order.PlaceOrder(symbol, OrderSide.Buy, OrderType.Market, quantity);`

If you want to take profit the whole position :
`_client.FuturesUsdt.Order.PlaceOrder(symbol, OrderSide.Sell, OrderType.Market, quantity);`

If you want to take profit some of it, you have to proceed this way :
`_client.FuturesUsdt.Order.PlaceOrder(symbol, OrderSide.Sell, OrderType.Market, quantityToRemove, reduceOnly:true);`
