### ISSUE TITLE
Error: -1021 Timestamp for this request was 1000ms ahead of the server's time.

### ISSUE THREAD

**Issue by vburwitz3** [JKorf/Binance.Net#728]
Not really a API error but since it so often happens lately and many coders should have the same issue I guess it is a good place to put the issue with Binance.

For monthe it was running fine but the last 2 month I regularly get:
"Error: -1021 Timestamp for this request was 1000ms ahead of the server's time."
when placing a new order, like updating a traling stop (cancelling old SL and placing new open order SL).

My server syncronizes with "time.windows.com" and therefore my time should be clearly be correct. Seemingly the Binance server clock frequently runs a bit late.

Is there any reliable mechanism to solve this problem?

**Comment by HypsyNZ** [comment]
`GetServerTimeAsync(true)`

 When `true` this function also determines the offset between server and local time and uses this for subsequent API calls

```cs
using (var client = new BinanceClient())
{                  
        var time = await client.Spot.System.GetServerTimeAsync(true);
        if (!time.Success)
        {
            // Error
        }           
}
```

This should fix the error you are seeing.
