### ISSUE TITLE
Websocket Status

### ISSUE THREAD

**Issue by sleepymatto** [JKorf/Binance.Net#729]
Hello

I'm wondering if there is a way to get the status of the websocket? I would like to keep track if its disconnected, connecting, reconnecting, connected, etc. If there isn't a way to get this information, would you possibly consider adding this functionality?

Thank you!

**Comment by JKorf** [comment]
The status of a subscription can be followed with the object returned from subscribing. It has events for ConnectionLost and ConnectionRestored:
````C#
var subscriptionResult = await binanceSocketClient.Spot.SubscribeToAllBookTickerUpdatesAsync(data =>
{
    // Process data
});

if(subscriptionResult.Success)
{
    subscriptionResult.Data.ConnectionLost += () => Console.WriteLine("Connection lost");
    subscriptionResult.Data.ConnectionRestored += (time) => Console.WriteLine("Connection restored");
}
````

**Comment by sleepymatto** [comment]
Ahh ok awesome! Thank you!

**Comment by eouree** [comment]
So in case of connection lost what is the best practice to handle subscriptions? Does it need to subscribe again or subscriptions reestablish automatically? 
If any example would be appreciated.

Thanks in advance

**Comment by HypsyNZ** [comment]
> So in case of connection lost what is the best practice to handle subscriptions? Does it need to subscribe again or subscriptions reestablish automatically?
> If any example would be appreciated.
> 
> Thanks in advance

The auto reconnect behavior is a ` BinanceSocketClientOptions`

![Auto Reconnect Behavior](https://i.imgur.com/juiM9kg.png)

By Default this behavior is `true`

![ARB](https://i.imgur.com/kDVerlt.png)

As you can also see from the screenshot, It waits `5` seconds between attempts by default

You can set default options like this:

```cs
            BinanceSocketClientOptions binanceSocketClientOptions = new BinanceSocketClientOptions
            {
                LogVerbosity = CryptoExchange.Net.Logging.LogVerbosity.Warning,
                AutoReconnect = true,
                ReconnectInterval = TimeSpan.FromSeconds(10),
            };

            BinanceSocketClient.SetDefaultOptions(binanceSocketClientOptions);
```

**Comment by eouree** [comment]
Thanks
