### ISSUE TITLE
Spot to Futures wallet transfer Issue

### ISSUE THREAD

**Issue by mdsoni** [JKorf/Binance.Net#730]
I am trying to consume Binance rest client on live environment with following code :

restClient.Spot.Futures.TransferFuturesAccount("USDT", Convert.ToDecimal("0.1"), Binance.Net.Enums.FuturesTransferType.FromSpotToUsdtFutures);

In response I am getting "You are not authorized to execute this request Binance"

Is this a problem with signature not being passed automatically by the library,

**Comment by HypsyNZ** [comment]
Check your API Key permissions on the website, Sounds like you don't have the permission checked.

**Comment by JKorf** [comment]
As @HypsyNZ suggested, make sure your API key permissions are set correctly

**Comment by mdsoni** [comment]
Thank you @HypsyNZ @JKorf 
You are right, I was having IP address restrictions on API
