### ISSUE TITLE
Stream subscriptions should allow for asynchronous handlers

### ISSUE THREAD

**Issue by mrmartan** [JKorf/Binance.Net#731]
For example `IBinanceSocketClientSpot` would have method overloads like

```csharp
Task<CallResult<UpdateSubscription>> SubscribeToBookTickerUpdatesAsync(string symbol, Func<BinanceStreamBookPrice, Task> onMessage);
```

and so on.

**Comment by JKorf** [comment]
Should it though? Generally you want to have the handlers called in a sync way because that way you can be sure the data is processed in the right order. If you handle them async multiple pieces of data might be processed at the same time and the order won't be guaranteed.

**Comment by mrmartan** [comment]
IMHO sync call is not the way to do it. If there are ordering concerns they should either be left for the implementor to deal with (in a business logic way, e.g. using the message timestamps) or surfaced though the interface.

Sync/async implementations deal mainly with technical aspects and resource usage. Say I want to make an HTTP call on every message. You force me to use the HttpClient's sync API and I have to work around that (two solutions that come to my mind right now are either `async void` or an in-memory queue, neither of which you want to deal with).

Lastly, are you sure the ordering will be an issue. You can await every call and then the messages should be processed in order, shouldn't they?

**Comment by HypsyNZ** [comment]
> they should either be left for the implementor to deal with  (in a business logic way

Or just not implemented.

> Sync/async implementations deal mainly with technical aspects and resource usage

Then your first sentence doesn't make any sense.

>  You force me to use the HttpClient's sync API

Whats your point.

> You can await every call and then the messages should be processed in order, shouldn't they?

You either know enough about Async to know the answer to this or are in no place to be recommending such changes to the code base.

Overall your comments seem to be in bad faith, You could have tested your suggestion.

**Comment by JKorf** [comment]
Not going to implement this
