### ISSUE TITLE
Futures PlaceOrder and  - set up  take profit 

### ISSUE THREAD

**Issue by Adamszsz** [JKorf/Binance.Net#734]
I try to find solution about place order.
How can i set Take profit when i place order?

`var otwarte_pozycje = client.FuturesUsdt.Order.PlaceOrder("BTCUSDT", OrderSide.Sell, OrderType.Limit, 1, PositionSide.Short, TimeInForce.GoodTillCancel, price: 57000M);`
How can i set take profit  or stop loss?

**Comment by HypsyNZ** [comment]
[Binance.Net/Enums/OrderType](https://github.com/JKorf/Binance.Net/blob/9e3572dc68a36e4680f22e130e63e5e6ddf06cb2/Binance.Net/Enums/OrderType.cs)

```cs
namespace Binance.Net.Enums
{
    /// <summary>
    /// The type of an order
    /// </summary>
    public enum OrderType
    {
        /// <summary>
        /// Limit orders will be placed at a specific price. If the price isn't available in the order book for that asset the order will be added in the order book for someone to fill.
        /// </summary>
        Limit,
        /// <summary>
        /// Market order will be placed without a price. The order will be executed at the best price available at that time in the order book.
        /// </summary>
        Market,
        /// <summary>
        /// Stop loss order. Will execute a market order when the price drops below a price to sell and therefor limit the loss
        /// </summary>
        StopLoss,
        /// <summary>
        /// Stop loss order. Will execute a limit order when the price drops below a price to sell and therefor limit the loss
        /// </summary>
        StopLossLimit,
        /// <summary>
        /// Stop loss order. Will execute a market order when the price drops below a price to sell and therefor limit the loss
        /// </summary>
        Stop,
        /// <summary>
        /// Stop loss order. Will be executed at the best price available at that time in the order book
        /// </summary>
        StopMarket,
        /// <summary>
        /// Take profit order. Will execute a market order when the price rises above a price to sell and therefor take a profit
        /// </summary>
        TakeProfit,
        /// <summary>
        /// Take profit order. Will be executed at the best price available at that time in the order book
        /// </summary>
        TakeProfitMarket,
        /// <summary>
        /// Take profit order. Will execute a limit order when the price rises above a price to sell and therefor take a profit
        /// </summary>
        TakeProfitLimit,
        /// <summary>
        /// Same as a limit order, however it will fail if the order would immediately match, therefor preventing taker orders
        /// </summary>
        LimitMaker,
        /// <summary>
        /// Trailing stop order will be placed without a price. The order will be executed at the best price available at that time in the order book.
        /// </summary>
        TrailingStopMarket,
        /// <summary>
        /// 
        /// </summary>
        Liquidation
    }
}
```

**Comment by mkleo21** [comment]
Were you able to make this work? I am not able to set a Stop Loss or Take Profit while placing an order.

**Comment by mimfa** [comment]
I'm involving with this problem too... Is there anybody to answer us?

**Comment by KingIthra** [comment]
December 2021 - I have been trying to place orders along with stop loss and take profit since October 2020. Has anyone been able to do this successfully? I heard you may open an order first and then send two more orders as TP and SL, i have been trying to implement this, No success. Can someone show us an example in code?

**Comment by sinaptech** [comment]
Can anyone solve this problem?

**Comment by eros1453** [comment]
https://github.com/JKorf/Binance.Net/issues/1005

**Comment by eros1453** [comment]
This works too but you have to make a market buy order to catch the await  for the other orders

**Comment by HypsyNZ** [comment]
> How can i set Take profit when i place order?

```cs
Task<WebCallResult<BinancePlacedOrder>> PlaceMarginOrderAsync(string symbol, OrderSide side, 
OrderType type, // StopLoss or TakeProfit
decimal quantity = null, 
decimal? quoteOrderQuantity = null, 
string? newClientOrderId = null, 
decimal? price = null, 
TimeInForce? timeInForce = null, 
decimal? stopPrice = null,  // This is also take profit price
decimal? icebergQuantity = null, 
SideEffectType? sideEffectType = null, // Maybe you want a side effect (borrow etc)
bool? isIsolated = null, 
OrderResponseType? orderResponseType = null, 
int? receiveWindow = null, 
CancellationToken ct = default(CancellationToken));
```

**Comment by eros1453** [comment]
You can mess with this code it`s for winform
 `
 private void BesLongLimitbutton_Click(object sender, EventArgs e)
        {
            Task.Run(async () =>
            {
                LongTradeAmount = tradeable_balance * (Convert.ToDecimal(Properties.Settings.Default.TRADEPERCENT) / 100);
                decimal trade_amount = Math.Round(LongTradeAmount * Leverage / bestBid, QUANTITYPRECISION);
                BesLongOrder_TP = Math.Round(bestAsk, PRICEPRECISION);
                using (var bfc = new BinanceClient())
                {
                    var BesLongorder_SellResult = await bfc.UsdFuturesApi.Trading.PlaceOrderAsync(ASSET, side: OrderSide.Buy, positionSide: PositionSide.Long, type: FuturesOrderType.Limit, quantity: trade_amount, price: bestBid, timeInForce: TimeInForce.GoodTillCrossing) ;

                    if (BesLongorder_SellResult.Success)
                    {
                        //var startTrail_trailing = bfc.UsdFuturesApi.Trading.PlaceOrder(ASSET, side: OrderSide.Sell, positionSide: PositionSide.Short, type: FuturesOrderType.TrailingStopMarket, quantity: BesLongorder_SellResult.Data.ExecutedQuantity, timeInForce: TimeInForce.GoodTillCanceled, callbackRate: "0.25", activationPrice: BesLongorder_SellResult.Data.Price * 1, 0025);
                        //MessageBox.Show(BesLongorder_SellResult.Data.ToString());
                        long_quantity = trade_amount;
                        long_price = BesLongorder_SellResult.Data.Price;
                        actpr = Math.Round(BesLongOrder_TP * 1.000454545M, PRICEPRECISION);
                        calbck = 0.2M;
                        var startTrail_trailing = await bfc.UsdFuturesApi.Trading.PlaceOrderAsync(ASSET, side: OrderSide.Sell, positionSide: PositionSide.Long, type: FuturesOrderType.TakeProfit, quantity: long_quantity, timeInForce: TimeInForce.GoodTillCanceled, price: long_price, stopPrice: actpr);
                        if (startTrail_trailing.Success)
                        {
                            //MessageBox.Show(startTrail_trailing.Data.ToString());
                        }
                        else
                        {
                            MessageBox.Show($"Order placing failed: {startTrail_trailing.Error.Message}", "Failed", MessageBoxButton.OK, MessageBoxImage.Error);
                        }
                        //LongTrailStop();
                        OpenOrders();
                        OpenPositions();
                    }
                    else
                    {
                        MessageBox.Show($"Order placing failed: {BesLongorder_SellResult.Error.Message}", "Failed", MessageBoxButton.OK, MessageBoxImage.Error);
                    }
                }
            });
        }
`

**Comment by eros1453** [comment]
![binance-test](https://user-images.githubusercontent.com/8195310/157142285-925b3f07-61c9-422e-82fc-d987db4db6dc.png)

**Comment by JKorf** [comment]
Cleaning up old issues, if you feel this issue is still relevant feel free to comment.
On topic, the API doesn't support setting an TP/SL when placing the initial order.
