### ISSUE TITLE
[Feature Request] Original Json

### ISSUE THREAD

**Issue by ehajri** [JKorf/Binance.Net#736]
In some scenarios, I'd need to store the result of the update streams as is, and to do that, I am serializing the object that Binance.Net has just deserialized. Example:
```c#
var stream= await _binanceSocketClient.Spot.SubscribeToTradeUpdatesAsync(symbol, async data =>
{
    var json = JsonSerializer.Serialize(data);
    await _redis.GetDatabase().PublishAsync("tradeStream", json);
});
```
running the app against a profiler shows a lot of time and memory are being utilized with `.Serialize()`.
Is it possible to add a property/method to retrieve the original Json text? Something like `data.Text`

So far, the areas I am concerned about is `Spot.SubscribeTo..` and `Spot.SubscribeToUserDataUpdatesAsync()`.

**Comment by HypsyNZ** [comment]
If you set up a `Logger` in `CryptoExchange` and set it to `Verbosity Debug` it will log every single update to file.

You could then read the data from file and it would be infinitely faster than what you are doing now.

(**Warning**: this file gets very large very fast if you sub to price update streams)

Copy / Paste solution, You just have to read the data from file
```cs
   List<TextWriter> writeFileSocket = new List<TextWriter>
            {
                 new CryptoExchange.Net.Logging.ThreadSafeFileWriter("c:\\logSocket.txt")
            };

            BinanceSocketClientOptions binanceSocketClientOptions = new BinanceSocketClientOptions
            {

                LogVerbosity = CryptoExchange.Net.Logging.LogVerbosity.Debug,

                LogWriters = writeFileSocket
            };

            BinanceSocketClient.SetDefaultOptions(binanceSocketClientOptions);
```

**Comment by ehajri** [comment]
@HypsyNZ thank you for the workaround.

Indeed the file is growing so fast, and it doesn't seem I can assign logwriter for each sub.

**Comment by HypsyNZ** [comment]
> @HypsyNZ thank you for the workaround.
> 
> Indeed the file is growing so fast, and it doesn't seem I can assign logwriter for each sub.

This may work 

```cs
// await Symbol Tickers Etc (_binanceSocketClient)
BinanceSocketClient.SetDefaultOptions(binanceSocketClientOptions);
// await SubscribeToUserDataUpdatesAsync (_binanceSocketClient1)
```

Do the subscriptions last and run this before you subscribe them, use a separate "_binanceSocketClient1"

**Comment by HypsyNZ** [comment]
Awesome, Thanks @JKorf

**Comment by ehajri** [comment]
@JKorf Thanks!
