### ISSUE TITLE
Market order smaller than MinNotional fails with AutoComply

### ISSUE THREAD

**Issue by ZornTaov** [JKorf/Binance.Net#737]
**Describe the bug**
When making a buy or sell Market order, if the given quantity * currentMarketPrice is smaller than the MinNotional for that symbol, even with `TradeRulesBehaviour.AutoComply` the order fails with the error: `{"code":-1013,"msg":"Filter failure: MIN_NOTIONAL"}`

**To Reproduce**
```C#
Client = new BinanceClient(new BinanceClientOptions
{
    BaseAddress = "https://api.binance.us",
    ApiCredentials = new ApiCredentials("[SNIP]","[SNIP]"),
    LogVerbosity = CryptoExchange.Net.Logging.LogVerbosity.Debug,
    LogWriters = new List<TextWriter> { writer },
    RateLimitingBehaviour = RateLimitingBehaviour.Wait,
    TradeRulesBehaviour = TradeRulesBehaviour.AutoComply
});
Client.Spot.Order.PlaceOrder("DOGEUSD", OrderSide.SELL, OrderType.Market, 1);
```
**Expected behavior**
With `TradeRulesBehaviour.AutoComply`, the quantity should be raised to match the symbol's `symbol.MinNotionalFilter.MinNotional`. For example, with a current market price of $0.50, it should be raised to a quantity of 20.

**Debug logging**
```
2021/05/14 21:07:17:194 | Binance    | Debug | [60] Creating request for https://api.binance.us/api/v3/order
2021/05/14 21:07:17:202 | Binance    | Debug | [60] Sending POST signed request to https://api.binance.us/api/v3/order with request body quantity=1&recvWindow=5000&side=SELL&signature=[SNIP]&symbol=DOGEUSD&timestamp=1621051637194&type=MARKET
2021/05/14 21:07:17:329 | Binance    | Debug | [60] Error received: {"code":-1013,"msg":"Filter failure: MIN_NOTIONAL"}
```

**Comment by JKorf** [comment]
Well the issue with this is that you would have to know the current market price to be able to check. And the library doesn't. It would have to do a request for this, which would take time and then the market price might have already changed again when the actual order placement happens.
