### ISSUE TITLE
TransactTime

### ISSUE THREAD

**Issue by marinkobabic** [JKorf/Binance.Net#74]
Is there a way to set the timezone in the client so that all dates returned by the client have the correct time for the set timezone?

https://msdn.microsoft.com/en-us/library/system.timezone.currenttimezone(v=vs.110).aspx

**Comment by JKorf** [comment]
All times are returned as UTC. There is no way to change this, but you could easily do this yourself by calling ToLocalTime on the DateTime object:
https://msdn.microsoft.com/en-us/library/system.datetime.tolocaltime(v=vs.110).aspx

**Comment by marinkobabic** [comment]
I'm fine with your proposal
