### ISSUE TITLE
How to get all filled orders for a specific symbol in spot market?

### ISSUE THREAD

**Issue by salocinx** [JKorf/Binance.Net#744]
Hi.

Is it somehow possible to get past filled orders for a specific symbol in spot market without listing cancelled orders as well?

I only found `GetAllOrders()` functions which returns cancelled and other order types (rejected, etc) as well.

Thanks!

**Comment by gianlucacini** [comment]
you can try `GetMyTrades()` and then you filter the results by status

**Comment by salocinx** [comment]
> you can try `GetMyTrades()` and then you filter the results by status

Hi. Thanks for the hint! I am now querying all the trades and get the corresponding orders one-by-one with the trade's order-ID. This way I have a reliable way to get all my filled orders including the custom-IDs. Thanks.
