### ISSUE TITLE
Error: -1022 Signature for this request is not valid

### ISSUE THREAD

**Issue by MacMerg** [JKorf/Binance.Net#747]
So, I'm having trouble with Spot.PlaceOrder , I get the error Error: -1022 Signature for this request is not valid . Funny thing is, same code to query openorders or cancelorders or accountinfo works fine.  I am using Binance.US  BaseAddress = "https://api.binance.us", otherwise, love your work! thank you! ryan

**Debug logging**
2021/05/20 19:46:14:322 | Binance    | Info | Time offset between 0 and 500ms (32.8185ms), no adjustment needed
2021/05/20 19:46:14:323 | Binance    | Debug | [32] Creating request for https://api.binance.us/api/v3/order
2021/05/20 19:46:14:325 | Binance    | Debug | [32] Sending POST signed request to https://api.binance.us/api/v3/order with request body newOrderRespType=RESULT&quoteOrderQty=536.52&recvWindow=5000&side=SELL&signature=352F5C59FCA6E44CEF5622D0434C2486E70F28A82DDF29698F9F5CE0C00F11CF&symbol=ADAUSD&timestamp=1621554374323&type=MARKET

2021/05/20 19:46:14:390 | Binance    | Debug | [32] Error received: {"code":-1022,"msg":"Signature for this request is not valid."}
2021/05/20 19:46:14:522 | Binance    | Debug | Disposing exchange client

**Comment by HypsyNZ** [comment]
Does your API Key have permission to post orders?

Have you modified anything to do with the signature?

**Comment by aaron-salisbury** [comment]
I ran into this too. My API key permissions are wide open for now. Makes me think the problem is on the Binance side. Some queries need one endpoint and others need another.

**Comment by JKorf** [comment]
Hm I can't reproduce it on binance.com, sending the same parameters will work fine for me there. I don't have binance.us account so it's a bit hard to test that. Since the the other endpoints work fine with the same api key/secret and the request url seem fine to me, it would suggest some permission issue or something. Maybe try contacting binance.us directly.

**Comment by MacMerg** [comment]
Yeah this must've been on the Binance Server side, because it just worked after I changed absolutely nothing.  Thanks for taking the time to check it out

**Comment by JKorf** [comment]
No problem, thanks for the update
