### ISSUE TITLE
[Question] History for Symbol

### ISSUE THREAD

**Issue by LiorBanai** [JKorf/Binance.Net#748]
Hi,
Is it possible to get the history for some symbol? meaning x hours old ticks?

**Comment by HypsyNZ** [comment]
> Hi,
> Is it possible to get the history for some symbol? meaning x hours old ticks?

![](https://i.imgur.com/gR30SQe.png)

[Binance Docs](https://binance-docs.github.io/apidocs/spot/en/#kline-candlestick-data)

**Comment by LiorBanai** [comment]
Thanks a lot!
