### ISSUE TITLE
Could not install package

### ISSUE THREAD

**Issue by azijhm** [JKorf/Binance.Net#751]
Hi
when I start to install package I see this Error:
You are trying to install this package into a project that targets '.NETFramework,Version=v4.8', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
Can you help me please

**Comment by JKorf** [comment]
.NET framework 4.8 supports netstandard2.0 packages which this is, so it should work for you. You'll need to make sure your Visual Studio and/or Nuget client are up to date.
