### ISSUE TITLE
Binance Tr Connection

### ISSUE THREAD

**Issue by miqteam** [JKorf/Binance.Net#752]
How can i connect to binance tr account?
Here is the offical web site : https://www.trbinance.com/

**Comment by JKorf** [comment]
You can change the address of the server using the client options ( BaseAddress property )

**Comment by miqteam** [comment]
When i change it, it cannot open socket stream. Rest api is ok.

**Comment by JKorf** [comment]
What are you changing it to?

**Comment by JKorf** [comment]
Setting the BaseAddress of the socket client to BaseAddress = "wss://stream.binance.cc" works for me
