### ISSUE TITLE
Trading Status on FuturesUsdt Market

### ISSUE THREAD

**Issue by pkodiscoverit** [JKorf/Binance.Net#753]
Hi All,

There is a REST endpoint for the tradingstatus of a Binance Account on the spot market. However, I couldn't find the tradingstatus endpoint for the futures market (/fapi/v1/apiTradingStatus). Are there any intensions (or wip) to add the tradingstatus ep for futures market too?

Cheers,
Peter

**Comment by HypsyNZ** [comment]
As a work around you can do the following;

`BinanceClientGeneral.cs` 

change 

```cs
_baseClient.SendRequestInternal<BinanceTradingStatusWrapper>(_baseClient.GetUrlSpot(tradingStatusEndpoint, "wapi", "3")
```

to 

```cs
_baseClient.SendRequestInternal<BinanceTradingStatusWrapper>(_baseClient.GetUrlSpot(tradingStatusEndpoint, "fapi", "1")
```

@JKorf

**Comment by pkodiscoverit** [comment]
> As a work around you can do the following;
> 
> `BinanceClientGeneral.cs`
> 
> change
> 
> ```cs
> _baseClient.SendRequestInternal<BinanceTradingStatusWrapper>(_baseClient.GetUrlSpot(tradingStatusEndpoint, "wapi", "3")
> ```
> 
> to
> 
> ```cs
> _baseClient.SendRequestInternal<BinanceTradingStatusWrapper>(_baseClient.GetUrlSpot(tradingStatusEndpoint, "fapi", "1")
> ```
> 
> @JKorf

Ok cool, I'll give this one a shot... thx a lot!

**Comment by JKorf** [comment]
I've added the USDT futures trading status endpoint to the beta release.
