### ISSUE TITLE
Dispose context in socketclients methods

### ISSUE THREAD

**Issue by MansoorJafari9** [JKorf/Binance.Net#756]
Hi, I want to retrieve data from database(context)  in "SubscribeToAggregatedTradeUpdates", but give me this below error please help!

![1400-03-08 12 13 40](https://user-images.githubusercontent.com/52848663/120062464-aa8de800-c077-11eb-962f-0ef48501fdef.jpg)
<img width="808" alt="Screen Shot 1400-03-08 at 10 58 53" src="https://user-images.githubusercontent.com/52848663/120062474-b5487d00-c077-11eb-99f8-1fb2cf90b925.png">

**Comment by HypsyNZ** [comment]
well, The error says you disposed `binanceContext`

The error also says if you used `binanceContext` in a `using` statement that it will be automatically disposed.

My guess is you did that.

**Comment by naserkaka** [comment]
Hi, do you know why I have  green undermarker in the end of  line 152 , it says this async method lacks away.....
I have await next to var listenResult = .... on the same line. If I runt this it will run synchronously.
![public async Task streamPrices()](https://user-images.githubusercontent.com/70115032/124759151-a0d98900-df2f-11eb-83a5-dc5cb4da2539.jpeg)

**Comment by naserkaka** [comment]
hmm okej I think I solved it just by removing async left to data =>
