### ISSUE TITLE
BinanceSpotSymbolOrderBook suddenly stops 

### ISSUE THREAD

**Issue by daguda** [JKorf/Binance.Net#757]
The BinanceSpotSymbolOrderBook randomly stops passing values If i run multiple instances in Linux. 
Any advice? thank you.

` 
```
           var options = new BinanceOrderBookOptions(10, 100);
            var obBTC = new BinanceSpotSymbolOrderBook($"BTCUSDT",options);
            var result = await obBTC.StartAsync();
            if (result.Success)
            {
                _logger.Info($"success");
            }
            else
            {
                _logger.Info(result.Error.Message);
                return;
            }
```
`

**Comment by HypsyNZ** [comment]
If you set up a `Logger` in `CryptoExchange` and set it to `Verbosity Debug` it will hopefully have some output, I doubt its just "randomly stopping" with no message of any kind.

You can also do this for the `Client`

```cs
   List<TextWriter> writeFileSocket = new List<TextWriter>
            {
                 new CryptoExchange.Net.Logging.ThreadSafeFileWriter("c:\\logSocket.txt")
            };

            BinanceSocketClientOptions binanceSocketClientOptions = new BinanceSocketClientOptions
            {

                LogVerbosity = CryptoExchange.Net.Logging.LogVerbosity.Debug,

                LogWriters = writeFileSocket
            };

            BinanceSocketClient.SetDefaultOptions(binanceSocketClientOptions);
```

This should point you in the right direction.

**Comment by mirror222** [comment]
thank you.

**Comment by MachineTrader** [comment]
A beginner question on the same type of error. My stream also stops after a while(an hour +). Is it possible to monitor the listenkey from the main function, if(!listenkey.Success){client.unsubscribeall(); myResubscribeFunc();} if stream is broken?

**Comment by HypsyNZ** [comment]
> This is probably a beginner question on the same type of problem, but referring to the user stream. My stream also stops after a while(an hour +). Is it possible to monitor the listenkey, or the result from the SubscribeToBookTickerUpdatesAsync or SubscribeToUserDataUpdatesAsync from the main function to detect if the stream needs to restart,
> ` if (ws_user.IsFaulted || ws_user.IsCanceled) { await socketClient.UnsubscribeAll(); StartWS(); }`
> ` if (ws_pub.IsFaulted || ws_pub.IsCanceled) { await socketClient.UnsubscribeAll(); StartWS(); }`
> 
> Is this redundant and buildt into the library and my problem comes from something else?
> Does this risk memory leak due to not being disposed?
> I red somewhere that Binance recommends resubscribing after and hour or so.

`client.Margin.UserStream.KeepAliveUserStreamAsync(YourListenKey);`

If you aren't keeping it alive it will eventually get closed.

Binance recommends doing this at least every 30 minutes.
