### ISSUE TITLE
Add Referral code to Ordres

### ISSUE THREAD

**Issue by IR4N0nY** [JKorf/Binance.Net#759]
Hello dear @JKorf 
Can you plz add a Function to add referral code in any order that i send to binance?
is that possible? Like Finandy.com that add there referral code to there customers ?

**Comment by JKorf** [comment]
I don't think there is such a thing in the Binance API. Note that this is a wrapper around the official Binance API, not the Binance API itself, so requests for adding features should go to them. 

If you have any API docs referencing a referal code please let me know and I'll be happy to add it.

**Comment by HypsyNZ** [comment]
Pretty sure this is an ad/phishing attempt, Don't go to that website.
