### ISSUE TITLE
GetKlinesAsync Limit Issue

### ISSUE THREAD

**Issue by myhorses2you** [JKorf/Binance.Net#76]
Hi! Thanks for the API. It is very useful for me.. However, I have one issue to solve. No matter what I did, I could not get more than 1000 elements from GetKlinesAsync method. Is there any way to increase the amount?

Thanks.

**Comment by keefehiggins** [comment]
That is a limit of the binance api itself. You can look over the docs here: https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md

I iterate through the dates I need and pass a startTime and endTime. Just be aware the dates are in UTC format.

**Comment by myhorses2you** [comment]
I understand that. Thank you for the response. 

Also, is it possible to retrieve historical data for every second? I will try to use this data for backtesting for my trading bot algorithm.

**Comment by keefehiggins** [comment]
I am not aware of a way to get data to the second. I subscribe to the 24 hour ticker web socket and then save the data. I use that data later in some knime reports I run.
