### ISSUE TITLE
Margin.GetInterestRateHistoryAsync() DailyInterest field is always 0

### ISSUE THREAD

**Issue by zlingqing** [JKorf/Binance.Net#760]
Margin.GetInterestRateHistoryAsync() DailyInterest field is always 0

**Comment by JKorf** [comment]
PR for this has been merged, will be fixed in next release

**Comment by HypsyNZ** [comment]
> Margin.GetInterestRateHistoryAsync() DailyInterest field is always 0

If you need to manually patch this before the next release here is the commit

https://github.com/JKorf/Binance.Net/pull/742/commits/98e0877b9831d7a9f49803f91c13315547da35b2

**Comment by JKorf** [comment]
Fixed in latest beta
