### ISSUE TITLE
How to set leverage and cross or isolated in futureusdt?

### ISSUE THREAD

**Issue by RezaDorosti** [JKorf/Binance.Net#761]
I need get  current leverage and margin & change leverage and margin in futuresUsdt.
how to do this?

**Comment by mkleo21** [comment]
Perhaps this is what you are looking for - 
To get - 
`var SymbolPositionList = client.FuturesUsdt.GetPositionInformation(CoinSymbol);
Futures.FuturesData.BinancePositionDetailsUsdt PositionDetails = SymbolPositionList.Data.ToList().FirstOrDefault();
`
`FuturesMarginType MarginType =  PositionDetails.MarginType;`
`int CoinLeverage = PositionDetails.Leverage;`

To set - 
`client.FuturesUsdt.ChangeMarginType("BTCUSDT", FuturesMarginType.Isolated); //Or Cross
                            client.FuturesUsdt.ChangeInitialLeverage("BTCUSDT", 2);`
