### ISSUE TITLE
Get asset by symbol

### ISSUE THREAD

**Issue by DragonDara** [JKorf/Binance.Net#762]
Hi there,

Was _GET /sapi/v1/asset/assetDetail_ implemented in current .net binance version?

For example, I wanna get a coin by a symbol in my asset. Currently, I had failed to find this method in this implementation

**Comment by JKorf** [comment]
The sapi call is not yet implemented, but the wapi version is (which is basically the same) and can be found at `binanceClient.WithdrawDeposit.GetAssetDetailsAsync()`

**Comment by DragonDara** [comment]
Thanks a lot. But what is distinct between sapi and wapi?

**Comment by JKorf** [comment]
As far as I know they're slowly replacing wapi endpoints with sapi endpoints, but I'm not sure about the reasoning or anything. There are multiple requests which first only had a wapi endpoint and later also received a sapi endpoint. The data is the same most of the time.
