### ISSUE TITLE
Is there a way to identify an account?

### ISSUE THREAD

**Issue by gensleralexander** [JKorf/Binance.Net#763]
Hello,

let's say I have an application, where the user enters his API Credentials and the application is observing what's happening on the account (e.g. trades).
Normally I would differentiate between several credentials based on the API key, however the user would still be able to create two api credentials for the same account and both register it in my application (stupid, but who knows what's going on in a user's head)
Is there a possibility to query some unique user data (like the e-mail address of the user or an account id) so that I can check if there is an existing API credential for the same user already?

Sincerly,
Alex

**Comment by JKorf** [comment]
I understand your use case for it, but I don't think there is a way to get a unique identifier for an API key. Email addresses and other personal info is not available and I'm not aware of any endpoint that returns anything like an account id.

**Comment by gensleralexander** [comment]
Thank you, I will display a warning for the user then.
