### ISSUE TITLE
Retrieving a single symbol from exchangeinfo endpoint

### ISSUE THREAD

**Issue by Benajax** [JKorf/Binance.Net#767]
The exchangeinfo endpoint does support the retrieval of a single symbol ( "https://api.binance.com/api/v3/exchangeInfo?symbol=BNBBTC"). Can you add support for it in the library? At the moment only the retrieval of all the symbols is supported.

**Comment by JKorf** [comment]
This is now available in the latest beta release

**Comment by Benajax** [comment]
That's great. Thanks.
