### ISSUE TITLE
Switch to test API

### ISSUE THREAD

**Issue by DragonDara** [JKorf/Binance.Net#768]
Is there any possibility to switch to Test API  **_https://testnet.binance.vision/api_**??

**Comment by JKorf** [comment]
Yes, using the latest beta release you can switch like so:
`BinanceClient.SetDefaultOptions(new BinanceClientOptions(BinanceApiAddresses.TestNet))`
Using an earlier version you can set the api address like so:
````C#
BinanceClient.SetDefaultOptions(new BinanceClientOptions()
{
    BaseAddress = "https://testnet.binance.vision/"
});
````
