### ISSUE TITLE
Add Binance ifNewUser method

### ISSUE THREAD

**Issue by NektoDron** [JKorf/Binance.Net#775]
Can you add method from Binance broker programm to API?
https://www.binance.com/en/support/faq/a78a065d0c4846aaa1af474d8e712ab9
For Spot, GET /sapi/v1/apiReferral/ifNewUser
For Futures, GET /fapi/v1/apiReferral/ifNewUser

**Comment by JKorf** [comment]
Well it took 3 years, but it's now available under `SpotApi.Agent.GetIfNewUserAsync`, `UsdFuturesApi.Agent.GetIfNewUserAsync` and `CoinFuturesApi.Agent.GetIfNewUserAsync`
