### ISSUE TITLE
Question: managing several IPs

### ISSUE THREAD

**Issue by thomasd3** [JKorf/Binance.Net#776]
If I have a server with multiple IP addresses available, is there a way to set which one I want to use for a connection to Binance? I would like to run multiple connections (each with their own IP) from one server vs. multiple servers with one IP each as it is now.

**Comment by JKorf** [comment]
This is not possible at the moment. The library uses netstandard2.0/netstandard2.1 HttpClient for requests, and as far as I'm aware this is not supported in the HttpClient (without hacky reflection code that is).

**Comment by thomasd3** [comment]
I saw a chat on dotnet's github (from 2020) where they said they will implement that for .net 5, I need to dig into the topic

**Comment by JKorf** [comment]
You can pass in an HttpClient in the client options, so if you can fix it using the HttpClient you should be able to use is using this library.
