### ISSUE TITLE
FuturesUsdt.SubscribeToMarkPriceUpdates

### ISSUE THREAD

**Issue by VozyakovAV** [JKorf/Binance.Net#779]
I get an error when requesting:
_client. FuturesUsdt.SubscribeToMarkPriceUpdates ("BTCUSDT_210625", null, x => { });

Error:
BTCUSDT_210625 is not a valid Binance symbol. Should be [BaseCurrency][QuoteCurrency], e.g. BTCUSDT

Please, remove call 'symbol.ValidateBinanceSymbol()' from a method SubscribeToMarkPriceUpdatesAsync.
Or fix the method ValidateBinanceSymbol().

**Comment by JKorf** [comment]
I've removed it in the latest beta
