### ISSUE TITLE
newOrderRespType Full

### ISSUE THREAD

**Issue by ZigmundL** [JKorf/Binance.Net#780]
Is there a way I can get "Response FULL" with all fills included? 
Currently I skip all OrderUpdates that are partially filled, and count only FILLED ones. There is a PlaceOrder param `OrderResponseType? orderResponseType = null`. I would like to have all "fills" info, but I don't see any enumerable that could contain this info in `Binance.Net.Objects.Spot.UserStream.BinanceStreamOrderUpdate`

**Comment by JKorf** [comment]
The OrderResponseType parameter is only to specify how much information should be returned on the PlaceOrder call. It doesn't do anything for the order updates.
