### ISSUE TITLE
Serialize/deserialize exception

### ISSUE THREAD

**Issue by karloballa** [JKorf/Binance.Net#781]
I really don't know how it works behind the scene, nor how I can debug it, but it seems that the BinanceSymbol won't deserialize, more precisely the MAX_POSITION filter.

Here is the object that won't deserialize:
{
	"symbol": "SXPDOWNUSDT",
	"Status": "TRADING",
	"BaseAsset": "SXPDOWN",
	"BaseAssetPrecision": 8,
	"QuoteAsset": "USDT",
	"quotePrecision": 8,
	"OrderTypes": [
		"LIMIT",
		"LIMIT_MAKER",
		"MARKET",
		"STOP_LOSS_LIMIT",
		"TAKE_PROFIT_LIMIT"
	],
	"IceBergAllowed": true,
	"IsSpotTradingAllowed": false,
	"IsMarginTradingAllowed": false,
	"OCOAllowed": true,
	"quoteOrderQtyMarketAllowed": true,
	"BaseCommissionPrecision": 8,
	"QuoteCommissionPrecision": 8,
	"Permissions": [
		"LEVERAGED"
	],
	"Filters": [
		{
			"filterType": "PRICE_FILTER",
			"maxPrice": 6.75500000,
			"minPrice": 0.35600000,
			"tickSize": 0.00100000
		},
		{
			"filterType": "PERCENT_PRICE",
			"multiplierUp": 5.0,
			"multiplierDown": 0.2,
			"avgPriceMins": 5
		},
		{
			"filterType": "LOT_SIZE",
			"maxQty": 100000000.00000000,
			"minQty": 0.01000000,
			"stepSize": 0.01000000
		},
		{
			"filterType": "MIN_NOTIONAL",
			"minNotional": 10.00000000,
			"applyToMarket": true,
			"avgPriceMins": 5
		},
		{
			"filterType": "ICEBERG_PARTS",
			"limit": 10
		},
		{
			"filterType": "MARKET_LOT_SIZE",
			"maxQty": 21879.34813888,
			"minQty": 0.00000000,
			"stepSize": 0.00000000
		},
		{
			"filterType": "MAX_NUM_ORDERS",
			"maxNumOrders": 200
		},
		{
			"filterType": "MAX_POSITION"
		},
		{
			"filterType": "MAX_NUM_ALGO_ORDERS",
			"maxNumAlgoOrders": 5
		}
	]
},

**Comment by nikkozp** [comment]
https://github.com/JKorf/Binance.Net/pull/766/commits/3ee5ca747b5485bd75d22d44322e4db2f8c13b16

**Comment by karloballa** [comment]
Thanks!
