### ISSUE TITLE
Issue with Spot.System.GetExchangeInfo()

### ISSUE THREAD

**Issue by Josip9989** [JKorf/Binance.Net#782]
My code just stopped working a few hours ago. I didn't make any changes.
The response from the Spot.System.GetExchangeInfo() is:
_[1] Deserialize JsonSerializationException: Error setting value to 'Type' on 'Binance.Net.Objects.BinanceRateLimit'_
The full response is in the Attachment.
[Full response.txt](https://github.com/JKorf/Binance.Net/files/6709781/Full.response.txt)

I have the following Options set for the Client:
```
            BinanceClient.SetDefaultOptions(new BinanceClientOptions()
            {
                ApiCredentials = new ApiCredentials(apiKey, apiSecret),
                LogVerbosity = LogVerbosity.Debug          
            });
```
Can anyone help?

Thank you

**Comment by chichoncoin** [comment]
Hi,
For me too.
Regards

**Comment by JKorf** [comment]
Hi, this is because of a change on the server side. I've pushed an update (v6.13.4) which should resolve this

**Comment by Josip9989** [comment]
Wow, that was very fast :)
Thank you very much.

**Comment by karloballa** [comment]
Very fast indeed :)

**Comment by CryptoClint78** [comment]
Thank you for fixing that so quickly dude.

**Comment by jurgenBE** [comment]
Hi, I am trying to update to this version 6.13.3 but i see some strange things on github like only version 7.1.2
![image](https://user-images.githubusercontent.com/10328935/132803599-96f77402-c380-4332-b466-c5bbeca0bf86.png)
And i fi update to this 7.1.2 version, my project dosn't build anymore and i have a lot of strange errors..
