### ISSUE TITLE
System.MissingMethodException, CryptoExchange.Net.RestClient..ctor,  

### ISSUE THREAD

**Issue by njorder** [JKorf/Binance.Net#783]
Suddenly got this exception today, on unchanged previously working code. 
Was using 6.4.0, now updated to 6.13.4, cleaned, rebuild, and reinstalled Binance.Net NuGet, but exception persists. 
Target framework :  .NET 4.6.1

```
System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'Void CryptoExchange.Net.RestClient..ctor(CryptoExchange.Net.Objects.RestClientOptions, CryptoExchange.Net.Authentication.AuthenticationProvider)'.
  Source=Binance.Net
  StackTrace:
   at Binance.Net.BinanceClient..ctor(BinanceClientOptions options)
```

Get this with or without BinanceClientOptions : 

```
var opt = new BinanceClientOptions()
{
      ApiCredentials = GetReadCredentials() 
};

using (var client = new BinanceClient(opt))
{ }
```

**Comment by HypsyNZ** [comment]
> Suddenly got this exception today, on unchanged previously working code.

If this is true then your RAM might be dying.

**Comment by JKorf** [comment]
I suspect you have (not) updated the CryptoExchange.Net library. What version of that is installed?

**Comment by njorder** [comment]
Sorry, found I also referenced another 6.4.0 Binance.Net.dll taking precedence over updated NuGet version. 
Solved.
