### ISSUE TITLE
Subscribing to KLIneUpdates for 1 Month, subscribes to the 1 minute interval.

### ISSUE THREAD

**Issue by fuzzlebuck** [JKorf/Binance.Net#785]
await SocketClient.Spot.SubscribeToKlineUpdatesAsync(""BTCUSDT", KlineInterval.OneMonth, async data => {

  // data.Data.Interval is OneMinute

});

Expected data.Data.Interval to be OneMonth

**Comment by JKorf** [comment]
This should be fixed in the latest version
