### ISSUE TITLE
Example code out of sync from nuget

### ISSUE THREAD

**Issue by CzBuCHi** [JKorf/Binance.Net#790]
**Describe the bug**
Example code out of sync from nuget version '6.14.0-beta7' - code do not compile (for ex. 'LogVerbosity' is unknown)

**To Reproduce**
create new console app (netcoreapp3.1)
Downloaded nuget '6.14.0-beta7'
copy source from [here](https://github.com/JKorf/Binance.Net/blob/master/Examples/ClientConsole/Program.cs) 

**Expected behavior**
Code compiles successfully

**Debug logging**
code didnt compile so no logs ...

**Comment by JKorf** [comment]
You're right, examples are not up to date with the beta releases, this will be fixed soon
