### ISSUE TITLE
Error on LOT_SIZE

### ISSUE THREAD

**Issue by 5appz** [JKorf/Binance.Net#791]
**Describe the bug**
When trying to convert BTC to USDT it gives error "LOT_SIZE"

**To Reproduce**
What endpoints and subscriptions are called.
var a = item.LotSizeFilter.MinQuantity

**Expected behavior**
Should give 1000000 for BTC (*example)

![err on lot_size](https://user-images.githubusercontent.com/72450361/124112673-d29fab00-da6a-11eb-9791-3d0cefd5c50b.png)

**Comment by JKorf** [comment]
https://binance-docs.github.io/apidocs/spot/en/#filters

**Comment by 5appz** [comment]
I think the problem was on binance when giving the result back. The problem is fixed by itself. Anyway, thnx for the reply.
