### ISSUE TITLE
Signature for this request is not valid for all requests

### ISSUE THREAD

**Issue by Zeddex** [JKorf/Binance.Net#795]
I have signature problem for all requests.

Sending GET signed request to https://api.binance.com/sapi/v1/capital/config/getall?timestamp=1625445740958&recvWindow=5000&signature=6EBC5BCAE704FBAF5B370DD3C836458E2D4306EB52A5EDA7030B395D9D51361C
Error received: {"code":-1022,"msg":"Signature for this request is not valid."}

**Comment by JKorf** [comment]
Make sure your API key/secret is correct

**Comment by Zeddex** [comment]
There was a problem with my old api/secret. I've made a new one and now all fine
