### ISSUE TITLE
I am using this api to place limit order but it doesn't order anything

### ISSUE THREAD

**Issue by WantHelp** [JKorf/Binance.Net#797]
private void btn_buy_Click(object sender, EventArgs e)
        {
            binancle.Spot.Order.PlaceOrder(cmb_coins.Text,OrderSide.Sell,OrderType.Limit,60,null,null,Convert.ToDecimal(0.2400));
        }

**Comment by stonebirdarchitect** [comment]
Could you at least tell what did you do wrong before closing it ?..

**Comment by WantHelp** [comment]
`binancle.Spot.Order.PlaceOrder(cmb_coins.Text, OrderSide.Buy, OrderType.Limit, Convert.ToDecimal(txt_qty.Text),null,null,Convert.ToDecimal(txt_price.Text),TimeInForce.GoodTillCancel);`

i Had to convert everything in decimal and timeinforce property was also needed. thanks

**Comment by thebitbrine** [comment]
Check the error data that `PlaceOrder` returns, _Binance_ is often very picky about the parameters sent.
Sending 1 unnecessary parameter is enough to make it throw an error and not post your order.

Also, it seems like you're not flooring your price or quantity, which is a problem.
You can use `client.UsdFuturesApi.ExchangeData.GetExchangeInfoAsync().Result.Data.Symbols` to get the `TickSize` and `LotSize` of your current symbol then floor it like this:

```CSharp
var FixedPrice = TickSize * Math.Floor(Price / TickSize);
var FixedAmount = LotSize * Math.Floor(Amount / LotSize);
```

Hope this helps.
