### ISSUE TITLE
GetKlines occasionally hangs indefinitely

### ISSUE THREAD

**Issue by Atari800Bootcamp** [JKorf/Binance.Net#80]
This is my first ever GitHub post! First of all, thank you for developing such great libraries.  I have recently updated from Binance.Net v2.2.5 to v3.1.3, and have noticed my application hanging after running for several hours (it never happened before). I re-ran in debug mode in Visual Studio and when it happened again I hit break, and it was stuck on the call to GetKlines which was not returning. Could this be a regression with the  library updates? In the meantime I think I can work around it by wrapping the calls and waiting on task completion for a time period.

**Comment by JKorf** [comment]
Hi, congrats on your first GitHub post ^^

I've head something like this before in my other library, https://github.com/JKorf/Bittrex.Net/issues/87
I'm not sure why this happens, but I'll look into it. Seems like you're not the only one with the problem. Does it happen often often/always?

**Comment by Atari800Bootcamp** [comment]
I haven't been able to run my application for longer than 10 hours without it hanging. I have also seen it hang after about an hour. Not sure if this is helpful, but with the task wrapper I added this morning, after starting application at 07:05:07, GetKlines failed to return within 3s at 07:06:06, and once again at 07:30:04, and it is still running at time of writing 08:22:00. I wondered if adding timeout functionality in CryptoExchange.Net might be useful?

**Comment by JKorf** [comment]
Thanks for the additional information. Could you share the (partial) code you use so I can maybe reproduce it?

**Comment by JKorf** [comment]
Also, could you put LogVerbosity on Debug and share the last logging before it hangs?

**Comment by Atari800Bootcamp** [comment]
The code is very fragmented but essentially the following call is made once inside a higher level loop that has a sleep interval of 500ms. The actual time between successive calls will obviously be greater than this. I don't cache anything in the application so I realise this is an expensive operation.

` var result = binanceClient.GetKlines(assetSymbolPair, KlineInterval.OneMinute,
                startTime: DateTime.UtcNow.AddMinutes(-20),
                endTime: DateTime.UtcNow, limit: 20);`

I'll set the LogVerbosity to Debug and try to get back to you.

**Comment by JKorf** [comment]
I've run the code yesterday from a couple of hours, doing the request every second. One time the call didn't complete in 30 seconds, but I missed that one x). Trying again today.

**Comment by JKorf** [comment]
Thanks for the info. Before you send the request that times out the log contains `Exception logged: One or more errors occurred.`, where is that coming from?

**Comment by Atari800Bootcamp** [comment]
That is my code catching an exception, so I have tweaked it to break out and report aggregation exceptions. I'll let you know what I find when I next see it.

**Comment by JKorf** [comment]
Hi, do you have any update on this? Is it still happening?

**Comment by Atari800Bootcamp** [comment]
Hi, yes it is still happening. In last 20 hours it happened 5 times. Each time my code does a time out at 30s and continues. I'll add the logging in again and switch on tracing, hopefully finding something useful.

**Comment by Atari800Bootcamp** [comment]
Attached is a log for last few transactions before it hangs for 30s. Hope this helps.

[BinanceTimeoutCapture.txt](https://github.com/JKorf/Binance.Net/files/2069745/BinanceTimeoutCapture.txt)

**Comment by crypt0d3v** [comment]
Being paranoid, but might be worth you changing your api key with that signature at the end of your file

**Comment by Atari800Bootcamp** [comment]
Not sure I follow?

**Comment by JKorf** [comment]
I've been unable to reproduce this and can't trace it based on existing information. If the issue still exists in the latest version of the library please re-open and provide new debug logging.
