### ISSUE TITLE
Margin problem

### ISSUE THREAD

**Issue by azzars** [JKorf/Binance.Net#800]
I'm having a problem with the margin orders.
Regular orders work fine for me, but everything that is relevant for margin gives me this error:
"Signature for this request is not valid."

**Comment by JKorf** [comment]
Make sure you have the correct permissions enabled on your API key on the Binance site

**Comment by azzars** [comment]
I do, it works for other orders like buy and sell.
it just doesn’t work for margin orders like transfer and borrow.

**Comment by azzars** [comment]
I checked in the margin trade, is there anything else I should do?

**Comment by JKorf** [comment]
There are 2 checkboxes, `Enable Spot & Margin Trading` and `Enable Margin`. I imagine you need them both.

**Comment by azzars** [comment]
Do I need any other restriction?

**Comment by azzars** [comment]
Done that (see image)

**Comment by JKorf** [comment]
You can try creating a new API key with those things enabled, sometimes older keys give problems. If that doesn't help then I don't know what the issue is

**Comment by azzars** [comment]
Thanks, is it working on your side?

**Comment by JKorf** [comment]
Yes
