### ISSUE TITLE
withdraw endpoint to be discontinued on august 1st

### ISSUE THREAD

**Issue by Sasja** [JKorf/Binance.Net#803]
**Describe the bug**

Some endpoints that binance.net relies on are about to be retired.

![image](https://user-images.githubusercontent.com/6564082/125831905-989dd5a5-6984-4e96-9670-85b97972c753.png)
https://binance-docs.github.io/apidocs/spot/en/#change-log

![image](https://user-images.githubusercontent.com/6564082/125832045-52d1e0a4-b917-453d-9941-87e82f99e5c4.png)
![image](https://user-images.githubusercontent.com/6564082/125832674-c27f137a-a87b-4279-8895-02386ef39522.png)

**Comment by JKorf** [comment]
New version has been released with all wapi endpoints replaced by sapi endpoints
