### ISSUE TITLE
Cannot place a Future Market Order?

### ISSUE THREAD

**Issue by WantHelp** [JKorf/Binance.Net#805]
This is my Code
`round = 10 / price;
round = Math.Round(round);
                binancle.FuturesUsdt.ChangeInitialLeverage("DOGEUSDT", 2);
                binancle.FuturesUsdt.ChangeMarginType("DOGEUSDT", FuturesMarginType.Cross);
                binancle.FuturesUsdt.Order.PlaceOrder("DOGEUSDT", OrderSide.Buy, OrderType.Market, round);`

I have been trying to place order with this code which I think is right. but still cant place order. Or is there Another Way.
please Help and thank you

**Comment by JKorf** [comment]
https://github.com/JKorf/CryptoExchange.Net#response-handling

**Comment by WantHelp** [comment]
Thanks ... but it was a problem of API permission. I had not enabled Future options

**Comment by WantHelp** [comment]
Now I can place order with the same code but I cannot place a order more than 1X Leverage.

**Comment by JKorf** [comment]
You should be checking what the output is, which should tell you what the problem is with your calls

**Comment by WantHelp** [comment]
Thank you. I will find out
