### ISSUE TITLE
Random results with Client.Spot.Order.GetMyTradesAsync

### ISSUE THREAD

**Issue by gensleralexander** [JKorf/Binance.Net#807]
**Describe the bug**
I'm getting different results for the API calls, specially on ADABNB and MATICBNB pair (there could be more however).
I added a small console program which I used to test (do 10 times the same call for both pairs).

**To Reproduce**
```
using Binance.Net;
using Binance.Net.Objects.Spot.SpotData;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Cryp2FA.ConsoleTest
{
    public class Program
    {
        static void Main(string[] args)
        {
            BinanceClient Client = new BinanceClient(new Binance.Net.Objects.Spot.BinanceClientOptions());
            Client.SetApiCredentials("<AddKeyHere>", "<AddSecretHere>"); //Add yours here for testing
            DateTime startTime = new DateTime(2017, 7, 1);
            List<BinanceTrade> trades = new List<BinanceTrade>();
            for (int i = 0; i < 10; i++)
            {
                Console.WriteLine("Call " + i);
                var resultADA = Client.Spot.Order.GetMyTradesAsync("ADABNB", startTime, null, 1000, null, null, default).Result;
                Task.Delay(1500).Wait();
                var resultMATIC = Client.Spot.Order.GetMyTradesAsync("MATICBNB", startTime, null, 1000, null, null, default).Result;
                Task.Delay(1500).Wait();
                if (resultADA.Success)
                {
                    trades.AddRange(resultADA.Data);
                    Console.WriteLine(resultADA.Data.Count() + " ADA added");
                }
                else { Console.WriteLine(resultADA.Error.Message); }
                if (resultMATIC.Success)
                {
                    trades.AddRange(resultMATIC.Data);
                    Console.WriteLine(resultMATIC.Data.Count() + " MATIC added");
                }
                else { Console.WriteLine(resultMATIC.Error.Message); }
            }
        }
    }
}
```

**Expected behavior**
There should be 11 ADABNB Trades and 3 MATICBNB trades.

**Results**
This are the Console results:
Call 1
11 ADA added
3 MATIC added
Call 2
1 ADA added
0 MATIC added
Call 3
11 ADA added
3 MATIC added
Call 4
1 ADA added
3 MATIC added
Call 5
1 ADA added
3 MATIC added
Call 6
11 ADA added
3 MATIC added
Call 7
11 ADA added
0 MATIC added
Call 8
11 ADA added
0 MATIC added
Call 9
11 ADA added
3 MATIC added
Call 10
1 ADA added
0 MATIC added

As the results show, there are for both calls two results possible (for ADA either 1 or 11 trades and for MATIC either 0 or 3 trades).
It also makes no difference whether I use a DateTime for startTime or leave it null.
The same goes for endTime. Only when I set both parameters I do get an error message that both parameters are more than 24 hours apart.

Does anyone else experience this?

/edit: Interestingly, these 10 ADA trades and the 3 MATIC trades are the 13 most recent trades in my account history.

**Comment by JKorf** [comment]
That is pretty weird, I agree. I haven't experienced this myself, and when I run your provided test program it returns the same info for each call as I'd expect.. 
If you enable debug logging in the client options you could verify that the same request each time returns different results. That would mean there is an issue on Binance` side.

**Comment by gensleralexander** [comment]
[Logs.txt](https://github.com/JKorf/Binance.Net/files/6867333/Logs.txt)

@JKorf I've attached the logs, but as far as I can see the only difference between the calls is the Timestamp and Signature parameters which should be normal. So it seems like there is an issue with the API.
Do you have any idea where I can open a ticket for that?

**Comment by JKorf** [comment]
There seem to be more people with the same issue:
https://dev.binance.vision/t/api-v3-allorders-is-giving-different-response-everytime/4886
https://dev.binance.vision/t/api-v3-allorders-is-buggy-as-it-returns-incomplete-response/4954/2
https://dev.binance.vision/t/not-all-trades-listed-in-response-to-api-v3-mytrades/4907

No solution listed yet however. Maybe you could join in the discussion there with the results you're seeing.

**Comment by gensleralexander** [comment]
@JKorf thanks for the links, quite interesting.
I also opened a ticket at binance support.
I'll close this issue here as it is no bug in your code.
