### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by Den4ikzxc** [JKorf/Binance.Net#81]
Hi!
Tried to install this package and using NuGet and get this error on **every** .NET framework version (4.5-4.6 too):
"Error Could not install package 'Binance.Net 3.1.3'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."

VS2015 - max .net version 4.6.1.

Someone know whats can be problem?

p.s. Also same problems with Bittrex and Bitfinex API.

**Comment by keefehiggins** [comment]
I have 2 suggestions. 

1. You can install the .net framework 4.71 and upgrade your projects.
2. You can choose a lower version of binance.net until it builds with your project.

I had the same issue initially and just upgraded my version of .net in the end. I cant remember what version of binance.net supported 4.61.

**Comment by JKorf** [comment]
Hi,

.Net version 4.6.1 is supported, however it initially wasn't in VS2015, they  added support for .NetStandard2.0 (which the libraries are) later on. This means you have to make sure everything is up to date. Make sure your VisualStudio has the latest update, and update the NuGet client using this installer:
https://dist.nuget.org/visualstudio-2015-vsix/latest/NuGet.Tools.vsix
Let me know if that helps.

**Comment by Den4ikzxc** [comment]
Thank you!
After installing from you link VS give me error that i need to download that:
https://aka.ms/netstandard-build-support-netfx
And after that all works with 4.6.1. 💯
