### ISSUE TITLE
Overall market performance over the past 24 hours in percent?

### ISSUE THREAD

**Issue by salocinx** [JKorf/Binance.Net#813]
Hi. I am looking for an indicator that shows me the _overall market performance of the last 24 hours in percent_. I remember having such a value in Coinbase. Is there something similar in the Binance API? And if so, where can I find it? Thank you!

**Comment by JKorf** [comment]
I'm not aware of an overall indicator. You should be able create your own indictor using the individual percentages though.
`binanceClient.Spot.Market.Get24HPricesAsync()` retrieves the 24h change percentages for all symbols.

**Comment by salocinx** [comment]
Thanks for the quick reply and the hint! Will simply calculate the arithmetic average of all 24H prices changes.
