### ISSUE TITLE
How to get ATH prices?

### ISSUE THREAD

**Issue by orionflame** [JKorf/Binance.Net#816]
Hi,

Is it possible to get ATH price or at least yearly ATH? Klines do not have 1 year. Maximum is 1 week so that means I have to get 52 weeks of candles and then calculate it myself?

Thanks a lot.

**Comment by JKorf** [comment]
Hi, no there is no way to directly get the ATH I think. The max kline interval is one month though, and can return a max of 1000 klines in one call. That allows you to get kline data for the last 83 years, which is just enough I think ;)

**Comment by orionflame** [comment]
Thanks a lot @JKorf I didn't notice 1 month. Is it this function for spot?
socketClient.Spot.SubscribeToKlineUpdatesAsync

Because I didn't see an argument that allows me to specify how many klines I can get. I do recall seeing something like that but can't remember which function it was.

Thanks again!

**Comment by JKorf** [comment]
The SubscribeToKlineUpdatesAsync on the socket client is only for receiving updates for the most recent kline. If you want to retrieve historical data, which you need for the ATH, then you need to use the rest client: `binanceClient.Spot.Market.GetKlinesAsync`

**Comment by orionflame** [comment]
Thanks a lot @JKorf will use this one now for ATH, amazing!
