### ISSUE TITLE
Does socketClient.Spot.SubscribeToKlineUpdatesAsync not accept IEnumerable type anymore in the latest update?

### ISSUE THREAD

**Issue by orionflame** [JKorf/Binance.Net#817]
Hi,

I updated my library to the latest but now VS complains that the above function does not accept IEnumerable. Is there a new function or do I have to loop over my collection manually?

Thanks a lot!

**Comment by JKorf** [comment]
Should still be available, how are you calling it?

**Comment by orionflame** [comment]
Thanks a lot @JKorf , this is how I was calling it no change in code:

			sub = socketClient.Spot.SubscribeToKlineUpdatesAsync ( symbols, KlineInterval.OneWeek, data =>
			{
				var coin = MarketData.Coins.FirstOrDefault ( c => c.SymbolPair == data.Symbol );
				if ( coin != null )
				{
					coin.LastWeekOpenPrice = data.Data.Open;
					coin.LastWeekClosePrice = data.Data.Close;
					coin.LowestWeeklyPrice = data.Data.Low;
				}
			} );
			tasks.Add ( sub );

symbols is IEnumerable<string>

**Comment by JKorf** [comment]
In the update some overloads were added, but none were removed. It seems to be fine on my end:
````C#
var x1 = await iclient.Spot.SubscribeToKlineUpdatesAsync("symbol", KlineInterval.EightHour, data =>
{

});
var x2 = await iclient.Spot.SubscribeToKlineUpdatesAsync(new List<string>() { "symbol" }, KlineInterval.EightHour, data =>
{

});
var x3 = await iclient.Spot.SubscribeToKlineUpdatesAsync("symbol", new List<KlineInterval> { KlineInterval.EightHour }, data =>
{

});
var x4 = await iclient.Spot.SubscribeToKlineUpdatesAsync(new List<string>() { "symbol" }, new List<KlineInterval> { KlineInterval.EightHour }, data =>
{

});
````

Have you cleaned the solution, maybe restarted VS?

**Comment by orionflame** [comment]
Thanks a lot @JKorf, after cleaning it did remove those errors very strange. Now it's giving a lot of XAML errors:

Error	XDG0008	The name "MarketData" does not exist in the namespace "clr-namespace:ProfitTracker".

Not sure why just upgrading causes all kinds of wrecks like this when I didn't change anything. I will try to fix it.

**Comment by orionflame** [comment]
Also in your code is iclient, BinanceClient or BinanceSocketClient? Because I am using the latter. Here is the available overloads that show up for me:

```
		//
		// Summary:
		//     Subscribes to the candlestick update stream for the provided symbol
		//
		// Parameters:
		//   symbol:
		//     The symbol
		//
		//   interval:
		//     The interval of the candlesticks
		//
		//   onMessage:
		//     The event handler for the received data
		//
		// Returns:
		//     A stream subscription. This stream subscription can be used to be notified when
		//     the socket is disconnected/reconnected
		Task<CallResult<UpdateSubscription>> SubscribeToKlineUpdatesAsync ( string symbol, KlineInterval interval, Action<IBinanceStreamKlineData> onMessage );
		//
		// Summary:
		//     Subscribes to the candlestick update stream for the provided symbol and intervals
		//
		// Parameters:
		//   symbol:
		//     The symbol
		//
		//   intervals:
		//     The intervals of the candlesticks
		//
		//   onMessage:
		//     The event handler for the received data
		//
		// Returns:
		//     A stream subscription. This stream subscription can be used to be notified when
		//     the socket is disconnected/reconnected
		Task<CallResult<UpdateSubscription>> SubscribeToKlineUpdatesAsync ( string symbol, IEnumerable<KlineInterval> intervals, Action<IBinanceStreamKlineData> onMessage );
		//
		// Summary:
		//     Subscribes to the candlestick update stream for the provided symbols and intervals
		//
		// Parameters:
		//   symbols:
		//     The symbols
		//
		//   intervals:
		//     The intervals of the candlesticks
		//
		//   onMessage:
		//     The event handler for the received data
		//
		// Returns:
		//     A stream subscription. This stream subscription can be used to be notified when
		//     the socket is disconnected/reconnected
		Task<CallResult<UpdateSubscription>> SubscribeToKlineUpdatesAsync ( IEnumerable<string> symbols, IEnumerable<KlineInterval> intervals, Action<IBinanceStreamKlineData> onMessage );
```

**Comment by orionflame** [comment]
After I change the code to this, it works:

`sub = socketClient.Spot.SubscribeToKlineUpdatesAsync ( symbols, symbols.Select ( s => KlineInterval.OneWeek ), data =>`

**Comment by JKorf** [comment]
My bad, you're right. The latest release version had missing overload (the beta version didn't). I've pushed a fix for this, if you update to 6.13.6 in a few minutes it should be available to you again.

**Comment by orionflame** [comment]
Thanks a lot @JKorf, will update to the latest asap :)

**Comment by orionflame** [comment]
Thanks a lot @JKorf, it works now :)
