### ISSUE TITLE
Is Kline data from Binance correct?

### ISSUE THREAD

**Issue by orionflame** [JKorf/Binance.Net#819]
Hi,

So I am getting ATH prices using:

`client.Spot.Market.GetKlinesAsync ( coin.SymbolPair, KlineInterval.OneMonth );`

but when I check the results it doesn't seem to be correct when I compare the ATH prices here:
https://cryptorank.io/ath

For example Nano returns ATH for about $17, but crypto rank says $37, and it's from 2018 so binance existed since then.

Am I missing something? I tried no limit and also using 120 as the limit but same result.

Thanks a lot in advance!

**Comment by JKorf** [comment]
Hi, that's because Binance listed Nano in April 2019, so after the 37$ ATH.

**Comment by orionflame** [comment]
Thanks a lot that makes sense :) Because a lot of coins show the yearly ATH and regular ATH the same, I guess because I am using newer coins.
