### ISSUE TITLE
Needed function to resynchronize Timestamp

### ISSUE THREAD

**Issue by jukoson** [JKorf/Binance.Net#82]
Thanks for this nice Api!

I am having an issue where I use autotimestamp and let it synchronize at the very beginning of my program. After a couple days, however, I see the following Error Message appear:
PlaceOrder: Server error: {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."}"
Most of the times, this error appears repeatedly and I have to abort whichever operation I am trying to execute.

Could you implement a way to resynchronize server and local time ?

**Comment by JKorf** [comment]
Hi, 

I've added a parameter (resetAutoTimestamp) to the GetServerTime request. If you set this to true it will recalculate the difference between the server and local time, hope that helps you!

**Comment by jukoson** [comment]
Yes great, thanks !
