### ISSUE TITLE
Implement new ApiRestrictions endpoint

### ISSUE THREAD

**Issue by fxbrandon** [JKorf/Binance.Net#820]
https://binance-docs.github.io/apidocs/spot/en/#change-log

Considering binance changelog, on 2021-07-16 Binance added new endpoint for apiRestrictions --> **/sapi/v1/account/apiRestrictions**

¿Could be possible to be implemented?

Many thanks.

**Comment by JKorf** [comment]
Hi, this has been implemented in the latest beta version. The beta will be released soon, but the beta package is also available on nuget
