### ISSUE TITLE
Is there a way to get the USD value of an account?

### ISSUE THREAD

**Issue by orionflame** [JKorf/Binance.Net#824]
Hi,

Instead of manually adding the value of all symbols in the account, is there a way to get the current value of the account?

Thanks a lot in advance!

**Comment by nikkozp** [comment]
Hi
1. Client.FuturesUsdt.Account.GetBalanceAsync()
2. Client.FuturesUsdt.Account.GetAccountInfoAsync()
3. Client.General.GetAccountInfoAsync()

**Comment by nikkozp** [comment]
in binance USD = BUSD

**Comment by orionflame** [comment]
Thanks but this just shows every possible token and so you have to check each of them? Also this will give you the number of tokens for each but not their USDT value no?

I am basically looking for the value Binance app shows in the Wallet section that's the total BTC and USD value of the account.

**Comment by z1net** [comment]
@orionflame, same problem.

**Comment by orionflame** [comment]
Yes it seem to be the case. But the issue is, there are some balances binance will just not report due to API limitations so you will miss them. Like if I lock a coin for savings (locked savings), those are gone from your account.

So without these and who knows what else is missing you will not get the actual total net worth in USD.

**Comment by JKorf** [comment]
I suggest asking this on the Binance developer forum and see what they say about this
https://dev.binance.vision/
