### ISSUE TITLE
Precision on the PlaceOrder 

### ISSUE THREAD

**Issue by stonebirdarchitect** [JKorf/Binance.Net#829]
When I've purchased some amount of ETH (0.00624231 for example) I can't sell this very amount back. In fact I have to downgrade it to 0.0062 to it to go through, and .00004231 will just sit there doing nothing. Is there any possible workaround to be able to clear out the wallet with the transaction?

**Comment by nikkozp** [comment]
Hi
1. Use BNB for commissions
2. U can convert low quantities to BNB in your wallet

**Comment by stonebirdarchitect** [comment]
Thanks for the suggestion, works for me
