### ISSUE TITLE
Is there a way to get the active pools of an account?

### ISSUE THREAD

**Issue by orionflame** [JKorf/Binance.Net#830]
Hi,

So for example if I have am liquidity providing to 2 different pools like USDT/DAI, BUSD/DAI, to get the names of these.

When I look at BinanceClient.BSwap, I see some methods but they seems either about all pools or pool records. I want to be able to access my pools similar to my token holdings, to get all of them in my account.

Thanks a lot in advance!

**Comment by JKorf** [comment]
Hi, I'm not too familiar with the BSwap API, but are you maybe looking for `BSwap.GetPoolLiquidityInfoAsync()`? The poolId parameter is optional

**Comment by orionflame** [comment]
Thanks @JKorf, I just called that function:

BinanceClient.BSwap.GetPoolLiquidityInfoAsync ( ).Result;

.Data is null and message returns "No data points provided for the private end point"?

I don't know what I need to provide to it.

**Comment by JKorf** [comment]
Hm that's weird, it works for me. Can you share debug logging?

**Comment by orionflame** [comment]
You mean the error message?

"{: No credentials provided for private endpoint }"

Or is there an argument I can set to get it for the API?

**Comment by JKorf** [comment]
You can enable debug logging by setting it in the client options:
````C#
var binanceClient = new BinanceClient(new BinanceClientOptions{
  LogLevel = LogLevel.Debug
});
````

But the message you posted indicates that you didn't set the API credentials, which you can also set in the client options

**Comment by orionflame** [comment]
Thanks a lot you are right @JKorf, it works. But it returns all available pools. How can I check which ones I have in my account as liquidity provider?

**Comment by JKorf** [comment]
Again, I'm not familiar with the BSwap API, but isn't the Share property what you're looking for?

**Comment by orionflame** [comment]
Thanks @JKorf, you are right it works! I will investigate how to find out the PNL from this.
