### ISSUE TITLE
Request Problem/Stop, Universal Transfer

### ISSUE THREAD

**Issue by jcardonne** [JKorf/Binance.Net#834]
**Describe the bug**
Hi, I'm trying to make a request to transfer usdt from my SPOT wallet to my futures wallet, but when I execute the request it creates itself but doesn't come back (see the logs).

**To Reproduce**
[CODE](https://pastebin.com/XZHnzUS9)

**Expected behavior**
Please tell me if the error comes from my code or from the interface or network.

**Debug logging**
_2021/08/13 23:42:19:770 | Debug | Binance    | Client configuration: LogLevel: Debug, Writers: 1, OutputOriginalData: False, Credentials: Set, BaseAddress: https://api.binance.com/, Proxy: -, RateLimiters: 0, RateLimitBehaviour:
Wait, RequestTimeout: 00:00:30, CryptoExchange.Net: v4.0.0.0, Binance.Net: v7.0.0.0
2021/08/13 23:42:19:832 | Debug | Binance    | [1] Creating request for https://api.binance.com/api/v3/time
2021/08/13 23:42:19:844 | Debug | Binance    | [1] Sending GET request to https://api.binance.com/api/v3/time

Process finished with exit code 0._

**Comment by JKorf** [comment]
Based on the logging I'd say you're not awaiting the call somewhere, and the program completes before the response comes back

**Comment by jcardonne** [comment]
Found, thanks!
