### ISSUE TITLE
GetExchangeInfoAsync now broken for multiple symbols

### ISSUE THREAD

**Issue by wclark17** [JKorf/Binance.Net#838]
**Describe the bug**
In BinanceCleintSpotSystem.cd, on line 141, you commented out 
// parameters.Add("symbols", $"[\"{string.Join("\",\"", symbols)}\"]");
and replaced it with
parameters.Add("symbols", symbols.ToArray());

This causes an error from Binance when requesting more that one symbol

**To Reproduce**
Call
Spot.System.GetExchangeInfoAsync(symbols, ct: CancellationToken.None);
Where symbols is a list

**Comment by GLipitch** [comment]
https://github.com/JKorf/Binance.Net/pull/843 @JKorf

**Comment by JKorf** [comment]
Has been merged and is available in the latest version
