### ISSUE TITLE
Field AccumulatedQuantityOfFilledTrades  in BinanceStreamOrderUpdate is always set into -0.00000001

### ISSUE THREAD

**Issue by NektoDron** [JKorf/Binance.Net#84]
I see field AccumulatedQuantityOfFilledTrades  in BinanceStreamOrderUpdate is always set into -0.00000001
Is it normal?
For example the first string is New order:
13:11:25.65[102]DEBUG:[Binance] OnOrderUpdateMessage: 20277859:-1:16.05.2018 10:11:27:GoodTillCancel:New:0.00000000:0.00000000:0.05000000:0.00000000:-0.00000001

The second is Executed and fully filled:
13:11:25.69[102]DEBUG:[Binance] OnOrderUpdateMessage: 20277859:2680197:16.05.2018 10:11:27:GoodTillCancel:Filled:0.00000000:0.00000000:0.05000000:0.05000000:-0.00000001

0.05 is the order quantity.

**Comment by JKorf** [comment]
Hi, I had a quick look, and this is a bug. The field is wrongly mapped from 'l' (lower) where it should be 'L'.
However, I'm currently on holiday so I won't be able to fix it until in about 2 weeks, sorry. I'll update it when I get back.

**Comment by NektoDron** [comment]
No, It's mapped as 'z' now and should be 'z'.
https://github.com/binance-exchange/binance-official-api-docs/blob/master/user-data-stream.md

**Comment by NektoDron** [comment]
The problem exists because Binance sends undefined property 'Z' with value '-0.00000001'
11:17:21.08[148]DEBUG:[Binance] API: 2018/05/19 11:17:21:042 | Debug | {"e":"executionReport","E":1526717845164,"s":"ZECBTC","c":"1340417368","S":"SELL","o":"MARKET","f":"GTC","q":"0.10000000","p":"0.00000000","P":"0.00000000","F":"0.00000000","g":-1,"C":"null","x":"NEW","X":"NEW","r":"NONE","i":21524635,"l":"0.00000000","z":"0.00000000","L":"0.00000000","n":"0","N":null,"T":1526717845162,"t":-1,"I":45964177,"w":true,"m":false,"M":false,"O":-1,"Z":"-0.00000001"}

Iэму made unused property in the BinanceStreamOrderUpdate and all works fine now:
        [JsonProperty("Z")]
        public decimal FakeAccumulatedQuantityOfFilledTrades { get; set; }

I think it's the bug in the NewtonJson library,  It makes mapping without case sensitivity.

**Comment by JKorf** [comment]
Hi, indeed the json library chooses to ignore the casing if the specific lower/upper case mapping isn't found. I've added a dummy property so now it doesn't override the other property in the latest version.

Thanks for the heads up.
