### ISSUE TITLE
create factory pattern to use multi exchanges

### ISSUE THREAD

**Issue by overstartup** [JKorf/Binance.Net#845]
There is any example to use several exchanges?
i mean, how i can be trading with binance and other . I want to have simple and less coding structure.

**Comment by overstartup** [comment]
No solution?

**Comment by JKorf** [comment]
There is no cut out way for this that I'm aware of. All exchange clients do however implement the IExchangeClient interface, which will allow you to talk to an exchange without knowing the details. This will only work for the high level functionality though.
