### ISSUE TITLE
SubAccount.TransferSubAccountAsync is not working in the last release 7.0.5

### ISSUE THREAD

**Issue by liberalmeida** [JKorf/Binance.Net#846]
We are using this method in version 6.13 and it's working fine.
Then we upgrade it to version 7.0.5 and now is not working anymore.
We are having the following exception as a result: **-1102: fromAccountType is not null**

Looking forward to have it fixed, because we recognized that the new version has a lot of improvements.

Regards,
Liber

**Comment by JKorf** [comment]
Thanks for the report. I'm not sure if it worked before, since the method hasn't changed and I don't see any change in the change logs.. Either way, I've updated the method with the latest documentation, so it should work for you now.
