### ISSUE TITLE
Stop working FuturesUsdt.GetPositionInformationAsync and FuturesUsdt.Account.GetAccountInfoAsync

### ISSUE THREAD

**Issue by usuf13** [JKorf/Binance.Net#849]
**Describe the bug**
After update to latest version  (7.1.0) FuturesUsdt.GetPositionInformationAsync and FuturesUsdt.Account.GetAccountInfoAsync return serialization error

**Debug logging**
[6] Deserialize JsonReaderException: Error reading date. Unexpected token: Integer. Path '[0].updateTime', line 1, position 332., Path: [0].updateTime, LineNumber: 1, LinePosition: 332
as I see in json updateTime is integer
"notional":"0","isolatedWallet":"0","updateTime":0},
in model BinancePositionDetailsUsdt
public DateTime UpdateTime { get; set; }

as I understand from source code "[JsonConverter(typeof(TimestampConverter)), JsonProperty("time")]" is missing

**Comment by JKorf** [comment]
Thanks, for the report, this should be fixed in version 7.1.1

**Comment by usuf13** [comment]
works in 7.1.2
