### ISSUE TITLE
Wrong subAccountAssetsEndpoint Version and Deserialization on BinanceSubAccounTransferResult

### ISSUE THREAD

**Issue by Gustavobbr** [JKorf/Binance.Net#852]
Hello Jkorf,

Following two fixes :

Wrong subAccountAssetsEndpoint Version
![image](https://user-images.githubusercontent.com/37227910/131760226-41aefb81-7c23-454c-baca-789b6c35736d.png)

Wrong Deserialization on BinanceSubAccounTransferResult
![image](https://user-images.githubusercontent.com/37227910/131760256-75b718da-0bd4-4e6d-a529-98b4524f02fd.png)

**Comment by JKorf** [comment]
Has been fixed in the latest version
