### ISSUE TITLE
new feature: POST /sapi/v1/sub-account/universalTransfer (HMAC SHA256)

### ISSUE THREAD

**Issue by milannovis** [JKorf/Binance.Net#853]
Hi, 
I can't find this implemented in your wrapper or any other way to transfer assets FROM master account TO a subAccount. (from master email to sub email) 

Do you plan to implement this?

**Comment by JKorf** [comment]
Hi, you can use `client.SubAccount.TransferSubAccount` for this. If you leave the fromEmail null it will use the master account as source
