### ISSUE TITLE
Is there a way to split the symbol pairs using the API?

### ISSUE THREAD

**Issue by orionflame** [JKorf/Binance.Net#858]
Hi,

Basically Binance uses the combined symbol pair without any separator like BTCUSDT, but what's the best method to split these into BTC and USDT? It seems really silly they didn't use some separator character.

Right now I am using stable pairs so I hard code to see if they have that in the end, etc, but seems not as robust obviously.

Any ideas?

**Comment by GLipitch** [comment]
I agree that it's silly. 
The robust workaround is to call `var symbols = (await binanceClient.Spot.System.GetExchangeInfoAsync()).Data.Symbols;` and use the Name, BaseAsset and QuoteAsset properties.

**Comment by JKorf** [comment]
I agree, I prefer exchanges using a `-` or `/` as a separator char.. Generally if an exchange doesn't have a separator in the symbol name there is some way of retrieving it in the API. As @GLipitch  mentioned, you can use the GetExchangeInfoAsync call to retrieve the base/quote assets for a symbol.

**Comment by caffreysbb** [comment]
> I agree, I prefer exchanges using a `-` or `/` as a separator char.. Generally if an exchange doesn't have a separator in the symbol name there is some way of retrieving it in the API. As @GLipitch mentioned, you can use the GetExchangeInfoAsync call to retrieve the base/quote assets for a symbol.

GetExchangeInfoAsync return null in last version
