### ISSUE TITLE
WaitingForActivation Status when executing GetOpenOrdersAsync()

### ISSUE THREAD

**Issue by Ruthy85** [JKorf/Binance.Net#861]
Hello,

I am executing other async methods successfully, however, when I am trying to query the open orders (with or without the symbol argument), I am getting the Result = null with Status = WaitingForActivation.  
I am working with .Net framework 4.7.2.
It seems an issue with the threading, that maybe it is not yet computed. Any advise? Thank you

**Comment by GLipitch** [comment]
If the call is within an async method, put await before the call. If not, put .Result at the end of the call - GetOpenOrdersAsync().Result.

**Comment by Ruthy85** [comment]
The call is not within async method.
GetOpenOrdersAsync().Result instead of awaiting to the Task WebCallResult and later look for Result, does the trick! 👍 
Thank you very much for your support!
