### ISSUE TITLE
Stop and start web socket

### ISSUE THREAD

**Issue by naserkaka** [JKorf/Binance.Net#862]
Hi, I would like to start and stop web socket with my bot.

Im doing following

public void startSocket(){
                BinanceNet binance = new BinanceNet();
                await binance.StreamPrice(); // calling a method that starts the websocket
                }
public void stopSocket(){
           socketclient.Dispose();
              }
              
     
     the startSocket works fine and when disposing with stopSocket it also work, but if I stopSocket and then try to startSocket it does not work.

**Comment by CarlPrentice** [comment]
I had a similar issue in my code that I fixed.
Is that all of your code for those two methods?
Are you setting any options or credentials for the API?
It would be helpful to see more of the code.

**Comment by naserkaka** [comment]
Hi @CarlPrentice , this is the BinanceNet class 

      public BinanceNet()
        {


            var key = "xxxxxxxxxxxx";
            var secret = "xxxxxxxxx";
            var testUrl = "https://testnet.binance.vision/";
            BinanceClient.SetDefaultOptions(new BinanceClientOptions(testUrl, testUrl, testUrl)
            {
                RequestTimeout = new TimeSpan(0, 0, 0, 0, 10000),
                ReceiveWindow = new TimeSpan(0, 0, 0, 0, 1000),
                RateLimitingBehaviour = RateLimitingBehaviour.Fail,
                ApiCredentials = new ApiCredentials(key, secret),
                LogVerbosity = LogVerbosity.Debug,
                LogWriters = new List<TextWriter> { Console.Out }
            });
            BinanceSocketClient.SetDefaultOptions(new BinanceSocketClientOptions()
            {
                ApiCredentials = new ApiCredentials(key, secret),
                LogVerbosity = LogVerbosity.Debug,
                LogWriters = new List<TextWriter> { Console.Out }
            });


        }
        
        I call this BinanceNet() when calling startSocket
        
        the await binance.StreamPrice() is calling this StreamPrice() method
        
         public async Task StreamPrice()
        {


            try
            {

                if (socketclient == null)
                {
                    socketclient = new BinanceSocketClient();

                    var listenResult = await socketclient.Spot.SubscribeToAggregatedTradeUpdatesAsync(tickers, data =>
                        {
                            Console.WriteLine(data.Price);
                   }}}}

**Comment by GLipitch** [comment]
"LogVerbosity" makes me think you are using an old version. I suggest not using an old version.

**Comment by naserkaka** [comment]
Yes I have version 6.13.3 I will update now to 7.1.2.

**Comment by GLipitch** [comment]
upgrade tip:
```
LogVerbosity = LogVerbosity.Debug,
LogWriters = new List<TextWriter> { Console.Out }
```
becomes
```
LogLevel = LogLevel.Debug,
LogWriters = new List<ILogger> { new DebugLogger() },
```

**Comment by naserkaka** [comment]
So how can I stop and start my web socket when streaming data price?

right now my startWebsocket is to call this=>
        
                BinanceNet binance = new BinanceNet();
                await binance.StreamPrice();
   
            
                  public BinanceNet()
        {


            var key = "xxxxxx";
            var secret = "xxxxxx";
            var testUrl = "https://testnet.binance.vision/";
            BinanceClient.SetDefaultOptions(new BinanceClientOptions(testUrl, testUrl, testUrl)
            {
                RequestTimeout = new TimeSpan(0, 0, 0, 0, 10000),
                ReceiveWindow = new TimeSpan(0, 0, 0, 0, 1000),
                RateLimitingBehaviour = RateLimitingBehaviour.Fail,
                ApiCredentials = new ApiCredentials(key, secret),
                LogLevel = LogLevel.Debug,
                LogWriters = new List<ILogger> { new DebugLogger() },
            });
            BinanceSocketClient.SetDefaultOptions(new BinanceSocketClientOptions()
            {
                ApiCredentials = new ApiCredentials(key, secret),
                LogLevel = LogLevel.Debug,
                LogWriters = new List<ILogger> { new DebugLogger() },
            });


        }

            
            // StreamPrice
            
             public async Task StreamPrice()
        {
            try
            {

                if (socketclient == null)
                {
                    socketclient = new BinanceSocketClient();

                    var listenResult = await socketclient.Spot.SubscribeToAggregatedTradeUpdatesAsync(tickers, data =>
                        {
                            Console.WriteLine(data.Data.Price);
                     }}}}
        
           
           
           and my stopWebsocket is  =>

                var result = Task.Run(async () => await BinanceNet.socketclient.UnsubscribeAllAsync());
  
  
  Once I unsubscribe/dispose I can't start the web socket again

**Comment by GLipitch** [comment]
This code successfully subscribes and unsubscribes in a loop (on latest Binance.Net on dotnet 5). Why not start with something simple like this, and see what code breaks it?
```
    internal class Program
    {
        private static async Task Main(string[] args)
        {
            var socketclient = new BinanceSocketClient(new BinanceSocketClientOptions
            {
                LogLevel = LogLevel.Debug,
                LogWriters = new List<ILogger> { new ConsoleLogger() }
            });

            while (true)
            {
                Console.WriteLine("subscribe");

                var listenResult = await socketclient.Spot.SubscribeToAggregatedTradeUpdatesAsync(new string[] { "BTCUSDT", "ETHBTC" }, data =>
                 {
                     Console.WriteLine(data.Data.Price);
                 });

                await Task.Delay(10_000);

                Console.WriteLine("unsubscribe");

                await socketclient.UnsubscribeAllAsync();

                await Task.Delay(10_000);
            }

            Console.ReadLine();
        }
    }
```

**Comment by naserkaka** [comment]
@GLipitch thank you! it helped!, the code that broke it was the "if(socket==null){ }....." in my StreamPrice() method.
