### ISSUE TITLE
I get this error when using getExchangeinfoAsync().

### ISSUE THREAD

**Issue by Rusifer** [JKorf/Binance.Net#863]
hi,
It was upgraded after using getExchangeinfo()
 I get this error when using getExchangeinfoAsync().
Failed to load Data.Symbols from exchange_Info.Data.Symbols in row 5
 cs1061 error.
I don't know why.
    public List<Quote> GetQuotes()
        {
            List<Quote> items = new List<Quote>();

             var exchange_Info = Client.Spot.System.GetExchangeInfoAsync();
            

          
            foreach (var quote in exchange_Info.**Data**.Symbols)
            {
                try
                {
                    if (quote.Status == SymbolStatus.Trading)
                    {
                        var item = new Quote()
                        {
                            symbol = quote.BaseAsset + quote.QuoteAsset,
                            source = eQuoteSource.Binance,
                            name = quote.BaseAsset + "/" + quote.QuoteAsset,
                            desc = quote.Name,
                        };

                        var symbol_price_filter = quote.Filters.OfType<BinanceSymbolPriceFilter>().FirstOrDefault();
                        if (symbol_price_filter != null)
                        {
                            item.tick_size = symbol_price_filter.TickSize;
                            item.decimal_count = symbol_price_filter.TickSize.GetDecimalPlaces();
                        }
                        else
                        {
                            continue;
                        }
                        items.Add(item);
                    }
                }
                catch (Exception ex)
                {

                }
            }
            /*if(exchange_info.Error.)*/
            return items;
        }

**Comment by GLipitch** [comment]
https://github.com/JKorf/Binance.Net/issues/861

**Comment by JKorf** [comment]
Change the call to Client.Spot.System.GetExchangeInfoAsync().Result;
