### ISSUE TITLE
TimeInForce, set to specific amount of minutes?

### ISSUE THREAD

**Issue by naserkaka** [JKorf/Binance.Net#864]
Hi , I would like to set the timeInForce to a specific amount of minutes instead of the available options right now(GoodTillCancel,ImmediateOrCancel,FillOrKill.....).  I want to delete my order after 10 minutes if not filled.

There is GoodTillExpiredOrCancel, can I customize "Expired" part? when will it expire right now out ?

  result = await client.Spot.Order.PlaceOrderAsync(
                                ticker,
                               OrderSide.Buy,
                               OrderType.Limit,
                               quantity: quantitycalc,
                               price: buyprice,
                              timeInForce: TimeInForce.GoodTillExpiredOrCanceled

                                );

**Comment by JKorf** [comment]
Hi, this is unfortunately not available. The value corresponds with a value that can be returned from the server, but not one that is valid to send for a new order. It is not mentioned in the API documentation, but can be returned from the server on the Futures API. See #495

**Comment by naserkaka** [comment]
@JKorf okey, thank you!
