### ISSUE TITLE
Change in BinanceSymbol

### ISSUE THREAD

**Issue by karloballa** [JKorf/Binance.Net#865]
I fell a little out of rhythm so perhaps I just overlooked something, but is there an event handler when the exchange changes LOT_SIZE on BinanceSymbol?

**Comment by JKorf** [comment]
Hi, no there is no such event. The only way to get the info is polling the GetExchangeInfoAsync call. You can pass in the symbols you're interested in to speed up the call, as retrieving the data for all symbols can be a bit heavy

**Comment by karloballa** [comment]
Thanks,

I suppose the simplest way is just to call GetExchangeInfo(Async) when the LOT_SIZE error happens.

**Comment by JKorf** [comment]
Depends on the project, but yes I would say that's a valid solution

**Comment by karloballa** [comment]
Thanks.
