### ISSUE TITLE
filter failure percent_price when sendin Limit buy order

### ISSUE THREAD

**Issue by naserkaka** [JKorf/Binance.Net#867]
Hi , I get the percent_price error when sending

  result = await client.Spot.Order.PlaceOrderAsync(
                                  "XRPUSDT",
                                 OrderSide.Buy,
                                 OrderType.Limit,
                                 quantity: Convert.ToDecimal(23),
                                 price: Convert.ToDecimal(1.03),
                                timeInForce: TimeInForce.GoodTillCancel )
                                
    The current XRPUSDT price is 1.0759  and I am using Testnet if that make any sense.

**Comment by karloballa** [comment]
> Hi , I get the percent_price error when sending
> 
> result = await client.Spot.Order.PlaceOrderAsync(
> "XRPUSDT",
> OrderSide.Buy,
> OrderType.Limit,
> quantity: Convert.ToDecimal(23),
> price: Convert.ToDecimal(1.03),
> timeInForce: TimeInForce.GoodTillCancel )
> 
> ```
> The current XRPUSDT price is 1.0759  and I am using Testnet if that make any sense.
> ```

Well, I have the same problems with XRPBTC, BNBBTC and ETHBTC, while LTCBTC and TRXBTC work well. I never had such problems on the real exchange, just on the testnet.

**Comment by JKorf** [comment]
I'm not sure what the price filter is on the testnet, you can check by calling client.Spot.System.GetExchangeInfoAsync and looking up the symbol you're interested in

**Comment by karloballa** [comment]
> I'm not sure what the price filter is on the testnet, you can check by calling client.Spot.System.GetExchangeInfoAsync and looking up the symbol you're interested in

The testnet lacks some basic functionality and it is full of bugs. My prog (with your libraries of course) worked for several months on the real net without any problems, but in the testnet errors are popping like crazy.

IMHO, the only way is to risk 200-300 bucks and start with the real exchange. There is however another problem. Binance suspended API trading for accounts with a basic verification. In practice, that means it is impossible to have more than one functional account on Binance. There is a subaccount possibility, but only for big traders. So why it is a big deal? If you have a working program, and you are using it 24 hours a day, where to find a place to test new ideas?!

**Comment by Gh0stD14l3r** [comment]
Im receiving the same error currently too on live. 

ERROR: Error: Filter failure: PRICE_FILTER

Current code for it is...

 var buyResult = await client.Spot.Order.PlaceOrderAsync(symbol, Binance.Net.Enums.OrderSide.Sell, Binance.Net.Enums.OrderType.Limit, quantity: tradeAmount, price: buyPrice, timeInForce: Binance.Net.Enums.TimeInForce.GoodTillCancel);

Is there any reference to what PRICE_FILTER is actually referring to? Is it the price itself?

**Comment by JKorf** [comment]
I agree that the test net (from what I've seen) is pretty buggy and you're probably better of just testing on the main net with a small amount of funds.

@karloballa I understand the issue, but I'm not sure what the solution would be. Maybe contact Binance about this and see what their thoughts about it are? There is a developer forum here:
https://dev.binance.vision/

I'll close this issue since the original issue is resolved.
