### ISSUE TITLE
Delete isolated account

### ISSUE THREAD

**Issue by valvv** [JKorf/Binance.Net#868]
Hi, 
Binance made a new limitation last week.
https://www.binance.com/en/support/announcement/3da6632fc02d49d0ac33f2ceb6607d15
Can you add DeleteIsolatedMarginAccount function, please
DELETE /sapi/v1/margin/isolated/account

**Comment by Jencek1** [comment]
It would be great to have EnableIsolatedMarginAccount that enables deleted account:
POST /sapi/v1/margin/isolated/account

Also there is a flag "enabled" returned by the Binance webservice that is not available in result of GetIsolatedMarginAccountAsync. Is is useful to check if the account is enabled/deleted. 

Thx.

**Comment by JKorf** [comment]
I added these in the latest version
