### ISSUE TITLE
 Socket 1 message processing slow (42158ms), consider offloading data handling to another thread. Data from this socket may arrive late or not at all if message processing is continuously slow.

### ISSUE THREAD

**Issue by naserkaka** [JKorf/Binance.Net#869]
Hi, I am getting this error when streaming crypto prices with websocket using testent. Any idea what to do? How can I offloading data to another thread?

error: Socket 1 message processing slow (42158ms), consider offloading data handling to another thread. Data from this socket may arrive late or not at all if message processing is continuously slow.

I call StreamPrice from another class with => await BinanceNet.StreamPrice()

 public static async Task StreamPrice(){
 var listenResult = await socketclient.Spot.SubscribeToAggregatedTradeUpdatesAsync(tickers, data =>
                        {
                            Console.WriteLine(data.Data.Price);
                           
                           //and code for this function =>
                         //    if price match my price => sendbuyorder to binance.....
                          
                          // this is the end in await socketclient...
                           if (!listenResult.Success)
                    {

                        throw new Exception("Failed to start user stream: " + listenResult.Error.ToString());
                    }

**Comment by naserkaka** [comment]
Hi, I have created thread for handling buy order / sellorder 

    public static async Task StreamPrice()
        {
            Thread threadStream = Thread.CurrentThread;    // !! this StreamPrice  method = CurrentThread right?
            try
            {  
                    socketclient = new BinanceSocketClient(new BinanceSocketClientOptions
                    {
                        LogLevel = LogLevel.Debug,
                        LogWriters = new List<ILogger> { new ConsoleLogger() }
                    });

                if (tickers != null)
                {
                    var listenResult = await socketclient.Spot.SubscribeToAggregatedTradeUpdatesAsync(tickers, data =>
                        {

                            if (data.Data.Symbol.Equals("XRPUSDT") && data.Data.Price <= XrpOrder.buyprice)
                            {
                                  // this is the buy and sell order function placeMarketBuyOrderAsync
                                Thread threadBuy = new Thread(async() => await placeMarketBuyOrderAsync("XRPUSDT", XrpOrder.amountUsdt, XrpOrder.buyprice, XrpOrder.buysell, XrpOrder.sellprice));
                                
                               
                                threadBuy.Start(); // start thread that handles buy order and sell order
                                threadStream.Join(); // wait with this current method from stream price until threadBuy finish
                                threadBuy.Join();   // wait until buy order and sell order succesfully sent
                                threadStream.Start(); // now start streaming price again


                            }
                        });
                        
                        
                        the problem is that it don't starts the streamPrice method again, I stops there after threadBuy.Join(), I would like to start the stream socket again (StreamPrice() method). Is this right approach?

**Comment by CarlPrentice** [comment]
If I've read it correctly, you're attempting to execute long running code within the subscription lambda. That's always going to be a bad idea, and I don't think your threading solution helps that.

You could just spin up a task on the thread pool and return immediately, rather than using Threads and blocking the subscription callback.

**Comment by naserkaka** [comment]
I am doing this in my socketclient.Spot.SubscribeToAggregatedTradeUpdatesAsync
creating a thread that reads incoming bitcoin price, if price match my target price then send buy-market-order to binance, after that, place sell order to. Then my thread1 finishes

 var listenResult = await socketclient.Spot.SubscribeToAggregatedTradeUpdatesAsync(tickers, data =>
                        {
                           // Console.WriteLine(data.Data.Price);


                            if (checkStream)
                            {
                                Telegram.sendMessage("Binance är aktiv,  valuta: " + data.Data.Symbol + " live price: " + data.Data.Price);
                                checkStream = false;
                            }
                            Thread thread1 = new Thread(() => sendStreamData(data));
                            thread1.Start();


                        });


                    if (!listenResult.Success)
                    {

                        throw new Exception("Failed to start user stream: " + listenResult.Error.ToString());
                    }

**Comment by naserkaka** [comment]
do you prefer this? a task instead of thread?

var listenResult = await socketclient.Spot.SubscribeToAggregatedTradeUpdatesAsync(tickers, data =>
{
Task.Run( ()=> sendStreamData(data));
});

my sendStreamData looks like this 
public static void sendStreamData(DataEvent<Binance.Net.Objects.Spot.MarketStream.BinanceStreamAggregatedTrade> data)
        {
         //check currency
         // send buy order market
         // send sell order limit
        // remove order from my database
        
    }

**Comment by naserkaka** [comment]
@CarlPrentice Hi , yes it solved my issue .
