### ISSUE TITLE
Problems with streams

### ISSUE THREAD

**Issue by karloballa** [JKorf/Binance.Net#870]
A few days ago I updated packages from v6.13.4 to v7.1.3 and from v3.9.0 to v4.0.8. Somehow it messed up with streams. I made negligible changes just to accommodate the code to new packages. Now, after some 20 hours, I lose streams. I had a similar problem with the user stream some time ago, but never with the public stream. There is no message just stopped sending data. 
The same thing happens when I debug the code in VS debugger and break execution for a few minutes. Never had similar problems. As I said, I made few changes, mostly replaced old sync methods with async_method().Result. I don't know if I broke something with that.

**Comment by JKorf** [comment]
Hi, the websocket implementation has changed, so it could be that there is some issue in there somewhere. Is it possible for you to reproduce this issue? I'd be very interested. If I put a breakpoint in the data handler and resume after +- 8min the socket reconnects and continues as expected.

**Comment by karloballa** [comment]
It seems I can reproduce the issue every time, however, I don't know what to do with it :)

**Comment by JKorf** [comment]
What are the steps you take to trigger it? It would be great if I can reproduce it on my end

**Comment by karloballa** [comment]
Not much to write about. Put a breakpoint anywhere in the code (I'm using Timer for trading, so I suppose I'm blocking the main thread). Brake the execution for 3 minutes, and then resume. The program receives few ticks, and nothing more. No need to open the user stream, just the public stream.

I'm using Windows Forms.

**Comment by JKorf** [comment]
Thanks, I've been able to reproduce it. Source of the issue is that .NetFramework throws a different kind of exception than dotnet core. I've pushed a new version, 4.2.1, of the CryptoExchange.Net library, can you try installing that version and see if your issue is fixed?

**Comment by karloballa** [comment]
Now it works ;)
Thanks!
