### ISSUE TITLE
Status WaitingForActivation

### ISSUE THREAD

**Issue by Dimarik1Krasnodar93** [JKorf/Binance.Net#872]
Hi! Can anybody help me, please
I wrote code from example. And in does not work
look. v1 has status "waiting for activation".
result null.
v1:
 Asyncstale null
canellationPening null
Creating Options None
Exception null
ID 14
Result null
Status WaitingForActivation
More that 30 seconds!!!!
What is wrong? I copied Code from your console example?
Can anybody help me, please

`class Program
    {
        static void Main(string[] args)
        {
            string _strApiKey = "THERE_WILL_BE_myAPIKEY";
            string _strSecretApiKey = "THERE_WILL_BE_mySecterAPIKEY";

            BinanceClient.SetDefaultOptions(new BinanceClientOptions()
            {
                ApiCredentials = new ApiCredentials(_strApiKey, _strSecretApiKey),
                LogLevel = LogLevel.None,
                LogWriters = new List<ILogger> { new ConsoleLogger() }
            });
            BinanceSocketClient.SetDefaultOptions(new BinanceSocketClientOptions()
            {
                ApiCredentials = new ApiCredentials(_strApiKey, _strSecretApiKey),
                LogLevel = LogLevel.None,
                LogWriters = new List<ILogger> { new ConsoleLogger() }
            });

            using (var client = new BinanceClient())
            {

                Task<WebCallResult<IEnumerable<BinancePrice>>> callResult = client.Spot.Market.GetPricesAsync();
                // Make sure to check if the call was successful
                /* if (!callResult.Success)
                 {
                     // Call failed, check callResult.Error for more info
                     var test = 0;
                 }
                 else
                 {
                     var test2 = 1;
                     // Call succeeded, callResult.Data will have the resulting data
                 }*/

                // Spot.Market | Spot market info endpoints
                var v1 = client.Spot.Market.GetBookPriceAsync("DODOUSDT");
                // Spot.Order | Spot order info endpoints
                var v2 = client.Spot.Order.GetOrdersAsync("BTCUSDT");
                // Spot.System | Spot system endpoints
                var v3 = client.Spot.System.GetExchangeInfoAsync();
                // Spot.UserStream | Spot user stream endpoints. Should be used to subscribe to a user stream with the socket client
                var v4 = client.Spot.UserStream.StartUserStreamAsync();
                // Spot.Futures | Transfer to/from spot from/to the futures account + cross-collateral endpoints
                var v5 = client.Spot.Futures.TransferFuturesAccountAsync("ASSET", 1, FuturesTransferType.FromSpotToUsdtFutures);

                // FuturesCoin | Coin-M general endpoints
                var v6 = client.FuturesCoin.GetPositionInformationAsync();
                // FuturesCoin.Market | Coin-M futures market endpoints
                var v7 = client.FuturesCoin.Market.GetBookPricesAsync("BTCUSD");
                // FuturesCoin.Order | Coin-M futures order endpoints
                var v8 = client.FuturesCoin.Order.GetUserTradesAsync();
                // FuturesCoin.Account | Coin-M account info
                var v9 = client.FuturesCoin.Account.GetAccountInfoAsync();
                // FuturesCoin.System | Coin-M system endpoints
                var v10 = client.FuturesCoin.System.GetExchangeInfoAsync();
                // FuturesCoin.UserStream | Coin-M user stream endpoints. Should be used to subscribe to a user stream with the socket client
                var v11 = client.FuturesCoin.UserStream.StartUserStreamAsync();

                // FuturesUsdt | USDT-M general endpoints
                var v12 = client.FuturesUsdt.GetPositionInformationAsync();
                // FuturesUsdt.Market | USDT-M futures market endpoints
                var v13 = client.FuturesUsdt.Market.GetBookPricesAsync("BTCUSDT");
                // FuturesUsdt.Order | USDT-M futures order endpoints
                var v14 = client.FuturesUsdt.Order.GetUserTradesAsync("BTCUSDT");
                // FuturesUsdt.Account | USDT-M account info
                var v15 = client.FuturesUsdt.Account.GetAccountInfoAsync();
                // FuturesUsdt.System | USDT-M system endpoints
                var v16 = client.FuturesUsdt.System.GetExchangeInfoAsync();
                // FuturesUsdt.UserStream | USDT-M user stream endpoints. Should be used to subscribe to a user stream with the socket client
                var v17 = client.FuturesUsdt.UserStream.StartUserStreamAsync();

                // General | General/account endpoints
                var v18 = client.General.GetAccountInfoAsync();

                // Lending | Lending endpoints
                var v19 = client.Lending.GetFlexibleProductListAsync();

                // Margin | Margin general/account info
                var v20 = client.Margin.GetMarginAccountInfoAsync();
                // Margin.Market | Margin market endpoints
                var v21 = client.Margin.Market.GetMarginPairsAsync();
                // Margin.Order | Margin order endpoints
                var v22 = client.Margin.Order.GetMarginAccountOrdersAsync("BTCUSDT");
                // Margin.UserStream | Margin user stream endpoints. Should be used to subscribe to a user stream with the socket client
                var v23 = client.Margin.UserStream.StartUserStreamAsync();
                // Margin.IsolatedUserStream | Isolated margin user stream endpoints. Should be used to subscribe to a user stream with the socket client
                var v24 = client.Margin.IsolatedUserStream.StartIsolatedMarginUserStreamAsync("BTCUSDT");

                // Mining | Mining endpoints
                var v25 = client.Mining.GetMiningCoinListAsync();

                // SubAccount | Sub account management
                // client.SubAccount.TransferSubAccountAsync("fromEmail", "toEmail", "asset", 1);

                // Brokerage | Brokerage management
                //  client.Brokerage.CreateSubAccountAsync();

                // WithdrawDeposit | Withdraw and deposit endpoints
                // client.WithdrawDeposit.GetWithdrawalHistoryAsync();
            }

        }
    }`

**Comment by Dimarik1Krasnodar93** [comment]
after 60 seconds will be error in Result: {: [2] Request timed out }

**Comment by Dimarik1Krasnodar93** [comment]
can I use your library withought async methods? for example I saw that in namespace Binance.Net.Interfaces.SubClients.Spot all methods are Async.

**Comment by JKorf** [comment]
You can use it as `client.Spot.Market.GetPricesAsync().Result`
