### ISSUE TITLE
Winform Klines Values

### ISSUE THREAD

**Issue by SARPSARP090** [JKorf/Binance.Net#873]
Can you share an example that can pass kline high, low, open, close values ​​to listbox for Winform?

```
 var callResult = await client.Spot.Market.GetKlinesAsync("ICXUSDT", KlineInterval.FourHour, limit: 2);
            await Task.Run(() =>
            {
                listBox1.Items.Add(callResult.Data);
                //everything from here on will not be executed
            });
```

**Comment by JKorf** [comment]
You'll get an exception when you're adding the item with `listBox1.Items.Add(callResult.Data);`. It will throw an exception because you're trying to update the UI from a different thread. Change it to `listBox1.Invoke(new Action(() => { listBox1.Items.Add(callResult.Data); } ));` and it should work

**Comment by SARPSARP090** [comment]
ilginiz için teşekkür ederim.  Sorunum çözüldü.
