### ISSUE TITLE
Question: Symbol for perpetual order book

### ISSUE THREAD

**Issue by nimrod46** [JKorf/Binance.Net#874]
Hi, when I use `client.FuturesCoin.Market.GetOrderBookAsync` I can use this symbol `BTCUSD_PERP` and it will work, 
but when subscribing:
```
var socketClient = new BinanceSocketClient();
var socket = await socketClient.FuturesUsdt.SubscribeToOrderBookUpdatesAsync(
  "BTCUSD_PERP", 100,
binanceFuturesEventOrderBook => { onUpdate(binanceFuturesEventOrderBook.Data); });
```
this symbol won't work, any idea why?

Edit: not working means no updates, although the socket connection is up and working.

**Comment by JKorf** [comment]
You're requesting the order book using `FuturesCoin` and subscribing the updates with `FuturesUsdt`. If you change the subscription to `await socketClient.FuturesCoin.SubscribeToOrderBookUpdatesAsync` it works

**Comment by nimrod46** [comment]
God thanks! What a rookie mistake 🤦‍♂️
