### ISSUE TITLE
How to get an account balance

### ISSUE THREAD

**Issue by justfitzgerald** [JKorf/Binance.Net#875]
Hello guys!
How can I get balance with API key and API secret?
Thx in advance)

**Comment by khaNuri** [comment]
> Hello guys!
> How can I get balance with API key and API secret?
> Thx in advance)

It's not issue. Please follow documentation and sample. You wil find answer.

**Comment by JKorf** [comment]
https://binance-docs.github.io/apidocs/spot/en/#change-log for Binance API docs, the ReadMe.md file for Binance.Net docs.
You can get account balance using `binanceClient.General.GetAccountInfoAsync()`
