### ISSUE TITLE
new order - error Mandatory parameter 'type' was not sent, was empty/null

### ISSUE THREAD

**Issue by Dimarik1Krasnodar93** [JKorf/Binance.Net#876]
I try to send order. Lool
`   _decSumToUse = 14;
            decPrice = 25000;
            decStopPrice = 25005;
            decimal decQuantity = Math.Round(_decSumToUse / decPrice * 0.999M,7); 
           
             var callResult = await client.Margin.Order.PlaceMarginOrderAsync("BTCUSDT", OrderSide.Buy, OrderType.Stop, decQuantity,null, null, decPrice, null, decStopPrice);
            var callResult2 = await client.Spot.Order.PlaceOrderAsync("BTCUSDT", OrderSide.Buy, OrderType.Limit, decQuantity, decPrice, timeInForce: TimeInForce.GoodTillCancel);
`
callResult has error: {-1102: Mandatory parameter 'type' was not sent, was empty/null, or malformed. },
for spot order I made like in your example, But I have an exepction: System.ArgumentException: "quoteOrderQuantity is only valid for market orders"
What is wrong? with PlaceMarginOrderAsync and PlaceOrderAsync.
Please, help me

**Comment by Dimarik1Krasnodar93** [comment]
var callResult2 = await client.Spot.Order.PlaceOrderAsync("BTCUSDT", OrderSide.Buy, OrderType.Limit, decQuantity, decPrice, timeInForce: TimeInForce.GoodTillCancel);
For this I understood my mistake. But what is wrong with          `var callResult = await client.Margin.Order.PlaceMarginOrderAsync("BTCUSDT", OrderSide.Buy, OrderType.Stop, decQuantity,null, null, decPrice, null, decStopPrice);`
can you help me, please?

**Comment by JKorf** [comment]
I'm pretty sure you have to use `OrderType.StopLoss`/`StopLossLimit`/`TakeProfit`/`TakeProfitLimit` instead of just `OrderType.Stop`
