### ISSUE TITLE
How to get Current Coins on Account

### ISSUE THREAD

**Issue by ExceedingLife** [JKorf/Binance.Net#878]
I have a question, how can I get the current coins that I am actively holding, basically the same thing as the pie chart on binance, I want to do that for my dashboard I am creating,
I want to get the coins and compare them with a percent of what the account currently has,
Do you know how I can use this API to make that pie chart same as binance?

**Comment by JKorf** [comment]
I'm not too familiar with the chart you mention as I hardly log into Binance these days. But I'm assuming it's based on USD value of the coins in percentages to your whole account USD value?
There is no direct way in the API to get this, you'll have to get the current account balances. Then calculate each coin' USD value based on the current price of the coin. After that you can add all these coins together for a total value, and you can determine what value percentage each coin is.

**Comment by ExceedingLife** [comment]
Thanks JKorf,
That was my original idea, doing it all manually and doing the calculations to get the data to display it in a pie chart.
I wasnt sure if there was an easier way.
That is what I will do. I currently have all my coins being held, quantity, and the price of the coin. Do you have a method in the API to get my total amount on Binance? like the Cash Total on the account or anything like that?

**Comment by JKorf** [comment]
Nope dont think so. You can have a look at the Binance API docs, but I don't think there is an endpoint for that

**Comment by SubZer000z** [comment]
@ExceedingLife Hey, I just wanted to chime in and say that I did somewhat of this. If you are grabbing all coinpairs prices, you can loop through your coins and their prices, to btc, or to eth, or to usd stable coin of sorts. Once you loop through all to find a pair to get back to base with, you should be able to estimate all coins values in usd (usdc or usdt). I couldn't find any api to get an estimated value with, so did this and it was pretty simple.

**Comment by ExceedingLife** [comment]
Hey all, sorry for the late reply. I also got this working for the most part of what I was trying to do. I use 'Chart'js' to show all my coins held in a pie graph. I have the % shown for each coin. I did not figure out how to display multiple properties on chart.js but i didnt look very hard i been developing other aspects of my website I created this this API. a trading bot. Here is what I did for the pie chart. 
`if (!ac.Asset.Equals("USD"))
                                    {
                                        if (ac.Asset.Equals("SHIB"))
                                        {
                                            string coinSymbol = ac.Asset + "USDT";
                                            var coinData = client.GetPrice(coinSymbol);
                                            if (coinData?.Data.Price != 0)
                                            {
                                                // Get User total $ amount for each coin.
                                                decimal coinTotal = ac.Total * coinData.Data.Price;
                                                // Add up each coin total value to get Users Account Total Cash.
                                                userTotal += coinTotal;
                                                Console.WriteLine(userTotal);
                                                (string, decimal, decimal) coinUserStats = (ac.Asset, ac.Total, coinTotal);
                                                lstAccountCoins.Add(coinUserStats);
                                            }
                                        }
                                        else
                                        {
                                            // Get the Coin Current Price.
                                            string coinSymbol = ac.Asset + "USD";
                                            var coinData = client.GetPrice(coinSymbol);
                                            if (coinData?.Data.Price != 0)
                                            {
                                                // Get User total $ amount for each coin.
                                                decimal coinTotal = ac.Total * coinData.Data.Price;
                                                // Add up each coin total value to get Users Account Total Cash.
                                                userTotal += coinTotal;
                                                Console.WriteLine(userTotal);
                                                (string, decimal, decimal) coinUserStats = (ac.Asset, ac.Total, coinTotal);
                                                lstAccountCoins.Add(coinUserStats);
                                            }
                                        }
                                        
                                    }
                                    else
                                    {
                                        // Add up each coin total value to get Users Account Total Cash.
                                        userTotal += ac.Total;
                                        Console.WriteLine(userTotal);
                                        (string, decimal, decimal) userUSDStats = (ac.Asset, ac.Total, ac.Total);
                                        lstAccountCoins.Add(userUSDStats);
                                    }                                   
                                }`
