### ISSUE TITLE
Updated Version not getting Orders

### ISSUE THREAD

**Issue by habeebmatrix** [JKorf/Binance.Net#88]
I updated the Binance.Net reference in Examples project.
Since then Methods within `Task.Run()` are not called.
Please see the specific sample below:
MainViewModel.cs - Line 272
```
Task.Run(() =>
{
  GetOrders();
  Get24HourStats();
});
```

**Comment by JKorf** [comment]
Hi, I updated the examples and fixed the issue. Instead of starting a task to subscribe each symbol to a socket stream to update the price now a single socket stream is used.

**Comment by habeebmatrix** [comment]
Thanks.
