### ISSUE TITLE
socketClient.Spot.SubscribeToSymbolTickerUpdatesAsync not working?

### ISSUE THREAD

**Issue by LiorBanai** [JKorf/Binance.Net#884]
HI,
I'm calling the socketClient.Spot.SubscribeToSymbolTickerUpdatesAsync with a list of symbols but getting error on the result (SubscribeToAllSymbolTickerUpdatesAsync works fine).

the result is 
![image](https://user-images.githubusercontent.com/36262995/135072133-d3a99462-6b50-4dff-b8ed-9e1268a3f398.png)

are there some limitation for that method? I'm calling with a list of 250 symbols

**Comment by JKorf** [comment]
Seems like you're right, it seems like you can sent a max of around 4090 bytes in the subscribe request, any more and it will not return anything. This is probably some (undocumented) limitation on Binance' side. You'll have to split up the subscription in batches, or alternatively use `SubscribeToAllSymbolTickerUpdatesAsync` and ignore the symbols you're no interested in

**Comment by LiorBanai** [comment]
Thanks! I'll reduce the list size.
