### ISSUE TITLE
GetHistoricalBlvtKlinesAsync() error {-1121: Invalid symbol. }

### ISSUE THREAD

**Issue by endiHuMan** [JKorf/Binance.Net#885]
Hi, 
I'm trying to get historical candlestick data to calculate moving average. I tried this:
```
BinanceClient client = new BinanceClient(new BinanceClientOptions()
{
    ApiCredentials = new CryptoExchange.Net.Authentication.ApiCredentials(key, secret)
});
DateTime thisTime = DateTime.Now;
DateTime prevTime = thisTime.AddMinutes(-20);
var charts = client.Blvt.GetHistoricalBlvtKlinesAsync("BTCUSDT", KlineInterval.OneMinute, prevTime, thisTime, 1000).GetAwaiter().GetResult();
```

and I get the following error: {-1121: Invalid symbol. 
Can you help me please?

![valid](https://user-images.githubusercontent.com/91561314/135138020-d4bd148f-44ea-412f-becf-da08ca906421.PNG)

**Comment by JKorf** [comment]
Are you sure you need the Blvt endpoint and not `client.Spot.Market.GetKlinesAsync()`?

**Comment by endiHuMan** [comment]
Yes, you are right, I didn't knew this method can give back historical chart data. Thank you so much!
