### ISSUE TITLE
To many error after migrating to latest libaray version from 6.13.4

### ISSUE THREAD

**Issue by NektoDron** [JKorf/Binance.Net#890]
Many unhandled execptions like this:
13:36:06.78[112]WARN :[BinanceCoin-MFutures] ApiResponse: SubscribeToMarkPrice DOGEUSD_PERP; 40009ms; Success=False, Error=': No response on subscription request received '
13:36:06.83[2]FATAL:UnobservedTaskException: AggregateException:
ArgumentException:Элемент с тем же ключом уже был добавлен.:   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at CryptoExchange.Net.Sockets.CryptoExchangeWebSocketClient.<ReceiveLoopAsync>d__94.MoveNext()

13:37:12.81[2]FATAL:UnobservedTaskException: AggregateException:
InvalidOperationException:Коллекция была изменена; невозможно выполнить операцию перечисления.:   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.KeyCollection.Enumerator.MoveNext()
   at CryptoExchange.Net.Sockets.CryptoExchangeWebSocketClient.UpdateReceivedMessages()
   at CryptoExchange.Net.Sockets.CryptoExchangeWebSocketClient.<ReceiveLoopAsync>d__94.MoveNext()

**To Reproduce**
any endpoint if connection error has been presented

**Expected behavior**
Clear exception handling

**Comment by JKorf** [comment]
Hi, sorry about that. I'm assuming you're running .net framework as I was able to reproduce the issue there. Some logic which works in dotnet 5, but not in framework. I've pushed a new version, if you manually update CryptoExchange.Net to 4.2.4 it should work again

**Comment by NektoDron** [comment]
Yes, it works fine

**Comment by ghominejad** [comment]
It was working for me but after 5 times running doesn't work anymore. It will receive one line of the dat and the same error:
```
UTC: 7/15/2022 7:31:36 AM:691 0.10703000 @ 20855.71000000
Failed to sub: : No response on subscription request received
```
