### ISSUE TITLE
Is there a func that closes all positions for a symbol?

### ISSUE THREAD

**Issue by posecmaker** [JKorf/Binance.Net#892]
**Describe the bug**

**To Reproduce**
What endpoints and subscriptions are called.

**Expected behavior**

**Debug logging**
Add debug logging related to the issue. Enable Debug logging in the client options by settings LogLevel to Debug.

**Comment by CarlPrentice** [comment]
I think this is what you're looking for:
```
CancelAllOpenOrdersAsync(string symbol, long? receiveWindow = null, CancellationToken ct = default)
```
```
BinanceClient.Spot.Order.CancelAllOpenOrdersAsync(...)
```

**Comment by posecmaker** [comment]
Oh, i think these are for cancelling active limit orders

**Comment by CarlPrentice** [comment]
Oh I see. I don't think there's a concept of an open position within the API since it's low level, you'll have to implement that in your application.

**Comment by posecmaker** [comment]
Yeah probably. I should implement it this way but it's an another unnecessary request for me.
var positionStatus = Api.FuturesUsdt.GetPositionInformation("BTCUSDT");
var poses = positionStatus.Data as IEnumerable<BinancePositionDetailsUsdt>;
var currentPosition = poses.ElementAt(0);

**Comment by JKorf** [comment]
I don't think the is a way to close all open positions no. You'll probably have to place a sell order for each position
