### ISSUE TITLE
See all the coins and amounts in my account

### ISSUE THREAD

**Issue by SARPSARP090** [JKorf/Binance.Net#894]
I want to get all the battery information in my wallet with the code below, but it returns me a result in the form of "FIDA". However, I want to access all the balance information in my account. In other words, I am trying to reach all my ccoin list and quantity in my wallet. I couldn't do this with the code below (WindowsForm for). Thank you in advance for our help.

  ```
var hesap = await client.General.GetAccountInfoAsync();
            foreach (var deneme in hesap.Data.Balances)
            {
               
                richTextBox1.Text = deneme.Asset;

            }
```

**Comment by JKorf** [comment]
Each iteration of the foreach loop will override the previous text. You also might need to invoke because you're trying to update the UI from a background task. Something like this should work:
````C#
foreach (var deneme in hesap.Data.Balances)
{
   
    richTextBox1.Invoke(new Action(() => {  richTextBox1.Text += $"{deneme.Asset}: {deneme.Quantity}"; } ));;

}
````

**Comment by SARPSARP090** [comment]
thank you. it works perfectly.
