### ISSUE TITLE
BinanceSocketClient.SubscribeToKlineUpdatesAsync not updating

### ISSUE THREAD

**Issue by Barros32** [JKorf/Binance.Net#897]
Hello,
first of all great project you have here!!!
Now the issue :
after I subscribe any pair using  "BinanceSocketClient.SubscribeToKlineUpdatesAsync" I recieve a couple of messages (~10) and after that no messages at all. 

**this is my test code:**
`        BinanceSocketClient socketClient;
        Binance.Net.Interfaces.IBinanceStreamKline lastKline;

            //https://github.com/JKorf/CryptoExchange.Net
            button1.Click += async (_o, _e) =>
            {
                if (socketClient is null)
                {
                    button1.Text = "STOP";
                    socketClient = new BinanceSocketClient(new BinanceSocketClientOptions() {
                       LogLevel = LogLevel.Trace,
                    });
          
                    int i = 0;
                  
                    var result = await socketClient.FuturesUsdt.SubscribeToKlineUpdatesAsync("ETHUSDT", KlineInterval.OneMinute,(msg) =>
                    {
                        lastKline = msg.Data.Data;
                        BeginInvoke(new MethodInvoker(() =>
                        {
                            label1.Text = $"{i++}:{lastKline.OpenTime}:{lastKline.Open}";
                        }));                 
                    });

                    if (!result.Success)
                    {
                      
                    }

                }
                else
                {
                    button1.Text = "START";
                    await socketClient.UnsubscribeAllAsync();
                    socketClient.Dispose();
                    socketClient = null;
                }

            };
`

----------------------------------------------------------------------------------------------------------------------------------------------
**And here is VS output:**
'XXXXXXXXXXX.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_32\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'XXXXXXXXXXX.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Users\root\source\repos\XXXXXXXXXXX\XXXXXXXXXXX\bin\Debug\XXXXXXXXXXX.exe'. Symbols loaded.
'XXXXXXXXXXX.exe' (CLR v4.0.30319: XXXXXXXXXXX.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'XXXXXXXXXXX.exe' (CLR v4.0.30319: XXXXXXXXXXX.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'XXXXXXXXXXX.exe' (CLR v4.0.30319: XXXXXXXXXXX.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'XXXXXXXXXXX.exe' (CLR v4.0.30319: XXXXXXXXXXX.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'XXXXXXXXXXX.exe' (CLR v4.0.30319: XXXXXXXXXXX.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'XXXXXXXXXXX.exe' (CLR v4.0.30319: XXXXXXXXXXX.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'XXXXXXXXXXX.exe' (CLR v4.0.30319: XXXXXXXXXXX.exe): Loaded 'C:\Users\root\source\repos\XXXXXXXXXXX\XXXXXXXXXXX\bin\Debug\CryptoExchange.Net.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'XXXXXXXXXXX.exe' (CLR v4.0.30319: XXXXXXXXXXX.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\netstandard\v4.0_2.0.0.0__cc7b13ffcd2ddd51\netstandard.dll'. Module was built without symbols.
'XXXXXXXXXXX.exe' (CLR v4.0.30319: XXXXXXXXXXX.exe): Loaded 'C:\Users\root\source\repos\XXXXXXXXXXX\XXXXXXXXXXX\bin\Debug\Binance.Net.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'XXXXXXXXXXX.exe' (CLR v4.0.30319: XXXXXXXXXXX.exe): Loaded 'C:\Users\root\source\repos\XXXXXXXXXXX\XXXXXXXXXXX\bin\Debug\Newtonsoft.Json.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'XXXXXXXXXXX.exe' (CLR v4.0.30319: XXXXXXXXXXX.exe): Loaded 'C:\Users\root\source\repos\XXXXXXXXXXX\XXXXXXXXXXX\bin\Debug\Microsoft.Extensions.Logging.Abstractions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'XXXXXXXXXXX.exe' (CLR v4.0.30319: XXXXXXXXXXX.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Net.Http\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Net.Http.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
2021/10/03 08:02:58:978 | Debug | Binance    | Client configuration: LogLevel: Trace, Writers: 1, OutputOriginalData: False, Credentials: -, BaseAddress: wss://stream.binance.com:9443/, Proxy: -, AutoReconnect: True, ReconnectInterval: 00:00:05, SocketResponseTimeout: 00:00:10, SocketSubscriptionsCombineTarget: 10, CryptoExchange.Net: v4.2.3.0, Binance.Net: v7.2.2.0
'XXXXXXXXXXX.exe' (CLR v4.0.30319: XXXXXXXXXXX.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'XXXXXXXXXXX.exe' (CLR v4.0.30319: XXXXXXXXXXX.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Numerics.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'XXXXXXXXXXX.exe' (CLR v4.0.30319: XXXXXXXXXXX.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
2021/10/03 08:02:59:119 | Debug | Binance    | Socket 1 new socket created for wss://fstream.binance.com/stream
2021/10/03 08:02:59:119 | Debug | Binance    | Socket 1 connecting
2021/10/03 08:03:01:338 | Trace | Binance    | Socket 1 connection succeeded, starting communication
2021/10/03 08:03:01:400 | Debug | Binance    | Socket 1 connected
The thread 0x241c has exited with code 0 (0x0).
The thread 0x1c30 has exited with code 0 (0x0).
2021/10/03 08:03:01:448 | Debug | Binance    | Socket 1 connected to wss://fstream.binance.com/stream with request {"method":"SUBSCRIBE","params":["ethusdt@kline_1m"],"id":1}
2021/10/03 08:03:01:448 | Debug | Binance    | Socket 1 sending data: {"method":"SUBSCRIBE","params":["ethusdt@kline_1m"],"id":1}
2021/10/03 08:03:01:463 | Trace | Binance    | Socket 1 Adding 59 to sent buffer
2021/10/03 08:03:01:463 | Trace | Binance    | Socket 1 sent 59 bytes
2021/10/03 08:03:01:791 | Trace | Binance    | Socket 1 received 22 bytes in single message
2021/10/03 08:03:01:806 | Trace | Binance    | Socket 1 received data: {"id":1,"result":null}
2021/10/03 08:03:01:932 | Trace | Binance    | Socket 1 received 319 bytes in single message
2021/10/03 08:03:01:947 | Trace | Binance    | Socket 1 received data: {"stream":"ethusdt@kline_1m","data":{"e":"kline","E":1633248183528,"s":"ETHUSDT","k":{"t":1633248180000,"T":1633248239999,"s":"ETHUSDT","i":"1m","f":1112881582,"L":1112881663,"o":"3391.05","c":"3390.33","h":"3391.06","l":"3390.03","v":"39.312","n":82,"x":false,"q":"133291.97865","V":"2.714","Q":"9201.01121","B":"0"}}}
2021/10/03 08:03:02:009 | Trace | Binance    | Socket 1 message processed in 59ms
2021/10/03 08:03:02:260 | Trace | Binance    | Socket 1 received 320 bytes in single message
2021/10/03 08:03:02:260 | Trace | Binance    | Socket 1 received data: {"stream":"ethusdt@kline_1m","data":{"e":"kline","E":1633248183844,"s":"ETHUSDT","k":{"t":1633248180000,"T":1633248239999,"s":"ETHUSDT","i":"1m","f":1112881582,"L":1112881668,"o":"3391.05","c":"3390.33","h":"3391.06","l":"3390.03","v":"40.618","n":87,"x":false,"q":"137719.73950","V":"3.007","Q":"10194.37790","B":"0"}}}
2021/10/03 08:03:02:275 | Trace | Binance    | Socket 1 message processed in 0ms
2021/10/03 08:03:02:556 | Trace | Binance    | Socket 1 received 323 bytes in single message
2021/10/03 08:03:02:572 | Trace | Binance    | Socket 1 received data: {"stream":"ethusdt@kline_1m","data":{"e":"kline","E":1633248184152,"s":"ETHUSDT","k":{"t":1633248180000,"T":1633248239999,"s":"ETHUSDT","i":"1m","f":1112881582,"L":1112881733,"o":"3391.05","c":"3391.59","h":"3391.62","l":"3390.03","v":"89.417","n":152,"x":false,"q":"303202.87138","V":"50.243","Q":"170376.53001","B":"0"}}}
2021/10/03 08:03:02:572 | Trace | Binance    | Socket 1 message processed in 0ms
2021/10/03 08:03:02:822 | Trace | Binance    | Socket 1 received 323 bytes in single message
2021/10/03 08:03:02:822 | Trace | Binance    | Socket 1 received data: {"stream":"ethusdt@kline_1m","data":{"e":"kline","E":1633248184407,"s":"ETHUSDT","k":{"t":1633248180000,"T":1633248239999,"s":"ETHUSDT","i":"1m","f":1112881582,"L":1112881744,"o":"3391.05","c":"3391.67","h":"3391.67","l":"3390.03","v":"92.929","n":163,"x":false,"q":"315114.21382","V":"53.753","Q":"182281.08911","B":"0"}}}
2021/10/03 08:03:02:838 | Trace | Binance    | Socket 1 message processed in 1ms
2021/10/03 08:03:03:072 | Trace | Binance    | Socket 1 received 324 bytes in single message
2021/10/03 08:03:03:088 | Trace | Binance    | Socket 1 received data: {"stream":"ethusdt@kline_1m","data":{"e":"kline","E":1633248184661,"s":"ETHUSDT","k":{"t":1633248180000,"T":1633248239999,"s":"ETHUSDT","i":"1m","f":1112881582,"L":1112881756,"o":"3391.05","c":"3391.76","h":"3391.86","l":"3390.03","v":"103.397","n":175,"x":false,"q":"350619.20194","V":"61.202","Q":"207546.57522","B":"0"}}}
2021/10/03 08:03:03:088 | Trace | Binance    | Socket 1 message processed in 0ms
2021/10/03 08:03:03:478 | Trace | Binance    | Socket 1 received 324 bytes in single message
2021/10/03 08:03:03:494 | Trace | Binance    | Socket 1 received data: {"stream":"ethusdt@kline_1m","data":{"e":"kline","E":1633248185070,"s":"ETHUSDT","k":{"t":1633248180000,"T":1633248239999,"s":"ETHUSDT","i":"1m","f":1112881582,"L":1112881763,"o":"3391.05","c":"3391.98","h":"3391.98","l":"3390.03","v":"105.180","n":182,"x":false,"q":"356667.07360","V":"62.936","Q":"213428.24035","B":"0"}}}
2021/10/03 08:03:03:494 | Trace | Binance    | Socket 1 message processed in 1ms
2021/10/03 08:03:03:807 | Trace | Binance    | Socket 1 received 324 bytes in single message
2021/10/03 08:03:03:807 | Trace | Binance    | Socket 1 received data: {"stream":"ethusdt@kline_1m","data":{"e":"kline","E":1633248185399,"s":"ETHUSDT","k":{"t":1633248180000,"T":1633248239999,"s":"ETHUSDT","i":"1m","f":1112881582,"L":1112881789,"o":"3391.05","c":"3392.72","h":"3392.86","l":"3390.03","v":"125.133","n":208,"x":false,"q":"424355.61801","V":"82.544","Q":"279946.34801","B":"0"}}}
2021/10/03 08:03:03:807 | Trace | Binance    | Socket 1 message processed in 0ms
2021/10/03 08:03:04:416 | Trace | Binance    | Socket 1 received 324 bytes in single message
2021/10/03 08:03:04:431 | Trace | Binance    | Socket 1 received data: {"stream":"ethusdt@kline_1m","data":{"e":"kline","E":1633248186011,"s":"ETHUSDT","k":{"t":1633248180000,"T":1633248239999,"s":"ETHUSDT","i":"1m","f":1112881582,"L":1112881792,"o":"3391.05","c":"3392.72","h":"3392.86","l":"3390.03","v":"125.340","n":211,"x":false,"q":"425057.91105","V":"82.544","Q":"279946.34801","B":"0"}}}
2021/10/03 08:03:04:431 | Trace | Binance    | Socket 1 message processed in 0ms
2021/10/03 08:03:04:697 | Trace | Binance    | Socket 1 received 324 bytes in single message
2021/10/03 08:03:04:697 | Trace | Binance    | Socket 1 received data: {"stream":"ethusdt@kline_1m","data":{"e":"kline","E":1633248186287,"s":"ETHUSDT","k":{"t":1633248180000,"T":1633248239999,"s":"ETHUSDT","i":"1m","f":1112881582,"L":1112881794,"o":"3391.05","c":"3392.72","h":"3392.86","l":"3390.03","v":"125.355","n":213,"x":false,"q":"425108.80185","V":"82.544","Q":"279946.34801","B":"0"}}}
2021/10/03 08:03:04:697 | Trace | Binance    | Socket 1 message processed in 0ms
2021/10/03 08:03:04:947 | Trace | Binance    | Socket 1 received 324 bytes in single message
2021/10/03 08:03:04:947 | Trace | Binance    | Socket 1 received data: {"stream":"ethusdt@kline_1m","data":{"e":"kline","E":1633248186538,"s":"ETHUSDT","k":{"t":1633248180000,"T":1633248239999,"s":"ETHUSDT","i":"1m","f":1112881582,"L":1112881799,"o":"3391.05","c":"3392.72","h":"3392.86","l":"3390.03","v":"125.812","n":218,"x":false,"q":"426659.27489","V":"82.544","Q":"279946.34801","B":"0"}}}
2021/10/03 08:03:04:962 | Trace | Binance    | Socket 1 message processed in 0ms
2021/10/03 08:03:05:557 | Trace | Binance    | Socket 1 received 324 bytes in single message
2021/10/03 08:03:05:572 | Trace | Binance    | Socket 1 received data: {"stream":"ethusdt@kline_1m","data":{"e":"kline","E":1633248187155,"s":"ETHUSDT","k":{"t":1633248180000,"T":1633248239999,"s":"ETHUSDT","i":"1m","f":1112881582,"L":1112881800,"o":"3391.05","c":"3392.72","h":"3392.86","l":"3390.03","v":"125.865","n":219,"x":false,"q":"426839.08905","V":"82.544","Q":"279946.34801","B":"0"}}}
2021/10/03 08:03:05:572 | Trace | Binance    | Socket 1 message processed in 0ms
The thread 0x960 has exited with code 0 (0x0).
The thread 0x3590 has exited with code 0 (0x0).
The thread 0x2de4 has exited with code 0 (0x0).

**Comment by SARPSARP090** [comment]
```
var result = await socketClient.FuturesUsdt.SubscribeToKlineUpdatesAsync("ETHUSDT", KlineInterval.OneMinute,(msg) =>
                {
                    lastKline = msg.Data.Data;
                    BeginInvoke(new MethodInvoker(() =>
                    {
                        label1.Text = $"{i++}:{lastKline.OpenTime}:{lastKline.Open}";
                    }));                 
                });
```

I think you are trying to get candle opening time and opening value.
Your problem should be resolved when you change the above code as below.

```

                var result = await socketClient.FuturesUsdt.SubscribeToKlineUpdatesAsync("ETHUSDT", KlineInterval.OneMinute,(msg) =>
                {
                    lastKline = msg.Data.Data; 
                    BeginInvoke(new MethodInvoker(() =>
                    {
                        label1.Text = $"{i++}:{result.OpenTime}:{result.Open}";
                    }));                 
                });
```


foreach (var item in callResult.Data.SkipLast(2).Skip(1)) // Açılış - Güncele En Yakın
                    {
                        decimal HARB30_HA_acilis1 = (item.Open + item.Close) / 2;
                        mum1acilis = HARB30_HA_acilis1;
                    }

**Comment by JKorf** [comment]
There was an issue when running from .net framework, can you try again with the latest version?

**Comment by Barros32** [comment]
> There was an issue when running from .net framework, can you try again with the latest version?
Hello I've installed .net framework 4.8 and the result is the same:

2021/10/05 14:13:15:174 | Debug | Binance    | Socket 1 new socket created for wss://fstream.binance.com/stream
2021/10/05 14:13:15:190 | Debug | Binance    | Socket 1 connecting
2021/10/05 14:13:16:441 | Trace | Binance    | Socket 1 connection succeeded, starting communication
The thread 0x768 has exited with code 0 (0x0).
The thread 0x348 has exited with code 0 (0x0).
2021/10/05 14:13:16:473 | Debug | Binance    | Socket 1 connected
2021/10/05 14:13:16:548 | Debug | Binance    | Socket 1 connected to wss://fstream.binance.com/stream with request {"method":"SUBSCRIBE","params":["ethusdt@kline_1m"],"id":1}
2021/10/05 14:13:16:554 | Debug | Binance    | Socket 1 sending data: {"method":"SUBSCRIBE","params":["ethusdt@kline_1m"],"id":1}
2021/10/05 14:13:16:557 | Trace | Binance    | Socket 1 Adding 59 to sent buffer
2021/10/05 14:13:16:564 | Trace | Binance    | Socket 1 sent 59 bytes
2021/10/05 14:13:16:895 | Trace | Binance    | Socket 1 received 22 bytes in single message
2021/10/05 14:13:16:900 | Trace | Binance    | Socket 1 received data: {"id":1,"result":null}
2021/10/05 14:13:17:065 | Trace | Binance    | Socket 1 received 324 bytes in single message
2021/10/05 14:13:17:070 | Trace | Binance    | Socket 1 received data: {"stream":"ethusdt@kline_1m","data":{"e":"kline","E":1633443198593,"s":"ETHUSDT","k":{"t":1633443180000,"T":1633443239999,"s":"ETHUSDT","i":"1m","f":1118274317,"L":1118274653,"o":"3455.09","c":"3456.83","h":"3456.87","l":"3455.09","v":"126.761","n":337,"x":false,"q":"438084.30110","V":"91.654","Q":"316753.68102","B":"0"}}}
2021/10/05 14:13:17:175 | Trace | Binance    | Socket 1 message processed in 89ms
2021/10/05 14:13:17:822 | Trace | Binance    | Socket 1 received 324 bytes in single message
2021/10/05 14:13:17:825 | Trace | Binance    | Socket 1 received data: {"stream":"ethusdt@kline_1m","data":{"e":"kline","E":1633443199235,"s":"ETHUSDT","k":{"t":1633443180000,"T":1633443239999,"s":"ETHUSDT","i":"1m","f":1118274317,"L":1118274664,"o":"3455.09","c":"3456.49","h":"3456.87","l":"3455.09","v":"133.916","n":348,"x":false,"q":"462816.49520","V":"91.754","Q":"317099.33002","B":"0"}}}
2021/10/05 14:13:17:829 | Trace | Binance    | Socket 1 message processed in 0ms
2021/10/05 14:13:18:452 | Trace | Binance    | Socket 1 received 324 bytes in single message
2021/10/05 14:13:18:460 | Trace | Binance    | Socket 1 received data: {"stream":"ethusdt@kline_1m","data":{"e":"kline","E":1633443199978,"s":"ETHUSDT","k":{"t":1633443180000,"T":1633443239999,"s":"ETHUSDT","i":"1m","f":1118274317,"L":1118274669,"o":"3455.09","c":"3456.48","h":"3456.87","l":"3455.09","v":"134.068","n":353,"x":false,"q":"463341.88064","V":"91.802","Q":"317265.24154","B":"0"}}}
2021/10/05 14:13:18:467 | Trace | Binance    | Socket 1 message processed in 0ms
2021/10/05 14:13:19:077 | Trace | Binance    | Socket 1 received 324 bytes in single message
2021/10/05 14:13:19:081 | Trace | Binance    | Socket 1 received data: {"stream":"ethusdt@kline_1m","data":{"e":"kline","E":1633443200581,"s":"ETHUSDT","k":{"t":1633443180000,"T":1633443239999,"s":"ETHUSDT","i":"1m","f":1118274317,"L":1118274670,"o":"3455.09","c":"3456.49","h":"3456.87","l":"3455.09","v":"134.088","n":354,"x":false,"q":"463411.01044","V":"91.822","Q":"317334.37134","B":"0"}}}
2021/10/05 14:13:19:083 | Trace | Binance    | Socket 1 message processed in 0ms
2021/10/05 14:13:19:579 | Trace | Binance    | Socket 1 received 324 bytes in single message
2021/10/05 14:13:19:580 | Trace | Binance    | Socket 1 received data: {"stream":"ethusdt@kline_1m","data":{"e":"kline","E":1633443201033,"s":"ETHUSDT","k":{"t":1633443180000,"T":1633443239999,"s":"ETHUSDT","i":"1m","f":1118274317,"L":1118274681,"o":"3455.09","c":"3456.40","h":"3456.87","l":"3455.09","v":"135.151","n":365,"x":false,"q":"467085.16233","V":"91.885","Q":"317552.12454","B":"0"}}}
2021/10/05 14:13:19:582 | Trace | Binance    | Socket 1 message processed in 0ms
2021/10/05 14:13:19:937 | Trace | Binance    | Socket 1 received 324 bytes in single message
2021/10/05 14:13:19:941 | Trace | Binance    | Socket 1 received data: {"stream":"ethusdt@kline_1m","data":{"e":"kline","E":1633443201424,"s":"ETHUSDT","k":{"t":1633443180000,"T":1633443239999,"s":"ETHUSDT","i":"1m","f":1118274317,"L":1118274696,"o":"3455.09","c":"3456.40","h":"3456.87","l":"3455.09","v":"136.582","n":380,"x":false,"q":"472031.27065","V":"93.308","Q":"322470.58174","B":"0"}}}
2021/10/05 14:13:19:944 | Trace | Binance    | Socket 1 message processed in 0ms
2021/10/05 14:13:20:280 | Trace | Binance    | Socket 1 received 324 bytes in single message
2021/10/05 14:13:20:284 | Trace | Binance    | Socket 1 received data: {"stream":"ethusdt@kline_1m","data":{"e":"kline","E":1633443201697,"s":"ETHUSDT","k":{"t":1633443180000,"T":1633443239999,"s":"ETHUSDT","i":"1m","f":1118274317,"L":1118274705,"o":"3455.09","c":"3456.40","h":"3456.87","l":"3455.09","v":"137.268","n":389,"x":false,"q":"474402.36053","V":"93.942","Q":"324661.93934","B":"0"}}}
2021/10/05 14:13:20:287 | Trace | Binance    | Socket 1 message processed in 0ms
2021/10/05 14:13:20:671 | Trace | Binance    | Socket 1 received 324 bytes in single message
2021/10/05 14:13:20:674 | Trace | Binance    | Socket 1 received data: {"stream":"ethusdt@kline_1m","data":{"e":"kline","E":1633443202114,"s":"ETHUSDT","k":{"t":1633443180000,"T":1633443239999,"s":"ETHUSDT","i":"1m","f":1118274317,"L":1118274711,"o":"3455.09","c":"3456.48","h":"3456.87","l":"3455.09","v":"153.167","n":395,"x":false,"q":"529356.73341","V":"96.475","Q":"333417.00054","B":"0"}}}
2021/10/05 14:13:20:677 | Trace | Binance    | Socket 1 message processed in 0ms

By the end of this week I will try it in different machine with VS2019, at the moment I'm using VS2017.

**Comment by JKorf** [comment]
Sorry I was referring to the latest version of Binance.Net
