### ISSUE TITLE
Errors from web server causing the api to crash

### ISSUE THREAD

**Issue by muteddisk** [JKorf/Binance.Net#90]
after calling this or other api function...whenever there's some weird web server error it causes the api to crash. It won't return from the function and the thread gets stuck.
Dim OrderBook As CallResult(Of BinanceOrderBook) = ex.GetOrderBook(Symbol & _QuoteSymbol)

error from web server report by the debugging in output window

2018/06/05 23:22:37:239 | Warning | Server returned an error: <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>

**Comment by JKorf** [comment]
Hi, I haven't been able to reproduce this. After writing ` Server returned an error:` to the logging it basically only returns, no further action is taken I think, so it would be weird if it gets stuck there. Doesn't the function just return a CallResult with Success = false?

**Comment by muteddisk** [comment]
Nope. It always happens when something is up with the Web server.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by TheFitzZZ** [comment]
We've seen this as well - I just handle the message content and retry whatever I just tried. No changes to the Binance.Net package was needed, just handle the obj.Error.Message appropriately.

**Comment by JKorf** [comment]
I can't reproduce the freezing you're describing. Could you put LogVerbosity on Debug and when it happens make a screenshot of the threads that are running?

**Comment by JKorf** [comment]
I've been unable to reproduce this and can't trace it based on existing information. If the issue still exists in the latest version of the library please re-open and provide new debug logging.
