### ISSUE TITLE
SocketClient not working

### ISSUE THREAD

**Issue by dvpot** [JKorf/Binance.Net#901]
SocketClient does not work since version 4.2.3 CryptoExchange.Net and higher.
Checked in my app and also in the Binance.Net ClientWPF example, prices are not updated.

**Comment by Sandr0oo** [comment]
My socket doesn't work either. It works for a while and then reconnects.

**Comment by JKorf** [comment]
This should be fixed in the latest version. Issue was .NET framework specific, I'm assuming you were using that.
@Sandr0oo The socket getting disconnected sometimes can have multiple causes. It should reconnect when it disconnects though

**Comment by dvpot** [comment]
Works fine.
I close it.
