### ISSUE TITLE
Some questions about BinanceClient and BinanceSocketClient 

### ISSUE THREAD

**Issue by vaniakurd** [JKorf/Binance.Net#906]
1)Is BinanceClient thread safe?(Sometimes a need to close 20 order in one moment(as fast as its possible), can i use one static BinanceClient or i need to use 20 local clients?)
2)The documentation says that: "A single connection to stream.binance.com is only valid for 24 hours; expect to be disconnected at the 24 hour mark". I need to manual recreate binanceSocketClient and binanceClient?
3) Binance have hard limit in 50 order per 10 second. When this 10 second starts? After my first order on whenever else?

**Comment by JKorf** [comment]
1. Yes, the client is thread safe
2. No, the socket client will automatically reconnect. You can listen to events for this on the subscribe result object
3. I have no answer on this, you'll probably have to ask Binance yourself. https://dev.binance.vision/
