### ISSUE TITLE
Error during install with Nuget 

### ISSUE THREAD

**Issue by hockeyadc** [JKorf/Binance.Net#91]
I'm getting the following error when trying to install this with Nuget:

"You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1, but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."

**Comment by JKorf** [comment]
Make sure you have the latest VisualStudio updates.
Also if you're using VS2015 make sure your Nuget client is up to date. You can download the latest Nuget client for VS2015 here: https://dist.nuget.org/visualstudio-2015-vsix/latest/NuGet.Tools.vsix

**Comment by hockeyadc** [comment]
Looks like that was it! Thanks!
