### ISSUE TITLE
Timestamp for this request is outside of the recvWindow

### ISSUE THREAD

**Issue by Tyreens** [JKorf/Binance.Net#914]
Hi,
i consistenly get a "Timestamp for this request is outside of the recvWindow" in Binance.net lately.
It wasn't a problem since now. Has anybody else that problem?

**Comment by Tyreens** [comment]
Are you using a ratelimiter? I found out that iit wait for the limiter it messes with the recv window in some way

**Comment by JKorf** [comment]
https://github.com/JKorf/Binance.Net#timestamping

**Comment by Aguxxx** [comment]
Hi there @JKorf
I have read https://github.com/JKorf/Binance.Net#timestamping in full
I use SP TimeSync to sync server time every 3 minutes. 
I use the AutoTimestamp: true and AutoTimestamp interval 1 minutes in the client setup options.
I no longer get the recvWindow error, but more often than not, I get the error message "Timestamp for this request was 1000ms ahead of the server's time"

I have read everywhere, and I'm sure that the server time is in sync, but I can't get rid of this error.
Is there another setup option that I can try to resolve this? Some way to timestamp -1000 or -1500 ms? Do you think that could work or could cause harm ?

Thanks !

**Comment by JKorf** [comment]
Hi, if you're sure your local time is correct ( which it should be in your case because you use TimeSync ) then you should set AutoTimestamp to false, as it will try to correct the local/server time with an offset which is no longer needed. Try setting it to false and let me know if that helps.

**Comment by JKorf** [comment]
I'm assuming this has been fixed
