### ISSUE TITLE
SubscribeToUserDataUpdatesAsync

### ISSUE THREAD

**Issue by Sergey7733** [JKorf/Binance.Net#915]
public Task<WebCallResult<string>> startResult;
startResult = apiClient.Spot.UserStream.StartUserStreamAsync();
private bool needReadOrders = true;
 _ = CheckNeedReadOrders();  

 public async Task CheckNeedReadOrders()
        {
            var SocketClient = new BinanceSocketClient();
            await SocketClient.Spot.SubscribeToUserDataUpdatesAsync(startResult.Result.Data,
               orderUpdate =>
               { 
                   needReadOrders = true;
               },
               ocoUpdate =>
               { // Handle oco order update
               },
               positionUpdate =>
               { // Handle account position update
               },
               balanceUpdate =>
               { // Handle balance update
               });
        }

while (true)
{
     if (needReadOrders)
            {
                 ...
            }
}

In this form, about 20% of the appearance or cancellation of orders goes unnoticed. Tell me what's wrong.

**Comment by JKorf** [comment]
Why are you requesting the data after getting the update? The update itself contains the information in the `orderUpdate` variable. 
What you're seeing is probably a delay between the update and the data being updated in the GetOrder endpoint. It can take a little time before the GetOrders endpoint has the latest state of things
