### ISSUE TITLE
 Deserialize JsonReaderException

### ISSUE THREAD

**Issue by hyperms** [JKorf/Binance.Net#918]
This error occurred in futures place order:

Deserialize JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0., Path: , LineNumber: 0, LinePosition: 0

**Comment by JKorf** [comment]
That might happens when there is an issue on the server.  If it serves back an html error page instead of actual json data this will be the error since the first character of an html page is `<` (`<html>`)

**Comment by Alxdhere** [comment]
I try to call GetMiningStatisticsAsync function or other mining functions with userName (my name: alxdhere), but always get an error like this:
2021.11.21 22:13:32:176 | Error | Binance    | [2] Deserialize JsonReaderException: Could not convert string to decimal: alxdhere. Path 'data.userName', line 1, position 222., Path: data.userName, LineNumber: 1, LinePosition: 222, data: [Data only available in Debug LogLevel]

My code:
`var tmp = await client.Mining.GetMiningStatisticsAsync(algorithm.AlgorithmName, userName).ConfigureAwait(false);`

But other mining functions, e.g. GetMiningAlgorithmListAsync, without userName is called successfully.
What's wrong with functions with userName?
Thanks.

**Comment by JKorf** [comment]
Does your username contain any special characters?

**Comment by Alxdhere** [comment]
I wrote that the username is the usual: alxdhere.

**Comment by JKorf** [comment]
You're right, my bad. I don't really understand the error message. The username is a string field in the model, so it makes no sense that it tries to parse to decimal. Are you still seeing this? If so, can you set LogLevel to LogLevel.Trace in the client options and check what the data is that is returned?

**Comment by Alxdhere** [comment]
I try to run code in VS 2019:
`
var tmp = await _client.Mining
                .GetMiningStatisticsAsync(algorithm.AlgorithmName, userName)
                .ConfigureAwait(false);
Console.WriteLine(tmp);
`
Variable tmp contain:
2022.01.14 15:20:35:176 | Error | Binance    | [2] Deserialize JsonReaderException: Could not convert string to decimal: alxdhere. Path 'data.userName', line 1, position 221., Path: data.userName, LineNumber: 1, LinePosition: 221, data: [Data only available in Debug LogLevel]

I don't know where to change Debug LogLevel in VS 2019.  I change in Tools-Options-Projects and Solutions-Build and Run options of MSBuild to Detailed, but has no effect.

**Comment by JKorf** [comment]
It's in the options for the client, in the code.
````C#
var client = new BinanceClient(new BinanceClientOptions{
  LogLevel = LogLevel.Trace
});
````
or before you create the client
````C#
BinanceClient.SetDefaultOptions(new BinanceClientOptions{
  LogLevel = LogLevel.Trace
});
````

**Comment by Alxdhere** [comment]
Wow! Cool!

Result:
2022.01.14 16:08:55:585 | Debug | Binance    | [2] Response received in 324ms: {"code":0,"msg":"","data":{"fifteenMinHashRate":"50666268913827","dayHashRate":"61729026142517","validNum":1,"invalidNum":0,"profitToday":{"BTC":"0.00013700"},"profitYesterday":{"BTC":"0.0003146"},"userName":"alxdhere","unit":"h/s","algo":"SHA256"}}
2022.01.14 16:08:55:615 | Error | Binance    | [2] Deserialize JsonReaderException: Could not convert string to decimal: alxdhere. Path 'data.userName', line 1, position 218. Path: data.userName, LineNumber: 1, LinePosition: 218, data: {
  "code": 0,
  "msg": "",
  "data": {
    "fifteenMinHashRate": "50666268913827",
    "dayHashRate": "61729026142517",
    "validNum": 1,
    "invalidNum": 0,
    "profitToday": {
      "BTC": "0.00013700"
    },
    "profitYesterday": {
      "BTC": "0.0003146"
    },
    "userName": "alxdhere",
    "unit": "h/s",
    "algo": "SHA256"
  }
}

**Comment by JKorf** [comment]
Great, thanks.  This issue has been fixed in the latest alpha version, which will be released soon.
