### ISSUE TITLE
Get24HPrices (or equivalent async method) missing from 7.2.5

### ISSUE THREAD

**Issue by dooferorg** [JKorf/Binance.Net#919]
I know this project likes to change things around quite a lot but it's a problem when methods disappear without any indication what to migrate to. Could there be some documentation when methods are removed/deprecated and what to do instead?

I use the Get24HPrices  method under the Spot.Market namespace. In 7.2.5 I am not seeing an equivalent method to move to. While most of the calls are easy to adapt to their Async equivalents I am not seeing where a suitable method for Get24HPrices  might be. i.e. something that returns a list of the Binance24HrPrice from the exchange - an object that is still there in the library.

Any hints would be appreciated, thank you.

**Comment by JKorf** [comment]
Hi,  I'm aware that the update documentation isn't great, I'm working on improving that for future releases. 
The method you're looking for has been renamed to `GetTickersAsync` to be more in line with other exchanges.

**Comment by dooferorg** [comment]
Ah, thank you so much for that. I'll give that a go and try to migrate again.

I do appreciate the work on the API client.
