### ISSUE TITLE
Fills from order reply should contains tradeId

### ISSUE THREAD

**Issue by NektoDron** [JKorf/Binance.Net#92]
Hi,

JSON message contains 'tradeId' for trades in message for PlaceOrder command.
For example:
"fills":[{"price":"0.03065500","qty":"0.02200000","commission":"0.00000067","commissionAsset":"BTC","tradeId":3383336}

But class BinanceOrderTrade doesn't have it.

**Comment by JKorf** [comment]
Hi, thanks for the report.
This should be fixed in the latest version.
