### ISSUE TITLE
SubscribeToPartialOrderBookUpdatesAsync problem

### ISSUE THREAD

**Issue by kiranmaya** [JKorf/Binance.Net#920]
**Describe the bug**
when passed pair symbols list count below 20 working fine and getting data, unable to get data when trying for more symbols > 200 pairs , also worked fine in older versions, used 6 months before version, now when I updated to the new version I'm no getting data stream. 
**To Reproduce**
Subscribe to more than 200 symbols for order book depth WebSockets update.
**Expected behavior**
Should get data any no of trade pairs to count. 

**Debug logging**
I haven't tried catching errors with these functions, don't know how to, sorry.

**Comment by JKorf** [comment]
Since that version the implementation has switched to use the live subscribing/unsubscribing functionality
https://binance-docs.github.io/apidocs/spot/en/#websocket-market-streams
It seems that Binance doesn't process subscribe requests larger than +- 4kb, see also #884

**Comment by kiranmaya** [comment]
working fine, by batches Method
`
            var pairs = TradePairs.SplitBy(100);
            foreach( var pairList in pairs )
            {
                StartWebsocketOrderBookForPairs(pairList);
            }
`
@JKorf Thanks for the help.
