### ISSUE TITLE
BinanceSocketClientOptions - looking for old reference

### ISSUE THREAD

**Issue by MikeCoderr** [JKorf/Binance.Net#921]
Hi there,
I have been using Binance.Net.6.13.6 in my development and production environments for some months now.

Now, after I upgraded to 7.25, all worked fine in my dev Visual Studio 2019 environment. Though, when I deployed, I get these errors:

Could not load type 'Binance.Net.Objects.BinanceSocketClientOptions' from assembly 'Binance.Net, Version=6.3.0.0, Culture=neutral, PublicKeyToken=null'

with this code: 
		var clientSocket = new BinanceSocketClient(new Binance.Net.Objects.BinanceSocketClientOptions
		{ 
			BaseAddressUsdtFutures = "wss://fstream-b.binance.com/"
		});
		
If I do not need to specify the BaseAddressUsdtFutures, like below, then all works fine:
	var clientSocket = new BinanceSocketClient();
	
So it seems like, the switch from BinanceSocketClientOptions from Binance.Net.Objects.Spot (where it is in 6.13.6) to Binance.Net.Objects (in the builds > 7.0) might have caused that error.

Any idea how this can be resolved or fixed?

Thanks
Mike

**Comment by JKorf** [comment]
This seems like a missmatch between Binance.Net and CryptoExchange.Net. Make sure you have the latest of both

**Comment by MikeCoderr** [comment]
Thanks for your reply.
3 things I tried:
1.) I have tried to replicate this in a new solution within a new project and just loaded the Binance.net 7.25. And it has CryptoExchange.net 4.2.8 as a dependency. Error persists.

2.) I also upgraded to 7.26 now, but same error occurs.

3.) I have also tried to replicate this in a new solution within a new project and just loaded the Binance.net 6.13.6. And it has CryptoExchange.net 4.2.8 as a dependency.  And I had to change the class: 
Binance.Net.Objects.Spot.BinanceSocketClientOptions instead of this: 
Binance.Net.Objects.BinanceSocketClientOptions
No error.

Does this help? Any other suggestion for me to try out? Where else could I try to find / look for this reference to Version 6.3?

**Comment by JKorf** [comment]
`Could not load type 'Binance.Net.Objects.BinanceSocketClientOptions' from assembly 'Binance.Net, Version=6.3.0.0, Culture=neutral, PublicKeyToken=null'` 
It's looking in assembly version 6.3, while it should be in 7.xx. There is still some issue with the versioning. I can't reproduce this issue in a clean solution

**Comment by MikeCoderr** [comment]
I found the issue, somewhere deep in the project, in a different folder, there was still an old version of Binance.net - and somehow somehow the exe was referring towards that. Once I delete that out of the folders, all went fine! Thanks for trying!
