### ISSUE TITLE
What's the best way to query sh!tcoin dominance?

### ISSUE THREAD

**Issue by orionflame** [JKorf/Binance.Net#923]
Hi,

I was thinking you can have a list of coins like SHIB DOGE etc and then see their dominance at a particular date. I assume there is still no way to get market cap from binance API. So no way to do this?

Thanks a lot in advance.

**Comment by JKorf** [comment]
There is actually an endpoint which returns market cap info, it's `client.General.GetProductsAsync`. Note that it's not an official API endpoint though. It's been scraped from the website, so it might stop working at some point.

**Comment by orionflame** [comment]
Thanks @JKorf this is very interesting!
