### ISSUE TITLE
PlaceOrderAsync method works on Windows. But on linux gives "Signature for this request is not valid".

### ISSUE THREAD

**Issue by AJCADamen** [JKorf/Binance.Net#925]
**Describe the bug**
When I call the placeorderasync method on windows it works fine. but from linux (raspberry pi) it gives a "Signature for this request is not valid" error. 

Error log:
![image](https://user-images.githubusercontent.com/47353259/140934123-4a00b4ed-debb-460f-82ed-981c85855ee5.png)

**Comment by JKorf** [comment]
I have it running on a raspberry pi as well, no issues here. Is your time configured correctly? What culture is it running?

**Comment by AJCADamen** [comment]
Thx for the quick response man. It was the time settings of the Pi. It works now. 

You guys do awesome work ;)
