### ISSUE TITLE
FuturesUsdt SubscribeToUserDataUpdatesAsync doesn't receive any update !

### ISSUE THREAD

**Issue by arsinteaalex** [JKorf/Binance.Net#927]
public async Task OrderUpdate(){

            var rez = await binance.client.FuturesUsdt.SubscribeToUserDataUpdatesAsync(binance.listenKeyResult.Result.Data,
                onLeverageUpdate =>
                {
                    Console.WriteLine(Newtonsoft.Json.JsonConvert.SerializeObject(onLeverageUpdate.Data, Newtonsoft.Json.Formatting.Indented));
                },
                onMarginUpdate =>
                {
                    Console.WriteLine(Newtonsoft.Json.JsonConvert.SerializeObject(onMarginUpdate.Data, Newtonsoft.Json.Formatting.Indented));
                },
                onAccountUpdate =>
                {
                    Console.WriteLine(Newtonsoft.Json.JsonConvert.SerializeObject(onAccountUpdate.Data, Newtonsoft.Json.Formatting.Indented));
                },
                onOrderUpdate =>
                {
                    Console.WriteLine(Newtonsoft.Json.JsonConvert.SerializeObject(onOrderUpdate.Data.UpdateData, Newtonsoft.Json.Formatting.Indented));
                },
                onListenKeyExpired =>
                {
                    Console.WriteLine(Newtonsoft.Json.JsonConvert.SerializeObject(onListenKeyExpired.Data, Newtonsoft.Json.Formatting.Indented));
                }
            );
            Console.WriteLine(rez.Success);
        }

**Comment by JKorf** [comment]
It should. Put the LogLevel to Trace in the client options and check the logs for more info on what's going on

**Comment by kedarnath97** [comment]
Same here, no update on futuresusdt even after putting log level to trace.

**Comment by kedarnath97** [comment]
ok, that was a silly mistake from me, had used the Spot listen key to subscribe to futuresusdt.

**Comment by JKorf** [comment]
I'm assuming this has been resolved
