### ISSUE TITLE
IBinanceMiniTick's BaseVolume and QuoteVolume properties...

### ISSUE THREAD

**Issue by hcanak** [JKorf/Binance.Net#929]
Hello,

IBinanceMiniTick BaseVolume and QuoteVolume properties. When you read the IBinanceMiniTick.BaseVolume it actualy gets the QuoteVolume of that asset. I think BaseVolume and QuoteVolume should change place. 
IBinanceTick also verifies me, that is;

IBinanceMiniTick.BaseVolume = IBinanceTick.QuoteVolume 
IBinanceMiniTick.QuoteVolume =IBinanceTick.BaseVolume 

Can you check wheather does it need to swap BaseVolume and QuoteVolume  in IBinanceMiniTick?

**Comment by JKorf** [comment]
On what API is this? Coin/Futures/Spot? With what call?

**Comment by hcanak** [comment]
Spot

**Comment by hcanak** [comment]
> On what API is this? Coin/Futures/Spot? With what call?

Spot

**Comment by hcanak** [comment]
in last version (8.0.6) _BaseVolume_ name changed to _Volume_ but same bug still exists.

**Comment by hcanak** [comment]
Thank you @JKorf my best regards.
