### ISSUE TITLE
3.1.8 freeze winform on UnsubscribeAllStreams

### ISSUE THREAD

**Issue by ksm2004** [JKorf/Binance.Net#93]
HI

Problem with latest version.
Fresh WinForms app, 4.7.1 NET framework. Binance.Net 3.1.8.
This code freeze the form on button click (UnsubscribeAllStreams)

`
namespace BinanceAPITest
{
    public partial class Form1 : Form
    {
        BinanceSocketClient BNB_SocketClient = new BinanceSocketClient();
        public Form1()
        {
            InitializeComponent();
        }
        private void Form1_Load(object sender, EventArgs e)
        {
            var successSymbols = BNB_SocketClient.SubscribeToAllSymbolTicker((data) =>
            {
                if (data != null)
                {
                    Console.WriteLine("Data");
                }
                else
                {
                    Console.WriteLine("no Data");

                }
            });

            successSymbols.Data.Error += (ex) =>
            {
                Console.WriteLine("BNB Socket error: " + ex.Message);
            };
        }

        private void button1_Click(object sender, EventArgs e)
        {
            BNB_SocketClient.UnsubscribeAllStreams();
        }
    }
}
`

**Comment by JKorf** [comment]
Hi, I found the issue, this will be resolved in the next release. For now you can change `BNB_SocketClient.UnsubscribeAllStreams();` to `Task.Run(() => BNB_SocketClient.UnsubscribeAllStreams());` and it should work as a temporary workaround.

**Comment by JKorf** [comment]
I just pushed a new version in which this issue should be fixed.
