### ISSUE TITLE
StopLossLimit order loses information on creation?

### ISSUE THREAD

**Issue by oathgg** [JKorf/Binance.Net#930]
I'm using the following code (custom wrapper for some logging) to post orders through the Binance.NET library:
```
public BinancePlacedOrder CreateOrder(string symbol, OrderSide side, OrderType type, decimal? quantity = null, decimal? quoteOrderQuantity = null, string? newClientOrderId = null, decimal? price = null, TimeInForce? timeInForce = TimeInForce.GoodTillCancel, decimal? stopPrice = null, decimal? icebergQty = null, OrderResponseType? orderResponseType = null, int? receiveWindow = null, int retryCount = 20)
{
	BinancePlacedOrder placedOrder = ParseWebCallResult(Client.Spot.Order.PlaceOrderAsync(symbol, side, type, quantity, quoteOrderQuantity, newClientOrderId, price, timeInForce, stopPrice, icebergQty, orderResponseType, receiveWindow));
	if (placedOrder != null)
	{
		string msg = $"[{placedOrder.Symbol}] -> Created {placedOrder.Type} {placedOrder.Side}, OrderId: {placedOrder.OrderId}, Price: {placedOrder.Price}";
		switch (placedOrder.Side)
		{
			case OrderSide.Sell:
				msg += $", Qty: {placedOrder.Quantity}";
				break;
			case OrderSide.Buy:
				msg += $", Quote: {placedOrder.Quantity * placedOrder.Price}";
				break;
		}
		Logger.LogDebug(msg);
	}

	return placedOrder;
}
```
When I create a sell or a buy limit order and it gets processed by the Binance API I receive the following output:
```[TRXUSDT] -> Created Limit Buy, OrderId: 1449196065, Price: 0.10335000, Quote: 11.9989350000000000```
This is expected behaviour.

When I create a sell or a buy StopLossLimit order I get the following output:
```[TRXUSDT] -> Created Limit Buy, OrderId: 1449228899, Price: 0, Quote: 0```
This is unexpected behaviour, shouldn't I get more information besides an OrderId just like I am getting with a limit order?
It also returns the type "limit buy" when its a stop loss limit sell order, this seems wrong as well?

I'm using the ``Client.Spot.Order.GetOrderAsync(symbol, orderId)`` as a work around to retrieve the Price and Quote information of the placed order, however, shouldn't this information return when I create a StopLossLimit order in the first place?

**Comment by JKorf** [comment]
Hi, I'm not too familiar with stop orders, but you can see what is returned from the server by turning on Trace logging in the client options: `LogLevel = LogLevel.Trace`. Can you check what the server returns and if it is mapped correctly?

**Comment by oathgg** [comment]
It seems there are 2 responses which are incoming when I place a StopLoss order:

```
{"symbol":"IDEXUSDT","orderId":xxx,"orderListId":-1,"clientOrderId":"xxx","transactTime":1637014924860}
{"symbol":"IDEXUSDT","orderId":xxx,"orderListId":-1,"clientOrderId":"xxx","price":"0.28807000","origQty":"42.60000000","executedQty":"0.00000000","cummulativeQuoteQty":"0.00000000","status":"NEW","timeInForce":"GTC","type":"STOP_LOSS_LIMIT","side":"BUY","stopPrice":"0.28782000","icebergQty":"0.00000000","time":1637014924860,"updateTime":1637014924860,"isWorking":false,"origQuoteOrderQty":"0.00000000"}
```

The first one is probably the one that gets parses, hence I receive an OrderId, but the second one is the actual Limit order that will get placed once the Stop price has been reached.

**Comment by oathgg** [comment]
Hi JKorf, it seems to be works as intended, the only JSON response I get is the following:
```
{"symbol":"UNIUSDT","orderId":1243347766,"orderListId":-1,"clientOrderId":"wOLvcGfhwNYNt8PCrbjMu6","transactTime":1637016763460}
CryptoExchange.Net.Objects.WebCallResult`1[Binance.Net.Objects.Spot.SpotData.BinancePlacedOrder]
```
I have included the type which is the line below, guess there is no other way to retrieve the data besides doing a second query for the order?

**Comment by JKorf** [comment]
No, that's all the info the API will return then. Have a look at the socket client so you can listen for events instead of having to query

**Comment by oathgg** [comment]
I have closed the issue as its working as intended. I'll try to look at a solution for my "problem". Thanks for the feedback.
