### ISSUE TITLE
PlaceOrderAsync doesn't place an order for selling

### ISSUE THREAD

**Issue by stonebirdarchitect** [JKorf/Binance.Net#931]
I've got a 
```
var callResult = Client.Spot.Order.PlaceOrderAsync(currency.Pair,
    OrderSide.Buy,
    OrderType.Market,
    quoteOrderQuantity: amount,
    newClientOrderId: request.Id.ToString());
```
that works perfectly. I'm providing it with info of how much I'd like to spend, the order is posted and everything's great. I've also got a SocketClient.Spot.SubscribeToUserDataUpdatesAsync elsewhere that reads orderUpdate in it (info is received correctly as well), and in there, when I've got information that orderUpdate is for purchase and its Status is Filled, I call 
```
var callResult = Client.Spot.Order.PlaceOrderAsync(orderUpdate.Data.Symbol,
    OrderSide.Sell,
    OrderType.Limit,
    quantity: tradableAmount,
    price: target,
    newClientOrderId: (request.Id + 1).ToString());
```
in an attempt to sell everything I've bought for a price I've calculated. Calculations to cut off untradable small amounts are not included, but they're also present in the code, and they give correct amounts - I can sell with these values by hand. 

callResult.IsCompleted and callResult.IsCompletedSuccessfully are both true after less than a second, however the sell order isn't being posted anyways. Any suggestions ?

**Comment by oathgg** [comment]
My limit sell orders are working fine, can you check if the callResult.Success is true?
Otherwise debug the webCallResult and check the values in ResponseStatusCode, Data and Error properties.

```
if (webCallResult != null && !webCallResult.Success)
{
    Logger.LogError($"{webCallResult.ResponseStatusCode} -> Data: {webCallResult.Data}, Error: {webCallResult.Error}");
}
```

**Comment by JKorf** [comment]
You're calling async methods without awaiting them. You'll either have to await them ( recommended ) or use the .Result of the call:
`var callResult = await Client.Spot.Order.PlaceOrderAsync`
or 
`var callResult = Client.Spot.Order.PlaceOrderAsync().Result`
