### ISSUE TITLE
Parameter(s) for new BinanceSocketClient(new Binance.Net.Objects.BinanceSocketClientOptions()

### ISSUE THREAD

**Issue by DuckShuffle** [JKorf/Binance.Net#932]
Hi Jan Korf,
This is my first C# app. My toolkit has always been VB.NET because C# seemed so intimidating to me until now, a real need to learn it.  W3Schools give me some level of confidence as most OOP concepts are transferable from VB.NET.
I’ve exhausted my options/guesses on how to get the following to return any data. I’ve searched the Open/Closed issues and found what appeared to be a solution but no avail. 

Could you please supply a working code snippet that returns a list of symbols and the current traded prices? This will serve as an example of what parameters to pass to BinanceSocketClient(new Binance.Net.Objects.BinanceSocketClientOptions().
LTC/BTC, 0.003658
AMP/USD, 0.05070
AXS/USDT, 129.34

Thank you in advance and forgive me if I am unaware or violated any online etiquettes. This is also my first time joining a community/blog.

Below is my best failed attempt...

using Binance.Net;

namespace WindowsCS
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();

            var client = new BinanceSocketClient(new Binance.Net.Objects.BinanceSocketClientOptions()
            {
                // Specify options for the client
                BaseAddressUsdtFutures="wss://fstream.binance.com"
            }) ;
            var subscribeResult = client.Spot.SubscribeToAllSymbolTickerUpdatesAsync(data => {
                // Handle data when it is received
                foreach (var result in subscribeResult.Result.Data)
                {
                    Console.WriteLine(result.Symbol);
                }

            });
            // Make sure to check if the subscritpion was successful
            if (!subscribeResult.Success)
            {
                // Subscription failed, check callResult.Error for more info
            }
            else
            {
                // Subscription succeeded, the handler will start receiving data when it is available
            }

        }
    }
}

**Comment by JKorf** [comment]
Hi, have you looked at the Examples folder in the repo? It contains a simple winforms sample project which displays the price on the screen

**Comment by DuckShuffle** [comment]
Thank you for your reply, Jan. I finally got it to stream what I needed with some struggles. The struggling part is a plus in helping to learn C#. I'll have a look at the repo now. My next challenge is getting balance info. Thank you for all you do for this community.
