### ISSUE TITLE
BinanceOrderBookEntry with quantity zero

### ISSUE THREAD

**Issue by xrth87** [JKorf/Binance.Net#934]
**Describe the bug**
The socket returns EventOrderbook with bids entries having quantity zero. Not sure if it is in line with expectations.

**To Reproduce**
BinanceSocketClient using SubscribeToOrderBookUpdatesAsync

**Expected behavior**
Should not every have a quantity larger than zero? Even if its only a small fraction. 

**Debug logging**
OrginalData is:
{"stream":"rlcbusd@depth","data":{"e":"depthUpdate","E":1637354002726,"s":"RLCBUSD","U":61903050,"u":61903052,"b":[["3.95900000","3.50000000"],["3.79100000","0.00000000"],["3.77400000","283.90000000"]],"a":[]}}

Or:

{"stream":"btcbusd@depth","data":{"e":"depthUpdate","E":1637354693759,"s":"BTCBUSD","U":7091235022,"u":7091235135,"b":[["57977.84000000","0.13603000"],["57976.43000000","0.00326000"],["57974.12000000","0.05825000"],["57970.53000000","0.04235000"],["57970.52000000","0.00000000"],["57970.51000000","0.10366000"],["57968.93000000","0.02032000"],["57968.76000000","0.00000000"],["57967.79000000","0.01494000"],["57967.78000000","0.03000000"],["57964.41000000","0.00000000"],["57963.73000000","0.00000000"],["57960.69000000","0.00000000"],["57960.68000000","0.00000000"],["57959.65000000","0.00787000"],["57959.64000000","0.08049000"],["57956.77000000","0.46370000"],["57955.35000000","0.00000000"],["57954.25000000","0.00000000"],["57953.68000000","0.03019000"],["57950.80000000","0.11398000"],["57950.21000000","0.20038000"],["57945.17000000","0.11000000"],["57939.10000000","0.00000000"],["57934.23000000","0.00000000"],["57933.23000000","0.00690000"],["57914.24000000","0.99012000"],["57903.95000000","0.00000000"],["57889.08000000","0.00000000"],["57874.27000000","1.00000000"],["57872.12000000","0.11000000"],["57830.85000000","0.10000000"],["57745.94000000","0.00034000"],["57548.26000000","0.21444000"]],"a":[["57977.85000000","0.30496000"],["57977.94000000","0.05174000"],["57983.48000000","0.00034000"],["57983.57000000","0.00000000"],["57984.97000000","0.07800000"],["57986.63000000","0.00000000"],["57987.69000000","0.00000000"],["57991.47000000","0.02143000"],["57996.14000000","0.04250000"],["57996.19000000","0.08126000"],["57999.22000000","0.03000000"],["57999.44000000","0.00747000"],["57999.45000000","0.10307000"],["57999.46000000","0.04470000"],["57999.99000000","0.00000000"],["58000.00000000","0.12910000"],["58003.15000000","0.00000000"],["58003.71000000","0.00000000"],["58008.30000000","0.00000000"],["58009.09000000","1.76090000"],["58009.96000000","0.00000000"],["58010.11000000","0.00000000"],["58014.35000000","0.00097000"],["58014.36000000","0.00000000"],["58015.21000000","0.00000000"],["58018.29000000","0.00000000"],["58021.83000000","0.43000000"],["58024.84000000","0.04313000"],["58028.00000000","0.01800000"],["58030.37000000","0.03599000"],["58030.91000000","0.00000000"],["58032.09000000","0.00000000"],["58032.84000000","0.11398000"],["58038.65000000","0.00000000"],["58046.86000000","0.00000000"],["58075.96000000","1.45601000"],["58084.57000000","0.00000000"],["58094.88000000","0.86000000"],["58112.36000000","1.00000000"],["58119.28000000","0.00000000"],["58127.67000000","0.00000000"],["58365.02000000","0.94450000"],["58802.77000000","0.00000000"]]}}

Is the OrginalData as it sent by Binance itself?

Can I make changes to Precision of the Quanity, when using BinanceSocketClient?

**Comment by xrth87** [comment]
I also tried using a python script [https://python-binance.readthedocs.io/en/latest/websockets.html](https://python-binance.readthedocs.io/en/latest/websockets.html). There I also received quantity zero.

**Comment by JKorf** [comment]
The OriginalData is indeed the data as received from the server before processing. The stream you're subscribing to is used to keep a locally synchronized order book, and the 0.0000000 entries are meant to tell you 'remove this entry from the order book'. Try the SubscribeToPartialOrderBookUpdatesAsync stream instead, it sends you the full order book each tick, though it limited to the top 5 / 10 / 20 levels.

**Comment by xrth87** [comment]
Thank you! 👍
