### ISSUE TITLE
-2010: Duplicate order sent.

### ISSUE THREAD

**Issue by stonebirdarchitect** [JKorf/Binance.Net#935]
I've been creating a fully automated program, that purchases a currency under certain conditions, and as soon as it's bought, it sells for a small profit. As in I've got BinanceSocketClient.Spot.SubscribeToUserDataUpdatesAsync() that handles Order events and if incoming order was filled and there is an entry in my list of this currency, it sends 

var call = await Client.Spot.Order.PlaceOrderAsync(orderUpdate.Data.Symbol,
			OrderSide.Sell,
			OrderType.Limit,
			quantity: tradableAmount,
			price: target,
			newClientOrderId: (2 * request.Id + 1).ToString(),
			timeInForce: TimeInForce.GoodTillCancel);
			
Sometimes, not often, this call fails with error "-2010: Duplicate order sent.", and I'm rather unsure what could be the reason for the issue, since order is most definitely isn't being sent multiple times - it triggers only when there's incoming order update of this specific currency that has status "Filled"... 
Any suggestions ? :)

**Comment by JKorf** [comment]
Could it be that your client order id is duplicated? As in, two different order with the same clientOrderId are sent? It needs to be a unique value.
