### ISSUE TITLE
client.FuturesUsdt test mode

### ISSUE THREAD

**Issue by nkarabulut** [JKorf/Binance.Net#937]
Hello,
I am using the futures api. But i need to do tests.

I found it on the spot. (client.Spot.Order.PlaceTestOrderAsync). Buy I can't find futures.
How can I (enable | use )test mode library.

Thanks.

**Comment by JKorf** [comment]
The futures API doesn't have that endpoint, which is why you can't find it. You could use the Binance test net if you don't want to place actual orders
