### ISSUE TITLE
Precision is over the maximum defined for this asset

### ISSUE THREAD

**Issue by prometheus82** [JKorf/Binance.Net#94]
I stumbled on a weird problem when selling coins.

1.-5. attempt
LTCUSDT	0.18772000	106.64000000	Precision is over the maximum defined for this asset.

6. attempt
LTCUSDT	0.18772000	106.64000000	No error.

Why is that happening?

**Comment by JKorf** [comment]
I have to say I don't know. Could you put LogVerbosity on Debug and see if the actual requests send are different when it fails or succeeds? If not then it's something weird on the Binance side.

**Comment by deewelop** [comment]
i have same problem :(

price = 90.22
qty = 0.2   //18$

client.FuturesUsdt.Order.PlaceOrder
(
    "LUNAUSDT",
    OrderSide.Buy,
    OrderType.Limit,
    qty,
    null,
    TimeInForce.GoodTillCancel,
    null,
    price 
);

then shows me error "Precision is over the maximum defined for this asset."
what's problem? little help pls? <3

**Comment by deewelop** [comment]
my guess, peobably in dll you will Multiplication and division or somthing like that on order size or price, and in that process it will create a lot of Precision in that value you are sending to binance...

or you are sending to binance exact values we are sending to dll? without any process?
idk, just help me fix it, its pain :(
