### ISSUE TITLE
GetSystemStatusAsync() returns 404

### ISSUE THREAD

**Issue by dooferorg** [JKorf/Binance.Net#940]
Not sure if this is a change/bug in the call or what it is but upgrading from the v6 API to v7 but GetSystemStatusAsync() gets a 404 response. I use the system status to determine if the exchange is operational or not. This used to return a BinanceSystemStatus object.

error:

`
{
  "timestamp": 1638295459128,
  "status": 404,
  "error": "Not Found",
  "message": "No message available",
  "path": "/sapi/v1/system/status"
}
`

**Comment by JKorf** [comment]
Seems to be working for me, at least in the latest alpha. Path also seems correct. If this is still not working for you, can you check the output logging when you set LogLevel to Trace in the client options?
