### ISSUE TITLE
Understanding Timestamp on the subscribed ticker updates.

### ISSUE THREAD

**Issue by kedarnath97** [JKorf/Binance.Net#942]
Hi JKorf,
I am subscribing to all ticker updates using BinanceSocketClient.Spot.SubscribeToBookTickerUpdatesAsync("BTCUSDT", SpotUpdatedEventHandler) and for futures USDT as well.

Could you please advise on 

1. whether we need to poll the heartbeat in case of all subscriptions we do?
2. I get timestamp with Spot updates, I suspect it is same as UTC if accessed on the same machine, could you please let me know on how do I get the timestamp of the update on the exchange?
3. there are 3 timestamps on futures USDT update Data.EventTime, Data.TransactionTime and Timestamp, could you please advise what these timestamps refer to?
4. If I set ReceiveWindow to 500ms, then all the data coming from socketclient will not be processed if the timestamp on the data recieved from exchange is 500ms older than current time?

Thank you,

Regards,
Kedar

**Comment by JKorf** [comment]
Hi,
1. No need to poll, the subscription will remain active and reconnect if it is disconnected.
2. All times used in the library and coming for the API are in UTC yes. I'm not sure I understand your question?
3. Data.EventTime = the timestamp of the event on the server, Data.TransactionTime = I'm not sure actually, Binance doesn't really specify, Timestamp = the timestamp of when the update was received on the client
4. ReceiveWindow is exculsively for the rest client and is a parameter for the server to validate the request. It has nothing to do with socket updates.

**Comment by kedarnath97** [comment]
Thank you Jan.

Regards,
Kedar
