### ISSUE TITLE
Visual studio C# Forms App

### ISSUE THREAD

**Issue by PietjePrecies** [JKorf/Binance.Net#943]
Hello everybody,

My knowledge of C# is not that great. I usually come a long with examples. Jan Korf has made a number of beautiful examples. Unfortunately not the one I'm looking for. I would like to create a C# Windows Forms App (I am most familiar with this) where I want to display the current price data of a coin in a textbox. I've tried to rewrite the console example but haven't succeeded so far. Could someone be so kind to help me on my way?

**Comment by PietjePrecies** [comment]
Hello,

As i said before i am not a c# programming expert. But i found a way to get symbol and price information about a token in a messagebox. This was made true the Binanceclient.  See code below.

private void button1_Click(object sender, EventArgs e)
        {
            var client = new BinanceClient(new BinanceClientOptions()
            {
                ApiCredentials = new ApiCredentials(key, secret)
            });
                var data = client.Spot.Market.GetPriceAsync("MANAUSDT");
                if (data.Result.Success)
                {
                    textBox1.Text = "symbol: " + data.Result.Data.Symbol;
                    textBox2.Text = "price: " + data.Result.Data.Price;
                    checkBox1.Checked = true;
                }
                else
                {
                    checkBox1.Checked = false;
                }
            
        }

Now i a searching to do the same with socketClient. I dont know how to handle data. Could anybody explain me a way to do this.

private void button3_Click(object sender, EventArgs e)
        {
            var socketClient = new BinanceSocketClient(new BinanceSocketClientOptions()
            {
                ApiCredentials = new ApiCredentials(key, secret)
            });

            var prices = socketClient.Spot.SubscribeToAllSymbolMiniTickerUpdatesAsync(data =>
            {
                //Handle data

            });
            if (!prices.Result.Success)
            {
                checkBox2.Checked = false;
            }
            else
            {
                checkBox2.Checked = true;
            }
        }

**Comment by PietjePrecies** [comment]
Hello,

I understand that I am only an amateur, yet I am sorry to see that after two weeks no one has been able to help me. Therefore I am closing this issue.

**Comment by voorhof** [comment]
@PietjePrecies,

Ik zie dat er al een tijdje geen activiteit is op je account,
mocht je interesse hebben de naam over te dragen, stuur me gerust een berichtje!

Grts,
