### ISSUE TITLE
-1121: Invalid symbol. While Cancelling Order

### ISSUE THREAD

**Issue by Kvariani** [JKorf/Binance.Net#945]
Hi.

I'M trying to cancel my existing order and when calling method client.FuturesCoin.Order.**CancelOrderAsync()** it returns error -  -1121: Invalid symbol.

orders which i want to cancel is from API too, using method - client.FuturesUsdt.Order.GetOpenOrdersAsync() .

the symbol is right, like "XRPUSDT", "GTCUSDT".

Can you help me? I don't know what is my mistake

**Comment by JKorf** [comment]
Can you provide logging of the request? Set LogLevel to Trace in the client options to see what is actually send to the server
