### ISSUE TITLE
Missing update about new filled order

### ISSUE THREAD

**Issue by fadenpendel** [JKorf/Binance.Net#947]
Helo Team!

Please help me, with proper documentation or any kind of advice.

I use BinanceSocketClient class and subscribe the Action - 

Action<DataEvent<BinanceStreamOrderUpdate>>? onOrderUpdateMessage

The Problem:

Most of the time the subscription works just fine. But sometimes, I miss at least one notification per a day about a filled order.

+ The KeepAlive runs every 30min - always with success result
+ ConnectionLost, ConnectionClosed, ConnectionRestored, ActivityPaused, ActivityUnpaused - did not fire anything -> assume success
+ After one missing order update the subscription continues working as expected.
+ PackageReference Include="Binance.Net" Version="7.2.6"
+ the average time span between filled orders is 20 Min.
+ Tried to work around this issue and performed a full socket reconnect every 24 hour - no success

**Comment by orionflame** [comment]
This happens to me too, that's why I added a discrepancy check at startup that shows me if I have more in my account vs what the app shows from the logs, or vice versa.

I use logs because otherwise I don't know if there is a way to figure out true realized and unrealized PNL from my holdings.

**Comment by fadenpendel** [comment]
orionflame, thank You for the response !

The good news is that I am not alone :-)
I 'll look now for a work around

**Comment by JKorf** [comment]
Hi, I haven't experienced this personally. If it's possible, could enable Trace logging for the socket client in the client options? This will generate a decent amount of logging depending on what subscriptions you have, but it would allow us to see if there was any data received which was not processed correctly by the client or if the data was not send from the server at all.

**Comment by fadenpendel** [comment]
JKorf, thanks for your contribution ! 

Meanwhile, I found out, that many updates about filled order are arrived correctly. They only were not handled within user code. :-)

Reason: (maybe of interrest for orionflame)

- Task<WebCallResult<BinancePlacedOrder>> PlaceOrderAsync(...) often fail. - But that's another story and is not a discussion of this topic.

For now, the problem still exist, but should be classified, in my opinion, as very minor, because of following test results:

- system run 30 days
- system gets 4283 of 4284 notifications about filled orders
- that's equal to 0.0002% losses

**Comment by mange-ess** [comment]
All, I also experienced this same issue just a moment ago, running version 8.0.3.

My app placed an order and it was filled, but the code handling order updates did not seem to execute. I am pretty sure this is not related to keepalive because I have own logging of failures to keep alive the stream.

@JKorf how would I enable the logging you mentioned in the client options (a few messages up)? Is it through the LogLevel and LogWrites properties on the socket client? Is there any example of this that you could provide? Any help would be greatly appreciated. :)

Best regards,

// Magnus
