### ISSUE TITLE
PartialFilled orders got tagged as Canceled

### ISSUE THREAD

**Issue by opiswahn** [JKorf/Binance.Net#95]
If there are PartialFilled orders that got canceled after beeing partial filled, they are tagged as 'canceld' if queried with 'GetMyTrades'

**Comment by JKorf** [comment]
Can look at the data returned by the server by putting LogVerbosity to Debug? If this also returns canceled for the trades then it's an issue on Binance server side.

**Comment by JKorf** [comment]
Going to assume this is on Binance side. Re-open if you have information suggesting otherwise.
