### ISSUE TITLE
Test spot and futures orders dont working

### ISSUE THREAD

**Issue by basarkavas** [JKorf/Binance.Net#951]
Hi,
when i call to 
        public static string URLTEST = "https://testnet.binancefuture.com";        
            var callResult = await client.Spot.Order.PlaceOrderAsync("BTCUSDT", OrderSide.Buy, OrderType.Market, quantity:100);

this code, resulted with message:
{404: {  "timestamp": 1640286232636,  "status": 404,  "error": "Not Found",  "message": "No message available",  "path": "/api/v3/order"} }

**Comment by JKorf** [comment]
Use `https://testnet.binance.vision`
