### ISSUE TITLE
How to create position for FuturesUsdt 

### ISSUE THREAD

**Issue by ecimen81** [JKorf/Binance.Net#956]
i want to  create position for FuturesUsdt  with leverage...
cant find any example how to create position..

**Comment by JKorf** [comment]
You can use PlaceOrder(Buy) for opening a position and close the position with PlaceOrder(Sell) on the FuturesUsdt api

**Comment by ecimen81** [comment]
thanks for reply but can set leverage... 

client.FuturesUsdt.Order.PlaceOrderAsync(symbol, OrderSide.Buy, OrderType.Market, quantity, null,TimeInForce.GoodTillExpiredOrCanceled, null, price, null,stopPrice, null, null, null, null, null, null);

theres no leverage option....

**Comment by ecimen81** [comment]
and another problem if i want to open short position,i will also use PlaceOrder(Sell) right?

**Comment by ecimen81** [comment]
> You can use PlaceOrder(Buy) for opening a position and close the position with PlaceOrder(Sell) on the FuturesUsdt api

possible to share one example to create open long and short position with leverage option?

**Comment by ecimen81** [comment]
thanks alot for helping i have managed to solve the problem by creating long ans short position.

**Comment by eragondr** [comment]
> thanks alot for helping i have managed to solve the problem by creating long ans short position.

How can you do that, i have the same proplem , that i can not set the leverage and isolated for the position
