### ISSUE TITLE
WebRequest Timeout

### ISSUE THREAD

**Issue by muratta** [JKorf/Binance.Net#961]
Hello 
Can anybody help me,please :(
i am running same code for 377 coins  to get last klines. but not works every time.  gives this error."| [8] Request timed out" 
now i tried the other pc, it works there. it works yesterday on my pc.
my nuget pages version is 7.2.6
my codes:
  using (var client = new BinanceClient())
            {

                var result = client.Spot.Market.GetKlinesAsync(t.CoinAdi, periyot, baslangic, DateTime.UtcNow, 1000).GetAwaiter().GetResult();
                if (result.Success)
                {
                    t.barlar = result.Data.Select(r => new Bar(r.Open, r.Close, r.High, r.Low, r.BaseVolume, r.OpenTime.ToLocalTime(), r.OpenTime.ToLocalTime())).ToList();

                }
                else
                    MessageBox.Show($"Error requesting data: {result.Error.Message} : {t.CoinAdi}", "error");
            }

**Comment by JKorf** [comment]
The requests time out. Generally this is a network issue. If you're trying to do this in parallel you might be trying to send too much requests in one go. Also, while using this approach with creating a new client every time you should provide an HttpClient in the default client options:
````C#
var binanceHttpClient = new HttpClient();
BinanceClient.SetDefaultOptions(new BinanceClientOptions(){
  HttpClient = binanceHttpClient
});
````
This prevents creating new connections for each client and reuses them instead.
