### ISSUE TITLE
How to handle Multiple Instances of a BinanceClient / more than one account

### ISSUE THREAD

**Issue by KomodoCrypto** [JKorf/Binance.Net#962]
I have my application working as expected using one binance account. Now I am testing it with two instances, completely independent between them, in order to trigger orders and subscribe events into two different binance accounts.
The problem that I am facing is that the Instance 1 is affected by the Instance 2.
So, If I run only the instance 1 it works fine. If I run instance 2 only, it works fine.
However, once instance 1 is running, if I start the instance 2, the instance 1 client is overwritten and receives the events and data for the client set in the instance 2.
So, How to handle more than one instance/binance account?
Is the API limited for just one client by IP or same machine? 

```
        private void InitBinanceAPI()
        {
            BinanceClient.SetDefaultOptions(new BinanceClientOptions()
            {
                ApiCredentials = new ApiCredentials(APIKEY, APISECRET),
            });
            BinanceSocketClient.SetDefaultOptions(new BinanceSocketClientOptions()
            {
                ApiCredentials = new ApiCredentials(APIKEY, APISECRET),
                AutoReconnect = true,
                ReconnectInterval = TimeSpan.FromSeconds(15),
            });
        }
```

**Comment by GLipitch** [comment]
```
var creds1 = new ApiCredentials("a key", "a secret");
var rest1 = new BinanceClient(new BinanceClientOptions { ApiCredentials=creds1  });
var socket1 = new BinanceSocketClient(new BinanceSocketClientOptions { ApiCredentials = creds1 });


var creds2 = new ApiCredentials("some other key", "and another secret");
var rest2 = new BinanceClient(new BinanceClientOptions { ApiCredentials = creds2 });
var socket2 = new BinanceSocketClient(new BinanceSocketClientOptions { ApiCredentials = creds2 });
```

**Comment by KomodoCrypto** [comment]
It works, thank you. Seems that, even different classes, the default parameters and options are shared. Thanks!
