### ISSUE TITLE
I'm really hopeless... I cannot even plase an order. 

### ISSUE THREAD

**Issue by AykutCanturk** [JKorf/Binance.Net#963]
As far I see placing order should be like this. 

Dim x As CryptoExchange.Net.Objects.WebCallResult(Of Futures.FuturesData.BinanceFuturesPlacedOrder) = Nothing
Await binance_client.FuturesUsdt.ChangeInitialLeverageAsync(coinname, 2) ' leverage X2

x = Await binance_client.FuturesUsdt.Order.PlaceOrderAsync(coinname, OrderSide.Buy, OrderType.Market,  coinamount, PositionSide.Long)

but.... I continiously get "Order's position side does not match user's setting." error even though hedge mode is off and binance_client.FuturesUsdt.GetPositionModeAsync() command shows one way.

I'm begging please, help me...

**Comment by JKorf** [comment]
Have you done this?
https://github.com/jaggedsoft/node-binance-api/issues/411#issuecomment-614790209

**Comment by AykutCanturk** [comment]
I removed positionside parameter and it worked. In this scope I dont understand that this parameter does but... anyways, I can place orders now. Thanks.

**Comment by phamthai** [comment]
I place an order as below, but Binance return errors. It works if I removed PositionSide.Long

var result = await futureOrderService.PlaceNewOrder(accountManger, futureTriggerOrder.Symbol,
                    orderSide, //Buy
                    orderType, // Market
                    quantity: quantity,
                    price: null,
                    PositionSide.Long,
                    ct: _cancellationToken);

Does anyone has any suggestion?
Thank you
