### ISSUE TITLE
MIN_NOTIONAL error when placing a market order

### ISSUE THREAD

**Issue by juliorgontijo** [JKorf/Binance.Net#964]
I am trying to place an order using the following code:

 var orderData = await client.Spot.Order.PlaceTestOrderAsync(
                "NEARETH",
                OrderSide.Sell,
                OrderType.Market,
                quantity: (decimal?)0.01);

However, I am getting a MIN_NOTIONAL error.  I google the web for quite some time, but the only information I could find is that for Market Order, there is no Notional price (as the Notional price is qty * order price).
Is there any missing parameter I should set ?

Thanks in advance!

**Comment by Kirill2Kirill** [comment]
As you say, you can calculate an minNot quantity with your formula. 
If it will be less than minNot value, this order will be rejected. 
I think that Binance make the same calculate on their server side, so you should increase quantity.

**Comment by JKorf** [comment]
The value of the order should still be > the min notional, even when you don't specify the price yourself.

**Comment by juliorgontijo** [comment]
Thank you very much. I have increased the quantity and it is working. Now I just have to find out how can I determine the min notional, but this should be another topic. Again, thank you all for your support.
