### ISSUE TITLE
SubscribeToUserDataUpdatesAsync 这个方法什么情况下有数据

### ISSUE THREAD

**Issue by ntluojianlin** [JKorf/Binance.Net#966]
private BinanceSocketClient _binanceSocketClient;
        private BinanceClient _binanceClient;
        private string _listenKey= string.Empty;
        private string ApiKey = "";
        private string Secret = "";

private void Form1_Load(object sender, EventArgs e)
        {
            Init();
            if (!string.IsNullOrEmpty(_listenKey))
            {
                Task.Run(GetUserDataAsync);
            }
        }

        public async Task Init()
        {
            BinanceClient.SetDefaultOptions(new BinanceClientOptions()
            {
                AutoTimestamp = false,
                ApiCredentials = new ApiCredentials(ApiKey, Secret)
            });
            BinanceSocketClient.SetDefaultOptions(new BinanceSocketClientOptions()
            {
                AutoReconnect = true,
                ReconnectInterval = TimeSpan.FromMinutes(1),
                ApiCredentials = new ApiCredentials(ApiKey, Secret)
            });
            _binanceSocketClient = new BinanceSocketClient();

            _binanceClient = new BinanceClient();

            var listenKeyResult = await _binanceClient.Spot.UserStream.StartUserStreamAsync();
            if (!listenKeyResult.Success)
            {
                richTextBox1.Invoke((EventHandler)delegate
                {
                    richTextBox1.Text = listenKeyResult.Error?.Message;
                });
            }
            else
            {
                richTextBox1.Invoke((EventHandler)delegate
                {
                    richTextBox1.Text = listenKeyResult.Data;
                });
                _listenKey = listenKeyResult.Data;
            }
        }

private async Task GetUserDataAsync()
        {
            var subscribeResult = await _binanceSocketClient.Spot.SubscribeToUserDataUpdatesAsync(_listenKey,
                orderData =>
                {
                    var data = orderData.Data;
                    richTextBox1.Invoke((EventHandler)delegate
                    {
                        richTextBox1.Text =data.OrderId+","+data.Type+","+data.Symbol+","+data.BuyerIsMaker+","+data.Price+","+data.Quantity+","+data.ExecutionType;
                    });
                }, orderList =>
                {
                    
                }, positionData =>
                {
                   
                }, balanceData =>
                {
                    
                });
            if (!subscribeResult.Success)
            {
                Console.WriteLine(subscribeResult.Error?.Message);
            }
            else
            {
                Console.WriteLine(@"Success");
            }

        }
运行之后，listenkey已取到，但是没啥数据推送过来，充值、下单也没啥动静？为什么？

**Comment by JKorf** [comment]
English please
