### ISSUE TITLE
Can't get all data from FuturesUsdt.SubscribeToAllSymbolTickerUpdatesAsync

### ISSUE THREAD

**Issue by step1985** [JKorf/Binance.Net#967]
I have one very big problem. Please help me.
I need to get AskPrice and BidPrice from  FuturesUsdt.SubscribeToAllSymbolTickerUpdatesAsync. When I call it I receive lot's of different data but AskPrice and BidPrice are default (0).
![b1](https://user-images.githubusercontent.com/35550840/148662698-3ab5209b-42bd-45c8-81cf-a1c4eb88b8e3.jpg)
But when I call Spot.SubscribeToAllSymbolTickerUpdatesAsync they are correct.
![b2](https://user-images.githubusercontent.com/35550840/148662812-224afa00-1be3-4731-a42d-3567eb7eb6c3.jpg)

**Comment by JKorf** [comment]
Hi, looks like the futures ticker doesn't include the best bid/ask price:
https://binance-docs.github.io/apidocs/futures/en/#individual-symbol-ticker-streams
