### ISSUE TITLE
Missing endpoint "withdraw/lockedData"

### ISSUE THREAD

**Issue by masherak** [JKorf/Binance.Net#969]
Hello @JKorf ,

First of all I would like to thank you for a great library. 

Please, is it possible to implement "/bapi/capital/v3/private/capital/withdraw/lockedData" endpoint? 

In exchange for sponsorship?

Thank you very much

Jarda

**Comment by masherak** [comment]
Hi, 

It looks like this endpoint is internal just for UI, sorry. But I solved it via deposit history endpoint where is field "ConfirmationsForUnlock" and together with information from specific blockchain about confirmations I can get the actual locked amount.

Anyway, I became your sponsor for a great job. 

I plan to use more your libraries, after a while I will increase the sponsorship tier.


Thank you!

Jarda

**Comment by JKorf** [comment]
I see. Thanks for the sponsorship, appreciate it. Let me know if you have any other issues or requests.
