### ISSUE TITLE
Subscribing to Websocket - Error not raised to client

### ISSUE THREAD

**Issue by habeebmatrix** [JKorf/Binance.Net#97]
As from your sample,

```
var successAccount = socketClient.SubscribeToUserStream(listenKey, data =>
{
    Console.WriteLine($"{DateTime.Now.ToLongTimeString()} : A/c info: {data.Event}");
},
data =>
{
    MyFunction(data);
});
```
The above code is in Main Method.
After sometime, the library throws error. but it is not caught in the client code.
Below is the error.
Any idea why this happens and also how this error can be cause in client program code and re subscribe to UserStream?

> Socket error Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by JKorf** [comment]
Hi, can you turn on debug logging by passing it in the client options like so:
````C#
socketClient = new BinanceSocketClient(new BinanceSocketClientOptions(){
    LogVerbosity = LogVerbosity.Debug
})
{

}
````

If you get that error again can you paste the logging of that moment here?

**Comment by Ofiraf** [comment]
Getting the same issue, websocket connection just drop with no warning

**Comment by habeebmatrix** [comment]
Hi @JKorf , Please find the error below:

10:45:23:105 | Error | Socket error Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
10:45:23:118 | Debug | Socket closed

**Comment by JKorf** [comment]
Hi, based on the debug message you appear to be using a pretty old version. Can you update to the latest version and let me know if this still is an issue? If it is please provide the debug logging from the new version

**Comment by JKorf** [comment]
If the issue still exists in the latest version of the library please re-open and provide new debug logging.

**Comment by habeebmatrix** [comment]
HI @JKorf , the issue is not happening any more. It was after getting the latest version + the logic for reconnecting every time the listenkey changes.
