### ISSUE TITLE
Withdraw from Funding Wallet

### ISSUE THREAD

**Issue by gcapitalteam** [JKorf/Binance.Net#970]
Per Binance API document, they support walletType 
https://binance-docs.github.io/apidocs/spot/en/#withdraw-user_data

Could you please add this option onto the WithdrawAsync function?

**Comment by HypsyNZ** [comment]
`https://github.com/JKorf/Binance.Net/blob/master/Binance.Net/Enums/AccountType.cs`

**Comment by JKorf** [comment]
Has been added
