### ISSUE TITLE
how can we open limit order with take profit and stop loss prices  in futures 

### ISSUE THREAD

**Issue by basarkavas** [JKorf/Binance.Net#972]

**Comment by HypsyNZ** [comment]
Can you be more specific

**Comment by basarkavas** [comment]
sorry, it not the same thing, because i want to bind my limit order with this take profit order, you can do this on user interface,
![TP](https://user-images.githubusercontent.com/6178844/159034050-3ca5067c-72f4-4496-9c64-98e2cb012b93.png)
You can see on attachment, maybe it is more clear, if you have more questions, i can tell more
