### ISSUE TITLE
SubscribeToTradeUpdatesAsync

### ISSUE THREAD

**Issue by Kirill2Kirill** [JKorf/Binance.Net#974]
**Describe the bug**
Subscription is not happening, when i use IEnumerable<string> symbols (not one symbol, but collection of symbols) in SubscribeToTradeUpdatesAsync(); When i use one individeul symbol its fine;

**To Reproduce**
SubscribeToTradeUpdatesAsync()

**Expected behavior**
Another subscribtions methods (which im using) working fine with the same instuctions.

**Comment by Kirill2Kirill** [comment]
This is my error.
It`s happening only when i try to sybscribe to a lot of symbols.
When i subs to one symbol everything is ok.

![image](https://user-images.githubusercontent.com/72548730/151614254-ef2315fd-5454-42ef-87e1-0e76f436b46c.png)

**Comment by JKorf** [comment]
Are you using a large amount of symbols at once? I know there is an issue where if you send too much data in a request the server ignores it

**Comment by Kirill2Kirill** [comment]
> Are you using a large amount of symbols at once? I know there is an issue where if you send too much data in a request the server ignores it

Thanx. This is the answer.
But its still fantastic. Because im using the same count of symbols for another subscribtions and everything is ok. 
This is some kinh of weight? You think it could be calculated?

**Comment by JKorf** [comment]
If I remember correctly the server will cut of any message larger than +- 4096 bytes. Depending on the length of your symbol names it might vary a bit. Have a look at the trace logging to see what is sent to the server

**Comment by cicaglisa80** [comment]
Hi guys I'm having the same problem does it mean we have to subscribe multiple times to do it across let's say 200 coins? I keep getting this error since yesterday before that I used to be able to do it all at once even with 500 coins at the time

**Comment by JKorf** [comment]
I'm not aware of any change since yesterday. There was someone saying it helped upping the  SocketResponseTimeout #1003. There has been a peak in usage on the exchanges the last few days which impact performance. Could be that the server is more busy now and takes longer to respond. But again I don't know if this is the issue you're seeing.

**Comment by JKorf** [comment]
I've been looking into this, see #1017 
There is some weird behavior on the binance socket server which I'm investigating
