### ISSUE TITLE
Is there an endpoint to place multiple orders? 

### ISSUE THREAD

**Issue by poorya-nlo** [JKorf/Binance.Net#975]
As the title says i couldnt find any info about it. And it  seems like binance doesnt have an enpoint for this. Which would be very odd. Seeing that this would be on of the easiest ways to reduce api calls.

ps

I am talking about spot orders

**Comment by JKorf** [comment]
Hi, no there is no such endpoint for the spot API, placing multiple orders in once call is only supported on the futures API
