### ISSUE TITLE
User Data Stream Subscription in Margin Account

### ISSUE THREAD

**Issue by hcanak** [JKorf/Binance.Net#976]
Can anyone show how to subscribe to following updates in **margin** account?

1. Payload: Account Update
2. Payload: Balance Update
3. Payload: Order Update

**Comment by HypsyNZ** [comment]
https://github.com/HypsyNZ/BinanceTrader.NET/blob/8d8e2db9bf8e7e628724b2fe390eaa67fbdd83b6/ViewModels/MainViewModel.cs#L783

https://github.com/HypsyNZ/BinanceTrader.NET/blob/8d8e2db9bf8e7e628724b2fe390eaa67fbdd83b6/ViewModels/MainViewModel.cs#L1698

https://github.com/HypsyNZ/BinanceTrader.NET/blob/8d8e2db9bf8e7e628724b2fe390eaa67fbdd83b6/ViewModels/MainViewModel.cs#L1727

https://github.com/HypsyNZ/BinanceTrader.NET/blob/8d8e2db9bf8e7e628724b2fe390eaa67fbdd83b6/ViewModels/MainViewModel.cs#L1762

**Comment by hcanak** [comment]
Can you show it in example please? 

For example in spot account subcribing the updates is as easy as calling one line code:
.SpotStreams.SubscribeToUserDataUpdatesAsync(...                                       
 
i need the the corresponding updates for margin account. i guess there should be a method named".SpotStreams.SubscribeToMARGINUserDataUpdatesAsync" .

**Comment by HypsyNZ** [comment]
> i need the the corresponding updates for margin account. i guess there should be a method named".SpotStreams.SubscribeToMARGINUserDataUpdatesAsync" .

if you are using v8 then `SpotStreams.SubscribeToUserDataUpdatesAsync(` is also for margin streams

**Comment by hcanak** [comment]
i am using v8. 0.6
spot account user data updates trigger but margin account user data updates do NOT trigger.
if _SpotStreams.SubscribeToUserDataUpdatesAsync(_ is also for margin streams then why do we need and where to use the following methods?
-StartIsolatedMarginUserStreamAsync
-StartMarginUserStreamAsync
-StopMarginUserStreamAsync
-KeepAliveIsolatedMarginUserStreamAsync
-KeepAliveMarginUserStreamAsync

**Comment by HypsyNZ** [comment]
> i am using v8. 0.6 spot account user data updates trigger but margin account user data updates do NOT trigger.

I have this same issue with v8 and can't figure out why, I use a customized version of v7,

Its upsetting to see another person with this same issue.

**Comment by JKorf** [comment]
The `SubscribeToUserDataUpdatesAsync` is just the data handler, and can provide data for either Spot, Margin or Isolated margin updates. You can determine what updates to receive by what listenKey you provide in the `SubscribeToUserDataUpdatesAsync`.
If you want to receive normal spot updates, you start the stream like this (omitted error checking for brevity):
````csharp
var listenKeyResult = await binanceClient.SpotApi.Account.StartUserStreamAsync();
var subscriptionResult = await binanceSocketClient.SpotStreams.SubscribeToUserDataUpdatesAsync(listenKeyResult.Data, xxx);
````
If you want to receive margin updates, you'd start it like this:
````csharp
var listenKeyResult = await binanceClient.SpotApi.Account.StartMarginUserStreamAsync();
var subscriptionResult = await binanceSocketClient.SpotStreams.SubscribeToUserDataUpdatesAsync(listenKeyResult.Data, xxx);
````

Hope this clears things up a bit

**Comment by HypsyNZ** [comment]
Yeah sadly that isn't the problem for me I already found `StartMarginUserStreamAsync`

Hopefully it helps @hcanak  though.

**Comment by hcanak** [comment]
That works:) Thank you @HypsyNZ @JKorf 
The key point that i missed is you have to supply different listenkey for _SubscribeToUserDataUpdatesAsync
You can receive both spot and margin updates with following code:

```
var listenKeySpotResult = await binanceClient.SpotApi.Account.StartUserStreamAsync();
var subscriptionResult = await binanceSocketClient.SpotStreams.SubscribeToUserDataUpdatesAsync(listenKeySpotResult.Data, xxx);

var listenKeyMarginResult = await binanceClient.SpotApi.Account.StartMarginUserStreamAsync();
var subscriptionResult = await binanceSocketClient.SpotStreams.SubscribeToUserDataUpdatesAsync(listenKeyMarginResult.Data, yyy);
```

**Comment by hcanak** [comment]
In order to receive isolated margin pair user data updates you have to register each pair with the above codes. Well, is there anyway to receive  user data updates for all isolated margin pair with single registeration? I asked this question to binance api team, they said "use combined stream". Here;
https://dev.binance.vision/t/listen-key-isolated-margin-why-symbol-parameter-is-mandotary/9745

Can anyone show how to use combined stream in this library? Thank you...

**Comment by ng-designs** [comment]
@hcanak 
try this
```
var symbols = new List<string>{ "BTCUSDT","ETHUSDT" };
var listenKeys = new List<string>();

foreach(var sym in symbols){
    listenKeys.Add( BinanceClient.SpotApi.Account.StartIsolatedMarginUserStreamAsync(sym).Result.Data );
}

BinanceSocketClient.ClientOptions.SocketSubscriptionsCombineTarget = listenKeys.Lenght;

string key = listenKeys[0];

for(int i = 1; i < listenKeys.Lenght; i++){
    key.AppendPath(listenKeys[i]);
}

BinanceSocketClient.SpotStreams.SubscribeToUserDataUpdatesAsync( key,
...
);
```

**Comment by hcanak** [comment]
@ng-designs Hi,

Can you check following code i made textual correction;

```
BinanceSocketClient.ClientOptions.SocketSubscriptionsCombineTarget = listenKeys.count;

string key = listenKeys[0];

for(int i = 1; i < listenKeys.count; i++){
    key+=listenKeys[i];
}
```


And can you show how to use KeepAliveIsolatedMarginUserStreamAsync method? Thanks.

**Comment by ng-designs** [comment]
@hcanak
As i understand for combined stream by `SubscribeToUserDataUpdatesAsync()` method, "key" parameter needs to be concatenated listenKeys separeted by "/", i.e. "listenKey1/listenKey2/listenKey3.....etc. You may use `String.AppenPath(listenKeys[i])` or `key+= $"/{listenKeys[i]}"` for it.

this another example how to usefull symbols and keys collection
```
            var symbolsAndListenKeys = new Dictionary<string, string>();
            var assets = _restClient.SpotApi.Account.GetIsolatedMarginAccountAsync().Result.Data.Assets;
            string combinedKeys = ""; // if this wont work, try -> string combinedKeys = "?streams="
            foreach(var asset in assets ) {
                if( asset.TradeEnabled && asset.Enabled ) {
                    symbolsAndListenKeys.Add( asset.Symbol, null );
                    symbolsAndListenKeys[asset.Symbol] = _restClient.SpotApi.Account.StartIsolatedMarginUserStreamAsync( asset.Symbol ).Result.Data;
                    combinedKeys += symbolsAndListenKeys[asset.Symbol] != null && symbolsAndListenKeys[asset.Symbol] != "" ? $"{symbolsAndListenKeys[asset.Symbol]}" : null;
                }
            }

            BinanceSocketClient.SpotStreams.SubscribeToUserDataUpdatesAsync( combinedKeys,
            ...
            );
```

here is an example for [keepAlive](https://github.com/JKorf/Binance.Net/issues/550#issuecomment-765301048) implementation
```
...
foreach( var symbol in symbolsAndListenKeys )
                _restClient.SpotApi.Account.KeepAliveIsolatedMarginUserStreamAsync( symbol.Key, symbol.Value );
...
```

**Comment by hcanak** [comment]
Combined streams are a bit complicated. 
For now it is best to deal it at the end of project.
