### ISSUE TITLE
-1116: Invalid orderType.

### ISSUE THREAD

**Issue by emin-karadag** [JKorf/Binance.Net#978]
Hello,
I am using Binance.Net **8.0.0-beta2**. In this version, the OrderType value set when sending the USDT Futures order has been changed to FuturesOrderType. Probably because of this `-1116: Invalid orderType`. i am getting error. I can't send orders of type "Market". _I didn't get the other types._
I reverted to version **8.0.0-beta1** and it's working now.
Thanks.

**Comment by JKorf** [comment]
Thanks for the report. You're right, there was a small issue there, should be fixed in beta3
