### ISSUE TITLE
WPF issues with API key

### ISSUE THREAD

**Issue by bonesmasher** [JKorf/Binance.Net#979]
I'm using binance.us and I'm trying to get the WPF app going. Framework is 4.8, changed my defaults to binance.us for Websockets and RESTapi. The console app works fine, but when I try to launch the WPF and select a coin - I get 'Error starting user stream: Invalid API-key, IP, or permissions for action.'. I'm using the test api key generated via testnet.vision.binance - I have tried using my personal API key from binance.us - but I'm really struggling to figure this out.

**Comment by HypsyNZ** [comment]
> I'm using binance.us and I'm trying to get the WPF app going. Framework is 4.8, changed my defaults to binance.us for Websockets and RESTapi. The console app works fine, but when I try to launch the WPF and select a coin - I get 'Error starting user stream: Invalid API-key, IP, or permissions for action.'. I'm using the test api key generated via testnet.vision.binance - I have tried using my personal API key from binance.us - but I'm really struggling to figure this out.

You should be able to fix whatever issue you are having with the WPF example by looking at this

https://github.com/HypsyNZ/BinanceTrader.NET

@JKorf  can you add this to the examples or something maybe
