### ISSUE TITLE
LOT_SIZE || MARKET LOT_SIZE 

### ISSUE THREAD

**Issue by kamranhuseyns** [JKorf/Binance.Net#981]
Hello. Now when I look at the codes, it is set to (TradeRulesBehaviour.None) by default, and in this case, the part of the mathematical formula does not work when (LOT_SIZE) is not true. What is the reason why (TradeRulesBehaviour) defaults to None? Thanks.
![2022-02-01_122211](https://user-images.githubusercontent.com/63323757/151946772-aaf1253d-ab43-4777-9d51-888cb5f84faa.png)
![2022-02-01_121754](https://user-images.githubusercontent.com/63323757/151946779-ae6213db-1df2-41c5-8a40-41edb74b2102.png)

**Comment by JKorf** [comment]
You can configure this in the client options by setting the `TradeRulesBehaviour` setting. The reason it is `None` by default is because it alters the quantity/price sent to the server. In my opinion the input should not be altered without explicit consent from the user.

**Comment by kamranhuseyns** [comment]
Thx
