### ISSUE TITLE
GetExchangeInfoAsync() API server time != than GetServerTimeAsync() API ?

### ISSUE THREAD

**Issue by pepoon** [JKorf/Binance.Net#984]
var serverTimeResult = Client.FuturesUsdt.System.GetServerTimeAsync().Result;
   var eiResult = Client.FuturesUsdt.System.GetExchangeInfoAsync().Result;

var serverTime2 = data.ServerTime;
var serverTime = serverTimeResult.Data.Date;

These 2 are different by days!
Don't know if it is an issue or not.

Thanks

**Comment by HypsyNZ** [comment]
`client.Spot.System.GetServerTimeAsync(true)`

**Comment by JKorf** [comment]
Huh interesting. The API docs also say `// Ignore please. If you want to check current server time, please check via "GET /fapi/v1/time"` for the server time property on the GetExchangeInfoAsync call. So not sure why that wouldn't match the server time. 
Anyway, not fixable on the client side.

**Comment by pepoon** [comment]
Aha! That's why. Thank you so much.
