### ISSUE TITLE
Version 8.0.0 About

### ISSUE THREAD

**Issue by MatrixYusuf** [JKorf/Binance.Net#987]
Hi. I was using version 7.2. I got the 8.0.0.0 beta6 API update. but client.Spot.Market.GetPricesAsync, await client.General.GetAccountInfoAsync(); Definitions such as are not available in the new version. Have these changed?

**Comment by Nillth** [comment]
Yes,
as detailed in the [Client-Structure](https://github.com/JKorf/Binance.Net/wiki/MigrationGuide#client-structure) section of the  [Migration Guide](https://github.com/JKorf/Binance.Net/wiki/MigrationGuide)
there are a couple of tables with the v7 vs v8 methods.
client.SpotApi.ExchangeData.GetPricesAsync() & client.SpotApi.Account.GetAccountInfoAsync()

**Comment by MatrixYusuf** [comment]
thank's you
