### ISSUE TITLE
Binance test server

### ISSUE THREAD

**Issue by Papercut110** [JKorf/Binance.Net#989]
Tell me please, is it possible to set up a connection to the Binance test server?

**Comment by JKorf** [comment]
Yes, set it in the client options:
`BaseAddress = BinanceApiAddresses.TestNet`

**Comment by Papercut110** [comment]
huge thank

**Comment by R00iBaard** [comment]
Hey, sorry to reopen this. However BinanceClientOptions() doesn't contain a BaseAddress property?
![image](https://user-images.githubusercontent.com/11412240/206980227-aa95bf7f-c0cb-4aeb-93f8-cec91a014f12.png)

**Comment by JKorf** [comment]
It's in the SpotApiOptions / UsdFuturesApiOptions

**Comment by R00iBaard** [comment]
> 

Thanks! Can now get current price. However, It looks like 'get current balance' doesnt work on test - think related to /sapi not being supported within test? 

![image](https://user-images.githubusercontent.com/11412240/208885475-44780159-fb57-4f8e-b3be-3a10c207a5aa.png)
