### ISSUE TITLE
BinanceSpotSymbolOrderBook NOT WORK with 7.2 version

### ISSUE THREAD

**Issue by heavymanto** [JKorf/Binance.Net#990]
**Describe the bug**
Test example code https://github.com/JKorf/CryptoExchange.Net/wiki/Orderbooks in my project it raise "can't connect to server" exception.  

**To Reproduce**
I have download Binance.Net project 6.13 and 7.2 version and test in BinanceNetTest class. The 6.13 version work but 7.2 not work and raise the same exception of my project. What wrong? Is a regretion?

7.2 version

![image](https://user-images.githubusercontent.com/6449169/152997421-38605667-b63d-4730-b5e3-d91577e70d8a.png)

6.13 version
![image](https://user-images.githubusercontent.com/6449169/152997462-5d4c6624-4452-48c3-84cf-f3a2c7241faf.png)

**Comment by JKorf** [comment]
It works fine for me. The difference between v6 and v7 is that the socket implementation has been replaced, so there could be something with that.
If you change the book constructor to this, what is the output in V7?
````C#
var book = new BinanceSpotSymbolOrderBook("BTCUSDT", new BinanceOrderBookOptions
{
    SocketClient = new BinanceSocketClient(new BinanceSocketClientOptions
    {
        LogLevel = LogLevel.Trace
    }),
    LogLevel = LogLevel.Trace
});
````

**Comment by JKorf** [comment]
Where do you get the exception? 
It seems like status code 407 is returned, which would mean proxy credentials are required. Are you using a proxy?

**Comment by heavymanto** [comment]
no, not use proxy, with vertion 6.13 it work fine whitout API credential but, I must use API Key credential in vertion 7?

**Comment by JKorf** [comment]
Again, it works fine for me. I tried with the zip you referenced, on two different computers. Only thing I couldn't change atm is the network. Did you test on another network?

**Comment by heavymanto** [comment]
Ok, i have test with 2 different network, another local network, and my phone hotspot but the result are the same, with 6.x work, with 7.x not work. How can i help you to find problem? 

Phone hotspot test
![image](https://user-images.githubusercontent.com/6449169/154057023-9a0f14e3-ed46-4f8b-8dfa-057f33ee3a57.png)
![image](https://user-images.githubusercontent.com/6449169/154057056-5aaf5659-7353-4ef9-b06c-e3a27e4e0811.png)

Another local network
![image](https://user-images.githubusercontent.com/6449169/154057123-048d9d9c-1257-4a92-8471-38ea0a1880ba.png)
![image](https://user-images.githubusercontent.com/6449169/154057149-0da856aa-cbdc-4a67-a1bf-5abe00b27c37.png)

**Comment by heavymanto** [comment]
I would like downgrade to 6.x in my project but there in a package reference discrepancy because the reference of 6.x package is declarated  CryptoExchnage.net MIN 3.9 but really is MAX this vertion. When I run it said not implemented method

![image](https://user-images.githubusercontent.com/6449169/154059333-085bb0f9-1fe9-4860-b15b-b0685fa1abdf.png)

Can i force change dependency?
![image](https://user-images.githubusercontent.com/6449169/154059409-fe9cad3f-9086-4e21-a5d6-b6cbf50bf3aa.png)

**Comment by heavymanto** [comment]
I have update to release 8.0.3 and change error in 

![image](https://user-images.githubusercontent.com/6449169/155845937-b219b8c5-1fdf-4a99-a5e6-f895e9b62cfb.png)
