### ISSUE TITLE
-1022: Signature for this request is not valid.

### ISSUE THREAD

**Issue by ceonqv** [JKorf/Binance.Net#992]
Iam try to use GetBalanceAsync but the response said:
Any kind of GetBalanceAsync have the same error 
-Client.FuturesUsdt.Account.GetBalanceAsync()
-Client.FuturesUsdt.Account.GetAccountInfoAsync()
-Client.General.GetAccountInfoAsync()
 
Error :
Sending GET signed request to https://fapi.binance.com/fapi/v2/balance?timestamp=1644522742096&recvWindow=5000&signature=AA22C74D1E8B3EE3BC88802464E48F79A0AE82CD51718FF00805361D843B5F1A
2022/02/11 02:52:23:649 | Debug | Binance    | [3] Error received: {"code":-1022,"msg":"Signature for this request is not valid."}
-1022: Signature for this request is not valid.

**Comment by ceonqv** [comment]
I dont get what you mean ?
![image](https://user-images.githubusercontent.com/89921865/153557476-8049aaf1-3b0b-4a7a-9716-df53e091389d.png)
what is the problem of my code :))). maybe my syntax is not correct ?
I use :
  var client = new BinanceClient(new BinanceClientOptions()
            {
                ApiCredentials = new ApiCredentials(API, key),
                LogLevel = LogLevel.Debug,
                LogWriters = new List<ILogger> { new ConsoleLogger() }
            });
            BinanceSocketClient.SetDefaultOptions(new BinanceSocketClientOptions()
            {
                ApiCredentials = new ApiCredentials(API, key),
                LogLevel = LogLevel.Debug,
                //  LogWriters = new List<ILogger> { new ConsoleLogger() }
            });
            var a = client.FuturesUsdt.Account.GetBalanceAsync();
            Console.WriteLine(a.Result.Error);
            Console.ReadLine();

**Comment by JKorf** [comment]
Seems fine, make sure you're API key and secret are correct
