### ISSUE TITLE
ComonOpen or Open

### ISSUE THREAD

**Issue by salmasi** [JKorf/Binance.Net#999]
hi 
this post isn't bug but i cant find any where to ask question
first i search https://binance-docs.github.io and https://jkorf.github.io/Binance.Net/ but i cant found any desc about it
what is difference between Open,Close,High,Low properties with CommonOpen,CommonClose,CommonHigh,CommonLow properties in IBinanceStreamKlineData object?
i cant find any common data in binance orginal data
thanks

**Comment by JKorf** [comment]
The Common properties we're used for usage by a `common interface` for multiple exchanges. This has been changed in the latest version though. Just use the properties without Common prefix.
